unpackaged/main/default/objects/GC_Design_Element__c/GC_Design_Element__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Element Task Custom Object.</description>
    <label>Design Element Task</label>
    <nameField>
        <displayFormat>DE-{0000000}</displayFormat>
        <label>Design Element Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Element Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Is_Revision__c.field-meta.xml
<CustomField>
    <fullName>Is_Revision__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag that is set if Design Element Task was created by revising a previous DET</description>
    <label>Is Revision</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <inlineHelpText>Holds Previous Status value</inlineHelpText>
    <label>Previous Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Previous_Task_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Previous_Task_Instructions__c</fullName>
    <description>Stores the Previous Task Instructions from a Previous Revision, in case these get removed.</description>
    <inlineHelpText>Stores the Previous Task Instructions from a Previous Revision, in case these get removed.</inlineHelpText>
    <label>Previous Task Instructions</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Revised_Task__c.field-meta.xml
<CustomField>
    <fullName>Revised_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the current task is archived, this lookup points to the revision of the task</description>
    <inlineHelpText>The newer revision of the current task</inlineHelpText>
    <label>Revised Task</label>
    <referenceTo>GC_Design_Element__c</referenceTo>
    <relationshipLabel>Previous Versions</relationshipLabel>
    <relationshipName>Design_Element_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of Revisions</description>
    <label>Revision</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Rework__c.field-meta.xml
<CustomField>
    <fullName>Rework__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If product or task is rejected or disapproved, rework is required</description>
    <inlineHelpText>Rework if task or product is rejected or disapproved.</inlineHelpText>
    <label>Rework</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of product or task</description>
    <inlineHelpText>Status of product or task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>CD Assign</fullName>
            </value>
            <value>
                <fullName>Task Accepted</fullName>
            </value>
            <value>
                <fullName>Task Rejected</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>On Hold/WFI</fullName>
            </value>
            <value>
                <fullName>GES Approved</fullName>
            </value>
            <value>
                <fullName>GES Disapproved</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Work Product Disapproved</fullName>
            </value>
            <value>
                <fullName>Work Product Approved</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Task_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Task_Instruction__c</fullName>
    <description>Instructions pertaining to task</description>
    <inlineHelpText>Instructions pertaining to task</inlineHelpText>
    <label>Task Instructions</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/GC_ReviseDesignElement_Controller.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Controller for Design Element revision page
* 2016-04-13 : Original Version
**/
public with sharing class GC_ReviseDesignElement_Controller {

    private final GC_Design_Element__c designElement;

    public GC_ReviseDesignElement_Controller(ApexPages.StandardController stdController) {
        this.designElement = (GC_Design_Element__c)stdController.getRecord();
    }

    public PageReference createRevision() {
        //Check that user has profile that allows revisions
        List<Profile> profile = [SELECT Id, Name FROM Profile WHERE Id = :userinfo.getProfileId() LIMIT 1];
        String profileName = profile[0].Name;
        if (GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_ACCT_MANAGER) &&
            GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_SALES_MGR) &&
            GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_DIRECTOR_ACCT_MGMT) &&
            GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_CREATIVE_DIRECTOR) &&
            GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_TRAFFIC_ADMIN) &&
            GC_SecurityUtil.userHasRole('System Administrator')) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'You don\'t have permissions to revise this Design Element'));
            return null;
        }
        //Requery existing record to get fields not referenced in Visualforce
        GC_Design_Element__c de = GC_DesignElementDao.getInstance().getDesignElementById(designElement.Id);
        if (!de.Active__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'You may only revise an active Design Element'));
            return null;
        }

        if (de.Status__c == 'New') {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'You may only revise Tasks that are not New.'));
            return null;
        }
        if (GC_ApprovalUtils.isUnderApproval(de.Id)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'You may only revise Tasks that are not currently in an approval process.  Please finish the workflow or recall the approval process.'));
            return null;
        }
        // Clone current DE, parameters: (clone id, deep clone, clone timestamps, clone autonumbers)
        // GC-627 No Longer Making Clone
        //oldVersion = de.clone(false, true, false, true);
        //oldVersion.Status__c = 'Archived';
        //oldVersion.Previous_Status__c = de.Status__c;
        //oldVersion.Active__c = false;
        //oldVersion.Revised_Task__c = de.Id;

        //insert oldVersion;

        de.Revision__c = de.Revision__c + 1;
        de.Is_Revision__c = true;
        de.Status__c = 'New';
        de.Rework__c = false;
        de.Previous_Task_Instructions__c = de.Task_Instruction__c;

        try {
            update de;
        }
        catch (DmlException e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Record is currently locked from an approval process.'));
            return null;
        }
        PageReference revisionPage = new ApexPages.StandardController(de).view();
        return revisionPage;
    }

    public GC_Design_Element__c getDesignElement() {
        return designElement;
    }
}