unpackaged/main/default/objects/GC_Design_Element__c/GC_Design_Element__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Element Task Custom Object.</description>
    <label>Design Element Task</label>
    <nameField>
        <displayFormat>DE-{0000000}</displayFormat>
        <label>Design Element Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Element Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Design_Element__c.field-meta.xml
<CustomField>
    <fullName>Design_Element__c</fullName>
    <description>Design Element Type</description>
    <inlineHelpText>Design Element Type</inlineHelpText>
    <label>Design Element</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Task_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Charging Station</fullName>
            </value>
            <value>
                <fullName>Column Wrap</fullName>
            </value>
            <value>
                <fullName>Design Style Guide</fullName>
            </value>
            <value>
                <fullName>Entrance</fullName>
            </value>
            <value>
                <fullName>Exhibitor Pods</fullName>
            </value>
            <value>
                <fullName>Fill-in</fullName>
            </value>
            <value>
                <fullName>Impact Unit</fullName>
            </value>
            <value>
                <fullName>Information Booth</fullName>
            </value>
            <value>
                <fullName>Kiosks</fullName>
            </value>
            <value>
                <fullName>Kit Booth Packages</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Management Booth</fullName>
            </value>
            <value>
                <fullName>Product Showcases</fullName>
            </value>
            <value>
                <fullName>Publication Bin</fullName>
            </value>
            <value>
                <fullName>Registration/Counters</fullName>
            </value>
            <value>
                <fullName>Resource Center</fullName>
            </value>
            <value>
                <fullName>Schedule at a Glance</fullName>
            </value>
            <value>
                <fullName>Service Desk</fullName>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Theater</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Assignment__c/GC_Show_Team_Assignment__c.object-meta.xml
<CustomObject>
    <description>Object which links a show team member to a Design Element, Work Order Task, or Sign Order Task to facilitate a Show Team Member being assigned to one of those records</description>
    <label>Show Team Assignment</label>
    <nameField>
        <displayFormat>STA-{0000000}</displayFormat>
        <label>Show Team Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Assignment__c/fields/Design_Element__c.field-meta.xml
<CustomField>
    <fullName>Design_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Design Element</label>
    <referenceTo>GC_Design_Element__c</referenceTo>
    <relationshipLabel>Show Team Assignments</relationshipLabel>
    <relationshipName>Show_Team_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Assignment__c/fields/Show_Team_Assignment_Unique__c.field-meta.xml
<CustomField>
    <fullName>Show_Team_Assignment_Unique__c</fullName>
    <label>Show Team Assignment Unique</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Assignment__c/fields/Show_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Show_Team_Member__c</fullName>
    <label>Show Team Member</label>
    <referenceTo>GC_Show_Team_Member__c</referenceTo>
    <relationshipLabel>Show Team Assignments</relationshipLabel>
    <relationshipName>Show_Team_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Assignment__c/fields/Team_Member_Role__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Role__c</fullName>
    <formula>TEXT(Show_Team_Member__r.Show_Role__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team Member Role</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GC_ShowTeamAssignmentTriggerHandler.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Trigger logic for Show Team Assignment
* 2016-04-13 : Original Version
**/
public without sharing class GC_ShowTeamAssignmentTriggerHandler {

    public static Map<String, String> mapAccessLevel = new Map<String, String> {
        'GC_Design_Element__c,Account Manager' => 'Edit'
        , 'GC_Design_Element__c,Secondary Account Manager' => 'Edit'
        , 'GC_Design_Element__c,Director of Account Management' => 'Edit'
        , 'GC_Design_Element__c,Sales Manager' => 'Edit'
        , 'GC_Design_Element__c,Creative Director' => 'Edit'
        , 'GC_Design_Element__c,Traffic Administrator' => 'Edit'
        , 'GC_Design_Element__c,Designer' => 'Edit'
        , 'GC_Design_Element__c,Detailer' => 'Edit'
        , 'GC_Design_Element__c,Designer/Detailer' => 'Edit'
    };

    public static void UpdateTaskAccess(List<GC_Show_Team_Assignment__c> showTeamAssignments) {
        Set<Id> deIds = new Set<Id>();
        Set<String> staIds = new Set<String>();
        for (GC_Show_Team_Assignment__c assignment : showTeamAssignments) {
            if (String.isNotBlank(assignment.Design_Element__c)) {
                deIds.add(assignment.Design_Element__c);
            }
            staIds.add(assignment.Id);
        }
        List<GC_Show_Team_Assignment__c> assignments = GC_ShowTeamAssignmentDao.getInstance().getByShowTeamAssignmentIds(staIds);
        List<GC_Design_Element__c> drfElements = [select Id from GC_Design_Element__c where Id in :deIds];
        List<GC_Design_Element__Share> drfElementShares = new List<GC_Design_Element__Share>();
        for (GC_Show_Team_Assignment__c showTeamAssignment : assignments) {
            if (String.isBlank(showTeamAssignment.Design_Element__c)) {
                continue;
            }
            for (GC_Design_Element__c drfElement : drfElements) {
                if (drfElement.Id != showTeamAssignment.Design_Element__c) {
                    continue;
                }
                String mapLookup = drfElement.getSObjectType().getDescribe().getName() + ',' + showTeamAssignment.Team_Member_Role__c;
                if (!mapAccessLevel.containsKey(mapLookup)) {
                    continue;
                }
                GC_Design_Element__Share shareObject = new GC_Design_Element__Share();
                shareObject.ParentId = drfElement.Id;
                shareObject.UserOrGroupId = showTeamAssignment.Show_Team_Member__r.User__c;
                shareObject.AccessLevel = mapAccessLevel.get(mapLookup);
                drfElementShares.add(shareObject);
            }
        }
        Database.SaveResult[] saveResultDET = Database.insert(drfElementShares, false);
    }

    public static void UpdateShowTeamAssignmentUnique(List<GC_Show_Team_Assignment__c> showTeamAssignments) {
        for (GC_Show_Team_Assignment__c sta : showTeamAssignments) {
            if (String.isNotBlank(sta.Design_Element__c)) {
                sta.Show_Team_Assignment_Unique__c = sta.Design_Element__c + '.' + sta.Show_Team_Member__c;
            }
        }
    }
}