unpackaged/main/default/objects/GC_Design_Element__c/GC_Design_Element__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Element Task Custom Object.</description>
    <label>Design Element Task</label>
    <nameField>
        <displayFormat>DE-{0000000}</displayFormat>
        <label>Design Element Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Element Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person who is responsible for the management of sales, and relationships with particular customers.</description>
    <inlineHelpText>This account manager is identified when the task is submitted for approval.  The system looks at the show team for any users with the role Account Manager and populates this field on submit.</inlineHelpText>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Manager_Design_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Contact_Designer_Detailer_Approver1__c.field-meta.xml
<CustomField>
    <fullName>Contact_Designer_Detailer_Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Designer/Detailer Approver1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Design Element Tasks</relationshipLabel>
    <relationshipName>Design_Element_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Creative_Director_Approvers__c.field-meta.xml
<CustomField>
    <fullName>Creative_Director_Approvers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of Creative Director is set to Approve the Design Element</description>
    <inlineHelpText>Name of Creative Director is set to Approve the Design Element.  This will automatically add this member to the Show Team.</inlineHelpText>
    <label>Creative Director Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Creative_Director_For</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Detailer_Approver__c.field-meta.xml
<CustomField>
    <fullName>Detailer_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is a lookup to the Designer/Detailer User that is Assigned to this Task to be used in the approval process routing.  This field is set by assigning a designer/detailer to the task.</inlineHelpText>
    <label>Designer/Detailer Approver1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>GC Detailer,GC Creative Director</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Design_Element_Tasks_Approver1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Secondary_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Secondary Account Manager.</description>
    <inlineHelpText>This account manager is identified when the task is submitted for approval.  The system looks at the show team for any users with the role Account Manager and populates this field on submit.</inlineHelpText>
    <label>Secondary Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Secondary_Account_Manager_Design_Element</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of product or task</description>
    <inlineHelpText>Status of product or task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>CD Assign</fullName>
            </value>
            <value>
                <fullName>Task Accepted</fullName>
            </value>
            <value>
                <fullName>Task Rejected</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>On Hold/WFI</fullName>
            </value>
            <value>
                <fullName>GES Approved</fullName>
            </value>
            <value>
                <fullName>GES Disapproved</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Work Product Disapproved</fullName>
            </value>
            <value>
                <fullName>Work Product Approved</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Traffic_Administrator_Approver__c.field-meta.xml
<CustomField>
    <fullName>Traffic_Administrator_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of Traffic Administrator set to Approve the Design Element</description>
    <inlineHelpText>Name of Traffic Administrator is set to Approve the Design Element.  This will automatically add this member to the Show Team.</inlineHelpText>
    <label>Traffic Administrator Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Design_Element_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/GC_Design_Request_Form__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Request Form Custom Object.  Each Opportunity will have one and only one Active Design Request Form.  The Design Request Form object will be the central object to relate Design Element designated to a show.  The DRF contains details about budgets / graphics / show information.</description>
    <label>Design Request Form</label>
    <nameField>
        <displayFormat>DRF-{0000}</displayFormat>
        <label>Design Request Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Request Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of DRF.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/recordTypes/RFP.recordType-meta.xml
<RecordType>
    <fullName>RFP</fullName>
    <active>true</active>
    <description>Request for Proposal for an Exhibition or Event.</description>
    <label>RFP (Exhibition or Event)</label>
</RecordType>

unpackaged/main/default/classes/GC_DRF_RFP_ApprovalController.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Controller for Design Request Form RFP approval display page
* 2016-04-13 : Original Version
**/
public with sharing class GC_DRF_RFP_ApprovalController {
    public GC_Design_Request_Form__c drf;
    public GC_Design_Element__c de  {get; set;}
    ApexPages.StandardController scsave;

    public Profile currentUserProfile {get; set;}

    public GC_DRF_RFP_ApprovalController(ApexPages.StandardController sc) {
        currentUserProfile = [select Id, Name from Profile where Id = :UserInfo.getProfileId()];
        de = GC_DesignElementDao.getInstance().getDesignElementById(((GC_Design_Element__c)sc.getRecord()).Id);
        scsave = sc;
    }

    public PageReference cancel() {
        return scsave.cancel();
    }

    public PageReference setApprover() {
        if (de.Status__c == 'Archived') {
            GC_PageUtil.AddErrorMessage('Cannot submit for approval when the Task is Archived.');
            return null;
        }
        if (de.Status__c == 'On Hold/WFI') {
            GC_PageUtil.AddErrorMessage('Cannot submit for approval when the Task is On Hold.');
            return null;
        }
        if (String.isBlank(de.Creative_Director_Approvers__c) || String.isBlank(de.Traffic_Administrator_Approver__c)) {
            GC_PageUtil.AddErrorMessage('You must assign a Creative Director and Traffic Administrator to this task to submit for approval.');
            return null;
        }
        if (!getCanSubmitForApproval()) {
            GC_PageUtil.AddErrorMessage('This user ' + UserInfo.getName() + ' can not submit for Approval.');
            return null;
        }
        if (GC_ApprovalUtils.isUnderApproval(de.Id)) {
            GC_PageUtil.AddErrorMessage('This task is currently under approval, you must recall or exit the approval process to resubmit for approval.');
            return null;
        }
        //Commenting out 1/28/2019 fixes for DET Process
        /*if (de.OwnerId != UserInfo.getUserId()) {
            GC_PageUtil.AddErrorMessage('Only the Task owner can submit this element for approval.  Change ownership of the item to submit to approval.');
            return null;
        }*/
        else {
            List<GC_Design_Element__c> des = new List<GC_Design_Element__c>();
            des.add(de);
            GC_DesignElementTaskTriggerHandler.SetAccountManager(des);
            update des;
            de = GC_DesignElementDao.getInstance().getDesignElementById(de.Id);
            if (de.Secondary_Account_Manager__c == null) {
                de.Secondary_Account_Manager__c = de.Account_Manager__c;
                update de;
            }

            if (GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_CREATIVE_DIRECTOR) || GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_TRAFFIC_ADMIN)) {
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Submitting request for approval');
                req1.setObjectId(de.Id);
                //if (String.isNotBlank(de.Detailer_Approver__c)) {
                    //req1.setNextApproverIds(new Id[] {de.Detailer_Approver__c});  //Amarab 04062021 SAL-1243 Replacing old Designer/Detailer Approver1 field with new field
                /*if (String.isNotBlank(de.Contact_Designer_Detailer_Approver1__c)) {
                    req1.setNextApproverIds(new Id[] {de.Contact_Designer_Detailer_Approver1__c});
                }
                else {
                    GC_PageUtil.AddErrorMessage('A Detailer must be selected to be submitted for approval.');
                    return null;
                }*/ //Amarab 04062021 SAL-1243 Designer Detailer Approver assignment is now managed in Workfront  

                req1.setProcessDefinitionNameOrId('DE_Approval_Process11');
                try {
                    Approval.ProcessResult result = Approval.process(req1);
                }
                catch (Exception e) {
                    GC_PageUtil.AddErrorMessage('Failed to Submit this task for Approval: ' + e.getMessage());
                    return null;
                }
            }
            else {
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Submitting request for approval');
                req1.setObjectId(de.Id);
                List<Id> approvers = new List<Id>();
                if (String.isNotBlank(de.Creative_Director_Approvers__c)) {
                    approvers.add(de.Creative_Director_Approvers__c);
                }
                if (String.isNotBlank(de.Traffic_Administrator_Approver__c)) {
                    approvers.add(de.Traffic_Administrator_Approver__c);
                }

                req1.setNextApproverIds(approvers);
                req1.setProcessDefinitionNameOrId('DE_Approval_Process9');
                try {
                    Approval.ProcessResult result = Approval.process(req1);
                }
                catch (Exception e) {
                    GC_PageUtil.AddErrorMessage('Failed to Submit this task for Approval: ' + e.getMessage());
                    return null;
                }
            }

            return new PageReference('/' + de.Id);
        }
        return null;
    }

    public Boolean getCanSubmitForApproval() {

        if (GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_ACCT_MANAGER)
                || GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_SALES_MGR)
                || GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_CREATIVE_DIRECTOR)
                || GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_TRAFFIC_ADMIN)
                || GC_SecurityUtil.userHasRole(GC_SecurityUtil.R_DIRECTOR_ACCT_MGMT)
                || GC_SecurityUtil.userHasRole('System Administrator')) {
            return true;
        }
        else {
            return false;
        }
    }
}