unpackaged/main/default/objects/CA_Exhibit__c/CA_Exhibit__c.object-meta.xml
<CustomObject>
    <description>This will be the Exhibit object for all Accounts under Generic Template</description>
    <label>CA Exhibit</label>
    <nameField>
        <displayFormat>CAEX-{00000}</displayFormat>
        <label>CA Exhibit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Exhibits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CA_Exhibit__c/fields/Agency_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Contact_Name__c</fullName>
    <label>Agency Contact Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CA_Exhibit__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>CA_Main_Event__c</referenceTo>
    <relationshipLabel>CA Exhibits</relationshipLabel>
    <relationshipName>CA_Exhibits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CA_Main_Event__c/CA_Main_Event__c.object-meta.xml
<CustomObject>
    <description>Object will be used to create Generic Template Account for GES Community</description>
    <label>CA Main Event</label>
    <nameField>
        <displayFormat>CAE-{00000}</displayFormat>
        <label>Main Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Main Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CA_Main_Event__c/fields/Event_Acronym__c.field-meta.xml
<CustomField>
    <fullName>Event_Acronym__c</fullName>
    <label>Event Acronym</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CA_Main_Event__c/fields/Name_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Event__c</fullName>
    <label>Name of Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sponsorship</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/Exhibit__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Exhibit</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exhibit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Exhibit__c/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <description>Created under SAL-480</description>
    <label>Agency Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Exhibit_Name__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Name__c</fullName>
    <label>Exhibit Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/GT_Brand__c.object-meta.xml
<CustomObject>
    <description>This will be the product object for all accounts in Generic Template</description>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Brand__c/fields/Additional_Cost_Description_6__c.field-meta.xml
<CustomField>
    <fullName>Additional_Cost_Description_6__c</fullName>
    <label>Additional Cost Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup for Event Activity Type</description>
    <label>Event</label>
    <referenceTo>GT_Event_RL__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Exhibit__c.field-meta.xml
<CustomField>
    <fullName>Exhibit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibit</label>
    <referenceTo>GT_Exhibit__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up for GT_Event__c  (GES Connect Event)</description>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Meeting_Room__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting Room</label>
    <referenceTo>GT_Meeting_Room__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Speaking_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Speaking_Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Speaking Engagement</label>
    <referenceTo>GT_Speaking_Engagement__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsorship</label>
    <referenceTo>GT_Sponsorship__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/GT_Event__c.object-meta.xml
<CustomObject>
    <description>Object will be used to create Generic Template Account for GES Community. Main Event object for 1st Lightning Community. CC, Merck, SS, GT, Pharma Template, NNI.</description>
    <label>GES Connect Event</label>
    <nameField>
        <displayFormat>GCE-{000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Event__c/fields/Shipping_City_c__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City_c__c</fullName>
    <label>Adv. Whs. City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/fields/Shipping_Zip_Postal_Code_c__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Zip_Postal_Code_c__c</fullName>
    <label>Adv. Whs. Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GT_Exhibit__c/GT_Exhibit__c.object-meta.xml
<CustomObject>
    <description>This will be the Exhibit object for all Accounts under Generic Template</description>
    <label>Exhibit</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exhibit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Exhibit__c/fields/Exhibit_Name__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Name__c</fullName>
    <label>Exhibit Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GT_Exhibit__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Exhibits</relationshipLabel>
    <relationshipName>Exhibits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Meeting_Room__c/GT_Meeting_Room__c.object-meta.xml
<CustomObject>
    <description>This will be the Meeting Room object for all accounts in Generic Template</description>
    <label>Meeting Room</label>
    <nameField>
        <displayFormat>MR-{00000}</displayFormat>
        <label>Meeting Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Meeting_Room__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Meeting Rooms</relationshipLabel>
    <relationshipName>Meeting_Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Speaking_Engagement__c/GT_Speaking_Engagement__c.object-meta.xml
<CustomObject>
    <description>This will be the Speaking Engagement object for all accounts in Generic Template</description>
    <label>Speaking Engagement</label>
    <nameField>
        <displayFormat>SE-{00000}</displayFormat>
        <label>Speaking Engagement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speaking Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Speaking_Engagement__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Speaking Engagements</relationshipLabel>
    <relationshipName>Symposia</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Sponsorship__c/GT_Sponsorship__c.object-meta.xml
<CustomObject>
    <description>This will be the Sponsorship object for all accounts in Generic Template</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Sponsorship__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up for GT_Event__c</description>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Meeting_Room__c/Meeting_Room__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Meeting Room</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Meeting Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Room</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Meeting_Room__c/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <label>Agency Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <inlineHelpText>Yes - Identifies an Event as a Planned Event</inlineHelpText>
    <label>Planned Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsorship__c/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Sponsorship</relationshipLabel>
    <relationshipName>Sponsorship_Instance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsorship__c/fields/Sponsorship_Name__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Name__c</fullName>
    <label>Sponsorship Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SingleRelatedListControllerTest.cls
@isTest
public class SingleRelatedListControllerTest {
    @testSetup
    public static void testsetupMethod(){
           Opportunity opp=LC_TestUtils.insertOpportunity();
            GC_Connect2_Show__c show=LC_TestUtils.insertShow(opp.Id,opp.Name);
        
        LC_TestUtils.insertMainEventPersonSetObj();
        LC_TestUtils.insertExhibitPersonSetObj();
        
        CA_Main_Event__c insertMainEvent= new CA_Main_Event__c();
        insertMainEvent.Name_of_Event__c='Test Event';
        insertMainEvent.Event_Acronym__c='TE';
        insert insertMainEvent;
        
        CA_Exhibit__c insertCAExhibit = new CA_Exhibit__c();
        insertCAExhibit.Exhibit_Name__c='Test Exhibit';
        insertCAExhibit.Event__c = insertMainEvent.Id;
        insert insertCAExhibit;
        
        GT_Event__c insertConnectEvent= new GT_Event__c();
        insertConnectEvent.Shipping_City_c__c='testShippingCity';
        insertConnectEvent.Shipping_Zip_Postal_Code_c__c='12345';
        insert insertConnectEvent;
        
        GT_Exhibit__c insertExhibit=new GT_Exhibit__c();
        insertExhibit.GES_Connect_Event__c=insertConnectEvent.Id;
        insertExhibit.Agency_Contact_Name__c='test Agency Contact Name';
        insert insertExhibit;
        GT_Brand__c insertBrand=new GT_Brand__c();
        insertBrand.Exhibit__c=insertExhibit.id;
        insertBrand.Additional_Cost_Description_6__c='test brand of Exhibit';
        insert insertBrand;
        
        GT_Sponsorship__c insertSponsership=new GT_Sponsorship__c();
        insertSponsership.GES_Connect_Event__c=insertConnectEvent.Id;
        insertSponsership.Sponsorship_Name__c='test Sponseship name';
        insert insertSponsership;
        GT_Brand__c insertsponBrand=new GT_Brand__c();
        insertsponBrand.Sponsorship__c=insertSponsership.Id;
        insertsponBrand.Additional_Cost_Description_6__c='test brand for sponsership';
        insert insertsponBrand;
        
        GT_Meeting_Room__c insertMeeting=new GT_Meeting_Room__c();
        insertMeeting.GES_Connect_Event__c=insertConnectEvent.Id;
        insertMeeting.Agency_Name__c='test meetingRoom name';
        insert insertMeeting;
        GT_Brand__c insertMeetingBrand=new GT_Brand__c();
        insertMeetingBrand.Meeting_Room__c=insertMeeting.Id;
        insertMeetingBrand.Additional_Cost_Description_6__c='test brand for Meeting';
        insert insertMeetingBrand;
        
        GT_Speaking_Engagement__c insertSpeaking=new GT_Speaking_Engagement__c();
        insertSpeaking.GES_Connect_Event__c=insertConnectEvent.Id;
        insertSpeaking.Event_Manager__c='test speakingEng name';
        insert insertSpeaking;
        GT_Brand__c insertSpeakingBrand=new GT_Brand__c();
        insertSpeakingBrand.Speaking_Engagement__c=insertSpeaking.Id;
        insertSpeakingBrand.Additional_Cost_Description_6__c='test brand for SpeakingEng';
        insert insertSpeakingBrand;
    }
    
    @isTest public static void testInit(){
        Account acc = new Account(Name = 'test');
        insert acc;
        Contact cnt = new Contact(LastName = 'test', AccountId = acc.Id);
        insert cnt;
        
        Map<String, Object> requestMap = new Map<String, Object>(); 
        requestMap.put(SingleRelatedListController.FIELDS_PARAM, 'Name, Title, Email, Phone');
        requestMap.put(SingleRelatedListController.RELATED_FIELD_API_NAME_PARAM, 'AccountId');
        requestMap.put(SingleRelatedListController.RECORD_ID_PARAM, acc.Id);
        requestMap.put(SingleRelatedListController.NUMBER_OF_RECORDS_PARAM, 1);
        requestMap.put(SingleRelatedListController.SOBJECT_API_NAME_PARAM, 'Contact');
        requestMap.put(SingleRelatedListController.SORTED_BY_PARAM, 'Name');
        requestMap.put(SingleRelatedListController.SORTED_DIRECTION_PARAM, 'ASC');
        
        String jsonData = SingleRelatedListController.initData(JSON.serialize(requestMap));
        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(jsonData);
        List<Object> records = (List<Object>)responseMap.get(SingleRelatedListController.RECORDS_PARAM);
        System.assert(!records.isEmpty());
        String iconName = (String)responseMap.get(SingleRelatedListController.ICON_NAME_PARAM);
        System.assert(String.isNotBlank(iconName));
        SingleRelatedListController.getProfileName();
        GT_Exhibit__c exhibit=[select Id from GT_Exhibit__c where Agency_Contact_Name__c='test Agency Contact Name' limit 1];
        SingleRelatedListController.relatedObjectNameToQuery(exhibit.Id);
        GT_Sponsorship__c GTBRandSpon=[select id from GT_Sponsorship__c where Sponsorship_Name__c='test Sponseship name' limit 1];
        SingleRelatedListController.relatedObjectNameToQuery(GTBRandSpon.Id);
        GT_Meeting_Room__c GTBRandmeeting=[select id from GT_Meeting_Room__c where Agency_Name__c='test meetingRoom name' limit 1];
        SingleRelatedListController.relatedObjectNameToQuery(GTBRandmeeting.Id);
        GT_Speaking_Engagement__c GTBRandspeaking=[select id from GT_Speaking_Engagement__c where Event_Manager__c='test speakingEng name' limit 1];
        SingleRelatedListController.relatedObjectNameToQuery(GTBRandspeaking.Id);
        SingleRelatedListController.deleteRecord(GTBRandspeaking.Id);
        
        GC_Connect2_Show__c sId=[select Id from GC_Connect2_Show__c where Show_Name__c = 'test show' and Job_Number__c = '12345' and Production_Location__c='71' limit 1];
        pharmaTemplateApexController.getShowRelated(sId.Id);
        
        GT_Event__c event=[select Id from GT_Event__c where Shipping_City_c__c='testShippingCity' and Shipping_Zip_Postal_Code_c__c='12345' limit 1];
        pharmaTemplateApexController.cloneRecord(event);
        
        pharmaTemplateApexController.CalendarValuesCongress(event.Id);
        
        Account testAccount = GC_TestUtils.getAccount(1);
        pharmaTemplateApexController.getFacilityRelated(testAccount.Id);

        
    }
    @isTest 
    public static void testGetMainEventId(){
                
        CA_Exhibit__c caExhibit = [SELECT ID,Name,Exhibit_Name__c FROM CA_Exhibit__c WHERE Exhibit_Name__c = 'Test Exhibit'];
        SingleRelatedListController.getPerObjSettings(caExhibit.Id, 'CA_Exhibit__c');
        SingleRelatedListController.getMainEventId('CA_Exhibit__c',caExhibit.Id);
    }
}