unpackaged/main/default/objects/CA_Event__c/CA_Event__c.object-meta.xml
<CustomObject>
    <label>CA Event</label>
    <nameField>
        <displayFormat>CAEV - {00000}</displayFormat>
        <label>CA Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CA_Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>CA_Main_Event__c</referenceTo>
    <relationshipLabel>CA Events</relationshipLabel>
    <relationshipName>CA_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CA_Event__c/fields/Reason_for_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Cancellation__c</fullName>
    <label>Reason for Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Budget Cut</fullName>
            </value>
            <value>
                <fullName>Exhibit Space Sold Out</fullName>
            </value>
            <value>
                <fullName>Product Owner Decision</fullName>
            </value>
            <value>
                <fullName>Public Health Issue</fullName>
            </value>
            <value>
                <fullName>Strategy Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CA_Exhibit__c/CA_Exhibit__c.object-meta.xml
<CustomObject>
    <description>This will be the Exhibit object for all Accounts under Generic Template</description>
    <label>CA Exhibit</label>
    <nameField>
        <displayFormat>CAEX-{00000}</displayFormat>
        <label>CA Exhibit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Exhibits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CA_Exhibit__c/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CA_Exhibit__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>CA_Main_Event__c</referenceTo>
    <relationshipLabel>CA Exhibits</relationshipLabel>
    <relationshipName>CA_Exhibits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CA_Exhibit__c/fields/Reason_For_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Cancellation__c</fullName>
    <label>Reason For Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Budget Cut</fullName>
            </value>
            <value>
                <fullName>Event Not Occurring</fullName>
            </value>
            <value>
                <fullName>Exhibit Space Sold Out</fullName>
            </value>
            <value>
                <fullName>Product Owner Decision</fullName>
            </value>
            <value>
                <fullName>Public Health Issue</fullName>
            </value>
            <value>
                <fullName>Strategy Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CA_Main_Event__c/CA_Main_Event__c.object-meta.xml
<CustomObject>
    <description>Object will be used to create Generic Template Account for GES Community</description>
    <label>CA Main Event</label>
    <nameField>
        <displayFormat>CAE-{00000}</displayFormat>
        <label>Main Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Main Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CA_Main_Event__c/fields/Reason_for_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Cancellation__c</fullName>
    <label>Reason for Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Budget cut</fullName>
            </value>
            <value>
                <fullName>Event Not Occurring</fullName>
                <isActive>false</isActive>
                <label>Event Not Occurring</label>
            </value>
            <value>
                <fullName>Exhibit Space Sold Out</fullName>
                <label>Exhibit space sold out</label>
            </value>
            <value>
                <fullName>Product owner decision</fullName>
            </value>
            <value>
                <fullName>Public Health Issue</fullName>
            </value>
            <value>
                <fullName>Strategy Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CA_Meeting_Planning__c/CA_Meeting_Planning__c.object-meta.xml
<CustomObject>
    <label>CA Meeting Planning</label>
    <nameField>
        <displayFormat>CAMP - {00000}</displayFormat>
        <label>CA Meeting Planning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Meeting Plannings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CA_Meeting_Planning__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>CA_Main_Event__c</referenceTo>
    <relationshipLabel>CA Meeting Plannings</relationshipLabel>
    <relationshipName>CA_Meeting_Plannings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CA_Meeting_Planning__c/fields/Reason_for_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Cancellation__c</fullName>
    <label>Reason for Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Budget Cut</fullName>
            </value>
            <value>
                <fullName>Event Not Occurring</fullName>
            </value>
            <value>
                <fullName>Exhibit Space Sold Out</fullName>
            </value>
            <value>
                <fullName>Product Owner Decision</fullName>
            </value>
            <value>
                <fullName>Public Health Issue</fullName>
            </value>
            <value>
                <fullName>Rollover Event</fullName>
            </value>
            <value>
                <fullName>Strategy Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CA_Meeting_Room__c/CA_Meeting_Room__c.object-meta.xml
<CustomObject>
    <label>CA Meeting Room</label>
    <nameField>
        <displayFormat>CAMR - {00000}</displayFormat>
        <label>CA Meeting Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Meeting Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CA_Meeting_Room__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>CA_Main_Event__c</referenceTo>
    <relationshipLabel>CA Meeting Rooms</relationshipLabel>
    <relationshipName>CA_Meeting_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CA_Meeting_Room__c/fields/Reason_for_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Cancellation__c</fullName>
    <label>Reason for Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Budget Cut</fullName>
            </value>
            <value>
                <fullName>Event Not Occurring</fullName>
            </value>
            <value>
                <fullName>Exhibit Space Sold Out</fullName>
            </value>
            <value>
                <fullName>Product Owner Decision</fullName>
            </value>
            <value>
                <fullName>Public Health Issue</fullName>
            </value>
            <value>
                <fullName>Rollover Event</fullName>
            </value>
            <value>
                <fullName>Strategy Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CA_Membership__c/CA_Membership__c.object-meta.xml
<CustomObject>
    <label>CA Membership</label>
    <nameField>
        <label>CA Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CA Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CA_Membership__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>CA_Main_Event__c</referenceTo>
    <relationshipLabel>CA Memberships</relationshipLabel>
    <relationshipName>CA_Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CA_Membership__c/fields/Reason_for_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Cancellation__c</fullName>
    <label>Reason for Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Budget Cut</fullName>
            </value>
            <value>
                <fullName>Exhibit Space Sold Out</fullName>
            </value>
            <value>
                <fullName>Strategy Change</fullName>
            </value>
            <value>
                <fullName>Product Owner Decision</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CA_Speaking_Engagement__c/CA_Speaking_Engagement__c.object-meta.xml
<CustomObject>
    <label>CA Speaking Engagement</label>
    <nameField>
        <displayFormat>CASE-{00000}</displayFormat>
        <label>CA Speaking Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Speaking Engagements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CA_Speaking_Engagement__c/fields/Cancellation_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date_Time__c</fullName>
    <description>The new field created for Cancellation Date with date/time data type.</description>
    <label>Cancellation Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/CA_Speaking_Engagement__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>CA_Main_Event__c</referenceTo>
    <relationshipLabel>CA Speaking Engagements</relationshipLabel>
    <relationshipName>CA_Speaking_Engagements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CA_Sponsorship__c/CA_Sponsorship__c.object-meta.xml
<CustomObject>
    <description>This will be the Sponsorship object for all accounts in Generic Template</description>
    <label>CA Sponsorship</label>
    <nameField>
        <displayFormat>CAS-{00000}</displayFormat>
        <label>CA Sponsorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Sponsorships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CA_Sponsorship__c/fields/Cancellation_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date_Time__c</fullName>
    <label>Cancellation Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/CA_Sponsorship__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>CA_Main_Event__c</referenceTo>
    <relationshipLabel>CA Sponsorships</relationshipLabel>
    <relationshipName>CA_Sponsorships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CA_Sporting_Event__c/CA_Sporting_Event__c.object-meta.xml
<CustomObject>
    <description>This will be the Sporting Event object for all accounts in Generic Template</description>
    <label>CA Sporting Event</label>
    <nameField>
        <label>CA Sporting Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CA Sporting Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CA_Sporting_Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>CA_Main_Event__c</referenceTo>
    <relationshipLabel>CA Sporting Events</relationshipLabel>
    <relationshipName>CA_Sporting_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CA_Sporting_Event__c/fields/Reason_for_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Cancellation__c</fullName>
    <label>Reason for Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Budget Cut</fullName>
            </value>
            <value>
                <fullName>Exhibit Space Sold Out</fullName>
            </value>
            <value>
                <fullName>Product Owner Decision</fullName>
            </value>
            <value>
                <fullName>Strategy Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CA_MainEventTriggerHandler.cls
public class CA_MainEventTriggerHandler {
    
    private static Boolean run = true;
    public static Boolean runOnce(){
        if(run){
            run = false;
            return true;
        }else{
            return run;
        }
    }
	Public static void updateCancelState(List<CA_Main_Event__c > allEvents){
        for(CA_Main_Event__c ev:allEvents){
            if(ev.Event_Cancelled__c==False){
                ev.Event_Cancellation_Date__c=NULL;
                ev.Reason_for_Cancellation__c=NULL;
            }
        }
    }
    Public static void cancelActivities(List<CA_Main_Event__c > allEvents){
        set<Id> recordIDs = new set<Id>();
        for(CA_Main_Event__c ev:allEvents){
        	recordIDs.add(ev.id);
        }
        if(recordIDs.size()>0){
            List<CA_Exhibit__c> exList=[SELECT id,name,Cancelled__c,Cancellation_Date_Time__c,Reason_for_Cancellation__c,Event__r.Event_Cancelled__c,Event__r.Event_Cancellation_Date__c,Event__r.Reason_For_Cancellation__c FROM CA_Exhibit__c WHERE Event__c IN :recordIDs];
            for(CA_Exhibit__c ev:exList){
                ev.Cancelled__c=ev.Event__r.Event_Cancelled__c;
                if(ev.Event__r.Event_Cancelled__c==true){
                    ev.Cancellation_Date_Time__c=ev.Event__r.Event_Cancellation_Date__c;
                    ev.Reason_For_Cancellation__c=ev.Event__r.Reason_For_Cancellation__c;
                }
                else{
                    ev.Cancellation_Date_Time__c=NULL;
                    ev.Reason_For_Cancellation__c=NULL;
                }
            }

            List<CA_Event__c> evList=[SELECT id,name,Cancelled__c,Cancellation_Date_Time__c,Reason_for_Cancellation__c,Event__r.Event_Cancelled__c,Event__r.Event_Cancellation_Date__c,Event__r.Reason_For_Cancellation__c FROM CA_Event__c WHERE Event__c IN :recordIDs];
            for(CA_Event__c ev:evList){
                ev.Cancelled__c=ev.Event__r.Event_Cancelled__c;
                if(ev.Event__r.Event_Cancelled__c==true){
                    ev.Cancellation_Date_Time__c=ev.Event__r.Event_Cancellation_Date__c;
                    ev.Reason_For_Cancellation__c=ev.Event__r.Reason_For_Cancellation__c;
                }
                else{
                    ev.Cancellation_Date_Time__c=NULL;
                    ev.Reason_For_Cancellation__c=NULL;
                }
            }

            List<CA_Meeting_Planning__c> mpList=[SELECT id,name,Cancelled__c,Cancellation_Date_Time__c,Reason_for_Cancellation__c,Event__r.Event_Cancelled__c,Event__r.Event_Cancellation_Date__c,Event__r.Reason_For_Cancellation__c FROM CA_Meeting_Planning__c WHERE Event__c IN :recordIDs];
            for(CA_Meeting_Planning__c ev:mpList){
                ev.Cancelled__c=ev.Event__r.Event_Cancelled__c;
                if(ev.Event__r.Event_Cancelled__c==true){
                    ev.Cancellation_Date_Time__c=ev.Event__r.Event_Cancellation_Date__c;
                    ev.Reason_For_Cancellation__c=ev.Event__r.Reason_For_Cancellation__c;
                }
                else{
					ev.Cancellation_Date_Time__c=NULL;
                    ev.Reason_For_Cancellation__c=NULL;
                }
            }
            
            List<CA_Meeting_Room__c> mrList=[SELECT id,name,Cancelled__c,Cancellation_Date_Time__c,Reason_for_Cancellation__c,Event__r.Event_Cancelled__c,Event__r.Event_Cancellation_Date__c,Event__r.Reason_For_Cancellation__c FROM CA_Meeting_Room__c WHERE Event__c IN :recordIDs];
            for(CA_Meeting_Room__c ev:mrList){
                ev.Cancelled__c=ev.Event__r.Event_Cancelled__c;
                if(ev.Event__r.Event_Cancelled__c==true){
                    ev.Cancellation_Date_Time__c=ev.Event__r.Event_Cancellation_Date__c;
                    ev.Reason_For_Cancellation__c=ev.Event__r.Reason_For_Cancellation__c;
                }
                else{
					ev.Cancellation_Date_Time__c=NULL;
                    ev.Reason_For_Cancellation__c=NULL;
                }
            }
            
            List<CA_Speaking_Engagement__c> spList=[SELECT id,name,Cancelled__c,Cancellation_Date_Time__c,Reason_for_Cancellation__c,Event__r.Event_Cancelled__c,Event__r.Event_Cancellation_Date__c,Event__r.Reason_For_Cancellation__c FROM CA_Speaking_Engagement__c WHERE Event__c IN :recordIDs];
            for(CA_Speaking_Engagement__c ev:spList){
                ev.Cancelled__c=ev.Event__r.Event_Cancelled__c;
                if(ev.Event__r.Event_Cancelled__c==true){
                    ev.Cancellation_Date_Time__c=ev.Event__r.Event_Cancellation_Date__c;
                    ev.Reason_For_Cancellation__c=ev.Event__r.Reason_For_Cancellation__c;
                }
                else{
                    ev.Cancellation_Date_Time__c=NULL;
                    ev.Reason_For_Cancellation__c=NULL;
                }
            }
            List<CA_Sponsorship__c> sponList=[SELECT id,name,Cancelled__c,Cancellation_Date_Time__c,Reason_for_Cancellation__c,Event__r.Event_Cancelled__c,Event__r.Event_Cancellation_Date__c,Event__r.Reason_For_Cancellation__c FROM CA_Sponsorship__c WHERE Event__c IN :recordIDs];
            for(CA_Sponsorship__c ev:sponList){
                ev.Cancelled__c=ev.Event__r.Event_Cancelled__c;
                if(ev.Event__r.Event_Cancelled__c==true){
                    ev.Cancellation_Date_Time__c=ev.Event__r.Event_Cancellation_Date__c;
                    ev.Reason_For_Cancellation__c=ev.Event__r.Reason_For_Cancellation__c;
                }
                else{
                    ev.Cancellation_Date_Time__c=NULL;
                    ev.Reason_For_Cancellation__c=NULL;
                }
            }
            List<CA_Sporting_Event__c> seList=[SELECT id,name,Cancelled__c,Cancellation_Date__c,Reason_for_Cancellation__c,Event__r.Event_Cancelled__c,Event__r.Event_Cancellation_Date__c,Event__r.Reason_For_Cancellation__c FROM CA_Sporting_Event__c WHERE Event__c IN :recordIDs];
            for(CA_Sporting_Event__c ev:seList){
                ev.Cancelled__c=ev.Event__r.Event_Cancelled__c;
                if(ev.Event__r.Event_Cancelled__c==true){
                    ev.Cancellation_Date__c=Date.Valueof(ev.Event__r.Event_Cancellation_Date__c);
                    ev.Reason_For_Cancellation__c=ev.Event__r.Reason_For_Cancellation__c;
                }
                else{
                    ev.Cancellation_Date__c=NULL;
                    ev.Reason_For_Cancellation__c=NULL;
                }
            }
            
            List<CA_Membership__c> msList=[SELECT id,name,Cancelled__c,Cancellation_Date__c,Reason_for_Cancellation__c,Event__r.Event_Cancelled__c,Event__r.Event_Cancellation_Date__c,Event__r.Reason_For_Cancellation__c FROM CA_Membership__c WHERE Event__c IN :recordIDs];
            for(CA_Membership__c ev:msList){
                ev.Cancelled__c=ev.Event__r.Event_Cancelled__c;
                if(ev.Event__r.Event_Cancelled__c==true){
                    ev.Cancellation_Date__c=Date.Valueof(ev.Event__r.Event_Cancellation_Date__c);
                    ev.Reason_For_Cancellation__c=ev.Event__r.Reason_For_Cancellation__c;
                }
                else{
                    ev.Cancellation_Date__c=NULL;
                    ev.Reason_For_Cancellation__c=NULL;
                }
            }
            
            if(exList.size()>0){
                database.update(exList, false);
            }
            if(evList.size()>0){
                database.update(evList, false);
            }
            if(mpList.size()>0){
                database.update(mpList, false);
            }
            if(mrList.size()>0){
                database.update(mrList, false);
            }
            if(spList.size()>0){
                database.update(spList, false);
            }
            if(sponList.size()>0){
                database.update(sponList, false);
            }
            if(seList.size()>0){
                database.update(seList, false);
            }           
            if(msList.size()>0){
                database.update(msList, false);
            }
            
        }
    }
    

}