unpackaged/main/default/objects/GES_Logistics_Certificate_Name__c/GES_Logistics_Certificate_Name__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Active certificate name for Logistics web service calls</description>
    <label>GES Logistics Certificate Name</label>
</CustomObject>

unpackaged/main/default/objects/GES_Logistics_Certificate_Name__c/fields/Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Name__c</fullName>
    <label>Certificate Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>Custom object to support Quote functionality for Logistics and other businesses (e.g. Graphics)</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Exhibitor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Dim_Weight__c.field-meta.xml
<CustomField>
    <fullName>Dim_Weight__c</fullName>
    <description>Dim weight</description>
    <label>Dim Weight</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Weight_Override__c.field-meta.xml
<CustomField>
    <fullName>Weight_Override__c</fullName>
    <label>Quick Quote Weight</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/LogisticsCommon.cls
global class LogisticsCommon {
	
    public static Integer GetWeight(Quote__c qte, String mode)
    {
    	Double TotWeight = 0;
    	
        //If Weight Override is specified, use that. Otherwise, check if
        //Dim Weight is greater than Crated Weight. If so, use Dim Weight
        //otherwise use Crated Weight
        if (qte.Weight_Override__c == null || qte.Weight_Override__c <= 0)
        {
        	if (mode.toUpperCase() == 'AIR')
        	{
	        	if (qte.Dim_Weight__c != null && qte.Crated_Weight__c != null)
	        	{
	        		if (qte.Dim_Weight__c > qte.Crated_Weight__c)
	        		{
	        			TotWeight = qte.Dim_Weight__c;
	        		}
	        		else
	        		{
	        			TotWeight = qte.Crated_Weight__c;
	        		}
	        	}
	        	else if (qte.Dim_Weight__c == null && qte.Crated_Weight__c != null)
	        		TotWeight = qte.Crated_Weight__c.intValue();
	        	else if (qte.Crated_Weight__c == null && qte.Dim_Weight__c != null)
	        		TotWeight = qte.Dim_Weight__c.intValue();	        	
        	}
        	else
        	{
        		if (qte.Crated_Weight__c != null)
        			TotWeight = qte.Crated_Weight__c;
        	}
        }
        else
        {
        	TotWeight = qte.Weight_Override__c.intValue();
        }
        
        return Math.Round(TotWeight); 	
    }
    
    public static String getFirst5OfExhibitorName(Quote__c qte)
    {
    	String ExhibitorName = '';
    	
        if (qte.Account_Id__c != null)
        {
        	if (qte.Account_Id__r.Name != null && qte.Account_Id__r.Name.length() > 5)
        		ExhibitorName = qte.Account_Id__r.Name.substring(0,5);
        	else
        		ExhibitorName = qte.Account_Id__r.Name;
        }
            
		return ExhibitorName;
    }
    
    public static String getMMDDYYDate(date d)
    {
    	String PickupDate = '';
    	
        if (d != null)
        { 
        	String Month = (d.month() <= 9 ? '0'+ String.valueOf(d.month()) : String.valueOf(d.month()));
        	String Day = (d.day() <= 9 ? '0'+ String.valueOf(d.day()) : String.valueOf(d.day()));
        	String Year = (String.valueOf(d.year())).substring(2,4);
        	
        	PickupDate = Month + Day + Year;
        } 
        
        return PickupDate;   	
    }
    
    public static String getCertificateName(string customSettingName) {
    	
    	String CertName = '';
    	
    	GES_Logistics_Certificate_Name__c CertCustSetting = [Select Certificate_Name__c From GES_Logistics_Certificate_Name__c Where Active__c = true And Name = :customSettingName];
    	
    	CertName = CertCustSetting.Certificate_Name__c;
    	
    	return CertName;
    }

}