unpackaged/main/default/objects/GC_Task_Field_Manager__c/GC_Task_Field_Manager__c.object-meta.xml
<CustomObject>
    <description>SAL 636</description>
    <label>GC Task Field Manager</label>
    <nameField>
        <label>GC  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GC Task Field Managers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Background__c.field-meta.xml
<CustomField>
    <fullName>Background__c</fullName>
    <defaultValue>(&#39;Shown&#39;)</defaultValue>
    <label>Background</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <isActive>false</isActive>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Booth_Area_Discount__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area_Discount__c</fullName>
    <label>Booth Area Discount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <default>true</default>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <isActive>false</isActive>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Budget_Code__c.field-meta.xml
<CustomField>
    <fullName>Budget_Code__c</fullName>
    <label>Budget Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Client_Layout_Notes__c.field-meta.xml
<CustomField>
    <fullName>Client_Layout_Notes__c</fullName>
    <label>Client Layout Notes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <isActive>false</isActive>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <label>Completion Date/Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <default>true</default>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <description>Parent Show</description>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>GC Task Field Managers</relationshipLabel>
    <relationshipName>GC_Task_Field_Managers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Copy_Placement__c.field-meta.xml
<CustomField>
    <fullName>Copy_Placement__c</fullName>
    <label>Copy Placement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <isActive>false</isActive>
                <label>Shown and Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Default_Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Default_Completion_Date_Time__c</fullName>
    <label>Default Completion Date/Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <isActive>false</isActive>
                <label>Shown and Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Default_Installation_Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Default_Installation_Delivery_Date_Time__c</fullName>
    <label>Default Installation Delivery Date/Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <isActive>false</isActive>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Default_Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Default_Removal_Date_Time__c</fullName>
    <label>Default Removal Date/Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <isActive>false</isActive>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Delivery_Area__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Area__c</fullName>
    <label>Delivery Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <default>true</default>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/File_Reference_Link_Folder__c.field-meta.xml
<CustomField>
    <fullName>File_Reference_Link_Folder__c</fullName>
    <label>File Reference Link/Folder</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Hide_Order_Level_File_Upload__c.field-meta.xml
<CustomField>
    <fullName>Hide_Order_Level_File_Upload__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Hide Order Level File Upload</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Installation_Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Installation_Delivery_Date_Time__c</fullName>
    <label>Installation Delivery Date/Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <default>true</default>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Installation_Method__c.field-meta.xml
<CustomField>
    <fullName>Installation_Method__c</fullName>
    <label>Installation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <isActive>false</isActive>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Onsite_Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Contact_Person__c</fullName>
    <label>Onsite Contact Person</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <default>true</default>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Onsite_Contact_Person_Number__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Contact_Person_Number__c</fullName>
    <defaultValue>(&quot;Shown&quot;)</defaultValue>
    <label>Onsite Contact Person Number</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <default>true</default>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Outdoors__c.field-meta.xml
<CustomField>
    <fullName>Outdoors__c</fullName>
    <label>Outdoors?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <isActive>false</isActive>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <label>Removal Date/Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shown</fullName>
                <default>true</default>
                <label>Visible</label>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Shown and Required</fullName>
                <label>Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Task_Field_Manager__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GC_Task_Field_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/LC_UserPrefrenceTabController.cls
/* LC_UserPrefrenceTabController - Apex Controller for LC_UserPrefrenceTab Lightning Component
* Author(s) - Namratha.P Salesforce Developer - SLK Software
* Date - 27/Dec/2018
*/

public  with sharing class LC_UserPrefrenceTabController {
    public class applicationException extends Exception {}
    @AuraEnabled
    Public static GC_Task_Field_Manager__c getTaskField(String projectCentralId){
        GC_Task_Field_Manager__c taskFieldObj = new GC_Task_Field_Manager__c();
        
        Set<String> objFields = new Set<String>();
        objFields = getFields();
        String fieldList = String.join(new List<String>(objFields), ',').toLowerCase();
        String query = 'SELECT ' + fieldList + ' FROM GC_Task_Field_Manager__c WHERE Connect2_Show__c =:projectCentralId';
        try{
            taskFieldObj = Database.query(query);
            if(Test.isRunningTest())
                throw new applicationException('Sorry! We don\'t do that here!!');
        }
        catch(EXception ex){
            taskFieldObj.User__c= UserInfo.getUserId();
            taskFieldObj.Connect2_Show__c =  projectCentralId;
        }
        return taskFieldObj;
    }
    
    @AuraEnabled
    Public static GC_Task_Field_Manager__c saveTaskFieldObj(id projectCentralId, GC_Task_Field_Manager__c TaskObj){
        TaskObj.Connect2_Show__c =  projectCentralId;
        upsert TaskObj;
        return TaskObj;
    }
    
    public static Set<String> getFields(){
        Set<String> objFields = new Set<String>();
        SObjectType objToken = Schema.getGlobalDescribe().get('GC_Task_Field_Manager__c');
        DescribeSObjectResult objDef = objToken.getDescribe();
        objFields = objDef.fields.getMap().keySet();
        return objFields;
    }
    
    /*@AuraEnabled
    public static void resetDisplayOptions(Id projectCentralId){
        GC_Task_Field_Manager__c taskField = [SELECT Id, Name FROM GC_Task_Field_Manager__c WHERE Connect2_Show__c =:projectCentralId LIMIT 1];
        Set<String> tfmFields = new Set<String>();
        tfmFields = getFields();
        SObject sTaskField = (SObject)taskField;
        // make all the fields as Shown
        for (String key : tfmFields) {
            if(key.contains('__c') && (key !='User__c' && key!='Connect2_Show__c' && key!='Hide_Order_Level_File_Upload__c')){
                sTaskField.put(key, 'Shown');
            }
        }
        sTaskField.put('User__c', UserInfo.getUserId());
        sTaskField.put('Hide_Order_Level_File_Upload__c', false);
        update taskField;
    }*/
    
    @AuraEnabled
    public static string restoreDefaultValues(Id projectCentralId){
        GC_Task_Field_Manager__c defaultTFM = new GC_Task_Field_Manager__c();
        List<GC_Task_Field_Manager__c> taskFields = [SELECT Id, Name FROM GC_Task_Field_Manager__c WHERE Connect2_Show__c =:projectCentralId LIMIT 1];
        
        if(taskFields != null && taskFields.size() > 0){
            defaultTFM = taskFields[0];
            defaultTFM.User__c = UserInfo.getUserId();
            defaultTFM.Hide_Order_Level_File_Upload__c = true;
            
            defaultTFM.Background__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Background__c.getDescribe());
            defaultTFM.Booth_Area_Discount__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Booth_Area_Discount__c.getDescribe());
            defaultTFM.Budget_Code__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Budget_Code__c.getDescribe());
            defaultTFM.Client_Layout_Notes__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Client_Layout_Notes__c.getDescribe());
            defaultTFM.Completion_Date_Time__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Completion_Date_Time__c.getDescribe());
            defaultTFM.Copy_Placement__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Copy_Placement__c.getDescribe());
            defaultTFM.Default_Completion_Date_Time__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Default_Completion_Date_Time__c.getDescribe());
            defaultTFM.Default_Installation_Delivery_Date_Time__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Default_Installation_Delivery_Date_Time__c.getDescribe());
            defaultTFM.Default_Removal_Date_Time__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Default_Removal_Date_Time__c.getDescribe());
            defaultTFM.Delivery_Area__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Delivery_Area__c.getDescribe());
            defaultTFM.File_Reference_Link_Folder__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.File_Reference_Link_Folder__c.getDescribe());
            defaultTFM.Installation_Delivery_Date_Time__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Installation_Delivery_Date_Time__c.getDescribe());
            defaultTFM.Installation_Method__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Installation_Method__c.getDescribe());
            defaultTFM.Onsite_Contact_Person__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Onsite_Contact_Person__c.getDescribe());
            defaultTFM.Onsite_Contact_Person_Number__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Onsite_Contact_Person_Number__c.getDescribe());
            defaultTFM.Outdoors__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Outdoors__c.getDescribe());
            defaultTFM.Price__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Price__c.getDescribe());
            defaultTFM.Removal_Date_Time__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Removal_Date_Time__c.getDescribe());
            defaultTFM.Save_Signs__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Save_Signs__c.getDescribe());
            defaultTFM.Sign_Copy__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Sign_Copy__c.getDescribe());
            defaultTFM.Sign_Title__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Sign_Title__c.getDescribe());
            defaultTFM.Sign_Type__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Sign_Type__c.getDescribe());
            defaultTFM.Sign_Type_Other__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Sign_Type_Other__c.getDescribe());
            defaultTFM.Single_Double_Sided__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Single_Double_Sided__c.getDescribe());
            defaultTFM.Special_Instructions_Client_Remarks__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.Special_Instructions_Client_Remarks__c.getDescribe());
            defaultTFM.User_Item_Description__c = LC_AppUtils.getDefaultValue(GC_Task_Field_Manager__c.User_Item_Description__c.getDescribe());
            
            update defaultTFM;
        }
        return defaultTFM.Id;
    }
}