unpackaged/main/default/objects/Account/fields/Alternative_Org_Name_1__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Org_Name_1__c</fullName>
    <label>Alternative Org Name 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Alternative_Org_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Org_Name_2__c</fullName>
    <label>Alternative Org Name 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Alternative_Org_Name_3__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Org_Name_3__c</fullName>
    <label>Alternative Org Name 3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Business_Type_Numerical_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Type_Numerical_Value__c</fullName>
    <formula>VALUE(CASE(Business_Type__c, &quot;Exhibitor&quot;, &quot;1&quot;, &quot;Firm&quot;, &quot;2&quot;, &quot;Contractor&quot;, &quot;3&quot;,&quot;1&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Type Numerical Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Cust_Type__c.field-meta.xml
<CustomField>
    <fullName>Cust_Type__c</fullName>
    <label>Cust Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01 Organiser</fullName>
            </value>
            <value>
                <fullName>11 Contractor</fullName>
            </value>
            <value>
                <fullName>12 Contractor</fullName>
            </value>
            <value>
                <fullName>13 Inter Company - Non Mes</fullName>
            </value>
            <value>
                <fullName>14 Melville Beck (Furniture)</fullName>
            </value>
            <value>
                <fullName>15 Gold Contractor</fullName>
            </value>
            <value>
                <fullName>17 Melville Events</fullName>
            </value>
            <value>
                <fullName>18 Logistics</fullName>
            </value>
            <value>
                <fullName>19 International Logistics</fullName>
            </value>
            <value>
                <fullName>20 Silver Contractor</fullName>
            </value>
            <value>
                <fullName>24 Graphics</fullName>
            </value>
            <value>
                <fullName>25 Elite</fullName>
            </value>
            <value>
                <fullName>35 Contractors Full Upfront Payment</fullName>
            </value>
            <value>
                <fullName>40 Contractor</fullName>
            </value>
            <value>
                <fullName>41 On Peak</fullName>
            </value>
            <value>
                <fullName>99 Exhibitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <inlineHelpText>Division, department or separate billing area for this account.</inlineHelpText>
    <label>Department</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EMEA__c.field-meta.xml
<CustomField>
    <fullName>EMEA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this account is EMEA and is to be transferred to SOP, check this box.</inlineHelpText>
    <label>EMEA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EMEA_Finance_Approved__c.field-meta.xml
<CustomField>
    <fullName>EMEA_Finance_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is automatically checked if not type Contractor or Firm. Only finance / admins can change this manually</description>
    <inlineHelpText>This indicates if the record can be synced with Salesforce. It is automatically set when not a firm or contractor. Only Finance and admins can manually check this box.</inlineHelpText>
    <label>EMEA Finance Approved</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NonVatable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vat_Number__c.field-meta.xml
<CustomField>
    <fullName>Vat_Number__c</fullName>
    <inlineHelpText>VAT number must be prefixed with country code from above list.</inlineHelpText>
    <label>Vat Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <description>Only to be used by EMEA Credit control</description>
    <label>Contractor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Exhibitor.recordType-meta.xml
<RecordType>
    <fullName>Exhibitor</fullName>
    <active>true</active>
    <description>E&amp;D Exhibitor Accounts</description>
    <label>Exhibitor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Firm.recordType-meta.xml
<RecordType>
    <fullName>Firm</fullName>
    <active>true</active>
    <description>A Management Company, Sponsor, Contractor (Prime and Sub), and Competitor related to Shows and Show Occurrences.</description>
    <label>Firm</label>
</RecordType>

unpackaged/main/default/classes/SOP_UpsertWrapper_Batch_Account.cls
public class SOP_UpsertWrapper_Batch_Account implements Database.Batchable<sObject>, Database.AllowsCallouts {

    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('SELECT Id, Name, EMEA__c, EMEA_Finance_Approved__c, BillingCountry, Department__c, Cust_Type__c, ' +
                                                  'Business_Type_Numerical_Value__c, Tax__c, Vat_Number__c, BillingStreet, BillingCity, ' +
                                                  'BillingPostalCode, BillingState, Alternative_Org_Name_1__c, Alternative_Org_Name_2__c, ' +
                                                  'Alternative_Org_Name_3__c, CreatedDate, LastModifiedDate ' +
                                             'FROM Account WHERE SOP_Sync__c = false AND EMEA__c = true AND EMEA_Finance_Approved__c = true AND BillingCountry != null AND BillingCountry != \'\'');
    }
   
    public void execute(Database.BatchableContext BC, List<Account> scope){
        for (Account acct : scope) {
            //If Account.EMEA is true and is approved by finance, call the SOP service
            //EMEA_Finance_Approved__c  is automatically set for all except Firm and Contractor via a field update
            if(acct.EMEA__c == True && acct.EMEA_Finance_Approved__c == True)
            {
                system.debug('emea and finance check passed, about to call upsert org');
                SOP_VIAD_V2.SalesforceUpsertOrganisationResult upsertResult; // = new SOP_VIAD_V2.SalesforceUpsertOrganisationResult();    
                SOP_VIAD_V2.SalesforceUpsertOrganisationRequest upsertRequest  = new SOP_VIAD_V2.SalesforceUpsertOrganisationRequest();
                    
                // set the organisation information
                upsertRequest.OrgName = acct.Name;
                upsertRequest.Country = acct.BillingCountry;
                upsertRequest.Department = acct.Department__c; 
                upsertRequest.CustCategory = acct.Cust_Type__c; // This is 99 for exhibitor etc
                upsertRequest.OrgType = (integer) acct.Business_Type_Numerical_Value__c; // 1, 2 or 3
                upsertRequest.SalesforceID = acct.id;
                upsertRequest.NonVatable = acct.Tax__c;
                upsertRequest.VatNumber = acct.Vat_Number__c;
            
                // set the billing address details
                upsertRequest.AddressLine1 = acct.BillingStreet;
                upsertRequest.AddressLine2 = '';
                upsertRequest.AddressLine3 = '';
                upsertRequest.AddressLine4 = '';
                upsertRequest.Town = acct.BillingCity;
                upsertRequest.Postcode = acct.BillingPostalCode;
                upsertRequest.County = acct.BillingState;
                upsertRequest.Country = acct.BillingCountry;
                upsertRequest.HouseNumber = '';
                upsertRequest.AltOrgName1 = acct.Alternative_Org_Name_1__c;
                upsertRequest.AltOrgName2 = acct.Alternative_Org_Name_2__c;
                upsertRequest.AltOrgName3 = acct.Alternative_Org_Name_3__c;
            
                //some defaults we have to set
                upsertRequest.IsDeleted = False;
                upsertRequest.IsDuplicate = False;
                upsertRequest.OwnerID = 69; // hard coded value for SOP
                
                // set other defaults
                upsertRequest.Created = acct.CreatedDate;
                upsertRequest.Updated = acct.LastModifiedDate;
                
                //public String OrgNotes;
                
                string upsertSerialisedRequest = JSON.serialize(upsertRequest);
                
                system.debug(upsertSerialisedRequest);
                SOP_UpsertWrapper.UpsertOrganisationNoFuture(upsertSerialisedRequest);
            }
            acct.SOP_Sync__c = true;
            update acct;
        }
    }

    public void finish(Database.BatchableContext BC){
        
    }
}