unpackaged/main/default/objects/Account/fields/EMEA__c.field-meta.xml
<CustomField>
    <fullName>EMEA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this account is EMEA and is to be transferred to SOP, check this box.</inlineHelpText>
    <label>EMEA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/GES_Status__c.field-meta.xml
<CustomField>
    <fullName>GES_Status__c</fullName>
    <label>GES Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exclusive</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>None of the above</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <externalId>true</externalId>
    <label>LMS Facility ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Merge_Flag__c.field-meta.xml
<CustomField>
    <fullName>Merge_Flag__c</fullName>
    <defaultValue>&quot;Y&quot;</defaultValue>
    <description>The merge flag for enabling auto Account records merge during Demand Tool Job</description>
    <label>Merge Flag</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Merge_Type__c.field-meta.xml
<CustomField>
    <fullName>Merge_Type__c</fullName>
    <description>This field provides the Account Merge Type</description>
    <label>Merge Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CT1-100% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>CT2-55% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>CT3-75% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>CT4-100% BEFORE PROD</fullName>
            </value>
            <value>
                <fullName>CT5-CONTRACT TERMS</fullName>
            </value>
            <value>
                <fullName>CT6-33-33% DEP NET</fullName>
            </value>
            <value>
                <fullName>CT7-50-25% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>CT8-NET 30</fullName>
            </value>
            <value>
                <fullName>CT9 -100% PRIOR SHIP</fullName>
            </value>
            <value>
                <fullName>CTL - 100% FINAL LOAD OUT</fullName>
            </value>
            <value>
                <fullName>CTLG-50% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>T10 - BALANCE DUE NET 45</fullName>
            </value>
            <value>
                <fullName>T11 - BALANCE DUE NET 60</fullName>
            </value>
            <value>
                <fullName>T12-75% DEP NET 10</fullName>
            </value>
            <value>
                <fullName>T13-55% DEP NET 45</fullName>
            </value>
            <value>
                <fullName>T14-75% DEP NET 45</fullName>
            </value>
            <value>
                <fullName>T15-75% DEP NET 60</fullName>
            </value>
            <value>
                <fullName>T16-55% DEP NET 60</fullName>
            </value>
            <value>
                <fullName>T17-50% DEP NET 45</fullName>
            </value>
            <value>
                <fullName>T18-2% 20 NET 60</fullName>
            </value>
            <value>
                <fullName>T19-2% 10 NET 30</fullName>
            </value>
            <value>
                <fullName>T20 - 15% DEP 50% INT N 60</fullName>
            </value>
            <value>
                <fullName>T21 - 50% DEP 50% INT N 30</fullName>
            </value>
            <value>
                <fullName>T22 - 25% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>T23 - 50% DEP 2% 15 NET 45</fullName>
            </value>
            <value>
                <fullName>T24-50% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>T25-50% DEP 40% INT N 30</fullName>
            </value>
            <value>
                <fullName>T26-2.5% 15 NET 90</fullName>
            </value>
            <value>
                <fullName>T27-55% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>T28 - NET 15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person MUST be same as Account Owner.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Firm.recordType-meta.xml
<RecordType>
    <fullName>Firm</fullName>
    <active>true</active>
    <description>A Management Company, Sponsor, Contractor (Prime and Sub), and Competitor related to Shows and Show Occurrences.</description>
    <label>Firm</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/International.recordType-meta.xml
<RecordType>
    <fullName>International</fullName>
    <active>true</active>
    <label>International</label>
</RecordType>

unpackaged/main/default/objects/AR_Customer_Info__c/AR_Customer_Info__c.object-meta.xml
<CustomObject>
    <label>AR Customer Info</label>
    <nameField>
        <label>AR Customer Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AR Customer Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AR_Customer_Info__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AR Customer Info</relationshipLabel>
    <relationshipName>AR_Customer_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Customer_Info__c/fields/AR_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>AR_Customer_Number__c</fullName>
    <label>AR Customer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AR_Customer_Info__c/fields/GBMS_ID__c.field-meta.xml
<CustomField>
    <fullName>GBMS_ID__c</fullName>
    <label>GBMS ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AR_Customer_Info__c/fields/Oracle_AR_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_AR_Customer_ID__c</fullName>
    <label>Oracle AR Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/GBMS_ID__c.field-meta.xml
<CustomField>
    <fullName>GBMS_ID__c</fullName>
    <label>Merged GBMS ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Oracle_AR_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_AR_Customer_ID__c</fullName>
    <label>Merged Oracle AR Customer ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/GBMS_ID__c.field-meta.xml
<CustomField>
    <fullName>GBMS_ID__c</fullName>
    <label>Merged GBMS ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Show Job Number.</inlineHelpText>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <formula>Facility__r.LMS_Facility_ID__c</formula>
    <inlineHelpText>Facility ID (acronym)</inlineHelpText>
    <label>Facility ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary sales person (regardless of user type)</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N40000001qZlCEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <description>The show type field from Show object, only for Custom Build opportunities</description>
    <formula>IF( RecordTypeId = &#39;01240000000DuxL&#39;,  TEXT( Show_Name__r.Show_Type__c ) ,  TEXT( Show_Occurrence__r.Show_Name__r.Show_Type__c ) )</formula>
    <inlineHelpText>The Show type</inlineHelpText>
    <label>Show Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account Name.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shows (Account)</relationshipLabel>
    <relationshipName>Shows2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_ID__c.field-meta.xml
<CustomField>
    <fullName>Show_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Legacy System Identifier.</inlineHelpText>
    <label>Show ID (LMS)</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <inlineHelpText>CEIR Industry Groupings</inlineHelpText>
    <label>Show Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Services</fullName>
            </value>
            <value>
                <fullName>Consumer Goods and Retail Trade</fullName>
            </value>
            <value>
                <fullName>Discretionary Consumer Goods &amp; Services</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food Sector</fullName>
            </value>
            <value>
                <fullName>Financial, Legal and Real Estate</fullName>
            </value>
            <value>
                <fullName>Government, Public &amp; Non-Profit Services</fullName>
            </value>
            <value>
                <fullName>Building, Construction, Home &amp; Repair</fullName>
            </value>
            <value>
                <fullName>Industrial / Heavy Machinery / Finished Business Outputs</fullName>
            </value>
            <value>
                <fullName>Communications &amp; Information Technology</fullName>
            </value>
            <value>
                <fullName>Medical &amp; Healthcare</fullName>
            </value>
            <value>
                <fullName>Raw Materials &amp; Science</fullName>
            </value>
            <value>
                <fullName>Sporting Goods, Travel and Amusement</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Museum, Traveling Exhibition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TestBatchableUpdate.cls
/*  Class: BatchableOpportunityUpdate
    Desc: Test Class
    Author: Gaurav
    Created Date: 09 Feb 2018
*/

    @isTest(SeeAllData=false)
    
    Private class TestBatchableUpdate{
    
    private static User ADMIN_USER = [select id  from user where username like 'accountmerge%' AND isActive = true LIMIT 1];
  
    static testMethod void unitTestBatchableOpportunity() {
        system.runAs(ADMIN_USER){
    
   
   List<Account> acList = new List<Account>();
    Account acc = new Account();
    acc.Name = 'Test';
    acc.BillingStreet = 'Test123';
    acc.BillingCity = 'Delhi';
    acc.BillingState = 'New Delhi';
    acc.BillingCountry = 'India';
    acc.merge_flag__c = 'MP';
    acc.merge_type__c = 'TopAcc';
    acc.RecordTypeId = Label.Account_Exhibitor;
    acc.EMEA__c = false;
    
    acList.add(acc);
    insert acList;
    
    acc.ownerid = '00540000001bR7gAAE';
    update acc;
    
    
    final map<Id,Account> accmap = new map<Id,Account>(); 
    accmap.put(acc.id, acc);   
    
    List<AR_Customer_Info__c> arcList = new List<AR_Customer_Info__c>();
    AR_Customer_Info__c arc = new AR_Customer_Info__c();
    arc.AR_Customer_Number__c = '87123';
    arc.GBMS_ID__c = '78578';
    arc.Oracle_AR_Customer_ID__c = '9879';
    arc.Name = '000000';
    arc.Payment_Terms__c= 'Pay Term';
    
    
    arcList.add(arc);
    insert arcList ;
    
        
        //Create User (for Owner)
      ID OwnerId = UserInfo.getUserId();
      
      //Create User Sales Person
      ID SalesRepId = UserInfo.getUserId();
           
      RecordType FacilityRecordType = [Select Id From RecordType Where SObjectType = 'Account' And Name = 'Facility'];
      Id FacilityRecordTypeId = FacilityRecordType.Id;
                   
      RecordType FirmRecordType = [Select Id From RecordType Where SObjectType = 'Account' And Name = 'Firm'];
      Id FirmRecordTypeId = FirmRecordType.Id;
              
      RecordType SalesRepRecordType = [Select Id From RecordType Where SObjectType = 'Opportunity' And Name = 'Sales Rep Show Occurrence'];
      Id SalesRepRecordTypeId = SalesRepRecordType.Id;      
      
      //Create Facility Account
      Account Facility = new Account();
      Facility.Sales_Person__c = SalesRepId;
      Facility.Name = 'MyTestFacilityName';
      Facility.Type = 'Hotel';
      Facility.GES_Status__c = 'Preferred';
      Facility.LMS_Facility_ID__c = 'ABCFAC';
      Facility.BillingStreet = '950 Grier Dr';
      Facility.BillingCity = 'Las Vegas';
      Facility.BillingPostalCode = '89119-0000';
      Facility.BillingState = 'NV';
      Facility.BillingCountry = 'US';
      Facility.RecordTypeId = FacilityRecordTypeId;
              
      Database.insert(Facility);
                      
      //Create Firm Account
      Account Firm = new Account();
      Firm.Sales_Person__c = SalesRepId;
      Firm.Name = 'SONY ENTERTAINMENT INC';
      Firm.Phone = '7022631500';
      Firm.BillingStreet = '950 Grier Dr';
      Firm.BillingCity = 'Las Vegas';
      Firm.BillingPostalCode = '89119-0000';
      Firm.BillingState = 'NV';
      Firm.BillingCountry = 'US';
      Firm.RecordTypeId = FirmRecordTypeId;
      
      Database.insert(Firm);
      
      //Create Show
      Show__c Show = new Show__c();
      Show.Sales_Person__c = SalesRepId;
      Show.Account__c = Firm.Id;
      Show.Name ='International CES';
      Show.Show_Type__c = 'Food Sector';
      Show.Show_ID__c = '123456';
      
      Database.insert(Show);            
             
      Opportunity Opp1 = new Opportunity();
      Opp1.Job_Number__c = '201212313';        
      Opp1.OwnerId = OwnerId;   
      Opp1.Sales_Person__c = SalesRepId;        
      Opp1.Sales_Location__c = '110- Las Vegas';        
      Opp1.Name = 'MyTestShow # 1';        
      Opp1.Prime_Contractor__c = null;        
      Opp1.Production_Location__c = '110- Las Vegas';        
      Opp1.Facility__c = Facility.Id;        
      Opp1.StageName = 'SL1';        
      Opp1.Amount = 1000;        
      Opp1.Probability = 25;        
      Opp1.Type = 'ITYFTY';        
      Opp1.New_Repeat__c = 'New';        
      Opp1.Frequency__c = 'B1';        
      Opp1.AccountId = Firm.Id;       
      Opp1.Show_Name__c = Show.Id;        
      Opp1.RecordTypeId = SalesRepRecordTypeId;                
      Opp1.Show_Open_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,1);       
      Opp1.Show_Close_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,2);        
      Opp1.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
      opp1.Requested_Stage__c = '';
      Database.insert(Opp1);  
          
      Opp1.RFP_Due_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,2);
      Opp1.Requested_Stage__c = 'PS';
      Database.update(Opp1);
         
    map<Id, Opportunity> opptyMap = new map<Id, Opportunity> ();
    opptyMap.put(opp1.Id, opp1);
    
        
    Test.StartTest();
    BatchableOpportunityUpdate obj = new BatchableOpportunityUpdate(opptyMap);
    Database.executeBatch(obj);
    
        
    Test.StopTest();
            
    }
       
       
   } 

    static testMethod void unitTestBatchableContact() {
        system.runAs(ADMIN_USER){
    
   
    List<AR_Customer_Info__c> arcList = new List<AR_Customer_Info__c>();
    AR_Customer_Info__c arc = new AR_Customer_Info__c();
    arc.AR_Customer_Number__c = '87123';
    arc.GBMS_ID__c = '78578';
    arc.Oracle_AR_Customer_ID__c = '9879';
    arc.Name = '000000';
    arc.Payment_Terms__c= 'Pay Term';
    
    
    arcList.add(arc);
    insert arcList ;
    
   List<Account> acList = new List<Account>();
    Account acc = new Account();
    acc.Name = 'Test';
    acc.BillingStreet = 'Test123';
    acc.BillingCity = 'Delhi';
    acc.BillingState = 'New Delhi';
    acc.BillingCountry = 'India';
    acc.merge_flag__c = 'MP';
    acc.merge_type__c = 'TopAcc';
    acc.RecordTypeId = Label.Account_Exhibitor;
    acc.EMEA__c = false;
    
    acList.add(acc);
    insert acList;
    
    acc.ownerid = '00540000001bR7gAAE';
    update acc;
    
    
    final map<Id,Account> accmap = new map<Id,Account>(); 
    accmap.put(acc.id, acc);   
    
    
       List<Contact> cntList = new List<Contact>();
        Contact BC2Contact = new Contact();
        BC2Contact.FirstName = 'Sahara';
        BC2Contact.LastName = 'Jones';
        BC2Contact.Email = 'sjones@ges.com';
        BC2Contact.Phone = '7022631500';
        BC2Contact.MailingStreet = '7000 Lindell Street';
        BC2Contact.MailingCity = 'Las Vegas';
        BC2Contact.MailingState = 'NV';
        BC2Contact.MailingCountry = 'USA';
        BC2Contact.MailingPostalCode = '89119';
        system.debug('Account ID is ---->'+acc.id);
        BC2Contact.AccountId = acc.id;
        
        cntList.add(BC2Contact);
        insert cntList;
        
        BC2Contact.ownerid = '00540000001bR7gAAE';
        update BC2Contact;
        
    map <Id, Contact> cnctMap = new map <Id, Contact>();
    cnctMap.put(BC2Contact.Id, BC2Contact);
    
    Test.StartTest();
       
    BatchableContactUpdate obj1 = new BatchableContactUpdate(cnctMap);
    Database.executeBatch(obj1);
    
    Test.StopTest();
            
    }
       
       
   } 
 }