unpackaged/main/default/objects/Account/fields/EMEA__c.field-meta.xml
<CustomField>
    <fullName>EMEA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this account is EMEA and is to be transferred to SOP, check this box.</inlineHelpText>
    <label>EMEA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Melissa_Address__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Address__c</fullName>
    <label>Melissa Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Melissa_City__c.field-meta.xml
<CustomField>
    <fullName>Melissa_City__c</fullName>
    <label>Melissa City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Melissa_Country__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Country__c</fullName>
    <label>Melissa Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Melissa_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Integration_Status__c</fullName>
    <label>Melissa Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Melissa_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Postal_Code__c</fullName>
    <label>Melissa Postal Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Melissa_Results__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Results__c</fullName>
    <label>Melissa Results</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Melissa_State__c.field-meta.xml
<CustomField>
    <fullName>Melissa_State__c</fullName>
    <label>Melissa State</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Exhibitor.recordType-meta.xml
<RecordType>
    <fullName>Exhibitor</fullName>
    <active>true</active>
    <description>E&amp;D Exhibitor Accounts</description>
    <label>Exhibitor</label>
</RecordType>

unpackaged/main/default/objects/MelissaSetting__c/MelissaSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is specify, melissa switch, Counter ,Melissa error etc. Don&#39;t change the Name field value.It is use in apex melissa classes.</description>
    <label>Melissa Setting</label>
</CustomObject>

unpackaged/main/default/objects/oAuth__c/oAuth__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>oAuth Settings</label>
</CustomObject>

unpackaged/main/default/objects/oAuth__c/fields/Auth_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Auth_Endpoint__c</fullName>
    <label>Auth Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/oAuth__c/fields/DataComURL__c.field-meta.xml
<CustomField>
    <fullName>DataComURL__c</fullName>
    <label>DataComURL</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/oAuth__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/oAuth__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TestEnrichmentOfAddressAccountSweep.cls
/* Class Name: EnrichmentOfAddressAccountSweep

    Author: Nehal Jain
    Created Date: 5/11/2017*/


@isTest(SeeAllData=false)
                                
public class TestEnrichmentOfAddressAccountSweep  {

private static void createCustomSetting(){
    List<MelissaSetting__c> listSetting = new List<MelissaSetting__c>();
    MelissaSetting__c instMsetting=new MelissaSetting__c(Name= 'MelisaPersonatorCountry',Value__c = 'US');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa GlobalAddress URL',Value__c = 'https://address.melissadata.net/V3/WEB/GlobalAddress/doGlobalAddress');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Personator URL',Value__c = 'https://personator.melissadata.net/v3/WEB/ContactVerify/doContactVerify');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Error Codes',Value__c = 'AE01');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa ClientId',Value__c = 'FWhH1f9hr-7NpBDjRxOu-R**');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Options',Value__c = 'DELIVERYLINES:ON');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Min Address Length',Value__c = '1');
    listSetting.add(instMsetting);
    
    
    insert listSetting;
    
    
    oAuth__c myoAuth = new oAuth__c();
    myoAuth.Auth_Endpoint__c = 'https://test123.salesforce.com';
    myoAuth.Client_ID__c = '3MVG9Pb';
    myoAuth.Client_Secret__c = '6888';
    myoAuth.Username__c='test@ges.com';
    myoAuth.Password__c='123456'; 
    myoAuth.name = 'DataComMatch';
    myoAuth.datacomUrl__C='https://test.com/services/data/v32.0/match/DunsRightMatchEngine/DatacloudCompany/DunsRightMatchRule';
    insert myoAuth;
    
}

static  testMethod void testMethod1() {

createCustomSetting();

//RecordType rt = [SELECT id,Name FROM RecordType WHERE SobjectType='Account' and name= 'Exhibitor' LIMIT 1];

    List<Account> AccLst= new List<Account>();
    Account Acc= new Account();
    Acc.Name= 'Test';
    Acc.BillingStreet= 'Test1';
    Acc.BillingCity= 'AVALON';
    Acc.BillingState= 'CA';
    Acc.BillingPostalCode= '201013';
    Acc.BillingCountry= 'US';
    //Acc.EMEA__c = False; 
    Acc.Melissa_Integration_Status__c = 'Melissa Error';
   // Acc.RecordTypeId = rt.id;
  //  Acc.Test__c = True;
    Acc.Melissa_Address__c   ='Test1';
    Acc.Melissa_Country__c='US';
    Acc.Melissa_City__c='AVALON';
    Acc.Melissa_State__c='CA';
    Acc.Melissa_Postal_Code__c ='201013';
    Acc.Melissa_Country__c='US';
    Acc.Melissa_Results__c ='AE01';
    AccLst.add(Acc);
    insert AccLst;
    
    
    
  BatchableDataComMockAccountSweep instBatch= new BatchableDataComMockAccountSweep();
    instBatch.accountId=AccLst[0].id;
    Test.setMock(HttpCalloutMock.class, instBatch);
     
                   
    
    
    Test.StartTest();
    EnrichmentOfAddressAccountSweep macc= new EnrichmentOfAddressAccountSweep();
    macc.enrichMelissaAddress(AccLst);
    
    Test.StopTest();
}

static  testMethod void testMethod2() {

createCustomSetting();



//RecordType rt = [SELECT id,Name FROM RecordType WHERE SobjectType='Account' and name= 'Exhibitor' LIMIT 1];

    List<Account> AccLst= new List<Account>();
    Account Acc= new Account();
    Acc.Name= 'Test';
    Acc.BillingStreet= 'Test1';
    Acc.BillingCity= 'AVALON';
    Acc.BillingState= 'CA';
    Acc.BillingPostalCode= '201013';
    Acc.BillingCountry= 'Canada';
    //Acc.EMEA__c = False; 
    Acc.Melissa_Integration_Status__c = 'Success';
    Acc.Melissa_Address__c   ='Test1';
    Acc.Melissa_Country__c='CA';
    Acc.Melissa_City__c='AVALON';
    Acc.Melissa_State__c='CA';
    Acc.Melissa_Postal_Code__c ='201013';
    Acc.Melissa_Results__c ='AS01';
    AccLst.add(Acc);
    insert AccLst;
    
   
    BatchableDataComMockAccountSweep instBatch= new BatchableDataComMockAccountSweep();
    instBatch.accountId=AccLst[0].id;
    Test.setMock(HttpCalloutMock.class, instBatch);
     
                   
   
    
    Test.StartTest();
    EnrichmentOfAddressAccountSweep macc= new EnrichmentOfAddressAccountSweep();
    macc.enrichMelissaAddress(AccLst);
    
    Test.StopTest();
}






}