unpackaged/main/default/objects/Account/fields/EMEA__c.field-meta.xml
<CustomField>
    <fullName>EMEA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this account is EMEA and is to be transferred to SOP, check this box.</inlineHelpText>
    <label>EMEA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Merge_Flag__c.field-meta.xml
<CustomField>
    <fullName>Merge_Flag__c</fullName>
    <defaultValue>&quot;Y&quot;</defaultValue>
    <description>The merge flag for enabling auto Account records merge during Demand Tool Job</description>
    <label>Merge Flag</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Merge_Type__c.field-meta.xml
<CustomField>
    <fullName>Merge_Type__c</fullName>
    <description>This field provides the Account Merge Type</description>
    <label>Merge Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CT1-100% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>CT2-55% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>CT3-75% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>CT4-100% BEFORE PROD</fullName>
            </value>
            <value>
                <fullName>CT5-CONTRACT TERMS</fullName>
            </value>
            <value>
                <fullName>CT6-33-33% DEP NET</fullName>
            </value>
            <value>
                <fullName>CT7-50-25% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>CT8-NET 30</fullName>
            </value>
            <value>
                <fullName>CT9 -100% PRIOR SHIP</fullName>
            </value>
            <value>
                <fullName>CTL - 100% FINAL LOAD OUT</fullName>
            </value>
            <value>
                <fullName>CTLG-50% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>T10 - BALANCE DUE NET 45</fullName>
            </value>
            <value>
                <fullName>T11 - BALANCE DUE NET 60</fullName>
            </value>
            <value>
                <fullName>T12-75% DEP NET 10</fullName>
            </value>
            <value>
                <fullName>T13-55% DEP NET 45</fullName>
            </value>
            <value>
                <fullName>T14-75% DEP NET 45</fullName>
            </value>
            <value>
                <fullName>T15-75% DEP NET 60</fullName>
            </value>
            <value>
                <fullName>T16-55% DEP NET 60</fullName>
            </value>
            <value>
                <fullName>T17-50% DEP NET 45</fullName>
            </value>
            <value>
                <fullName>T18-2% 20 NET 60</fullName>
            </value>
            <value>
                <fullName>T19-2% 10 NET 30</fullName>
            </value>
            <value>
                <fullName>T20 - 15% DEP 50% INT N 60</fullName>
            </value>
            <value>
                <fullName>T21 - 50% DEP 50% INT N 30</fullName>
            </value>
            <value>
                <fullName>T22 - 25% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>T23 - 50% DEP 2% 15 NET 45</fullName>
            </value>
            <value>
                <fullName>T24-50% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>T25-50% DEP 40% INT N 30</fullName>
            </value>
            <value>
                <fullName>T26-2.5% 15 NET 90</fullName>
            </value>
            <value>
                <fullName>T27-55% DEP NET 30</fullName>
            </value>
            <value>
                <fullName>T28 - NET 15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AR_Customer_Info__c/AR_Customer_Info__c.object-meta.xml
<CustomObject>
    <label>AR Customer Info</label>
    <nameField>
        <label>AR Customer Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AR Customer Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AR_Customer_Info__c/fields/AR_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>AR_Customer_Number__c</fullName>
    <label>AR Customer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AR_Customer_Info__c/fields/GBMS_ID__c.field-meta.xml
<CustomField>
    <fullName>GBMS_ID__c</fullName>
    <label>GBMS ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AR_Customer_Info__c/fields/Oracle_AR_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_AR_Customer_ID__c</fullName>
    <label>Oracle AR Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/GBMS_ID__c.field-meta.xml
<CustomField>
    <fullName>GBMS_ID__c</fullName>
    <label>Merged GBMS ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Oracle_AR_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_AR_Customer_ID__c</fullName>
    <label>Merged Oracle AR Customer ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Oracle_AR_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_AR_Customer_Number__c</fullName>
    <label>Merged Oracle AR Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/GBMS_ID__c.field-meta.xml
<CustomField>
    <fullName>GBMS_ID__c</fullName>
    <label>Merged GBMS ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Oracle_AR_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_AR_Customer_Number__c</fullName>
    <label>Merged Oracle AR Customer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/Oracle_Show_Booth__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booths from Oracle</description>
    <label>Booth</label>
    <nameField>
        <label>Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booths</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/Booth_Account_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Booth_Account_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Booth Account Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/GBMS_ID__c.field-meta.xml
<CustomField>
    <fullName>GBMS_ID__c</fullName>
    <label>Merged GBMS ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/Oracle_AR_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_AR_Customer_ID__c</fullName>
    <label>Merged Oracle AR Customer ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/Oracle_AR_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Oracle_AR_Customer_Number__c</fullName>
    <label>Merged Oracle AR Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>Custom object to support Quote functionality for Logistics and other businesses (e.g. Graphics)</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote__c/fields/AR_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>AR_Customer_Number__c</fullName>
    <description>To keep the oracle AR customer number of loosing accounts on Quote</description>
    <label>Merged Oracle AR Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/GBMS_ID__c.field-meta.xml
<CustomField>
    <fullName>GBMS_ID__c</fullName>
    <description>To keep the oracle AR customer number of loosing accounts on Quote</description>
    <label>Merged GBMS ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Merged_AR_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Merged_AR_Customer_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merge AR Customer Number</label>
    <referenceTo>AR_Customer_Info__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Oracle_AR_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_AR_Customer_ID__c</fullName>
    <label>Merged Oracle AR Customer ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AccountTriggerHandlerTest.cls
/*  Class: AccountTriggerHandler
    Desc: Test Class
    Author: Gaurav
    Created Date: 10 Oct 2017
*/

    @isTest(SeeAllData=false)
    
    Private class AccountTriggerHandlerTest{
    Private static testmethod void TesttriggerControllerMethod(){
    
    
   
   List<Account> acList = new List<Account>();
    Account acc = new Account();
    acc.Name = 'Test';
    acc.BillingStreet = 'Test123';
    acc.BillingCity = 'Delhi';
    acc.BillingState = 'New Delhi';
    acc.BillingCountry = 'India';
    acc.merge_flag__c = 'MP';
    acc.merge_type__c = 'TopAcc';
    acc.RecordTypeId = Label.Account_Exhibitor;
    acc.EMEA__c = false;
    
    acList.add(acc);
    insert acList;
    
    acc.ownerid = '00540000001bR7gAAE';
    update acc;
    
    
    final map<Id,Account> accmap = new map<Id,Account>(); 
    accmap.put(acc.id, acc);   
    
    List<AR_Customer_Info__c> arcList = new List<AR_Customer_Info__c>();
    AR_Customer_Info__c arc = new AR_Customer_Info__c();
    arc.AR_Customer_Number__c = '87123';
    arc.GBMS_ID__c = '78578';
    arc.Oracle_AR_Customer_ID__c = '9879';
    arc.Name = '000000';
    arc.Payment_Terms__c= 'Pay Term';
    
    
    arcList.add(arc);
    insert arcList ;
    
    
    List<Quote__c> qutList = new List<Quote__c>();
    Quote__c qt = new Quote__c();
    
    qt.AR_Customer_Number__c = '87123';
    qt.GBMS_ID__c = '78578';
    qt.Oracle_AR_Customer_ID__c = '9879';
       
        
    
    qutList.add(qt);
    insert qutList ;
    
    
    qt.AR_Customer_Number__c = '87123';
    qt.GBMS_ID__c = '78578';
    qt.Oracle_AR_Customer_ID__c = '9879';
   // qt.Merged_AR_Customer_Number__c = '196553';
    
    update qt;
   
   Contact BC2Contact = new Contact();
        BC2Contact.FirstName = 'Sahara';
        BC2Contact.LastName = 'Jones';
        BC2Contact.Email = 'sjones@ges.com';
        BC2Contact.Phone = '7022631500';
        BC2Contact.MailingStreet = '7000 Lindell Street';
        BC2Contact.MailingCity = 'Las Vegas';
        BC2Contact.MailingState = 'NV';
        BC2Contact.MailingCountry = 'USA';
        BC2Contact.MailingPostalCode = '89119';
        
           
    List<Opportunity> opptList = new List<Opportunity>();
    Opportunity oppty= new Opportunity ();
    oppty.Oracle_AR_Customer_Number__c= '87123';
    oppty.GBMS_ID__c= '78578';
    oppty.Oracle_AR_Customer_ID__c= '9879';
    oppty.Name= 'Test Oppty';
    oppty.StageName = 'Closed Won';
    oppty.CloseDate = System.today() - 25;
        
    
    opptList.add(oppty);
    insert opptList;
    
    List<String> listOpportunityWrapper=new List<String>();       
    OpportunityWrapper oppWrpObj=new OpportunityWrapper(oppty.ID,oppty.Oracle_AR_Customer_Number__c,oppty.GBMS_ID__c,oppty.Oracle_AR_Customer_ID__c);
    listOpportunityWrapper.add(JSON.serialize(oppWrpObj));
    
    List<Oracle_Show_Booth__c> bthList = new List<Oracle_Show_Booth__c>();
    Oracle_Show_Booth__c boo = new Oracle_Show_Booth__c();
    boo.Oracle_AR_Customer_Number__c = '87123';
    boo.GBMS_ID__c = '78578';
    boo.Oracle_AR_Customer_ID__c = '9879';
    boo.Booth_Account_Deleted__c = True;   
     
          
    Test.StartTest();
    AccountTriggerHandler obj= new AccountTriggerHandler();
    obj.triggerControllerMethod(accmap);
    obj.QuoteUpdateOnAccountdelete(accmap);
    obj.OpportunityUpdateOnAccountdeleteBatch(accmap);
    obj.ContactUpdateOnAccountdeleteBatch(accmap);
    //obj.OpportunityUpdateOnAccountdelete(accmap);
    obj.BoothUpdateOnAccountdelete(accmap);
    //obj.contactUpdateOnAccountdelete(accmap);
    obj.ARcustomerUpdateOnAccountdelete(accmap);
    AccountTriggerHandler.updateOpportunityInMerge(listOpportunityWrapper);  
    AccountTriggerHandler.updateProcessedFlag(accmap.keySet()); 
            
     Test.StopTest();
    
    }
       
        
 }