unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/LMS_Firm_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Firm_ID__c</fullName>
    <externalId>true</externalId>
    <label>LMS Firm ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_1__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_1__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 1</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_2__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_2__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 2</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_3__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_3__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 3</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_4__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_4__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 4</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_5__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_5__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 5</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <description>Displays facility of show</description>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility_lk__c.field-meta.xml
<CustomField>
    <fullName>Facility_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Connect2_Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <description>Displays the opportunity Id</description>
    <label>Opportunity Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <description>Displays the opportunity name</description>
    <label>Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_1__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_1__c</fullName>
    <inlineHelpText>Show Hours Day 1.</inlineHelpText>
    <label>Exhibit Hall Hours Day 1</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_2__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_2__c</fullName>
    <inlineHelpText>Show Hours Day 2.</inlineHelpText>
    <label>Exhibit Hall Hours Day 2</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_3__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_3__c</fullName>
    <inlineHelpText>Show Hours Day 3.</inlineHelpText>
    <label>Exhibit Hall Hours Day 3</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_4__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_4__c</fullName>
    <inlineHelpText>Show Hours Day 4.</inlineHelpText>
    <label>Exhibit Hall Hours Day 4</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_5__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_5__c</fullName>
    <inlineHelpText>Show Hours Day 5.</inlineHelpText>
    <label>Exhibit Hall Hours Day 5</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibitor_Move_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Exhibitor_Move_In_Date__c</fullName>
    <inlineHelpText>Date when exhibitors will start move in</inlineHelpText>
    <label>Exhibitor Move-In Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Venue in which exhibition takes place</inlineHelpText>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Facility type account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Show Occurrences (Private)</relationshipLabel>
    <relationshipName>R00N40000001pjqSEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Show Job Number.</inlineHelpText>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Move_Out__c.field-meta.xml
<CustomField>
    <fullName>Move_Out__c</fullName>
    <inlineHelpText>Date when exhibitors start move out</inlineHelpText>
    <label>Exhibitor Move-Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date_Time__c</fullName>
    <description>Blitz field for Opportunity Integration</description>
    <inlineHelpText>For EMEA AV Use Only.</inlineHelpText>
    <label>Show End Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date_Time__c</fullName>
    <description>Blitz field for Opportunity Integration</description>
    <label>Show Start Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/LC_Connect2ShowCreateControllerTest.cls
@isTest
public class LC_Connect2ShowCreateControllerTest {
    
   
    static TestMethod void testAllMethods() {
        Opportunity oppObj1 = GC_TestUtils.getTestOpportunity();
        
        Opportunity oppObj2 = new Opportunity();
        oppObj2.Name = 'LA Auto Show';
        oppObj2.AccountId = oppObj1.AccountId;
        oppObj2.Facility__c = oppObj1.Facility__c;
        oppObj2.CloseDate = System.Today() + 40;
        oppObj2.StageName = 'CV';
        oppObj2.Amount = 30000;
        oppObj2.Show_Start_Date_Time__c = System.Today() + 12;
        oppObj2.Show_End_Date_Time__c = System.Today() + 17;
        oppObj2.Exhibit_Hall_Hours_Day_1__c = '5:00 PM To 8:00 PM';
        oppObj2.Exhibit_Hall_Hours_Day_2__c = '7:00 AM To 6:30 PM';
        oppObj2.Exhibit_Hall_Hours_Day_3__c = '8:00 AM To 4:00 PM';
        oppObj2.Exhibit_Hall_Hours_Day_4__c = '9:00 AM To 10:00 PM';
        oppObj2.Exhibit_Hall_Hours_Day_5__c = '9:00 AM To 10:00 PM';
        oppObj2.Exhibitor_Move_In_Date__c = System.Today() + 11;
        oppObj2.RecordTypeId = oppObj1.RecordTypeId;
        oppObj2.Prime_Contractor__c = oppObj1.Prime_Contractor__c;
        oppObj2.Move_Out__c = System.Today() + 14;
        insert oppObj2;
            
        GC_Connect2_Show__c connect2Show = new GC_Connect2_Show__c();  
        Account testAcc = GC_TestUtils.getTestFacility();
        testAcc.LMS_Firm_ID__c = '7356';
        testAcc.BillingCity = 'ny';
        testAcc.BillingPostalCode = 'test';
        testAcc.BillingState = 'test';
        testAcc.BillingCountry = 'test';
        upsert testAcc;
        
        connect2Show.Opportunity_Name__c = '01453-201601-';
        connect2Show.Opportunity_Id__c = oppObj2.Id;
        connect2Show.Show_Name__c = 'test show';
        connect2Show.Job_Number__c = '12345';
        connect2Show.Show_Start_Date__c = Date.today();
        connect2Show.Show_End_Date__c = Date.today();
        connect2Show.Exhibit_Hall_Hours_Day_1__c = '5:00 PM To 8:00 PM';
        connect2Show.Exhibit_Hall_Hours_Day_2__c = '7:00 AM To 6:30 PM';
        connect2Show.Exhibit_Hall_Hours_Day_3__c = '8:00 AM To 4:00 PM';
        connect2Show.Exhibit_Hall_Hours_Day_4__c = '9:00 AM To 10:00 PM';
        connect2Show.Exhibit_Hall_Hours_Day_5__c = '9:00 AM To 10:00 PM';
        connect2Show.Opportunity_Name__c = '01453-201601-';
        connect2Show.Job_Number__c = '123456';
        connect2Show.Facility_lk__c = testAcc.Id;
        insert connect2Show;
                
        LC_Connect2ShowCreateController.isOpportunityUnique(oppObj2.Id);
        LC_Connect2ShowCreateController.isOpportunityUnique(oppObj1.Id);
        LC_Connect2ShowCreateController.getFacilityAccFields(testAcc.Id);
    }
}