unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/GES_Status__c.field-meta.xml
<CustomField>
    <fullName>GES_Status__c</fullName>
    <label>GES Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exclusive</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>None of the above</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <externalId>true</externalId>
    <label>LMS Facility ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person MUST be same as Account Owner.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Firm.recordType-meta.xml
<RecordType>
    <fullName>Firm</fullName>
    <active>true</active>
    <description>A Management Company, Sponsor, Contractor (Prime and Sub), and Competitor related to Shows and Show Occurrences.</description>
    <label>Firm</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/International.recordType-meta.xml
<RecordType>
    <fullName>International</fullName>
    <active>true</active>
    <label>International</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Show Job Number.</inlineHelpText>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <formula>Facility__r.LMS_Facility_ID__c</formula>
    <inlineHelpText>Facility ID (acronym)</inlineHelpText>
    <label>Facility ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Production_Location__c.field-meta.xml
<CustomField>
    <fullName>Production_Location__c</fullName>
    <description>As determined by Operations / Exhibitions account management. Any additions or edits also need to be made to the Locations object.</description>
    <inlineHelpText>Operational location producing exhibition</inlineHelpText>
    <label>Production Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120-OnPeak</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix</fullName>
            </value>
            <value>
                <fullName>180 - Registration</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles, CA</fullName>
            </value>
            <value>
                <fullName>230-Intl Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>270- Corporate Events (Marketing Dept only)</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460 - Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470 - Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480- Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Florida</fullName>
            </value>
            <value>
                <fullName>530- New Orleans</fullName>
            </value>
            <value>
                <fullName>610- Portland, Seattle</fullName>
            </value>
            <value>
                <fullName>710- Chicago, Cleveland, Milwaukee, St. Louis</fullName>
            </value>
            <value>
                <fullName>810- New York &amp; Boston</fullName>
            </value>
            <value>
                <fullName>830-DC, Philadelphia</fullName>
            </value>
            <value>
                <fullName>890- Toronto, Canada</fullName>
            </value>
            <value>
                <fullName>940 - Tradeshow Foreign</fullName>
            </value>
            <value>
                <fullName>944 - E&amp;E Foreign</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi, UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Location__c.field-meta.xml
<CustomField>
    <fullName>Sales_Location__c</fullName>
    <inlineHelpText>Primary exhibition sales person&#39;s office/team</inlineHelpText>
    <label>Sales Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120- Housing</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix, Tucson, Albquerque</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles</fullName>
            </value>
            <value>
                <fullName>230- Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>290 - Audio Visual</fullName>
            </value>
            <value>
                <fullName>310 - Lead Gen</fullName>
            </value>
            <value>
                <fullName>320 - Program</fullName>
            </value>
            <value>
                <fullName>330 - GES INT, DPM</fullName>
            </value>
            <value>
                <fullName>340 - GES UK, BD</fullName>
            </value>
            <value>
                <fullName>350 - GES Europe, BD</fullName>
            </value>
            <value>
                <fullName>360 - GES Middle East, BD</fullName>
            </value>
            <value>
                <fullName>370 - Retail INT, BD</fullName>
            </value>
            <value>
                <fullName>380 - Show Team</fullName>
            </value>
            <value>
                <fullName>390 - Branded Entertainment</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460- Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470- Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Miami, Orlando, Tampa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary sales person (regardless of user type)</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N40000001qZlCEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <description>The show type field from Show object, only for Custom Build opportunities</description>
    <formula>IF( RecordTypeId = &#39;01240000000DuxL&#39;,  TEXT( Show_Name__r.Show_Type__c ) ,  TEXT( Show_Occurrence__r.Show_Name__r.Show_Type__c ) )</formula>
    <inlineHelpText>The Show type</inlineHelpText>
    <label>Show Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account Name.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shows (Account)</relationshipLabel>
    <relationshipName>Shows2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_ID__c.field-meta.xml
<CustomField>
    <fullName>Show_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Legacy System Identifier.</inlineHelpText>
    <label>Show ID (LMS)</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <inlineHelpText>CEIR Industry Groupings</inlineHelpText>
    <label>Show Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Services</fullName>
            </value>
            <value>
                <fullName>Consumer Goods and Retail Trade</fullName>
            </value>
            <value>
                <fullName>Discretionary Consumer Goods &amp; Services</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food Sector</fullName>
            </value>
            <value>
                <fullName>Financial, Legal and Real Estate</fullName>
            </value>
            <value>
                <fullName>Government, Public &amp; Non-Profit Services</fullName>
            </value>
            <value>
                <fullName>Building, Construction, Home &amp; Repair</fullName>
            </value>
            <value>
                <fullName>Industrial / Heavy Machinery / Finished Business Outputs</fullName>
            </value>
            <value>
                <fullName>Communications &amp; Information Technology</fullName>
            </value>
            <value>
                <fullName>Medical &amp; Healthcare</fullName>
            </value>
            <value>
                <fullName>Raw Materials &amp; Science</fullName>
            </value>
            <value>
                <fullName>Sporting Goods, Travel and Amusement</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Museum, Traveling Exhibition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SOPService__c/SOPService__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A custom setting for the SOP Service</description>
    <label>SOPService</label>
</CustomObject>

unpackaged/main/default/objects/SOPService__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The URL for the SOP Service</description>
    <inlineHelpText>The URL for the SOP Service</inlineHelpText>
    <label>URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/TesttrgOpportunitySubmitForApproval.cls
@isTest(SeeAllData=false)
private class TesttrgOpportunitySubmitForApproval {
  
  private static User ADMIN_USER = [SELECT Id FROM User WHERE Profile.Name = 'EMEA System Administrator' AND isActive = true and ManagerId != null LIMIT 1] ;
  
    static testMethod void myUnitTest() {
        system.runAs(ADMIN_USER){
      //Create User (for Owner)
      ID OwnerId = UserInfo.getUserId();
      
      //Create User Sales Person
      ID SalesRepId = UserInfo.getUserId();
           
      RecordType FacilityRecordType = [Select Id From RecordType Where SObjectType = 'Account' And Name = 'Facility'];
      Id FacilityRecordTypeId = FacilityRecordType.Id;
                   
      RecordType FirmRecordType = [Select Id From RecordType Where SObjectType = 'Account' And Name = 'Firm'];
      Id FirmRecordTypeId = FirmRecordType.Id;
              
      RecordType SalesRepRecordType = [Select Id From RecordType Where SObjectType = 'Opportunity' And Name = 'Sales Rep Show Occurrence'];
      Id SalesRepRecordTypeId = SalesRepRecordType.Id;      
      
      //Create Facility Account
      Account Facility = new Account();
      Facility.Sales_Person__c = SalesRepId;
      Facility.Name = 'MyTestFacilityName';
      Facility.Type = 'Hotel';
      Facility.GES_Status__c = 'Preferred';
      Facility.LMS_Facility_ID__c = 'ABCFAC';
      Facility.BillingStreet = '950 Grier Dr';
      Facility.BillingCity = 'Las Vegas';
      Facility.BillingPostalCode = '89119-0000';
      Facility.BillingState = 'NV';
      Facility.BillingCountry = 'US';
      Facility.RecordTypeId = FacilityRecordTypeId;
              
      Database.insert(Facility);
                      
      //Create Firm Account
      Account Firm = new Account();
      Firm.Sales_Person__c = SalesRepId;
      Firm.Name = 'SONY ENTERTAINMENT INC';
      Firm.Phone = '7022631500';
      Firm.BillingStreet = '950 Grier Dr';
      Firm.BillingCity = 'Las Vegas';
      Firm.BillingPostalCode = '89119-0000';
      Firm.BillingState = 'NV';
      Firm.BillingCountry = 'US';
      Firm.RecordTypeId = FirmRecordTypeId;
      
      Database.insert(Firm);
      
      //Create Show
      Show__c Show = new Show__c();
      Show.Sales_Person__c = SalesRepId;
      Show.Account__c = Firm.Id;
      Show.Name ='International CES';
      Show.Show_Type__c = 'Food Sector';
      Show.Show_ID__c = '123456';
      
      Database.insert(Show); 

      SOPAuthentication__c newAuth = new SOPAuthentication__c();
            newAuth.Name = 'Login Credentials';
            newAuth.Password__c = 'lalalala';
            newAuth.Username__c = 'lalalala';
            insert newAuth;      

            SOPService__c serv = new SOPService__c();
            serv.Name = 'Default';
            serv.URL__c = 'test';
            insert serv;      

      Test.startTest();
             
      Opportunity Opp1 = new Opportunity();
      Opp1.Job_Number__c = '201212313';        
      Opp1.OwnerId = OwnerId;   
      Opp1.Sales_Person__c = SalesRepId;        
      Opp1.Sales_Location__c = '110- Las Vegas';        
      Opp1.Name = 'MyTestShow # 1';        
      Opp1.Prime_Contractor__c = null;        
      Opp1.Production_Location__c = '110- Las Vegas';        
      Opp1.Facility__c = Facility.Id;        
      Opp1.StageName = 'SL1';        
      Opp1.Amount = 1000;        
      Opp1.Probability = 25;        
      Opp1.Type = 'ITYFTY';        
      Opp1.New_Repeat__c = 'New';        
      Opp1.Frequency__c = 'B1';        
      Opp1.AccountId = Firm.Id;       
      Opp1.Show_Name__c = Show.Id;        
      Opp1.RecordTypeId = SalesRepRecordTypeId;                
      Opp1.Show_Open_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,1);       
      Opp1.Show_Close_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,2);        
      Opp1.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
      opp1.Requested_Stage__c = '';
      insert(Opp1); 
      
      Opp1.RFP_Due_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,2);
      Opp1.Requested_Stage__c = 'PS';
      update(Opp1);
      
      test.stopTest();
        
      /*set<Id> SoOpps = new set<Id>();
      List<Opportunity> LoOppportunities = [Select Id, Name, Facility__c From Opportunity Where Id = :Opp1.Id];
      
      for (Opportunity objopp : LoOppportunities) 
      {
            SoOpps.add(opp1.Id);
      }     
      
      if (SoOpps.size() > 0)
      {
        map<Id,Id> MoProcessInstance  = new map<Id, Id>();
        set<Id> SoProcessInstance = new set<Id>();
      
      list<ProcessInstance> ProcInst = [Select Id, TargetObjectId From ProcessInstance where Status in ('Pending') limit 5 ];   
        
        if (ProcInst != null)
        {
          for(ProcessInstance pi : ProcInst)
          {
              MoProcessInstance.put(pi.TargetObjectId,pi.Id);         
          }
        }

          
          }
          
          Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
          req1.setComments('Submitting request for approval.');
          req1.setObjectId(opp1.Id);  
          
          test.stopTest();*/
          }
   }    
}