unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <externalId>true</externalId>
    <label>LMS Facility ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/LOB__c/LOB__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>LOB</label>
</CustomObject>

unpackaged/main/default/objects/LOB__c/fields/Picklist_value__c.field-meta.xml
<CustomField>
    <fullName>Picklist_value__c</fullName>
    <label>Picklist value</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LOB__c/fields/RTDevName__c.field-meta.xml
<CustomField>
    <fullName>RTDevName__c</fullName>
    <label>RTDevName</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_1__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_1__c</fullName>
    <inlineHelpText>Show Hours Day 1.</inlineHelpText>
    <label>Exhibit Hall Hours Day 1</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_2__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_2__c</fullName>
    <inlineHelpText>Show Hours Day 2.</inlineHelpText>
    <label>Exhibit Hall Hours Day 2</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_3__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_3__c</fullName>
    <inlineHelpText>Show Hours Day 3.</inlineHelpText>
    <label>Exhibit Hall Hours Day 3</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_4__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_4__c</fullName>
    <inlineHelpText>Show Hours Day 4.</inlineHelpText>
    <label>Exhibit Hall Hours Day 4</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_5__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_5__c</fullName>
    <inlineHelpText>Show Hours Day 5.</inlineHelpText>
    <label>Exhibit Hall Hours Day 5</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibitor_Move_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Exhibitor_Move_In_Date__c</fullName>
    <inlineHelpText>Date when exhibitors will start move in</inlineHelpText>
    <label>Exhibitor Move-In Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Venue in which exhibition takes place</inlineHelpText>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Facility type account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Show Occurrences (Private)</relationshipLabel>
    <relationshipName>R00N40000001pjqSEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <formula>Facility__r.LMS_Facility_ID__c</formula>
    <inlineHelpText>Facility ID (acronym)</inlineHelpText>
    <label>Facility ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Move_Out__c.field-meta.xml
<CustomField>
    <fullName>Move_Out__c</fullName>
    <inlineHelpText>Date when exhibitors start move out</inlineHelpText>
    <label>Exhibitor Move-Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Close_Date__c</fullName>
    <inlineHelpText>Date exhibition floor closes; if show close date unknown, select last day of appropriate month</inlineHelpText>
    <label>Exhibition Close Date.</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date_Time__c</fullName>
    <description>Blitz field for Opportunity Integration</description>
    <inlineHelpText>For EMEA AV Use Only.</inlineHelpText>
    <label>Show End Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Show_Occurrence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Corporate Accounts &amp; AV Projects</relationshipLabel>
    <relationshipName>Show_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date_Time__c</fullName>
    <description>Blitz field for Opportunity Integration</description>
    <label>Show Start Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/Show_ID__c.field-meta.xml
<CustomField>
    <fullName>Show_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Legacy System Identifier.</inlineHelpText>
    <label>Show ID (LMS)</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/GNT_TestUtil.cls
/**
* @author Brian Lau
* @version 1.0
* @description COMPONENT: GNT (GES New/Repeat Trigger)
*              CLASS: GNT_TestUtil
*              PURPOSE: Test utility class
*              CREATED: 08/2016 Ethos Solutions - www.ethos.com
**/
@isTest
public class GNT_TestUtil {

    public static List<Opportunity> createTestOpportunity(Integer numOfOpportunities) {
        RecordType facilityRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'Facility' and SobjectType = 'Account' limit 1];
        RecordType masterShowRT = [Select Id, SobjectType, Name From RecordType WHERE DeveloperName = 'AV_CR' and SobjectType = 'Opportunity' limit 1];
        RecordType fieldSecurityRT = [Select Id from RecordType where DeveloperName = 'FieldSecurityLR' and SobjectType = 'Opportunity'];
        Account acc = new Account(
            Name = 'Auto Show',
            Phone = '212-460-6659',
            Fax = '212-888-6523',
            BillingStreet = '1201 S Figueroa St.' ,
            BillingCity = 'Los Angeles' ,
            BillingState = 'CA',
            BillingPostalCode = '90015-1308',
            NumberOfEmployees = 500,
            AnnualRevenue = 60000000);
        Account facility = new Account(
            Name = 'Las Vegas Convention Center',
            Phone = '(702) 892-0711',
            Fax = '555-555-5555',
            BillingStreet = '43150 Paradise Rd.',
            BillingCity = 'Las Vegas',
            BillingState = 'NV' ,
            BillingPostalCode = '89109',
            NumberOfEmployees = 200,
            AnnualRevenue = 20000000,
            LMS_Facility_ID__c = '2ks9as',
            RecordTypeId = facilityRT.Id);
        List<Account> accList = new List<Account> {
            acc,
            facility
        };
        insert acclist;

        Show__c show = new Show__c(Show_Id__c = 'TESTSH');
        insert show;

        Opportunity showOpp = new Opportunity(
            Name = 'LA Auto Show',
            AccountId = acc.Id,
            Facility__c = facility.Id,
            CloseDate = System.Today(),
            Show_Close_Date__c = System.Today(),
            StageName = 'CV',
            Amount = 30000,
            Show_Start_Date_Time__c = System.Today() + 12,
            Show_End_Date_Time__c = System.Today() + 17,
            Exhibit_Hall_Hours_Day_1__c = '5:00 PM To 8:00 PM',
            Exhibit_Hall_Hours_Day_2__c = '7:00 AM To 6:30 PM',
            Exhibit_Hall_Hours_Day_3__c = '8:00 AM To 4:00 PM',
            Exhibit_Hall_Hours_Day_4__c = '9:00 AM To 10:00 PM',
            Exhibit_Hall_Hours_Day_5__c = '9:00 AM To 10:00 PM',
            Exhibitor_Move_In_Date__c = System.Today() + 11,
            RecordTypeId = fieldSecurityRT.Id,
            Prime_Contractor__c = acc.Id,
            Move_Out__c = System.Today() + 14,
            Show_Name__c = show.Id);
        insert showOpp;

        List<Opportunity> opps = new List<Opportunity>();
        for (Integer i = 0; i < numOfOpportunities; i++) {
            Opportunity opp = new Opportunity(
                Name = 'LA Auto Show',
                AccountId = acc.Id,
                Facility__c = facility.Id,
                CloseDate = System.Today() + 30,
                Show_Close_Date__c = System.Today() + 30,
                StageName = 'CV',
                Amount = 30000,
                Show_Start_Date_Time__c = System.Today() + 12,
                Show_End_Date_Time__c = System.Today() + 17,
                Exhibit_Hall_Hours_Day_1__c = '5:00 PM To 8:00 PM',
                Exhibit_Hall_Hours_Day_2__c = '7:00 AM To 6:30 PM',
                Exhibit_Hall_Hours_Day_3__c = '8:00 AM To 4:00 PM',
                Exhibit_Hall_Hours_Day_4__c = '9:00 AM To 10:00 PM',
                Exhibit_Hall_Hours_Day_5__c = '9:00 AM To 10:00 PM',
                Exhibitor_Move_In_Date__c = System.Today() + 11,
                RecordTypeId = masterShowRT.Id,
                Prime_Contractor__c = acc.Id,
                Move_Out__c = System.Today() + 14,
                Show_Occurrence__c = showOpp.Id);
            opps.add(opp);
        }
        return opps;
    }

    public static void createTestCustomSettings() {
        List<LOB__c> lobs = new List<LOB__c>();
        Map<String, String> rtMapping = new Map<String, String>();
        rtMapping.put('EMEA_AV', 'EMEA - AV');
        rtMapping.put('EMEA_Custom_Build', 'EMEA - Custom Build');
        rtMapping.put('EMEA_Exhibition', 'EMEA - Exhibition');
        rtMapping.put('EMEA_ADP', 'EMEA - ADP');
        rtMapping.put('E_D_Projects', 'North America - Corporate Accounts');
        rtMapping.put('E_D_Projects_Proposal', 'North America - Corporate Accounts');
        rtMapping.put('E_D_Projects_Read_Only', 'North America - Corporate Accounts');
        rtMapping.put('FieldSecurityCR', 'North America - Exhibition & Events');
        rtMapping.put('FieldSecurityCV', 'North America - Exhibition & Events');
        rtMapping.put('FieldSecurityDB', 'North America - Exhibition & Events');
        rtMapping.put('FieldSecurity_IA', 'North America - Exhibition & Events');
        rtMapping.put('FieldSecurityLO', 'North America - Exhibition & Events');
        rtMapping.put('FieldSecurityLPE', 'North America - Exhibition & Events');
        rtMapping.put('FieldSecurityLPM', 'North America - Exhibition & Events');
        rtMapping.put('FieldSecurityLR', 'North America - Exhibition & Events');
        rtMapping.put('FieldSecurity_NE', 'North America - Exhibition & Events');
        rtMapping.put('FieldSecurityPS', 'North America - Exhibition & Events');
        rtMapping.put('FieldSecurityTS', 'North America - Exhibition & Events');
        rtMapping.put('MasterShowOccurrence', 'North America - Exhibition & Events');
        rtMapping.put('SalesRepShowOccurrence', 'North America - Exhibition & Events');
        rtMapping.put('US_Housing', 'North America - Housing');
        rtMapping.put('US_Registration', 'North America - Registration');
        rtMapping.put('AV', 'North America - AV');
        rtMapping.put('AV_CR', 'North America - AV');
        rtMapping.put('AV_LO', 'North America - AV');
        rtMapping.put('AV_Master', 'North America - AV');
        rtMapping.put('AV_PO', 'North America - AV');
        rtMapping.put('AV_PS', 'North America - AV');
        rtMapping.put('AV_TS', 'North America - AV');
        rtMapping.put('AV_CV', 'North America - AV');
        rtMapping.put('AV_CC', 'North America - AV');
        rtMapping.put('AAV_DB', 'North America - AV');
        rtMapping.put('AV_IA', 'North America - AV');
        for (String rtDevName : rtMapping.keySet()) {
            lobs.add(new LOB__c(Name = rtDevName, RTDevName__c = rtDevName, Picklist_value__c = rtMapping.get(rtDevName)));
        }
        insert lobs;
    }
}