unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person MUST be same as Account Owner.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_1__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_1__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 1</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_2__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_2__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 2</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_3__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_3__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 3</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_4__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_4__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 4</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_5__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_5__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 5</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <description>Displays facility of show</description>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <description>Displays the opportunity Id</description>
    <label>Opportunity Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <description>Displays the opportunity name</description>
    <label>Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Production_Location__c.field-meta.xml
<CustomField>
    <fullName>Production_Location__c</fullName>
    <label>Production Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_1__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_1__c</fullName>
    <inlineHelpText>Show Hours Day 1.</inlineHelpText>
    <label>Exhibit Hall Hours Day 1</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_2__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_2__c</fullName>
    <inlineHelpText>Show Hours Day 2.</inlineHelpText>
    <label>Exhibit Hall Hours Day 2</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_3__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_3__c</fullName>
    <inlineHelpText>Show Hours Day 3.</inlineHelpText>
    <label>Exhibit Hall Hours Day 3</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_4__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_4__c</fullName>
    <inlineHelpText>Show Hours Day 4.</inlineHelpText>
    <label>Exhibit Hall Hours Day 4</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_5__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_5__c</fullName>
    <inlineHelpText>Show Hours Day 5.</inlineHelpText>
    <label>Exhibit Hall Hours Day 5</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Show Job Number.</inlineHelpText>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Production_Location__c.field-meta.xml
<CustomField>
    <fullName>Production_Location__c</fullName>
    <description>As determined by Operations / Exhibitions account management. Any additions or edits also need to be made to the Locations object.</description>
    <inlineHelpText>Operational location producing exhibition</inlineHelpText>
    <label>Production Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120-OnPeak</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix</fullName>
            </value>
            <value>
                <fullName>180 - Registration</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles, CA</fullName>
            </value>
            <value>
                <fullName>230-Intl Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>270- Corporate Events (Marketing Dept only)</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460 - Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470 - Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480- Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Florida</fullName>
            </value>
            <value>
                <fullName>530- New Orleans</fullName>
            </value>
            <value>
                <fullName>610- Portland, Seattle</fullName>
            </value>
            <value>
                <fullName>710- Chicago, Cleveland, Milwaukee, St. Louis</fullName>
            </value>
            <value>
                <fullName>810- New York &amp; Boston</fullName>
            </value>
            <value>
                <fullName>830-DC, Philadelphia</fullName>
            </value>
            <value>
                <fullName>890- Toronto, Canada</fullName>
            </value>
            <value>
                <fullName>940 - Tradeshow Foreign</fullName>
            </value>
            <value>
                <fullName>944 - E&amp;E Foreign</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi, UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Location__c.field-meta.xml
<CustomField>
    <fullName>Sales_Location__c</fullName>
    <inlineHelpText>Primary exhibition sales person&#39;s office/team</inlineHelpText>
    <label>Sales Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120- Housing</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix, Tucson, Albquerque</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles</fullName>
            </value>
            <value>
                <fullName>230- Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>290 - Audio Visual</fullName>
            </value>
            <value>
                <fullName>310 - Lead Gen</fullName>
            </value>
            <value>
                <fullName>320 - Program</fullName>
            </value>
            <value>
                <fullName>330 - GES INT, DPM</fullName>
            </value>
            <value>
                <fullName>340 - GES UK, BD</fullName>
            </value>
            <value>
                <fullName>350 - GES Europe, BD</fullName>
            </value>
            <value>
                <fullName>360 - GES Middle East, BD</fullName>
            </value>
            <value>
                <fullName>370 - Retail INT, BD</fullName>
            </value>
            <value>
                <fullName>380 - Show Team</fullName>
            </value>
            <value>
                <fullName>390 - Branded Entertainment</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460- Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470- Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Miami, Orlando, Tampa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary sales person (regardless of user type)</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N40000001qZlCEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GT_EventCreateControllerTest.cls
@isTest
public class GT_EventCreateControllerTest {
    
    public static Account testFac {get; set;}
    
    static TestMethod void testAllMethods() {
        Opportunity testOpp = getTestOpportunity();
        
        GC_Connect2_Show__c testShow = getTestConnect2Show();
        testShow.Opportunity_Id__c = testOpp.Id;
        update testShow;
        
        GT_EventCreateController.getFacilityRelated(testFac.Id);
        GT_EventCreateController.getShowRelated(testShow.Id);
    }
    
    static GC_Connect2_Show__c getTestConnect2Show() {        
        GC_Connect2_Show__c newShow = new GC_Connect2_Show__c();
        newShow.Opportunity_Name__c = '01453-201601-';
        newShow.Show_Name__c = 'test show';
        newShow.Show_Start_Date__c = Date.today();
        newShow.Show_End_Date__c = Date.today();
        newShow.Exhibit_Hall_Hours_Day_1__c = '5:00 PM To 8:00 PM';
        newShow.Exhibit_Hall_Hours_Day_2__c = '7:00 AM To 6:30 PM';
        newShow.Exhibit_Hall_Hours_Day_3__c = '8:00 AM To 4:00 PM';
        newShow.Exhibit_Hall_Hours_Day_4__c = '9:00 AM To 10:00 PM';
        newShow.Exhibit_Hall_Hours_Day_5__c = '9:00 AM To 10:00 PM';
        insert newShow;
        return newShow;
    }
    
    static Opportunity getTestOpportunity() {
        testFac = getTestFacilityAccount();
        
        Opportunity Opp1 = new Opportunity();
        Opp1.Job_Number__c = '201212313';        
        Opp1.OwnerId = UserInfo.getUserId();   
        Opp1.Sales_Person__c = UserInfo.getUserId();        
        Opp1.Sales_Location__c = '110- Las Vegas';        
        Opp1.Name = 'MyTestShow # 1';        
        Opp1.Prime_Contractor__c = null;        
        Opp1.Production_Location__c = '110- Las Vegas';        
        Opp1.Facility__c = testFac.Id;    
        Opp1.StageName = 'AV';        
        Opp1.Amount = 1000;        
        Opp1.Probability = 0;        
        Opp1.Type = 'ITYFTY';        
        Opp1.New_Repeat__c = 'New';        
        Opp1.Frequency__c = 'B1';  
        Opp1.RecordTypeId = SObjectType.Opportunity.getRecordTypeInfosByName().get(Properties.edProjectsRecordTypeName).getRecordTypeId();
        Opp1.Show_Open_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,1);       
        Opp1.Show_Close_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,2);        
        Opp1.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
        Opp1.Requested_Stage__c = '';
        insert Opp1;
        return Opp1;
    }
    
    static Account getTestFacilityAccount() {
        RecordType facilityRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'Facility' and SobjectType = 'Account' limit 1];
        Account facility = new Account(
            Name = 'Las Vegas Convention Center',
            Phone = '(702) 892-0711',
            Fax = '555-555-5555',
            BillingStreet = '43150 Paradise Rd.',
            BillingCity = 'Las Vegas',
            BillingState = 'NV' ,
            BillingPostalCode = '89109',
            NumberOfEmployees = 200,
            AnnualRevenue = 20000000,
            RecordTypeId = facilityRT.Id);
        insert facility;
        return facility;
    }
}