unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <description>Displays facility of show</description>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/GES_Move_In_Date_1__c.field-meta.xml
<CustomField>
    <fullName>GES_Move_In_Date_1__c</fullName>
    <label>GES Move-In Date 1</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <description>Amount from Opportunity</description>
    <inlineHelpText>Amount from Opportunity</inlineHelpText>
    <label>Revenue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_ID__c.field-meta.xml
<CustomField>
    <fullName>Show_ID__c</fullName>
    <label>Show ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/GC_Design_Element__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Element Task Custom Object.</description>
    <label>Design Element Task</label>
    <nameField>
        <displayFormat>DE-{0000000}</displayFormat>
        <label>Design Element Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Element Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Design Element Tasks</relationshipLabel>
    <relationshipName>Design_Element_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Design_Request_Form__c.field-meta.xml
<CustomField>
    <fullName>Design_Request_Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Design request form number associated with opportunity</description>
    <inlineHelpText>Design request form number associated with opportunity</inlineHelpText>
    <label>Design Request Form</label>
    <referenceTo>GC_Design_Request_Form__c</referenceTo>
    <relationshipLabel>Manifest</relationshipLabel>
    <relationshipName>Design_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <formula>Connect2_Show__r.Facility_lk__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Facility</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Last_Day_of_Move_Out__c.field-meta.xml
<CustomField>
    <fullName>Last_Day_of_Move_Out__c</fullName>
    <formula>Connect2_Show__r.Exhibitor_Move_Out_Date2__c</formula>
    <label>Exhibitor Move Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Move_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Move_In_Date__c</fullName>
    <formula>Connect2_Show__r.Exhibitor_Move_In_Date2__c</formula>
    <label>Exhibitor Move In Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name associated with Requestor user</description>
    <inlineHelpText>Name of Requestor</inlineHelpText>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Requester_Design_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Requester_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Requester_Phone_Number__c</fullName>
    <formula>Design_Request_Form__r.Requester_User_Phone_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requester Phone Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Show_Dates__c.field-meta.xml
<CustomField>
    <fullName>Show_Dates__c</fullName>
    <formula>TEXT(Connect2_Show__r.Show_Start_Date__c) + &#39; to &#39; + TEXT(Connect2_Show__r.Show_End_Date__c)</formula>
    <label>Show Dates</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Show_ID__c.field-meta.xml
<CustomField>
    <fullName>Show_ID__c</fullName>
    <formula>Connect2_Show__r.Show_ID__c</formula>
    <label>Show ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <formula>Connect2_Show__r.Show_Name__c</formula>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/GC_Design_Request_Form__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Request Form Custom Object.  Each Opportunity will have one and only one Active Design Request Form.  The Design Request Form object will be the central object to relate Design Element designated to a show.  The DRF contains details about budgets / graphics / show information.</description>
    <label>Design Request Form</label>
    <nameField>
        <displayFormat>DRF-{0000}</displayFormat>
        <label>Design Request Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Request Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Design Request Forms</relationshipLabel>
    <relationshipName>Design_Request_Forms</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Date_Requested__c.field-meta.xml
<CustomField>
    <fullName>Date_Requested__c</fullName>
    <defaultValue>today()</defaultValue>
    <description>Date Requested for show</description>
    <inlineHelpText>Date Requested for show</inlineHelpText>
    <label>Date Requested</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Design_Team__c.field-meta.xml
<CustomField>
    <fullName>Design_Team__c</fullName>
    <description>Name of Design Team.</description>
    <inlineHelpText>Name of Design Team.</inlineHelpText>
    <label>Design Team</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/DRF_Requester_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>DRF_Requester_Phone_Number__c</fullName>
    <label>Requester Phone Number</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/DRF_Revenue__c.field-meta.xml
<CustomField>
    <fullName>DRF_Revenue__c</fullName>
    <label>Revenue</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <description>(No Longer Used)</description>
    <inlineHelpText>Name of Facility.</inlineHelpText>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Hall__c.field-meta.xml
<CustomField>
    <fullName>Hall__c</fullName>
    <description>(No Longer Used)</description>
    <inlineHelpText>Name of the Hall</inlineHelpText>
    <label>Hall</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>GC_Show_Team_Member__c</referenceTo>
    <relationshipLabel>Design Request Forms</relationshipLabel>
    <relationshipName>Design_Request_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Requesters__c.field-meta.xml
<CustomField>
    <fullName>Requesters__c</fullName>
    <description>The person(s) who asks for something or who makes a request</description>
    <label>Requester(s)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/recordTypes/RFP.recordType-meta.xml
<RecordType>
    <fullName>RFP</fullName>
    <active>true</active>
    <description>Request for Proposal for an Exhibition or Event.</description>
    <label>RFP (Exhibition or Event)</label>
</RecordType>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <formula>Connect2_Show__r.Show_Name__c</formula>
    <label>Show Name Formula</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Role__c.field-meta.xml
<CustomField>
    <fullName>Show_Role__c</fullName>
    <description>Determines the level of access to associated elements on a show.</description>
    <inlineHelpText>Determines the level of access to associated elements on a show.</inlineHelpText>
    <label>Show Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Convention_Planning</fullName>
                <label>Convention Planning</label>
            </value>
            <value>
                <fullName>Creative Director</fullName>
            </value>
            <value>
                <fullName>Designer/Detailer</fullName>
            </value>
            <value>
                <fullName>Director of Account Management</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager Direct</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Secondary Account Manager</fullName>
            </value>
            <value>
                <fullName>Show Organizer</fullName>
            </value>
            <value>
                <fullName>Show Organizer - Read Only</fullName>
            </value>
            <value>
                <fullName>Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GC_DesignRequestFormTriggerHandler.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Trigger logic for Design Request Form
* 2016-04-13 : Original Version
**/
public without sharing class GC_DesignRequestFormTriggerHandler {

    public static void HandleBeforeUpdate(List<GC_Design_Request_Form__c> designRequestForms) {
        // GC-625 Removing obsolete trigger code.
        //Set<Id> drfShowIds = new Set<Id>();
        //for (GC_Design_Request_Form__c drf : designRequestForms) {
        //    drfShowIds.add(drf.Connect2_Show__c);
        //}
        //List<GC_Connect2_Show__c> showList = [SELECT Id, Show_Name__c, Show_ID__c, City_Code__c, Job_Number__c
        //                                      , Show_Month_Year__c, Facility__c, Revenue__c, Show_Dates__c
        //                                      , Last_Day_Of_Move_Out__c, Halls__c
        //                                      , Requester__c, Date_Requested__c, Requester_Phone_Number__c
        //                                      , Creative_Director__c, Design_Team__c, GES_Move_In_Date_1__c FROM GC_Connect2_Show__c WHERE Id IN :drfShowIds];
        //Map<Id, GC_Connect2_Show__c> showMap = new Map<Id, GC_Connect2_Show__c>(showList);
        //for (GC_Design_Request_Form__c drfLoop : designRequestForms) {
        //    if (showMap.containsKey(drfLoop.Connect2_Show__c)) {
        //        GC_Connect2_Show__c show = showMap.get(drfLoop.Connect2_Show__c);

        //        if (drfLoop.RecordType_Name__c != 'RFP (Exhibition or Event)') {
        //            drfLoop.DRF_Show_Name__c = show.Show_Name__c;
        //            drfLoop.DRF_Show_ID__c = show.Show_ID__c;
        //            drfLoop.DRF_Job_Number__c = show.Job_Number__c;
        //            drfLoop.DRF_Show_Month_And_Year__c = show.Show_Month_Year__c;
        //            drfLoop.Facility__c = show.Facility__c;

        //            try {
        //                drfLoop.DRF_Revenue__c = show.Revenue__c;
        //                drfLoop.City_Code__c = show.City_Code__c;
        //                //drfLoop.Last_Year_s_Job_Number__c = show.Last_Year_s_Job_Number__c;
        //                drfLoop.Last_Day_of_Move_Out__c = show.Last_Day_Of_Move_Out__c;
        //                drfLoop.Move_In_Date__c = show.GES_Move_In_Date_1__c;
        //            }
        //            catch (Exception e) {
        //                System.debug(e.getMessage());
        //            }

        //            drfLoop.DRF_Show_Dates__c = show.Show_Dates__c;
        //            drfLoop.Hall__c = show.Halls__c;
        //            drfLoop.Requesters__c = show.Requester__c;
        //            drfLoop.DRF_Requester_Phone_Number__c = show.Requester_Phone_Number__c;
        //            drfLoop.Creative_Director__c = show.Creative_Director__c;
        //            drfLoop.Design_Team__c = show.Design_Team__c;
        //        }
        //        else {
        //            // For RFP record type, only populate show dates if user didn't enter it in.
        //            if (String.isBlank(drfLoop.DRF_Show_Dates__c)) drfLoop.DRF_Show_Dates__c = show.Show_Dates__c;
        //            if (String.isBlank(drfLoop.DRF_Job_Number__c)) drfLoop.DRF_Job_Number__c = show.Job_Number__c;
        //            if (String.isBlank(drfLoop.DRF_Show_Name__c)) drfLoop.DRF_Show_Name__c = show.Show_Name__c;
        //            if (String.isBlank(drfLoop.DRF_Show_ID__c)) drfLoop.DRF_Show_ID__c = show.Show_ID__c;

        //        }
        //    }
        //}
    }

    public static void HandleShowTeamRecordAccess(List<GC_Design_Request_Form__c> designRequestForms) {
        Set<String> showIds = new Set<String>();
        for (GC_Design_Request_Form__c drf : designRequestForms) {
            showIds.add((String)drf.Connect2_Show__c);
        }
        List<GC_Show_Team_Member__c> showTeamMembers = [select Id, Name, User__c, Show_Role__c, Connect2_Show__c from GC_Show_Team_Member__c where Connect2_Show__c in :showIds];
        GC_ShowTeamMemberTriggerHandler.UpdateShowRecordAccess(showTeamMembers);
    }

    public static void CheckMoreThanOneDRF(List<GC_Design_Request_Form__c> designRequestForms) {
        for (GC_Design_Request_Form__c drf : designRequestForms) {
            List<GC_Design_Request_Form__c> existingDRF = [Select Id From GC_Design_Request_Form__c Where Connect2_Show__c = :drf.Connect2_Show__c];
            if (existingDRF.size() > 0) {
                drf.Connect2_Show__c.addError('This show already has a DRF attached to it');
            }
        }
    }

    public static void HandleCancelActionTrigger(List<GC_Design_Request_Form__c> designRequestForms) {
        Set<Id> drfShowIds = new Set<Id>();
        Set<Id> drfIds = new Set<Id>();

        for (GC_Design_Request_Form__c drf : designRequestForms) {
            drfShowIds.add(drf.Connect2_Show__c);
            drfIds.add(drf.Id);
        }
        List<GC_Connect2_Show__c> showList = [SELECT Id, Name FROM GC_Connect2_Show__c WHERE Id IN :drfShowIds];
        List<GC_Design_Element__c> elementList = [SELECT Id, Name, Status__c, Design_Request_Form__c FROM GC_Design_Element__c WHERE Design_Request_Form__c IN :drfIds];

        Map<Id, List<GC_Design_Element__c>> deDrfMap = new Map<Id, List<GC_Design_Element__c>>();

        for (GC_Design_Element__c de : elementList) {
            if (!deDrfMap.containsKey(de.Design_Request_Form__c)) {
                deDrfMap.put(de.Design_Request_Form__c, new List<GC_Design_Element__c>());
            }
            deDrfMap.get(de.Design_Request_Form__c).add(de);
        }
        Map<Id, GC_Design_Element__c> elementMap = new Map<Id, GC_Design_Element__c>(elementList);

        for (GC_Design_Request_Form__c drfLoop : designRequestForms) {
            if (drfLoop.Status__c == 'Canceled' && Userinfo.getUserId() != drfLoop.Requester_User__c) {
                drfLoop.addError(' Only assigned requester user can cancel a design request form');
            }
            else if (drfLoop.Status__c == 'Canceled') {
                Boolean hasApprovedOrClosedStatus = false;

                for (GC_Design_Element__c de : deDrfMap.get(drfLoop.Id)) {
                    if (de.Status__c == 'Approved' || de.Status__c == 'Closed') {
                        hasApprovedOrClosedStatus = true;
                        break;
                    }
                }
                if (hasApprovedOrClosedStatus) {
                    drfLoop.addError(' Cannot cancel a DRF when 1 or more design element tasks have the status of approved or closed');
                }
            }
        }
    }

    public static void DetermineRequester(Map<Id, GC_Design_Request_Form__c> oldMap, Map<Id, GC_Design_Request_Form__c> newMap) {
        List<GC_Design_Request_Form__c> drfs = new List<GC_Design_Request_Form__c>();
        for (Id drfId : newMap.keySet()) {
            if (oldMap.get(drfId).Requester_User__c != newMap.get(drfId).Requester_User__c) {
                drfs.add(newMap.get( drfId ));
            }
            else if (oldMap.get(drfId).Requester_Secondary_User__c != newMap.get(drfId).Requester_Secondary_User__c) {
                drfs.add(newMap.get( drfId ));
            }
        }
        if (drfs.size() > 0) {
            GC_DesignRequestFormTriggerHandler.HandleValidRequester(drfs);
        }
    }

    public static void HandleValidRequester(List<GC_Design_Request_Form__c> designRequestForms) {
        Set<Id> drfIdList = new Set<Id>();
        Set<Id> drfShowIds = new Set<Id>();
        Set<Id> drfUserIds = new Set<Id>();

        for (GC_Design_Request_Form__c drf : designRequestForms ) {
            drfIdList.add(drf.Id);
            drfShowIds.add(drf.Connect2_Show__c);
            drfUserIds.add(drf.Requester_User__c);
            drfUserIds.add(drf.Requester_Secondary_User__c);
        }


        Map<String, User> requestorUsers = new Map<String, User>([select Id, Name, GC_Show_Role__c, Profile.Name from User where Id in :drfUserIds]);

        List<GC_Connect2_Show__c> showList = [SELECT Id, Name FROM GC_Connect2_Show__c WHERE Id IN :drfShowIds];
        List<GC_Show_Team_Member__c> showTeamMembers = [select Id, Name, User__c, Show_Role__c, Connect2_Show__c from GC_Show_Team_Member__c where Connect2_Show__c in :drfShowIds AND User__c IN :drfUserIds];


        Map<Id, GC_Show_Team_Member__c> teamMemberMap = new Map<Id, GC_Show_Team_Member__c>();
        for ( GC_Show_Team_Member__c stm : showTeamMembers) {
            teamMemberMap.put(stm.User__c, stm);
        }

        Map<String, GC_Show_Team_Member__c> stms = new Map<String, GC_Show_Team_Member__c>();

        for ( GC_Design_Request_Form__c drfLoop : designRequestForms) {
            if (teamMemberMap.containsKey(drfLoop.Requester_User__c)) {
                stms.put(drfLoop.Requester_User__c + ',' + drfLoop.Connect2_Show__c, teamMemberMap.get(drfLoop.Requester_User__c));
            }
            else if (drfLoop.Requester_User__c != null) {
                GC_Show_Team_Member__c newMember = new GC_Show_Team_Member__c();
                newMember.User__c = drfLoop.Requester_User__c;
                newMember.Connect2_Show__c = drfLoop.Connect2_Show__c;

                if (GC_SecurityUtil.userHasRole(requestorUsers.get(drfLoop.Requester_User__c), GC_SecurityUtil.R_CREATIVE_DIRECTOR)) {
                    newMember.Show_Role__c = 'Creative Director';
                }
                else if (GC_SecurityUtil.userHasRole(requestorUsers.get(drfLoop.Requester_User__c), GC_SecurityUtil.R_TRAFFIC_ADMIN )) {
                    newMember.Show_Role__c = 'Traffic Administrator';
                }
                else if (GC_SecurityUtil.userHasRole(requestorUsers.get(drfLoop.Requester_User__c), GC_SecurityUtil.R_ACCT_MANAGER)) {
                    newMember.Show_Role__c = 'Account Manager';
                }
                else if (GC_SecurityUtil.userHasRole(requestorUsers.get(drfLoop.Requester_User__c), GC_SecurityUtil.R_SALES_MGR)) {
                    newMember.Show_Role__c = 'Account Manager';
                }
                else if (GC_SecurityUtil.userHasRole(requestorUsers.get(drfLoop.Requester_User__c), GC_SecurityUtil.R_DIRECTOR_ACCT_MGMT)) {
                    newMember.Show_Role__c = 'Director of Account Management';
                }
                else {
                    // FIXME GC-14, need a mechanism to determine what show role to give,
                    // right now we'll default all others to sales manager just so we can get it inserted.
                    // If they have the permissions set, this should insert just fine, otherwise the validation rule on show team member will kick back and show team member won't get inserted.
                    newMember.Show_Role__c = 'Sales Manager';
                }

                stms.put(drfLoop.Requester_User__c + ',' + drfLoop.Connect2_Show__c, newMember);
            }

            if (teamMemberMap.containsKey(drfLoop.Requester_Secondary_User__c)) {
                stms.put(drfLoop.Requester_Secondary_User__c + ',' + drfLoop.Connect2_Show__c, teamMemberMap.get(drfLoop.Requester_Secondary_User__c));
            }
            else if (drfLoop.Requester_Secondary_User__c != null) {
                GC_Show_Team_Member__c newMember = new GC_Show_Team_Member__c();
                newMember.User__c = drfLoop.Requester_Secondary_User__c;
                newMember.Connect2_Show__c = drfLoop.Connect2_Show__c;

                if (GC_SecurityUtil.userHasRole(requestorUsers.get(drfLoop.Requester_Secondary_User__c), GC_SecurityUtil.R_CREATIVE_DIRECTOR)) {
                    newMember.Show_Role__c = 'Creative Director';
                }
                else if (GC_SecurityUtil.userHasRole(requestorUsers.get(drfLoop.Requester_Secondary_User__c), GC_SecurityUtil.R_TRAFFIC_ADMIN)) {
                    newMember.Show_Role__c = 'Traffic Administrator';
                }
                else if (GC_SecurityUtil.userHasRole(requestorUsers.get(drfLoop.Requester_Secondary_User__c), GC_SecurityUtil.R_ACCT_MANAGER)) {
                    newMember.Show_Role__c = 'Account Manager';
                }
                else if (GC_SecurityUtil.userHasRole(requestorUsers.get(drfLoop.Requester_Secondary_User__c), GC_SecurityUtil.R_SALES_MGR)) {
                    newMember.Show_Role__c = 'Account Manager';
                }
                else if (GC_SecurityUtil.userHasRole(requestorUsers.get(drfLoop.Requester_Secondary_User__c), GC_SecurityUtil.R_DIRECTOR_ACCT_MGMT)) {
                    newMember.Show_Role__c = 'Director of Account Management';
                }
                else {
                    newMember.Show_Role__c = 'Sales Manager';
                }

                stms.put(drfLoop.Requester_Secondary_User__c + ',' + drfLoop.Connect2_Show__c, newMember);
            }

        }
        Database.upsert(stms.values(), false);

        for (GC_Design_Request_Form__c drfLoop : designRequestForms) {
            String key = drfLoop.Requester_User__c + ',' + drfLoop.Connect2_Show__c;
            String secondaryKey = drfLoop.Requester_Secondary_User__c + ',' + drfLoop.Connect2_Show__c;
            if (stms.containsKey(key)) {
                drfLoop.Requester_STM__c = stms.get(key).Id;
            }
            if (stms.containsKey(secondaryKey)) {
                drfLoop.Requester_Secondary_STM__c = stms.get(secondaryKey).Id;
            }
        }
        //update drfList;
    }

    public static void CheckChangeOwner(Map<Id, GC_Design_Request_Form__c> oldMap, Map<Id, GC_Design_Request_Form__c> newMap) {
        List<GC_Design_Request_Form__c> drfs = new List<GC_Design_Request_Form__c>();
        for (Id drfId : newMap.keySet()) {
            if (oldMap.get(drfId).OwnerId != newMap.get(drfId).OwnerId) {
                drfs.add(newMap.get( drfId ));
            }
            if (drfs.size() > 0) {
                HandleShowTeamRecordAccess(drfs);
            }
        }
    }

    public static void PopulateLastYearsJobNumber(List<GC_Design_Request_Form__c> designRequestForms) {
        Set<Id> showIds = new Set<Id>();
        for (GC_Design_Request_Form__c drf : designRequestForms) {
            showIds.add(drf.Connect2_Show__c);
        }
        List<GC_Connect2_Show__c> shows = [select Id, Name, Job_Number__c, YRMO__c, Show_ID__c, Last_Worked_YRMO_JN__c from GC_Connect2_Show__c where Id in :showIds];
        Set<String> lmsShowIds = new Set<String>();
        for (GC_Connect2_Show__c show : shows) {
            // check to see if it's already set, and if so move on, it should only be correct
            if (String.isNotBlank(show.Last_Worked_YRMO_JN__c)) {
                continue;
            }
            lmsShowIds.add(show.Show_ID__c);
        }
        List<GC_Connect2_Show__c> showsToUpdate = new List<GC_Connect2_Show__c>();

        List<GC_Connect2_Show__c> linkedShows = [select Id, Name, Job_Number__c, YRMO__c, Show_ID__c from GC_Connect2_Show__c where Show_ID__c in :lmsShowIds order by Show_ID__c desc, YRMO__c desc];
        // TODO can probably make this for loop a little more efficient by building up a map, but for the most part we're only going to be inserting / updating one design request form, so it's not that big of a deal.

        // go through each show with the same show id, and find the job numbers associated.
        for (GC_Connect2_Show__c show : shows) {
            Boolean lastShowFlag = false;
            for (GC_Connect2_Show__c linkedShow : linkedShows) {
                if (lastShowFlag) {
                    show.Last_Worked_YRMO_JN__c = linkedShow.YRMO__c + '-' + linkedShow.Job_Number__c;
                    showsToUpdate.add(show);
                    lastShowFlag = false;
                    break;
                }
                if (show.Show_ID__c == linkedShow.Show_ID__c && show.YRMO__c == linkedShow.YRMO__c) {
                    lastShowFlag = true;
                    continue;
                }
            }
        }
        update showsToUpdate;
    }
}