unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person MUST be same as Account Owner.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Venue in which exhibition takes place</inlineHelpText>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Facility type account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Show Occurrences (Private)</relationshipLabel>
    <relationshipName>R00N40000001pjqSEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Production_Location__c.field-meta.xml
<CustomField>
    <fullName>Production_Location__c</fullName>
    <description>As determined by Operations / Exhibitions account management. Any additions or edits also need to be made to the Locations object.</description>
    <inlineHelpText>Operational location producing exhibition</inlineHelpText>
    <label>Production Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120-OnPeak</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix</fullName>
            </value>
            <value>
                <fullName>180 - Registration</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles, CA</fullName>
            </value>
            <value>
                <fullName>230-Intl Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>270- Corporate Events (Marketing Dept only)</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460 - Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470 - Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480- Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Florida</fullName>
            </value>
            <value>
                <fullName>530- New Orleans</fullName>
            </value>
            <value>
                <fullName>610- Portland, Seattle</fullName>
            </value>
            <value>
                <fullName>710- Chicago, Cleveland, Milwaukee, St. Louis</fullName>
            </value>
            <value>
                <fullName>810- New York &amp; Boston</fullName>
            </value>
            <value>
                <fullName>830-DC, Philadelphia</fullName>
            </value>
            <value>
                <fullName>890- Toronto, Canada</fullName>
            </value>
            <value>
                <fullName>940 - Tradeshow Foreign</fullName>
            </value>
            <value>
                <fullName>944 - E&amp;E Foreign</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi, UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/RecordType_Name__c.field-meta.xml
<CustomField>
    <fullName>RecordType_Name__c</fullName>
    <formula>$RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RecordType Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary sales person (regardless of user type)</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N40000001qZlCEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Close_Date__c</fullName>
    <inlineHelpText>Date exhibition floor closes; if show close date unknown, select last day of appropriate month</inlineHelpText>
    <label>Exhibition Close Date.</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Open_Date__c</fullName>
    <inlineHelpText>Date exhibition floor opens; if show open date unknown, select first day of appropriate month</inlineHelpText>
    <label>Exhibition Open Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/USShowCalendar.cls
public with sharing class USShowCalendar {

  public List<OpportunityWrapper> show {get;set;}
  public string searchQuery{get;set;}
  public list<string> monthValue{get;set;} 
  public list<string> productionLocation {get;set;}
  public list<string> yearValue{get;set;}
  public string stageFilter{get;set;}
  public transient string venueFilter{get;set;}
  public transient string probabilityFilter{get;set;}

  

  public USShowCalendar(ApexPages.StandardSetController controller){
   // monthValue = 'THIS_MONTH';
   // productionLocation = 'All';
    stageFilter = 'All';
    venueFilter = 'All';
    probabilityFilter = 'All';
  }

  //public void search(){ Amarab 1/6/2016
  public void searchquery(){
   system.debug('monthValue=====================' +monthValue);
   system.debug('yearValue=====================' +yearValue);

    system.debug('productionLocation =====================' +productionLocation);
    searchQuery= 'SELECT RecordType_Name__c, Production_Location__c,StageName,Show_Name__r.name,Sales_Person__r.name, probability, amount, Show_Name__c, Name, Facility__r.name, Show_Open_Date__c, Show_Close_Date__c, Sales_Person__c FROM Opportunity';
   // searchQuery += ' WHERE Show_Open_Date__c = ' + monthValue;
    searchQuery += ' WHERE  (RecordType_Name__c LIKE \'Field%\' OR RecordType_Name__c LIKE \'Sales Rep Show Occurrence%\' OR RecordType_Name__c = \'Master Show Occurrence\')';
    system.debug('productionLocation =====================' +productionLocation.size());
    
    // check if a filter on production location has been applied
    String checkprlocation ;
    string searchQuery1 =' ' ;
    string searchQuerymonth =' ' ;
    string searchQueryyear =' ' ;


    for (string  s : productionLocation)
    { 
     if(s == 'All'){  
      checkprlocation = 'true';   
      }      
     else{
     searchQuery1 +=' production_Location__c =' + '\'' +  s + '\' ' + 'or'  ;
    }
 }   
 
   if(productionLocation.size() > 0) {
    if (checkprlocation != 'true' )
       {
        searchQuery1 = searchQuery1.substring(0, searchQuery1.length() - 2);
        searchQuery +=' AND (' + searchQuery1 +')'; 
        }
   }    
        system.debug('SearchQuery for pr location===='+ searchQuery);
        
      for (string  s : monthValue)
    { 
     
     searchQuerymonth  +=' CALENDAR_MONTH(Show_Open_Date__c) =' +  +  s +  + 'or'  ;
     
          //searchQuerymonth  +=' CALENDAR_MONTH(Show_Open_Date__c) =' + '\'' +  s + '\' ' + 'or'  ;

    
 }   
 
   if(monthValue.size() > 0) {
   
        searchQuerymonth  = searchQuerymonth.substring(0, searchQuerymonth.length() - 2);
        searchQuery +=' AND (' + searchQuerymonth +')'; 
        
   }    
        system.debug('SearchQuery for month===='+ searchQuery);
  
        for (string  s : yearValue)
    { 
     
     searchQueryyear +=' CALENDAR_YEAR(Show_Open_Date__c) =' +  +  s +  + 'or'  ;
    
 }   
  system.debug('SearchQuery for month===='+ searchQuery);
  if(yearValue.size() > 0) {
   
        searchQueryyear = searchQueryyear.substring(0, searchQueryyear.length() - 2);
        searchQuery +=' AND (' + searchQueryyear +')'; 
        
   }    
        system.debug('SearchQuery for month===='+ searchQuery);
    
        

    // check if a filter has been set on stage
    
    
     if (stageFilter =='CR/CV')
        searchQuery += ' AND (stagename = \'CR\' or stagename = \'CV\')';

    if (stageFilter =='PO/PS')
        searchQuery += ' AND (stagename = \'PO\' or stagename = \'PS\')';
    if (stageFilter =='SL1/SL3')
        searchQuery += ' AND (stagename = \'SL1\' or stagename = \'SL3\')';
    if (stageFilter =='Open (PO/PS/SL1/SL3)')
        searchQuery += ' AND (stagename = \'PO\' or stagename = \'PS\' or stagename = \'SL1\' or stagename = \'SL3\')';
    if (stageFilter =='TS')
        searchQuery += ' AND (stagename = \'TS\' or stagename = \'TS\')';
    if (stageFilter =='LO/LR/LPE/LPM')
        searchQuery += ' AND (stagename = \'LO\' or stagename = \'LR\' or stagename = \'LPE\' or stagename = \'LPM\')';
    if (stageFilter =='CC/DB/IA/SC/NE/SM')
        searchQuery += ' AND (stagename = \'CC\' or stagename = \'DB\' or stagename = \'IA\' or stagename = \'SC\' or stagename = \'NE\'or stagename = \'SM\')';
        
        
        
    // check if a filter has been set on venue
    if (venueFilter != 'All')
        searchQuery += ' AND (facility__r.name = \'' + venueFilter + '\')';
        
    // check if a filter has been set on probability
    if (probabilityFilter != 'All')
        searchQuery += ' AND (probability = ' + probabilityFilter + ')';
   
    searchQuery += ' ORDER BY Show_Close_Date__c Limit 1500';
    string.escapeSingleQuotes(searchQuery);
    System.debug(searchQuery);
   }
   
  public void search(){
    searchquery();
    List<Opportunity> showTemp = Database.query(searchQuery);
    show = new List<OpportunityWrapper>();
    for (Opportunity o : showTemp) {
      show.add(new OpportunityWrapper(o));
     }
  }

  public void clear() {
    show.clear();
  }

  
  public pageReference exportxlsmeth(){ 
     searchquery();
     String temp = EncodingUtil.urlEncode(searchQuery, 'UTF-8');
     System.debug('temp --------------------------' + temp );
       return new PageReference('/apex/US_Show_Calendar_Excel?searchQueryforExcel=' + temp );     
     }  
  
  public class OpportunityWrapper {
    
    public Opportunity opp { get; set; }
    
    public string products {
      get {
        string prods = '';
        for (OpportunityLineItem oli : opp.OpportunityLineItems) {
          if (prods != '')
            prods += ', ';
          prods += oli.Product2.Name;
        }
        return prods;
      }
    }
    
    public OpportunityWrapper(Opportunity o) {
      opp = o;
    }
    
  }
}