unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person MUST be same as Account Owner.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Firm.recordType-meta.xml
<RecordType>
    <fullName>Firm</fullName>
    <active>true</active>
    <description>A Management Company, Sponsor, Contractor (Prime and Sub), and Competitor related to Shows and Show Occurrences.</description>
    <label>Firm</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/International.recordType-meta.xml
<RecordType>
    <fullName>International</fullName>
    <active>true</active>
    <label>International</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Venue in which exhibition takes place</inlineHelpText>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Facility type account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Show Occurrences (Private)</relationshipLabel>
    <relationshipName>R00N40000001pjqSEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Frequency of Show Occurrence</description>
    <inlineHelpText>B1-B5: Base business (exhibition occurs same city/venue every occurrence), either annually (1), every other year (2), etc.; R1-R5: Rotating business (exhibition occurs different city/venue each occurrence), either annually (1), every other year (2), etc.</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
            <value>
                <fullName>B4</fullName>
            </value>
            <value>
                <fullName>B5</fullName>
            </value>
            <value>
                <fullName>R1</fullName>
            </value>
            <value>
                <fullName>R2</fullName>
            </value>
            <value>
                <fullName>R3</fullName>
            </value>
            <value>
                <fullName>R4</fullName>
            </value>
            <value>
                <fullName>R5</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Show Job Number.</inlineHelpText>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/New_Repeat__c.field-meta.xml
<CustomField>
    <fullName>New_Repeat__c</fullName>
    <inlineHelpText>If GES produced prior occurrence, business is &quot;Repeat&quot;, if GES did not produce prior occurrence, business is &quot;New&quot;</inlineHelpText>
    <label>New/Repeat</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Repeat</fullName>
            </value>
            <value>
                <fullName>ADP</fullName>
            </value>
            <value>
                <fullName>Up Sell</fullName>
            </value>
            <value>
                <fullName>Cross Sell</fullName>
            </value>
            <value>
                <fullName>Electric Only</fullName>
            </value>
            <value>
                <fullName>New Logo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Production_Location__c.field-meta.xml
<CustomField>
    <fullName>Production_Location__c</fullName>
    <description>As determined by Operations / Exhibitions account management. Any additions or edits also need to be made to the Locations object.</description>
    <inlineHelpText>Operational location producing exhibition</inlineHelpText>
    <label>Production Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120-OnPeak</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix</fullName>
            </value>
            <value>
                <fullName>180 - Registration</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles, CA</fullName>
            </value>
            <value>
                <fullName>230-Intl Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>270- Corporate Events (Marketing Dept only)</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460 - Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470 - Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480- Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Florida</fullName>
            </value>
            <value>
                <fullName>530- New Orleans</fullName>
            </value>
            <value>
                <fullName>610- Portland, Seattle</fullName>
            </value>
            <value>
                <fullName>710- Chicago, Cleveland, Milwaukee, St. Louis</fullName>
            </value>
            <value>
                <fullName>810- New York &amp; Boston</fullName>
            </value>
            <value>
                <fullName>830-DC, Philadelphia</fullName>
            </value>
            <value>
                <fullName>890- Toronto, Canada</fullName>
            </value>
            <value>
                <fullName>940 - Tradeshow Foreign</fullName>
            </value>
            <value>
                <fullName>944 - E&amp;E Foreign</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi, UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Location__c.field-meta.xml
<CustomField>
    <fullName>Sales_Location__c</fullName>
    <inlineHelpText>Primary exhibition sales person&#39;s office/team</inlineHelpText>
    <label>Sales Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120- Housing</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix, Tucson, Albquerque</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles</fullName>
            </value>
            <value>
                <fullName>230- Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>290 - Audio Visual</fullName>
            </value>
            <value>
                <fullName>310 - Lead Gen</fullName>
            </value>
            <value>
                <fullName>320 - Program</fullName>
            </value>
            <value>
                <fullName>330 - GES INT, DPM</fullName>
            </value>
            <value>
                <fullName>340 - GES UK, BD</fullName>
            </value>
            <value>
                <fullName>350 - GES Europe, BD</fullName>
            </value>
            <value>
                <fullName>360 - GES Middle East, BD</fullName>
            </value>
            <value>
                <fullName>370 - Retail INT, BD</fullName>
            </value>
            <value>
                <fullName>380 - Show Team</fullName>
            </value>
            <value>
                <fullName>390 - Branded Entertainment</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460- Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470- Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Miami, Orlando, Tampa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary sales person (regardless of user type)</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N40000001qZlCEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Close_Date__c</fullName>
    <inlineHelpText>Date exhibition floor closes; if show close date unknown, select last day of appropriate month</inlineHelpText>
    <label>Exhibition Close Date.</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Open_Date__c</fullName>
    <inlineHelpText>Date exhibition floor opens; if show open date unknown, select first day of appropriate month</inlineHelpText>
    <label>Exhibition Open Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestLOBDetailsCalculations.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestLOBDetailsCalculations 
{      
    static testMethod void myUnitTest() 
    {
        User u = getUser();
        system.runAs(u)
        {
            //Create User (for Owner)            
            ID OwnerId = UserInfo.getUserId();
        
            //Create User Sales Person
            ID SalesRepId = UserInfo.getUserId();
            
            //Create facility Account
            Account facility = getFacilityAccount(SalesRepId);
            insert facility;
            
            //Create Firm Account
            Account firm = getFirmAccount(SalesRepId);
            insert firm;
            
            //Create Show
            Show__c Show = getShow(SalesRepId, firm.Id);
            insert show;
            
            Opportunity Opp1 = new Opportunity();
            Opp1.Job_Number__c = '201212313';        
            Opp1.OwnerId = OwnerId;   
            Opp1.Sales_Person__c = SalesRepId;        
            Opp1.Sales_Location__c = '110- Las Vegas';        
            Opp1.Name = 'MyTestShow # 1';        
            Opp1.Prime_Contractor__c = null;        
            Opp1.Production_Location__c = '110- Las Vegas';        
            Opp1.Facility__c = Facility.Id;        
            Opp1.StageName = 'CR';        
            Opp1.Amount = 1000;        
            Opp1.Probability = 0;        
            Opp1.Type = 'ITYFTY';        
            Opp1.New_Repeat__c = 'New';        
            Opp1.Frequency__c = 'B1';        
            Opp1.AccountId = Firm.Id;       
            Opp1.Show_Name__c = Show.Id;        
            Opp1.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('EMEA - Exhibition').getRecordTypeId();              
            Opp1.Show_Open_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,1);       
            Opp1.Show_Close_Date__c = Date.today().addDays(1);
            Opp1.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
            opp1.Requested_Stage__c = '';
            opp1.Show_Occurrence__c =  opp1.id;
            opp1.Show_Name__c = Show.id;                        
            
            Opportunity Opp2 = new Opportunity();
            Opp2.Job_Number__c = '201212313';        
            Opp2.OwnerId = OwnerId;   
            Opp2.Sales_Person__c = SalesRepId;        
            Opp2.Sales_Location__c = '110- Las Vegas';        
            Opp2.Name = 'MyTestShow # 1';        
            Opp2.Prime_Contractor__c = null;        
            Opp2.Production_Location__c = '110- Las Vegas';        
            Opp2.Facility__c = Facility.Id;        
            Opp2.StageName = 'CR';        
            Opp2.Amount = 1000;        
            Opp2.Probability = 0;        
            Opp2.Type = 'ITYFTY';        
            Opp2.New_Repeat__c = 'New';        
            Opp2.Frequency__c = 'B1';        
            Opp2.AccountId = Firm.Id;       
            Opp2.Show_Name__c = Show.Id;        
            Opp2.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Master Show Occurrence').getRecordTypeId();              
            Opp2.Show_Open_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,1);       
            Opp2.Show_Close_Date__c = Date.today().addDays(2);
            Opp2.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
            opp2.Requested_Stage__c = '';
            opp2.Show_Occurrence__c =  opp1.id;
            opp2.Show_Name__c = Show.id;   
            opp2.Prime_Contractor__c = Firm.Id;         
            insert new list<Opportunity>{opp1, opp2};  
            
            LOBDetailsCalculations.LOBDetailsCalculations(new Set<Id>{show.Id});
            LOBDetailsCalculations.NewLOBDetailsCalculations(new Set<Id>{show.Id});
        }
    }
    static testMethod void myUnitTest2() 
    {
        User u = getUser();
        system.runAs(u)
        {
            //Create User (for Owner)            
            ID OwnerId = UserInfo.getUserId();
        
            //Create User Sales Person
            ID SalesRepId = UserInfo.getUserId();
            
            //Create facility Account
            Account facility = getFacilityAccount(SalesRepId);
            insert facility;
            
            //Create Firm Account
            Account firm = getFirmAccount(SalesRepId);
            insert firm;
            
            //Create Show
            Show__c Show = getShow(SalesRepId, firm.Id);
            insert show;
            
            Opportunity Opp1 = new Opportunity();
            Opp1.Job_Number__c = '201212313';        
            Opp1.OwnerId = OwnerId;   
            Opp1.Sales_Person__c = SalesRepId;        
            Opp1.Sales_Location__c = '110- Las Vegas';        
            Opp1.Name = 'MyTestShow # 1';        
            Opp1.Prime_Contractor__c = null;        
            Opp1.Production_Location__c = '110- Las Vegas';        
            Opp1.Facility__c = Facility.Id;        
            Opp1.StageName = 'CR';        
            Opp1.Amount = 1000;        
            Opp1.Probability = 0;        
            Opp1.Type = 'ITYFTY';        
            Opp1.New_Repeat__c = 'New';        
            Opp1.Frequency__c = 'B1';        
            Opp1.AccountId = Firm.Id;       
            Opp1.Show_Name__c = Show.Id;        
            Opp1.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('AV - CR').getRecordTypeId();              
            Opp1.Show_Open_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,1);       
            Opp1.Show_Close_Date__c = Date.today().addDays(1);
            Opp1.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
            opp1.Requested_Stage__c = '';
            opp1.Show_Occurrence__c =  opp1.id;
            opp1.Show_End_Date_Time__c = system.today();
            opp1.Show_Name__c = Show.id;                        
            insert opp1;
            
            Test.startTest();
            Opportunity Opp2 = new Opportunity();
            Opp2.Job_Number__c = '201212313';        
            Opp2.OwnerId = OwnerId;   
            Opp2.Sales_Person__c = SalesRepId;        
            Opp2.Sales_Location__c = '110- Las Vegas';        
            Opp2.Name = 'MyTestShow # 1';        
            Opp2.Prime_Contractor__c = null;        
            Opp2.Production_Location__c = '110- Las Vegas';        
            Opp2.Facility__c = Facility.Id;        
            Opp2.StageName = 'CR';        
            Opp2.Amount = 1000;        
            Opp2.Probability = 0;        
            Opp2.Type = 'ITYFTY';        
            Opp2.New_Repeat__c = 'New';        
            Opp2.Frequency__c = 'B1';        
            Opp2.AccountId = Firm.Id;       
            Opp2.Show_Name__c = Show.Id;        
            Opp2.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('EMEA - AV').getRecordTypeId();              
            Opp2.Show_Open_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,1);       
            Opp2.Show_Close_Date__c = Date.today().addDays(2);
            Opp2.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
            opp2.Requested_Stage__c = '';
            opp2.Show_Occurrence__c =  opp1.id;
            opp2.Show_Name__c = Show.id;   
            opp2.Prime_Contractor__c = Firm.Id;  
            opp2.Show_End_Date_Time__c = system.today();   
            insert opp2;                          
            Test.stopTest();
            
            LOBDetailsCalculations.LOBDetailsCalculations(new Set<Id>{show.Id});    
            LOBDetailsCalculations.NewLOBDetailsCalculations(new Set<Id>{show.Id});        
        }
    }
    //Housing -1 
    static testMethod void myUnitTest3() 
    {
        User u = getUser();
        system.runAs(u)
        {
            //Create User (for Owner)            
            ID OwnerId = UserInfo.getUserId();
        
            //Create User Sales Person
            ID SalesRepId = UserInfo.getUserId();
            
            //Create facility Account
            Account facility = getFacilityAccount(SalesRepId);
            insert facility;
            
            //Create Firm Account
            Account firm = getFirmAccount(SalesRepId);
            insert firm;
            
            //Create Show
            Show__c Show = getShow(SalesRepId, firm.Id);
            insert show;
                        
            Opportunity Opp1 = new Opportunity();
            Opp1.Job_Number__c = '201212313';        
            Opp1.OwnerId = OwnerId;   
            Opp1.Sales_Person__c = SalesRepId;        
            Opp1.Sales_Location__c = '110- Las Vegas';        
            Opp1.Name = 'MyTestShow # 1';        
            Opp1.Prime_Contractor__c = null;        
            Opp1.Production_Location__c = '110- Las Vegas';        
            Opp1.Facility__c = Facility.Id;        
            Opp1.StageName = 'CR';        
            Opp1.Amount = 1000;        
            Opp1.Probability = 0;        
            Opp1.Type = 'ITYFTY';        
            Opp1.New_Repeat__c = 'New';        
            Opp1.Frequency__c = 'B1';        
            Opp1.AccountId = Firm.Id;       
            Opp1.Show_Name__c = Show.Id;        
            Opp1.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('EMEA – Housing').getRecordTypeId();              
            Opp1.Show_Open_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,1);       
            Opp1.Show_Close_Date__c = Date.today().addDays(1);
            Opp1.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
            opp1.Requested_Stage__c = '';
            opp1.Show_Occurrence__c =  opp1.id;
            opp1.Show_End_Date_Time__c = system.today();
            opp1.Show_Name__c = Show.id;                        
            insert opp1;
            
            Test.startTest();
            Opportunity Opp2 = new Opportunity();
            Opp2.Job_Number__c = '201212313';        
            Opp2.OwnerId = OwnerId;   
            Opp2.Sales_Person__c = SalesRepId;        
            Opp2.Sales_Location__c = '110- Las Vegas';        
            Opp2.Name = 'MyTestShow # 1';        
            Opp2.Prime_Contractor__c = null;        
            Opp2.Production_Location__c = '110- Las Vegas';        
            Opp2.Facility__c = Facility.Id;        
            Opp2.StageName = 'CR';        
            Opp2.Amount = 1000;        
            Opp2.Probability = 0;        
            Opp2.Type = 'ITYFTY';        
            Opp2.New_Repeat__c = 'New';        
            Opp2.Frequency__c = 'B1';        
            Opp2.AccountId = Firm.Id;       
            Opp2.Show_Name__c = Show.Id;        
            Opp2.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('EMEA – Housing').getRecordTypeId();              
            Opp2.Show_Open_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,1);       
            Opp2.Show_Close_Date__c = Date.today().addDays(2);
            Opp2.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
            opp2.Requested_Stage__c = '';
            opp2.Show_Occurrence__c =  opp1.id;
            opp2.Show_Name__c = Show.id;   
            opp2.Prime_Contractor__c = Firm.Id;  
            opp2.Show_End_Date_Time__c = system.today();   
            insert opp2;                          
            Test.stopTest();
            
            LOBDetailsCalculations.LOBDetailsCalculations(new Set<Id>{show.Id});
            LOBDetailsCalculations.NewLOBDetailsCalculations(new Set<Id>{show.Id});            
        }
    }
    static testMethod void myUnitTest4() 
    {
        User u = getUser();
        system.runAs(u)
        {
            //Create User (for Owner)            
            ID OwnerId = UserInfo.getUserId();
        
            //Create User Sales Person
            ID SalesRepId = UserInfo.getUserId();
            
            //Create facility Account
            Account facility = getFacilityAccount(SalesRepId);
            insert facility;
            
            //Create Firm Account
            Account firm = getFirmAccount(SalesRepId);
            insert firm;
            
            //Create Show
            Show__c Show = getShow(SalesRepId, firm.Id);
            show.Registration_Not_Applicable__c = false;
            insert show;
            
            Opportunity Opp1 = new Opportunity();
            Opp1.Job_Number__c = '201212313';        
            Opp1.OwnerId = OwnerId;   
            Opp1.Sales_Person__c = SalesRepId;        
            Opp1.Sales_Location__c = '110- Las Vegas';        
            Opp1.Name = 'MyTestShow # 1';        
            Opp1.Prime_Contractor__c = null;        
            Opp1.Production_Location__c = '110- Las Vegas';        
            Opp1.Facility__c = Facility.Id;        
            Opp1.StageName = 'CR';        
            Opp1.Amount = 1000;        
            Opp1.Probability = 0;        
            Opp1.Type = 'ITYFTY';        
            Opp1.New_Repeat__c = 'New';        
            Opp1.Frequency__c = 'B1';        
            Opp1.AccountId = Firm.Id;       
            Opp1.Show_Name__c = Show.Id;        
            Opp1.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('US - Registration').getRecordTypeId();              
            Opp1.Show_Open_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,1);       
            Opp1.Show_Close_Date__c = Date.today().addDays(1);
            Opp1.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
            opp1.Requested_Stage__c = '';
            opp1.Show_Occurrence__c =  opp1.id;
            opp1.Show_Close_Date__c = system.today();
            opp1.Show_Name__c = Show.id;                        
            insert opp1;
            
            Opportunity Opp2 = new Opportunity();
            Opp2.Job_Number__c = '201212313';        
            Opp2.OwnerId = OwnerId;   
            Opp2.Sales_Person__c = SalesRepId;        
            Opp2.Sales_Location__c = '110- Las Vegas';        
            Opp2.Name = 'MyTestShow # 1';        
            Opp2.Prime_Contractor__c = null;        
            Opp2.Production_Location__c = '110- Las Vegas';        
            Opp2.Facility__c = Facility.Id;        
            Opp2.StageName = 'CR';        
            Opp2.Amount = 1000;        
            Opp2.Probability = 0;        
            Opp2.Type = 'ITYFTY';        
            Opp2.New_Repeat__c = 'New';        
            Opp2.Frequency__c = 'B1';        
            Opp2.AccountId = Firm.Id;       
            Opp2.Show_Name__c = Show.Id;        
            Opp2.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('US - Registration').getRecordTypeId();
            Opp2.Show_Open_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,12,1);       
            Opp2.Show_Close_Date__c = Date.today().addDays(2);
            Opp2.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
            opp2.Requested_Stage__c = '';
            opp2.Show_Occurrence__c =  opp1.id;
            opp2.Show_Name__c = Show.id;   
            opp2.Prime_Contractor__c = Firm.Id;  
            opp2.Show_Close_Date__c = system.today();   
            insert opp2; 
            
            LOBDetailsCalculations.LOBDetailsCalculations(new Set<Id>{show.Id});       
            LOBDetailsCalculations.NewLOBDetailsCalculations(new Set<Id>{show.Id});
        }
    }
    private static User getUser()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator']; 
        User u = new User(Alias = 'culatons', 
                          Email='standarduserTestLOBDetailsCalculations@testorg.com', 
                          EmailEncodingKey='UTF-8', 
                          LastName='Testing', 
                          LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', 
                          ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', 
                          UserName='standarduserTestLOBDetailsCalculations@testorg.com');
        insert u;
        return u;
    }
    private static Account getFacilityAccount(Id SalesRepId)
    {
        //Create Facility Account
        Account Facility = new Account();
        Facility.Sales_Person__c = SalesRepId;
        Facility.Name = 'MyTestFacilityName';
        Facility.Type = 'Hotel';
        Facility.GES_Status__c = 'Preferred';
        Facility.LMS_Facility_ID__c = 'ABCFAC';
        Facility.BillingStreet = '950 Grier Dr';
        Facility.BillingCity = 'Las Vegas';
        Facility.BillingPostalCode = '89119-0000';
        Facility.BillingState = 'NV';
        Facility.BillingCountry = 'US';
        Facility.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Facility').getRecordTypeId();
        return Facility;
    }
    private static Account getFirmAccount(Id SalesRepId)
    {
        //Create Firm Account
        Account Firm = new Account();
        Firm.Sales_Person__c = SalesRepId;
        Firm.Name = 'SONY ENTERTAINMENT INC';
        Firm.Phone = '7022631500';
        Firm.BillingStreet = '950 Grier Dr';
        Firm.BillingCity = 'Las Vegas';
        Firm.BillingPostalCode = '89119-0000';
        Firm.BillingState = 'NV';
        Firm.BillingCountry = 'US';
        Firm.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Firm').getRecordTypeId();
        return firm;
    }
    private static Show__c getShow(Id SalesRepId, Id firmId)
    {
        Show__c Show = new Show__c();
        Show.Sales_Person__c = SalesRepId;
        Show.Account__c = firmId;
        Show.Name ='International CES';
        Show.Show_Type__c = 'Food Sector';
        Show.Show_ID__c = '123456';
        return show;
    }
}