unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Show_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Show_Opportunity__c</fullName>
    <label>Show Opportunity</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <description>Only to be used by EMEA Credit control</description>
    <label>Contractor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Show_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Show_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Show Opportunity/Project on which user requested service</description>
    <label>Show Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Customer Service Inquiries (Cases)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_1__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_1__c</fullName>
    <inlineHelpText>Show Hours Day 1.</inlineHelpText>
    <label>Exhibit Hall Hours Day 1</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_2__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_2__c</fullName>
    <inlineHelpText>Show Hours Day 2.</inlineHelpText>
    <label>Exhibit Hall Hours Day 2</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_3__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_3__c</fullName>
    <inlineHelpText>Show Hours Day 3.</inlineHelpText>
    <label>Exhibit Hall Hours Day 3</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_4__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_4__c</fullName>
    <inlineHelpText>Show Hours Day 4.</inlineHelpText>
    <label>Exhibit Hall Hours Day 4</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_5__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_5__c</fullName>
    <inlineHelpText>Show Hours Day 5.</inlineHelpText>
    <label>Exhibit Hall Hours Day 5</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibitor_Move_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Exhibitor_Move_In_Date__c</fullName>
    <inlineHelpText>Date when exhibitors will start move in</inlineHelpText>
    <label>Exhibitor Move-In Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Venue in which exhibition takes place</inlineHelpText>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Facility type account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Show Occurrences (Private)</relationshipLabel>
    <relationshipName>R00N40000001pjqSEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Move_Out__c.field-meta.xml
<CustomField>
    <fullName>Move_Out__c</fullName>
    <inlineHelpText>Date when exhibitors start move out</inlineHelpText>
    <label>Exhibitor Move-Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date_Time__c</fullName>
    <description>Blitz field for Opportunity Integration</description>
    <inlineHelpText>For EMEA AV Use Only.</inlineHelpText>
    <label>Show End Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date_Time__c</fullName>
    <description>Blitz field for Opportunity Integration</description>
    <label>Show Start Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Show_Opportunity_Alert__c/Show_Opportunity_Alert__c.object-meta.xml
<CustomObject>
    <description>Show opportunity specific alert</description>
    <label>Show Opportunity Alert</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Opportunity Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show_Opportunity_Alert__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Alert message</description>
    <label>Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show_Opportunity_Alert__c/fields/Show_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Show_Opportunity__c</fullName>
    <description>Show opportunity for the child alert</description>
    <label>Show Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Show Opportunity Alerts</relationshipLabel>
    <relationshipName>Show_Opportunity_Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/SC_ShowOpportunityAlertsControllerTest.cls
@isTest
private class SC_ShowOpportunityAlertsControllerTest {

    @isTest static void testShowOpportunityController() {

        Opportunity opp = getTestOpportunity();
        addAlert(opp.Id);
        addAlert(opp.Id);
        addAlert(opp.Id);
        addAlert(opp.Id);
        addAlert(opp.Id);
        addAlert(opp.Id);
        addAlert(opp.Id);
        addAlert(opp.Id);
        addAlert(opp.Id);
        addAlert(opp.Id);
        addAlert(opp.Id);
        
        Case testCase = new Case();
        testCase.Show_Opportunity__c = opp.Id;
        insert testCase;

        ApexPages.StandardController sc = new ApexPages.StandardController(testCase);
        SC_ShowOpportunityAlertsController controller = new SC_ShowOpportunityAlertsController(sc);

        System.assertEquals(controller.errorMessage, null);
        System.assertEquals(controller.oppAlerts.size(), 11);

        System.assertEquals(controller.getRecords().size(), 4);
        controller.getPageRange();
        controller.con.next();
        controller.con.next();
        controller.getPageRange();
    }

    @isTest static void testShowOpportunityControllerNoShow() {
        Case testCase = new Case();
        testCase.Show_Opportunity__c = null;
        insert testCase;

        ApexPages.StandardController sc = new ApexPages.StandardController(testCase);
        SC_ShowOpportunityAlertsController controller = new SC_ShowOpportunityAlertsController(sc);

        System.assertEquals(controller.errorMessage, 'This case is not linked to a show opportunity.');
    }

    @isTest static void testShowOpportunityControllerNoAlerts() {
        Opportunity opp = getTestOpportunity();
        Case testCase = new Case();
        testCase.Show_Opportunity__c = opp.Id;
        insert testCase;

        ApexPages.StandardController sc = new ApexPages.StandardController(testCase);
        SC_ShowOpportunityAlertsController controller = new SC_ShowOpportunityAlertsController(sc);

        System.assert(String.isNotBlank(controller.errorMessage));
    }

    public static Opportunity getTestOpportunity() {
        RecordType facilityRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'Facility' and SobjectType = 'Account' limit 1];
        RecordType contractorRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'Contractor' and SobjectType = 'Account' limit 1];
        RecordType masterShowRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'Master Show Occurrence' and SobjectType = 'Opportunity' limit 1];
        Account acc = new Account(
            Name = 'Auto Show',
            Phone = '212-460-6659',
            Fax = '212-888-6523',
            BillingStreet = '1201 S Figueroa St.' ,
            BillingCity = 'Los Angeles' ,
            BillingState = 'CA',
            BillingPostalCode = '90015-1308',
            NumberOfEmployees = 500,
            AnnualRevenue = 60000000);
        Account facility = new Account(
            Name = 'Las Vegas Convention Center',
            Phone = '(702) 892-0711',
            Fax = '555-555-5555',
            BillingStreet = '43150 Paradise Rd.',
            BillingCity = 'Las Vegas',
            BillingState = 'NV' ,
            BillingPostalCode = '89109',
            NumberOfEmployees = 200,
            AnnualRevenue = 20000000,
            RecordTypeId = facilityRT.Id);
        List<Account> accList = new List<Account>();
        accList.add(acc);
        accList.add(facility);
        insert acclist;
        Opportunity opp = new Opportunity(
            Name = 'LA Auto Show',
            AccountId = acc.Id,
            Facility__c = facility.Id,
            CloseDate = System.Today() + 40,
            StageName = 'CV',
            Amount = 30000,
            Show_Start_Date_Time__c = System.Today() + 12,
            Show_End_Date_Time__c = System.Today() + 17,
            Exhibit_Hall_Hours_Day_1__c = '5:00 PM To 8:00 PM',
            Exhibit_Hall_Hours_Day_2__c = '7:00 AM To 6:30 PM',
            Exhibit_Hall_Hours_Day_3__c = '8:00 AM To 4:00 PM',
            Exhibit_Hall_Hours_Day_4__c = '9:00 AM To 10:00 PM',
            Exhibit_Hall_Hours_Day_5__c = '9:00 AM To 10:00 PM',
            Exhibitor_Move_In_Date__c = System.Today() + 11,
            RecordTypeId = masterShowRT.Id,
            Prime_Contractor__c = acc.Id,
            Move_Out__c = System.Today() + 14);
        insert opp;
        return opp;
    }

    public static Show_Opportunity_Alert__c addAlert(String oppId) {
        Show_Opportunity_Alert__c newAlert = new Show_Opportunity_Alert__c();
        newAlert.Show_Opportunity__c = oppId;
        newAlert.Message__c = 'This is a test';
        insert newAlert;
        return newAlert;
    }
}