unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <description>Displays facility of show</description>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility_Address__c.field-meta.xml
<CustomField>
    <fullName>Facility_Address__c</fullName>
    <description>Displays location of the facility</description>
    <label>Facility Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/FormulaShowDates__c.field-meta.xml
<CustomField>
    <fullName>FormulaShowDates__c</fullName>
    <formula>TEXT(Show_Start_Date__c) + &#39; - &#39; + TEXT(Show_End_Date__c)</formula>
    <label>Show Dates</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <description>Displays the opportunity name</description>
    <label>Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <formula>Connect2_Show__r.Show_Name__c</formula>
    <label>Show Name Formula</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/LC_ProjectCentralHomePage.cls
public  with sharing class LC_ProjectCentralHomePage {
   @AuraEnabled
    public static List<GC_Connect2_Show__c> getShowsApex() {  
     List<GC_Connect2_Show__c> shows =
            [SELECT Id, Name, Show_End_Date__c,FormulaShowDates__c  ,Show_Start_Date__c,Show_Name__c, Opportunity_Name__c,Facility__c, Job_Number__c,Facility_Address__c
              FROM GC_Connect2_Show__c  WHERE Job_Number__c!=null AND Show_End_Date__c>TODAY order by Show_Start_Date__c asc  LIMIT 2000 ];
        return shows;
    } 
      
    //SAL-1215 - added isPastShow parametner in the method call to display the Past shows - 07/26/24 - Sajid
    @AuraEnabled
    public static List<GC_Connect2_Show__c> getrecords(string searchname,date searchbydatefield, Boolean isPastShow) {
        
        searchname= string.isNotBlank(searchname)?searchname.normalizeSpace():searchname;
        String searchKey = '%' + searchname + '%';
        String searchQueryString = 'SELECT Id, Name, Show_End_Date__c,FormulaShowDates__c ,Show_Start_Date__c,Show_Name__c, Opportunity_Name__c,Facility__c, Job_Number__c,Facility_Address__c FROM GC_Connect2_Show__c WHERE Job_Number__c!=null ';
        
        if(searchname != null && searchbydatefield != null){
            searchQueryString +=' AND (Show_Name__c Like :searchKey OR Show_Start_Date__c  =: searchbydatefield)';
        }
        else if(searchname != null){
            searchQueryString += ' AND Show_Name__c Like :searchKey';
        }
        
        else if(searchbydatefield != null){
            searchQueryString += ' AND Show_Start_Date__c  =: searchbydatefield';
        }
        //SAL-1215 - Display the Past shows - 07/26/24 - Sajid
        if(isPastShow){
            searchQueryString += ' AND Show_End_Date__c  < TODAY order by Show_Start_Date__c desc  LIMIT 2000';
        }else{
            searchQueryString += ' AND Show_End_Date__c  >= TODAY';
        }
        //SAL-1215 - end
        
        List<GC_Connect2_Show__c> showsdetail = new  List<GC_Connect2_Show__c>();
        showsdetail = Database.query(searchQueryString);
        return showsdetail;
    } 
    
     @AuraEnabled
    public static string checkUsersPermission() {
        string profileId= userInfo.getProfileId();
        if(System.Label.LC_ProfilesToCreateSTM.contains(userInfo.getProfileId()) || System.Label.LC_ProfilesToCreateSTM.contains(profileId.left(15))){
            return 'canCreateSTM';
        }else{
            throw new AuraHandledException('Please consult your Account Manager');
        }
        
    }
 
    @AuraEnabled
    public static boolean overRidePermissions() {
        return(System.Label.LC_AtShowOverride.contains(UserInfo.getProfileId())); 
    }
    
    @AuraEnabled
    public static string saveNewSTM(GC_Show_Team_Member__c newSTM) {
        try{
            upsert newSTM;
            return null;
        }catch(exception e){
            string errorMessage= e.getMessage();
            return errorMessage ;
        }
    }
    
    //method to be called to maintain the current show on every page
    @AuraEnabled
    public static GC_Connect2_Show__c returnCurrentShow(String projectNumber) {
        GC_Connect2_Show__c currentShow =[SELECT Id, Name, Show_End_Date__c ,Show_Start_Date__c,Show_Name__c, Opportunity_Name__c,Facility__c, Job_Number__c
              FROM GC_Connect2_Show__c WHERE Job_Number__c=:projectNumber];
        return currentShow;
    }
    
 
   /* @AuraEnabled
    public static List<String> getUserSessionID() {
        List<String> results= new List<String>();
        string apiSsn= LC_IntegrationsApexController.getSessionIDWithLogin();
        string userSsn= LC_IntegrationsApexController.getUserSessionID();
        results.add(userSsn);
        results.add(apiSsn);
        return results;
    }*/
    
    @AuraEnabled 
    public static user fetchUser(){
       User u = [select id,FirstName from User where id =: userInfo.getUserId()];
        return u;
    }
}