unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Venue in which exhibition takes place</inlineHelpText>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Facility type account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Show Occurrences (Private)</relationshipLabel>
    <relationshipName>R00N40000001pjqSEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Facility_City__c.field-meta.xml
<CustomField>
    <fullName>Facility_City__c</fullName>
    <formula>IF(   ISBLANK( Show_Occurrence__c )  , occurrence_city__c, Show_Occurrence__r.occurrence_city__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Facility City</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Show Job Number.</inlineHelpText>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/RecordType_Name__c.field-meta.xml
<CustomField>
    <fullName>RecordType_Name__c</fullName>
    <formula>$RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RecordType Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Close_Date__c</fullName>
    <inlineHelpText>Date exhibition floor closes; if show close date unknown, select last day of appropriate month</inlineHelpText>
    <label>Exhibition Close Date.</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/classes/GC_ShowSync.cls
/**
* @author Ethos Solutions
* @version 1.0
* @description Syncs the Opportunity with the Schedule
*
* 2016-12-09 : Ethos Solutions - Original
**/
global class GC_ShowSync implements Schedulable {
    global void execute(SchedulableContext sc) {
        String yesterdayFormatted = DateTime.now().addDays(-1).formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        System.debug(loggingLevel.Error, '*** yesterdayFormatted: ' + yesterdayFormatted);
        String query = 'select Id, Name, Show_Close_Date__c, Show_Name__r.Name, Job_Number__c, Amount, RecordType.Name, RecordType_Name__c, Facility__r.Name, Facility_City__c from Opportunity where Job_Number__c != null AND LastModifiedDate >= ' + yesterdayFormatted + ' order by Show_Close_Date__c desc limit 50000';
        try {
            GC_OpportunityToShowBatch batchProcess = new GC_OpportunityToShowBatch(query);
            Database.executeBatch(batchProcess);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }
}