unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/GES_Status__c.field-meta.xml
<CustomField>
    <fullName>GES_Status__c</fullName>
    <label>GES Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exclusive</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>None of the above</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <externalId>true</externalId>
    <label>LMS Facility ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/LMS_Firm_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Firm_ID__c</fullName>
    <externalId>true</externalId>
    <label>LMS Firm ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person MUST be same as Account Owner.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <description>Only to be used by EMEA Credit control</description>
    <label>Contractor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Firm.recordType-meta.xml
<RecordType>
    <fullName>Firm</fullName>
    <active>true</active>
    <description>A Management Company, Sponsor, Contractor (Prime and Sub), and Competitor related to Shows and Show Occurrences.</description>
    <label>Firm</label>
</RecordType>

unpackaged/main/default/objects/Account_Credit__c/Account_Credit__c.object-meta.xml
<CustomObject>
    <description>Re-design of Credit information directly to an Account record, and allow multiple SO records to be linked.</description>
    <label>Account-Credit</label>
    <nameField>
        <displayFormat>AC-{00000}</displayFormat>
        <label>Account-Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account-Credit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Credit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account-Credit</relationshipLabel>
    <relationshipName>Account_Credit</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Credit__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Credit</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advance_Payment__c/Advance_Payment__c.object-meta.xml
<CustomObject>
    <description>As part of the credit re-design, this object will hold the advance payments related to an account- credit record, if advance payments are required.  This object has a link to the account-credit object, and to the show opportunity record for which the advance payments are required.</description>
    <label>Advance Payment</label>
    <nameField>
        <displayFormat>AP# -{00000}</displayFormat>
        <label>AP No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advance Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advance_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Account_Credit__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Advance_Payment__c/fields/Account_Credit__c.field-meta.xml
<CustomField>
    <fullName>Account_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account-Credit</label>
    <referenceTo>Account_Credit__c</referenceTo>
    <relationshipName>Advance_Payment_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advance_Payment__c/fields/Advance_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Advance_Payment_Amount__c</fullName>
    <label>Advance Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Advance_Payment__c/fields/Advance_Payment_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Advance_Payment_Due_Date__c</fullName>
    <label>Advance Payment Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Advance_Payment__c/fields/Date_Paid__c.field-meta.xml
<CustomField>
    <fullName>Date_Paid__c</fullName>
    <label>Date Paid</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Advance_Payment__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advance_Payment_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advance_Payment__c/fields/sent30dayNotice__c.field-meta.xml
<CustomField>
    <fullName>sent30dayNotice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>sent30dayNotice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Advance_Payment__c/fields/sent5dayNotice__c.field-meta.xml
<CustomField>
    <fullName>sent5dayNotice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>sent5dayNotice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Advance_Payment__c/fields/sentPastDueNotice__c.field-meta.xml
<CustomField>
    <fullName>sentPastDueNotice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>sentPastDueNotice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Advance_Payment__c/fields/Show_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Show_Occurrence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Show Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Advance Payments</relationshipLabel>
    <relationshipName>Advance_Payment_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Venue in which exhibition takes place</inlineHelpText>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Facility type account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Show Occurrences (Private)</relationshipLabel>
    <relationshipName>R00N40000001pjqSEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <formula>Facility__r.LMS_Facility_ID__c</formula>
    <inlineHelpText>Facility ID (acronym)</inlineHelpText>
    <label>Facility ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/New_Repeat__c.field-meta.xml
<CustomField>
    <fullName>New_Repeat__c</fullName>
    <inlineHelpText>If GES produced prior occurrence, business is &quot;Repeat&quot;, if GES did not produce prior occurrence, business is &quot;New&quot;</inlineHelpText>
    <label>New/Repeat</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Repeat</fullName>
            </value>
            <value>
                <fullName>ADP</fullName>
            </value>
            <value>
                <fullName>Up Sell</fullName>
            </value>
            <value>
                <fullName>Cross Sell</fullName>
            </value>
            <value>
                <fullName>Electric Only</fullName>
            </value>
            <value>
                <fullName>New Logo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary sales person (regardless of user type)</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N40000001qZlCEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Show_Occurrence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Corporate Accounts &amp; AV Projects</relationshipLabel>
    <relationshipName>Show_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <description>The show type field from Show object, only for Custom Build opportunities</description>
    <formula>IF( RecordTypeId = &#39;01240000000DuxL&#39;,  TEXT( Show_Name__r.Show_Type__c ) ,  TEXT( Show_Occurrence__r.Show_Name__r.Show_Type__c ) )</formula>
    <inlineHelpText>The Show type</inlineHelpText>
    <label>Show Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account Name.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shows (Account)</relationshipLabel>
    <relationshipName>Shows2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_ID__c.field-meta.xml
<CustomField>
    <fullName>Show_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Legacy System Identifier.</inlineHelpText>
    <label>Show ID (LMS)</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <inlineHelpText>CEIR Industry Groupings</inlineHelpText>
    <label>Show Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Services</fullName>
            </value>
            <value>
                <fullName>Consumer Goods and Retail Trade</fullName>
            </value>
            <value>
                <fullName>Discretionary Consumer Goods &amp; Services</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food Sector</fullName>
            </value>
            <value>
                <fullName>Financial, Legal and Real Estate</fullName>
            </value>
            <value>
                <fullName>Government, Public &amp; Non-Profit Services</fullName>
            </value>
            <value>
                <fullName>Building, Construction, Home &amp; Repair</fullName>
            </value>
            <value>
                <fullName>Industrial / Heavy Machinery / Finished Business Outputs</fullName>
            </value>
            <value>
                <fullName>Communications &amp; Information Technology</fullName>
            </value>
            <value>
                <fullName>Medical &amp; Healthcare</fullName>
            </value>
            <value>
                <fullName>Raw Materials &amp; Science</fullName>
            </value>
            <value>
                <fullName>Sporting Goods, Travel and Amusement</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Museum, Traveling Exhibition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/testAdvancePaymentAlerts.cls
@isTest
private class testAdvancePaymentAlerts {
     public class SalesforceUpsertOrganisationMokup implements WebServiceMock {
        String sfID;
        public SalesforceUpsertOrganisationMokup(String SalesforceID) {
            sfID = SalesforceID;
        }

        public void doInvoke(
           Object stub,
           Object request,
           Map<String, Object> response,
           String endpoint,
           String soapAction,
           String requestName,
           String responseNS,
           String responseName,
           String responseType) {

        SOP_VIAD_V2.SalesforceUpsertOrganisationResult suor = new SOP_VIAD_V2.SalesforceUpsertOrganisationResult();
        suor.EUSopID = 43621;
        suor.MESopID = 23231;
        suor.SalesforceID = this.sfID;
        suor.UKSopID = 23212;
        SOP_VIAD_V2.SalesforceUpsertOrganisationResponse_element respElement = new SOP_VIAD_V2.SalesforceUpsertOrganisationResponse_element();
        respElement.SalesforceUpsertOrganisationResult = suor;
        response.put('response_x', respElement); 
        }
    }
	static testmethod void test() {
		
		ID SalesRepId = UserInfo.getUserId();
		
        RecordType SalesRepOppRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND NAME = 'Sales Rep Show Occurrence' LIMIT 1];
        RecordType FirmRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND NAME = 'Firm'];
        RecordType FacilityRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND NAME = 'Facility'];
        
        
        
        Show__c s = [select id, Show_ID__c, Account__c from Show__c where Show_ID__c != null And Account__c != null limit 1];
        
        Account ac1 = [select id from Account where Id =: s.Account__c limit 1];   
        
        //Create Firm Account
        Account Firm = new Account();
        //Firm.Id = s.Account__c;
        Firm.Sales_Person__c = SalesRepId;
        Firm.Name = 'MyTestFirmName';
        Firm.Type = 'Association'; 
        Firm.LMS_Firm_ID__c = 'FIRM01';
        Firm.BillingStreet = '950 Grier Dr';
        Firm.BillingCity = 'Las Vegas';
        Firm.BillingPostalCode = '89119-1234';
        Firm.BillingState = 'Nevada';
        Firm.BillingCountry = 'US';
        Firm.RecordTypeId = FirmRT.Id;
        
        Database.insert(Firm);

        Test.setMock(WebServiceMock.class, new SalesforceUpsertOrganisationMokup(Firm.id));
        
        //Create Prime Contractor Account
        Account PrimeContractor = new Account();
        PrimeContractor.Sales_Person__c = SalesRepId;
        PrimeContractor.Name = 'MyTestPrimeContractorName';
        PrimeContractor.Type = 'Contractor Competitor'; 
        PrimeContractor.LMS_Firm_ID__c = 'FIRM02';
        PrimeContractor.BillingStreet = '950 Grier Dr';
        PrimeContractor.BillingCity = 'Las Vegas';
        PrimeContractor.BillingPostalCode = '89119-1234';
        PrimeContractor.BillingState = 'Nevada';
        PrimeContractor.BillingCountry = 'US';
        PrimeContractor.RecordTypeId = FirmRT.Id;
        
        Database.insert(PrimeContractor);        
        
                
        //Create Facility
        Account Facility = new Account();
        //Facility.Id = s.Account__c;
        Facility.Sales_Person__c = SalesRepId;
        Facility.Name = 'MyTestFacilityName';
        Facility.Type = 'Hotel'; 
        Facility.GES_Status__c = 'Preferred';
        Facility.LMS_Facility_ID__c = 'GYRNMP';
        Facility.BillingStreet = '950 Grier Dr';
        Facility.BillingCity = 'Las Vegas';
        Facility.BillingPostalCode = '89119-0000';
        Facility.BillingState = 'Nevada';
        Facility.BillingCountry = 'US';
        Facility.RecordTypeId = FacilityRT.Id;
        
        Database.insert(Facility);       
        
        
        //Create Show
        Show__c Show = new Show__c();
        Show.Sales_Person__c = SalesRepId;
        Show.Account__c = Firm.Id;
        Show.Name ='MyTestShow';
        Show.Show_Type__c = 'Food Sector';
        Show.Show_ID__c = '123456';
        
		Database.insert(Show);   
        
        Contact ct1 = new Contact(AccountID=Firm.Id, LastName='test');
        Database.insert(ct1);
         
        Opportunity op1 = new Opportunity (Name='TestOppty', Sales_Person__c=SalesRepId, Show_Name__c = Show.Id,
                                           AccountId=Firm.Id, Prime_Contractor__c=PrimeContractor.Id, StageName='CR', Amount = 100, 
                                           Facility__c=Facility.Id,RecordTypeId = SalesRepOppRT.Id,
                                           New_Repeat__c='New', CloseDate=Date.today().addDays(3));
         									
        Database.insert(op1);
        
        Account_Credit__c acNew = new Account_Credit__c();
        acNew.Account__c = Firm.Id;
        insert acNew;
        
        Advance_Payment__c ap1 = new Advance_Payment__c(Advance_Payment_Due_Date__c = Date.today().addDays(3));
        ap1.Account_Credit__c = acNew.Id;
        ap1.Advance_Payment_Amount__c = 100;
        ap1.Show_Occurrence__c = op1.id;
        ap1.sent5dayNotice__c = false;
        ap1.Date_Paid__c = null;
       
        insert ap1;
        
        Advance_Payment__c ap2 = new Advance_Payment__c(Advance_Payment_Due_Date__c = Date.today().addDays(9));
        ap2.Account_Credit__c = acNew.Id;
        ap2.Advance_Payment_Amount__c = 100;
        ap2.Show_Occurrence__c = op1.id;       
        ap2.sent30dayNotice__c = false;
        ap2.Date_Paid__c = null;
        insert ap2;
        
        Advance_Payment__c ap3 = new Advance_Payment__c(Advance_Payment_Due_Date__c = Date.today().addDays(-2));
        ap3.Account_Credit__c = acNew.Id;
        ap3.Advance_Payment_Amount__c = 100;
        ap3.Show_Occurrence__c = op1.id;       
        ap3.sent30dayNotice__c = false;
        ap3.Date_Paid__c = null;
        insert ap3;
        
        DateTime d0Days = DateTime.now();
		DateTime d5Days = DateTime.now().addDays(5);
		String sd0Days = d0Days.formatGmt('yyyy-MM-dd');
		String sd5Days = d5Days.formatGmt('yyyy-MM-dd');
		
		Batch5dayAdvancePaymentAlert b5 = new Batch5dayAdvancePaymentAlert();
		b5.email = 'sfawcett@astadia.com';
		String query = 'SELECT sent30dayNotice__c, sent5dayNotice__c, Show_Occurrence__r.StageName, Show_Occurrence__r.RecordTypeID';
		query+= ' FROM Advance_Payment__c WHERE sent5dayNotice__c = false';
		query+= ' AND Date_Paid__c = null AND Advance_Payment_Due_Date__c <=' + sd5Days;
		query+= ' AND Advance_Payment_Due_Date__c >= ' + sd0Days;
		b5.query = query;
		Database.executeBatch(b5);
		
		DateTime d30Days = DateTime.now().addDays(30);
		DateTime d6Days = DateTime.now().addDays(6);
		String sd30Days = d30Days.formatGmt('yyyy-MM-dd');
		String sd6Days = d6Days.formatGmt('yyyy-MM-dd');
		
		Batch30dayAdvancePaymentAlert b30 = new Batch30dayAdvancePaymentAlert();
		b30.email = 'sfawcett@astadia.com';
		String query2 = 'SELECT sent30dayNotice__c, sent5dayNotice__c, Show_Occurrence__r.StageName, Show_Occurrence__r.RecordTypeID';
		query2+= ' FROM Advance_Payment__c WHERE sent30dayNotice__c = false';
		query2+= ' AND Date_Paid__c = null AND Advance_Payment_Due_Date__c <=' + sd30Days;
		query2+= ' AND Advance_Payment_Due_Date__c >= ' + sd6Days;
		b30.query = query2;
		Database.executeBatch(b30);
		
		DateTime d0Days1 = DateTime.now();
		String sd0Days1 = d0Days1.formatGmt('yyyy-MM-dd');
		
		BatchPastDueAdvancePaymentAlert pd = new BatchPastDueAdvancePaymentAlert();
		pd.email = 'sfawcett@astadia.com';
		pd.sendWrapUpEmail = false;
		String query3 = 'SELECT sentPastDueNotice__c, Show_Occurrence__r.StageName, Show_Occurrence__r.RecordTypeID';
		query3+= ' FROM Advance_Payment__c WHERE sent5dayNotice__c = false AND sentPastDueNotice__c = false';
		query3+= ' AND Date_Paid__c = null AND Advance_Payment_Due_Date__c <' + sd0Days1;
		pd.query = query3;
		Database.executeBatch(pd);
	}
}