unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/GES_Status__c.field-meta.xml
<CustomField>
    <fullName>GES_Status__c</fullName>
    <label>GES Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exclusive</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>None of the above</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <externalId>true</externalId>
    <label>LMS Facility ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person MUST be same as Account Owner.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Exhibitor.recordType-meta.xml
<RecordType>
    <fullName>Exhibitor</fullName>
    <active>true</active>
    <description>E&amp;D Exhibitor Accounts</description>
    <label>Exhibitor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Venue in which exhibition takes place</inlineHelpText>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Facility type account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Show Occurrences (Private)</relationshipLabel>
    <relationshipName>R00N40000001pjqSEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <formula>Facility__r.LMS_Facility_ID__c</formula>
    <inlineHelpText>Facility ID (acronym)</inlineHelpText>
    <label>Facility ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Production_Location__c.field-meta.xml
<CustomField>
    <fullName>Production_Location__c</fullName>
    <description>As determined by Operations / Exhibitions account management. Any additions or edits also need to be made to the Locations object.</description>
    <inlineHelpText>Operational location producing exhibition</inlineHelpText>
    <label>Production Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120-OnPeak</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix</fullName>
            </value>
            <value>
                <fullName>180 - Registration</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles, CA</fullName>
            </value>
            <value>
                <fullName>230-Intl Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>270- Corporate Events (Marketing Dept only)</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460 - Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470 - Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480- Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Florida</fullName>
            </value>
            <value>
                <fullName>530- New Orleans</fullName>
            </value>
            <value>
                <fullName>610- Portland, Seattle</fullName>
            </value>
            <value>
                <fullName>710- Chicago, Cleveland, Milwaukee, St. Louis</fullName>
            </value>
            <value>
                <fullName>810- New York &amp; Boston</fullName>
            </value>
            <value>
                <fullName>830-DC, Philadelphia</fullName>
            </value>
            <value>
                <fullName>890- Toronto, Canada</fullName>
            </value>
            <value>
                <fullName>940 - Tradeshow Foreign</fullName>
            </value>
            <value>
                <fullName>944 - E&amp;E Foreign</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi, UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Location__c.field-meta.xml
<CustomField>
    <fullName>Sales_Location__c</fullName>
    <inlineHelpText>Primary exhibition sales person&#39;s office/team</inlineHelpText>
    <label>Sales Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120- Housing</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix, Tucson, Albquerque</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles</fullName>
            </value>
            <value>
                <fullName>230- Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>290 - Audio Visual</fullName>
            </value>
            <value>
                <fullName>310 - Lead Gen</fullName>
            </value>
            <value>
                <fullName>320 - Program</fullName>
            </value>
            <value>
                <fullName>330 - GES INT, DPM</fullName>
            </value>
            <value>
                <fullName>340 - GES UK, BD</fullName>
            </value>
            <value>
                <fullName>350 - GES Europe, BD</fullName>
            </value>
            <value>
                <fullName>360 - GES Middle East, BD</fullName>
            </value>
            <value>
                <fullName>370 - Retail INT, BD</fullName>
            </value>
            <value>
                <fullName>380 - Show Team</fullName>
            </value>
            <value>
                <fullName>390 - Branded Entertainment</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460- Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470- Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Miami, Orlando, Tampa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary sales person (regardless of user type)</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N40000001qZlCEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <description>The show type field from Show object, only for Custom Build opportunities</description>
    <formula>IF( RecordTypeId = &#39;01240000000DuxL&#39;,  TEXT( Show_Name__r.Show_Type__c ) ,  TEXT( Show_Occurrence__r.Show_Name__r.Show_Type__c ) )</formula>
    <inlineHelpText>The Show type</inlineHelpText>
    <label>Show Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account Name.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shows (Account)</relationshipLabel>
    <relationshipName>Shows2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_ID__c.field-meta.xml
<CustomField>
    <fullName>Show_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Legacy System Identifier.</inlineHelpText>
    <label>Show ID (LMS)</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <inlineHelpText>CEIR Industry Groupings</inlineHelpText>
    <label>Show Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Services</fullName>
            </value>
            <value>
                <fullName>Consumer Goods and Retail Trade</fullName>
            </value>
            <value>
                <fullName>Discretionary Consumer Goods &amp; Services</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food Sector</fullName>
            </value>
            <value>
                <fullName>Financial, Legal and Real Estate</fullName>
            </value>
            <value>
                <fullName>Government, Public &amp; Non-Profit Services</fullName>
            </value>
            <value>
                <fullName>Building, Construction, Home &amp; Repair</fullName>
            </value>
            <value>
                <fullName>Industrial / Heavy Machinery / Finished Business Outputs</fullName>
            </value>
            <value>
                <fullName>Communications &amp; Information Technology</fullName>
            </value>
            <value>
                <fullName>Medical &amp; Healthcare</fullName>
            </value>
            <value>
                <fullName>Raw Materials &amp; Science</fullName>
            </value>
            <value>
                <fullName>Sporting Goods, Travel and Amusement</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Museum, Traveling Exhibition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TestTrg_Update_Showplan_New.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=false)
private class TestTrg_Update_Showplan_New {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        //Create User (for Owner)
        ID OwnerId = UserInfo.getUserId();
        
        //Create User Sales Person
        ID SalesRepId = UserInfo.getUserId();
        
        //Create Facility
        Account Facility = new Account();
        Facility.Sales_Person__c = SalesRepId;
        Facility.Name = 'MyTestFacilityName';
        Facility.Type = 'Hotel';
        Facility.GES_Status__c = 'Preferred';
        Facility.LMS_Facility_ID__c = 'ABCFAC';
        Facility.BillingStreet = '950 Grier Dr';
        Facility.BillingCity = 'Las Vegas';
        Facility.BillingPostalCode = '89119-0000';
        Facility.BillingState = 'Nevada';
        Facility.BillingCountry = 'US';
        Facility.RecordTypeId = '012400000005NYN';
        
        insert Facility;
        
        //Create Account
        Account Exhibitor = new Account();
        Exhibitor.Sales_Person__c = SalesRepId;
        Exhibitor.Name = 'MyTestExhibitorName';
        Exhibitor.Phone = '7022631500';
        Exhibitor.BillingStreet = '950 Grier Dr';
        Exhibitor.BillingCity = 'Las Vegas';
        Exhibitor.BillingPostalCode = '89119-0000';
        Exhibitor.BillingState = 'NV';
        Exhibitor.BillingCountry = 'US';
        Exhibitor.RecordTypeId = '0124000000012Ob';
        
        insert Exhibitor;
                
        //Create Show
        Show__c Show = new Show__c();
        Show.Sales_Person__c = SalesRepId;
        Show.Account__c = Exhibitor.Id;
        Show.Name ='MyTestShow';
        Show.Show_Type__c = 'Food Sector';
        Show.Show_ID__c = '123456';
        
        Test.startTest();
        insert Show;        
        
        Id EDRecordTypeId = null;
        Id EDWonRecordTypeId = null;
        Id EDProposalRecordTypeId = null;
        //Id BEProjectsRecordTypeId = null;
        //Id BEProjectsReadOnlyRecordTypeId = null;
        Id SalesRepShowOccurrenceRecordTypeId = null;
    
        // Fetch RecordTypeIds
        List<string> listRecordTypes = new List<string>();
        listRecordTypes.add(Properties.edProjectsRecordTypeName);
        listRecordTypes.add(Properties.edProjectsProposalRecordTypeName);
        listRecordTypes.add(Properties.edProjectsReadOnlyRecordTypeName);
        //listRecordTypes.add(Properties.beProjectsRecordTypeName);
        //listRecordTypes.add(Properties.beProjectsReadOnlyRecordTypeName); 
        listRecordTypes.add('Sales Rep Show Occurrence');
        
        for(RecordType r : [SELECT Id, Name FROM RecordType WHERE Name IN : listRecordTypes AND SobjectType = 'Opportunity']){
          if(r.Name == Properties.edProjectsRecordTypeName){
              EDRecordTypeId = r.Id;
            }
            else if(r.Name == Properties.edProjectsProposalRecordTypeName){
              EDWonRecordTypeId = r.Id;
            }
            else if(r.Name == Properties.edProjectsReadOnlyRecordTypeName){
              EDProposalRecordTypeId = r.Id;
            }
            /* else if (r.Name == Properties.beProjectsRecordTypeName) {
              BEProjectsRecordTypeId = r.Id;
            }
            else if (r.Name == Properties.beProjectsReadOnlyRecordTypeName) {
              BEProjectsReadOnlyRecordTypeId = r.Id;
            } */
            else if (r.Name == 'Sales Rep Show Occurrence') {
                SalesRepShowOccurrenceRecordTypeId = r.Id;
            }
        }        
        
        /*
        //Create ShowOccurrence for E&D Record Type
        Opportunity EDShowOcc = new Opportunity();
       
        EDShowOcc.OwnerId = OwnerId;
        EDShowOcc.Sales_Person__c = SalesRepId;
        EDShowOcc.Sales_Location__c = '520- Miami, Orlando, Tampa';
        EDShowOcc.Name = 'E&DOpp';
        EDShowOcc.Prime_Contractor__c = null;
        EDShowOcc.Production_Location__c = '710- Chicago, Cleveland, Milwaukee, St. Louis';
        EDShowOcc.Facility__c = Facility.Id;
        EDShowOcc.StageName = 'OF';
        EDShowOcc.Amount = 1000;
        EDShowOcc.Type = 'ITYFTY';
        EDShowOcc.New_Repeat__c = 'New';
        EDShowOcc.Frequency__c = 'B1';
        EDShowOcc.Job_Number_Status__c = 'Open';
        EDShowOcc.AccountId = Exhibitor.Id;
        EDShowOcc.Show_Name__c = Show.Id;
        EDShowOcc.RecordTypeId = EDRecordTypeId;
        
        Date OpenDate1 = Date.newInstance(DateTime.now().yearGmt(),12,1);
        Date CloseDate1 = Date.newInstance(DateTime.now().yearGmt(),12,2);
        
        EDShowOcc.Show_Open_Date__c = OpenDate1;
        EDShowOcc.Show_Close_Date__c = CloseDate1;
        EDShowOcc.CloseDate = CloseDate1;
        
        //Create ShowOccurrence for E&D Won Record Type
        Opportunity EDWonShowOcc = new Opportunity();
       
        EDWonShowOcc.OwnerId = OwnerId;
        EDWonShowOcc.Sales_Person__c = SalesRepId;
        EDWonShowOcc.Sales_Location__c = '520- Miami, Orlando, Tampa';
        EDWonShowOcc.Name = 'E&DWonOpp';
        EDWonShowOcc.Prime_Contractor__c = null;
        EDWonShowOcc.Production_Location__c = '710- Chicago, Cleveland, Milwaukee, St. Louis';
        EDWonShowOcc.Facility__c = Facility.Id;
        EDWonShowOcc.StageName = 'OF';
        EDWonShowOcc.Amount = 1000;
        EDWonShowOcc.Type = 'ITYFTY';
        EDWonShowOcc.New_Repeat__c = 'New';
        EDWonShowOcc.Frequency__c = 'B1';
        EDWonShowOcc.Job_Number_Status__c = 'Open';
        EDWonShowOcc.AccountId = Exhibitor.Id;
        EDWonShowOcc.Show_Name__c = Show.Id;
        
        Date OpenDate2 = Date.newInstance(DateTime.now().yearGmt(),12,1);
        Date CloseDate2 = Date.newInstance(DateTime.now().yearGmt(),12,2);
        
        EDWonShowOcc.Show_Open_Date__c = OpenDate2;
        EDWonShowOcc.Show_Close_Date__c = CloseDate2;
        EDWonShowOcc.CloseDate = CloseDate2;
        EDWonShowOcc.RecordTypeId = EDWonRecordTypeId;
              
        //Create ShowOccurrence for E&D Proposal Record Type
        Opportunity EDProposalShowOcc = new Opportunity();
       
        EDProposalShowOcc.OwnerId = OwnerId;
        EDProposalShowOcc.Sales_Person__c = SalesRepId;
        EDProposalShowOcc.Sales_Location__c = '520- Miami, Orlando, Tampa';
        EDProposalShowOcc.Name = 'E&DProposalOpp';
        EDProposalShowOcc.Prime_Contractor__c = null;
        EDProposalShowOcc.Production_Location__c = '710- Chicago, Cleveland, Milwaukee, St. Louis';
        EDProposalShowOcc.Facility__c = Facility.Id;
        EDProposalShowOcc.StageName = 'OF';
        EDProposalShowOcc.Amount = 1000;
        EDProposalShowOcc.Type = 'ITYFTY';
        EDProposalShowOcc.New_Repeat__c = 'New';
        EDProposalShowOcc.Frequency__c = 'B1';
        EDProposalShowOcc.Job_Number_Status__c = 'Open';
        EDProposalShowOcc.AccountId = Exhibitor.Id;
        EDProposalShowOcc.Show_Name__c = Show.Id;
        EDProposalShowOcc.RecordTypeId = EDProposalRecordTypeId;
        
        Date OpenDate3 = Date.newInstance(DateTime.now().yearGmt(),12,1);
        Date CloseDate3 = Date.newInstance(DateTime.now().yearGmt(),12,2);
        
        EDProposalShowOcc.Show_Open_Date__c = OpenDate3;
        EDProposalShowOcc.Show_Close_Date__c = CloseDate3;
        EDProposalShowOcc.CloseDate = CloseDate3;
        
        */
        
        /*
        //Create ShowOccurrence for BE Projects Record Type
        Opportunity BEProjectsShowOcc = new Opportunity();
       
        BEProjectsShowOcc.OwnerId = OwnerId;
        BEProjectsShowOcc.Sales_Person__c = SalesRepId;
        BEProjectsShowOcc.Sales_Location__c = '520- Miami, Orlando, Tampa';
        BEProjectsShowOcc.Name = 'BEProjectOpp';
        BEProjectsShowOcc.Prime_Contractor__c = null;
        BEProjectsShowOcc.Production_Location__c = '710- Chicago, Cleveland, Milwaukee, St. Louis';
        BEProjectsShowOcc.Facility__c = Facility.Id;
        BEProjectsShowOcc.StageName = 'OF';
        BEProjectsShowOcc.Amount = 1000;
        BEProjectsShowOcc.Type = 'ITYFTY';
        BEProjectsShowOcc.New_Repeat__c = 'New';
        BEProjectsShowOcc.Frequency__c = 'B1';
        BEProjectsShowOcc.Job_Number_Status__c = 'Open';
        BEProjectsShowOcc.AccountId = Exhibitor.Id;
        BEProjectsShowOcc.Show_Name__c = Show.Id;
        BEProjectsShowOcc.RecordTypeId = BEProjectsRecordTypeId;
        
        Date OpenDate4 = Date.newInstance(DateTime.now().yearGmt(),12,1);
        Date CloseDate4 = Date.newInstance(DateTime.now().yearGmt(),12,2);
        
        BEProjectsShowOcc.Show_Open_Date__c = OpenDate4;
        BEProjectsShowOcc.Show_Close_Date__c = CloseDate4;
        BEProjectsShowOcc.CloseDate = CloseDate4; 
        
        //Create ShowOccurrence for BE Projects Read Only Record Type
        Opportunity BEProjectsReadOnlyShowOcc = new Opportunity();
       
        BEProjectsReadOnlyShowOcc.OwnerId = OwnerId;
        BEProjectsReadOnlyShowOcc.Sales_Person__c = SalesRepId;
        BEProjectsReadOnlyShowOcc.Sales_Location__c = '520- Miami, Orlando, Tampa';
        BEProjectsReadOnlyShowOcc.Name = 'BEProjectOpp';
        BEProjectsReadOnlyShowOcc.Prime_Contractor__c = null;
        BEProjectsReadOnlyShowOcc.Production_Location__c = '710- Chicago, Cleveland, Milwaukee, St. Louis';
        BEProjectsReadOnlyShowOcc.Facility__c = Facility.Id;
        BEProjectsReadOnlyShowOcc.StageName = 'OF';
        BEProjectsReadOnlyShowOcc.Amount = 1000;
        BEProjectsReadOnlyShowOcc.Type = 'ITYFTY';
        BEProjectsReadOnlyShowOcc.New_Repeat__c = 'New';
        BEProjectsReadOnlyShowOcc.Frequency__c = 'B1';
        BEProjectsReadOnlyShowOcc.Job_Number_Status__c = 'Open';
        BEProjectsReadOnlyShowOcc.AccountId = Exhibitor.Id;
        BEProjectsReadOnlyShowOcc.Show_Name__c = Show.Id;
        BEProjectsReadOnlyShowOcc.RecordTypeId = BEProjectsReadOnlyRecordTypeId;
        
        Date OpenDate5 = Date.newInstance(DateTime.now().yearGmt(),12,1);
        Date CloseDate5 = Date.newInstance(DateTime.now().yearGmt(),12,2);
        
        BEProjectsReadOnlyShowOcc.Show_Open_Date__c = OpenDate5;
        BEProjectsReadOnlyShowOcc.Show_Close_Date__c = CloseDate5;
        BEProjectsReadOnlyShowOcc.CloseDate = CloseDate5;
        
        */
               
        //Create ShowOccurrence for Sales Rep Show Occurrence Record Type
        Opportunity SalesRepShowOcc = new Opportunity();
       
        SalesRepShowOcc.OwnerId = OwnerId;
        SalesRepShowOcc.Sales_Person__c = SalesRepId;
        SalesRepShowOcc.Sales_Location__c = '520- Miami, Orlando, Tampa';
        SalesRepShowOcc.Name = 'SalesRepProjectOpp';
        SalesRepShowOcc.Prime_Contractor__c = null;
        SalesRepShowOcc.Production_Location__c = '710- Chicago, Cleveland, Milwaukee, St. Louis';
        SalesRepShowOcc.Facility__c = Facility.Id;
        SalesRepShowOcc.StageName = 'Closed Won';
        SalesRepShowOcc.Amount = 1000;
        SalesRepShowOcc.Type = 'ITYFTY';
        SalesRepShowOcc.New_Repeat__c = 'New';
        SalesRepShowOcc.Frequency__c = 'B1';
        SalesRepShowOcc.Job_Number_Status__c = 'Open';
        SalesRepShowOcc.AccountId = Exhibitor.Id;
        SalesRepShowOcc.Show_Name__c = Show.Id;
        SalesRepShowOcc.RecordTypeId = SalesRepShowOccurrenceRecordTypeId;
        
        Date OpenDate6 = Date.newInstance(DateTime.now().yearGmt()-1,12,1);
        Date CloseDate6 = Date.newInstance(DateTime.now().yearGmt()-1,12,2);
        
        SalesRepShowOcc.Show_Open_Date__c = OpenDate6;
        SalesRepShowOcc.Show_Close_Date__c = CloseDate6;
        SalesRepShowOcc.CloseDate = CloseDate6;
        
        list<Opportunity> OppsToInsert = new list<Opportunity>();
        
        /*
        OppsToInsert.add(EDShowOcc);
        OppsToInsert.add(EDWonShowOcc);
        OppsToInsert.add(EDProposalShowOcc);
        */
        //OppsToInsert.add(BEProjectsShowOcc);
        //OppsToInsert.add(BEProjectsReadOnlyShowOcc);
        
        OppsToInsert.add(SalesRepShowOcc);
                
        database.insert(OppsToInsert); 
        
        Show_Plan__c ShowPlan = new Show_Plan__c();
        ShowPlan.Show_Opportunity__c = SalesRepShowOcc.Id;
        ShowPlan.Proposal_Due_Date__c = Date.newInstance(DateTime.now().yearGmt()-1,DateTime.now().monthGmt()+1,1);
        ShowPlan.Previous_Occurrence_Revenue__c = 9000;
        ShowPlan.Show_Name__c = SalesRepShowOcc.Show_Name__c;
        
        //Database.insert(ShowPlan, false);
        
        //database.update(OppsToInsert);
        
        //Create ShowOccurrence for Sales Rep Show Occurrence Record Type
        Opportunity NextSalesRepShowOcc = new Opportunity();
       
        NextSalesRepShowOcc.OwnerId = OwnerId;
        NextSalesRepShowOcc.Sales_Person__c = SalesRepId;
        NextSalesRepShowOcc.Sales_Location__c = '520- Miami, Orlando, Tampa';
        NextSalesRepShowOcc.Name = 'SalesRepProjectOpp';
        NextSalesRepShowOcc.Prime_Contractor__c = null;
        NextSalesRepShowOcc.Production_Location__c = '710- Chicago, Cleveland, Milwaukee, St. Louis';
        NextSalesRepShowOcc.Facility__c = Facility.Id;
        NextSalesRepShowOcc.StageName = 'OF';
        NextSalesRepShowOcc.Amount = 1000;
        NextSalesRepShowOcc.Type = 'ITYFTY';
        NextSalesRepShowOcc.New_Repeat__c = 'New';
        NextSalesRepShowOcc.Frequency__c = 'B1';
        NextSalesRepShowOcc.Job_Number_Status__c = 'Open';
        NextSalesRepShowOcc.AccountId = Exhibitor.Id;
        NextSalesRepShowOcc.Show_Name__c = Show.Id;
        NextSalesRepShowOcc.RecordTypeId = SalesRepShowOccurrenceRecordTypeId;
        
        Date OpenDate7 = Date.newInstance(DateTime.now().yearGmt(),12,1);
        Date CloseDate7 = Date.newInstance(DateTime.now().yearGmt(),12,2);
        
        NextSalesRepShowOcc.Show_Open_Date__c = OpenDate7;
        NextSalesRepShowOcc.Show_Close_Date__c = CloseDate7;
        NextSalesRepShowOcc.CloseDate = CloseDate7;
        
        list<Opportunity> NextOppsToInsert = new list<Opportunity>();
               
        NextOppsToInsert.add(NextSalesRepShowOcc);
                
        //database.insert(NextOppsToInsert); 
        
        Show_Plan__c NextShowPlan = new Show_Plan__c();
        NextShowPlan.Show_Opportunity__c = NextSalesRepShowOcc.Id;
        NextShowPlan.Proposal_Due_Date__c = Date.newInstance(DateTime.now().yearGmt(),DateTime.now().monthGmt()+1,1);
        NextShowPlan.Previous_Occurrence_Revenue__c = 9000;
        NextShowPlan.Show_Name__c = NextSalesRepShowOcc.Show_Name__c;
        
        //Database.insert(NextShowPlan, false);
        
        //NextOppsToInsert.add(SalesRepShowOcc);
        
        List<Show_Plan__c>  SP = new List<Show_Plan__c>();
        SP.add(ShowPlan);
        SP.add(NextShowPlan);
        
        database.insert(SP);  
        
        SalesRepShowOcc.Account_Plan__c = ShowPlan.Id;
        NextSalesRepShowOcc.Account_Plan__c = NextShowPlan.Id;
                
        database.insert(NextOppsToInsert);
        
        test.stopTest();
     
               
    }
}