unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <externalId>true</externalId>
    <label>LMS Facility ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <description>Only to be used by EMEA Credit control</description>
    <label>Contractor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_1__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_1__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 1</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_2__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_2__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 2</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_3__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_3__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 3</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_4__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_4__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 4</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibit_Hall_Hours_Day_5__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_5__c</fullName>
    <description>Field that displays hall hours</description>
    <label>Exhibit Hall Hours Day 5</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <description>Displays facility of show</description>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>Facility_ID__c</fullName>
    <label>Facility ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility_lk__c.field-meta.xml
<CustomField>
    <fullName>Facility_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Connect2_Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <description>Displays the opportunity name</description>
    <label>Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ED_Opportunity_Owner__c.field-meta.xml
<CustomField>
    <fullName>ED_Opportunity_Owner__c</fullName>
    <description>E&amp;D Sales Rep from GBMS</description>
    <label>ED Opportunity Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_1__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_1__c</fullName>
    <inlineHelpText>Show Hours Day 1.</inlineHelpText>
    <label>Exhibit Hall Hours Day 1</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_2__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_2__c</fullName>
    <inlineHelpText>Show Hours Day 2.</inlineHelpText>
    <label>Exhibit Hall Hours Day 2</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_3__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_3__c</fullName>
    <inlineHelpText>Show Hours Day 3.</inlineHelpText>
    <label>Exhibit Hall Hours Day 3</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_4__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_4__c</fullName>
    <inlineHelpText>Show Hours Day 4.</inlineHelpText>
    <label>Exhibit Hall Hours Day 4</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibit_Hall_Hours_Day_5__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Hall_Hours_Day_5__c</fullName>
    <inlineHelpText>Show Hours Day 5.</inlineHelpText>
    <label>Exhibit Hall Hours Day 5</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exhibitor_Move_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Exhibitor_Move_In_Date__c</fullName>
    <inlineHelpText>Date when exhibitors will start move in</inlineHelpText>
    <label>Exhibitor Move-In Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Venue in which exhibition takes place</inlineHelpText>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Facility type account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Show Occurrences (Private)</relationshipLabel>
    <relationshipName>R00N40000001pjqSEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/GES_Move_In__c.field-meta.xml
<CustomField>
    <fullName>GES_Move_In__c</fullName>
    <inlineHelpText>GES Move in Day 1.</inlineHelpText>
    <label>GES Move-In Date 1</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Show Job Number.</inlineHelpText>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <formula>Facility__r.LMS_Facility_ID__c</formula>
    <inlineHelpText>Facility ID (acronym)</inlineHelpText>
    <label>Facility ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Move_Out__c.field-meta.xml
<CustomField>
    <fullName>Move_Out__c</fullName>
    <inlineHelpText>Date when exhibitors start move out</inlineHelpText>
    <label>Exhibitor Move-Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/RecordType_Name__c.field-meta.xml
<CustomField>
    <fullName>RecordType_Name__c</fullName>
    <formula>$RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RecordType Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date_Time__c</fullName>
    <description>Blitz field for Opportunity Integration</description>
    <inlineHelpText>For EMEA AV Use Only.</inlineHelpText>
    <label>Show End Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Show_Occurrence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Corporate Accounts &amp; AV Projects</relationshipLabel>
    <relationshipName>Show_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date_Time__c</fullName>
    <description>Blitz field for Opportunity Integration</description>
    <label>Show Start Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SOP_Event_ID__c.field-meta.xml
<CustomField>
    <fullName>SOP_Event_ID__c</fullName>
    <description>Holds EMEA SOP Event ID, only Exhibition</description>
    <inlineHelpText>Please enter the SOP Event ID, this should be a six digit number</inlineHelpText>
    <label>SOP Event ID</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/GC_OpportunityTriggerHandlerTest.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Test code for Opportunity trigger handler
* 2016-04-13 : Original Version
**/
@isTest
public class GC_OpportunityTriggerHandlerTest {

    static testMethod void validateOpportunityUpdate() {
        
        Opportunity opp = GC_TestUtils.getTestOpportunity();
        RecordType masterShowRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'EMEA - Exhibition' and SobjectType = 'Opportunity' limit 1];
        opp.RecordTypeId = masterShowRT.Id;
        opp.SOP_Event_ID__c = 11.0;
        Test.startTest();
        update opp;
        List<Opportunity> oppList= [select RecordType_Name__c, SOP_Event_ID__c, Job_Number__c from Opportunity];
        system.debug('op==='+oppList);
        GC_OpportunityTriggerHandler.HandleOpps(oppList);
        // Re-query to get lookup fields
        opp = GC_OpportunityDao.getInstance().getOppById(opp.Id);
        Test.stopTest();

        /*GC_Connect2_Show__c show = GC_Connect2ShowDao.getInstance().getByOpportunityId(opp.Id);
        System.assertEquals(opp.Exhibit_Hall_Hours_Day_1__c, show.Exhibit_Hall_Hours_Day_1__c);
        System.assertEquals(opp.Exhibit_Hall_Hours_Day_2__c, show.Exhibit_Hall_Hours_Day_2__c);
        System.assertEquals(opp.Exhibit_Hall_Hours_Day_3__c, show.Exhibit_Hall_Hours_Day_3__c);
        System.assertEquals(opp.Exhibit_Hall_Hours_Day_4__c, show.Exhibit_Hall_Hours_Day_4__c);
        System.assertEquals(opp.Exhibit_Hall_Hours_Day_5__c, show.Exhibit_Hall_Hours_Day_5__c);
        System.assertEquals(opp.Name, show.Opportunity_Name__c);
        System.assertEquals(opp.Facility__c, show.Facility_lk__c);
        System.assertEquals(opp.LMS_Facility_ID__c, show.Facility_ID__c);*/
    }
    
    static testMethod void validateOpportunityUpdateNoShowOccurance() 
    {        
        RecordType facilityRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'Facility' and SobjectType = 'Account' limit 1];
        RecordType contractorRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'Contractor' and SobjectType = 'Account' limit 1];
        RecordType masterShowRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'E&D - Projects - Read Only' and SobjectType = 'Opportunity' limit 1];
        Account acc = new Account(
            Name = 'Auto Show',
            Phone = '212-460-6659',
            Fax = '212-888-6523',
            BillingStreet = '1201 S Figueroa St.' ,
            BillingCity = 'Los Angeles' ,
            BillingState = 'CA',
            BillingPostalCode = '90015-1308',
            NumberOfEmployees = 500,
            AnnualRevenue = 60000000);
        Account facility = new Account(
            Name = 'Las Vegas Convention Center',
            Phone = '(702) 892-0711',
            Fax = '555-555-5555',
            BillingStreet = '43150 Paradise Rd.',
            BillingCity = 'Las Vegas',
            BillingState = 'NV' ,
            BillingPostalCode = '89109',
            NumberOfEmployees = 200,
            LMS_Facility_ID__c = '123456',
            AnnualRevenue = 20000000,
            RecordTypeId = facilityRT.Id);
        List<Account> accList = new List<Account>();
        accList.add(acc);
        accList.add(facility);
        insert acclist;
        Opportunity opp = new Opportunity(
            Name = 'LA Auto Show',
            AccountId = acc.Id,
            Facility__c = facility.Id,
            CloseDate = System.Today() + 40,
            Amount = 30000,
            Show_Start_Date_Time__c = System.Today() + 12,
            Show_End_Date_Time__c = System.Today() + 17,
            Exhibit_Hall_Hours_Day_1__c = '5:00 PM To 8:00 PM',
            Exhibit_Hall_Hours_Day_2__c = '7:00 AM To 6:30 PM',
            Exhibit_Hall_Hours_Day_3__c = '8:00 AM To 4:00 PM',
            Exhibit_Hall_Hours_Day_4__c = '9:00 AM To 10:00 PM',
            Exhibit_Hall_Hours_Day_5__c = '9:00 AM To 10:00 PM',
            Exhibitor_Move_In_Date__c = System.Today() + 11,
            RecordTypeId = masterShowRT.Id,
            Prime_Contractor__c = acc.Id,
            SOP_Event_ID__c = 11.0,
            StageName = 'Closed Won',
            ED_Opportunity_Owner__c = 'Test ED Owner',
            Move_Out__c = System.Today() + 14);
        insert opp;
        Test.setCreatedDate(opp.Id, DateTime.newInstance(2012,12,12));
        
        Test.startTest();
        update opp;
        
        List<Opportunity> oppList= [select RecordType_Name__c, SOP_Event_ID__c, Job_Number__c, StageName from Opportunity];
        GC_OpportunityTriggerHandler.HandleOpps(oppList);
        system.debug('EDoppList==' +oppList);
        opp = GC_OpportunityDao.getInstance().getOppById(opp.Id);
        Test.stopTest();
    }

    static testMethod void validateOpportunityUpdateWithShowOccurance() 
    {        
        RecordType facilityRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'Facility' and SobjectType = 'Account' limit 1];
        RecordType contractorRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'Contractor' and SobjectType = 'Account' limit 1];
        RecordType masterShowRT = [Select Id, SobjectType, Name From RecordType WHERE Name = 'E&D - Projects - Read Only' and SobjectType = 'Opportunity' limit 1];
        RecordType x = [Select Id, SobjectType, Name From RecordType WHERE Name = 'Master Show Occurrence' and SobjectType = 'Opportunity' limit 1];
        Account acc = new Account(
            Name = 'Auto Show2',
            Phone = '212-460-6657',
            Fax = '212-888-6533',
            BillingStreet = '1202 S Figueroa St.' ,
            BillingCity = 'Los Angeles 2' ,
            BillingState = 'FL',
            BillingPostalCode = '90115-1308',
            NumberOfEmployees = 501,
            AnnualRevenue = 60000000);
        Account facility = new Account(
            Name = 'Las Vegas Convention Center',
            Phone = '(702) 892-0711',
            Fax = '555-555-5555',
            BillingStreet = '43150 Paradise Rd.',
            BillingCity = 'Las Vegas',
            BillingState = 'NV' ,
            BillingPostalCode = '89109',
            NumberOfEmployees = 200,
            LMS_Facility_ID__c = '123456',
            AnnualRevenue = 20000000,
            RecordTypeId = facilityRT.Id);
        List<Account> accList = new List<Account>();
        accList.add(acc);
        accList.add(facility);
        insert acclist;
        Opportunity opp2 = new Opportunity(
            Name = 'LA Auto Show2',
            AccountId = acc.Id,
            Facility__c = facility.Id,
            CloseDate = System.Today() + 41,
            Amount = 30001,
            Show_Start_Date_Time__c = System.Today() + 13,
            Show_End_Date_Time__c = System.Today() + 18,
            Exhibit_Hall_Hours_Day_1__c = '6:00 PM To 8:00 PM',
            Exhibit_Hall_Hours_Day_2__c = '8:00 AM To 6:30 PM',
            Exhibit_Hall_Hours_Day_3__c = '9:00 AM To 4:00 PM',
            Exhibit_Hall_Hours_Day_4__c = '10:00 AM To 10:00 PM',
            Exhibit_Hall_Hours_Day_5__c = '11:00 AM To 10:00 PM',
            Exhibitor_Move_In_Date__c = System.Today() + 11,
            RecordTypeId = x.Id,
            Prime_Contractor__c = acc.Id,
            SOP_Event_ID__c = 12.0,
            StageName = 'Closed Won',
            ED_Opportunity_Owner__c = 'Test ED Owner2',
            Move_Out__c = System.Today() + 14);
        insert opp2;
        Opportunity opp = new Opportunity(
            Name = 'LA Auto Show2',
            AccountId = acc.Id,
            Facility__c = facility.Id,
            CloseDate = System.Today() + 41,
            Amount = 30001,
            Show_Start_Date_Time__c = System.Today() + 13,
            Show_End_Date_Time__c = System.Today() + 18,
            Exhibit_Hall_Hours_Day_1__c = '6:00 PM To 8:00 PM',
            Exhibit_Hall_Hours_Day_2__c = '8:00 AM To 6:30 PM',
            Exhibit_Hall_Hours_Day_3__c = '9:00 AM To 4:00 PM',
            Exhibit_Hall_Hours_Day_4__c = '10:00 AM To 10:00 PM',
            Exhibit_Hall_Hours_Day_5__c = '11:00 AM To 10:00 PM',
            Exhibitor_Move_In_Date__c = System.Today() + 11,
            RecordTypeId = masterShowRT.Id,
            Prime_Contractor__c = acc.Id,
            SOP_Event_ID__c = 12.0,
            StageName = 'Closed Won',
            ED_Opportunity_Owner__c = 'Test ED Owner2',
            Show_Occurrence__c = opp2.Id,
            Move_Out__c = System.Today() + 14);
        insert opp;
        Test.setCreatedDate(opp.Id, DateTime.newInstance(2012,12,12));
        
        Test.startTest();
        update opp;
        
        List<Opportunity> oppList= [select RecordType_Name__c, SOP_Event_ID__c, Job_Number__c, StageName from Opportunity];
        GC_OpportunityTriggerHandler.HandleOpps(oppList);
        system.debug('EDoppList==' +oppList);
        opp = GC_OpportunityDao.getInstance().getOppById(opp.Id);
        Test.stopTest();
    }


    static testMethod void testBatch() {
        Opportunity opp = GC_TestUtils.getTestOpportunity();
        opp.GES_Move_In__c = System.Today();
        update opp;

        String selectStr = GC_OpportunityDao.getInstance().getSelect('', '', null);
        GC_OpportunityToShowBatch b = new GC_OpportunityToShowBatch(selectStr);

        Test.startTest();

        Database.executeBatch(b);

        Test.stopTest();

        //GC_Connect2_Show__c show = GC_Connect2ShowDao.getInstance().getByOpportunityId(opp.Id);

        //System.assertNotEquals(null, show);
    }
}