unpackaged/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non-Shows</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/GES_Status__c.field-meta.xml
<CustomField>
    <fullName>GES_Status__c</fullName>
    <label>GES Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exclusive</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>None of the above</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <externalId>true</externalId>
    <label>LMS Facility ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person MUST be same as Account Owner.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Exhibitor.recordType-meta.xml
<RecordType>
    <fullName>Exhibitor</fullName>
    <active>true</active>
    <description>E&amp;D Exhibitor Accounts</description>
    <label>Exhibitor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <formula>Facility__r.LMS_Facility_ID__c</formula>
    <inlineHelpText>Facility ID (acronym)</inlineHelpText>
    <label>Facility ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Production_Location__c.field-meta.xml
<CustomField>
    <fullName>Production_Location__c</fullName>
    <description>As determined by Operations / Exhibitions account management. Any additions or edits also need to be made to the Locations object.</description>
    <inlineHelpText>Operational location producing exhibition</inlineHelpText>
    <label>Production Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120-OnPeak</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix</fullName>
            </value>
            <value>
                <fullName>180 - Registration</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles, CA</fullName>
            </value>
            <value>
                <fullName>230-Intl Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>270- Corporate Events (Marketing Dept only)</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460 - Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470 - Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480- Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Florida</fullName>
            </value>
            <value>
                <fullName>530- New Orleans</fullName>
            </value>
            <value>
                <fullName>610- Portland, Seattle</fullName>
            </value>
            <value>
                <fullName>710- Chicago, Cleveland, Milwaukee, St. Louis</fullName>
            </value>
            <value>
                <fullName>810- New York &amp; Boston</fullName>
            </value>
            <value>
                <fullName>830-DC, Philadelphia</fullName>
            </value>
            <value>
                <fullName>890- Toronto, Canada</fullName>
            </value>
            <value>
                <fullName>940 - Tradeshow Foreign</fullName>
            </value>
            <value>
                <fullName>944 - E&amp;E Foreign</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi, UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Location__c.field-meta.xml
<CustomField>
    <fullName>Sales_Location__c</fullName>
    <inlineHelpText>Primary exhibition sales person&#39;s office/team</inlineHelpText>
    <label>Sales Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120- Housing</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix, Tucson, Albquerque</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles</fullName>
            </value>
            <value>
                <fullName>230- Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>290 - Audio Visual</fullName>
            </value>
            <value>
                <fullName>310 - Lead Gen</fullName>
            </value>
            <value>
                <fullName>320 - Program</fullName>
            </value>
            <value>
                <fullName>330 - GES INT, DPM</fullName>
            </value>
            <value>
                <fullName>340 - GES UK, BD</fullName>
            </value>
            <value>
                <fullName>350 - GES Europe, BD</fullName>
            </value>
            <value>
                <fullName>360 - GES Middle East, BD</fullName>
            </value>
            <value>
                <fullName>370 - Retail INT, BD</fullName>
            </value>
            <value>
                <fullName>380 - Show Team</fullName>
            </value>
            <value>
                <fullName>390 - Branded Entertainment</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460- Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470- Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Miami, Orlando, Tampa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary sales person (regardless of user type)</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N40000001qZlCEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <description>The show type field from Show object, only for Custom Build opportunities</description>
    <formula>IF( RecordTypeId = &#39;01240000000DuxL&#39;,  TEXT( Show_Name__r.Show_Type__c ) ,  TEXT( Show_Occurrence__r.Show_Name__r.Show_Type__c ) )</formula>
    <inlineHelpText>The Show type</inlineHelpText>
    <label>Show Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account Name.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shows (Account)</relationshipLabel>
    <relationshipName>Shows2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_Function_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Function_Type__c</fullName>
    <label>Show Function Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>I:Independent Organizer</fullName>
            </value>
            <value>
                <fullName>M:Show Mgmt</fullName>
            </value>
            <value>
                <fullName>S:Subcontract</fullName>
            </value>
            <value>
                <fullName>U:Union</fullName>
            </value>
            <value>
                <fullName>A:Association</fullName>
            </value>
            <value>
                <fullName>B:B-B Media/Portfolio Accounts</fullName>
            </value>
            <value>
                <fullName>C:Corporation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_ID__c.field-meta.xml
<CustomField>
    <fullName>Show_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Legacy System Identifier.</inlineHelpText>
    <label>Show ID (LMS)</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <inlineHelpText>CEIR Industry Groupings</inlineHelpText>
    <label>Show Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Services</fullName>
            </value>
            <value>
                <fullName>Consumer Goods and Retail Trade</fullName>
            </value>
            <value>
                <fullName>Discretionary Consumer Goods &amp; Services</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food Sector</fullName>
            </value>
            <value>
                <fullName>Financial, Legal and Real Estate</fullName>
            </value>
            <value>
                <fullName>Government, Public &amp; Non-Profit Services</fullName>
            </value>
            <value>
                <fullName>Building, Construction, Home &amp; Repair</fullName>
            </value>
            <value>
                <fullName>Industrial / Heavy Machinery / Finished Business Outputs</fullName>
            </value>
            <value>
                <fullName>Communications &amp; Information Technology</fullName>
            </value>
            <value>
                <fullName>Medical &amp; Healthcare</fullName>
            </value>
            <value>
                <fullName>Raw Materials &amp; Science</fullName>
            </value>
            <value>
                <fullName>Sporting Goods, Travel and Amusement</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Museum, Traveling Exhibition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TestCreateMarketingListPageController.cls
@isTest
private class TestCreateMarketingListPageController{

	@isTest
    static void createMarketingListPageController_Test()
    {   
		//Test converage for the myPage visualforce page
		//Create Test Data First
		
		//Create User (for Owner)
		ID OwnerId = UserInfo.getUserId();
		
		//Create User Sales Person
		ID SalesRepId = UserInfo.getUserId();
		
		//Create Facility
		Account Facility = new Account();
		Facility.Sales_Person__c = SalesRepId;
		Facility.Name = 'MyTestFacilityName';
		Facility.Type = 'Hotel';
		Facility.GES_Status__c = 'Preferred';
		Facility.LMS_Facility_ID__c = 'ABCFAC';
		Facility.BillingStreet = '950 Grier Dr';
		Facility.BillingCity = 'Las Vegas';
		Facility.BillingPostalCode = '89119';
		Facility.BillingState = 'Nevada';
		Facility.BillingCountry = 'US';
		Facility.RecordTypeId = '012400000005NYN';
		
		//Create Account
		Account Exhibitor = new Account();
		Exhibitor.Sales_Person__c = SalesRepId;
		Exhibitor.Name = 'MyTestExhibitorName';
		Exhibitor.Phone = '7022631500';
		Exhibitor.BillingStreet = '950 Grier Dr';
		Exhibitor.BillingCity = 'Las Vegas';
		Exhibitor.BillingPostalCode = '89119';
		Exhibitor.BillingState = 'Nevada';
		Exhibitor.BillingCountry = 'US';
		Exhibitor.RecordTypeId = '0124000000012Ob';
				
		//Create Show
		Show__c Show = new Show__c();
		Show.Sales_Person__c = SalesRepId;
		Show.Account__c = Exhibitor.Id;
		Show.Name ='MyTestShow';
		Show.Show_Type__c = 'Food Sector';
		//Commenting this field as this field is being removed from "Show" object per RFC-001155
		//Show.Show_Function_Type__c = 'I:Independent Organizer';
		Show.Show_ID__c = '123456';
	     
		//Create ShowOccurrence
		Opportunity ShowOcc = new Opportunity();
	   
		ShowOcc.OwnerId = OwnerId;
		ShowOcc.Sales_Person__c = SalesRepId;
		ShowOcc.Sales_Location__c = '520- Miami, Orlando, Tampa';
		ShowOcc.Name = 'MyTestShow001';
		ShowOcc.Prime_Contractor__c = null;
		ShowOcc.Production_Location__c = '710- Chicago, Cleveland, Milwaukee, St. Louis';
		ShowOcc.Facility__c = Facility.Id;
		ShowOcc.StageName = 'OF';
		ShowOcc.Amount = 1000;
		ShowOcc.Type = 'ITYFTY';
		ShowOcc.New_Repeat__c = 'New';
		ShowOcc.Frequency__c = 'B1';
		ShowOcc.Job_Number_Status__c = 'Open';
		ShowOcc.AccountId = Exhibitor.Id;
		ShowOcc.Show_Name__c = Show.Id;
		
		Date OpenDate = Date.newInstance(2010,12,1);
		Date CloseDate = Date.newInstance(2010,12,2);
		
		ShowOcc.Show_Open_Date__c = OpenDate;
		ShowOcc.Show_Close_Date__c = CloseDate;
		ShowOcc.CloseDate = CloseDate;
		
		database.insert(ShowOcc);
		
		//Create Leads
		List<Lead> ListOfLeads = new List<Lead>();
		Lead[] InsertLeads = new Lead[200];
		Integer Count = 0;
		
		for(Integer i=0; i<201;i++)
		{
			Lead MyLead = new Lead();
			MyLead.FirstName = 'TestFirstName' + String.valueof(i);
			MyLead.LastName = 'TestLastName' + String.valueof(i);
			MyLead.Email = 'testemail' + String.valueof(i) + '@test.com';
			MyLead.Company = 'TestCompany';
			MyLead.Phone = '7029630102';
			MyLead.Street = '950 Grier Dr';
			MyLead.City = 'Las Vegas';
			MyLead.State = 'Nevada';
			MyLead.PostalCode = '89119';
			MyLead.Country = 'US';
			
			MyLead.Active_Source_Code__c = 'TESTSOURCECODE001';
			
			InsertLeads[Count] = MyLead;
			
			if (Count == 199)
			{
				Database.insert(InsertLeads, false);
				
				for(Lead lead: InsertLeads)
					ListOfLeads.add(lead.clone(true,true));
				
				Count = -1;
				InsertLeads = new Lead[1];
			}
			
			Count++;
		}
		
		
		Database.insert(InsertLeads, false);
	   
		for(Lead lead: InsertLeads)
			ListOfLeads.add(lead.clone(true,true));	   
	   
	   
		//Create Contacts
		List<Contact> ListOfContacts = new List<Contact>();
		Contact[] InsertContacts = new Contact[200];
		Count = 0;
		
		for(Integer i=0; i<201;i++)
		{
			Contact MyCon = new Contact();
			MyCon.FirstName = 'TestFirstName' + String.valueof(i);
			MyCon.LastName = 'TestLastName' + String.valueof(i);
			MyCon.Email = 'testemail' + String.valueof(i) + '@test.com';
			MyCon.Active_Source_Code__c = 'TESTSOURCECODE001';
			
			InsertContacts[Count] = MyCon;
			
			if (Count == 199)
			{
				Database.insert(InsertContacts, false);
				
				for(Contact con: InsertContacts)
					ListOfContacts.add(con.clone(true,true));				
				
				Count = -1;
				InsertContacts = new Contact[1];
			}
			
			Count++;
		}
		
		
		Database.insert(InsertContacts, false);	
		
		for(Contact con: InsertContacts)
			ListOfContacts.add(con.clone(true,true));			
		
		
		PageReference pageRef = Page.CreateMarketingSourceList;
	    Test.setCurrentPageReference(pageRef);
	
	    // create an instance of the controller
	    CreateMarketingListPageController PageController = new CreateMarketingListPageController ();
	    
	    //Call methods/properties of the controller in all possible scenarios
	    //to get the best coverage.
	    
	    Test.StartTest();
	    
	    //Get Controller Name
	    String ControllerName = PageController.getName();
	    System.assertEquals('CreateMarketingListPageController', ControllerName);
	    
	    //Invoke Save() method before Source Code and Show Id are set. This will test the
	    //the outer try{} catch{} block
	    //PageController.Save();        
	   
	    //Get Marketing Source List before it is explicitly intialized
	    //this will test the instantiation in the getMarketingSourceList() getter method
	    PageController.getMarketingSourceList();
	    
	    //Invoke Save() method before Source Code and Show Id are set. This will test the
	    //first if() block in the method
	    PageController.Save();
	    
	    //Set Source Code
	    PageController.setSourceCode('TESTSOURCECODE001');
	    String SourceCode = PageController.getSourceCode();
	    System.assertEquals('TESTSOURCECODE001',SourceCode);  
	    
	    //Invoke Save() method after Source Code is set, but before Show Id is set. This will test the
	    //else if() block in the method which tests for null or blank Show Id
	    PageController.Save();              
	    
	    //Set Marketing Source List
	    Marketing_Source_List__c Msl = new Marketing_Source_List__c();
	    Msl.Show_Occurrence__c = ShowOcc.Id;
	    
	    PageController.setMarketingSourceList(Msl);
	    
	    //Get Marekting Source List
	    System.assertEquals(PageController.getMarketingSourceList(), Msl);
	    
	    //Get Show Id
	    String ShowId = PageController .getShowId();
	    System.assertEquals(ShowOcc.Id, ShowId);
	    
	    //Cannot test these private methods
	    //Integer LeadCount = PageController.AssociateLeads(SourceCode, ShowId);
	    //Integer ConCount = PageController.AssociateContacts(SourceCode, ShowId);
	    
	    //Invoke the save method
	    PageReference ReturnedPageRef = PageController.save();
	    PageReference NullPageRef = new ApexPages.StandardController(PageController.getMarketingSourceList()).view();
	    System.assert(NullPageRef.getUrl() == ReturnedPageRef.getUrl());
	    
	    Test.StopTest();
           
    }

}