unpackaged/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is Account InActive?</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Exhibitor.recordType-meta.xml
<RecordType>
    <fullName>Exhibitor</fullName>
    <active>true</active>
    <description>E&amp;D Exhibitor Accounts</description>
    <label>Exhibitor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Firm.recordType-meta.xml
<RecordType>
    <fullName>Firm</fullName>
    <active>true</active>
    <description>A Management Company, Sponsor, Contractor (Prime and Sub), and Competitor related to Shows and Show Occurrences.</description>
    <label>Firm</label>
</RecordType>

unpackaged/main/default/objects/Booth_Setting__c/Booth_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Booth Setting</label>
</CustomObject>

unpackaged/main/default/objects/Booth_Setting__c/fields/PhoneExtension__c.field-meta.xml
<CustomField>
    <fullName>PhoneExtension__c</fullName>
    <label>PhoneExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/Booth__c.field-meta.xml
<CustomField>
    <fullName>Booth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booth</label>
    <referenceTo>Oracle_Show_Booth__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Booth__c.field-meta.xml
<CustomField>
    <fullName>Booth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booth on which user requested service</description>
    <label>Booth (Lookup)</label>
    <referenceTo>Oracle_Show_Booth__c</referenceTo>
    <relationshipLabel>Customer Service Inquiries (Cases)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if Contact is InActive.</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Text_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Text_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Invalid Phone Numbers, User Opted not to receive text messages</inlineHelpText>
    <label>Text Opt Out</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to contact, filter on the account so we only show related contacts in the search</description>
    <inlineHelpText>Please search for the relevant contact</inlineHelpText>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <infoMessage>Please select the correct contact</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact)</relationshipLabel>
    <relationshipName>OpportunitiesContact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Show Job Number.</inlineHelpText>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Show_Occurrence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Corporate Accounts &amp; AV Projects</relationshipLabel>
    <relationshipName>Show_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/Oracle_Show_Booth__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booths from Oracle</description>
    <label>Booth</label>
    <nameField>
        <label>Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booths</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booths</relationshipLabel>
    <relationshipName>Oracle_Show_Booths</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/Show_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Show_Occurrence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Show Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booths</relationshipLabel>
    <relationshipName>Oracle_Show_Booths</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/Oracle_Show_Booth_Contact__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booth Contacts from Oracle</description>
    <label>Booth Contact</label>
    <nameField>
        <displayFormat>BC-{000000000}</displayFormat>
        <label>Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booth Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship field to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Booth_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/EMAIL__c.field-meta.xml
<CustomField>
    <fullName>EMAIL__c</fullName>
    <description>Oracle Booth Contact Email</description>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/Oracle_Show_Booth__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Show_Booth__c</fullName>
    <description>Master Detail relationship to parent Booth</description>
    <label>Booth</label>
    <referenceTo>Oracle_Show_Booth__c</referenceTo>
    <relationshipLabel>Booth Contacts</relationshipLabel>
    <relationshipName>Booth_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/BoothContactAllTest.cls
@isTest
private class BoothContactAllTest {     
    @isTest 
    static void test_method_one() {

        String uid = [SELECT Id FROM User WHERE Alias = 'CorpAcct' LIMIT 1].Id;
        Id TradeshowRTId = ((RecordType)[SELECT Id FROM RecordType WHERE Name = 'Sales Rep Show Occurrence' And SObjectType = 'Opportunity']).Id;
        Id FirmRTId = ((RecordType)[SELECT Id FROM RecordType WHERE Name = 'Firm' And SObjectType = 'Account']).Id;
        Id ExhibitorRTId = ((RecordType)[SELECT Id FROM RecordType WHERE Name = 'Exhibitor' And SObjectType = 'Account']).Id;

        Account acc = new Account();
        acc.Name = 'name-firm';
        acc.RecordTypeId = FirmRTId;
        acc.BillingCity = 'city';
        acc.BillingCountry = 'US';
        acc.BillingState = 'AL';
        acc.BillingPostalCode = '12345-1234';
        acc.BillingStreet = 'street';
        acc.Phone = '12345';
        insert acc;
        
        Account exh = new Account();
        exh.Name = 'name-exhibitor';
        exh.RecordTypeId = ExhibitorRTId;
        exh.BillingCity = 'city';
        exh.BillingCountry = 'US';
        exh.BillingState = 'AL';
        exh.BillingPostalCode = '12345-1234';
        exh.BillingStreet = 'street';
        exh.Phone = '12345';
        exh.Inactive__c = false;
        insert exh;     
        
        Contact c = new Contact();
        c.LastName = 'lname';
        c.OwnerId = uid;
        c.AccountId = exh.Id;
        c.Inactive__c = false;
        insert c;
             
        Campaign cmp = new Campaign();
        cmp.Status = 'In Progress';
        cmp.Name = 'name-12345xYZ'; //Make case different from that in Opportunity Job # just to make sure the trigger code handles it
        insert cmp;          
              
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = TradeshowRTId;
        opp.CloseDate = date.today();
        opp.Name = 'name';
        opp.StageName = 'Closed Won';
        opp.Job_Number__c = '12345XYZ';
        //opp.Prime_Contractor__c = c.Id;
        opp.Amount = 1;
        opp.AccountId = acc.Id;
        insert opp; 
        
        Oracle_Show_Booth__c  b = new Oracle_Show_Booth__c();
        b.Show_Occurrence__c = opp.Id; 
        b.Account__c = exh.Id;
        insert b;
                
        Oracle_Show_Booth_Contact__c bc = new Oracle_Show_Booth_Contact__c();
        bc.Contact__c = c.Id;
        bc.Oracle_Show_Booth__c = b.Id;
        bc.Email__c = 'alex@vertiba.com';
        //bc.CreatedById = uid;
        insert bc;
        
        CampaignMember cm = new CampaignMember();
        cm.Booth__c = b.Id;
        cm.ContactId = c.Id;
        cm.CampaignId = cmp.Id;
        //insert cm;
        
        updcontactfrombooth ucfb = new updcontactfrombooth();
        updcontactfrombooth.updsyncmarketo(new map<Id, CampaignMember>([SELECT Id FROM CampaignMember]).keyset());
        /*
        //This unit test verifies that if the given contact (c) associated with booth contact (bc), is not already
        //a campaign member, it is added to the campaign
        
        Campaign cmp = [SELECT Id, Name FROM Campaign];
        
        System.debug('Campaign Id: ' + cmp.Id + ' Campaign Name: ' + cmp.Name);
        System.debug('Opportunity Id: ' + opp.Id + ' Opportunity Name: ' + opp.Name + ' Opportunity Job #: ' + opp.Job_Number__c);
        System.debug('Booth Id: ' + b.Id + ' Booth  Opportunity Id: ' + b.Show_Occurrence__c);
        System.debug('Booth Contact Id: ' + bc.Id + ' Booth Contact Email: ' + bc.Email__c);        
        
        CampaignMember cm = [SELECT Id, ContactId FROM CampaignMember WHERE CampaignId =: cmp.Id LIMIT 1];
        
        system.assertEquals(cm.ContactId, c.Id);
        
        //This unit test verifies that if the given contact (c1) associated with booth contact (bc1), is already
        //a campaign member, it should not be added to the campaign
        
        Contact c1 = new Contact();
        c1.LastName = 'lnamec1';
        c1.OwnerId = uid;
        c1.AccountId = exh.Id;
        insert c1;
        
        CampaignMember cm1 = new CampaignMember(ContactId = c1.Id, Status='Sent', Booth__c = b.Id, CampaignId = cmp.Id);
        insert cm1;
        
        Oracle_Show_Booth_Contact__c bc1 = new Oracle_Show_Booth_Contact__c();
        bc1.Contact__c = c1.Id;
        bc1.Oracle_Show_Booth__c = b.Id;
        bc1.Email__c = 'alex@vertiba.com';
        insert bc1; 
        */
    }
    @isTest
    static void test_method_two() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator']; 
        User u = new User(Alias = 'CorpAcct', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, FirstName = 'Corporate Accounts',
            TimeZoneSidKey='America/Los_Angeles', UserName='BoothContactAllTest@testorg.com');

        System.runAs(u) 
        {
            String uid = [SELECT Id FROM User WHERE Alias = 'CorpAcct' LIMIT 1].Id;
            Id TradeshowRTId = ((RecordType)[SELECT Id FROM RecordType WHERE Name = 'Sales Rep Show Occurrence' And SObjectType = 'Opportunity']).Id;
            Id FirmRTId = ((RecordType)[SELECT Id FROM RecordType WHERE Name = 'Firm' And SObjectType = 'Account']).Id;
            Id ExhibitorRTId = ((RecordType)[SELECT Id FROM RecordType WHERE Name = 'Exhibitor' And SObjectType = 'Account']).Id;
    
            Account acc = new Account();
            acc.Name = 'name-firm';
            acc.RecordTypeId = FirmRTId;
            acc.BillingCity = 'city';
            acc.BillingCountry = 'US';
            acc.BillingState = 'AL';
            acc.BillingPostalCode = '12345-1234';
            acc.BillingStreet = 'street';
            acc.Phone = '12345';
            insert acc;
            
            Account exh = new Account();
            exh.Name = 'name-exhibitor';
            exh.RecordTypeId = ExhibitorRTId;
            exh.BillingCity = 'city';
            exh.BillingCountry = 'US';
            exh.BillingState = 'AL';
            exh.BillingPostalCode = '12345-1234';
            exh.BillingStreet = 'street';
            exh.Phone = '12345';
            exh.Inactive__c = false;
            insert exh;     
            
            Contact c = new Contact();
            c.LastName = 'lname';
            c.OwnerId = uid;
            c.AccountId = exh.Id;
            c.Inactive__c = false;
            insert c;
            
            Opportunity opp = new Opportunity();
            opp.RecordTypeId = TradeshowRTId;
            opp.CloseDate = date.today();
            opp.Name = 'name';
            opp.StageName = 'Closed Won';
            opp.Job_Number__c = '12345XYZ';
            //opp.Prime_Contractor__c = c.Id;
            opp.Amount = 1;
            opp.AccountId = acc.Id;
            insert opp; 
            
            Oracle_Show_Booth__c  b = new Oracle_Show_Booth__c();
            b.Show_Occurrence__c = opp.Id; 
            b.Account__c = exh.Id;
            insert b;
                    
            Oracle_Show_Booth_Contact__c bc = new Oracle_Show_Booth_Contact__c();
            bc.Contact__c = c.Id;
            bc.Oracle_Show_Booth__c = b.Id;
            bc.Email__c = 'alex@vertiba.com';
            //database.insert(bc, false);
            insert bc;
        }
    }
    
    @isTest 
    static void TextingCampaignTest() {

        String uid = [SELECT Id FROM User WHERE Alias = 'CorpAcct' LIMIT 1].Id;
        Id TradeshowRTId = ((RecordType)[SELECT Id FROM RecordType WHERE Name = 'Sales Rep Show Occurrence' And SObjectType = 'Opportunity']).Id;
        Id FirmRTId = ((RecordType)[SELECT Id FROM RecordType WHERE Name = 'Firm' And SObjectType = 'Account']).Id;
        Id ExhibitorRTId = ((RecordType)[SELECT Id FROM RecordType WHERE Name = 'Exhibitor' And SObjectType = 'Account']).Id;

        Booth_Setting__c bs = new Booth_Setting__c(PhoneExtension__c = '+1null,EXT,ext,X');
        insert bs;
        
        Account acc = new Account();
        acc.Name = 'name-firm';
        acc.RecordTypeId = FirmRTId;
        acc.BillingCity = 'city';
        acc.BillingCountry = 'US';
        acc.BillingState = 'AL';
        acc.BillingPostalCode = '12345-1234';
        acc.BillingStreet = 'street';
        acc.Phone = '12345';
        insert acc;
        
        Account exh = new Account();
        exh.Name = 'name-exhibitor';
        exh.RecordTypeId = ExhibitorRTId;
        exh.BillingCity = 'city';
        exh.BillingCountry = 'US';
        exh.BillingState = 'AL';
        exh.BillingPostalCode = '12345-1234';
        exh.BillingStreet = 'street';
        exh.Phone = '12345';
        exh.Inactive__c = false;
        insert exh;     
        
        Contact c = new Contact();
        c.LastName = 'lname';
        c.OwnerId = uid;
        c.AccountId = exh.Id;
        c.Inactive__c = false;
        c.Phone = '+19898989898';
        c.MobilePhone = '+19898989898';
        c.Text_Opt_Out__c = false;
        insert c;
             
        Campaign cmp = new Campaign();
        cmp.Status = 'In Progress';
        cmp.Name = 'name-12345xYZ'; //Make case different from that in Opportunity Job # just to make sure the trigger code handles it
        insert cmp;          
              
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = TradeshowRTId;
        opp.CloseDate = date.today();
        opp.Name = 'name';
        opp.StageName = 'Closed Won';
        opp.Job_Number__c = '12345XYZ';
        //opp.Prime_Contractor__c = c.Id;
        opp.Amount = 1;
        opp.AccountId = acc.Id;
        insert opp; 
        
        Oracle_Show_Booth__c  b = new Oracle_Show_Booth__c();
        b.Show_Occurrence__c = opp.Id; 
        b.Account__c = exh.Id;
        insert b;
                
        Oracle_Show_Booth_Contact__c bc = new Oracle_Show_Booth_Contact__c();
        bc.Contact__c = c.Id;
        bc.Oracle_Show_Booth__c = b.Id;
        bc.Email__c = 'alex@vertiba.com';
        //bc.CreatedById = uid;
        insert bc;
        
        
    }
}