unpackaged/main/default/objects/Account/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <externalId>true</externalId>
    <label>LMS Facility ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibitor_Move_In_Date2__c.field-meta.xml
<CustomField>
    <fullName>Exhibitor_Move_In_Date2__c</fullName>
    <description>Date for client to move in</description>
    <label>Exhibitor Move-In Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Exhibitor_Move_Out_Date2__c.field-meta.xml
<CustomField>
    <fullName>Exhibitor_Move_Out_Date2__c</fullName>
    <description>Date for client to move out</description>
    <label>Exhibitor Move-Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <description>Displays the opportunity Id</description>
    <label>Opportunity Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <label>Show Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/GES_Connect_Corporate_Accounts__c.object-meta.xml
<CustomObject>
    <description>Details for GES Connect - Corporate Accounts  for the Data Requirements purpose</description>
    <label>GES Connect - Corporate Accounts</label>
    <nameField>
        <displayFormat>GCA-{0000}</displayFormat>
        <label>GES Connect - Corporate Accounts</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect - Corporate Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>GES_Connet_Corporate_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Association_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Contact_Name__c</fullName>
    <label>Association Contact Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <label>Association Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Facility_Name_Account__c.field-meta.xml
<CustomField>
    <fullName>Facility_Name_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GES Connect - Corporate Accounts</relationshipLabel>
    <relationshipName>GES_Connect_Corporate_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Housing_Logistics_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Housing_Logistics_Vendor__c</fullName>
    <label>Housing Logistics Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCD Travel</fullName>
            </value>
            <value>
                <fullName>Am Ex</fullName>
            </value>
            <value>
                <fullName>CWT</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Housing_Required_PL__c.field-meta.xml
<CustomField>
    <fullName>Housing_Required_PL__c</fullName>
    <label>Housing Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Name_of_Congress__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Congress__c</fullName>
    <label>Name of Congress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Number_of_rooms_Secured__c.field-meta.xml
<CustomField>
    <fullName>Number_of_rooms_Secured__c</fullName>
    <label>Number of Rooms Secured</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Number_of_rooms_to_Secure__c.field-meta.xml
<CustomField>
    <fullName>Number_of_rooms_to_Secure__c</fullName>
    <label>Number of Rooms to Secure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Secretariat_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Secretariat_Contact_Email__c</fullName>
    <label>Secretariat Contact Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Secretariat_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Secretariat_Contact_Name__c</fullName>
    <label>Secretariat Contact Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Secretariat_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Secretariat_Contact_Phone__c</fullName>
    <label>Secretariat Contact Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Secretariat_Name__c.field-meta.xml
<CustomField>
    <fullName>Secretariat_Name__c</fullName>
    <label>Secretariat Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Secretariat_Same_as_Association__c.field-meta.xml
<CustomField>
    <fullName>Secretariat_Same_as_Association__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SAL 476- when checked it is used to copy the association info into secretariat.</description>
    <label>Secretariat Same as Association</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Shipping Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Virgin Islands</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Shipping_Street_c__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Street_c__c</fullName>
    <label>Adv. Whs. Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>GES_Connet_Corporate_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LMS_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Facility_ID__c</fullName>
    <formula>Facility__r.LMS_Facility_ID__c</formula>
    <inlineHelpText>Facility ID (acronym)</inlineHelpText>
    <label>Facility ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Type__c.field-meta.xml
<CustomField>
    <fullName>Show_Type__c</fullName>
    <description>The show type field from Show object, only for Custom Build opportunities</description>
    <formula>IF( RecordTypeId = &#39;01240000000DuxL&#39;,  TEXT( Show_Name__r.Show_Type__c ) ,  TEXT( Show_Occurrence__r.Show_Name__r.Show_Type__c ) )</formula>
    <inlineHelpText>The Show type</inlineHelpText>
    <label>Show Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account Name.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shows (Account)</relationshipLabel>
    <relationshipName>Shows2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CongressTest.cls
@isTest
Public Class CongressTest{
    Public Static Testmethod void CongressTest()
    {
        GC_Connect2_Show__c cgs=new GC_Connect2_Show__c();   
        cgs.Show_Start_Date__c=Date.parse('3/4/2015');
        cgs.Show_End_Date__c=Date.parse('3/4/2015');
        //cgs.Opportunity_Id__c='01234';
        insert cgs;
        GES_Connect_Corporate_Accounts__c  gca=new GES_Connect_Corporate_Accounts__c();  
        gca.Name_of_Congress__c='Test';
        gca.Shipping_Street_c__c='Bangalore';
        gca.Show_Name__c=cgs.id;
        gca.Secretariat_Same_as_Association__c =true;
        gca.Secretariat_Contact_Email__c = 'reachrksinha@gmail.com';
        gca.Secretariat_Contact_Name__c= 'aAssociation_Contact_Name__c';
        gca.Secretariat_Contact_Phone__c='9789944733';
        gca.Secretariat_Name__c='aAssociation_Name__c';
        gca.Association_Contact_Name__c='2.0 Health';
        gca.Association_Name__c='Test';
        gca.Housing_Logistics_Vendor__c = 'BCD Travel';
        gca.Number_of_rooms_to_Secure__c = 3;
        gca.Number_of_rooms_Secured__c = 3;
        gca.Housing_Required_PL__c = 'No';
        gca.Shipping_Country__c='Afghanistan';
        insert gca;    
        
        system.debug('Test Show Name'+gca.Show_Name__c);
        Test.setCurrentPageReference(new PageReference('Page.Congress'));
        Test.setCurrentPageReference(new PageReference('Page.GC_Community_ShowCongress'));
        System.currentPageReference().getParameters().put('congressid',gca.id);
        ApexPages.StandardController sc=new ApexPages.StandardController(gca);
        Congress cng=new Congress(sc);
        
        cng.congid=  gca.id; //'987654678';    
        GES_Connect_Corporate_Accounts__c gotA=cng.geta();
        
        cng.updateDate();
        cng.updateCancelledDate();
        
        Account testFacility = new Account ();
        //testFacility.RecordType.DeveloperName ='Facility';
        testFacility.name='testFacility';
        testFacility.type='Hotel';
        testFacility.LMS_Facility_ID__c='1111';
        //testFacility.CurrencyIsoCode='USD - U.S. Dollar';
        
        insert testFacility;
        
        gotA.Facility_Name_Account__c=testFacility.id;
        cng.Congressedit();        
        cng.cancelAction();
        cng.getSaveTitle();
        cng.getCancelTitle(); 
        cng.copyAssociationValues();
        cng.showHousingRequiredFields();
        
        gca.Secretariat_Same_as_Association__c =false;
        upsert gca;
        system.debug('Test Show Name'+gca.Show_Name__c);
        GC_Connect2_Show__c  gests=[SELECT Show_Name__c,Show_Start_Date__c,Show_End_Date__c,Exhibitor_Move_In_Date2__c,Opportunity_Id__c,Exhibitor_Move_Out_Date2__c FROM GC_Connect2_Show__c WHERE id= :gca.Show_Name__c];
        system.debug('Test show Name'+gests);
        
        
        
        
        Account ac=new Account();
        ac.Name='show';
        ac.BillingStreet='ster';
        ac.BillingCity='city';
        ac.BillingState='BillingState';
        ac.BillingCountry='BillingCountry';
        ac.BillingPostalCode='BillingPostalCode';
        insert ac;
        
        cng.copyAssociationValues();
        cng.onFacilitySelect();
        cng.showHousingLogisticVendorOtherField();
        
        Account ac1=new Account();
        ac1.Name='show';
        ac1.BillingStreet='ster';
        ac1.BillingCity='city';
        ac1.BillingState='BillingState';
        ac1.BillingCountry='BillingCountry';
        ac1.BillingPostalCode='BillingPostalCode';
        id ab = Schema.SObjectType.account.getRecordTypeInfosByName().get('Facility').getRecordTypeId();
        ac1.recordtypeid=ab;
        insert ac1;
        
        Show__c sh=new Show__c();
        sh.Name='shows';
        sh.Show_Type__c='Medical & Healthcare';
        sh.Job_Classification__c='Congress';
        sh.Account__c=ac.id;
        sh.Website__c='www.google.com';
        sh.Show_ID__c='AMAPMR';
        sh.CurrencyIsoCode='';
        //sh.Sales_Person__c='';
        insert sh;
        /*-----*/ 
        Opportunity conOpt=new Opportunity();
        conOpt.Show_Open_Date__c=Date.parse('3/4/2015');
        conOpt.Show_Close_Date__c=Date.parse('3/4/2015');
        conOpt.AccountId=ac.id;
        conOpt.StageName='CR';
        conOpt.CurrencyIsoCode='';
        conOpt.Prime_Contractor__c=ac.id;
        conOpt.CloseDate=Date.parse('3/4/2015');
        conOpt.Name='Test';    
        conOpt.Facility__c=ac1.id;
        // conOpt.SHOW_Servi_Centre__c=sh.Account__r.Name;
        //conOpt.Show_Name__c='';
        insert conOpt;
        cgs.Opportunity_Id__c=conOpt.id;
        update cgs;
        
        GC_Connect2_Show__c  connShow= [SELECT Name, Opportunity_Id__c FROM GC_Connect2_Show__c WHERE Id = : gca.Show_Name__c];
        //  Opportunity ExhbOpp = [SELECT id,Show_Name__r.Name, Show_Name__r.Show_ID__c, Facility__r.Name, Facility__r.BillingStreet, Facility__r.BillingCity, Facility__r.BillingState, Facility__r.BillingCountry, Facility__r.BillingPostalCode, Show_Open_Date__c, Show_Close_Date__c FROM Opportunity WHERE Id = : connShow.Opportunity_Id__c];
        //system.debug('Test opportunity Name'+ExhbOpp );
        cng.fetchConnect2ShowDetails();
    }
    
    public static testMethod void popupTest() {
        Account testFacility = new Account ();
        //testFacility.RecordType.DeveloperName ='Facility';
        testFacility.name='testFacility';
        testFacility.type='Hotel';
        testFacility.LMS_Facility_ID__c='1111';
        //testFacility.CurrencyIsoCode='USD - U.S. Dollar';
        
        insert testFacility;
        PageReference pageRef = Page.CongressFacilityPopup;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('facilityName', 'testFacility');
        Congress con = new Congress();
        con.runQuery();
    }
}