unpackaged/main/default/objects/Account/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person MUST be same as Account Owner.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Firm.recordType-meta.xml
<RecordType>
    <fullName>Firm</fullName>
    <active>true</active>
    <description>A Management Company, Sponsor, Contractor (Prime and Sub), and Competitor related to Shows and Show Occurrences.</description>
    <label>Firm</label>
</RecordType>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account Name.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shows (Account)</relationshipLabel>
    <relationshipName>Shows2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>GES Sales Person.</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_ID__c.field-meta.xml
<CustomField>
    <fullName>Show_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Legacy System Identifier.</inlineHelpText>
    <label>Show ID (LMS)</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Show_Contact__c/Show_Contact__c.object-meta.xml
<CustomObject>
    <description>A custom object to display the Contacts that are associated to a Show.</description>
    <label>Show Contact</label>
    <nameField>
        <displayFormat>Show Contact#-{0000000}</displayFormat>
        <label>Show Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Contact</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R00N40000001qQACEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show_Contact__c/fields/Show__c.field-meta.xml
<CustomField>
    <fullName>Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Show</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipName>R00N40000001qQA7EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show_Plan__c/Show_Plan__c.object-meta.xml
<CustomObject>
    <description>A custom object to track the strategy planning details against those Show Occurrences not yet won.</description>
    <label>Show Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Show Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show_Plan__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <inlineHelpText>Show the plan is associated to.</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TestDetailPageShowPlan.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestDetailPageShowPlan {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        //Create User (for Owner)
        ID OwnerId = UserInfo.getUserId();
        
        //Create User Sales Person
        ID SalesRepId = UserInfo.getUserId();
                
        RecordType FirmRecordType = [Select Id From RecordType Where SObjectType = 'Account' And Name = 'Firm'];
        Id FirmRecordTypeId = FirmRecordType.Id;
        
        //Create Firm Account
        Account Firm = new Account();
        Firm.Sales_Person__c = SalesRepId;
        Firm.Name = 'SONY ENTERTAINMENT INC';
        Firm.Phone = '7022631500';
        Firm.BillingStreet = '950 Grier Dr';
        Firm.BillingCity = 'Las Vegas';
        Firm.BillingPostalCode = '89119-0000';
        Firm.BillingState = 'NV';
        Firm.BillingCountry = 'US';
        Firm.RecordTypeId = FirmRecordTypeId;
        
        Database.Insert(Firm);
        
        Show__c Show = new Show__c();
        Show.Account__c = Firm.Id;
        Show.Name = 'Test Show';
        Show.Show_ID__c = 'TESTID';
        
        Database.Insert(Show);
        
        Contact Cont = new Contact();
        Cont.FirstName = 'Test First NAme';
        Cont.LastName = 'Test Last Name';
        Cont.Email = 'testtest@fakeges.com';
        
        Database.Insert(Cont);
        
        Show_Contact__c ShowContact = new Show_Contact__c();
        ShowContact.Contact__c = Cont.Id;
        ShowContact.Show__c = Show.Id;
        
        Database.Insert(ShowContact);
        
        Show_Plan__c ShowPlan = new Show_Plan__c();
        ShowPlan.Show_Name__c = Show.Id;
        
        Database.Insert(ShowPlan);
                
        ApexPages.Standardcontroller StdCtrlr = new ApexPages.Standardcontroller(ShowPlan);
        
        /*
        ApexPages.Pagereference DetailShowPlanPage = new ApexPages.Pagereference('/apex/DetailShowPlan');
        DetailShowPlanPage.getParameters().put('id', ShowPlan.Id);
        Test.setCurrentPageReference(DetailShowPlanPage);
        */
        
        //DetailPageShowPlan Controller = new DetailPageShowPlan(StdCtrlr);
        
        //List<Contact> LoContacts = Controller.getcntacts();
        
    }
}