unpackaged/main/default/objects/GT_Event__c/GT_Event__c.object-meta.xml
<CustomObject>
    <description>Object will be used to create Generic Template Account for GES Community. Main Event object for 1st Lightning Community. CC, Merck, SS, GT, Pharma Template, NNI.</description>
    <label>GES Connect Event</label>
    <nameField>
        <displayFormat>GCE-{000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Event__c/fields/Congress_Acronym__c.field-meta.xml
<CustomField>
    <fullName>Congress_Acronym__c</fullName>
    <label>Congress Acronym</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/fields/Congress_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Congress_End_Date__c</fullName>
    <label>Congress End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/fields/Congress_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Congress_Start_Date__c</fullName>
    <label>Congress Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/fields/Wrike_Folder_ID__c.field-meta.xml
<CustomField>
    <fullName>Wrike_Folder_ID__c</fullName>
    <description>This field is used to store the ID of the folder created in Wrike for this Event. Not be used by any user in SFDC. Strictly for admin purposes only</description>
    <inlineHelpText>This field is used to store the ID of the folder created in Wrike for this Event. Not be used by any user in SFDC. Strictly for admin purposes only</inlineHelpText>
    <label>Wrike Folder ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/fields/Wrike_Integration_Messages__c.field-meta.xml
<CustomField>
    <fullName>Wrike_Integration_Messages__c</fullName>
    <description>This field is used to store the responses of callouts made to Wrike related to this Event. Not be used by any user in SFDC. Strictly for admin purposes only</description>
    <inlineHelpText>This field is used to store the responses of callouts made to Wrike related to this Event. Not be used by any user in SFDC. Strictly for admin purposes only</inlineHelpText>
    <label>Wrike Integration Messages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/fields/Wrike_Project_ID__c.field-meta.xml
<CustomField>
    <fullName>Wrike_Project_ID__c</fullName>
    <description>This field is used to store the ID of the project created in Wrike to store tasks related to this Event. Not be used by any user in SFDC. Strictly for admin purposes only</description>
    <inlineHelpText>This field is used to store the ID of the project created in Wrike to store tasks related to this Event. Not be used by any user in SFDC. Strictly for admin purposes only</inlineHelpText>
    <label>Wrike Project ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/GT_Wrike_Integration_Setting__c/GT_Wrike_Integration_Setting__c.object-meta.xml
<CustomObject>
    <description>ThisObject will be used to integrate with Wrike for Corporate Accounts. Please contact Catie Brosig or Rahul Sinha for more details on the usage of this metadata type</description>
    <label>Wrike Integration Setting</label>
    <nameField>
        <label>Event Record Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wrike Integration Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Wrike_Integration_Setting__c/fields/Authorization_Key__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Key__c</fullName>
    <defaultValue>&quot;Authorization&quot;</defaultValue>
    <description>Type Of Authorization to connect to Wrike</description>
    <inlineHelpText>Type Of Authorization to connect to Wrike</inlineHelpText>
    <label>Authorization Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GT_Wrike_Integration_Setting__c/fields/Event_Record_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>Event_Record_Type_ID__c</fullName>
    <description>This field contains the recordtypeID of the Corp Event for a customer. Please be careful while entering this field.</description>
    <inlineHelpText>This field contains the recordtypeID of the Corp Event for a customer. Please be careful while entering this field.</inlineHelpText>
    <label>Event Record Type ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/GT_Wrike_Integration_Setting__c/fields/Folder_Map__c.field-meta.xml
<CustomField>
    <fullName>Folder_Map__c</fullName>
    <description>This field will keep the folder names mapped to their IDs. It will be a json string of an Object having a Map of List&lt;string, string&gt; and data would be in format =&gt;Folder_Name, WrikeID</description>
    <inlineHelpText>This field will keep the folder names mapped to their IDs. It will be a json string of an Object having a Map of List&lt;string, string&gt; and data would be in format =&gt;Folder_Name, WrikeID</inlineHelpText>
    <label>Folder Map</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GT_Wrike_Integration_Setting__c/fields/Permanent_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Access_Token__c</fullName>
    <defaultValue>&quot;Bearer eyJ0dCI6InAiLCJhbGciOiJIUzI1NiIsInR2IjoiMSJ9.eyJkIjoie1wiYVwiOjE5ODIzMjEsXCJpXCI6NjUwNzY5OCxcImNcIjo0NjEzMzk3LFwidVwiOjY0OTkyNTcsXCJyXCI6XCJVU1wiLFwic1wiOltcIldcIixcIkZcIixcIklcIixcIlVcIixcIktcIixcIkNcIixcIkFcIixcIkxcIl0sXCJ6XCI6W10sXCJ0XCI6MH0iLCJpYXQiOjE1NjY5ODkyMDN9.lZZ5RHTfvHs3q1mnQn2t6wy2-3mVrPW8QuHf-bciujc&quot;</defaultValue>
    <description>This field holds the value of Access Token Generated in Wrike For SFDC</description>
    <inlineHelpText>This field holds the value of Access Token Generated in Wrike For SFDC</inlineHelpText>
    <label>Permanent Access Token</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GT_Wrike_Integration_Setting__c/fields/Project_Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_Template_ID__c</fullName>
    <defaultValue>&quot;IEAB4P3RI4L266YF&quot;</defaultValue>
    <description>This field contains the ID of the project which is used as a template to create tasks.</description>
    <inlineHelpText>This field contains the ID of the project which is used as a template to create tasks.</inlineHelpText>
    <label>Project Template ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GT_Wrike_Integration_Setting__c/fields/Wrike_Space_Id__c.field-meta.xml
<CustomField>
    <fullName>Wrike_Space_Id__c</fullName>
    <description>Used to Store the ID of the space created uniquely for this record type/customer in Wrike</description>
    <inlineHelpText>Used to Store the ID of the space created uniquely for this record type/customer in Wrike</inlineHelpText>
    <label>Wrike Space Id</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/GT_WrikeHandler.cls
/**
* The class contains the methods used to create Tasks in Wrike after an Event is Created in SFDC
*
* @author  Rahul Sinha
* @version 1.0
* @since   09-10-2019
*/

/* using without sharing so that the class can be called appropriately*/
public without sharing class GT_WrikeHandler{
    public enum TaskType {Backlog, Milestone, Planned}
    //the overall method of creating tasks in wrike
    @future (callout=true)
    public static void createTaskInWrike(set<Id> createdEventIds){
        List<GT_Event__c> createdEventList=[SELECT id, name, RecordTypeId, Event_Start_Date__c,Event_End_Date__c,Congress_Start_Date__c,Congress_End_Date__c,Event_Acronym__c,Congress_Acronym__c,Wrike_Folder_ID__c,Wrike_Project_ID__c,Wrike_Integration_Messages__c FROM GT_Event__c WHERE id IN :createdEventIds];
        for(GT_Event__c createdEvent:createdEventList){
            string parentFolderId=null;
            string eventFolderId=null;
            string eventProjectId=null;
            map<string,string> parentFolderMap=null;
            try{
                //1. get parent year folder in the wrike space
                string year= (createdEvent.Event_Start_Date__c!=null)?string.valueOf(createdEvent.Event_Start_Date__c.year()):string.valueOf(createdEvent.Congress_Start_Date__c.year());
                parentFolderMap= GT_WrikeApiMethods.getParentFolderIdInSpace(createdEvent.RecordTypeId,year,createdEvent.id);
                parentFolderId = (parentFolderMap!=null)?parentFolderMap.get(year):null;
                
                //2. create the subfolder for the Event in the Parent Folder
                List<GT_Wrike_Integration_Setting__c>relevantWrikeSetting=[SELECT id, authorization_key__c,permanent_access_token__c, event_record_type_id__c,folder_map__c,wrike_space_id__c,Project_Template_ID__c FROM  GT_Wrike_Integration_Setting__c WHERE event_record_type_id__c=:createdEvent.RecordTypeId];
                if(relevantWrikeSetting.size()>0){
                    map<string,string> tempFolderMap= new map<string,string>();
                    string tempAcronym= string.isNotBlank(createdEvent.Event_Acronym__c)?createdEvent.Event_Acronym__c:createdEvent.Congress_Acronym__c;
                    tempAcronym+=year;
                    if(string.isNotBlank(createdEvent.Wrike_Folder_ID__c)){
                        eventFolderId=createdEvent.Wrike_Folder_ID__c;
                        system.debug('Wrike Folder exists==='+eventFolderId);
                    }else{
                        eventFolderId= GT_WrikeApiMethods.createYearFolderInSpace(parentFolderId, EncodingUtil.urlEncode(tempAcronym, 'UTF-8'), tempFolderMap,relevantWrikeSetting.get(0).authorization_key__c,relevantWrikeSetting.get(0).permanent_access_token__c,null,createdEvent.id);
                        createdEvent.Wrike_Folder_ID__c=eventFolderId;
                        system.debug('Wrike Folder Created==='+eventFolderId);
                    }
                    
                    //3. Copy Template project in the folder created in the previous step
                    
                    if(string.isNotBlank(createdEvent.Wrike_Project_ID__c)){
                        eventProjectId=createdEvent.Wrike_Project_ID__c;
                    }else{
                        string rescheduleDateStr=(createdEvent.Event_Start_Date__c!=null)?getFormattedDate(createdEvent.Event_Start_Date__c -182):getFormattedDate(createdEvent.Congress_Start_Date__c-182);
                        eventProjectId=GT_WrikeApiMethods.copyTemplateProject(relevantWrikeSetting.get(0).Project_Template_ID__c,eventFolderId,EncodingUtil.urlEncode(tempAcronym+' Tasks', 'UTF-8'),EncodingUtil.urlEncode(rescheduleDateStr, 'UTF-8'),relevantWrikeSetting.get(0).authorization_key__c,relevantWrikeSetting.get(0).permanent_access_token__c,createdEvent.id);
                        createdEvent.Wrike_Project_ID__c=eventProjectId;
                    }
                    
                    //4. Get the later scheduled tasks in the project created above
                    set<string> taskTitles= new set<string>();
                    taskTitles.add('SHOW CLOSE');
                    taskTitles.add('Score Cards to client');
                    taskTitles.add('Final invoice and Variance Report to Exhibit Lead');
                    taskTitles.add('Client to provide payment to GES');
                    List<GT_WrikeTaskQueryResponse.Data> neededTasks=GT_WrikeApiMethods.getAllTasksInFolder(eventProjectId,taskTitles,relevantWrikeSetting.get(0).authorization_key__c,relevantWrikeSetting.get(0).permanent_access_token__c,createdEvent.id);

                    //5. Correct the dates of the tasks recievved from the previous step
                    for(GT_WrikeTaskQueryResponse.Data singleTask:neededTasks){
                        GT_WrikeApiObject.TaskDatesObj dates=new GT_WrikeApiObject.TaskDatesObj();
                        dates.type='Planned';
                        dates.duration=1;
                        string planDateStr='';
                        if(singleTask.title.containsIgnoreCase('SHOW CLOSE')){
                            planDateStr=(createdEvent.Event_End_Date__c!=null)?getFormattedDate(createdEvent.Event_End_Date__c):getFormattedDate(createdEvent.Congress_End_Date__c);                      
                        }
                        if(singleTask.title.containsIgnoreCase('Score Cards')){
                            planDateStr=(createdEvent.Event_End_Date__c!=null)?getFormattedDate(createdEvent.Event_End_Date__c+10):getFormattedDate(createdEvent.Congress_End_Date__c+10);
                        }
                        if(singleTask.title.containsIgnoreCase('Final invoice')){
                            planDateStr=(createdEvent.Event_End_Date__c!=null)?getFormattedDate(createdEvent.Event_End_Date__c+60):getFormattedDate(createdEvent.Congress_End_Date__c+60);                               
                        }
                        if(singleTask.title.containsIgnoreCase('Client to provide')){
                            planDateStr=(createdEvent.Event_End_Date__c!=null)?getFormattedDate(createdEvent.Event_End_Date__c+90):getFormattedDate(createdEvent.Congress_End_Date__c+90);                           
                        }
                        dates.start=planDateStr;
                        dates.due=planDateStr;
                        string modParams= json.serialize(dates);
                        //call api to modify the task
                        GT_WrikeApiMethods.modifyTask(singleTask.id,modParams,relevantWrikeSetting.get(0).authorization_key__c,relevantWrikeSetting.get(0).permanent_access_token__c,createdEvent.id);
                    }
                    
                    //6. update record with details of wrike folder and project IDs
                    database.update(createdEvent,false);
                    GT_WrikeApiObject.FolderMapObj tempFolderMapObj= new GT_WrikeApiObject.FolderMapObj();
                    tempFolderMapObj.folderMap=parentFolderMap;
                    relevantWrikeSetting.get(0).folder_map__c=json.serialize(tempFolderMapObj);
                    database.update(relevantWrikeSetting,false);
                }else{
                    system.debug('No wrike settings found for this record type: '+createdEvent.RecordTypeId);
                }               
            }catch(exception e){
                system.debug(e.getStackTraceString()+' gave bad response==='+e.getMessage());
                createdEvent.Wrike_Integration_Messages__c=e.getStackTraceString()+' gave bad response==='+e.getMessage();
                Database.DMLOptions dml = new Database.DMLOptions();
                dml.allowFieldTruncation = true;
                dml.optAllOrNone = false;
                database.update(createdEvent,dml);
            }
        }
    }
    
    //get date as a 'yyyy-MM-dd' string
    public static string getFormattedDate(date needToBeConvertedDate){
        string resultDateString=string.valueOf(needToBeConvertedDate.year())+'-';
        resultDateString+=  (needToBeConvertedDate.month()>=10)?string.valueOf(needToBeConvertedDate.month())+'-':'0'+string.valueOf(needToBeConvertedDate.month())+'-';
        resultDateString+=  (needToBeConvertedDate.day()>=10)?string.valueOf(needToBeConvertedDate.day()):'0'+string.valueOf(needToBeConvertedDate.day());
        return resultDateString;
    }
}