unpackaged/main/default/objects/Account/recordTypes/Exhibitor.recordType-meta.xml
<RecordType>
    <fullName>Exhibitor</fullName>
    <active>true</active>
    <description>E&amp;D Exhibitor Accounts</description>
    <label>Exhibitor</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>EAC</fullName>
            </value>
            <value>
                <fullName>Exhibitor</fullName>
            </value>
            <value>
                <fullName>GES</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>Stand Contractor</fullName>
            </value>
            <value>
                <fullName>Organiser</fullName>
            </value>
            <value>
                <fullName>Service Partner (GES)</fullName>
            </value>
            <value>
                <fullName>Show Management</fullName>
            </value>
            <value>
                <fullName>Non-Tradeshow</fullName>
            </value>
            <value>
                <fullName>SMS Message</fullName>
            </value>
            <value>
                <fullName>SMS Message - Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Show_Status__c.field-meta.xml
<CustomField>
    <fullName>Show_Status__c</fullName>
    <label>Show Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-Pre</fullName>
            </value>
            <value>
                <fullName>2-Showsite</fullName>
            </value>
            <value>
                <fullName>3-Post</fullName>
            </value>
            <value>
                <fullName>4-Non Tradeshow-N/A</fullName>
            </value>
            <value>
                <fullName>Pre-show</fullName>
            </value>
            <value>
                <fullName>Showsite (Build)</fullName>
            </value>
            <value>
                <fullName>Show Open</fullName>
            </value>
            <value>
                <fullName>Showsite (Breakdown)</fullName>
            </value>
            <value>
                <fullName>Post-show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/deleteSpamCasesTest.cls
@isTest 
public class deleteSpamCasesTest{ 
    
    static testmethod void executeTest()
    { 
        
        Account a  = new Account();
        a.Name = 'test Acc';
        insert a;
        
        Contact cont = new Contact();
        cont.FirstName = 'xyzFirst';
        cont.LastName = 'XyZLast';
        cont.AccountId = a.Id;
        cont.Email = 'xyzmail@mail.com';
        insert cont;
        
        User u = new user();
        u.LastName = 'Test Code';
        u.Email = 'test@test.com';
        u.Alias = 'Tcode';
        u.Username = 'test231411234444@tasd1511a131est.com';
        u.CommunityNickname = 'test12';
        u.LocaleSidKey = 'en_US';
        u.TimeZoneSidKey = 'GMT';
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        u.ProfileID = profileId.Id;
        u.LanguageLocaleKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        insert u;
        
        Case c = new Case();
        c.AccountId = a.id;
        c.ContactId = cont.Id;
        c.Customer_Type__c = 'Exhibitor';
        c.Show_Status__c = 'Showsite (Build)';
        c.Type = 'Audio-Visual';
        c.Reason__c = 'New Order';
        c.Priority = 'Low Priority';
        c.Status = 'Open';
        insert c; 
        
        Test.startTest(); 
        deleteSpamCases  obj= new deleteSpamCases();
        Database.executeBatch( obj );
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, obj  );
        Test.stopTest();
        
        system.assertNotEquals(c, null ,'Case Record is Null');
        
        Database.delete(c);
    } 
}