unpackaged/main/default/objects/Account/recordTypes/Exhibitor.recordType-meta.xml
<RecordType>
    <fullName>Exhibitor</fullName>
    <active>true</active>
    <description>E&amp;D Exhibitor Accounts</description>
    <label>Exhibitor</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to contact, filter on the account so we only show related contacts in the search</description>
    <inlineHelpText>Please search for the relevant contact</inlineHelpText>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <infoMessage>Please select the correct contact</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact)</relationshipLabel>
    <relationshipName>OpportunitiesContact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Show_Occurrence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Corporate Accounts &amp; AV Projects</relationshipLabel>
    <relationshipName>Show_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/Oracle_Show_Booth__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booths from Oracle</description>
    <label>Booth</label>
    <nameField>
        <label>Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booths</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booths</relationshipLabel>
    <relationshipName>Oracle_Show_Booths</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/Show_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Show_Occurrence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Show Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booths</relationshipLabel>
    <relationshipName>Oracle_Show_Booths</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/Oracle_Show_Booth_Contact__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booth Contacts from Oracle</description>
    <label>Booth Contact</label>
    <nameField>
        <displayFormat>BC-{000000000}</displayFormat>
        <label>Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booth Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship field to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Booth_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/Oracle_Show_Booth__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Show_Booth__c</fullName>
    <description>Master Detail relationship to parent Booth</description>
    <label>Booth</label>
    <referenceTo>Oracle_Show_Booth__c</referenceTo>
    <relationshipLabel>Booth Contacts</relationshipLabel>
    <relationshipName>Booth_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account Name.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shows (Account)</relationshipLabel>
    <relationshipName>Shows2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CCPageRedirect.cls
public with sharing class CCPageRedirect {
	
	public PageReference redirectToPage() {
		
		String sObjectType = ApexPages.currentPage().getParameters().get('Object');
		String RecordId = ApexPages.currentPage().getParameters().get('Id');
		String IsConsole = ApexPages.currentPage().getParameters().get('IsConsole');
		String RetUrl = ApexPages.currentPage().getParameters().get('RetUrl');
		String URL = null;
		
		if (sObjectType.toUpperCase() == 'ACCOUNT') {
			
			Account A = [Select Id, Name From Account Where Id = :RecordId];
			
			URL = '/500/e?cas4=' + EncodingUtil.urlEncode(A.Name, 'UTF-8') + 
				'&cas4_lkid=' + A.Id + '&00N40000002SoBd=Exhibitor';
				
			if (IsConsole.toUpperCase() == 'YES') {
				URL += '&isdtp=vw&retURL=%2F500%2Fo'; 
			} 
			else 
			{ 
				URL += '&retURL='+RetUrl; 
			}	
		}		
		else if (sObjectType.toUpperCase() == 'CONTACT') {
			
			Contact C = [Select Id, Name, Account.Id, Account.Name From Contact Where Id = :RecordId];
			
			URL = '/500/e?cas4=' + EncodingUtil.urlEncode(C.Account.Name, 'UTF-8') + 
				'&cas4_lkid=' + C.Account.Id + '&cas3=' + EncodingUtil.urlEncode(C.Name, 'UTF-8') + 
				'&cas3_lkid=' + C.Id + '&00N40000002SoBc=' + EncodingUtil.urlEncode(C.Account.Name, 'UTF-8') + 
				'&00N40000002SoBd=Exhibitor';
				
			if (IsConsole.toUpperCase() == 'YES') {
				URL += '&isdtp=vw&retURL=%2F500%2Fo'; 
			} 
			else 
			{ 
				URL += '&retURL='+RetUrl; 
			}	
		}
		else if (sObjectType.toUpperCase() == 'ORACLE_SHOW_BOOTH__C') {
		
			Oracle_Show_Booth__c B = [Select Id, Name, Show_Occurrence__c, Show_Occurrence__r.Name, Account__c, Account__r.Name From Oracle_Show_Booth__c Where Id = :RecordId];

			URL = '/500/e?cas4=' + EncodingUtil.urlEncode(B.Account__r.Name, 'UTF-8') +
				'&cas4_lkid=' + B.Account__c + '&CF00N40000002SoBY=' + EncodingUtil.urlEncode(B.Name, 'UTF-8') + 
				'&CF00N40000002SoBY_lkid=' + B.Id + '&CF00N40000002SoBx=' + EncodingUtil.urlEncode(B.Show_Occurrence__r.Name, 'UTF-8') + 
				'&CF00N40000002SoBx_lkid=' + B.Show_Occurrence__c + '&00N40000002SoBd=Exhibitor';
				
			if (IsConsole.toUpperCase() == 'YES') {
				URL += '&isdtp=vw&retURL=%2F500%2Fo'; 
			} 
			else 
			{ 
				URL += '&retURL='+RetUrl; 
			}			
		}
		else if (sObjectType.toUpperCase() == 'ORACLE_SHOW_BOOTH_CONTACT__C') {
		
			Oracle_Show_Booth_Contact__c BC = [Select Id, Oracle_Show_Booth__c, Contact__c, Contact__r.Name, Oracle_Show_Booth__r.Name, Oracle_Show_Booth__r.Account__r.Id, Oracle_Show_Booth__r.Account__r.Name, Oracle_Show_Booth__r.Show_Occurrence__r.Id, Oracle_Show_Booth__r.Show_Occurrence__r.Name From Oracle_Show_Booth_Contact__c Where Id = :RecordId];

			String AccountId = EncodingUtil.urlEncode(BC.Oracle_Show_Booth__r.Account__c, 'UTF-8'); 
			String AccountName = EncodingUtil.urlEncode(BC.Oracle_Show_Booth__r.Account__r.Name, 'UTF-8'); 
			String BoothId = EncodingUtil.urlEncode(BC.Oracle_Show_Booth__c, 'UTF-8'); 
			String BoothName = EncodingUtil.urlEncode(BC.Oracle_Show_Booth__r.Name, 'UTF-8');
			String OptyId = EncodingUtil.urlEncode(BC.Oracle_Show_Booth__r.Show_Occurrence__c, 'UTF-8');
			String OptyName = EncodingUtil.urlEncode(BC.Oracle_Show_Booth__r.Show_Occurrence__r.Name, 'UTF-8');

			URL = '/500/e?cas4=' + AccountName + '&cas4_lkid=' + AccountId + 
				'&CF00N40000002SoBY=' + BoothName + '&CF00N40000002SoBY_lkid=' + BoothId + 
				'&CF00N40000002SoBx=' + OptyName + '&CF00N40000002SoBx_lkid=' + OptyId + 
				'&00N40000002SoBd=Exhibitor'; 

			if (IsConsole.toUpperCase() == 'YES') {
				URL += '&isdtp=vw&retURL=%2F500%2Fo'; 
			} 
			else 
			{ 
				URL += '&retURL='+RetUrl; 
			}
			
		}		
		else if (sObjectType.toUpperCase() == 'OPPORTUNITY') {
			
			Opportunity O = [Select Id, Name, Show_Name__c, Show_Name__r.Name From Opportunity Where Id = :RecordId];
						
			URL = '/500/e?CF00N40000002SoBx=' + EncodingUtil.urlEncode(O.Name, 'UTF-8') + 
				'&CF00N40000002SoBx_lkid=' + O.Id;
			
			if (O.Show_Name__c != null && O.Show_Name__r != null)
			{
				URL += '&CF00N40000002SoBw=' + EncodingUtil.urlEncode(O.Show_Name__r.Name, 'UTF-8');
				URL += '&CF00N40000002SoBw_lkid=' + EncodingUtil.urlEncode(O.Show_Name__c, 'UTF-8');
			}
			
			URL += '&00N40000002SoBd=Exhibitor';
			
			if (IsConsole.toUpperCase() == 'YES') {			
				URL += '&isdtp=vw&retURL=%2F500%2Fo';
			} 
			else 
			{ 
				URL += '&retURL='+RetUrl; 
			}			
		}
		
		return  new PageReference(URL);
	}
}