unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Firm.recordType-meta.xml
<RecordType>
    <fullName>Firm</fullName>
    <active>true</active>
    <description>A Management Company, Sponsor, Contractor (Prime and Sub), and Competitor related to Shows and Show Occurrences.</description>
    <label>Firm</label>
</RecordType>

unpackaged/main/default/objects/AR_Adjustments__c/AR_Adjustments__c.object-meta.xml
<CustomObject>
    <label>AR Adjustments</label>
    <nameField>
        <displayFormat>ARA-{0000}</displayFormat>
        <label>AR_Adjustments_No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR1_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Email__c</fullName>
    <label>AR1 Approver Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR1_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments7</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR2_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver_Email__c</fullName>
    <label>AR2 Approver Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR2_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments8</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR_Adj_CSI_ID__c.field-meta.xml
<CustomField>
    <fullName>AR_Adj_CSI_ID__c</fullName>
    <description>AR_Adj_CSI_ID</description>
    <label>CSI ICS</label>
    <referenceTo>Customer_Service_Inquiries_ICS__c</referenceTo>
    <relationshipName>AR_Adjustments_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/CSO_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>AR Adjustments (CSO Approver Name)</relationshipLabel>
    <relationshipName>AR_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/DAM_Approver_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>DAM_Approver_Email_ID__c</fullName>
    <label>DAM Approver Email ID</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/DAM_LOB_Approver__c.field-meta.xml
<CustomField>
    <fullName>DAM_LOB_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DAM/LOB Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/F_A_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>F_A_Approver_Email__c</fullName>
    <label>F&amp;A Approver Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/F_R_Approver__c.field-meta.xml
<CustomField>
    <fullName>F_R_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>F&amp;R Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments6</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ICS_Location_City</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/Customer_Service_Inquiries_ICS__c.object-meta.xml
<CustomObject>
    <label>ICS Cases</label>
    <nameField>
        <displayFormat>ICS {000000}</displayFormat>
        <label>CSI ICS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICS Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>IF(ISBLANK(TEXT(Opportunity_Name__r.Production_Location__c)),Opportunity_Name__r.EE_Production_Location__c, TEXT(Opportunity_Name__r.Production_Location__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Show Occurrence</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Customer_Service_Inquiries_ICS</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E&amp;E (Trade Show)</fullName>
                <default>true</default>
                <label>E&amp;E (Trade Show)</label>
            </value>
            <value>
                <fullName>E&amp;E Logistics (Trade Show)</fullName>
            </value>
            <value>
                <fullName>E&amp;E(GBMS)</fullName>
            </value>
            <value>
                <fullName>Revenue Exhibitor</fullName>
            </value>
            <value>
                <fullName>Revenue Logistics</fullName>
            </value>
            <value>
                <fullName>Revenue Show Org</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Revenue Trade Show &amp; Logistics</fullName>
                <isActive>false</isActive>
                <label>Revenue Trade Show &amp; Logistics</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <description>Employees  object stored information about gesemployee email address</description>
    <label>Employees</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/ICS_Approver_Matrix__c.object-meta.xml
<CustomObject>
    <label>ICS Approver Matrix</label>
    <nameField>
        <displayFormat>ICS_AM-{00000}</displayFormat>
        <label>ICS Approver Matrix N0</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICS Approver Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Additional_Approver__c.field-meta.xml
<CustomField>
    <fullName>Additional_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (Additional Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/AR1_Approver__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (AR1 Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/AR2_Approver__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (AR2 Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/CSO_Approver__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (CSO Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/F_R_Approver__c.field-meta.xml
<CustomField>
    <fullName>F_R_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>F&amp;R Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (F&amp;R Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/LOB_Approver__c.field-meta.xml
<CustomField>
    <fullName>LOB_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOB Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ICS_Location_City</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Max_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Amount__c</fullName>
    <label>Max - Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Min_Amount__c.field-meta.xml
<CustomField>
    <fullName>Min_Amount__c</fullName>
    <label>Min - Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E&amp;E (Trade Show)</fullName>
            </value>
            <value>
                <fullName>E&amp;E Logistics (Trade Show)</fullName>
            </value>
            <value>
                <fullName>E&amp;E(GBMS)</fullName>
            </value>
            <value>
                <fullName>Revenue Exhibitor</fullName>
            </value>
            <value>
                <fullName>Revenue Logistics</fullName>
            </value>
            <value>
                <fullName>Revenue Show Org</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Revenue Trade Show &amp; Logistics</fullName>
                <isActive>false</isActive>
                <label>Revenue Trade Show &amp; Logistics</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Transaction_Types__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Types__c</fullName>
    <label>Transaction Types</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AR Adjustments</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>Credit Memo</fullName>
            </value>
            <value>
                <fullName>Payment Transfer</fullName>
            </value>
            <value>
                <fullName>Receipt Reversals</fullName>
            </value>
            <value>
                <fullName>Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ICS_AR_Adjustments_Approver_Update_TEST.cls
@istest
public class ICS_AR_Adjustments_Approver_Update_TEST {
    static Account facility=TestDataUtil.CreateTestFacility();
    static Account firm=TestDataUtil.CreateTestFirm();
    static Show__c show=TestDataUtil.CreateTestShow(firm.id);
    static List<AR_Adjustments__c> testdata=new List<AR_Adjustments__c>();
    static AR_Adjustments__c sample=new AR_Adjustments__c();

    @istest 
    public static void test1(){
        ICS_Approver_Matrix__c cr=new ICS_Approver_Matrix__c();
        Employees__c e=new Employees__c();
        e.name='sample';
        e.Email_Address__c='sample@sample.com';
        insert e;
        Employees__c e1=new Employees__c();
        e1.name='sample1';
        e1.Email_Address__c='sample1@sample.com';
        insert e1;
        Customer_Service_Inquiries_ICS__c test1=new Customer_Service_Inquiries_ICS__c();
        test1.Sales_Channel__c ='Revenue Show Org';
        //test1.Customer_Name__c='test';
        test1.Opportunity_Name__c=TestDataUtil.CreateTestSalesRepOpp(facility.id,firm.id,show.id).id;
        insert test1;
        cr.Min_Amount__c=null;
        cr.Max_Amount__c=5000;
        cr.LOB_Approver__c=e1.id;
        cr.F_R_Approver__c=e.Id;
        cr.AR1_Approver__c=e1.id;
		cr.CSO_Approver__c=e1.id;
        cr.AR2_Approver__c=e.id;
        cr.Additional_Approver__c=e.id;
        cr.Transaction_Types__c='AR Adjustments';
        cr.Location__c='110- Las Vegas';
        cr.sales_channel__c='Revenue Show Org';
        insert cr;
        sample.AR_Adj_CSI_ID__c=test1.id;
        
        sample.Amount__c=1000;
        testdata.add(sample);
        insert testdata;
        list<AR_Adjustments__c> res_ar=[select  DAM_LOB_Approver__c,DAM_Approver_Email_ID__c, F_R_Approver__c,F_A_Approver_Email__c,
                                        AR1_Approver_Name__c, AR1_Approver_Email__c,	CSO_Approver_Name__c, cso_Approver_Email__c,     
                                        AR2_Approver_Name__c,AR2_Approver_Email__c from AR_Adjustments__c where id in:testdata];
        
    }
    @istest
    public static void test2(){
        ICS_Approver_Matrix__c cr=new ICS_Approver_Matrix__c();
        Employees__c e=new Employees__c();
        e.name='sample';
        e.Email_Address__c='sample@sample.com';
        insert e;
        Employees__c e1=new Employees__c();
        e1.name='sample1';
        e1.Email_Address__c='sample1@sample.com';
        insert e1;
        Customer_Service_Inquiries_ICS__c test1=new Customer_Service_Inquiries_ICS__c();
        test1.Sales_Channel__c ='Revenue Show Org';
        //test1.Customer_Name__c='test';
        test1.Opportunity_Name__c=TestDataUtil.CreateTestSalesRepOpp(facility.id,firm.id,show.id).id;
        insert test1;
        cr.Min_Amount__c=5000;
        cr.Max_Amount__c=null;
        cr.LOB_Approver__c=e1.id;
        cr.F_R_Approver__c=e.Id;
        cr.AR1_Approver__c=e1.id;
		cr.CSO_Approver__c=e1.id;
        cr.AR2_Approver__c=e.id;
        cr.Additional_Approver__c=e.id;
        cr.Transaction_Types__c='AR Adjustments';
        cr.Location__c='110- Las Vegas';
        cr.sales_channel__c='Revenue Show Org';
        insert cr;
        sample.AR_Adj_CSI_ID__c=test1.id;
        sample.Amount__c=6000;
        testdata.add(sample);
        insert testdata;
        list<AR_Adjustments__c> res_ar=[select  DAM_LOB_Approver__c,DAM_Approver_Email_ID__c, F_R_Approver__c,F_A_Approver_Email__c,
                                        AR1_Approver_Name__c, AR1_Approver_Email__c,	CSO_Approver_Name__c, cso_Approver_Email__c,     
                                        AR2_Approver_Name__c,AR2_Approver_Email__c from AR_Adjustments__c where id in:testdata];
        
    }

}