unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility_Address__c.field-meta.xml
<CustomField>
    <fullName>Facility_Address__c</fullName>
    <description>Displays location of the facility</description>
    <label>Facility Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility_lk__c.field-meta.xml
<CustomField>
    <fullName>Facility_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Connect2_Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/LC_ShowDetailsApex.cls
// The class is without sharing to override the difficulties in getting facility name
public without sharing class LC_ShowDetailsApex {

    // method to get the show details to display on each page in community.
    @AuraEnabled
    public static GC_Connect2_Show__c showDetils(string showId,String jobNo){
        GC_Connect2_Show__c shw=new GC_Connect2_Show__c();
        if(String.isNotBlank(showId)&&String.isBlank(jobNo))
        {
           shw=[SELECT Id,Show_Name__c,Show_Start_Date__c,Show_End_Date__c,Facility_lk__r.Name FROM  GC_Connect2_Show__c WHERE Id=:showId]; 
        }
        if(String.isNotBlank(jobNo)&&String.isBlank(showId)){
            shw=[SELECT Id,Show_Name__c,Show_Start_Date__c,Show_End_Date__c, Facility_lk__r.Name FROM  GC_Connect2_Show__c WHERE Job_Number__c=:jobNo];
        }
        if((String.isNotBlank(jobNo))&&(String.isNotBlank(showId))){
            shw=[SELECT Id,Show_Name__c,Show_Start_Date__c,Show_End_Date__c, Facility_lk__r.Name FROM  GC_Connect2_Show__c WHERE Id=:showId AND Job_Number__c=:jobNo];
        }
        if((jobNo == 'undefined')&&(String.isNotBlank(showId))){
            shw=[SELECT Id,Show_Name__c,Show_Start_Date__c,Show_End_Date__c, Facility_lk__r.Name FROM  GC_Connect2_Show__c WHERE Id=:showId];
        }
      
        return shw;
        
    }
    
    // method to get the user details for welcome page
    @AuraEnabled 
    public static user fetchUser(){
       User currentUser = [SELECT Id,FirstName FROM User WHERE Id =: userInfo.getUserId()];
        return currentUser;
    }
      @AuraEnabled
    public static string getShows(string ShowsId) {
    GC_Connect2_Show__c shows =new GC_Connect2_Show__c();
     shows=[SELECT Id, Name, Job_Number__c,Facility_Address__c  FROM GC_Connect2_Show__c WHERE Id =:ShowsId];
        return shows.Job_Number__c;
    } 
      
    
}