unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>A physical location where a Show will occur.</description>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Firm.recordType-meta.xml
<RecordType>
    <fullName>Firm</fullName>
    <active>true</active>
    <description>A Management Company, Sponsor, Contractor (Prime and Sub), and Competitor related to Shows and Show Occurrences.</description>
    <label>Firm</label>
</RecordType>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/Customer_Service_Inquiries_ICS__c.object-meta.xml
<CustomObject>
    <label>ICS Cases</label>
    <nameField>
        <displayFormat>ICS {000000}</displayFormat>
        <label>CSI ICS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICS Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Case_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Approval_Status__c</fullName>
    <label>Case Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Case Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Case Open</fullName>
                <default>true</default>
                <label>Case Open</label>
            </value>
            <value>
                <fullName>Requestor Submitted</fullName>
            </value>
            <value>
                <fullName>Requestor Approved</fullName>
            </value>
            <value>
                <fullName>Requestor Rejected</fullName>
            </value>
            <value>
                <fullName>LOB Open</fullName>
            </value>
            <value>
                <fullName>LOB Submitted</fullName>
            </value>
            <value>
                <fullName>LOB Approved</fullName>
            </value>
            <value>
                <fullName>LOB Rejected</fullName>
            </value>
            <value>
                <fullName>F&amp;R Open</fullName>
            </value>
            <value>
                <fullName>F&amp;R Submitted</fullName>
            </value>
            <value>
                <fullName>F&amp;R Approved</fullName>
            </value>
            <value>
                <fullName>F&amp;R Rejected</fullName>
            </value>
            <value>
                <fullName>AR1 Open</fullName>
            </value>
            <value>
                <fullName>AR1 Submitted</fullName>
            </value>
            <value>
                <fullName>AR1 Approved</fullName>
            </value>
            <value>
                <fullName>AR1 Rejected</fullName>
            </value>
            <value>
                <fullName>CSO Open</fullName>
            </value>
            <value>
                <fullName>CSO Submitted</fullName>
            </value>
            <value>
                <fullName>CSO Approved</fullName>
            </value>
            <value>
                <fullName>CSO Rejected</fullName>
            </value>
            <value>
                <fullName>AR2 Open</fullName>
            </value>
            <value>
                <fullName>AR2 Submitted</fullName>
            </value>
            <value>
                <fullName>AR2 Approved</fullName>
            </value>
            <value>
                <fullName>AR2 Rejected</fullName>
            </value>
            <value>
                <fullName>Additional Open</fullName>
            </value>
            <value>
                <fullName>Additional Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Case_Requestor_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_Requestor_Email_ID__c</fullName>
    <label>Case Requestor Email ID</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>IF(ISBLANK(TEXT(Opportunity_Name__r.Production_Location__c)),Opportunity_Name__r.EE_Production_Location__c, TEXT(Opportunity_Name__r.Production_Location__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Show Occurrence</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Customer_Service_Inquiries_ICS</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <description>Employees  object stored information about gesemployee email address</description>
    <label>Employees</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/ICS_Approver_Matrix__c.object-meta.xml
<CustomObject>
    <label>ICS Approver Matrix</label>
    <nameField>
        <displayFormat>ICS_AM-{00000}</displayFormat>
        <label>ICS Approver Matrix N0</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICS Approver Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Additional_Approver__c.field-meta.xml
<CustomField>
    <fullName>Additional_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (Additional Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/AR1_Approver__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (AR1 Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/AR2_Approver__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (AR2 Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/CSO_Approver__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (CSO Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ICS_Location_City</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Max_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Amount__c</fullName>
    <label>Max - Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Min_Amount__c.field-meta.xml
<CustomField>
    <fullName>Min_Amount__c</fullName>
    <label>Min - Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Transaction_Types__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Types__c</fullName>
    <label>Transaction Types</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AR Adjustments</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>Credit Memo</fullName>
            </value>
            <value>
                <fullName>Payment Transfer</fullName>
            </value>
            <value>
                <fullName>Receipt Reversals</fullName>
            </value>
            <value>
                <fullName>Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/Refunds_ICS__c.object-meta.xml
<CustomObject>
    <label>Refunds</label>
    <nameField>
        <displayFormat>Refunds-{00000}</displayFormat>
        <label>Refunds ICS No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Refunds_ICS__c/fields/AR1_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>Refunds_ICS1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/fields/AR2_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>Refunds_ICS2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/fields/CSI_ICS__c.field-meta.xml
<CustomField>
    <fullName>CSI_ICS__c</fullName>
    <label>CSI ICS</label>
    <referenceTo>Customer_Service_Inquiries_ICS__c</referenceTo>
    <relationshipName>Refunds_ICS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/fields/Last_4_of_CC__c.field-meta.xml
<CustomField>
    <fullName>Last_4_of_CC__c</fullName>
    <label>Last 4 # of CC</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/fields/Last_4_of_Token__c.field-meta.xml
<CustomField>
    <fullName>Last_4_of_Token__c</fullName>
    <label>Last 4 of Token #</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ICS_Refunds_Approver_UpdateTest.cls
@isTest
public class ICS_Refunds_Approver_UpdateTest {
     static Account facility=TestDataUtil.CreateTestFacility();
    static Account firm=TestDataUtil.CreateTestFirm();
    static Show__c show=TestDataUtil.CreateTestShow(firm.id);
     static List<Refunds_ICS__c> testdata=new List<Refunds_ICS__c>();
     static Refunds_ICS__c sample=new Refunds_ICS__c();
    
    
   		   @istest
  		  public static void test1(){        
   			ICS_Approver_Matrix__c AM=new ICS_Approver_Matrix__c();
            Employees__c e=new Employees__c();
            e.name='sample';
            e.Email_Address__c='sample@sample.com';
            insert e;
            Employees__c e1=new Employees__c();
            e1.name='sample1';
            e1.Email_Address__c='sample1@sample.com';
            insert e1;
            Customer_Service_Inquiries_ICS__c ICS1 = TestDataUtil.createTestCustomerServiceInquries();
            ICS1.Opportunity_Name__c=TestDataUtil.CreateTestSalesRepOpp(facility.id,firm.id,show.id).id;
            ICS1.Case_Approval_Status__c = 'Requestor Submitted';        
            ICS1.Case_Requestor_Email_ID__c='sample1@sample.com';
            insert ICS1;
            am.Min_Amount__c=1000;
            am.Max_Amount__c=10000;
            am.AR1_Approver__c=e1.id;
            am.AR2_Approver__c=e.id;
            am.CSO_Approver__c=e.id;      
            am.Additional_Approver__c=e.id;
            am.Transaction_Types__c='Refunds';
            am.Location__c='110- Las Vegas';
            insert am;
            Refunds_ICS__c i1 = new Refunds_ICS__c();
            i1.Amount__c=1500;
            i1.Last_4_of_CC__c='2000';	
            i1.Last_4_of_Token__c='3000';
            i1.AR1_Approver_Name__c =i1.Name;
            i1.CSI_ICS__c=ICS1.Id;
            i1.AR2_Approver_Name__c =i1.Name;     
            List<Refunds_ICS__c> RefundsList = new List<Refunds_ICS__c>();
            RefundsList.add(i1);
            insert RefundsList;
            ICS_Refunds_Approver_Update.Refunds_Approverdetails(RefundsList);                 
 	  	 }
     @istest
  		  public static void test2(){        
   			ICS_Approver_Matrix__c AM=new ICS_Approver_Matrix__c();
            Employees__c e=new Employees__c();
            e.name='sample';
            e.Email_Address__c='sample@sample.com';
            insert e;
            Employees__c e1=new Employees__c();
            e1.name='sample1';
            e1.Email_Address__c='sample1@sample.com';
            insert e1;
            Customer_Service_Inquiries_ICS__c ICS2 = TestDataUtil.createTestCustomerServiceInquries();
            ICS2.Opportunity_Name__c=TestDataUtil.CreateTestSalesRepOpp(facility.id,firm.id,show.id).id;
            ICS2.Case_Approval_Status__c = 'Requestor Submitted';        
            ICS2.Case_Requestor_Email_ID__c='sample1@sample.com';
            insert ICS2;
            am.Min_Amount__c=10001;
            am.AR1_Approver__c=e1.id;
            am.AR2_Approver__c=e.id;
            am.CSO_Approver__c=e.id;      
            am.Additional_Approver__c=e.id;
            am.Transaction_Types__c='Refunds';
            am.Location__c='110- Las Vegas';
            insert am;
            Refunds_ICS__c i1 = new Refunds_ICS__c();
            i1.Amount__c=100001;
            i1.Last_4_of_CC__c='2000';	
            i1.Last_4_of_Token__c='3000';
            i1.AR1_Approver_Name__c =i1.Name;
            i1.CSI_ICS__c=ICS2.Id;
            i1.AR2_Approver_Name__c =i1.Name;     
            List<Refunds_ICS__c> RefundsList = new List<Refunds_ICS__c>();
            RefundsList.add(i1);
            insert RefundsList;
            ICS_Refunds_Approver_Update.Refunds_Approverdetails(RefundsList);                 
 	  	 }
  }