unpackaged/main/default/objects/Account/recordTypes/Firm.recordType-meta.xml
<RecordType>
    <fullName>Firm</fullName>
    <active>true</active>
    <description>A Management Company, Sponsor, Contractor (Prime and Sub), and Competitor related to Shows and Show Occurrences.</description>
    <label>Firm</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Audio_Visual_Provider__c.field-meta.xml
<CustomField>
    <fullName>Audio_Visual_Provider__c</fullName>
    <inlineHelpText>Company providing AV services for this exhibition opportunity</inlineHelpText>
    <label>Audio Visual Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Absolute Productions</fullName>
            </value>
            <value>
                <fullName>Access Audio Visual</fullName>
            </value>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>AEE Productions</fullName>
            </value>
            <value>
                <fullName>Aesthetic Visual Solutions</fullName>
            </value>
            <value>
                <fullName>AG Light and Sound</fullName>
            </value>
            <value>
                <fullName>Alford Media</fullName>
            </value>
            <value>
                <fullName>Alliance AV</fullName>
            </value>
            <value>
                <fullName>Alliant</fullName>
            </value>
            <value>
                <fullName>American AV</fullName>
            </value>
            <value>
                <fullName>ASP Group</fullName>
            </value>
            <value>
                <fullName>Atlanta AV</fullName>
            </value>
            <value>
                <fullName>Audio Visual One</fullName>
            </value>
            <value>
                <fullName>Audio Visual One, Ltd.</fullName>
            </value>
            <value>
                <fullName>Audio Visual Technology Services (AVTS)</fullName>
            </value>
            <value>
                <fullName>AV-Canada</fullName>
            </value>
            <value>
                <fullName>AV Concepts</fullName>
            </value>
            <value>
                <fullName>AV Connections</fullName>
            </value>
            <value>
                <fullName>AV Experience</fullName>
            </value>
            <value>
                <fullName>AVI SPL</fullName>
            </value>
            <value>
                <fullName>AV Matters</fullName>
            </value>
            <value>
                <fullName>AVmedia</fullName>
            </value>
            <value>
                <fullName>AV Network</fullName>
            </value>
            <value>
                <fullName>AV Outsource</fullName>
            </value>
            <value>
                <fullName>AV Partners</fullName>
            </value>
            <value>
                <fullName>AVPG</fullName>
            </value>
            <value>
                <fullName>AV PRO</fullName>
            </value>
            <value>
                <fullName>AVPS - Audio Visual Production Services</fullName>
            </value>
            <value>
                <fullName>avts group</fullName>
            </value>
            <value>
                <fullName>Backstage Logic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Housing_Provider__c.field-meta.xml
<CustomField>
    <fullName>Housing_Provider__c</fullName>
    <inlineHelpText>Company providing Housing services for this exhibition opportunity</inlineHelpText>
    <label>Housing Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A111 Power of Conference Service</fullName>
            </value>
            <value>
                <fullName>AC Central Reservations</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Anthony Travel &amp; airbnb</fullName>
            </value>
            <value>
                <fullName>aRes Travel</fullName>
            </value>
            <value>
                <fullName>b-network</fullName>
            </value>
            <value>
                <fullName>CMR – Convention Management Resources</fullName>
            </value>
            <value>
                <fullName>Conference Direct</fullName>
            </value>
            <value>
                <fullName>Connections Housing</fullName>
            </value>
            <value>
                <fullName>Convention Housing Management (CHMrooms)</fullName>
            </value>
            <value>
                <fullName>Convention Housing Partners</fullName>
            </value>
            <value>
                <fullName>CVB</fullName>
            </value>
            <value>
                <fullName>Cvent</fullName>
            </value>
            <value>
                <fullName>Davis_Trapp</fullName>
                <label>Davis Trapp</label>
            </value>
            <value>
                <fullName>De Prez</fullName>
            </value>
            <value>
                <fullName>Events in Focus</fullName>
            </value>
            <value>
                <fullName>Eventsphere</fullName>
            </value>
            <value>
                <fullName>Expovision</fullName>
            </value>
            <value>
                <fullName>Express Travel</fullName>
            </value>
            <value>
                <fullName>Facility</fullName>
            </value>
            <value>
                <fullName>Fusion Marketing</fullName>
            </value>
            <value>
                <fullName>Globetrotter Travel Management Services</fullName>
            </value>
            <value>
                <fullName>Helms Brisco</fullName>
            </value>
            <value>
                <fullName>Hotel Direct</fullName>
            </value>
            <value>
                <fullName>Housing Connections</fullName>
            </value>
            <value>
                <fullName>ICS</fullName>
            </value>
            <value>
                <fullName>IMN</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>InSITE Selection Services</fullName>
            </value>
            <value>
                <fullName>J. Spargo &amp; Associates</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Registration_Provider__c.field-meta.xml
<CustomField>
    <fullName>Registration_Provider__c</fullName>
    <inlineHelpText>Company providing Registration services for this exhibition opportunity</inlineHelpText>
    <label>Registration Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>a2z</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>American Tradeshow</fullName>
            </value>
            <value>
                <fullName>An Ideal Partner</fullName>
            </value>
            <value>
                <fullName>ARI</fullName>
            </value>
            <value>
                <fullName>Avectra</fullName>
            </value>
            <value>
                <fullName>BADGEGuys</fullName>
            </value>
            <value>
                <fullName>Boomset</fullName>
            </value>
            <value>
                <fullName>CMI Resources</fullName>
            </value>
            <value>
                <fullName>CompuSystems (CSI)</fullName>
            </value>
            <value>
                <fullName>Conexysis</fullName>
            </value>
            <value>
                <fullName>Conference Direct</fullName>
            </value>
            <value>
                <fullName>Convention Data Services (CDS)</fullName>
            </value>
            <value>
                <fullName>Convention Management Resources</fullName>
            </value>
            <value>
                <fullName>CRG Events</fullName>
            </value>
            <value>
                <fullName>CTE</fullName>
            </value>
            <value>
                <fullName>CUNA</fullName>
            </value>
            <value>
                <fullName>Customreg.com</fullName>
            </value>
            <value>
                <fullName>Cvent</fullName>
            </value>
            <value>
                <fullName>Epic Registration Services</fullName>
            </value>
            <value>
                <fullName>eShow</fullName>
            </value>
            <value>
                <fullName>eTouches</fullName>
            </value>
            <value>
                <fullName>Event Ready</fullName>
            </value>
            <value>
                <fullName>Executive Events &amp; Management Company</fullName>
            </value>
            <value>
                <fullName>Experient</fullName>
            </value>
            <value>
                <fullName>Expologic</fullName>
            </value>
            <value>
                <fullName>Exposoft</fullName>
            </value>
            <value>
                <fullName>Expo Tracker, LLC</fullName>
            </value>
            <value>
                <fullName>Facility</fullName>
            </value>
            <value>
                <fullName>Freeman</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Close_Date__c</fullName>
    <inlineHelpText>Date exhibition floor closes; if show close date unknown, select last day of appropriate month</inlineHelpText>
    <label>Exhibition Close Date.</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date_Time__c</fullName>
    <description>Blitz field for Opportunity Integration</description>
    <inlineHelpText>For EMEA AV Use Only.</inlineHelpText>
    <label>Show End Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Show_Occurrence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Corporate Accounts &amp; AV Projects</relationshipLabel>
    <relationshipName>Show_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sync_with_Marketo__c.field-meta.xml
<CustomField>
    <fullName>Sync_with_Marketo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be checked if this record is to be synced with Marketo. We have custom workflow that sets this flag automatically upon creation if criteria are met. Historical records will be bulk updated</description>
    <inlineHelpText>Sync with Marketo?</inlineHelpText>
    <label>Sync with Marketo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/fields/AV_Not_Applicable__c.field-meta.xml
<CustomField>
    <fullName>AV_Not_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If client does not want or provide this service, check this box.</inlineHelpText>
    <label>AV Not Applicable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Housing_Not_Applicable__c.field-meta.xml
<CustomField>
    <fullName>Housing_Not_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If client does not want or provide this service, check this box.</inlineHelpText>
    <label>Housing Not Applicable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Housing_Provider__c.field-meta.xml
<CustomField>
    <fullName>Housing_Provider__c</fullName>
    <inlineHelpText>Housing provider from current YRMO opportunity.</inlineHelpText>
    <label>Housing Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Registration_Not_Applicable__c.field-meta.xml
<CustomField>
    <fullName>Registration_Not_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If client does not want or provide this service, check this box.</inlineHelpText>
    <label>Registration Not Applicable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Registration_Provider__c.field-meta.xml
<CustomField>
    <fullName>Registration_Provider__c</fullName>
    <inlineHelpText>Registration Provider from current YRMO Registration Opportunity.</inlineHelpText>
    <label>Registration Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Show_ID__c.field-meta.xml
<CustomField>
    <fullName>Show_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Legacy System Identifier.</inlineHelpText>
    <label>Show ID (LMS)</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Show__c/fields/Sync_with_Marketo__c.field-meta.xml
<CustomField>
    <fullName>Sync_with_Marketo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync with Marketo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/ShowLOBDetailsTest.cls
@isTest    
public class ShowLOBDetailsTest{
    
    static testMethod void MyTest1(){
        
        
        Account a = new Account();
        a.name = 'test account';
        a.recordTypeId = [select Id from RecordType where Name = 'Firm' and SobjectType = 'Account'].id;
        insert a;
        
        Test.startTest();
        Show__c s = new Show__c();
        s.Show_ID__c = 'abcdef';
        s.Registration_Not_Applicable__c = false;
        s.Housing_Not_Applicable__c = false;
        s.AV_Not_Applicable__c = false;
        s.Sync_with_Marketo__c = true;
        insert s;
        
        Opportunity o1 = new Opportunity();
        Opportunity o2 = new Opportunity();
        Opportunity o3 = new Opportunity();
        //Opportunity o4 = new Opportunity();
        Opportunity o5 = new Opportunity();
        Opportunity o6 = new Opportunity();
        //Opportunity o7 = new Opportunity();
        Opportunity o8 = new Opportunity();
        
        //Exh
        o2.name = 'test opp 2';
        o2.stagename = 'LO';
        o2.closedate = Date.today()+10;
        o2.Show_Name__c = s.id;
        o2.Show_Close_Date__c = Date.Today()+10;
        o2.Show_End_Date_Time__c = Date.Today()+15; 
        o2.RecordTypeId = [select Id from RecordType where Name = 'Master Show Occurrence' and SobjectType = 'Opportunity'].id;
        o2.amount = 20000;
        o2.Prime_Contractor__c = a.id;
        
        //Exh
        o6.name = 'test opp 6';
        o6.stagename = 'LO';
        o6.closedate = Date.today()+11;
        o6.Show_Name__c = s.id;
        o6.Show_Close_Date__c = Date.Today()+15;
        o6.Show_End_Date_Time__c = Date.Today()+15;
        o6.RecordTypeId = [select Id from RecordType where Name = 'EMEA - Exhibition' and SobjectType = 'Opportunity'].id; /* EMEA - Europe */
        o6.amount = 20000;
        o6.Prime_Contractor__c = a.id;
        
        List<Opportunity> opps = new List<Opportunity>();
        opps.add(o2);
        opps.add(o6);
        insert opps;
        
        //Hs
        o3.name = 'test opp 3';
        o3.stagename = 'CV';
        o3.closedate = Date.today()+15;
        o3.Show_Name__c = s.id;
        o3.Show_Close_Date__c = Date.Today()+15;
        o3.Housing_Provider__c = 'test provider 3';
        o3.Show_Occurrence__c = o2.id;
        o3.RecordTypeId = [select Id from RecordType where Name = 'EMEA - AV' and SobjectType = 'Opportunity'].id; /* EMEA – Housing */
        o3.amount = 30000;
        
        //Hs
        o8.name = 'test opp 8';
        o8.stagename = 'CV';
        o8.closedate = Date.today()+20;
        o8.Show_Name__c = s.id;
        o8.Show_Close_Date__c = Date.Today()+16;
        o8.Housing_Provider__c = 'test provider 8';
        o8.Show_Occurrence__c = o6.id;
        o8.RecordTypeId = [select Id from RecordType where Name = 'EMEA – Housing' and SobjectType = 'Opportunity'].id;
        o8.amount = 50000;
        
        //Reg
        /*o4.name = 'test opp 4';
        o4.stagename = 'Won';
        o4.closedate = Date.today()+25;
        o4.Show_Name__c = s.id;
        o4.Show_Close_Date__c = Date.Today()+25;
        o4.Registration_Provider__c = 'test provider 4';
        o4.Show_Occurrence__c = o2.id;
        o4.RecordTypeId = [select Id from RecordType where Name = 'EMEA - Registration' and SobjectType = 'Opportunity'].id;
        o4.amount = 40000;*/
        
        //Reg
        o5.name = 'test opp 5';
        o5.stagename = 'Won';
        o5.closedate = Date.today()+25;
        o5.Show_Name__c = s.id;
        o5.Show_Close_Date__c = Date.Today()+26;
        o5.Registration_Provider__c = 'test provider 5';
        o5.Show_Occurrence__c = o6.id;
        o5.RecordTypeId = [select Id from RecordType where Name = 'EMEA - AV' and SobjectType = 'Opportunity'].id; /* EMEA - Registration */
        o5.amount = 40000;
        
        //AV
        o1.name = 'test opp 1';
        o1.stagename = 'CR';
        o1.closedate = Date.today()+5;
        o1.Show_Name__c = s.id;
        o1.Show_Close_Date__c = Date.Today()+5;
        o1.Audio_Visual_Provider__c = 'test provider 1';
        o1.Show_Occurrence__c = o2.id;
        o1.RecordTypeId = [select Id from RecordType where Name = 'AV - CR' and SobjectType = 'Opportunity'].id;
        o1.amount = 10000;
        
        //AV
        /*o7.name = 'test opp 7';
        o7.stagename = 'CR';
        o7.closedate = Date.today()+6;
        o7.Show_Name__c = s.id;
        o7.Show_End_Date_Time__c = DateTime.Now()+35;
        o7.Audio_Visual_Provider__c = 'test provider 7';
        o7.Show_Occurrence__c = o6.id;
        o7.RecordTypeId = [select Id from RecordType where Name = 'EMEA - AV New Business' and SobjectType = 'Opportunity'].id;
        o7.amount = 10000;*/
        
        
        List<Opportunity> opps2 = new List<Opportunity>();
        opps2.add(o3);
        //opps2.add(o4);
        opps2.add(o5);
        opps2.add(o1);
        //opps2.add(o7);
        opps2.add(o8);
        insert opps2;
        
        TriggerOptimizationUtility.ShowLOBDetails_Handled = new Set<Id>();
        delete o3;
        
        TriggerOptimizationUtility.ShowLOBDetails_Handled = new Set<Id>();
        s.Registration_Not_Applicable__c = true;
        s.Housing_Not_Applicable__c = true;
        s.AV_Not_Applicable__c = true;
        update s;
        Test.stopTest();

        LOBDetailsCalculations lob = new LOBDetailsCalculations();
        lob.dummyClasspro11method();
        lob.dummyClasspro22method();
        lob.dummyClasspro33method();
        lob.dummyClasspro44method();
        
    }
    
    static testMethod void MyTest2(){
        
        Account a = new Account();
        a.name = 'test account';
        a.recordTypeId = [select Id from RecordType where Name = 'Firm' and SobjectType = 'Account'].id;
        insert a;
        
        Test.startTest();
        Show__c s = new Show__c();
        s.Show_ID__c = 'abcdef';
        s.Sync_with_Marketo__c = true;
        insert s;
        
        Opportunity o1 = new Opportunity();
        Opportunity o2 = new Opportunity();
        Opportunity o3 = new Opportunity();
        //Opportunity o4 = new Opportunity();
        Opportunity o5 = new Opportunity();
        Opportunity o6 = new Opportunity();
        //Opportunity o7 = new Opportunity();
        Opportunity o8 = new Opportunity();
        
        //Exh
        o2.name = 'test opp 2';
        o2.stagename = 'LO';
        o2.closedate = Date.today()+10;
        o2.Show_Name__c = s.id;
        o2.Show_Close_Date__c = Date.Today()+10;
        o2.RecordTypeId = [select Id from RecordType where Name = 'Master Show Occurrence' and SobjectType = 'Opportunity'].id;
        o2.amount = 20000;
        o2.Prime_Contractor__c = a.id;
        
        //Exh
        o6.name = 'test opp 6';
        o6.stagename = 'LO';
        o6.closedate = Date.today()+9;
        o6.Show_Name__c = s.id;
        o6.Show_Close_Date__c = Date.Today()+9;
        o6.RecordTypeId = [select Id from RecordType where Name = 'EMEA - Exhibition' and SobjectType = 'Opportunity'].id; /* EMEA - Europe */
        o6.amount = 20000;
        o6.Prime_Contractor__c = a.id;
        
        List<Opportunity> opps = new List<Opportunity>();
        opps.add(o2);
        opps.add(o6);
        insert opps;
        
        //Hs
        o3.name = 'test opp 3';
        o3.stagename = 'CV';
        o3.closedate = Date.today()+15;
        o3.Show_Name__c = s.id;
        o3.Show_Close_Date__c = Date.Today()+15;
        o3.Housing_Provider__c = 'test provider 3';
        o3.Show_Occurrence__c = o2.id;
        o3.RecordTypeId = [select Id from RecordType where Name = 'EMEA - AV' and SobjectType = 'Opportunity'].id; /* EMEA – Housing */
        o3.amount = 30000;
        
        //Hs
        o8.name = 'test opp 8';
        o8.stagename = 'CV';
        o8.closedate = Date.today()+20;
        o8.Show_Name__c = s.id;
        o8.Show_Close_Date__c = Date.Today()+16;
        o8.Housing_Provider__c = 'test provider 8';
        o8.Show_Occurrence__c = o6.id;
        o8.RecordTypeId = [select Id from RecordType where Name = 'EMEA – Housing' and SobjectType = 'Opportunity'].id;
        o8.amount = 50000;
        
        //Reg
        /*o4.name = 'test opp 4';
        o4.stagename = 'CV';
        o4.closedate = Date.today()+25;
        o4.Show_Name__c = s.id;
        o4.Show_Close_Date__c = Date.Today()+25;
        o4.Registration_Provider__c = 'test provider 4';
        o4.Show_Occurrence__c = o2.id;
        o4.RecordTypeId = [select Id from RecordType where Name = 'EMEA - Registration' and SobjectType = 'Opportunity'].id;
        o4.amount = 40000;*/
        
        //Reg
        o5.name = 'test opp 5';
        o5.stagename = 'CV';
        o5.closedate = Date.today()+25;
        o5.Show_Name__c = s.id;
        o5.Show_Close_Date__c = Date.Today()+26;
        o5.Registration_Provider__c = 'test provider 5';
        o5.Show_Occurrence__c = o6.id;
        o5.RecordTypeId = [select Id from RecordType where Name = 'US - Registration' and SobjectType = 'Opportunity'].id; /* EMEA - Registration */
        o5.amount = 40000;
        
        //AV
        o1.name = 'test opp 1';
        o1.stagename = 'CR';
        o1.closedate = Date.today()+5;
        o1.Show_Name__c = s.id;
        o1.Show_Close_Date__c = Date.Today()+5;
        o1.Audio_Visual_Provider__c = 'test provider 1';
        o1.Show_Occurrence__c = o2.id;
        o1.RecordTypeId = [select Id from RecordType where Name = 'AV - CR' and SobjectType = 'Opportunity'].id;
        o1.amount = 10000;
        
        //AV
        /*o7.name = 'test opp 7';
        o7.stagename = 'CR';
        o7.closedate = Date.today()+6;
        o7.Show_Name__c = s.id;
        o7.Show_End_Date_Time__c = DateTime.Now()+35;
        o7.Audio_Visual_Provider__c = 'test provider 7';
        o7.Show_Occurrence__c = o6.id;
        o7.RecordTypeId = [select Id from RecordType where Name = 'EMEA - AV New Business' and SobjectType = 'Opportunity'].id;
        o7.amount = 10000;*/
        
        
        List<Opportunity> opps2 = new List<Opportunity>();
        opps2.add(o3);
        //opps2.add(o4);
        opps2.add(o5);
        opps2.add(o1);
        //opps2.add(o7);
        opps2.add(o8);
        insert opps2;
        
        TriggerOptimizationUtility.ShowLOBDetails_Handled = new Set<Id>();
        delete o3;
        
        TriggerOptimizationUtility.ShowLOBDetails_Handled = new Set<Id>();
        s.Registration_Not_Applicable__c = true;
        s.Housing_Not_Applicable__c = true;
        s.AV_Not_Applicable__c = true;
        update s;
        Test.stopTest();
    }
}