unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>GES Connect Order Object.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Role__c.field-meta.xml
<CustomField>
    <fullName>Show_Role__c</fullName>
    <description>Determines the level of access to associated elements on a show.</description>
    <inlineHelpText>Determines the level of access to associated elements on a show.</inlineHelpText>
    <label>Show Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Convention_Planning</fullName>
                <label>Convention Planning</label>
            </value>
            <value>
                <fullName>Creative Director</fullName>
            </value>
            <value>
                <fullName>Designer/Detailer</fullName>
            </value>
            <value>
                <fullName>Director of Account Management</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager Direct</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Secondary Account Manager</fullName>
            </value>
            <value>
                <fullName>Show Organizer</fullName>
            </value>
            <value>
                <fullName>Show Organizer - Read Only</fullName>
            </value>
            <value>
                <fullName>Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/GC_Vendor_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Vendor Order Task Custom Object. This Object is used to identify Vendor Order Task details to be performed in a GES Connect Show.</description>
    <label>Vendor Order Task</label>
    <nameField>
        <displayFormat>VOT-{0000}</displayFormat>
        <label>Vendor Order Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/GESOrderTask1__c.field-meta.xml
<CustomField>
    <fullName>GESOrderTask1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the GES Order Task associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order Task associated with this vendor order task.</inlineHelpText>
    <label>GES Order Task 1</label>
    <referenceTo>GC_GES_Order_Task__c</referenceTo>
    <relationshipLabel>GES Order Tasks</relationshipLabel>
    <relationshipName>GES_Order_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/GESOrderTask2__c.field-meta.xml
<CustomField>
    <fullName>GESOrderTask2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the GES Order Task associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order Task associated with this vendor order task.</inlineHelpText>
    <label>GES Order Task 2</label>
    <referenceTo>GC_GES_Order_Task__c</referenceTo>
    <relationshipLabel>GES Order Tasks</relationshipLabel>
    <relationshipName>GES_Order_Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/GESOrderTask3__c.field-meta.xml
<CustomField>
    <fullName>GESOrderTask3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the GES Order Task associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order Task associated with this vendor order task.</inlineHelpText>
    <label>GES Order Task 3</label>
    <referenceTo>GC_GES_Order_Task__c</referenceTo>
    <relationshipLabel>GES Order Tasks</relationshipLabel>
    <relationshipName>GES_Order_Tasks3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/GESOrderTask4__c.field-meta.xml
<CustomField>
    <fullName>GESOrderTask4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the GES Order Task associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order Task associated with this vendor order task.</inlineHelpText>
    <label>GES Order Task 4</label>
    <referenceTo>GC_GES_Order_Task__c</referenceTo>
    <relationshipLabel>GES Order Tasks</relationshipLabel>
    <relationshipName>GES_Order_Tasks4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/GESOrderTask5__c.field-meta.xml
<CustomField>
    <fullName>GESOrderTask5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the GES Order Task associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order Task associated with this vendor order task.</inlineHelpText>
    <label>GES Order Task 5</label>
    <referenceTo>GC_GES_Order_Task__c</referenceTo>
    <relationshipLabel>GES Order Tasks</relationshipLabel>
    <relationshipName>GES_Order_Tasks5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the GES Order associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order associated with this vendor order task.</inlineHelpText>
    <label>Delivery Location</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipLabel>Vendor Order Tasks</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/SelectAllOrderTasks__c.field-meta.xml
<CustomField>
    <fullName>SelectAllOrderTasks__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Select All Order Tasks</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor2__c.field-meta.xml
<CustomField>
    <fullName>Vendor2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor 2</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor3__c.field-meta.xml
<CustomField>
    <fullName>Vendor3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor 3</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor4__c.field-meta.xml
<CustomField>
    <fullName>Vendor4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor 4</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor5__c.field-meta.xml
<CustomField>
    <fullName>Vendor5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor 5</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GC_VendorOrderTaskTriggerHandler.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Trigger logic for Vendor Order Task
* 2016-04-13 : Original Version
**/
public without sharing class GC_VendorOrderTaskTriggerHandler {

    public static void UpdateShowTeamAccess(List<GC_Vendor_Order_Task__c> vendorOrderTask) {
        Set<Id> votIds = new Set<Id>();

        for (GC_Vendor_Order_Task__c vot : vendorOrderTask) {
            votIds.add(vot.Id);
        }

        List<GC_Vendor_Order_Task__c> votQuery = [select Id, order__r.id, Order__r.Connect2_Show__c, Vendor__c from GC_Vendor_Order_Task__c where Id In :votIds];
        Set<Id> showIds = new Set<Id>();
        Set<Id> vendorIds = new Set<Id>();
        List<GC_Order__c> ordersOfVots = new  List<GC_Order__c>();
        for (GC_Vendor_Order_Task__c vot : votQuery) {
            showIds.add(vot.Order__r.Connect2_Show__c);
            //GC_Order__c votOrder= new GC_Order__c();
            //votOrder
            ordersOfVots.add(vot.Order__r);
            vendorIds.add(vot.Vendor__c);
        }

        List<GC_Show_Team_Member__c> showTeamMembers = [select Id, Name, User__c, Show_Role__c, Connect2_Show__c from GC_Show_Team_Member__c where Connect2_Show__c in :showIds];
        if(vendorIds.size()>0){
                List<GC_Show_Team_Member__c> showVendors = [select Id, Name, User__c, Show_Role__c, Connect2_Show__c from GC_Show_Team_Member__c where Connect2_Show__c in :vendorIds];
                //GC_ShowTeamMemberTriggerHandler.UpdateRecordAccessOrders(showVendors, ordersOfVots);
        }

        
        GC_ShowTeamMemberTriggerHandler.UpdateRecordAccessVendorOrderTasks(showTeamMembers, votQuery);
    }


    public static void HandleShowTeamCreation(List<GC_Vendor_Order_Task__c> vendorOrderTasks) {
        Set<Id> votIds = new Set<Id>();
        List<GC_Show_Team_Member__c> stmList = new List<GC_Show_Team_Member__c>();

        for (GC_Vendor_Order_Task__c vot : vendorOrderTasks) {
            votIds.add(vot.Id);

        }

        List<GC_Vendor_Order_Task__c> votQuery = [select Id, Order__r.Connect2_Show__c, Vendor__c from GC_Vendor_Order_Task__c where Id In :votIds];

        for (GC_Vendor_Order_Task__c vot : votQuery) {

            GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c();
            stm.Connect2_Show__c = vot.Order__r.Connect2_Show__c;
            stm.User__c = vot.Vendor__c;
            stm.Show_Role__c = 'Vendor';
            stmList.add(stm);
        }

        Database.insert(stmList, false);
    }


    public static void HandleVendorShares(List<GC_Vendor_Order_Task__c> vendorOrderTasks) {
        Set<Id> votIds = new Set<Id>();

        for (GC_Vendor_Order_Task__c vot : vendorOrderTasks) {
            votIds.add(vot.Id);
        }

        List<GC_Vendor_Order_Task__c> votQuery = [Select Id, Order__c, Vendor__c, Vendor2__c, Vendor3__c, Vendor4__c, Vendor5__c, Order__r.Connect2_Show__c from GC_Vendor_Order_Task__c where Id in :votIds];

        List<GC_Vendor_Order_Task__Share> votShares = new List<GC_Vendor_Order_Task__Share>();
        List<GC_Connect2_Show__Share> connect2Shares = new List<GC_Connect2_Show__Share>();
        List<GC_Order__Share> orderShares = new List<GC_Order__Share>();
        Map<String, String> vendorMap = new Map<String, String>();
        List<GC_Show_Team_Member__c> showVendors = new List<GC_Show_Team_Member__c>();

        Set<Id> showIds = new Set<Id>();

        for (GC_Vendor_Order_Task__c vot : votQuery) {
            showIds.add(vot.Order__r.Connect2_Show__c);
        }

        List<GC_Show_Team_Member__c> showteamMembers = [select Id, Name, User__c, Show_role__c, Connect2_Show__c from GC_Show_Team_Member__c where Connect2_Show__c in :showIds];

        for (GC_Vendor_Order_Task__c vot : votQuery) {
            if (vot.Vendor__c != null) {
                GC_Vendor_Order_Task__Share votShareObject = new GC_Vendor_Order_Task__Share();
                votShareObject.ParentId = vot.Id;
                votShareObject.UserOrGroupId = vot.Vendor__c;
                votShareObject.AccessLevel = 'Read';
                votShares.add(votShareObject);

                GC_Connect2_Show__Share connect2ShareObject = new GC_Connect2_Show__Share();
                connect2ShareObject.ParentId = vot.Order__r.Connect2_Show__c;
                connect2ShareObject.UserOrGroupId = vot.Vendor__c;
                connect2ShareObject.AccessLevel = 'Read';
                connect2Shares.add(connect2ShareObject);

                GC_Order__Share orderShareObject = new GC_Order__Share();
                orderShareObject.ParentId = vot.Order__c;
                orderShareObject.UserOrGroupId = vot.Vendor__c;
                orderShareObject.AccessLevel = 'Read';
                orderShares.add(orderShareObject);
                vendorMap.put(vot.Vendor__c, vot.Id);
            }

            if (vot.Vendor2__c != null) {
                GC_Vendor_Order_Task__Share votShareObject = new GC_Vendor_Order_Task__Share();
                votShareObject.ParentId = vot.Id;
                votShareObject.UserOrGroupId = vot.Vendor2__c;
                votShareObject.AccessLevel = 'Read';
                votShares.add(votShareObject);

                GC_Connect2_Show__Share connect2ShareObject = new GC_Connect2_Show__Share();
                connect2ShareObject.ParentId = vot.Order__r.Connect2_Show__c;
                connect2ShareObject.UserOrGroupId = vot.Vendor2__c;
                connect2ShareObject.AccessLevel = 'Read';
                connect2Shares.add(connect2ShareObject);

                GC_Order__Share orderShareObject = new GC_Order__Share();
                orderShareObject.ParentId = vot.Order__c;
                orderShareObject.UserOrGroupId = vot.Vendor2__c;
                orderShareObject.AccessLevel = 'Read';
                orderShares.add(orderShareObject);
                vendorMap.put(vot.Vendor2__c, vot.Id);
            }

            if (vot.Vendor3__c != null) {
                GC_Vendor_Order_Task__Share votShareObject = new GC_Vendor_Order_Task__Share();
                votShareObject.ParentId = vot.Id;
                votShareObject.UserOrGroupId = vot.Vendor3__c;
                votShareObject.AccessLevel = 'Read';
                votShares.add(votShareObject);

                GC_Connect2_Show__Share connect2ShareObject = new GC_Connect2_Show__Share();
                connect2ShareObject.ParentId = vot.Order__r.Connect2_Show__c;
                connect2ShareObject.UserOrGroupId = vot.Vendor3__c;
                connect2ShareObject.AccessLevel = 'Read';
                connect2Shares.add(connect2ShareObject);

                GC_Order__Share orderShareObject = new GC_Order__Share();
                orderShareObject.ParentId = vot.Order__c;
                orderShareObject.UserOrGroupId = vot.Vendor3__c;
                orderShareObject.AccessLevel = 'Read';
                orderShares.add(orderShareObject);
                vendorMap.put(vot.Vendor3__c, vot.Id);
            }

            if (vot.Vendor4__c != null) {
                GC_Vendor_Order_Task__Share votShareObject = new GC_Vendor_Order_Task__Share();
                votShareObject.ParentId = vot.Id;
                votShareObject.UserOrGroupId = vot.Vendor4__c;
                votShareObject.AccessLevel = 'Read';
                votShares.add(votShareObject);

                GC_Connect2_Show__Share connect2ShareObject = new GC_Connect2_Show__Share();
                connect2ShareObject.ParentId = vot.Order__r.Connect2_Show__c;
                connect2ShareObject.UserOrGroupId = vot.Vendor4__c;
                connect2ShareObject.AccessLevel = 'Read';
                connect2Shares.add(connect2ShareObject);

                GC_Order__Share orderShareObject = new GC_Order__Share();
                orderShareObject.ParentId = vot.Order__c;
                orderShareObject.UserOrGroupId = vot.Vendor4__c;
                orderShareObject.AccessLevel = 'Read';
                orderShares.add(orderShareObject);
                vendorMap.put(vot.Vendor4__c, vot.Id);
            }

            if (vot.Vendor5__c != null) {
                GC_Vendor_Order_Task__Share votShareObject = new GC_Vendor_Order_Task__Share();
                votShareObject.ParentId = vot.Id;
                votShareObject.UserOrGroupId = vot.Vendor5__c;
                votShareObject.AccessLevel = 'Read';
                votShares.add(votShareObject);

                GC_Connect2_Show__Share connect2ShareObject = new GC_Connect2_Show__Share();
                connect2ShareObject.ParentId = vot.Order__r.Connect2_Show__c;
                connect2ShareObject.UserOrGroupId = vot.Vendor5__c;
                connect2ShareObject.AccessLevel = 'Read';
                connect2Shares.add(connect2ShareObject);

                GC_Order__Share orderShareObject = new GC_Order__Share();
                orderShareObject.ParentId = vot.Order__c;
                orderShareObject.UserOrGroupId = vot.Vendor5__c;
                orderShareObject.AccessLevel = 'Read';
                orderShares.add(orderShareObject);
                vendorMap.put(vot.Vendor5__c, vot.Id);
            }
        }

        List<GC_Show_Team_Member__c> showVendorQuery = [select Id, Name, User__c, Show_role__c, Connect2_Show__c from GC_Show_Team_Member__c where User__c in :vendorMap.keySet()];

        for (GC_Show_Team_Member__c sho : showVendorQuery) {
            showVendors.add(sho);
        }

        Database.insert(votShares, false);
        Database.insert(connect2Shares, false);
        Database.insert(orderShares, false);
        Database.insert(showVendors, false);
    }

    public static void AddVendorToShow(List<GC_Vendor_Order_Task__c> vendorTasks) {
        List<GC_Show_Team_Member__c> stmList = new List<GC_Show_Team_Member__c>();

        Set<Id> votIds = new Set<Id>();

        for (GC_Vendor_Order_Task__c vot : vendorTasks) {
            votIds.add(vot.Id);
        }

        List<GC_Vendor_Order_Task__c> votQuery = [Select Id, Order__c, Vendor__c, Vendor2__c, Vendor3__c, Vendor4__c, Vendor5__c, Order__r.Connect2_Show__c from GC_Vendor_Order_Task__c where Id in :votIds];

        for (GC_Vendor_Order_Task__c vot : votQuery) {
            if (vot.Vendor__c != null) {
                GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c();
                stm.Connect2_Show__c = vot.Order__r.Connect2_Show__c;
                stm.User__c = vot.Vendor__c;
                stm.Show_Role__c = 'Vendor';
                stmList.add(stm);
            }

            if (vot.Vendor2__c != null) {
                GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c();
                stm.Connect2_Show__c = vot.Order__r.Connect2_Show__c;
                stm.User__c = vot.Vendor2__c;
                stm.Show_Role__c = 'Vendor';
                stmList.add(stm);
            }

            if (vot.Vendor3__c != null) {
                GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c();
                stm.Connect2_Show__c = vot.Order__r.Connect2_Show__c;
                stm.User__c = vot.Vendor3__c;
                stm.Show_Role__c = 'Vendor';
                stmList.add(stm);
            }

            if (vot.Vendor4__c != null) {
                GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c();
                stm.Connect2_Show__c = vot.Order__r.Connect2_Show__c;
                stm.User__c = vot.Vendor4__c;
                stm.Show_Role__c = 'Vendor';
                stmList.add(stm);
            }

            if (vot.Vendor5__c != null) {
                GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c();
                stm.Connect2_Show__c = vot.Order__r.Connect2_Show__c;
                stm.User__c = vot.Vendor5__c;
                stm.Show_Role__c = 'Vendor';
                stmList.add(stm);
            }
        }

        if (stmList.size() > 0) {
            //insert stmList;
            Database.insert(stmList, false);
        }
    }

    public static void AddVendorToShow(Map<Id, GC_Vendor_Order_Task__c> oldMap, Map<Id, GC_Vendor_Order_Task__c> newMap) {
        Set<Id> votIds = new Set<Id>();

        for (Id task : oldMap.keySet()) {
            if (oldMap.get(task).Vendor__c != newMap.get(task).Vendor__c) {
                votIds.add(task);
            }

            if (oldMap.get(task).Vendor2__c != newMap.get(task).Vendor2__c) {
                votIds.add(task);
            }

            if (oldMap.get(task).Vendor3__c != newMap.get(task).Vendor3__c) {
                votIds.add(task);
            }

            if (oldMap.get(task).Vendor4__c != newMap.get(task).Vendor4__c) {
                votIds.add(task);
            }

            if (oldMap.get(task).Vendor5__c != newMap.get(task).Vendor5__c) {
                votIds.add(task);
            }
        }

        if (votIds.size() > 0) {
            List<GC_Vendor_Order_Task__c> votQuery = [select Id, Order__r.Connect2_Show__c, Vendor__c, Vendor2__c, Vendor3__c, Vendor4__c, Vendor5__c from GC_Vendor_Order_Task__c where Id In :votIds];
            AddVendorToShow(votQuery);
        }
    }

    public static void CheckChangeOwner(Map<Id, GC_Vendor_Order_Task__c> oldMap, Map<Id, GC_Vendor_Order_Task__c> newMap) {
        List<GC_Vendor_Order_Task__c> recalcRecords = new List<GC_Vendor_Order_Task__c>();

        for (Id taskId : Trigger.newMap.keySet()) {
            if (oldMap.get(taskId).OwnerId != newMap.get(taskId).OwnerId) {
                recalcRecords.add(newMap.get(taskId));
            }
        }

        if (recalcRecords.size() > 0) {
            UpdateShowTeamAccess(recalcRecords);
            HandleVendorShares(recalcRecords);
        }
    }

    public static void HandleGESOrderTaskShares(List<GC_Vendor_Order_Task__c> vendorOrderTasks) {
        // Get the list of vendors by task
        // Get the list of ges tasks by vendor task
        List<GC_GES_Order_Task__Share> newShares = new List<GC_GES_Order_Task__Share>();
        //Set<Id> relatedOrderIdSet= new Set<Id>();
        Map<Id, Set<Id>>orderToVendorsMap = new Map<Id, Set<Id>>();

        for (GC_Vendor_Order_Task__c vot : vendorOrderTasks) {
            if(vot.SelectAllOrderTasks__c && vot.Order__c!=null){
                //relatedOrderIdSet.add(vot.Order__c);
                if(!orderToVendorsMap.containsKey(vot.Order__c)){
                    orderToVendorsMap.put(vot.Order__c, new Set<Id>());
                }
                orderToVendorsMap.get(vot.Order__c).add(vot.Vendor__c);
                //system.debug('Step 1 Checkbox checked for==='+vot.Vendor__c);
            }
            
            if (vot.Vendor__c != null) {
                if (vot.GESOrderTask1__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask1__c, vot.Vendor__c, 'Read'));
                }

                if (vot.GESOrderTask2__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask2__c, vot.Vendor__c, 'Read'));
                }

                if (vot.GESOrderTask3__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor__c, 'Read'));
                }

                if (vot.GESOrderTask4__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor__c, 'Read'));
                }

                if (vot.GESOrderTask5__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor__c, 'Read'));
                }
            }

            if (vot.Vendor2__c != null) {
                if (vot.GESOrderTask1__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask1__c, vot.Vendor2__c, 'Read'));
                }

                if (vot.GESOrderTask2__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask2__c, vot.Vendor2__c, 'Read'));
                }

                if (vot.GESOrderTask3__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor2__c, 'Read'));
                }

                if (vot.GESOrderTask4__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor2__c, 'Read'));
                }

                if (vot.GESOrderTask5__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor2__c, 'Read'));
                }
            }

            if (vot.Vendor3__c != null) {
                if (vot.GESOrderTask1__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask1__c, vot.Vendor3__c, 'Read'));
                }

                if (vot.GESOrderTask2__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask2__c, vot.Vendor3__c, 'Read'));
                }

                if (vot.GESOrderTask3__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor3__c, 'Read'));
                }

                if (vot.GESOrderTask4__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor3__c, 'Read'));
                }

                if (vot.GESOrderTask5__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor3__c, 'Read'));
                }
            }

            if (vot.Vendor4__c != null) {
                if (vot.GESOrderTask1__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask1__c, vot.Vendor4__c, 'Read'));
                }

                if (vot.GESOrderTask2__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask2__c, vot.Vendor4__c, 'Read'));
                }

                if (vot.GESOrderTask3__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor4__c, 'Read'));
                }

                if (vot.GESOrderTask4__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor4__c, 'Read'));
                }

                if (vot.GESOrderTask5__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor4__c, 'Read'));
                }
            }

            if (vot.Vendor5__c != null) {
                if (vot.GESOrderTask1__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask1__c, vot.Vendor5__c, 'Read'));
                }

                if (vot.GESOrderTask2__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask2__c, vot.Vendor5__c, 'Read'));
                }

                if (vot.GESOrderTask3__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor5__c, 'Read'));
                }

                if (vot.GESOrderTask4__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor5__c, 'Read'));
                }

                if (vot.GESOrderTask5__c != null) {
                    newShares.add(newGESTaskShare(vot.GESOrderTask3__c, vot.Vendor5__c, 'Read'));
                }
            }
        }
        
        //START- Create share objects for orders and all GOTs if the checkbox is selected -START
        if(orderToVendorsMap.keySet().size()>0){
            
            List<GC_GES_Order_Task__c> allGotsToBeShared = [SELECT id, name,Order__c FROM GC_GES_Order_Task__c WHERE Order__c IN :orderToVendorsMap.keySet() ];
            for(GC_GES_Order_Task__c gotToBeShared:allGotsToBeShared){
                if(orderToVendorsMap.containsKey(gotToBeShared.Order__c)){
                    for(Id vendorId: orderToVendorsMap.get(gotToBeShared.Order__c)){
                        newShares.add(newGESTaskShare(gotToBeShared.Id, vendorId, 'Read'));
                        //system.debug('Step 1 Checkbox checked for==='+vendorId);
                    }
                }
            }
            
        }
        
        //END- Create share objects for orders and all GOTs if the checkbox is selected -END
        Database.insert(newShares, false);
    }

    private static GC_GES_Order_Task__Share newGESTaskShare(String gesTaskId, String userId, String permissionLevel) {
        GC_GES_Order_Task__Share newShare = new GC_GES_Order_Task__Share();
        newShare.ParentId = gesTaskId;
        newShare.UserOrGroupId = userId;
        newShare.AccessLevel = 'Read';
        return newShare;
    }

    public static void HandleGESOrderTaskShares(Map<Id, GC_Vendor_Order_Task__c> oldMap, Map<Id, GC_Vendor_Order_Task__c> newMap) {
        // this will ignore things like status changes and instruction changes, and only capture assignment changes.
        List<GC_Vendor_Order_Task__c> vendorTasks = new List<GC_Vendor_Order_Task__c>();

        for (Id task : oldMap.keySet()) {
            if (oldMap.get(task).Vendor__c != newMap.get(task).Vendor__c) {
                vendorTasks.add(newMap.get(task));
            } else if (oldMap.get(task).Vendor2__c != newMap.get(task).Vendor2__c) {
                vendorTasks.add(newMap.get(task));
            } else if (oldMap.get(task).Vendor3__c != newMap.get(task).Vendor3__c) {
                vendorTasks.add(newMap.get(task));
            } else if (oldMap.get(task).Vendor4__c != newMap.get(task).Vendor4__c) {
                vendorTasks.add(newMap.get(task));
            } else if (oldMap.get(task).Vendor5__c != newMap.get(task).Vendor5__c) {
                vendorTasks.add(newMap.get(task));
            } else if (oldMap.get(task).GESOrderTask1__c != newMap.get(task).GESOrderTask1__c) {
                vendorTasks.add(newMap.get(task));
            } else if (oldMap.get(task).GESOrderTask2__c != newMap.get(task).GESOrderTask2__c) {
                vendorTasks.add(newMap.get(task));
            } else if (oldMap.get(task).GESOrderTask3__c != newMap.get(task).GESOrderTask3__c) {
                vendorTasks.add(newMap.get(task));
            } else if (oldMap.get(task).GESOrderTask4__c != newMap.get(task).GESOrderTask4__c) {
                vendorTasks.add(newMap.get(task));
            } else if (oldMap.get(task).GESOrderTask5__c != newMap.get(task).GESOrderTask5__c) {
                vendorTasks.add(newMap.get(task));
            }
        }

        if (vendorTasks.size() > 0) {
            HandleGESOrderTaskShares(vendorTasks);
        }
    }
}