unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_10__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_10__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 10</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks10</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_11__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_11__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 11</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks11</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_12__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_12__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 12</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks12</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_13__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_13__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 13</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks13</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_14__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_14__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 14</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks14</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_15__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_15__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 15</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks15</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_2__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_3__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_4__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_5__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 5</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_6__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 6</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks6</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_7__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 7</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks7</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_8__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_8__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 8</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks8</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/AM_Approver_9__c.field-meta.xml
<CustomField>
    <fullName>AM_Approver_9__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple AMs</description>
    <label>AM Approver 9</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Order_Tasks9</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/GPM_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>GPM_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple GPMs</description>
    <inlineHelpText>Hidden user lookup field used to submit orders for approval to multiple GPMs</inlineHelpText>
    <label>GPM Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GPM_Approval_Order_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/GPM_Approver_2__c.field-meta.xml
<CustomField>
    <fullName>GPM_Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple GPMs</description>
    <label>GPM Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GPM_Approval_Order_Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/GPM_Approver_3__c.field-meta.xml
<CustomField>
    <fullName>GPM_Approver_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple GPMs</description>
    <label>GPM Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GPM_Approval_Order_Tasks3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/GPM_Direct__c.field-meta.xml
<CustomField>
    <fullName>GPM_Direct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Graphics Project Manager Direct, this will be set to the last one added on a show and populated upon submit.</description>
    <inlineHelpText>Graphics Project Manager Direct, this will be set to the last one added on a show and populated upon submit.</inlineHelpText>
    <label>GPM_Direct</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Template__c.field-meta.xml
<CustomField>
    <fullName>Item_Template__c</fullName>
    <description>Determines the list of order options to select for an order task</description>
    <inlineHelpText>Basic, Carpet, Graphics, Custom Carpet, Custom Graphics as determined by selecting the item.</inlineHelpText>
    <label>Item Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>GES Connect Order Object.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Role__c.field-meta.xml
<CustomField>
    <fullName>Show_Role__c</fullName>
    <description>Determines the level of access to associated elements on a show.</description>
    <inlineHelpText>Determines the level of access to associated elements on a show.</inlineHelpText>
    <label>Show Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Convention_Planning</fullName>
                <label>Convention Planning</label>
            </value>
            <value>
                <fullName>Creative Director</fullName>
            </value>
            <value>
                <fullName>Designer/Detailer</fullName>
            </value>
            <value>
                <fullName>Director of Account Management</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager Direct</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Secondary Account Manager</fullName>
            </value>
            <value>
                <fullName>Show Organizer</fullName>
            </value>
            <value>
                <fullName>Show Organizer - Read Only</fullName>
            </value>
            <value>
                <fullName>Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GC_ApprovalUtils.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Utility class for approvals
* 2016-04-13 : Original Version
**/
public with sharing class GC_ApprovalUtils {
    public static final String ShowOrgSubmit = 'GES_Order_Approval_Process';
    public static final String ShowOrgGraphicsSubmit = 'GES_Order_Approval_Process_GPMDirect';
    public static final String ShowOrgGpmToAMSubmit = 'GES_Order_Approval_Process_AM_Review';
    //public static final String AccountMgrGraphicsSubmit = 'GES_Graphics_Order_AM_Approval_Process';

    public static Boolean isUnderApproval(String objectId) {
        List<ProcessInstanceWorkitem> wiList
            = [Select Id, ProcessInstance.Status, ProcessInstance.TargetObjectId, ProcessInstanceId
               From ProcessInstanceWorkitem where ProcessInstance.TargetObjectId = :objectId];
        return wiList.size() != 0;
    }

    public static Map<String, Boolean> isUnderApproval(Set<String> objectIds) {

        List<ProcessInstanceWorkitem> wiList = [Select Id, ProcessInstance.Status, ProcessInstance.TargetObjectId, ProcessInstanceId
                                                From ProcessInstanceWorkitem where ProcessInstance.TargetObjectId in :objectIds];

        Map<String, Boolean> approvalItems = new Map<String, Boolean>();

        for (String objectId : objectIds) {
            approvalItems.put(objectId, false);
        }

        for (ProcessInstanceWorkitem wi : wiList) {
            String procId = String.valueOf(wi.ProcessInstance.TargetObjectId);

            if (approvalItems.containsKey(procId)) {
                approvalItems.put(procId, true);
            }
        }

        return approvalItems;
    }

    public static Boolean submitForApproval(GC_GES_Order_Task__c got) {
        return submitForApproval(got.Order__r.Connect2_Show__c, new List<GC_GES_Order_Task__c> {got});
    }

    public static Boolean submitForApproval(String showId, List<GC_GES_Order_Task__c> gots) {
        Integer errors = 0;
        Integer successes = 0;
        // Get the show team
        List<GC_Show_Team_Member__c> accountManagersTeam = [Select Id, Name, User__c, Connect2_Show__c, Show_Role__c , User__r.Email
                From GC_Show_Team_Member__c
                Where Connect2_Show__c = :showId and (Show_Role__c = 'Account Manager' or
                                         Show_Role__c = 'Secondary Account Manager')
                                         Order By Show_Role__c asc, LastModifiedDate desc];

        List<GC_Show_Team_Member__c> graphicsTeam = [Select Id, Name, User__c, Connect2_Show__c, Show_Role__c , User__r.Email
                From GC_Show_Team_Member__c
                Where Connect2_Show__c = :showId
                                         and (Show_Role__c = 'Graphics Project Manager')
                                         Order By LastModifiedDate desc];

        List<GC_Show_Team_Member__c> graphicsDirect = [Select Id, Name, User__c, Connect2_Show__c, Show_Role__c , User__r.Email
                From GC_Show_Team_Member__c
                Where Connect2_Show__c = :showId
                                         and (Show_Role__c = 'Graphics Project Manager Direct')
                                         Order By LastModifiedDate desc];

        if (accountManagersTeam.size() == 0) {
            GC_PageUtil.AddErrorMessage('Account Manager is not assigned to show as a show team member. Cannot submit any tasks.');
            return false;
        }

        // create a list of tasks that meet all conditions to submit for approval
        List<GC_GES_Order_Task__c> tasksToUpdate = new List<GC_GES_Order_Task__c>();
        Set<String> taskIds = new Set<String>();

        for (GC_GES_Order_Task__c got : gots) {
            taskIds.add(got.Id);
        }

        Map<String, Boolean> tasksUnderApproval = isUnderApproval(taskIds);

        for (GC_GES_Order_Task__c got : gots) {
            taskIds.add(got.Id);

            Boolean validateStatus = GC_PageUtil.validateGesTask(got);

            if (!validateStatus) {
                errors++;
                continue;
            }

            if (tasksUnderApproval.containsKey(got.Id) && tasksUnderApproval.get(got.Id)) {
                GC_PageUtil.AddErrorMessage('The Task is Already under approval.');
                errors++;
                continue;
            }

            GC_GES_Order_Task__c updatedTask = updateTaskApprovers(got, showId, accountManagersTeam, graphicsTeam, graphicsDirect);

            if (updatedTask != null) {
                tasksToUpdate.add(updatedTask);
            }
        }

        // Update new approver fields needed by approval processes
        Database.update(tasksToUpdate, false);
      /*  List<GC_GES_Order_Task__Share> shareTaskWithGPMD = new List<GC_GES_Order_Task__Share>();
        for(GC_GES_Order_Task__c task: tasksToUpdate) {
            
            // create share objects so that the GPM Direct user will be able to edit the record.
            if(task.GPM_Direct__c != null && (task.Item_Template__c =='Graphics') ){
                GC_GES_Order_Task__Share shareObject = new GC_GES_Order_Task__Share();
                shareObject.ParentId = task.Id;
                shareObject.UserOrGroupId = task.GPM_Direct__c;
                shareObject.AccessLevel = 'Edit';
                shareTaskWithGPMD.add(shareObject);
            }
        }
        //database.insert(shareTaskWithGPMD, false);
        system.debug('shareTaskWithGPMD==='+shareTaskWithGPMD);
        */
        for(GC_GES_Order_Task__c task: tasksToUpdate) {
            
            
            if (submitTaskForApproval(task)) {
                successes++;
            }
            else {
                errors++;
            }
        }
        
        
        
        return successes > 0;
    }

    //public List<GC_GES_Order_Task__c> tasksToUpdate {get; private set;}

    //public static Boolean submitForApproval(GC_GES_Order_Task__c got) {
    //    return submitForApproval(got, null, null, null, null, null);
    //}

    //public static Boolean submitForApproval(GC_GES_Order_Task__c got, String showId, List<GC_Show_Team_Member__c> accountTeam, List<GC_Show_Team_Member__c> graphicsTeam, List<GC_Show_Team_Member__c> gpmDirect, List<GC_GES_Order_Task__c> tasks) {
    //    if (got.OwnerId != UserInfo.getUserId()) {
    //        GC_PageUtil.AddErrorMessage('The task may only be submitted by the task owner.');
    //        return false;
    //    } else {
    //        //Validation Rule:
    //        Boolean validateStatus = GC_PageUtil.validateGesTask(got);

    //        if (!validateStatus) {
    //            return false;
    //        }

    //        if (GC_ApprovalUtils.isUnderApproval(got.Id)) {
    //            GC_PageUtil.AddErrorMessage('The Task is Already under approval.');
    //            return false;
    //        }

    //        got = updateTaskApprovers(got, showId, accountTeam, graphicsTeam, gpmDirect);

    //        if (got == null) {
    //            return false;
    //        }

    //        if (tasks != null) {
    //            tasks.add(got);
    //        } else {
    //            update got;
    //            return submitTaskForApproval(got);
    //        }

    //        return true;
    //    }
    //}

    public static GC_GES_Order_Task__c updateTaskApprovers(GC_GES_Order_Task__c got, String showId, List<GC_Show_Team_Member__c> accountTeam, List<GC_Show_Team_Member__c> graphicsTeam, List<GC_Show_Team_Member__c> gpmDirect) {
        if (showId == null) {
            showId = got.Order__r.Connect2_Show__c;
        }

        if (accountTeam == null) {
            accountTeam = [Select Id, Name, User__c, Connect2_Show__c, Show_Role__c , User__r.Email
                           From GC_Show_Team_Member__c
                           Where Connect2_Show__c = :showId and (Show_Role__c = 'Account Manager' or
                                                    Show_Role__c = 'Secondary Account Manager')
                                                    Order By Show_Role__c asc, LastModifiedDate desc];
        }

        if (graphicsTeam == null) {
            graphicsTeam = [Select Id, Name, User__c, Connect2_Show__c, Show_Role__c , User__r.Email
                            From GC_Show_Team_Member__c
                            Where Connect2_Show__c = :showId
                                    and (Show_Role__c = 'Graphics Project Manager')
                                    Order By LastModifiedDate desc];
        }

        if (gpmDirect == null) {
            gpmDirect = [Select Id, Name, User__c, Connect2_Show__c, Show_Role__c , User__r.Email
                         From GC_Show_Team_Member__c
                         Where Connect2_Show__c = :showId
                                                  and (Show_Role__c = 'Graphics Project Manager Direct')
                                                  Order By LastModifiedDate desc];
        }

        // Blank out all approver fields and repopulate in case record has been submitted previously and team changed
        got.AM_Approver_1__c = null;
        got.AM_Approver_2__c = null;
        got.AM_Approver_3__c = null;
        got.AM_Approver_4__c = null;
        got.AM_Approver_5__c = null;
        got.AM_Approver_6__c = null;
        got.AM_Approver_7__c = null;
        got.AM_Approver_8__c = null;
        got.AM_Approver_9__c = null;
        got.AM_Approver_10__c = null;
        got.AM_Approver_11__c = null;
        got.AM_Approver_12__c = null;
        got.AM_Approver_13__c = null;
        got.AM_Approver_14__c = null;
        got.AM_Approver_15__c = null;

        got.GPM_Approver_1__c = null;
        got.GPM_Approver_2__c = null;
        got.GPM_Approver_3__c = null;
        got.GPM_Direct__c = null;

        for (GC_Show_Team_Member__c teamMember : accountTeam) {
            if (got.AM_Approver_1__c == null) {
                got.AM_Approver_1__c = teamMember.User__c;
            } else if (got.AM_Approver_2__c == null) {
                got.AM_Approver_2__c = teamMember.User__c;
            } else if (got.AM_Approver_3__c == null) {
                got.AM_Approver_3__c = teamMember.User__c;
            } else if (got.AM_Approver_4__c == null) {
                got.AM_Approver_4__c = teamMember.User__c;
            } else if (got.AM_Approver_5__c == null) {
                got.AM_Approver_5__c = teamMember.User__c;
            } else if (got.AM_Approver_6__c == null) {
                got.AM_Approver_6__c = teamMember.User__c;
            } else if (got.AM_Approver_7__c == null) {
                got.AM_Approver_7__c = teamMember.User__c;
            } else if (got.AM_Approver_8__c == null) {
                got.AM_Approver_8__c = teamMember.User__c;
            } else if (got.AM_Approver_9__c == null) {
                got.AM_Approver_9__c = teamMember.User__c;
            } else if (got.AM_Approver_10__c == null) {
                got.AM_Approver_10__c = teamMember.User__c;
            } else if (got.AM_Approver_11__c == null) {
                got.AM_Approver_11__c = teamMember.User__c;
            } else if (got.AM_Approver_12__c == null) {
                got.AM_Approver_12__c = teamMember.User__c;
            } else if (got.AM_Approver_13__c == null) {
                got.AM_Approver_13__c = teamMember.User__c;
            } else if (got.AM_Approver_14__c == null) {
                got.AM_Approver_14__c = teamMember.User__c;
            } else if (got.AM_Approver_15__c == null) {
                got.AM_Approver_15__c = teamMember.User__c;
            }
        }

        for (GC_Show_Team_Member__c teamMember : graphicsTeam) {
            if (got.GPM_Approver_1__c == null) {
                got.GPM_Approver_1__c = teamMember.User__c;
            } else if (got.GPM_Approver_2__c == null) {
                got.GPM_Approver_2__c = teamMember.User__c;
            } else if (got.GPM_Approver_3__c == null) {
                got.GPM_Approver_3__c = teamMember.User__c;
            }
        }

        if (gpmDirect.size() > 0) {
            got.GPM_Direct__c = gpmDirect[0].User__c;
        }

        // If any of the approver lookups are empty, need to fill them out with existing approver to prevent error
        if (got.AM_Approver_1__c != null) {
            if (got.AM_Approver_2__c == null) {
                got.AM_Approver_2__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_3__c == null) {
                got.AM_Approver_3__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_4__c == null) {
                got.AM_Approver_4__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_5__c == null) {
                got.AM_Approver_5__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_6__c == null) {
                got.AM_Approver_6__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_7__c == null) {
                got.AM_Approver_7__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_8__c == null) {
                got.AM_Approver_8__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_9__c == null) {
                got.AM_Approver_9__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_10__c == null) {
                got.AM_Approver_10__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_11__c == null) {
                got.AM_Approver_11__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_12__c == null) {
                got.AM_Approver_12__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_13__c == null) {
                got.AM_Approver_13__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_14__c == null) {
                got.AM_Approver_14__c = got.AM_Approver_1__c;
            }

            if (got.AM_Approver_15__c == null) {
                got.AM_Approver_15__c = got.AM_Approver_1__c;
            }
        } else {
            GC_PageUtil.AddErrorMessage('Account Manager is not assigned to show as a show team member. Cannot submit task.');
            return null;
        }

        if (got.GPM_Approver_1__c != null) {
            if (got.GPM_Approver_2__c == null) {
                got.GPM_Approver_2__c = got.GPM_Approver_1__c;
            }

            if (got.GPM_Approver_3__c == null) {
                got.GPM_Approver_3__c = got.GPM_Approver_1__c;
            }
        }
        return got;
    }

    public static Boolean submitTaskForApproval(GC_GES_Order_Task__c got) {
        // Create an approval request
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval');
        req1.setObjectId(got.Id);
        
// for SAL - 421== forking the approval process based on criteria
        if (got.GPM_Direct__c != null && (got.Item_Template__c =='Graphics') && got.Status__c=='Pending AM Review' ){
            req1.setProcessDefinitionNameOrId(ShowOrgGpmToAMSubmit);
        }
        /*if(got.GPM_Direct__c != null && (got.Item_Template__c =='Graphics') ){           
            req1.setProcessDefinitionNameOrId(ShowOrgGraphicsSubmit);
            // create a sharing rule to give access to the GPM Direct user
            
        } */
        else if (got.GPM_Direct__c != null && (got.Item_Template__c =='Graphics')){
            req1.setProcessDefinitionNameOrId(ShowOrgGraphicsSubmit);
        }else{
            req1.setProcessDefinitionNameOrId(ShowOrgSubmit);
        }
        

        // Submit the approval request for the account
        try {
            Approval.ProcessResult result = Approval.process(req1);
            GC_PageUtil.AddDeveloperMessage('Task has been Submitted for approval');
            return true;
            // GC-739 Email will be sent as a result of this to any GPM Direct Role Users.
            // Upon Active change.
        } catch (Exception e) {
            GC_PageUtil.AddErrorMessage('Failed to Submit the Task for Approval ' + e.getMessage());
            GC_PageUtil.AddDeveloperMessage('Failed to Submit the Task for Approval ' + e.getStackTraceString());
            return false;
        }
    }
    
    // for SAL 421- rksinha
    public static Boolean submitForGPMApproval(GC_GES_Order_Task__c got, String approvalProcess) {
        system.debug('got==='+got);
        // Create an approval request
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for GPM approval');
        req1.setObjectId(got.Id);
        
        req1.setProcessDefinitionNameOrId(approvalProcess);

        // Submit the approval request for the account
        try {
            Approval.ProcessResult result = Approval.process(req1);
            GC_PageUtil.AddDeveloperMessage('Task has been Submitted for GPM approval');
            return true;
            // GC-739 Email will be sent as a result of this to any GPM Direct Role Users.
            // Upon Active change.
        } catch (Exception e) {
            GC_PageUtil.AddErrorMessage('Failed to Submit the Task for Approval ' + e.getMessage());
            GC_PageUtil.AddDeveloperMessage('Failed to Submit the Task for Approval ' + e.getStackTraceString());
            return false;
        }
    }

    public static Boolean approveTask(GC_GES_Order_Task__c got) {
        try {
            Set<Id> gotIds = new Set<Id>();
            gotIds.add(got.Id);
            approveRecord(gotIds, 'Approve for submission to Core.');
            return true;
        } catch (Exception e) {
            GC_PageUtil.AddErrorMessage('Failed to approve task due to: ' + e.getMessage());
            return false;
        }
    }

    public static Boolean approveTasks(List<GC_GES_Order_Task__c> gots) {
        try {
            Set<Id> gotIds = new Set<Id>();
            for (GC_GES_Order_Task__c got : gots) {
                gotIds.add(got.Id);
            }
            approveRecord(gotIds, 'Approve for submission to Core.');
            return true;
        } catch (Exception e) {
            GC_PageUtil.AddErrorMessage('Failed to approve task due to: ' + e.getMessage());
            return false;
        }
    }

    public static void approveRecord(Set<Id> workItemId, String approvalText) {
        Set<Id> procinIds = new Set<Id>();
        Set<Id> setTargetObjectIds = new Set<Id>();
        system.debug('workItemId==='+workItemId);
        List<ProcessInstance> procins = [select Id from ProcessInstance where Status = 'Pending' and TargetObjectId in :workItemId];
        system.debug('procins==='+procins);
        for (ProcessInstance procin : procins) {
             procinIds.add(procin.Id);
        }
        system.debug('procinIds==='+procinIds);
        // Retrieve the process work instance id associated to the process instance
        List<ProcessInstanceWorkitem>  workitems = [select Id, ProcessInstance.TargetObjectId, ActorId from ProcessInstanceWorkitem where ProcessInstanceId in :procinIds];
        system.debug('workitems==='+workitems.size());
        for (ProcessInstanceWorkitem item : workitems) {
            if(!setTargetObjectIds.contains(item.ProcessInstance.TargetObjectId) && item.ActorId==UserInfo.getUserId()) {
                Approval.ProcessWorkItemRequest pwr = new Approval.ProcessWorkItemRequest();
               // system.debug('item==='+item);
               //system.debug('ProcessInstance.TargetObjectId==='+item.ProcessInstance.TargetObjectId);
               //system.debug('item.ActorId==='+item.ActorId);
                pwr.SetComments(approvalText);
                pwr.setWorkItemId(item.id);
                pwr.setAction('Approve');
                system.debug('pwr==='+pwr);
                // Execute process request
                try {
                    Approval.ProcessResult pr = Approval.process(pwr);
                    // setTargetObjectIds.add(item.ProcessInstance.TargetObjectId);
                } catch(Exception e) {
                    GC_PageUtil.AddErrorMessage('Failed to approve the task.' + e.getMessage());
                    System.debug(e.getMessage());
                }
            }
        }
    }

}