unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>GES Connect Order Object.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/GC_Vendor_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Vendor Order Task Custom Object. This Object is used to identify Vendor Order Task details to be performed in a GES Connect Show.</description>
    <label>Vendor Order Task</label>
    <nameField>
        <displayFormat>VOT-{0000}</displayFormat>
        <label>Vendor Order Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the GES Order associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order associated with this vendor order task.</inlineHelpText>
    <label>Delivery Location</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipLabel>Vendor Order Tasks</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GC_OrderBulkDeleteController.cls
/**
* @author Rahul Sinha   for SLK Software Services
* @description Controller for Bulk deletion of GES Order Tasks
* 23-02-2018 : Original Version
**/

public with sharing class GC_OrderBulkDeleteController {

    public List<GC_Order__c> orders {get; set;}
    public List<ResultWrapper> resultList {get; set;}
    //public String header {get; set;}
    //public String message {get; set;}
    public Set<Id> ordersToDelete = new Set<Id>();
    public GC_OrderBulkDeleteController(ApexPages.StandardSetController controller) {
        orders = controller.getSelected();
        resultList = new List<ResultWrapper>();
    }

    public void bulkDelete(){
        if(orders.size()>0){
            //header='Are You Sure?';
            //message='Please Confirm else close this dialog box.';
            for(GC_Order__c order:orders){
                ordersToDelete.add(order.Id);
            }
            List<GC_GES_Order_Task__c> relatedTasksToDelete= [SELECT id, Name from GC_GES_Order_Task__c WHERE Order__c In :ordersToDelete ];
            List<GC_Vendor_Order_Task__c> relatedVOTsToDelete= [SELECT id, Name from GC_Vendor_Order_Task__c WHERE Order__c In :ordersToDelete ];
            Database.delete(relatedTasksToDelete, false);
            Database.delete(relatedVOTsToDelete, false);
        }//else{
            //header='No Orders Selected';
            //message='Please select one or more orders to delete.';
        //}
        
        Database.DeleteResult[] deleteResultsList = Database.delete(orders, false);
        
        if(deleteResultsList.size()>0){
            for(Database.DeleteResult dr : deleteResultsList) {
                ResultWrapper rw= new ResultWrapper(dr);
                resultList.add(rw);
            }
        }
    }
    public PageReference backAction() {
        return new PageReference('/' + GC_Order__c.sobjecttype.getDescribe().getKeyPrefix());
    }
    
    public class ResultWrapper{
        public String name {get; set;}
        public String status {get; set;}
        
        public resultWrapper(Database.DeleteResult dr){
            this.name= string.valueOf(dr.getId());
            //this.status= string.valueOf(dr.isSuccess());
            if(dr.isSuccess()){
                this.status='Deleted Successfully';
            }else{
                for(Database.Error err : dr.getErrors()) {
                        this.status='The following error has occurred--'+string.valueOf(err.getMessage());
                    }
            }
        }
    }
}