unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Booth_Area_Discount__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area_Discount__c</fullName>
    <description>Booth Area discount percentage as determined by the Parent Orders booth area.</description>
    <inlineHelpText>Booth Area discount percentage 0-100</inlineHelpText>
    <label>Booth Area Discount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Carpet_Length__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Length__c</fullName>
    <description>Carpet Length Option (Required) when Submitting a Carpet Line Item Order.</description>
    <inlineHelpText>Carpet Length Option (Required) when Submitting a Carpet Line Item Order.</inlineHelpText>
    <label>Carpet Length</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Carpet_Width__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Width__c</fullName>
    <description>Carpet Width Option (Required) when Submitting a Carpet Line Item Order.</description>
    <inlineHelpText>Carpet Width Option (Required) when Submitting a Carpet Line Item Order.</inlineHelpText>
    <label>Carpet Width</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Child_Category__c.field-meta.xml
<CustomField>
    <fullName>Child_Category__c</fullName>
    <label>Child Category</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</inlineHelpText>
    <label>Installation/Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of Item from the External System.</description>
    <inlineHelpText>Description of Item from the External System.</inlineHelpText>
    <label>Item Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Electrical_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Electrical_Ordered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has electrical been ordered?</description>
    <inlineHelpText>Has electrical been ordered?</inlineHelpText>
    <label>Electrical Ordered</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Electrical_Under__c.field-meta.xml
<CustomField>
    <fullName>Electrical_Under__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does electrical need to be under carpet?</description>
    <inlineHelpText>Does electrical need to be under carpet?</inlineHelpText>
    <label>Electrical Under</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <description>Item Number defined by the product selection picklist.</description>
    <inlineHelpText>Item Number defined by the product selection picklist.</inlineHelpText>
    <label>Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Template__c.field-meta.xml
<CustomField>
    <fullName>Item_Template__c</fullName>
    <description>Determines the list of order options to select for an order task</description>
    <inlineHelpText>Basic, Carpet, Graphics, Custom Carpet, Custom Graphics as determined by selecting the item.</inlineHelpText>
    <label>Item Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>GES Connect Order Object.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Parent_Category__c.field-meta.xml
<CustomField>
    <fullName>Parent_Category__c</fullName>
    <label>Parent Category</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/QuantityNum__c.field-meta.xml
<CustomField>
    <fullName>QuantityNum__c</fullName>
    <description>Number of Units to Order</description>
    <inlineHelpText>Number of Units to Order</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</inlineHelpText>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Text field that displays current revision number</description>
    <inlineHelpText>Current revision number</inlineHelpText>
    <label>Revision</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Show_Management_Field__c.field-meta.xml
<CustomField>
    <fullName>Show_Management_Field__c</fullName>
    <description>Special Notes for the Order Task.</description>
    <inlineHelpText>Special Notes.</inlineHelpText>
    <label>Special Instructions (Client Remarks)</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Sign_Length__c.field-meta.xml
<CustomField>
    <fullName>Sign_Length__c</fullName>
    <description>Sign height in inches for a custom graphics order.</description>
    <inlineHelpText>Sign height in inches for a custom graphics order.</inlineHelpText>
    <label>Sign Height (in)</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Sign_Width__c.field-meta.xml
<CustomField>
    <fullName>Sign_Width__c</fullName>
    <description>Sign length in inches for a custom graphics order.</description>
    <inlineHelpText>Sign length in inches for a custom graphics order.</inlineHelpText>
    <label>Sign Width (in)</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Special_Instructions_Client_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Special_Instructions_Client_Remarks__c</fullName>
    <description>Special Notes for the Order Task</description>
    <inlineHelpText>Special Notes for the Order Task</inlineHelpText>
    <label>Special Instructions (Client Remarks)</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that display&#39;s different status values</description>
    <inlineHelpText>Status of GES Order Task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Graphics Requested</fullName>
            </value>
            <value>
                <fullName>Graphics Submitted</fullName>
            </value>
            <value>
                <fullName>Graphics Rejected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Submitted to Graphics</fullName>
            </value>
            <value>
                <fullName>Submitted For AM Review</fullName>
            </value>
            <value>
                <fullName>Pending AM Review</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <description>Units identified by the Order Item.</description>
    <inlineHelpText>Units identified by the Order Item.</inlineHelpText>
    <label>Units</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>Completion Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Completion Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>Delivery Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Delivery Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <description>Removal Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Removal Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Status of the Order.  Defaults to &#39;New&#39; and will clearly indicate the status of the order state and what its in.</description>
    <inlineHelpText>Status of the Order.</inlineHelpText>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_List__c/Product_List__c.object-meta.xml
<CustomObject>
    <label>Product List</label>
    <nameField>
        <label>Product List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_List__c/fields/Project_Number__c.field-meta.xml
<CustomField>
    <fullName>Project_Number__c</fullName>
    <label>Project Number</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_List__c/fields/Show_Org_Products__c.field-meta.xml
<CustomField>
    <fullName>Show_Org_Products__c</fullName>
    <description>It will keep a copy of values returned from GetShowOrgProducts method and can be refreshed anytime by using the refresh button on GOT Create Page</description>
    <label>Show Org Products</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/GC_GOTCreationControllerTest.cls
@isTest
private class GC_GOTCreationControllerTest {
    public GC_CoreQuery coreApi {get; set;}
    public CORE_V1MockImpl Core {get; set;}
    public List<String> currentItems { get; set; } 
    public GC_CoreQuery.GC_ItemHolder selectedItem { get; set; } 
    GC_GOTCreationControllerTest(){
        
    }
    
    @isTest static void testAllMethodsClassic(){
        GC_Order__c order= GC_TestUtils.getTestOrder(); 
        GC_GES_Order_Task__c got = new GC_GES_Order_Task__c();
        got.Order__c = order.Id;
        got.Sign_Length__c = 10;
        got.Sign_Width__c = 10;
        got.Delivery_Date_Time__c = DateTime.now();
        got.Completion_Date_Time__c = DateTime.now() + 10;
        got.Removal_Date_Time__c = DateTime.now() + 15;
        got.QuantityNum__c = 5;
        got.Carpet_Length__c = 15;
        got.Carpet_Width__c = 15;
        got.Revision__c = 1;
        got.Status__c = 'New';
        got.Item_Number__c = '400004';
        got.Item_Template__c = 'Carpet';
        got.UOM__c = 'SF';
        got.Electrical_Ordered__c = false;
        got.Electrical_Under__c = false;
        insert got;
        String classicURL = '/apex/GC_OrderView?id='+order.Id;
        
        Test.setCurrentPageReference(new PageReference('Page.GC_GOTCreatePage'));
        System.currentPageReference().getParameters().put('orderId',order.Id);    
        System.currentPageReference().getParameters().put('showId',order.Connect2_Show__c );
        System.currentPageReference().getParameters().put('isClone', 'true' );
        System.currentPageReference().getParameters().put('isEdit', 'true' );
        System.currentPageReference().getParameters().put('taskId', got.Id );
        System.currentPageReference().getParameters().put('isTaskPage', 'true' );
        
        
        
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(got);
        GC_GOTCreationController controller= new GC_GOTCreationController(stdController);
        PageReference pr = controller.sessionLoad();
        controller.coreApi.obtainProducts();
        
        //controller.coreApi.setItemNumber.add('400004');
        controller.selectedGesTask.task.Sign_Length__c = 10;
        controller.selectedGesTask.task.Sign_Width__c = 10;
        controller.selectedGesTask.task.Delivery_Date_Time__c = DateTime.now();
        controller.selectedGesTask.task.Completion_Date_Time__c = DateTime.now() + 10;
        controller.selectedGesTask.task.Removal_Date_Time__c = DateTime.now() + 15;
        controller.selectedGesTask.task.QuantityNum__c = 5;
        controller.selectedGesTask.task.Carpet_Length__c = 15;
        controller.selectedGesTask.task.Carpet_Width__c = 15;
        controller.selectedGesTask.task.Status__c = 'New';
        controller.selectedGesTask.task.Item_Number__c = '400004';
        controller.selectedGesTask.task.Item_Template__c = 'Carpet';
        controller.selectedGesTask.task.UOM__c = 'SF';
        controller.selectedGesTask.task.Show_Management_Field__c = '';
        controller.selectedGesTask.task.Electrical_Ordered__c = false;
        controller.selectedGesTask.task.Electrical_Under__c = false;
        GC_OrderViewController.GesTaskWrapper taskWrapper = controller.selectedGesTask;
        controller.taskFieldManager.Special_Instructions_Client_Remarks__c='Shown and Required';
        PageReference saveNReturn1=controller.validateFields();
        PageReference saveNReturn=controller.validateSave();
        //PageReference saveNReturn=controller.saveTask();
        PageReference cancelNReturn= controller.cancelEditTask();
        GC_GES_Order_Task__c taskk = taskWrapper.task.clone(false, false);
        controller.selectedGesTask= taskWrapper;
        controller.selectedGesTask.task = taskk;
        controller.coreapi.setItemNumber= new set<string>();
        controller.coreapi.setItemNumber.add(taskk.Item_Number__c);
        controller.coreapi.setItemNumber= new set<string>();
        
        saveNReturn1=controller.saveTask();
        GC_GOTCreationController.getReasonCodes('inputReasonCode');
        controller.clearDiscountValues();
        stdController.save();
             
    }
    
    @isTest static void testAllMethodsComm(){
        Test.setMock(WebServiceMock.class, new CORE_V1MockImpl());
        CORE_V1.BasicHttpBinding_IProductService productService = new CORE_V1.BasicHttpBinding_IProductService();
        GC_Order__c order= GC_TestUtils.getTestOrder(); 
        GC_GES_Order_Task__c got = new GC_GES_Order_Task__c();
        got.Order__c = order.Id;
        got.Sign_Length__c = 10;
        got.Sign_Width__c = 10;
        got.Delivery_Date_Time__c = DateTime.now();
        got.Completion_Date_Time__c = DateTime.now() + 10;
        got.Removal_Date_Time__c = DateTime.now() + 15;
        got.QuantityNum__c = 5;
        got.Carpet_Length__c = 15;
        got.Carpet_Width__c = 15;
        //got.Revision__c = 1;
        got.Status__c = 'New';
        got.Item_Number__c = '400004';
        got.Item_Template__c = 'Carpet';
        got.UOM__c = 'SF';
        got.Electrical_Ordered__c = false;
        got.Electrical_Under__c = false;
        got.Parent_Category__c='test';
        got.Child_Category__c='test';
        got.Booth_Area_Discount__c=10;
        got.Description__c='Test Desc';
        insert got;
        String communityURL = '/apex/GC_Community_OrderView?orderid='+order.Id+'&showid='+order.Connect2_Show__c;
        
        Test.setCurrentPageReference(new PageReference('Page.GC_Community_GOTCreatePage'));
        System.currentPageReference().getParameters().put('orderId',order.Id);    
        System.currentPageReference().getParameters().put('showId',order.Connect2_Show__c );
        GC_GOTCreationController controller= new GC_GOTCreationController();
        GC_OrderViewController.GesTaskWrapper taskWrapper = controller.selectedGesTask;
        controller.taskFieldManager.Special_Instructions_Client_Remarks__c='Shown and Required';
        PageReference pr = controller.sessionLoad();
        controller.coreApi.obtainProducts();
        controller.coreApi.selectItem();
        controller.coreApi.obtainBoothAreas();
        controller.coreApi.selectBoothArea();
        controller.coreapi.setItemNumber= new set<string>();
        controller.coreapi.setItemNumber.add(got.Item_Number__c);
        controller.selectedGesTask.task=got;
        PageReference saveNReturn=controller.validateSave();
        PageReference pr1=controller.saveTask();
        PageReference cancelNReturn= controller.cancelEditTask();
        
        Product_List__c prd = new Product_List__c();
        prd.Name = 'test';
        prd.Project_Number__c ='123456';
        prd.Show_Org_Products__c='test';

        insert prd;
        
         List<Product_List__c> productList = new  List<Product_List__c>();
         productList.add(prd);
        
        SelectOption so = new SelectOption('uniqueValue', 'displayValue');
       
       
        LargeSelectList lst = new LargeSelectList();
        lst.add(so);
        controller.coreApi.populateProductList();
        controller.coreApi.emptyProductList();
        controller.coreApi.selectedParentCategory='Carpet';
        controller.coreApi.selectedChildCategory ='Autro';
        controller.coreApi.searchItemClick='searchItemHidden';
        controller.coreApi.selectedItemNumberAndDescription='400004_Test Desc';
        
       /*  GC_CoreQuery.GC_ItemHolder gcItem =  controller.coreApi.selectedItem;
        gcItem.BoothAreaDiscount='12';
        gcItem.Category='2345';
        gcItem.CategoryId ='1234';
        gcItem.ChildCategory='Testchild';
        gcItem.ImageUrl='image.jpeg';
        gcItem.InventoryItemId='Test';
        gcItem.ItemDescription='testItemdesc';
        gcItem.ItemNumber='1234';
        gcItem.ItemOptionTemplate='Carpet';
        gcItem.ItemType='String';
        gcItem.LineOfBusiness='TestLob';
        gcItem.ParentCategory='Carpet';
        gcItem.Price='1234';
        gcItem.TaxRate='1234';
        gcItem.Units='12345'; */
        
       
        controller.coreApi.selectItem();
         SelectOption noneOption = new SelectOption('' , '--None--');
        noneOption.setValue('test');
         
        List<SelectOption> childCategories= new  List<SelectOption>();
            childCategories.add(noneOption);
       controller.coreApi.selectCategories();      
      
        
      }      
}