unpackaged/main/default/objects/Freight_Item__c/Freight_Item__c.object-meta.xml
<CustomObject>
    <label>Freight Item</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freight Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Freight_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Quote_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Pickup_Date__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Date__c</fullName>
    <label>Pickup Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>Custom object to support Quote functionality for Logistics and other businesses (e.g. Graphics)</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote__c/fields/Destination_State__c.field-meta.xml
<CustomField>
    <fullName>Destination_State__c</fullName>
    <description>Inbound Shipping Destination State</description>
    <label>Destination State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/OB_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>OB_Delivery_Date__c</fullName>
    <description>Outbound Shipping Delivery Date</description>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/OB_Destination_State__c.field-meta.xml
<CustomField>
    <fullName>OB_Destination_State__c</fullName>
    <description>Outbound Shipping Destination State</description>
    <label>Destination State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/OB_Origination_State__c.field-meta.xml
<CustomField>
    <fullName>OB_Origination_State__c</fullName>
    <label>Origination State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/OB_Pickup_Date__c.field-meta.xml
<CustomField>
    <fullName>OB_Pickup_Date__c</fullName>
    <description>Outbound Shipping Pickup date.</description>
    <label>Pickup Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/OB_Shipment_Type__c.field-meta.xml
<CustomField>
    <fullName>OB_Shipment_Type__c</fullName>
    <label>OB Shipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Air Transportation</fullName>
            </value>
            <value>
                <fullName>Ground Transportation</fullName>
            </value>
            <value>
                <fullName>Local Shipments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Origination_State__c.field-meta.xml
<CustomField>
    <fullName>Origination_State__c</fullName>
    <label>Origination State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Shipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Type__c</fullName>
    <label>Shipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Air Transportation</fullName>
            </value>
            <value>
                <fullName>Ground Transportation</fullName>
            </value>
            <value>
                <fullName>Local Shipments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LogisticsDLSReports.cls
global with sharing class LogisticsDLSReports {
	/*
	global static Blob InboundDLSReport {get; set;}
	global static Blob OutboundDLSReport {get; set;}
	global static LogisticsQuoteReportService.BasicHttpEndpoint_IDLSReport DLSReport {get; set; }
	global static LogisticsQuoteReportService.ExternalQuote ExQuote {get; set; }
	global static LogisticsQuoteReportService.ArrayOfExternalQuoteLine ArrExQuoteLines { get; set; }
	global static Quote__c q {get; set; }
	global static Freight_Item__c[] arrFI {get; set; }
	global static boolean InReportRequiredFieldsSpecified {get; set; }
	global static boolean OutReportRequiredFieldsSpecified {get; set; }
	
    global class CalloutException extends Exception {        
    }
    
    WebService static void CreateDLSReport(id quoteId)
    {      
        String ErrorMessage = ''; Initialize(quoteId);
        
      	try
      	{	        	        	
	        if (InReportRequiredFieldsSpecified)
	        {
	        	if (CreateInboundReportPreInvoke(quoteId, q, arrFI, DLSReport))
	        	{ InboundDLSReport = CreateInboundReport(DLSReport, ExQuote); }
	        }
			//else
			//	ErrorMessage = 'Minimum fields required for creating BOL report for Inbound Shipment not provided.';
			
				
	        if (OutReportRequiredFieldsSpecified)
			{
	        	if (CreateOutboundReportPreInvoke(quoteId, q, arrFI, DLSReport))
	        	{ OutboundDLSReport = CreateOutboundReport(DLSReport, ExQuote); }			
			}
	        //else
	        //	ErrorMessage = (ErrorMessage != '' ? ErrorMessage + '\n' + 'Minimum fields required for creating BOL report for Outbound Shipment not provided.' : 'Minimum fields required for creating BOL report for Outbound Shipment not provided.');
			
			SaveInboundDLSReport(quoteId, InboundDLSReport); SaveOutboundDLSReport(quoteId, OutboundDLSReport);	
			
      	}
      	finally
      	{
      		q = null; arrFI = null; InboundDLSReport = null; OutboundDLSReport = null; DLSReport = null; ExQuote = null; ArrExQuoteLines = null;
      	}       
    }  
    
    public static void Initialize(Id quoteId)
    {
    	q = LogisticsQuoteObjectMapper.getQuote(quoteId);		
        arrFI = LogisticsQuoteObjectMapper.getFreightItems(quoteId); 
        
        DLSReport = new LogisticsQuoteReportService.BasicHttpEndpoint_IDLSReport();
        
	    InReportRequiredFieldsSpecified = q.Origination_State__c != null && q.Origination_State__c != '' && 
	        	q.Destination_State__c != null && q.Destination_State__c != '' &&
	        	q.Pickup_Date__c != null && q.Delivery_Date__c != null &&
	        	q.Shipment_Type__c != null && q.Shipment_Type__c != '';
	        	
	    OutReportRequiredFieldsSpecified = q.OB_Origination_State__c != null && q.OB_Origination_State__c != '' && 
	        	q.OB_Destination_State__c != null && q.OB_Destination_State__c != '' &&
	        	q.OB_Pickup_Date__c != null && q.OB_Delivery_Date__c != null &&
	        	q.OB_Shipment_Type__c != null && q.OB_Shipment_Type__c != '';
    }
    
    public static boolean CreateInboundReportPreInvoke(id quoteId, Quote__c qte, Freight_Item__c[] fItems, LogisticsQuoteReportService.BasicHttpEndpoint_IDLSReport reportProxy)
    {
    	boolean RetVal = true;
    	
        ExQuote = new LogisticsQuoteReportService.ExternalQuote();
        ArrExQuoteLines = new LogisticsQuoteReportService.ArrayOfExternalQuoteLine();
                
        RetVal = LogisticsQuoteObjectMapper.mapInboundQuoteToExternalQuote(qte, fItems, ExQuote, ArrExQuoteLines);
                
        reportProxy.timeout_x = 60000;
        reportProxy.clientCertName_x = 'GES';
		//reportProxy.clientCert_x = LogisticsQuoteObjectMapper.certificate;
		//reportProxy.clientCertPasswd_x = LogisticsQuoteObjectMapper.password;
		
		return RetVal;
    } 
    
    public static Blob CreateInboundReport(LogisticsQuoteReportService.BasicHttpEndpoint_IDLSReport reportProxy, LogisticsQuoteReportService.ExternalQuote externalQuote)
    {
    	return EncodingUtil.base64Decode(reportProxy.Get(externalQuote));
    }
    
	public static void SaveInboundDLSReport(Id quoteId, Blob report)
	{
        if(report != null)
        {  
            integer Version = 0;

            Attachment[] existingAttachments = [Select Id, Name, CreatedDate From Attachment Where ParentID = :quoteId And Name Like :q.Name + '_DLS%_v%.xlsx' Order By CreatedDate Desc];
            
            try
            {
	            for(Attachment existingAttachment : existingAttachments)
	            {
	                integer verStartPos = existingAttachment.Name.lastIndexOf('_');
	                integer verEndPos = existingAttachment.Name.lastIndexOf('.');
	                
	                if (verStartPos > -1 && verEndPos > -1)
	                {
	                    Version = Integer.valueOf(existingAttachment.Name.subString(verStartPos+2,verEndPos));
	                }
	                break;
	            }
            }
            finally
            {
            	existingAttachments = null;
            }
            
            string inboundReportName = q.Name + '_DLS_Inbound_v' + (Version + 1)+ '.xlsx';
                        
            Attachment attach = new Attachment();
            
            try
            {  
	            attach.Body= report;
	            attach.Name= inboundReportName ;
	            attach.ContentType= 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';  
	            attach.ParentID = quoteId;  
	
	            insert(attach);
            }
            finally
            {
            	attach = null;
            }

        }		
	}    
    
    public static boolean CreateOutboundReportPreInvoke(id quoteId, Quote__c qte, Freight_Item__c[] fItems, LogisticsQuoteReportService.BasicHttpEndpoint_IDLSReport reportProxy)
    {
    	boolean RetVal = true;
    	
        ExQuote = new LogisticsQuoteReportService.ExternalQuote();
        ArrExQuoteLines = new LogisticsQuoteReportService.ArrayOfExternalQuoteLine();
                
        RetVal = LogisticsQuoteObjectMapper.mapOutboundQuoteToExternalQuote(qte, fItems, ExQuote, ArrExQuoteLines);
                
        reportProxy.timeout_x = 60000;
        reportProxy.clientCertName_x = 'GES';
		//reportProxy.clientCert_x = LogisticsQuoteObjectMapper.certificate;
		//reportProxy.clientCertPasswd_x = LogisticsQuoteObjectMapper.password;
		
		return RetVal;
    } 

    public static Blob CreateOutboundReport(LogisticsQuoteReportService.BasicHttpEndpoint_IDLSReport reportProxy, LogisticsQuoteReportService.ExternalQuote externalQuote)
    {
    	return EncodingUtil.base64Decode(reportProxy.Get(externalQuote));
    }
    
    public static void SaveOutboundDLSReport(Id quoteId, Blob report)
    {
        if(report != null)
        {  
            integer Version = 0;

            Attachment[] existingAttachments = [Select Id, Name, CreatedDate From Attachment Where ParentID = :quoteId And Name Like :q.Name + 'A_DLS%_v%.xlsx' Order By CreatedDate Desc];
            
            try
            {
	            for(Attachment existingAttachment : existingAttachments)
	            {
	                integer verStartPos = existingAttachment.Name.lastIndexOf('_');
	                integer verEndPos = existingAttachment.Name.lastIndexOf('.');
	                
	                if (verStartPos > -1 && verEndPos > -1)
	                {
	                    Version = Integer.valueOf(existingAttachment.Name.subString(verStartPos+2,verEndPos));
	                }
	                break;
	            }
            }
            finally
            {
            	existingAttachments = null;
            }
            
            string OutboundReportName = q.Name + 'A_DLS_Outbound_v' + (Version + 1)+ '.xlsx';
                        
            Attachment attach=new Attachment();
            
            try
            {
	            attach.Body= report ;
	            attach.Name= OutboundReportName ;
	            attach.ContentType= 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';  
	            attach.ParentID = quoteId;  
	
	            insert(attach);
            }
            finally
            {
            	attach = null;
            }
        } 
    }
    */
}