unpackaged/main/default/objects/Case/fields/Booth__c.field-meta.xml
<CustomField>
    <fullName>Booth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booth on which user requested service</description>
    <label>Booth (Lookup)</label>
    <referenceTo>Oracle_Show_Booth__c</referenceTo>
    <relationshipLabel>Customer Service Inquiries (Cases)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/CORE_SQR_ID__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_ID__c</fullName>
    <description>CORE SQR ID</description>
    <label>CORE SQR ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/CORE_SQR_Last_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_Last_Sent_Date__c</fullName>
    <description>Send to CORE SQR Date</description>
    <label>CORE SQR Last Sent Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/GES_Type__c.field-meta.xml
<CustomField>
    <fullName>GES_Type__c</fullName>
    <description>!!! To keep SFDC in sync with Oracle, we need to have the CasetoSQRMapping completed as part of that process so that when the case are sent to Oracle, the data is aligned to the requirements in Oracle. Reach out to Bhargavi or Robynn Coulter if you need to add an additional type.!!!  Values constrained by Show Status field selection.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Show_Status__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Any/All Services</fullName>
            </value>
            <value>
                <fullName>Audio Visual</fullName>
            </value>
            <value>
                <fullName>Billing Error/Dispute</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Carpet/Flooring Inquiry</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Complaint - Other</fullName>
            </value>
            <value>
                <fullName>Complaint - Rude Staff</fullName>
            </value>
            <value>
                <fullName>Compliment</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Documentation Request</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Exhibitor List</fullName>
            </value>
            <value>
                <fullName>Floor-Covering</fullName>
            </value>
            <value>
                <fullName>Furnishings</fullName>
            </value>
            <value>
                <fullName>General Event Enquiry/Other</fullName>
            </value>
            <value>
                <fullName>Ghost Call</fullName>
            </value>
            <value>
                <fullName>Graphics</fullName>
            </value>
            <value>
                <fullName>Insurance Requests (New Type to Create)</fullName>
                <label>Insurance Requests</label>
            </value>
            <value>
                <fullName>Invoice/Order Confirmation Explanation</fullName>
            </value>
            <value>
                <fullName>Invoice Request</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Lead Generation</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Logistics/Freight</fullName>
            </value>
            <value>
                <fullName>Logistics Lead</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>MultiService</fullName>
            </value>
            <value>
                <fullName>Nameboards</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/CaseToSQRSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CaseToSQR Setting</description>
    <label>CaseToSQR Setting</label>
</CustomObject>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/ApplicationID__c.field-meta.xml
<CustomField>
    <fullName>ApplicationID__c</fullName>
    <description>ApplicationID for Case to SQR Webservice Authentication</description>
    <label>ApplicationID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/ApplicationKey__c.field-meta.xml
<CustomField>
    <fullName>ApplicationKey__c</fullName>
    <description>ApplicationKey for Case to SQR Webservice Authentication</description>
    <label>ApplicationKey</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/Authentication_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>Authentication_EndPoint__c</fullName>
    <description>Case to SQR Webservice Authentication End Point</description>
    <label>Authentication EndPoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/Client_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>Client_EndPoint__c</fullName>
    <description>Case to SQR Webservice Client End Point</description>
    <label>Client EndPoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>Case to SQR Webservice End Point</description>
    <label>EndPoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password for Case to SQR Webservice Authentication</description>
    <label>Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username for Case to SQR Webservice Authentication</description>
    <label>Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_SQR__c/Core_SQR__c.object-meta.xml
<CustomObject>
    <label>Core SQR</label>
    <nameField>
        <label>Core SQR Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Core SQRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_SQR__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Core SQRs</relationshipLabel>
    <relationshipName>Core_SQRs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_SQR__c/fields/CORE_SQR_Last_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_Last_Sent_Date__c</fullName>
    <label>CORE SQR Last Sent Date Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Core_SQR__c/fields/GES_Type__c.field-meta.xml
<CustomField>
    <fullName>GES_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Any/All Services</fullName>
            </value>
            <value>
                <fullName>Audio Visual</fullName>
            </value>
            <value>
                <fullName>Billing Error/Dispute</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Carpet/Flooring Inquiry</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Complaint - Other</fullName>
            </value>
            <value>
                <fullName>Complaint - Rude Staff</fullName>
            </value>
            <value>
                <fullName>Compliment</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Documentation Request</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Exhibitor List</fullName>
            </value>
            <value>
                <fullName>Floor-Covering</fullName>
            </value>
            <value>
                <fullName>Furnishings</fullName>
            </value>
            <value>
                <fullName>General Event Enquiry/Other</fullName>
            </value>
            <value>
                <fullName>Ghost Call</fullName>
            </value>
            <value>
                <fullName>Graphics</fullName>
            </value>
            <value>
                <fullName>Insurance Requests (New Type to Create)</fullName>
            </value>
            <value>
                <fullName>Invoice/Order Confirmation Explanation</fullName>
            </value>
            <value>
                <fullName>Invoice Request</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Lead Generation</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Logistics/Freight</fullName>
            </value>
            <value>
                <fullName>Logistics Lead</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>MultiService</fullName>
            </value>
            <value>
                <fullName>Nameboards</fullName>
            </value>
            <value>
                <fullName>NL - Advance Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/Oracle_Show_Booth__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booths from Oracle</description>
    <label>Booth</label>
    <nameField>
        <label>Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booths</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SQRServiceClient_Test.cls
@isTest
public class SQRServiceClient_Test
{
    static Testmethod void SQRServiceClient1()
    {
        Account acc = TestDataUtil.CreateTestFacility(); 
        Account acc1 = TestDataUtil.CreateTestFirm(); 
        Contact con = TestDataUtil.CreateTestContact(acc1.Id);
        Show__c show = TestDataUtil.CreateTestShow(acc1.id);
        
        Test.startTest();
        Opportunity opp = TestDataUtil.CreateTestSalesRepOpp(acc.Id, acc1.Id, show.Id);
        Oracle_Show_Booth__c booth = TestDataUtil.CreateTestBooth(acc1.Id, opp.id, '1111', show.Id);
        Test.stopTest();
        
        CaseToSQRSetting__c ct = new CaseToSQRSetting__c();
        ct.Name = 'CaseToSQR Webservice Authentication';
        ct.ApplicationID__c = 'SalesForce';
        ct.ApplicationKey__c =  '76v.H-_7};9^+4(]J.;3';
        ct.Authentication_EndPoint__c =  'https://qaapi.viad.com/Security/v2/AuthenticationService.svc';
        ct.Client_EndPoint__c =  '';
        ct.EndPoint__c =  'http://qaapi.viad.com/GES/v2/SqrService.svc';
        ct.Password__c =  'coresqr';
        ct.Username__c =  'welcome#123';
        insert ct;
        
        Test.setMock(WebServiceMock.class, new SQRServiceClientMockImpl());
        Case c = new Case();
        c.Subject = 'sub';
        c.Booth__c = booth.Id;
        insert c;
        
        CaseComment cc = new CaseComment();
        cc.parentId = c.Id;
        cc.commentbody = 'test';
        insert cc;
        
        SQRServiceClient.submitCaseSQRs(c.Id);  
    }   
    static Testmethod void SQRServiceClient2()
    {
        Account acc = TestDataUtil.CreateTestFacility(); 
        Account acc1 = TestDataUtil.CreateTestFirm(); 
        Contact con = TestDataUtil.CreateTestContact(acc1.Id);
        Show__c show = TestDataUtil.CreateTestShow(acc1.id);
        
        Test.startTest();
        Opportunity opp = TestDataUtil.CreateTestSalesRepOpp(acc.Id, acc1.Id, show.Id);
        Oracle_Show_Booth__c booth = TestDataUtil.CreateTestBooth(acc1.Id, opp.id, '1111', show.Id);
        Test.stopTest();
        
        CaseToSQRSetting__c ct = new CaseToSQRSetting__c();
        ct.Name = 'CaseToSQR Webservice Authentication';
        ct.ApplicationID__c = 'SalesForce';
        ct.ApplicationKey__c =  '76v.H-_7};9^+4(]J.;3';
        ct.Authentication_EndPoint__c =  'https://qaapi.viad.com/Security/v2/AuthenticationService.svc';
        ct.Client_EndPoint__c =  '';
        ct.EndPoint__c =  'http://qaapi.viad.com/GES/v2/SqrService.svc';
        ct.Password__c =  'coresqr';
        ct.Username__c =  'welcome#123';
        insert ct;
        
        Test.setMock(WebServiceMock.class, new SQRServiceClientMockImpl());
        Case c = new Case();
        c.Subject = 'sub';
        c.Booth__c = booth.Id;
        c.CORE_SQR_ID__c = '1';
        c.CORE_SQR_Last_Sent_Date__c = system.now();
        insert c;
        
        CaseComment cc = new CaseComment();
        cc.parentId = c.Id;
        cc.commentbody = 'test';
        insert cc;
        
        SQRServiceClient.submitCaseSQRs(c.Id);   
    } 
      
    static Testmethod void SQRServiceClient3()
    {
        Account acc = TestDataUtil.CreateTestFacility(); 
        Account acc1 = TestDataUtil.CreateTestFirm(); 
        Contact con = TestDataUtil.CreateTestContact(acc1.Id);
        Show__c show = TestDataUtil.CreateTestShow(acc1.id);
        User u = GC_TestUtils.createUser('System Administrator', 'Twilio', 'Integration');
        
        Test.startTest();
        Opportunity opp = TestDataUtil.CreateTestSalesRepOpp(acc.Id, acc1.Id, show.Id);
        Oracle_Show_Booth__c booth = TestDataUtil.CreateTestBooth(acc1.Id, opp.id, '1111', show.Id);
        Test.stopTest();
        
        CaseToSQRSetting__c ct = new CaseToSQRSetting__c();
        ct.Name = 'CaseToSQR Webservice Authentication';
        ct.ApplicationID__c = 'SalesForce';
        ct.ApplicationKey__c =  '76v.H-_7};9^+4(]J.;3';
        ct.Authentication_EndPoint__c =  'https://qaapi.viad.com/Security/v2/AuthenticationService.svc';
        ct.Client_EndPoint__c =  '';
        ct.EndPoint__c =  'http://qaapi.viad.com/GES/v2/SqrService.svc';
        ct.Password__c =  'coresqr';
        ct.Username__c =  'welcome#123';
        insert ct;
        
        Test.setMock(WebServiceMock.class, new SQRServiceClientMockImpl());
        List<Case> listCase = new List<Case>();
        
        System.runAs(u) {
            Case c1 = new Case();
            c1.Subject = 'sub';
            c1.Booth__c = booth.Id;
            c1.CORE_SQR_ID__c = '1';
            c1.ContactId = con.Id;
            c1.GES_Type__c = 'Labor';
            listCase.add(c1);
            
            insert listCase;
            
            CaseComment cc1 = new CaseComment();
            cc1.parentId = c1.Id;
            cc1.commentbody = 'test';
            insert cc1;
        }
        SQRServiceClient.submitCaseSQRs(listCase[0].Id);
    }
    
    static Testmethod void SQRServiceClient4()
    {
        Account acc = TestDataUtil.CreateTestFacility(); 
        Account acc1 = TestDataUtil.CreateTestFirm(); 
        Contact con = TestDataUtil.CreateTestContact(acc1.Id);
        Show__c show = TestDataUtil.CreateTestShow(acc1.id);
        User u = GC_TestUtils.createUser('System Administrator', 'Twilio', 'Integration');
        
        Test.startTest();
        Opportunity opp = TestDataUtil.CreateTestSalesRepOpp(acc.Id, acc1.Id, show.Id);
        Oracle_Show_Booth__c booth = TestDataUtil.CreateTestBooth(acc1.Id, opp.id, '1111', show.Id);
        Test.stopTest();
        
        CaseToSQRSetting__c ct = new CaseToSQRSetting__c();
        ct.Name = 'CaseToSQR Webservice Authentication';
        ct.ApplicationID__c = 'SalesForce';
        ct.ApplicationKey__c =  '76v.H-_7};9^+4(]J.;3';
        ct.Authentication_EndPoint__c =  'https://qaapi.viad.com/Security/v2/AuthenticationService.svc';
        ct.Client_EndPoint__c =  '';
        ct.EndPoint__c =  'http://qaapi.viad.com/GES/v2/SqrService.svc';
        ct.Password__c =  'coresqr';
        ct.Username__c =  'welcome#123';
        insert ct;
        
        Test.setMock(WebServiceMock.class, new SQRServiceClientMockImpl());
        List<Case> listCase = new List<Case>();
        
        System.runAs(u) {
            Case c1 = new Case();
            c1.Subject = 'sub';
            c1.Booth__c = booth.Id;
            c1.CORE_SQR_ID__c = '1';
            c1.ContactId = con.Id;
            c1.GES_Type__c = 'Labor';
            listCase.add(c1);
            
            insert listCase;
            
            List<Core_SQR__c> listCaseSQR = new List<Core_SQR__c>();
            Core_SQR__c cSQR2 = new Core_SQR__c();
            cSQR2.Name = '122345565';
            cSQR2.GES_Type__c = 'Labor';
            cSQR2.Case__c = c1.Id;
            listCaseSQR.add(cSQR2);
            
            insert listCaseSQR;
            
            CaseComment cc1 = new CaseComment();
            cc1.parentId = c1.Id;
            cc1.commentbody = 'test';
            insert cc1;
        }
        SQRServiceClient.submitCaseSQRs(listCase[0].Id);
    }
    
    
}