unpackaged/main/default/objects/Case/fields/Booth__c.field-meta.xml
<CustomField>
    <fullName>Booth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booth on which user requested service</description>
    <label>Booth (Lookup)</label>
    <referenceTo>Oracle_Show_Booth__c</referenceTo>
    <relationshipLabel>Customer Service Inquiries (Cases)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/CORE_SQR_Last_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_Last_Sent_Date__c</fullName>
    <description>Send to CORE SQR Date</description>
    <label>CORE SQR Last Sent Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/GES_Type__c.field-meta.xml
<CustomField>
    <fullName>GES_Type__c</fullName>
    <description>!!! To keep SFDC in sync with Oracle, we need to have the CasetoSQRMapping completed as part of that process so that when the case are sent to Oracle, the data is aligned to the requirements in Oracle. Reach out to Bhargavi or Robynn Coulter if you need to add an additional type.!!!  Values constrained by Show Status field selection.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Show_Status__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Any/All Services</fullName>
            </value>
            <value>
                <fullName>Audio Visual</fullName>
            </value>
            <value>
                <fullName>Billing Error/Dispute</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Carpet/Flooring Inquiry</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Complaint - Other</fullName>
            </value>
            <value>
                <fullName>Complaint - Rude Staff</fullName>
            </value>
            <value>
                <fullName>Compliment</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Documentation Request</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Exhibitor List</fullName>
            </value>
            <value>
                <fullName>Floor-Covering</fullName>
            </value>
            <value>
                <fullName>Furnishings</fullName>
            </value>
            <value>
                <fullName>General Event Enquiry/Other</fullName>
            </value>
            <value>
                <fullName>Ghost Call</fullName>
            </value>
            <value>
                <fullName>Graphics</fullName>
            </value>
            <value>
                <fullName>Insurance Requests (New Type to Create)</fullName>
                <label>Insurance Requests</label>
            </value>
            <value>
                <fullName>Invoice/Order Confirmation Explanation</fullName>
            </value>
            <value>
                <fullName>Invoice Request</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Lead Generation</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Logistics/Freight</fullName>
            </value>
            <value>
                <fullName>Logistics Lead</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>MultiService</fullName>
            </value>
            <value>
                <fullName>Nameboards</fullName>
            </value>
            <value>
                <fullName>Twilio Automatic Case Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRMapping__mdt/CaseToSQRMapping__mdt.object-meta.xml
<CustomObject>
    <description>Case To CORE SQR Mapping</description>
    <label>CaseToSQRMapping</label>
    <pluralLabel>CaseToSQRMappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/CaseToSQRMapping__mdt/fields/CORE_SQR_Cause__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_Cause__c</fullName>
    <description>CORE SQR Cause</description>
    <label>CORE SQR Cause</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRMapping__mdt/fields/CORE_SQR_Cause_Code__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_Cause_Code__c</fullName>
    <description>CORE SQR Cause Code</description>
    <label>CORE SQR Cause Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRMapping__mdt/fields/CORE_SQR_LOB__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_LOB__c</fullName>
    <description>CORE SQR LOB</description>
    <label>CORE SQR LOB</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRMapping__mdt/fields/CORE_SQR_LOB_Code__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_LOB_Code__c</fullName>
    <description>CORE SQR LOB Code</description>
    <label>CORE SQR LOB Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRMapping__mdt/fields/CORE_SQR_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_Order_Type__c</fullName>
    <description>CORE SQR Order Type</description>
    <label>CORE SQR Order Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRMapping__mdt/fields/CORE_SQR_Order_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_Order_Type_Code__c</fullName>
    <description>CORE SQR Order Type Code</description>
    <label>CORE SQR Order Type Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRMapping__mdt/fields/CORE_SQR_Service_Category__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_Service_Category__c</fullName>
    <description>CORE SQR Service Category</description>
    <label>CORE SQR Service Category</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRMapping__mdt/fields/CORE_SQR_Service_Category_Code__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_Service_Category_Code__c</fullName>
    <description>CORE SQR Service Category Code</description>
    <label>CORE SQR Service Category Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRMapping__mdt/fields/SF_Show_Type__c.field-meta.xml
<CustomField>
    <fullName>SF_Show_Type__c</fullName>
    <description>SF Show Type</description>
    <label>SF Show Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/CaseToSQRSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CaseToSQR Setting</description>
    <label>CaseToSQR Setting</label>
</CustomObject>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/ApplicationID__c.field-meta.xml
<CustomField>
    <fullName>ApplicationID__c</fullName>
    <description>ApplicationID for Case to SQR Webservice Authentication</description>
    <label>ApplicationID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/ApplicationKey__c.field-meta.xml
<CustomField>
    <fullName>ApplicationKey__c</fullName>
    <description>ApplicationKey for Case to SQR Webservice Authentication</description>
    <label>ApplicationKey</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/Authentication_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>Authentication_EndPoint__c</fullName>
    <description>Case to SQR Webservice Authentication End Point</description>
    <label>Authentication EndPoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/Client_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>Client_EndPoint__c</fullName>
    <description>Case to SQR Webservice Client End Point</description>
    <label>Client EndPoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password for Case to SQR Webservice Authentication</description>
    <label>Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CaseToSQRSetting__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username for Case to SQR Webservice Authentication</description>
    <label>Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_SQR__c/Core_SQR__c.object-meta.xml
<CustomObject>
    <label>Core SQR</label>
    <nameField>
        <label>Core SQR Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Core SQRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_SQR__c/fields/CORE_SQR_Last_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>CORE_SQR_Last_Sent_Date__c</fullName>
    <label>CORE SQR Last Sent Date Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Core_SQR__c/fields/GES_Type__c.field-meta.xml
<CustomField>
    <fullName>GES_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Any/All Services</fullName>
            </value>
            <value>
                <fullName>Audio Visual</fullName>
            </value>
            <value>
                <fullName>Billing Error/Dispute</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Carpet/Flooring Inquiry</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Complaint - Other</fullName>
            </value>
            <value>
                <fullName>Complaint - Rude Staff</fullName>
            </value>
            <value>
                <fullName>Compliment</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Documentation Request</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Exhibitor List</fullName>
            </value>
            <value>
                <fullName>Floor-Covering</fullName>
            </value>
            <value>
                <fullName>Furnishings</fullName>
            </value>
            <value>
                <fullName>General Event Enquiry/Other</fullName>
            </value>
            <value>
                <fullName>Ghost Call</fullName>
            </value>
            <value>
                <fullName>Graphics</fullName>
            </value>
            <value>
                <fullName>Insurance Requests (New Type to Create)</fullName>
            </value>
            <value>
                <fullName>Invoice/Order Confirmation Explanation</fullName>
            </value>
            <value>
                <fullName>Invoice Request</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Lead Generation</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Logistics/Freight</fullName>
            </value>
            <value>
                <fullName>Logistics Lead</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>MultiService</fullName>
            </value>
            <value>
                <fullName>Nameboards</fullName>
            </value>
            <value>
                <fullName>NL - Advance Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/Oracle_Show_Booth__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booths from Oracle</description>
    <label>Booth</label>
    <nameField>
        <label>Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booths</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/BOOTH_ID__c.field-meta.xml
<CustomField>
    <fullName>BOOTH_ID__c</fullName>
    <description>Unique ID of Oracle Booth record</description>
    <label>BOOTH_ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SQRServiceClient.cls
public class SQRServiceClient {
    public static Boolean SQRInvoked = false;
    @future(callout=true)
    public static void submitCaseSQRs(Id caseId){
        
        String Comments; 
        DateTime dt = System.now();
        String currentCaseId='';
        
        try{
            CaseToSQRSetting__c CaseToSQRSetting = CaseToSQRSetting__c.getValues('CaseToSQR Webservice Authentication');  //  get values from custom setting 
            
            String loginName= CaseToSQRSetting != null ? CaseToSQRSetting.Username__c : '';  
            String password= CaseToSQRSetting != null ? CaseToSQRSetting.Password__c : '';
            String ApplicationID= CaseToSQRSetting != null ? CaseToSQRSetting.ApplicationID__c : '';
            string ApplicationKey= CaseToSQRSetting != null ? CaseToSQRSetting.ApplicationKey__c : '';
            
            String appSessionId;
            if(!Test.isRunningTest()){
                wwwViadComSecurityV2.BasicHttpBinding_IAuthenticationService authClient=new wwwViadComSecurityV2.BasicHttpBinding_IAuthenticationService();
                authClient.endpoint_x= CaseToSQRSetting != null ? CaseToSQRSetting.Authentication_EndPoint__c : '';
                
                wwwViadComSecurityV2.AppSessionInfo authResponse=authClient.StartAppSession(applicationID,applicationKey,null,null);
                appSessionId=authResponse.SessionID;
                
                system.debug('sessionid=='+authResponse.SessionID);
                system.debug('Expiration==='+authResponse.Expiration);
                
                wwwViadComSecurityV2.AppSessionInfo loginResponse =authClient.UserLogin(appSessionId,loginName,password,null);
                
                system.debug('sessionid=='+loginResponse.SessionID);
                system.debug('Expiration==='+authResponse.Expiration);
            }
            
            //The Type found in the SFDC Case Detail section will be used to determine the additional field values for Oracle SQR – Category, Order Type, LOB & Cause.
            
            Map<String,CaseToSQRMapping__mdt> mCaseToSQRMapping=new Map<String,CaseToSQRMapping__mdt>();
            for (CaseToSQRMapping__mdt mapping:[SELECT SF_Show_Type__c ,CORE_SQR_Cause__c ,CORE_SQR_Cause_Code__c ,
                                                CORE_SQR_LOB__c,CORE_SQR_LOB_Code__c,CORE_SQR_Order_Type__c ,CORE_SQR_Order_Type_Code__c ,
                                                CORE_SQR_Service_Category__c,CORE_SQR_Service_Category_Code__c  FROM CaseToSQRMapping__mdt]){
                                                    mCaseToSQRMapping.put(mapping.SF_Show_Type__c, mapping);
                                                }
            
            wwwViadComV2_SQR.BasicHttpBinding_ISqrService client=new wwwViadComV2_SQR.BasicHttpBinding_ISqrService();
            client.endpoint_x= CaseToSQRSetting != null ? CaseToSQRSetting.Client_EndPoint__c : '';
            
            Case existingsqr = [Select CORE_SQR_Last_Sent_Date__c from Case Where Id = :caseId];
            List <Case> CaseRecords = new List<Case>();
            
            if (existingsqr.CORE_SQR_Last_Sent_Date__c != null) {
                CaseRecords =  [select Id, CaseNumber, Booth__r.BOOTH_ID__c, ContactEmail, ContactPhone, Contact.Name, Show_Name__r.Name, Account.Name, GES_Type__c, CORE_SQR_ID__c, CreatedBy.Name, ContactId,
                                Reason__c, Origin, Refund_Adj_Amount__c, Refund_Adj_Reason_Code__c, Resolution__c, Credit_Memo_Code__c, Status, Send_CORE_SQR_Status__c, CORE_SQR_Last_Sent_Date__c, (select CommentBody, CreatedBy.Name from CaseComments where lastmodifieddate > :existingsqr.CORE_SQR_Last_Sent_Date__c order by CreatedDate), (select id, Name,GES_Type__c,CORE_SQR_Last_Sent_Date__c from Core_SQRs__r) 
                                from Case Where Id = :caseId];
            }
            else {
                CaseRecords =  [select Id, CaseNumber, Booth__r.BOOTH_ID__c, ContactEmail, ContactPhone, Contact.Name, Show_Name__r.Name, Account.Name, GES_Type__c, CORE_SQR_ID__c, CreatedBy.Name, ContactId,
                                Reason__c, Origin, Refund_Adj_Amount__c, Refund_Adj_Reason_Code__c, Resolution__c, Credit_Memo_Code__c, Status, Send_CORE_SQR_Status__c, CORE_SQR_Last_Sent_Date__c, (select CommentBody, CreatedBy.Name from CaseComments order by CreatedDate), (select id, Name,GES_Type__c,CORE_SQR_Last_Sent_Date__c from Core_SQRs__r)  
                                from Case Where Id = :caseId];    
            }
            
            if(!CaseRecords.isEmpty()){
                
                for(Case oCase: CaseRecords){
                    
                    CaseToSQRMapping__mdt mapping = mCaseToSQRMapping.containsKey(oCase.GES_Type__c)?mCaseToSQRMapping.get(oCase.GES_Type__c):null;
                    Integer boothId = oCase.Booth__r.BOOTH_ID__c!=null?Integer.valueOf(oCase.Booth__r.BOOTH_ID__c):null;
                    
                    system.debug('CaseId==='+oCase.Id);
                    system.debug('boothId==='+boothId);
                    system.debug('ContactEmail==='+oCase.ContactEmail);
                    
                    // Twilio Case
                    if(oCase.CreatedBy.Name == 'Twilio Integration' && oCase.ContactId != null){
                        Map<String, Core_SQR__c> mapTypeToCoreSQR = new Map<String, Core_SQR__c>();
                        for(Core_SQR__c cSQR : oCase.Core_SQRs__r){
                            mapTypeToCoreSQR.put(cSQR.GES_Type__c, cSQR);
                        }
                        
                        if(oCase.GES_Type__c != '' && oCase.GES_Type__c != 'Twilio Automatic Case Closure'){
                            if(!mapTypeToCoreSQR.isEmpty() && mapTypeToCoreSQR.containsKey(oCase.GES_Type__c)){
                                Core_SQR__c existingCoreSQR = mapTypeToCoreSQR.get(oCase.GES_Type__c);
                                if(existingCoreSQR != null && existingCoreSQR.Name != null){
                                    wwwViadComDataV2_SQR.SqrUpdateRequest sqrInfo = updateSQR(oCase, mapping, boothId, comments);
                                    sqrInfo.SqrHeaderId= Integer.valueOf(existingCoreSQR.Name);
                                    Integer responseCode;
                                    if(!Test.isRunningTest())
                                        responseCode = client.UpdateSqr(appSessionId,sqrInfo);   
                                    else
                                        responseCode = 1;
                                    
                                    system.debug('Response Code ==='+responseCode);
                                    existingCoreSQR.CORE_SQR_Last_Sent_Date__c = dt;
                                    Update existingCoreSQR;
                                }else{
                                    wwwViadComDataV2_SQR.SqrCreateRequest sqrInfo = createSQR(oCase, mapping, boothId, comments);
                                    Integer responseCode;
                                    if(!Test.isRunningTest())
                                        responseCode=client.SubmitSqr(appSessionId,sqrInfo);
                                    else
                                        responseCode = 1;
                                    
                                    Core_SQR__c coreSQR = new Core_SQR__c();
                                    coreSQR.Name = String.valueOf(+responseCode);
                                    coreSQR.CORE_SQR_Last_Sent_Date__c = dt;
                                    coreSQR.Case__c = oCase.Id;
                                    coreSQR.GES_Type__c = oCase.GES_Type__c;
                                    
                                    insert coreSQR;
                                }
                            }else{
                                wwwViadComDataV2_SQR.SqrCreateRequest sqrInfo = createSQR(oCase, mapping, boothId, comments);
                                Integer responseCode;
                                if(!Test.isRunningTest())
                                    responseCode=client.SubmitSqr(appSessionId,sqrInfo);
                                else
                                    responseCode = 1;
                                
                                Core_SQR__c coreSQR = new Core_SQR__c();
                                coreSQR.Name = String.valueOf(+responseCode);
                                coreSQR.CORE_SQR_Last_Sent_Date__c = dt;
                                coreSQR.Case__c = oCase.Id;
                                coreSQR.GES_Type__c = oCase.GES_Type__c;
                                
                                insert coreSQR;
                            }
                        }
                    }else{
                        if (oCase.CORE_SQR_ID__c == null){
                            wwwViadComDataV2_SQR.SqrCreateRequest sqrInfo = createSQR(oCase, mapping, boothId, comments);
                            Integer responseCode;
                            if(!Test.isRunningTest())
                                responseCode=client.SubmitSqr(appSessionId,sqrInfo);
                            else
                                responseCode = 1;
                            
                            oCase.CORE_SQR_ID__c = String.valueOf(+responseCode);
                            oCase.CORE_SQR_Last_Sent_Date__c = dt;
                            
                            Update oCase;                       
                        }
                        else{
                            wwwViadComDataV2_SQR.SqrUpdateRequest sqrInfo = updateSQR(oCase, mapping, boothId, comments);
                            sqrInfo.SqrHeaderId= Integer.valueOf(oCase.CORE_SQR_ID__c);
                            Integer responseCode;
                            if(!Test.isRunningTest())
                                responseCode = client.UpdateSqr(appSessionId,sqrInfo);   
                            else
                                responseCode = 1;
                            
                            system.debug('Response Code ==='+responseCode);
                            oCase.CORE_SQR_Last_Sent_Date__c = dt;
                            currentCaseId=oCase.id;
                            Update oCase;
                        }
                    }
                }
            }
            
        }
        catch(Exception e){
            
            /*Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
String[] toAddresses = new String[] {'snair@ges.com','rsinha@ges.com'};
mail.setToAddresses(toAddresses);
mail.setReplyTo('snair@ges.com');
mail.setSenderDisplayName('Apex error message');
mail.setSubject('Error from Org&nbsp;: ' + UserInfo.getOrganizationName());
mail.setPlainTextBody(e.getMessage()+'case Id='+currentCaseId+'user='+UserInfo.getUserId());
Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });*/
            System.debug(e);
        }   
    }
    
    public static wwwViadComDataV2_SQR.SqrCreateRequest createSQR(Case oCase, CaseToSQRMapping__mdt mapping, Integer boothId, String comments){
        for(CaseComment comm : oCase.CaseComments){
            comments=comm.CreatedBy.Name + ': ' + comm.CommentBody + ' \r\n' + (comments != NULL ? comments : '');  
        }
        
        wwwViadComDataV2_SQR.SqrCreateRequest sqrInfo=new wwwViadComDataV2_SQR.SqrCreateRequest();
        
        sqrInfo.ContactEmail=oCase.ContactEmail;
        sqrInfo.ContactName=oCase.Contact.Name;
        sqrInfo.ContactPhone=oCase.ContactPhone;
        sqrInfo.CustomerBoothId=boothId;
        sqrInfo.Description=oCase.CaseNumber +' - '+ oCase.GES_Type__c +' - '+ oCase.Reason__c;
        sqrInfo.LineOfBusiness = mapping != null ? mapping.CORE_SQR_LOB_Code__c : null; 
        sqrInfo.OrderType= mapping != null ? mapping.CORE_SQR_Order_Type_Code__c : null;
        sqrInfo.Priority='L'; //Low
        sqrInfo.ServiceCategory=mapping !=null ? mapping.CORE_SQR_Service_Category_Code__c : null;
        sqrInfo.Cause= mapping != null ? mapping.CORE_SQR_Cause_Code__c : null;
        sqrInfo.Source='N'; //National Servicenter
        if (oCase.Status == 'Closed') {
            sqrInfo.Status='C'; 
            oCase.Send_CORE_SQR_Status__c = 'Closed'; 
        }
        else if (oCase.Send_CORE_SQR_Status__c == 'In Process' && oCase.Status != 'Closed') {
            sqrInfo.Status='I'; 
        }
        else if (oCase.Send_CORE_SQR_Status__c == 'Closed') {
            sqrInfo.Status='C'; 
        }
        sqrInfo.Comments=(comments != NULL ? 'Case Comments: '+ comments : '') + ' \r\n' + (oCase.Origin != NULL ? 'Source: '+ oCase.Origin : '') + ' \r\n' + (oCase.Resolution__c != NULL ? 'Resolution: ' + oCase.Resolution__c : '') + ' \r\n' + (oCase.Refund_Adj_Amount__c != NULL ?  'Refund/Adj Amount: ' + oCase.Refund_Adj_Amount__c : 'Refund/Adj Amount: '+ 0) + ' \r\n' + (oCase.Refund_Adj_Reason_Code__c != NULL ? 'Adj Code: ' + oCase.Refund_Adj_Reason_Code__c : '') + ' \r\n' + (oCase.Credit_Memo_Code__c != NULL ? 'CM Code: ' + oCase.Credit_Memo_Code__c : '');   
        // adding the following code to remove the issue of string greater than the allowed limit
        if(sqrInfo.Comments.length()>2499){
            sqrInfo.Comments= sqrInfo.Comments.left(2499);
        }
        
        return sqrInfo;
    }
    
    public static wwwViadComDataV2_SQR.SqrUpdateRequest updateSQR(Case oCase, CaseToSQRMapping__mdt mapping, Integer boothId, String comments){
        for(CaseComment comm : oCase.CaseComments){
            comments=comm.CreatedBy.Name + ': ' + comm.CommentBody + ' \r\n' + (comments != NULL ? comments : '');  
        }  
        
        wwwViadComDataV2_SQR.SqrUpdateRequest sqrInfo=new wwwViadComDataV2_SQR.SqrUpdateRequest();
        
        sqrInfo.ContactEmail=oCase.ContactEmail;
        sqrInfo.ContactName=oCase.Contact.Name;
        sqrInfo.ContactPhone=oCase.ContactPhone;
        sqrInfo.Description=oCase.CaseNumber +' - '+ oCase.GES_Type__c +' - '+ oCase.Reason__c;
        sqrInfo.LineOfBusiness = mapping != null ? mapping.CORE_SQR_LOB_Code__c : null; 
        sqrInfo.OrderType= mapping != null ? mapping.CORE_SQR_Order_Type_Code__c : null;
        sqrInfo.Priority='L'; //Low
        sqrInfo.ServiceCategory=mapping !=null ? mapping.CORE_SQR_Service_Category_Code__c : null;
        sqrInfo.Cause= mapping != null ? mapping.CORE_SQR_Cause_Code__c : null;
        sqrInfo.Source='N'; //National Servicenter
        if (oCase.Status == 'Closed'){
            sqrInfo.Status='C'; 
            oCase.Send_CORE_SQR_Status__c = 'Closed'; 
        }
        else if (oCase.Send_CORE_SQR_Status__c == 'In Process' && oCase.Status != 'Closed') {
            sqrInfo.Status='I'; 
        }
        else if (oCase.Send_CORE_SQR_Status__c == 'Closed') {
            sqrInfo.Status='C'; 
        }
        sqrInfo.Comments=(comments != NULL ? 'Case Comments: '+ comments : '') + ' \r\n' + (oCase.Origin != NULL ? 'Source: '+ oCase.Origin : '') + ' \r\n' + (oCase.Resolution__c != NULL ? 'Resolution: ' + oCase.Resolution__c : '') + ' \r\n' + (oCase.Refund_Adj_Amount__c != NULL ?  'Refund/Adj Amount: ' + oCase.Refund_Adj_Amount__c : 'Refund/Adj Amount: '+ 0) + ' \r\n' + (oCase.Refund_Adj_Reason_Code__c != NULL ? 'Adj Code: ' + oCase.Refund_Adj_Reason_Code__c : '') + ' \r\n' + (oCase.Credit_Memo_Code__c != NULL ? 'CM Code: ' + oCase.Credit_Memo_Code__c : '');   
        //sqrInfo.SqrHeaderId= Integer.valueOf(oCase.CORE_SQR_ID__c);
        
        return sqrInfo;
    }
    
}