unpackaged/main/default/objects/Case/fields/Booth__c.field-meta.xml
<CustomField>
    <fullName>Booth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booth on which user requested service</description>
    <label>Booth (Lookup)</label>
    <referenceTo>Oracle_Show_Booth__c</referenceTo>
    <relationshipLabel>Customer Service Inquiries (Cases)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/GES_Type__c.field-meta.xml
<CustomField>
    <fullName>GES_Type__c</fullName>
    <description>!!! To keep SFDC in sync with Oracle, we need to have the CasetoSQRMapping completed as part of that process so that when the case are sent to Oracle, the data is aligned to the requirements in Oracle. Reach out to Bhargavi or Robynn Coulter if you need to add an additional type.!!!  Values constrained by Show Status field selection.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Show_Status__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Any/All Services</fullName>
            </value>
            <value>
                <fullName>Audio Visual</fullName>
            </value>
            <value>
                <fullName>Billing Error/Dispute</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Carpet/Flooring Inquiry</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Complaint - Other</fullName>
            </value>
            <value>
                <fullName>Complaint - Rude Staff</fullName>
            </value>
            <value>
                <fullName>Compliment</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Documentation Request</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Exhibitor List</fullName>
            </value>
            <value>
                <fullName>Floor-Covering</fullName>
            </value>
            <value>
                <fullName>Furnishings</fullName>
            </value>
            <value>
                <fullName>General Event Enquiry/Other</fullName>
            </value>
            <value>
                <fullName>Ghost Call</fullName>
            </value>
            <value>
                <fullName>Graphics</fullName>
            </value>
            <value>
                <fullName>Insurance Requests (New Type to Create)</fullName>
                <label>Insurance Requests</label>
            </value>
            <value>
                <fullName>Invoice/Order Confirmation Explanation</fullName>
            </value>
            <value>
                <fullName>Invoice Request</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Lead Generation</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Logistics/Freight</fullName>
            </value>
            <value>
                <fullName>Logistics Lead</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>MultiService</fullName>
            </value>
            <value>
                <fullName>Nameboards</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Send_CORE_SQR_Status__c.field-meta.xml
<CustomField>
    <fullName>Send_CORE_SQR_Status__c</fullName>
    <description>Send to CORE SQR Status</description>
    <label>Send CORE SQR Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Closed</fullName>
                <default>true</default>
                <label>Closed</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Show_Status__c.field-meta.xml
<CustomField>
    <fullName>Show_Status__c</fullName>
    <label>Show Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-Pre</fullName>
            </value>
            <value>
                <fullName>2-Showsite</fullName>
            </value>
            <value>
                <fullName>3-Post</fullName>
            </value>
            <value>
                <fullName>4-Non Tradeshow-N/A</fullName>
            </value>
            <value>
                <fullName>Pre-show</fullName>
            </value>
            <value>
                <fullName>Showsite (Build)</fullName>
            </value>
            <value>
                <fullName>Show Open</fullName>
            </value>
            <value>
                <fullName>Showsite (Breakdown)</fullName>
            </value>
            <value>
                <fullName>Post-show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/Oracle_Show_Booth__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booths from Oracle</description>
    <label>Booth</label>
    <nameField>
        <label>Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booths</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/BOOTH_ID__c.field-meta.xml
<CustomField>
    <fullName>BOOTH_ID__c</fullName>
    <description>Unique ID of Oracle Booth record</description>
    <label>BOOTH_ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CasetoSQR.cls
public class CasetoSQR 
{
    public Case CaseId { get; set; }
    public Case c { get; set; }
    
    public CasetoSQR(ApexPages.StandardController stdController) 
    {
        CaseId = (Case)stdController.getRecord(); 
        c = new case();
        c = [SELECT Id, GES_Type__c, Reason__c, Show_Status__c, Booth__r.BOOTH_ID__c, Send_CORE_SQR_Status__c FROM Case WHERE Id = :CaseId.Id];
        
        if(c.Booth__r.BOOTH_ID__c == null){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'CORE SQR cannot be created without a Booth. Please update the Booth and try again.'));          
        } 
    }  
    public PageReference save()
    {
        if(String.isBlank(c.Booth__r.BOOTH_ID__c))
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'CORE SQR cannot be created without a Booth. Please update the Booth and try again.')); 
            return null;         
        }
        
        if(String.isBlank(c.GES_Type__c))
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Type is mandatory.'));
            return null;
        }
        
        if(String.isBlank(c.Reason__c))
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Reason is mandatory.'));
            return null;
        }
        if(String.isBlank(c.Send_CORE_SQR_Status__c))
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Send CORE SQR Status is mandatory.'));
            return null;
        }
        
        try{
            SQRServiceClient.SQRInvoked = true;
            upsert c;
            SQRServiceClient.submitCaseSQRs(c.Id);  
        }catch(exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You do not have sufficient privileges to perform this operation. Please check with your System Administrator. To go back, press Cancel. For more details, please refer to the detailed error message here- '+e.getMessage()));
            return null;
        }
        PageReference pg = new PageReference('/'+c.Id);
        pg.setRedirect(true);
        return pg;
    } 
    public PageReference Cancel()
    {
        PageReference pg = new PageReference('/'+c.Id);
        pg.setRedirect(true);
        return pg;
    } 
}