unpackaged/main/default/objects/Case/fields/Show_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Show_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Show Opportunity/Project on which user requested service</description>
    <label>Show Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Customer Service Inquiries (Cases)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Show_Opportunity_Alert__c/Show_Opportunity_Alert__c.object-meta.xml
<CustomObject>
    <description>Show opportunity specific alert</description>
    <label>Show Opportunity Alert</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Opportunity Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Show_Opportunity_Alert__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Alert message</description>
    <label>Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show_Opportunity_Alert__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Show_Opportunity_Alert__c/fields/Show_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Show_Opportunity__c</fullName>
    <description>Show opportunity for the child alert</description>
    <label>Show Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Show Opportunity Alerts</relationshipLabel>
    <relationshipName>Show_Opportunity_Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/CCShowOpportunityAlertListController.cls
public with sharing class CCShowOpportunityAlertListController {
    
    private ApexPages.StandardController controller;
    private final Case c;
    private List<Show_Opportunity_Alert__c> loAlerts;
    private Integer alertCount = 0;
    
    public CCShowOpportunityAlertListController(ApexPages.StandardController stdController)
    {
        controller = stdController;
        this.c = (Case)stdController.getRecord();
        
        if (this.c != null && this.c.Id != null) {
        	
	        Case TheCase = [Select Id, Show_Opportunity__c From Case Where Id = :this.c.Id];
	    	
	    	loAlerts= new List<Show_Opportunity_Alert__c>();
	    	
	    	if (TheCase != null) {
		    	if (TheCase.Show_Opportunity__c != null)
		    	{
		    		loAlerts = [SELECT Id, Name, Message__c, LastModifiedDate FROM Show_Opportunity_Alert__c WHERE Show_Opportunity__c = :TheCase.Show_Opportunity__c And IsActive__c = True ORDER BY Order__c];
		    		this.alertCount = loAlerts.size();
		    	}
	    	}
        }
     
    }
    
    public List<Show_Opportunity_Alert__c> getShowOpportunityAlerts() {
        return loAlerts;
    }    
        
	public Boolean getAlertsAvailable()
	{
		return (this.alertCount > 0 ? true : false);
	}

}