unpackaged/main/default/objects/GC_GES_Connect2_Settings__c/GC_GES_Connect2_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>GES Connect2 Custom Settings to be used for the Application.</description>
    <label>GES Connect2 Settings</label>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Connect2_Settings__c/fields/API_ENDPOINT__c.field-meta.xml
<CustomField>
    <fullName>API_ENDPOINT__c</fullName>
    <description>Endpoint for Webservices.</description>
    <inlineHelpText>Endpoint for Webservices,</inlineHelpText>
    <label>API_ENDPOINT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Connect2_Settings__c/fields/Default_Login_Email__c.field-meta.xml
<CustomField>
    <fullName>Default_Login_Email__c</fullName>
    <description>Default Login email for Testing.  Null for production.</description>
    <inlineHelpText>Default Login email for Testing.  Null for production.</inlineHelpText>
    <label>Default Login Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Connect2_Settings__c/fields/Send_Show_Org_Emails__c.field-meta.xml
<CustomField>
    <fullName>Send_Show_Org_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sends the show organizer emails upon order changes.</description>
    <inlineHelpText>Sends the show organizer emails upon order changes.</inlineHelpText>
    <label>Send Show Org Emails</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/GPM_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>GPM_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple GPMs</description>
    <inlineHelpText>Hidden user lookup field used to submit orders for approval to multiple GPMs</inlineHelpText>
    <label>GPM Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GPM_Approval_Order_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/GPM_Approver_2__c.field-meta.xml
<CustomField>
    <fullName>GPM_Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple GPMs</description>
    <label>GPM Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GPM_Approval_Order_Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/GPM_Approver_3__c.field-meta.xml
<CustomField>
    <fullName>GPM_Approver_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden user lookup field used to submit orders for approval to multiple GPMs</description>
    <label>GPM Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GPM_Approval_Order_Tasks3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Template__c.field-meta.xml
<CustomField>
    <fullName>Item_Template__c</fullName>
    <description>Determines the list of order options to select for an order task</description>
    <inlineHelpText>Basic, Carpet, Graphics, Custom Carpet, Custom Graphics as determined by selecting the item.</inlineHelpText>
    <label>Item Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>GES Connect Order Object.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that display&#39;s different status values</description>
    <inlineHelpText>Status of GES Order Task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Graphics Requested</fullName>
            </value>
            <value>
                <fullName>Graphics Submitted</fullName>
            </value>
            <value>
                <fullName>Graphics Rejected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Submitted to Graphics</fullName>
            </value>
            <value>
                <fullName>Submitted For AM Review</fullName>
            </value>
            <value>
                <fullName>Pending AM Review</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Status of the Order.  Defaults to &#39;New&#39; and will clearly indicate the status of the order state and what its in.</description>
    <inlineHelpText>Status of the Order.</inlineHelpText>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Attribute__c/GC_Show_Attribute__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Attribute object for use in storing dynamic lookup content for a Show such as Department / Sign Types / Hall Information / Area Information / Sign Sizes and other related content.  Each type of object is defined by RecordType.</description>
    <label>Show Attribute</label>
    <nameField>
        <label>Show Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Show Attributes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Attribute__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Attributes</relationshipLabel>
    <relationshipName>Show_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Attribute__c/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <description>Department Lookup Value</description>
    <label>Department</label>
</RecordType>

unpackaged/main/default/objects/GC_Show_Attribute__c/recordTypes/Material.recordType-meta.xml
<RecordType>
    <fullName>Material</fullName>
    <active>true</active>
    <description>Material Look up Value</description>
    <label>Material</label>
</RecordType>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/GC_Vendor_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Vendor Order Task Custom Object. This Object is used to identify Vendor Order Task details to be performed in a GES Connect Show.</description>
    <label>Vendor Order Task</label>
    <nameField>
        <displayFormat>VOT-{0000}</displayFormat>
        <label>Vendor Order Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Completion_Date_Time_Ven__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time_Ven__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Delivery_Date_Time_Ven__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time_Ven__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</inlineHelpText>
    <label>Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Delivery_Location_Ven__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Location_Ven__c</fullName>
    <label>Delivery Area</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the GES Order associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order associated with this vendor order task.</inlineHelpText>
    <label>Delivery Location</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipLabel>Vendor Order Tasks</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Removal_Date_Time_Ven__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time_Ven__c</fullName>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/SA_Venue_Location_Ven__c.field-meta.xml
<CustomField>
    <fullName>SA_Venue_Location_Ven__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GC_Show_Attribute__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Venue Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GC_Show_Attribute__c</referenceTo>
    <relationshipLabel>Vendor Order Tasks (Venue Location)</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Vendor Order Task.</description>
    <inlineHelpText>Status of the Vendor Order Task.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Instructions__c</fullName>
    <description>Instructions to the Vendor.</description>
    <inlineHelpText>Instructions to the Vendor indicating services needed.</inlineHelpText>
    <label>Vendor Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GC_Show_Role__c.field-meta.xml
<CustomField>
    <fullName>GC_Show_Role__c</fullName>
    <label>GES Connect Show Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GC Account Manager</fullName>
            </value>
            <value>
                <fullName>GC Creative Director</fullName>
            </value>
            <value>
                <fullName>GC Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>GC Detailer</fullName>
            </value>
            <value>
                <fullName>GC Director of Account Management</fullName>
            </value>
            <value>
                <fullName>GC Sales Manager</fullName>
            </value>
            <value>
                <fullName>GC Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>GC Community Client</fullName>
            </value>
            <value>
                <fullName>GC Community Vendor</fullName>
            </value>
            <value>
                <fullName>GC Drafter</fullName>
            </value>
            <value>
                <fullName>GC Convention Planning Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/GC_OrderUtils.cls
public without sharing class GC_OrderUtils {
    public static Boolean devMode = true;
    public static User currentUserInfo1 = [select Id, GC_Show_Role__c from User where Id =: UserInfo.getUserId()];
    public static string showRole = string.isNotBlank(currentUserInfo1.GC_Show_Role__c) ? currentUserInfo1.GC_Show_Role__c: '';
    
    public static GC_GES_Connect2_Settings__c settings { get; set; }
    public enum FieldToSort {
        Label, Value
    }

    public class TaskPermissions {
        public GC_GES_Order_Task__c got {get; set;}
        public Boolean CanEdit {get; set;}
        public Boolean CanClone {get; set;}
        public Boolean CanRevise {get; set;}
        public Boolean CanCancel {get; set;}
        public Boolean CanPlaceOnHold {get; set;}
        public Boolean CanReleaseFromHold {get; set;}
        public Boolean CanApprove {get; set;}
        public Boolean CanReset {get; set;}
        public Boolean CanRecall {get; set;}
        public Boolean CanSubmit {get; set;}
        public Boolean CanDelete {get; set;}
        public Boolean CanCommunityCancel {get; set;}
        public Boolean CanCommunityEdit {get; set;}
        public Boolean CanSubmitGraphics {get; set;}
        public Boolean CanSubmittoCore {get; set;}
        public Boolean canSubmitToReview {get; set;}        
        public Boolean canSubmitToAM {get; set;}  
        
        public TaskPermissions(GC_GES_Order_Task__c task) {
            this(task, GC_ApprovalUtils.isUnderApproval(task.Id));
        }
        
        public TaskPermissions(GC_GES_Order_Task__c task, Boolean isUnderApproval) {
            got = task;
            CanEdit = got.Status__c == 'New' || got.Status__c == 'Rejected' || got.Status__c == 'Submitted' || got.Status__c == 'Pending AM Review' ;
            CanClone = true; // all status's can be cloned;
            //CanRevise = got.Status__c == 'Active' || got.Status__c == 'Released';  --Amarab 06/22/2023 SAL-1287 GOT Edit Button Hidden when Orders are in Proof Status
            CanRevise = got.Status__c == 'Active' || got.Status__c == 'Released' || got.Status__c == 'Proof Waiting for Approval' || got.Status__c == 'Proof Changes Required' || got.Status__c == 'Proof Approved';
            //CanCancel = got.Status__c == 'Active' || got.Status__c == 'Submitted to Graphics' || got.Status__c == 'Released';  --Amarab 06/22/2023 SAL-1287 GOT Edit Button Hidden when Orders are in Proof Status
            CanCancel = got.Status__c == 'Active' || got.Status__c == 'Submitted to Graphics' || got.Status__c == 'Released' || got.Status__c == 'Proof Waiting for Approval' || got.Status__c == 'Proof Changes Required' || got.Status__c == 'Proof Approved';  
            CanApprove = got.Status__c == 'New' || got.Status__c == 'Rejected' || got.Status__c == 'Submitted' || (got.Status__c == 'Submitted to Graphics' &&showRole.contains('GC Graphics Project Manager') ) || (got.Status__c == 'Submitted For AM Review' && showRole.Contains('GC Account Manager') );
            CanPlaceOnHold = got.Status__c == 'New' || got.Status__c == 'Submitted' || got.Status__c == 'Approved' || got.Status__c == 'Rejected' || got.Status__c == 'Submitted to Graphics' || got.Status__c == 'Released' || got.Status__c == 'Pending AM Review' ;
            CanReleaseFromHold = got.Status__c == 'On Hold';
            CanReset = got.Status__c == 'Approved';
            CanRecall = isUnderApproval && ( (got.OwnerId == UserInfo.getUserId()  && got.Status__c == 'Submitted') || (got.Status__c == 'Submitted to Graphics' && showRole.Contains('GC Account Manager') ) || (got.Status__c == 'Submitted For AM Review' && showRole.Contains('GC Graphics Project Manager')) );            
            CanSubmit = ((got.Status__c == 'New' || got.Status__c == 'Rejected' ) && got.OwnerId == UserInfo.getUserId());            
            CanDelete = (got.Status__c == 'On Hold'|| got.Status__c == 'New' || got.Status__c == 'Approved' || got.Status__c == 'Rejected') && got.OwnerId == UserInfo.getUserId();
            CanCommunityCancel = got.Status__c == 'New' || got.Status__c == 'Approved' || got.Status__c == 'Rejected'||got.Status__c == 'On Hold';
            CanCommunityEdit = got.Status__c == 'New' || got.Status__c == 'Rejected' ||got.Status__c == 'On Hold' ;
            CanSubmitGraphics = (got.Item_Template__c != null && got.Item_Template__c.contains('Graphics'));
            CanSubmittoCore = got.Status__c == 'Approved';
            canSubmitToReview  = got.Status__c == 'Active' && (got.GPM_Approver_1__c != null || got.GPM_Approver_2__c != null || got.GPM_Approver_3__c != null) && (showRole != null && showRole.Contains('GC Account Manager'))  ; //SAL-421  
            canSubmitToAM= got.Status__c.Contains('Pending AM Review') && showRole.Contains('GC Graphics Project Manager') ;
            
        }
    }

    public static PageReference editTask(GC_GES_Order_Task__c task) {
        ApexPages.StandardController sc = new ApexPages.StandardController(task);
        GC_GESOrderTaskViewController vc = new GC_GESOrderTaskViewController(sc);
        return vc.editAction();
    }
    public static PageReference cloneTask(GC_GES_Order_Task__c task) {
        ApexPages.StandardController sc = new ApexPages.StandardController(task);
        GC_GESOrderTaskViewController vc = new GC_GESOrderTaskViewController(sc);
        return vc.cloneAction();
    }

    public static PageReference cancelTask(GC_GES_Order_Task__c task) {
        ApexPages.StandardController sc = new ApexPages.StandardController(task);
        GC_GESOrderTaskViewController vc = new GC_GESOrderTaskViewController(sc);

        // TODO need to also do cancel from core, which requires web service call.
        // Can't easily be done right now.
        if (task.Status__c == 'Active') {
            GC_PageUtil.AddWarningMessage('Cancel an Active task requires submitting the cancel in core.');
        }

        vc.cancelAction();
        return null;
    }
    public static PageReference reviseTask(GC_GES_Order_Task__c task) {
        ApexPages.StandardController sc = new ApexPages.StandardController(task);
        GC_GESOrderTaskViewController vc = new GC_GESOrderTaskViewController(sc);
        return vc.reviseAction();
    }
    public static PageReference placeOnHoldTask(GC_GES_Order_Task__c task) {
        ApexPages.StandardController sc = new ApexPages.StandardController(task);
        GC_GESOrderTaskViewController vc = new GC_GESOrderTaskViewController(sc);
        vc.placeOnHoldAction();
        return null;
    }
    public static PageReference releaseFromHoldTask(GC_GES_Order_Task__c task) {
        ApexPages.StandardController sc = new ApexPages.StandardController(task);
        GC_GESOrderTaskViewController vc = new GC_GESOrderTaskViewController(sc);
        vc.releaseFromHoldAction();
        return null;
    }
    public static PageReference approveTask(GC_GES_Order_Task__c task) {
        ApexPages.StandardController sc = new ApexPages.StandardController(task);
        GC_GESOrderTaskViewController vc = new GC_GESOrderTaskViewController(sc);
        vc.approveForSubmitAction();
        return null;
    }
    public static PageReference reworkTask(GC_GES_Order_Task__c task) {
        ApexPages.StandardController sc = new ApexPages.StandardController(task);
        GC_GESOrderTaskViewController vc = new GC_GESOrderTaskViewController(sc);
        vc.resetToNew();
        return null;
    }

    public static PageReference submitTask(GC_GES_Order_Task__c task) {
        ApexPages.StandardController sc = new ApexPages.StandardController(task);
        GC_GESOrderTaskViewController vc = new GC_GESOrderTaskViewController(sc);
        vc.submitRecord();
        return null;
    }

    public static void lookupServiceTypeAttributes(String showId, List<SelectOption> serviceTypeOptions) {
        List<GC_Show_Attribute__c> showAttributes = [select Id, Name, RecordType.Name from GC_Show_Attribute__c where Connect2_Show__c = :showId];

        if (serviceTypeOptions == null) {
            serviceTypeOptions = new List<SelectOption>();
        }

        serviceTypeOptions.clear();
        SelectOption noneSelectOption = new SelectOption('', '---None---');
        serviceTypeOptions.add(noneSelectOption);

        for (GC_Show_Attribute__c showAttribute : showAttributes) {
            if (showAttribute.RecordType.Name == 'Show Service') {
                SelectOption option = new SelectOption(showAttribute.Id, showAttribute.Name);
                serviceTypeOptions.Add(option);
            }
        }
    }

    public static void lookupShowAttributes(String showId, List<SelectOption> materialOptions, List<SelectOption> venueOptions, List<SelectOption> departmentOptions) {
        List<GC_Show_Attribute__c> showAttributes = [select Id, Name, RecordType.Name from GC_Show_Attribute__c where Connect2_Show__c = :showId];

        if (venueOptions == null) {
            venueOptions = new List<SelectOption>();
        }

        if (materialOptions == null) {
            materialOptions = new List<SelectOption>();
        }

        if (departmentOptions == null) {
            departmentOptions = new List<SelectOption>();
        }

        venueOptions.clear();
        materialOptions.clear();
        departmentOptions.clear();
        SelectOption noneSelectOption = new SelectOption('', '---None---');
        venueOptions.Add(noneSelectOption);
        materialOptions.Add(noneSelectOption);
        departmentOptions.Add(noneSelectOption);

        for (GC_Show_Attribute__c showAttribute : showAttributes) {
            if (showAttribute.RecordType.Name == 'Venue Location') {
                SelectOption option = new SelectOption(showAttribute.Id, showAttribute.Name);
                venueOptions.Add(option);
            } else if (showAttribute.RecordType.Name == 'Material') {
                SelectOption option = new SelectOption(showAttribute.Id, showAttribute.Name);
                materialOptions.Add(option);
            } else if (showAttribute.RecordType.Name == 'Department') {
                SelectOption option = new SelectOption(showAttribute.Id, showAttribute.Name);
                departmentOptions.Add(option);
            }
        }

        system.debug('venueOptions++++'+venueOptions);

        doSort(venueOptions,FieldToSort.Label);
        system.debug('venueOptionsSort++++'+venueOptions);
        //venueOptions.sort();
        //venueOptions.Add(noneSelectOption);
    }

    public static void doSort(List<Selectoption> opts, FieldToSort sortField) {
        
        Map<String, Selectoption> mapping = new Map<String, Selectoption>();
        // Suffix to avoid duplicate values like same labels or values are in inbound list 
        Integer suffix = 1;
        for (Selectoption opt : opts) {
            if (sortField == FieldToSort.Label) {
                mapping.put(    // Done this cryptic to save scriptlines, if this loop executes 10000 times
                                // it would every script statement would add 1, so 3 would lead to 30000.
                             (opt.getLabel() + suffix++), // Key using Label + Suffix Counter  
                             opt);   
            } else {
                mapping.put(    
                             (opt.getValue() + suffix++), // Key using Label + Suffix Counter  
                             opt);   
            }
        }
        
        List<String> sortKeys = new List<String>();
        sortKeys.addAll(mapping.keySet());
        sortKeys.sort();
        // clear the original collection to rebuilt it
        opts.clear();
        
        for (String key : sortKeys) {
            opts.add(mapping.get(key));
        }
    }

    public static GC_GES_Connect2_Settings__c getCustomSettings() {
        if (settings == null) {
            try {
                settings = [Select Id, Name, Send_Show_Org_Emails__c, Default_Login_Email__c, API_ENDPOINT__c From GC_GES_Connect2_Settings__c Where Name = 'GES Connect Settings'];
            } catch (QueryException e) {
                // Fill out defaults for running unit tests etc.
                settings = new GC_GES_Connect2_Settings__c();
                settings.Name = 'GES Connect Settings';
                settings.Send_Show_Org_Emails__c = false;
                settings.Default_Login_Email__c = 'LDrummond@ges.com';
                settings.API_ENDPOINT__c = 'https://xsysapi.viad.com';
            }
        }

        return settings;

        //List<GC_GES_Connect2_Settings__c> defaultCustomSettings = [select Id, Name, Send_Show_Org_Emails__c, Default_Login_Email__c, API_ENDPOINT__c from GC_GES_Connect2_Settings__c limit 1];
        //if (defaultCustomSettings.size() == 0) {
        //    GC_GES_Connect2_Settings__c newDefaults = new GC_GES_Connect2_Settings__c();
        //    newDefaults.Name = 'GES Connect Settings';
        //    newDefaults.Send_Show_Org_Emails__c = false;
        //    newDefaults.Default_Login_Email__c = 'LDrummond@ges.com';
        //    newDefaults.API_ENDPOINT__c = 'https://xsysapi.viad.com';
        //    return newDefaults;
        //}
        //else {
        //    GC_GES_Connect2_Settings__c appSettings = defaultCustomSettings[0];
        //    return appSettings;
        //}
    }

    public static void DeleteOrder(GC_Order__c order) {


    }

    public static Messaging.SingleEmailMessage generateVendorEmail(GC_Vendor_Order_Task__c vot, String vendorId,String showName,String serviceType){
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
        String url='';
        url+='<a href="';
        url+=System.Label.GC_URLforLinks;
        url+=vot.Id;
        //url+='&showId=';
        if(vot.Order__c!=null){
            url+='&orderId='+vot.Order__c;
        }
        
        url+='">'+vot.Name;
        url+='</a>';
        set<id> attachId=new set<id>();
        mail.setTargetObjectId(vendorId);
        String subject = 'Vendor Order Task [' + vot.Name + '] has been created and sent for your review.';
        String message = '<p>The following Vendor Order Task has been created and sent for your review:</p>' +
                         '<p><b>Show Name:</b> ' + showName + '</p>' +   
                         '<p><b>Vendor Order:</b> ' + url + '</p>' +
                         '<p><b>Venue Location:</b> ' + (String.isNotBlank(vot.SA_Venue_Location_Ven__r.Name) ? vot.SA_Venue_Location_Ven__r.Name : '' ) + '</p>' +
                         '<p><b>Delivery Area:</b> ' + (String.isNotBlank(vot.Delivery_Location_Ven__c) ? vot.Delivery_Location_Ven__c : '' ) + '</p>' +
                         '<p><b>Delivery Date/Time:</b> ' + (vot.Delivery_Date_Time_Ven__c != null ? vot.Delivery_Date_Time_Ven__c.format() : '') + '</p>' +
                         '<p><b>Completion Date/Time:</b> ' + (vot.Completion_Date_Time_Ven__c != null ? vot.Completion_Date_Time_Ven__c.format() : '') + '</p>' +
                         '<p><b>Removal Date/Time:</b> ' +  (vot.Removal_Date_Time_Ven__c != null ? vot.Removal_Date_Time_Ven__c.format() : '') + '</p>' +
                         '<p><b>Service Type:</b> ' + serviceType + '</p>' +
                         '<p><b>Submitted By:</b> ' + UserInfo.getName() + '</p>';

        if (String.isNotBlank(vot.Vendor_Instructions__c)) {
            message += '<p><b>Instructions:</b> ' + vot.Vendor_Instructions__c + '</p>';
        }
         system.debug('notes and attachment======>'+vot.NotesAndAttachments);
        if (vot.NotesAndAttachments != null) {
            message += '<p><b>Attachments:</b></p>';
            
            
            //Newline of code for sending attachments
            for(NoteAndAttachment attach: vot.NotesAndAttachments) {
            attachId.add(attach.Id);
                // get the URL and find what the URL is before /apex/ to get the community name.
               // URL currentURL = URL.getCurrentRequestUrl();
                //String currentPath = currentURL.getPath();
                //String communityName = currentPath.substringBefore('/apex/');
                //String attachmentURL = URL.getSalesforceBaseUrl().toExternalForm() + communityName + '/servlet/servlet.FileDownload?file='+ attach.Id;
                //if (attach.isNote)
                  //  continue;
                 //message += '<p><a href=\"' + attachmentURL + '\">' + attach.Title + '</a></p>';
            }
            system.debug('vendor id =========>'+vendorId);
            for (Attachment a : [select Name, Body, BodyLength from Attachment where Id =:attachId]){
          
             Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
                                       efa.setFileName(a.Name);
                                     efa.setBody(a.Body);
                                     fileAttachments.add(efa);
            
            }
         
         
           
        }
            system.debug('file size===========>'+fileAttachments.size());
            List<Messaging.Emailfileattachment> fileAsAttachments= new List<Messaging.Emailfileattachment> ();
            fileAsAttachments=GC_EmailUtils.getFileAttchmentsForSingle(vot.Id);
            If(fileAsAttachments.size()>0){
                fileAttachments.addAll(fileAsAttachments);
            }
            
            system.debug('file size===========>'+fileAttachments.size());
            if(fileAttachments.size()>0){
                mail.setFileAttachments(fileAttachments);
            }
            
            mail.setSenderDisplayName(UserInfo.getName());
            mail.setSubject(subject);
            mail.setHtmlBody(message);
            mail.setPlainTextBody(message.stripHtmlTags());
            mail.setSaveAsActivity(false);
            //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); //Sending mail commented this for SAL-622. It was sending emails twice @@ rksinha
            
        //Sending PageMessage
        //GC_PageUtil.AddConfirmMessage('Vendor Task has been Sent to the Vendor(s).');
        return mail;
    }
 
    
    

    public static Boolean validateVendorTask(GC_Vendor_Order_Task__c vot) {
        Integer errors = 0;
        if (vot.Service_Type__c != null && vot.Vendor__c == null) {
            vot.Vendor__c.addError('Vendor is required when specifying service');
            errors++;
        }
        if (vot.Service_Type2__c != null && vot.Vendor2__c == null) {
            vot.Vendor2__c.addError('Vendor is required when specifying service');
            errors++;
        }
        if (vot.Service_Type3__c != null && vot.Vendor3__c == null) {
            vot.Vendor3__c.addError('Vendor is required when specifying service');
            errors++;
        }
        if (vot.Service_Type4__c != null && vot.Vendor4__c == null) {
            vot.Vendor4__c.addError('Vendor is required when specifying service');
            errors++;
        }
        if (vot.Service_Type5__c != null && vot.Vendor5__c == null) {
            vot.Vendor5__c.addError('Vendor is required when specifying service');
            errors++;
        }
        return errors == 0;
    }
    
    public static User currentUserInfo(Id userId) {
       return [select GC_Show_Role__c from User where Id =: userId];
    }

    public class URLParameters {
        public Set<String> orderIds {get; set;}
        public Set<String> statusValues {get; set;}
    }
}