unpackaged/main/default/objects/Exhibit__c/Exhibit__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Exhibit</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exhibit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Exhibit__c/fields/Activity_Type_Exhibit_Instance_c__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type_Exhibit_Instance_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connet - Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Exhibit</relationshipLabel>
    <relationshipName>Activity_Type_Exhibit_Instance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/GES_Connect_Corporate_Accounts__c.object-meta.xml
<CustomObject>
    <description>Details for GES Connect - Corporate Accounts  for the Data Requirements purpose</description>
    <label>GES Connect - Corporate Accounts</label>
    <nameField>
        <displayFormat>GCA-{0000}</displayFormat>
        <label>GES Connect - Corporate Accounts</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect - Corporate Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Exhibit_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exhibit Cancelled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/ExhibitTriggerHandler.cls
public class ExhibitTriggerHandler {
    public static void updateExhibitCancelledOnCongress(List<Exhibit__c> listExhibit, Set<Id> setUpdatedExhibitIds, Set<Id> setCongressIds) {
        /*List<GES_Connect_Corporate_Accounts__c> listCongressToUpdate = new List<GES_Connect_Corporate_Accounts__c>();
        Map<Id, List<Exhibit__c>> mapExhibit = new Map<Id, List<Exhibit__c>>();
        for(Exhibit__c exhibit : [select Canceled__c, Activity_Type_Exhibit_Instance_c__c, Activity_Type_Exhibit_Instance_c__r.Exhibit_Cancelled__c from Exhibit__c
                                    where Activity_Type_Exhibit_Instance_c__c IN: setCongressIds AND Id NOT IN: setUpdatedExhibitIds]) {
            if(!mapExhibit.containsKey(exhibit.Activity_Type_Exhibit_Instance_c__c)) {
                mapExhibit.put(exhibit.Activity_Type_Exhibit_Instance_c__c, new List<Exhibit__c>());
            }
            mapExhibit.get(exhibit.Activity_Type_Exhibit_Instance_c__c).add(exhibit);
        }
        for(Exhibit__c updatedExhibit : listExhibit) {
            if(mapExhibit.get(updatedExhibit.Activity_Type_Exhibit_Instance_c__c) != null) {
                Boolean checkExhibitNotCancelled = false;
                GES_Connect_Corporate_Accounts__c congress = new GES_Connect_Corporate_Accounts__c();
                for(Exhibit__c exhibit : mapExhibit.get(updatedExhibit.Activity_Type_Exhibit_Instance_c__c)) {
                    congress = exhibit.Activity_Type_Exhibit_Instance_c__r;
                    if(!exhibit.Canceled__c) {
                        checkExhibitNotCancelled = true;
                        break;
                    }
                }
                if(!checkExhibitNotCancelled ) {
                    congress.Exhibit_Cancelled__c = true;
                    listCongressToUpdate.add(congress);
                }
            }
        }
        if(listCongressToUpdate.size() > 0) {
            update listCongressToUpdate;
        }*/
    }
}