unpackaged/main/default/objects/Exhibit__c/Exhibit__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Exhibit</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exhibit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Exhibit__c/fields/Booth_Length__c.field-meta.xml
<CustomField>
    <fullName>Booth_Length__c</fullName>
    <label>Booth Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Booth_Number__c.field-meta.xml
<CustomField>
    <fullName>Booth_Number__c</fullName>
    <label>Booth Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Booth_Width__c.field-meta.xml
<CustomField>
    <fullName>Booth_Width__c</fullName>
    <label>Booth Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/GT_Brand__c.object-meta.xml
<CustomObject>
    <description>This will be the product object for all accounts in Generic Template</description>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Brand__c/fields/Canceled__c.field-meta.xml
<CustomField>
    <fullName>Canceled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup for Event Activity Type</description>
    <label>Event</label>
    <referenceTo>GT_Event_RL__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Exhibit__c.field-meta.xml
<CustomField>
    <fullName>Exhibit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibit</label>
    <referenceTo>GT_Exhibit__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up for GT_Event__c  (GES Connect Event)</description>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Meeting_Room__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting Room</label>
    <referenceTo>GT_Meeting_Room__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Speaking_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Speaking_Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Speaking Engagement</label>
    <referenceTo>GT_Speaking_Engagement__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsorship</label>
    <referenceTo>GT_Sponsorship__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/GT_Event__c.object-meta.xml
<CustomObject>
    <description>Object will be used to create Generic Template Account for GES Community. Main Event object for 1st Lightning Community. CC, Merck, SS, GT, Pharma Template, NNI.</description>
    <label>GES Connect Event</label>
    <nameField>
        <displayFormat>GCE-{000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Event__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/fields/Shipping_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State_Province__c</fullName>
    <label>Shipping State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GT_Event_RL__c/GT_Event_RL__c.object-meta.xml
<CustomObject>
    <description>This will be the Event (Related List to GES Connect Event) object for all Accounts under Generic Template</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Event_RL__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Exhibit__c/GT_Exhibit__c.object-meta.xml
<CustomObject>
    <description>This will be the Exhibit object for all Accounts under Generic Template</description>
    <label>Exhibit</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exhibit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Exhibit__c/fields/Booth_Length__c.field-meta.xml
<CustomField>
    <fullName>Booth_Length__c</fullName>
    <label>Booth Length</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GT_Exhibit__c/fields/Booth_Width__c.field-meta.xml
<CustomField>
    <fullName>Booth_Width__c</fullName>
    <label>Booth Width</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GT_Exhibit__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Exhibits</relationshipLabel>
    <relationshipName>Exhibits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Meeting_Room__c/GT_Meeting_Room__c.object-meta.xml
<CustomObject>
    <description>This will be the Meeting Room object for all accounts in Generic Template</description>
    <label>Meeting Room</label>
    <nameField>
        <displayFormat>MR-{00000}</displayFormat>
        <label>Meeting Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Meeting_Room__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Meeting Rooms</relationshipLabel>
    <relationshipName>Meeting_Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Membership__c/GT_Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>MS-{0000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Membership__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Reg_Attend_Only__c/GT_Reg_Attend_Only__c.object-meta.xml
<CustomObject>
    <description>This will be the Registration/Attend Only object for all accounts in Generic Template</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Registration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Reg_Attend_Only__c/fields/Canceled__c.field-meta.xml
<CustomField>
    <fullName>Canceled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GT_Reg_Attend_Only__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipName>Registration_Attend_Only</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Speaking_Engagement__c/GT_Speaking_Engagement__c.object-meta.xml
<CustomObject>
    <description>This will be the Speaking Engagement object for all accounts in Generic Template</description>
    <label>Speaking Engagement</label>
    <nameField>
        <displayFormat>SE-{00000}</displayFormat>
        <label>Speaking Engagement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speaking Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Speaking_Engagement__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Speaking Engagements</relationshipLabel>
    <relationshipName>Symposia</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Speaking_Engagement__c/fields/Speaking_Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Speaking_Engagement_Type__c</fullName>
    <label>Speaking Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Breakout session</fullName>
            </value>
            <value>
                <fullName>Education Session speaker</fullName>
            </value>
            <value>
                <fullName>Keynote speaker</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Panel speaker</fullName>
            </value>
            <value>
                <fullName>Product Theater</fullName>
            </value>
            <value>
                <fullName>Sales session</fullName>
            </value>
            <value>
                <fullName>Scientific Posters</fullName>
            </value>
            <value>
                <fullName>Symposia</fullName>
            </value>
            <value>
                <fullName>Symposium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GT_Sponsorship__c/GT_Sponsorship__c.object-meta.xml
<CustomObject>
    <description>This will be the Sponsorship object for all accounts in Generic Template</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Sponsorship__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up for GT_Event__c</description>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Sporting_Event__c/GT_Sporting_Event__c.object-meta.xml
<CustomObject>
    <description>This will be the Sporting Event object for all accounts in Generic Template</description>
    <label>Sporting Event</label>
    <nameField>
        <displayFormat>SE - {0000}</displayFormat>
        <label>Sporting Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sporting Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Sporting_Event__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Sporting Events</relationshipLabel>
    <relationshipName>Sporting_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsorship__c/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Sponsorship</relationshipLabel>
    <relationshipName>Sponsorship_Instance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsorship__c/fields/Sponsorship_Name__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Name__c</fullName>
    <label>Sponsorship Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GT_ExhibitScheduleControllerTest.cls
@isTest
public class GT_ExhibitScheduleControllerTest {
    
    static TestMethod void fetchReportTest(){
        
        //Test GES Connect Event
        GT_Event__c testGCEvent = new GT_Event__c();
        testGCEvent.Name_of_Event__c = 'Test Event';
        testGCEvent.Event_Acronym__c = 'TEST';
        testGCEvent.Event_Start_Date__c = Date.today();
        testGCEvent.Event_End_Date__c = Date.today() + 2;
        testGCEvent.Facility_Name__c = 'Test Facility';
        testGCEvent.Shipping_City__c = 'Chicago';
        testGCEvent.Shipping_State_Province__c = 'Illinois';
        testGCEvent.Shipping_Country__c = 'United States';
        insert testGCEvent;
        
        //Test Exhibit
        GT_Exhibit__c testExhibit = new GT_Exhibit__c();
        testExhibit.Booth_Length__c = 100;
        testExhibit.Booth_Width__c = 200;
        testExhibit.Booth_Number__c = '12345';
        testExhibit.GES_Connect_Event__c = testGCEvent.Id;
        testExhibit.Canceled__c = false;
        insert testExhibit;
        
        //Test Speaking Engagement
        GT_Speaking_Engagement__c testSpEngmnt = new GT_Speaking_Engagement__c();
        testSpEngmnt.Speaking_Engagement_Type__c = 'Panel speaker';
        testSpEngmnt.GES_Connect_Event__c = testGCEvent.Id;
        testSpEngmnt.Canceled__c = false;
        insert testSpEngmnt;
        
        //Test Sponsorship
        GT_Sponsorship__c testSponsorship = new GT_Sponsorship__c();
        testSponsorship.Sponsorship_Name__c = 'Test Sponsorship';
        testSponsorship.GES_Connect_Event__c = testGCEvent.Id;
        testSponsorship.Canceled__c = false;
        insert testSponsorship;
        
        //Test Meeting Room
        GT_Meeting_Room__c testMR = new GT_Meeting_Room__c();
        testMR.Meeting_Room_Name__c = 'Test Meeting Room';
        testMR.GES_Connect_Event__c = testGCEvent.Id;
        testMR.Canceled__c = false;
        insert testMR;
        
        //Test Event(RL)
        GT_Event_RL__c testevntRL = new GT_Event_RL__c();
        testevntRL.Event_Room_Name__c = 'Test Event Room';
        testevntRL.GES_Connect_Event__c = testGCEvent.Id;
        testevntRL.Canceled__c = false;
        insert testevntRL;
        
        //Test Reg_Attend_Only
        GT_Reg_Attend_Only__c testRegAttend = new GT_Reg_Attend_Only__c();
        testRegAttend.GES_Connect_Event__c = testGCEvent.Id;
        testRegAttend.Canceled__c =false;
        testRegAttend.Names_of_Attendees__c = 'Karthik';
        insert testRegAttend;
        
        //Test Sporting Event
        GT_Sporting_Event__c testSportingEvent = new GT_Sporting_Event__c();
        testSportingEvent.GES_Connect_Event__c = testGCEvent.Id;
        testSportingEvent.Canceled__c =false;
        testSportingEvent.Sporting_Event_Name__c = 'Test';
        testSportingEvent.Sporting_Event_Type__c = 'Suite';
        insert testSportingEvent;
        
        //Test Membership
        GT_Membership__c testMembership = new GT_Membership__c();
        testMembership.GES_Connect_Event__c = testGCEvent.Id;
        testMembership.Canceled__c =false;
        testMembership.Membership_Name__c = 'Test';
        insert testMembership;
        
        //Test Product
        GT_Brand__c testBrand = new GT_Brand__c();
        testBrand.Canceled__c = false;
        testBrand.Exhibit__c = testExhibit.Id;
        testBrand.Speaking_Engagement__c = testSpEngmnt.Id;
        testBrand.Sponsorship__c = testSponsorship.Id;
        testBrand.Meeting_Room__c = testMR.Id;
        testBrand.Event__c = testevntRL.Id;
        testBrand.Registration_Attend_Only__c = testRegAttend.Id;
        insert testBrand;
        
        GT_ExhibitScheduleController.getConnectSettings();
        GT_ExhibitScheduleController.fetchReports(null, null, null);
        GT_ExhibitScheduleController.fetchReports(string.valueof(Date.today()), null,'Sig Sauer');
        GT_ExhibitScheduleController.fetchReports(null, string.valueof(Date.today()),null);
        GT_ExhibitScheduleController.fetchReports(string.valueof(Date.today()), string.valueof(Date.today()), 'Crown Castle');
       
       // GT_ExhibitScheduleController.fetchBrandNames();
        GT_ExhibitScheduleController.fetchCountryNames();
        GT_ExhibitScheduleController.fetchBusinessUnitCategory();
        
    }
}