unpackaged/main/default/objects/Asset/fields/Actual_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Return_Date__c</fullName>
    <label>Actual Return Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/ExpectedReturn__c.field-meta.xml
<CustomField>
    <fullName>ExpectedReturn__c</fullName>
    <label>Expected Return</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Scan_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Scan_Out_Date__c</fullName>
    <label>Scan Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Weight_Kg__c.field-meta.xml
<CustomField>
    <fullName>Weight_Kg__c</fullName>
    <formula>Product2.Weight_Kg__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weight (Kg)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Weight_Lb__c.field-meta.xml
<CustomField>
    <fullName>Weight_Lb__c</fullName>
    <formula>Product2.Weight_Lb__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weight (Lb)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Exhibition__c.field-meta.xml
<CustomField>
    <fullName>Exhibition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Exhibition Orders</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Expected_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Return_Date__c</fullName>
    <label>Expected Return Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OrderItem/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <formula>PricebookEntry.Product2.Inventory__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Sendable__c.field-meta.xml
<CustomField>
    <fullName>Sendable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sendable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Weight_Kg__c.field-meta.xml
<CustomField>
    <fullName>Weight_Kg__c</fullName>
    <label>Weight (Kg)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Weight_Lb__c.field-meta.xml
<CustomField>
    <fullName>Weight_Lb__c</fullName>
    <label>Weight (Lb)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipment records to be used by legacy Visit process to send inventory items to events/shows.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SHP-{00000000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Shipment__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Shipment__c/fields/ExhibitionOpportunity__c.field-meta.xml
<CustomField>
    <fullName>ExhibitionOpportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Shipment__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Shipment__c/fields/ShowName__c.field-meta.xml
<CustomField>
    <fullName>ShowName__c</fullName>
    <formula>OrderID__r.Opportunity.Show_Name_ref_Occ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/ShipmentItem__c.object-meta.xml
<CustomObject>
    <label>Shipment Item</label>
    <nameField>
        <displayFormat>SHP-IT-{0000000000}</displayFormat>
        <label>Shipment Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ShipmentItem__c/fields/Actual_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Return_Date__c</fullName>
    <label>Actual Return Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/AssetID__c.field-meta.xml
<CustomField>
    <fullName>AssetID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Shipment Items</relationshipLabel>
    <relationshipName>Shipment_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/Check_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Date__c</fullName>
    <label>Check Out Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/Exhibition__c.field-meta.xml
<CustomField>
    <fullName>Exhibition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Shipment Items</relationshipLabel>
    <relationshipName>Shipment_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <formula>OrderProductID__r.PricebookEntry.Product2.Inventory__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/Item_is_Packed__c.field-meta.xml
<CustomField>
    <fullName>Item_is_Packed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Item is Packed?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Shipment Items</relationshipLabel>
    <relationshipName>Shipment_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/OrderProductID__c.field-meta.xml
<CustomField>
    <fullName>OrderProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Shipment Items</relationshipLabel>
    <relationshipName>Shipment_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/Packing_Status__c.field-meta.xml
<CustomField>
    <fullName>Packing_Status__c</fullName>
    <label>Packing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not packed</fullName>
                <default>true</default>
                <label>Not packed</label>
            </value>
            <value>
                <fullName>Packed in Shipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/ProductID__c.field-meta.xml
<CustomField>
    <fullName>ProductID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Shipment Items</relationshipLabel>
    <relationshipName>Shipment_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Shipment does not exist or is not part of the same Order.</errorMessage>
        <filterItems>
            <field>Shipment__c.OrderID__c</field>
            <operation>equals</operation>
            <valueField>$Source.OrderID__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Shipment Items</relationshipLabel>
    <relationshipName>Shipment_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/Weight_Kg__c.field-meta.xml
<CustomField>
    <fullName>Weight_Kg__c</fullName>
    <label>Weight (Kg)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ShipmentItem__c/fields/Weight_Lb__c.field-meta.xml
<CustomField>
    <fullName>Weight_Lb__c</fullName>
    <label>Weight (Lb)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ShipmentReturn_Controller.cls
public class ShipmentReturn_Controller {
    private ApexPages.StandardController ctrl;
    public String scannedId {get;set;}
    public Boolean DisplayDetails {get;set;}
    public Shipment__c Ship {get;set;}
    public List<OrderItem> OrdItems {get;set;}
    public List<ShipmentItem__c> ShipmentItems= new List<ShipmentItem__c>();
    public List<ShipmentItem__c> CheckedIn_Items {get;set;}
    
    public ShipmentReturn_Controller(ApexPages.StandardController controllerParam){
        ctrl = controllerParam;
        DisplayDetails = False;
        
        
    }
    
    public void SpecialCharacterCheck(){
        system.debug('Inside SpecialCharacterCheck====>');
        //scannedId=Apexpages.currentPage().getParameters().get('valFromVf');
        if(scannedId.contains('?')){
            list<string> y= scannedId.split('\\?');
            CheckinAsset(y[0]);
            system.debug('scannedId====>'+scannedId);
        }
        
    }
    
    public void CheckinItem(){
        system.debug('scannedId====>'+scannedId);
        CheckinAsset(scannedId);
    }
    
    public Void CheckinAsset(string AssetID){
        
        Asset AssetItem= new Asset(); //checked in Asset info
        ShipmentItem__c ShipItem= new ShipmentItem__c(); //Shipment Item linked to Asset
        CheckedIn_Items= new List<ShipmentItem__c>(); 
        system.debug('<==Inside CheckinAsset==>');
        system.debug('scannedId====>'+scannedId);
        
        //query asset info using serial number
        try{
            AssetItem =[select Id,Name,SerialNumber,Status,Scan_Out_Date__c,ExpectedReturn__c,Description,Product2.Name from Asset where SerialNumber=:AssetID And Status='Rented Out' limit 1];
        }
        catch(exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No matching Rented Asset found in system!'));
        }
        
        Id itemId=AssetItem.Id;
        
        if(itemId!=Null){ // if asset is found
            System.debug('Asset Found ===>'+AssetItem);
            DisplayDetails=False;
            DisplayDetails=True;
            
            System.debug('Display Details==>'+DisplayDetails);
            try{
                //query shipment Item linked to asset
                ShipItem= [Select Id,Actual_Return_Date__c,AssetID__c,Check_Out_Date__c,Exhibition__c,Expected_Return_Date__c,Inventory__c,Item_is_Packed__c,OrderID__c,OrderProductID__c,Packing_Status__c,ProductID__c,ProductID__r.Name,Quantity__c,Shipment__c,Weight_Kg__c,Weight_Lb__c from ShipmentItem__c where AssetID__c=:itemId and Actual_Return_Date__c= null];
            }
            catch(exception e){
                System.debug('Error:'+e);
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Unknown Shipment!'));
            }
            
            try{
                ShipItem.Actual_Return_Date__c= date.today();
                update(ShipItem);
            }
            catch(exception e){
                System.debug('Error:'+e);
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Error in update'));
            }
            
            System.debug('Shipment Item Found===>'+ShipItem);
            Id shipmentId=ShipItem.Shipment__c;
            Id OrdId;
            
            if(shipmentId!=null){
                
                try{
                    //query shipment info using shipment Id
                    Ship = [Select Id,ExhibitionOpportunity__c,ShippingDate__c,AccountID__c,OrderID__c,ShowName__c,ReturnDate__c from Shipment__c where Id=:shipmentId limit 1]; 
                }
                catch(QueryException e)
                {
                    System.debug('Error:'+e);
                }
                
                try{
                    //query Order info using shipment Id
                    OrdId = [Select OrderID__c from Shipment__c where Id=:shipmentId limit 1].OrderID__c; 
                }
                catch(QueryException e)
                {
                    System.debug('Error:'+e);
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Unknown Order!'));
                }
                
                if ( OrdId != null ){
                    System.debug('Order Found===>'+OrdId);
                    OrdItems=new List<OrderItem>();
                    
                    try{
                        //query order Items using order id
                        OrdItems = [Select Id,Quantity,Product2.Name,Inventory__c,Sendable__c from OrderItem where OrderId=:OrdId and Sendable__c=True and Inventory__c=True];
                    }
                    catch(QueryException e){
                        System.debug('Error:'+e);
                    }
                    
                    
                    system.debug('OrdItems======>'+OrdItems);
                    system.debug('Scanned Id=====>'+scannedId);
                    system.debug('Ship Id=====>'+shipmentId);
                    
                    //query all returnable shipment Items
                    ShipmentItems=[Select Id,Actual_Return_Date__c,AssetID__c,Check_Out_Date__c,Exhibition__c,Expected_Return_Date__c,Inventory__c,Item_is_Packed__c,OrderID__c,OrderProductID__c,Packing_Status__c,ProductID__c,ProductID__r.Name,Quantity__c,Shipment__c,Weight_Kg__c,Weight_Lb__c,AssetId__r.Name,AssetId__r.SerialNumber from ShipmentItem__c where Shipment__c=:shipmentId and ProductID__r.Inventory__c=true and ProductID__r.Sendable__c=true]; 
                    
                    System.debug('ShipmentItems====>'+ShipmentItems);
                    
                    for(ShipmentItem__c Item:ShipmentItems){
                        if(Item.Actual_Return_Date__c!=Null){ //check if shipment is returned
                            System.debug('returned Item====>'+Item);
                            CheckedIn_Items.add(Item);
                        }
                    }
                    
                    System.debug('CheckedIn_Items====>'+CheckedIn_Items);
                    
                }
                
            }
            
            
        }
        
        
    }
}