unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Brand Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brand__c/fields/GES_Connect_Corporate_Accounts__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Corporate_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect - Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Brand</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Product_Theater__c.field-meta.xml
<CustomField>
    <fullName>Product_Theater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Theater</label>
    <referenceTo>Product_Theater__c</referenceTo>
    <relationshipLabel>Brand</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/Exhibit__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Exhibit</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exhibit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Exhibit__c/fields/Activity_Type_Exhibit_Instance_c__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type_Exhibit_Instance_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connet - Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Exhibit</relationshipLabel>
    <relationshipName>Activity_Type_Exhibit_Instance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/GES_Connect_Corporate_Accounts__c.object-meta.xml
<CustomObject>
    <description>Details for GES Connect - Corporate Accounts  for the Data Requirements purpose</description>
    <label>GES Connect - Corporate Accounts</label>
    <nameField>
        <displayFormat>GCA-{0000}</displayFormat>
        <label>GES Connect - Corporate Accounts</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect - Corporate Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Theater__c/Product_Theater__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Product Theater</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Product Theater Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Theater</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ExhibitBrandEditTest.cls
@isTest
Public Class ExhibitBrandEditTest{
    
    Public Static Testmethod void ExhibitBrandEdit1()
    {   
        GES_Connect_Corporate_Accounts__c parentCongress = GC_TestUtils.getTestCongress();
        Exhibit__c  exhibit= GC_TestUtils.getTestExhibit();
        Brand__c brand= GC_TestUtils.getTestBrand();
        brand.Product_Theater__c =exhibit.id;
        Test.setCurrentPageReference(new PageReference('Page.ExhibitBrandEdit'));
        System.currentPageReference().getParameters().put('congid',exhibit.Activity_Type_Exhibit_Instance_c__c);    
        System.currentPageReference().getParameters().put('exhibitid',exhibit.id);
        System.currentPageReference().getParameters().put('brandId',brand.Id);    
        System.currentPageReference().getParameters().put('ExhibitName',exhibit.Name);
        ExhibitBrandEdit eBrandCTRL= new ExhibitBrandEdit();
        

        eBrandCTRL.BrandSave();
        eBrandCTRL.BrandCancel();
        eBrandCTRL.gete(); 
        eBrandCTRL.getb();
        eBrandCTRL.geta();
        eBrandCTRL.changeBrandCatandBusUnit();
        eBrandCTRL.cancelOperation();
    }


}