unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Brand Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brand__c/fields/Brand_Category__c.field-meta.xml
<CustomField>
    <fullName>Brand_Category__c</fullName>
    <label>Therapeutic Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anti Infectives</fullName>
            </value>
            <value>
                <fullName>Biosimilars</fullName>
            </value>
            <value>
                <fullName>CentreOne</fullName>
            </value>
            <value>
                <fullName>Consumer Healthcare</fullName>
            </value>
            <value>
                <fullName>DoD</fullName>
            </value>
            <value>
                <fullName>Greenstone</fullName>
            </value>
            <value>
                <fullName>Inflammation and Immunology</fullName>
            </value>
            <value>
                <fullName>Internal Medicine (CV/Metabolics)</fullName>
            </value>
            <value>
                <fullName>Oncology</fullName>
            </value>
            <value>
                <fullName>Rare Diseases</fullName>
            </value>
            <value>
                <fullName>Sterile Injectables</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vaccines</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acrodat</fullName>
            </value>
            <value>
                <fullName>Alopeca</fullName>
            </value>
            <value>
                <fullName>Alt Site</fullName>
            </value>
            <value>
                <fullName>Anti Infectives</fullName>
            </value>
            <value>
                <fullName>Atgam</fullName>
            </value>
            <value>
                <fullName>Avelumab</fullName>
            </value>
            <value>
                <fullName>Bavencio</fullName>
            </value>
            <value>
                <fullName>BeneFIX</fullName>
            </value>
            <value>
                <fullName>BeneFIX (Europe Only)</fullName>
            </value>
            <value>
                <fullName>Besponsa</fullName>
            </value>
            <value>
                <fullName>Bosulif</fullName>
            </value>
            <value>
                <fullName>Braftovi</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>CentreOne</fullName>
            </value>
            <value>
                <fullName>Champix</fullName>
            </value>
            <value>
                <fullName>Chantix</fullName>
            </value>
            <value>
                <fullName>Consumables</fullName>
            </value>
            <value>
                <fullName>Consumer Above Brand</fullName>
            </value>
            <value>
                <fullName>Consumer Healthcare</fullName>
            </value>
            <value>
                <fullName>Cresemba</fullName>
            </value>
            <value>
                <fullName>Crisaborole</fullName>
            </value>
            <value>
                <fullName>Cutaquig</fullName>
            </value>
            <value>
                <fullName>Daurismo</fullName>
            </value>
            <value>
                <fullName>DoD</fullName>
            </value>
            <value>
                <fullName>Duavee</fullName>
            </value>
            <value>
                <fullName>eATG</fullName>
            </value>
            <value>
                <fullName>Ecalta</fullName>
            </value>
            <value>
                <fullName>Elelyso</fullName>
            </value>
            <value>
                <fullName>Eliquis</fullName>
            </value>
            <value>
                <fullName>Enbrel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>IM</fullName>
            </value>
            <value>
                <fullName>PIH</fullName>
            </value>
            <value>
                <fullName>CBO</fullName>
            </value>
            <value>
                <fullName>PBG</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <isActive>false</isActive>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>PEH</fullName>
                <isActive>false</isActive>
                <label>PEH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Funding_Owner__c.field-meta.xml
<CustomField>
    <fullName>Funding_Owner__c</fullName>
    <label>Funding Provider Owner</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Sponsorship_Costs_Estimated__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Costs_Estimated__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sponsorship Costs Estimated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/SponsorshipBrandDetailTest.cls
@isTest
Public Class SponsorshipBrandDetailTest{
Public Static Testmethod void SponsorshipBrandDetail()
{          
   Brand__c b =new Brand__c();
    b.Sponsorship_Costs_Estimated__c=325;
    b.Funding_Owner__c='Test';
    b.Brand_Category__c = 'Anti Infectives';
    b.Brand_Name__c = '	Acrodat';
    b.Business_Unit__c = 'CH';
    insert b;
    Test.setCurrentPageReference(new PageReference('Page.SponsorshipBrandDetail'));
    System.currentPageReference().getParameters().put('sponbrandid',b.id);
    ApexPages.StandardController sc = new ApexPages.standardController(b);
    SponsorshipBrandDetail sp = new SponsorshipBrandDetail();    
    sp.BrandSave();
    sp.BrandCancel();
    sp.getbr();   
   
}
}