unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Brand Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brand__c/fields/Congress_Lead__c.field-meta.xml
<CustomField>
    <fullName>Congress_Lead__c</fullName>
    <label>Congress Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Virginia Hayward</fullName>
            </value>
            <value>
                <fullName>Lee Kim</fullName>
            </value>
            <value>
                <fullName>Sandra Kusek</fullName>
            </value>
            <value>
                <fullName>Laine Mann</fullName>
            </value>
            <value>
                <fullName>Don Schmid</fullName>
            </value>
            <value>
                <fullName>Suthee Suvansri</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/GES_Connect_Corporate_Accounts__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Corporate_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect - Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Brand</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/Exhibit__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Exhibit</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exhibit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Exhibit__c/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <label>Activity Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>DOD</fullName>
                <isActive>false</isActive>
                <label>DOD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Activity_Type_Exhibit_Instance_c__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type_Exhibit_Instance_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connet - Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Exhibit</relationshipLabel>
    <relationshipName>Activity_Type_Exhibit_Instance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Booth_Length__c.field-meta.xml
<CustomField>
    <fullName>Booth_Length__c</fullName>
    <label>Booth Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Booth_Number__c.field-meta.xml
<CustomField>
    <fullName>Booth_Number__c</fullName>
    <label>Booth Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/GES_Connect_Corporate_Accounts__c.object-meta.xml
<CustomObject>
    <description>Details for GES Connect - Corporate Accounts  for the Data Requirements purpose</description>
    <label>GES Connect - Corporate Accounts</label>
    <nameField>
        <displayFormat>GCA-{0000}</displayFormat>
        <label>GES Connect - Corporate Accounts</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect - Corporate Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Acronym_of_Congress__c.field-meta.xml
<CustomField>
    <fullName>Acronym_of_Congress__c</fullName>
    <label>Acronym of Congress</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Association_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Contact_Name__c</fullName>
    <label>Association Contact Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <label>Association Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Congress_Website__c.field-meta.xml
<CustomField>
    <fullName>Congress_Website__c</fullName>
    <label>Congress Website</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Exhibit_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Close_Date__c</fullName>
    <label>Exhibit Close Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Exhibit_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Open_Date__c</fullName>
    <label>Exhibit Open Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Housing_Logistics_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Housing_Logistics_Vendor__c</fullName>
    <label>Housing Logistics Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCD Travel</fullName>
            </value>
            <value>
                <fullName>Am Ex</fullName>
            </value>
            <value>
                <fullName>CWT</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Name_of_Congress__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Congress__c</fullName>
    <label>Name of Congress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Number_of_rooms_Secured__c.field-meta.xml
<CustomField>
    <fullName>Number_of_rooms_Secured__c</fullName>
    <label>Number of Rooms Secured</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Number_of_rooms_to_Secure__c.field-meta.xml
<CustomField>
    <fullName>Number_of_rooms_to_Secure__c</fullName>
    <label>Number of Rooms to Secure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Meeting_Room__c/Meeting_Room__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Meeting Room</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Meeting Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Room</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Meeting_Room__c/fields/Congress__c.field-meta.xml
<CustomField>
    <fullName>Congress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Congress</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Meeting Room</relationshipLabel>
    <relationshipName>Meeting_Room</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product_Theater__c/Product_Theater__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Product Theater</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Product Theater Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Theater</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Theater__c/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <label>Activity Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
                <default>true</default>
                <label>5</label>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>DOD</fullName>
                <isActive>false</isActive>
                <label>DOD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product_Theater__c/fields/Congress__c.field-meta.xml
<CustomField>
    <fullName>Congress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Congress</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Product Theater</relationshipLabel>
    <relationshipName>Product_Theater</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsorship__c/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <label>Activity Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
                <default>true</default>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>DOD</fullName>
                <isActive>false</isActive>
                <label>DOD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Symposia__c/Symposia__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Symposia</label>
    <nameField>
        <displayFormat>SYI-{0000}</displayFormat>
        <label>Symposia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Symposia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Symposia__c/fields/Congress__c.field-meta.xml
<CustomField>
    <fullName>Congress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Congress</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Symposia</relationshipLabel>
    <relationshipName>Symposia</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CongressFinancialSummaryReportTest.cls
@isTest
public class CongressFinancialSummaryReportTest
{
    static testMethod void CongressFinancialSummaryReport()
    {
        GES_Connect_Corporate_Accounts__c gs=new GES_Connect_Corporate_Accounts__c();
        Brand__c br=new Brand__c(); 
        Exhibit__c ex=new Exhibit__c(); 
        gs.Exhibit_Close_Date__c=Date.parse('12/05/2017');
        gs.Exhibit_Open_Date__c=Date.parse('02/12/2017');
        gs.Acronym_of_Congress__c='as';
        gs.Name_of_Congress__c='test';
        gs.Congress_Website__c='www.google.com';
        gs.Association_Name__c ='Mary';
        gs.Association_Contact_Name__c ='Jhonny';
        gs.Housing_Logistics_Vendor__c = 'BCD Travel';
        gs.Number_of_rooms_Secured__c = 5;
        gs.Number_of_rooms_to_Secure__c = 6;
        insert gs;
        ex.Activity_Level__c='2';
        ex.Booth_Length__c=245;
        ex.Booth_Number__c='234';
        ex.Activity_Type_Exhibit_Instance_c__c=gs.id;
        ex.Congress_Lead__c ='Don Schmid';
        ex.GES_Congress_Manager__c='Debbie Hummel';
        insert ex;
        Sponsorship__c sp=new Sponsorship__c();
        sp.Sponsorship_Name__c='test';
        sp.Sponsorship__c=gs.id;
        sp.Congress_Lead__c ='Don Schmid';
        sp.GES_Congress_Manager__c='Debbie Hummel';        
        insert sp;
        Product_Theater__c pd=new Product_Theater__c();
        pd.Product_Theater_Name__c='test';
        pd.Congress__c=gs.id;
        pd.Congress_Lead__c ='Don Schmid';
        pd.GES_Congress_Manager__c='Debbie Hummel';
        insert pd;
        Symposia__c sy=new Symposia__c();
        sy.Symposia_Name__c='test';
        sy.Congress__c=gs.id;
        sy.Congress_Lead__c ='Don Schmid';
        sy.GES_Congress_Manager__c='Debbie Hummel';
        insert sy;
        Meeting_Room__c mt=new Meeting_Room__c();
        mt.Meeting_Room_Name__c='test';
        mt.Congress__c=gs.id;
        mt.Congress_Lead__c ='Don Schmid';
        mt.GES_Congress_Manager__c='Debbie Hummel';
        insert mt;
        br.Brand_Name__c='Eucrisa';
        br.GES_Congress_Manager__c='Purcell';
        br.Exhibit_Instance__c=ex.id;
        br.GES_Connect_Corporate_Accounts__c=gs.id;
        br.Sponsorship_Costs_Actual__c=4355;
        br.Sponsorship_Costs_Estimated__c=4000;
        br.Product_Theater_Costs_Actual__c=858;
        br.Product_Theater_Costs_Estimated__c=800;
        br.Symposia_Estimated_Cost__c=345;
        br.Symposia_Actual_Cost__c=300;
        br.Meeting_Room_Estimated_Cost__c=504;
        br.Meeting_Room_Actual_Cost__c=500;
        br.Symposia__c=sy.id;
        br.Sponsorship__c=sp.id;
        br.Product_Theater__c=pd.id;
        br.Meeting_Room__c=mt.id;
        br.Brand_Category__c= 'CentreOne' ;
        br.Business_Unit__c = 'CH';
        insert br;
        
        Test.setCurrentPageReference(new PageReference('Page.CongressFinancialSummaryReport'));
        System.currentPageReference().getParameters().put('id',gs.id);    
        ApexPages.StandardController sc=new ApexPages.StandardController(gs);   
        CongressFinancialSummaryReport cnFnSr=new CongressFinancialSummaryReport(sc);     
        cnFnSr.back();
        cnFnSr.save(); 
      }
}