unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Brand Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brand__c/fields/Canceled__c.field-meta.xml
<CustomField>
    <fullName>Canceled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Canceled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Congress_Lead__c.field-meta.xml
<CustomField>
    <fullName>Congress_Lead__c</fullName>
    <label>Congress Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Virginia Hayward</fullName>
            </value>
            <value>
                <fullName>Lee Kim</fullName>
            </value>
            <value>
                <fullName>Sandra Kusek</fullName>
            </value>
            <value>
                <fullName>Laine Mann</fullName>
            </value>
            <value>
                <fullName>Don Schmid</fullName>
            </value>
            <value>
                <fullName>Suthee Suvansri</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/GES_Congress_Manager__c.field-meta.xml
<CustomField>
    <fullName>GES_Congress_Manager__c</fullName>
    <label>GES Congress Manager</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Debbie Hummel</fullName>
            </value>
            <value>
                <fullName>Elena Fezzardi</fullName>
            </value>
            <value>
                <fullName>Eva McCartney</fullName>
            </value>
            <value>
                <fullName>Gail Griffith</fullName>
            </value>
            <value>
                <fullName>Ilysa Link</fullName>
            </value>
            <value>
                <fullName>Julia Noonan</fullName>
            </value>
            <value>
                <fullName>Linnell Navarro</fullName>
            </value>
            <value>
                <fullName>Michelle Pflug</fullName>
            </value>
            <value>
                <fullName>Stephanie Houck</fullName>
            </value>
            <value>
                <fullName>Tricia Purcell</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/GES_Connect_Corporate_Accounts__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Corporate_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect - Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Brand</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/Exhibit__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Exhibit</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exhibit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Exhibit__c/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <label>Activity Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>DOD</fullName>
                <isActive>false</isActive>
                <label>DOD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Activity_Type_Exhibit_Instance_c__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type_Exhibit_Instance_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connet - Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Exhibit</relationshipLabel>
    <relationshipName>Activity_Type_Exhibit_Instance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Booth_Length__c.field-meta.xml
<CustomField>
    <fullName>Booth_Length__c</fullName>
    <label>Booth Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Booth_Width__c.field-meta.xml
<CustomField>
    <fullName>Booth_Width__c</fullName>
    <label>Booth Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Congress_Lead__c.field-meta.xml
<CustomField>
    <fullName>Congress_Lead__c</fullName>
    <label>Congress Lead</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Don Schmid</fullName>
            </value>
            <value>
                <fullName>Laine Mann</fullName>
            </value>
            <value>
                <fullName>Lee Kim</fullName>
            </value>
            <value>
                <fullName>Sandra Kusek</fullName>
            </value>
            <value>
                <fullName>Suthee Suvansri</fullName>
            </value>
            <value>
                <fullName>Virginia Hayward</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
            </value>
            <value>
                <fullName>Carson, Jeffery</fullName>
                <isActive>false</isActive>
                <label>Carson, Jeffery</label>
            </value>
            <value>
                <fullName>Cristine Watrous</fullName>
                <isActive>false</isActive>
                <label>Cristine Watrous</label>
            </value>
            <value>
                <fullName>Hayward, Virginia</fullName>
                <isActive>false</isActive>
                <label>Hayward, Virginia</label>
            </value>
            <value>
                <fullName>Jeffery Carson</fullName>
                <isActive>false</isActive>
                <label>Jeffery Carson</label>
            </value>
            <value>
                <fullName>Kim, Lee</fullName>
                <isActive>false</isActive>
                <label>Kim, Lee</label>
            </value>
            <value>
                <fullName>Kusek, Sandra</fullName>
                <isActive>false</isActive>
                <label>Kusek, Sandra</label>
            </value>
            <value>
                <fullName>Mann, Laine</fullName>
                <isActive>false</isActive>
                <label>Mann, Laine</label>
            </value>
            <value>
                <fullName>Schmid, Don</fullName>
                <isActive>false</isActive>
                <label>Schmid, Don</label>
            </value>
            <value>
                <fullName>Suvansri, Suthee</fullName>
                <isActive>false</isActive>
                <label>Suvansri, Suthee</label>
            </value>
            <value>
                <fullName>Watrous, Cristine</fullName>
                <isActive>false</isActive>
                <label>Watrous, Cristine</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Exhibit_Name__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Name__c</fullName>
    <label>Exhibit Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/GES_Congress_Manager__c.field-meta.xml
<CustomField>
    <fullName>GES_Congress_Manager__c</fullName>
    <label>GES Congress Manager</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andrea Speckin</fullName>
            </value>
            <value>
                <fullName>Ashley Simmons</fullName>
            </value>
            <value>
                <fullName>Eva Keogh</fullName>
            </value>
            <value>
                <fullName>Francesca Molisso</fullName>
            </value>
            <value>
                <fullName>Gail Griffith</fullName>
            </value>
            <value>
                <fullName>Jessica Bodner</fullName>
            </value>
            <value>
                <fullName>Kathy Deneen</fullName>
            </value>
            <value>
                <fullName>Linnell Navarro</fullName>
            </value>
            <value>
                <fullName>Melinda Powers</fullName>
            </value>
            <value>
                <fullName>Tara Nigro</fullName>
            </value>
            <value>
                <fullName>Wendy Irvine</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/GES_Connect_Corporate_Accounts__c.object-meta.xml
<CustomObject>
    <description>Details for GES Connect - Corporate Accounts  for the Data Requirements purpose</description>
    <label>GES Connect - Corporate Accounts</label>
    <nameField>
        <displayFormat>GCA-{0000}</displayFormat>
        <label>GES Connect - Corporate Accounts</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect - Corporate Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Association_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Contact_Name__c</fullName>
    <label>Association Contact Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <label>Association Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Housing_Logistics_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Housing_Logistics_Vendor__c</fullName>
    <label>Housing Logistics Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCD Travel</fullName>
            </value>
            <value>
                <fullName>Am Ex</fullName>
            </value>
            <value>
                <fullName>CWT</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Name_of_Congress__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Congress__c</fullName>
    <label>Name of Congress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Number_of_rooms_Secured__c.field-meta.xml
<CustomField>
    <fullName>Number_of_rooms_Secured__c</fullName>
    <label>Number of Rooms Secured</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Shipping_Street_c__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Street_c__c</fullName>
    <label>Adv. Whs. Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>GES_Connet_Corporate_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ExhibitTriggerTest.cls
@isTest
public class ExhibitTriggerTest {
    public static testMethod void testMethod1() {
        GC_Connect2_Show__c cgs=new GC_Connect2_Show__c();   
        cgs.Show_Start_Date__c=Date.parse('3/4/2015');
        cgs.Show_End_Date__c=Date.parse('3/4/2015');
        insert cgs; 
        
        GES_Connect_Corporate_Accounts__c  gca=new GES_Connect_Corporate_Accounts__c();  
        gca.Name_of_Congress__c='Test';
        gca.Shipping_Street_c__c='Bangalore';
        gca.Show_Name__c=cgs.id;
        gca.Housing_Logistics_Vendor__c = 'BCD Travel';
        gca.Number_of_rooms_Secured__c = 6;
        gca.Association_Contact_Name__c='SLK Soft';
        gca.Association_Name__c='rksinha';
        insert gca;  
        
        List<Exhibit__c> listExhibit = new List<Exhibit__c>();
        Exhibit__c ex = new Exhibit__c();
        ex.Booth_Length__c = 10;
        ex.Booth_Width__c = 10;
        ex.Exhibit_Name__c = 'Test';
        ex.Activity_Level__c = '1';
        ex.Activity_Type_Exhibit_Instance_c__c =  gca.Id;
        ex.Congress_Lead__c = 'Don Schmid';
        ex.GES_Congress_Manager__c = 'Debbie Hummel';
        
        Exhibit__c ex1 = new Exhibit__c();
        ex1.Booth_Length__c = 10;
        ex1.Booth_Width__c = 10;
        ex1.Exhibit_Name__c = 'Test';
        ex1.Activity_Level__c = '1';
        ex1.Canceled__c = true;
        ex1.Activity_Type_Exhibit_Instance_c__c =  gca.Id;
        ex1.Congress_Lead__c = 'Don Schmid';
        ex1.GES_Congress_Manager__c = 'Debbie Hummel';
        listExhibit.add(ex);
        listExhibit.add(ex1);
        insert listExhibit;
        
        Brand__c b5 = new Brand__c();
        b5.Brand_Name__c = 'Test';
        b5.GES_Congress_Manager__c = 'McCartney, Eva';
        b5.Exhibit_Instance__c = ex.Id;
        b5.GES_Connect_Corporate_Accounts__c = gca.Id;
        b5.Brand_Category__c = 'Oncology' ;
        b5.Business_Unit__c = 'CH' ;
        insert b5;
        
        ex.Canceled__c = true;
        update ex;
    }
}