unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Brand Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brand__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acrodat</fullName>
            </value>
            <value>
                <fullName>Alopeca</fullName>
            </value>
            <value>
                <fullName>Alt Site</fullName>
            </value>
            <value>
                <fullName>Anti Infectives</fullName>
            </value>
            <value>
                <fullName>Atgam</fullName>
            </value>
            <value>
                <fullName>Avelumab</fullName>
            </value>
            <value>
                <fullName>Bavencio</fullName>
            </value>
            <value>
                <fullName>BeneFIX</fullName>
            </value>
            <value>
                <fullName>BeneFIX (Europe Only)</fullName>
            </value>
            <value>
                <fullName>Besponsa</fullName>
            </value>
            <value>
                <fullName>Bosulif</fullName>
            </value>
            <value>
                <fullName>Braftovi</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>CentreOne</fullName>
            </value>
            <value>
                <fullName>Champix</fullName>
            </value>
            <value>
                <fullName>Chantix</fullName>
            </value>
            <value>
                <fullName>Consumables</fullName>
            </value>
            <value>
                <fullName>Consumer Above Brand</fullName>
            </value>
            <value>
                <fullName>Consumer Healthcare</fullName>
            </value>
            <value>
                <fullName>Cresemba</fullName>
            </value>
            <value>
                <fullName>Crisaborole</fullName>
            </value>
            <value>
                <fullName>Cutaquig</fullName>
            </value>
            <value>
                <fullName>Daurismo</fullName>
            </value>
            <value>
                <fullName>DoD</fullName>
            </value>
            <value>
                <fullName>Duavee</fullName>
            </value>
            <value>
                <fullName>eATG</fullName>
            </value>
            <value>
                <fullName>Ecalta</fullName>
            </value>
            <value>
                <fullName>Elelyso</fullName>
            </value>
            <value>
                <fullName>Eliquis</fullName>
            </value>
            <value>
                <fullName>Enbrel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Canceled__c.field-meta.xml
<CustomField>
    <fullName>Canceled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Canceled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Congress_Lead__c.field-meta.xml
<CustomField>
    <fullName>Congress_Lead__c</fullName>
    <label>Congress Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Virginia Hayward</fullName>
            </value>
            <value>
                <fullName>Lee Kim</fullName>
            </value>
            <value>
                <fullName>Sandra Kusek</fullName>
            </value>
            <value>
                <fullName>Laine Mann</fullName>
            </value>
            <value>
                <fullName>Don Schmid</fullName>
            </value>
            <value>
                <fullName>Suthee Suvansri</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/GES_Congress_Manager__c.field-meta.xml
<CustomField>
    <fullName>GES_Congress_Manager__c</fullName>
    <label>GES Congress Manager</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Debbie Hummel</fullName>
            </value>
            <value>
                <fullName>Elena Fezzardi</fullName>
            </value>
            <value>
                <fullName>Eva McCartney</fullName>
            </value>
            <value>
                <fullName>Gail Griffith</fullName>
            </value>
            <value>
                <fullName>Ilysa Link</fullName>
            </value>
            <value>
                <fullName>Julia Noonan</fullName>
            </value>
            <value>
                <fullName>Linnell Navarro</fullName>
            </value>
            <value>
                <fullName>Michelle Pflug</fullName>
            </value>
            <value>
                <fullName>Stephanie Houck</fullName>
            </value>
            <value>
                <fullName>Tricia Purcell</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/GES_Connect_Corporate_Accounts__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Corporate_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect - Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Brand</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Product_Theater__c.field-meta.xml
<CustomField>
    <fullName>Product_Theater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Theater</label>
    <referenceTo>Product_Theater__c</referenceTo>
    <relationshipLabel>Brand</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/GES_Connect_Corporate_Accounts__c.object-meta.xml
<CustomObject>
    <description>Details for GES Connect - Corporate Accounts  for the Data Requirements purpose</description>
    <label>GES Connect - Corporate Accounts</label>
    <nameField>
        <displayFormat>GCA-{0000}</displayFormat>
        <label>GES Connect - Corporate Accounts</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect - Corporate Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Association_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Contact_Name__c</fullName>
    <label>Association Contact Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <label>Association Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Housing_Logistics_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Housing_Logistics_Vendor__c</fullName>
    <label>Housing Logistics Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCD Travel</fullName>
            </value>
            <value>
                <fullName>Am Ex</fullName>
            </value>
            <value>
                <fullName>CWT</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Name_of_Congress__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Congress__c</fullName>
    <label>Name of Congress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Number_of_rooms_Secured__c.field-meta.xml
<CustomField>
    <fullName>Number_of_rooms_Secured__c</fullName>
    <label>Number of Rooms Secured</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Shipping_Street_c__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Street_c__c</fullName>
    <label>Adv. Whs. Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>GES_Connet_Corporate_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product_Theater__c/Product_Theater__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Product Theater</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Product Theater Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Theater</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Theater__c/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <label>Activity Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
                <default>true</default>
                <label>5</label>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>DOD</fullName>
                <isActive>false</isActive>
                <label>DOD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product_Theater__c/fields/Congress__c.field-meta.xml
<CustomField>
    <fullName>Congress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Congress</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Product Theater</relationshipLabel>
    <relationshipName>Product_Theater</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product_Theater__c/fields/Congress_Lead__c.field-meta.xml
<CustomField>
    <fullName>Congress_Lead__c</fullName>
    <label>Congress Lead</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Don Schmid</fullName>
            </value>
            <value>
                <fullName>Laine Mann</fullName>
            </value>
            <value>
                <fullName>Lee Kim</fullName>
            </value>
            <value>
                <fullName>Sandra Kusek</fullName>
            </value>
            <value>
                <fullName>Suthee Suvansri</fullName>
            </value>
            <value>
                <fullName>Virginia Hayward</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product_Theater__c/fields/Product_Theater_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Theater_Name__c</fullName>
    <label>Product Theater Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ProductThearerTriggerTest.cls
@isTest
public class ProductThearerTriggerTest {

    public static testMethod void testMethod1() {
        GC_Connect2_Show__c cgs=new GC_Connect2_Show__c();   
        cgs.Show_Start_Date__c=Date.parse('3/4/2015');
        cgs.Show_End_Date__c=Date.parse('3/4/2015');
        insert cgs; 
        
        GES_Connect_Corporate_Accounts__c  gca=new GES_Connect_Corporate_Accounts__c();  
        gca.Name_of_Congress__c='Test';
        gca.Shipping_Street_c__c='Bangalore';
        gca.Show_Name__c=cgs.id;
        gca.Housing_Logistics_Vendor__c = 'BCD Travel';
        gca.Number_of_rooms_Secured__c = 6;
        gca.Association_Contact_Name__c='SLK Soft';
        gca.Association_Name__c='rksinha';
        insert gca;  
        
        List<Product_Theater__c> listProductTheater = new List<Product_Theater__c>();
        Product_Theater__c pt = new Product_Theater__c();
        pt.Product_Theater_Name__c = 'Test';
        pt.Activity_Level__c = '1';
        pt.Congress__c =  gca.Id;
        pt.Congress_Lead__c = 'Don Schmid';
        pt.GES_Congress_Manager__c = 'Debbie Hummel';
        
        Product_Theater__c pt1 = new Product_Theater__c();
        pt.Product_Theater_Name__c = 'Test';
        pt1.Activity_Level__c = '1';
        pt1.Canceled__c = true;
        pt1.Congress__c =  gca.Id;
        pt1.Congress_Lead__c = 'Don Schmid';
        pt1.GES_Congress_Manager__c = 'Debbie Hummel';
        listProductTheater.add(pt);
        listProductTheater.add(pt1);
        insert listProductTheater;
        
        Brand__c b5 = new Brand__c();
        b5.Brand_Name__c = 'Test';
        b5.GES_Congress_Manager__c = 'McCartney, Eva';
        b5.Product_Theater__c = pt.Id;
        b5.GES_Connect_Corporate_Accounts__c = gca.Id;
        b5.Brand_Category__c = 'Oncology' ;
        b5.Business_Unit__c = 'CH' ;
        insert b5;
        
        pt.Canceled__c = true;
        update pt;
    }
}