unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Brand Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brand__c/fields/Congress_Lead__c.field-meta.xml
<CustomField>
    <fullName>Congress_Lead__c</fullName>
    <label>Congress Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Virginia Hayward</fullName>
            </value>
            <value>
                <fullName>Lee Kim</fullName>
            </value>
            <value>
                <fullName>Sandra Kusek</fullName>
            </value>
            <value>
                <fullName>Laine Mann</fullName>
            </value>
            <value>
                <fullName>Don Schmid</fullName>
            </value>
            <value>
                <fullName>Suthee Suvansri</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/GES_Connect_Corporate_Accounts__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Corporate_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect - Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Brand</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/Exhibit__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Exhibit</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exhibit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Exhibit__c/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <label>Activity Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>DOD</fullName>
                <isActive>false</isActive>
                <label>DOD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Booth_Length__c.field-meta.xml
<CustomField>
    <fullName>Booth_Length__c</fullName>
    <label>Booth Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Booth_Width__c.field-meta.xml
<CustomField>
    <fullName>Booth_Width__c</fullName>
    <label>Booth Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Exhibit__c/fields/Exhibit_Name__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Name__c</fullName>
    <label>Exhibit Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/GES_Connect_Corporate_Accounts__c.object-meta.xml
<CustomObject>
    <description>Details for GES Connect - Corporate Accounts  for the Data Requirements purpose</description>
    <label>GES Connect - Corporate Accounts</label>
    <nameField>
        <displayFormat>GCA-{0000}</displayFormat>
        <label>GES Connect - Corporate Accounts</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect - Corporate Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Acronym_of_Congress__c.field-meta.xml
<CustomField>
    <fullName>Acronym_of_Congress__c</fullName>
    <label>Acronym of Congress</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Association_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Contact_Name__c</fullName>
    <label>Association Contact Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <label>Association Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Exhibit_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Close_Date__c</fullName>
    <label>Exhibit Close Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Exhibit_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Open_Date__c</fullName>
    <label>Exhibit Open Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Housing_Logistics_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Housing_Logistics_Vendor__c</fullName>
    <label>Housing Logistics Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCD Travel</fullName>
            </value>
            <value>
                <fullName>Am Ex</fullName>
            </value>
            <value>
                <fullName>CWT</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Name_of_Congress__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Congress__c</fullName>
    <label>Name of Congress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Number_of_rooms_Secured__c.field-meta.xml
<CustomField>
    <fullName>Number_of_rooms_Secured__c</fullName>
    <label>Number of Rooms Secured</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Shipping_Street_c__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Street_c__c</fullName>
    <label>Adv. Whs. Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Shipping_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Zip_Postal_Code__c</fullName>
    <label>Shipping Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Meeting_Room__c/Meeting_Room__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Meeting Room</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Meeting Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Room</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Meeting_Room__c/fields/Congress__c.field-meta.xml
<CustomField>
    <fullName>Congress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Congress</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Meeting Room</relationshipLabel>
    <relationshipName>Meeting_Room</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product_Theater__c/Product_Theater__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Product Theater</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Product Theater Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Theater</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Theater__c/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <label>Activity Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
                <default>true</default>
                <label>5</label>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>DOD</fullName>
                <isActive>false</isActive>
                <label>DOD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product_Theater__c/fields/Congress__c.field-meta.xml
<CustomField>
    <fullName>Congress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Congress</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Product Theater</relationshipLabel>
    <relationshipName>Product_Theater</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsorship__c/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <label>Activity Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
                <default>true</default>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>DOD</fullName>
                <isActive>false</isActive>
                <label>DOD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Symposia__c/Symposia__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Symposia</label>
    <nameField>
        <displayFormat>SYI-{0000}</displayFormat>
        <label>Symposia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Symposia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Symposia__c/fields/Congress__c.field-meta.xml
<CustomField>
    <fullName>Congress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Congress</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Symposia</relationshipLabel>
    <relationshipName>Symposia</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CongressTriggersTest.cls
@isTest(SeeAllData=true)
public class CongressTriggersTest 
{
    public static testMethod void exhbitTrigger() 
    {
        GES_Connect_Corporate_Accounts__c  gca=new GES_Connect_Corporate_Accounts__c();  
        gca.Name_of_Congress__c='Test';
        gca.Acronym_of_Congress__c = 'TEST';
        gca.Exhibit_Open_Date__c = Date.Today();
        gca.Exhibit_Close_Date__c = Date.Today();
        gca.Facility_Name__c = 'Test';
        gca.Shipping_City__c = 'Atlanta';
        gca.Shipping_Street_c__c='Bangalore';
        gca.Shipping_Zip_Postal_Code__c = '23';
        gca.CurrencyIsoCode='USD';
        gca.Housing_Logistics_Vendor__c = 'BCD Travel';
        gca.Number_of_rooms_Secured__c = 6;
        gca.Association_Contact_Name__c='SLK Soft';
        gca.Association_Name__c='rksinha';
        
        insert gca;
        
        Exhibit__c ex = new Exhibit__c();
        ex.Booth_Length__c = 10;
        ex.Booth_Width__c = 10;
        ex.Exhibit_Name__c = 'Test';
        ex.Activity_Level__c = '1';
        ex.Congress_Lead__c = 'Lee Kim';
        ex.GES_Congress_Manager__c = 'Debbie Hummel';
        ex.Activity_Type_Exhibit_Instance_c__c =  gca.Id;
        insert ex;
        
        Brand__c b = new Brand__c();
        b.Brand_Name__c = 'Test';
        b.GES_Congress_Manager__c = 'Debbie Hummel';
        b.Exhibit_Instance__c = ex.Id;
        b.GES_Connect_Corporate_Accounts__c = gca.Id;
        b.CurrencyIsoCode='USD';
        b.Brand_Category__c = 'Anti Infectives' ;
        b.Business_Unit__c = 'CH';
        insert b;
        Brand__c b1 = new Brand__c();
        b1.Brand_Name__c = 'Test';
        b1.GES_Congress_Manager__c = 'Debbie Hummel';
        b1.Exhibit_Instance__c = ex.Id;
        b1.GES_Connect_Corporate_Accounts__c = gca.Id;
        b1.CurrencyIsoCode='USD';
        b1.Brand_Category__c = 'Anti Infectives' ;
        b1.Business_Unit__c = 'CH';
        
        insert b1;
        
		GES_Connect_Corporate_Accounts__c  updateGCA=new GES_Connect_Corporate_Accounts__c();  
		updateGCA = [SELECT ID,Congress_Cancelled__c FROM GES_Connect_Corporate_Accounts__c WHERE Id = :gca.Id];
        updateGCA.Congress_Cancelled__c = true;
        update updateGCA; 
        gca.CurrencyIsoCode='GBP';
        update gca;
        
        Exhibit__c  updateEX=new Exhibit__c();  
		updateEX = [SELECT ID,Canceled__c FROM Exhibit__c WHERE Id = :ex.Id];
        updateEX.Canceled__c = true;
        update updateEX;
        
        GES_Connect_Corporate_Accounts__c  updateGCA1=new GES_Connect_Corporate_Accounts__c();  
		updateGCA1 = [SELECT ID,Congress_Cancelled__c FROM GES_Connect_Corporate_Accounts__c WHERE Id = :gca.Id];
        updateGCA1.Congress_Cancelled__c = false;
        update updateGCA1;
        
    }
    
    public static testMethod void sponsorshipTrigger() 
    {
        GES_Connect_Corporate_Accounts__c  gca=new GES_Connect_Corporate_Accounts__c();  
        gca.Name_of_Congress__c='Test';
        gca.Acronym_of_Congress__c = 'TEST';
        gca.Exhibit_Open_Date__c = Date.Today();
        gca.Exhibit_Close_Date__c = Date.Today();
        gca.Facility_Name__c = 'Test';
        gca.Shipping_City__c = 'Atlanta';
        gca.Shipping_Street_c__c='Bangalore';
        gca.Shipping_Zip_Postal_Code__c = '23';
        gca.Housing_Logistics_Vendor__c = 'BCD Travel';
        gca.Number_of_rooms_Secured__c = 6;
        gca.Association_Contact_Name__c='SLK Soft';
        gca.Association_Name__c='rksinha';
        insert gca;
        
        Sponsorship__c sp = new Sponsorship__c();
        sp.Sponsorship_Name__c = 'Test';
        sp.Activity_Level__c = '1';
        sp.Sponsorship__c = gca.Id;
        sp.Congress_Lead__c = 'Lee Kim';
        sp.GES_Congress_Manager__c = 'Debbie Hummel';
        insert sp;
        
        Brand__c b = new Brand__c();
        b.Brand_Name__c = 'Test';
        b.GES_Congress_Manager__c = 'McCartney, Eva';
        b.Sponsorship__c = sp.Id;
        b.GES_Connect_Corporate_Accounts__c = gca.Id;
        b.Brand_Category__c = 'Anti Infectives' ;
        b.Business_Unit__c = 'CH';
        insert b;
        
        GES_Connect_Corporate_Accounts__c  updateGCA=new GES_Connect_Corporate_Accounts__c();  
		updateGCA = [SELECT ID,Congress_Cancelled__c FROM GES_Connect_Corporate_Accounts__c WHERE Id = :gca.Id];
        updateGCA.Congress_Cancelled__c = true;
        update updateGCA;
        
        Sponsorship__c  updateSP=new Sponsorship__c();  
		updateSP = [SELECT ID,Canceled__c FROM Sponsorship__c WHERE Id = :sp.Id];
        updateSP.Canceled__c = true;
        update updateSP;
        
        GES_Connect_Corporate_Accounts__c  updateGCA1=new GES_Connect_Corporate_Accounts__c();  
		updateGCA1 = [SELECT ID,Congress_Cancelled__c FROM GES_Connect_Corporate_Accounts__c WHERE Id = :gca.Id];
        updateGCA1.Congress_Cancelled__c = false;
        update updateGCA1;
        
        //sp.Canceled__c = true;
        //update sp;
    }
    
    public static testMethod void symposiaTrigger() 
    {
        GES_Connect_Corporate_Accounts__c  gca=new GES_Connect_Corporate_Accounts__c();  
        gca.Name_of_Congress__c='Test';
        gca.Acronym_of_Congress__c = 'TEST';
        gca.Exhibit_Open_Date__c = Date.Today();
        gca.Exhibit_Close_Date__c = Date.Today();
        gca.Facility_Name__c = 'Test';
        gca.Shipping_City__c = 'Atlanta';
        gca.Shipping_Street_c__c='Bangalore';
        gca.Shipping_Zip_Postal_Code__c = '23';
        gca.Housing_Logistics_Vendor__c = 'BCD Travel';
        gca.Number_of_rooms_Secured__c = 6;
        gca.Association_Contact_Name__c='SLK Soft';
        gca.Association_Name__c='rksinha';
        insert gca;
        
        Symposia__c sy = new Symposia__c();
        sy.Activity_Level__c = '2';
        sy.Symposia_Name__c = 'Test';
        sy.Congress__c = gca.Id;
        sy.Congress_Lead__c = 'Lee Kim';
        sy.GES_Congress_Manager__c = 'Debbie Hummel';
        insert sy;
        
        Brand__c b = new Brand__c();
        b.Brand_Name__c = 'Test';
        b.GES_Congress_Manager__c = 'McCartney, Eva';
        b.Symposia__c = sy.Id;
        b.GES_Connect_Corporate_Accounts__c = gca.Id;
        b.Brand_Category__c = 'Anti Infectives' ;
        b.Business_Unit__c = 'CH';
        insert b;
        
        GES_Connect_Corporate_Accounts__c  updateGCA=new GES_Connect_Corporate_Accounts__c();  
		updateGCA = [SELECT ID,Congress_Cancelled__c FROM GES_Connect_Corporate_Accounts__c WHERE Id = :gca.Id];
        updateGCA.Congress_Cancelled__c = true;
        update updateGCA;
        
        Symposia__c  updateSYM=new Symposia__c();  
		updateSYM = [SELECT ID,Canceled__c FROM Symposia__c WHERE Id = :sy.Id];
        updateSYM.Canceled__c = true;
        update updateSYM;
        
        GES_Connect_Corporate_Accounts__c  updateGCA1=new GES_Connect_Corporate_Accounts__c();  
		updateGCA1 = [SELECT ID,Congress_Cancelled__c FROM GES_Connect_Corporate_Accounts__c WHERE Id = :gca.Id];
        updateGCA1.Congress_Cancelled__c = false;
        update updateGCA1;
        
       // sy.Canceled__c = true;
        //update sy;
    }
    
    public static testMethod void meetingRoomTrigger() 
    {
        GES_Connect_Corporate_Accounts__c  gca=new GES_Connect_Corporate_Accounts__c();  
        gca.Name_of_Congress__c='Test';
        gca.Acronym_of_Congress__c = 'TEST';
        gca.Exhibit_Open_Date__c = Date.Today();
        gca.Exhibit_Close_Date__c = Date.Today();
        gca.Facility_Name__c = 'Test';
        gca.Shipping_City__c = 'Atlanta';
        gca.Shipping_Street_c__c='Bangalore';
        gca.Shipping_Zip_Postal_Code__c = '23';
        gca.Housing_Logistics_Vendor__c = 'BCD Travel';
        gca.Number_of_rooms_Secured__c = 6;
        gca.Association_Contact_Name__c='SLK Soft';
        gca.Association_Name__c='rksinha';
        insert gca;
        
        Meeting_Room__c mr = new Meeting_Room__c();
        mr.Activity_Level__c = '1';
        mr.Meeting_Room_Name__c = 'Test';
        mr.Congress__c = gca.Id;
        mr.Congress_Lead__c = 'Lee Kim';
        mr.GES_Congress_Manager__c = 'Debbie Hummel';
        insert mr;
        
        Brand__c b = new Brand__c();
        b.Brand_Name__c = 'Test';
        b.Brand_Category__c = 'Anti Infectives' ;
        b.Business_Unit__c = 'CH';
        b.GES_Congress_Manager__c = 'McCartney, Eva';
        b.Meeting_Room__c = mr.Id;
        b.GES_Connect_Corporate_Accounts__c = gca.Id;
        insert b;
        
        GES_Connect_Corporate_Accounts__c  updateGCA=new GES_Connect_Corporate_Accounts__c();  
		updateGCA = [SELECT ID,Congress_Cancelled__c FROM GES_Connect_Corporate_Accounts__c WHERE Id = :gca.Id];
        updateGCA.Congress_Cancelled__c = true;
        update updateGCA;
        
        Meeting_Room__c  updateMR=new Meeting_Room__c();  
		updateMR = [SELECT ID,Canceled__c FROM Meeting_Room__c WHERE Id = :mr.Id];
        updateMR.Canceled__c = true;
        update updateMR;
        
        GES_Connect_Corporate_Accounts__c  updateGCA1=new GES_Connect_Corporate_Accounts__c();  
		updateGCA1 = [SELECT ID,Congress_Cancelled__c FROM GES_Connect_Corporate_Accounts__c WHERE Id = :gca.Id];
        updateGCA1.Congress_Cancelled__c = false;
        update updateGCA1;
        
        //mr.Canceled__c = true;
        //update mr;
    }
    
    public static testMethod void productTheatreTrigger() 
    {
        GES_Connect_Corporate_Accounts__c  gca=new GES_Connect_Corporate_Accounts__c();  
        gca.Name_of_Congress__c='Test';
        gca.Acronym_of_Congress__c = 'TEST';
        gca.Exhibit_Open_Date__c = Date.Today();
        gca.Exhibit_Close_Date__c = Date.Today();
        gca.Facility_Name__c = 'Test';
        gca.Shipping_City__c = 'Atlanta';
        gca.Shipping_Street_c__c='Bangalore';
        gca.Shipping_Zip_Postal_Code__c = '23';
        gca.Housing_Logistics_Vendor__c = 'BCD Travel';
        gca.Number_of_rooms_Secured__c = 6;
        gca.Association_Contact_Name__c='SLK Soft';
        gca.Association_Name__c='rksinha';
        insert gca;
        
        Product_Theater__c pt = new Product_Theater__c();
        pt.Activity_Level__c = '1';
        pt.Product_Theater_Name__c = 'Test';
        pt.Congress__c = gca.Id;
        pt.Congress_Lead__c = 'Lee Kim';
        pt.GES_Congress_Manager__c = 'Debbie Hummel';
        insert pt;
        
        Brand__c b = new Brand__c();
        b.Brand_Name__c = 'Test';
        b.GES_Congress_Manager__c = 'McCartney, Eva';
        b.Product_Theater__c = pt.Id;
        b.GES_Connect_Corporate_Accounts__c = gca.Id;
        b.Brand_Category__c = 'Anti Infectives' ;
        b.Business_Unit__c = 'CH';
        insert b;
        
        GES_Connect_Corporate_Accounts__c  updateGCA=new GES_Connect_Corporate_Accounts__c();  
		updateGCA = [SELECT ID,Congress_Cancelled__c FROM GES_Connect_Corporate_Accounts__c WHERE Id = :gca.Id];
        updateGCA.Congress_Cancelled__c = true;
        update updateGCA;
        
        Product_Theater__c  updatePT=new Product_Theater__c();  
		updatePT = [SELECT ID,Canceled__c FROM Product_Theater__c WHERE Id = :pt.Id];
        updatePT.Canceled__c = true;
        update updatePT;
        
        GES_Connect_Corporate_Accounts__c  updateGCA1=new GES_Connect_Corporate_Accounts__c();  
		updateGCA1 = [SELECT ID,Congress_Cancelled__c FROM GES_Connect_Corporate_Accounts__c WHERE Id = :gca.Id];
        updateGCA1.Congress_Cancelled__c = false;
        update updateGCA1; 
    }
}