unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Brand Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brand__c/fields/Brand_Category__c.field-meta.xml
<CustomField>
    <fullName>Brand_Category__c</fullName>
    <label>Therapeutic Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anti Infectives</fullName>
            </value>
            <value>
                <fullName>Biosimilars</fullName>
            </value>
            <value>
                <fullName>CentreOne</fullName>
            </value>
            <value>
                <fullName>Consumer Healthcare</fullName>
            </value>
            <value>
                <fullName>DoD</fullName>
            </value>
            <value>
                <fullName>Greenstone</fullName>
            </value>
            <value>
                <fullName>Inflammation and Immunology</fullName>
            </value>
            <value>
                <fullName>Internal Medicine (CV/Metabolics)</fullName>
            </value>
            <value>
                <fullName>Oncology</fullName>
            </value>
            <value>
                <fullName>Rare Diseases</fullName>
            </value>
            <value>
                <fullName>Sterile Injectables</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vaccines</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acrodat</fullName>
            </value>
            <value>
                <fullName>Alopeca</fullName>
            </value>
            <value>
                <fullName>Alt Site</fullName>
            </value>
            <value>
                <fullName>Anti Infectives</fullName>
            </value>
            <value>
                <fullName>Atgam</fullName>
            </value>
            <value>
                <fullName>Avelumab</fullName>
            </value>
            <value>
                <fullName>Bavencio</fullName>
            </value>
            <value>
                <fullName>BeneFIX</fullName>
            </value>
            <value>
                <fullName>BeneFIX (Europe Only)</fullName>
            </value>
            <value>
                <fullName>Besponsa</fullName>
            </value>
            <value>
                <fullName>Bosulif</fullName>
            </value>
            <value>
                <fullName>Braftovi</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>CentreOne</fullName>
            </value>
            <value>
                <fullName>Champix</fullName>
            </value>
            <value>
                <fullName>Chantix</fullName>
            </value>
            <value>
                <fullName>Consumables</fullName>
            </value>
            <value>
                <fullName>Consumer Above Brand</fullName>
            </value>
            <value>
                <fullName>Consumer Healthcare</fullName>
            </value>
            <value>
                <fullName>Cresemba</fullName>
            </value>
            <value>
                <fullName>Crisaborole</fullName>
            </value>
            <value>
                <fullName>Cutaquig</fullName>
            </value>
            <value>
                <fullName>Daurismo</fullName>
            </value>
            <value>
                <fullName>DoD</fullName>
            </value>
            <value>
                <fullName>Duavee</fullName>
            </value>
            <value>
                <fullName>eATG</fullName>
            </value>
            <value>
                <fullName>Ecalta</fullName>
            </value>
            <value>
                <fullName>Elelyso</fullName>
            </value>
            <value>
                <fullName>Eliquis</fullName>
            </value>
            <value>
                <fullName>Enbrel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Brand_Team_Contact__c.field-meta.xml
<CustomField>
    <fullName>Brand_Team_Contact__c</fullName>
    <label>Brand Team Contact</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adamczyk, Alice</fullName>
            </value>
            <value>
                <fullName>Akkad, Fouad</fullName>
            </value>
            <value>
                <fullName>Alitto, Liana</fullName>
            </value>
            <value>
                <fullName>Alper (Schubach), Jen</fullName>
            </value>
            <value>
                <fullName>Andrei, Elisa</fullName>
            </value>
            <value>
                <fullName>Anjos, Suzana</fullName>
            </value>
            <value>
                <fullName>Apostolakis, Yannis</fullName>
            </value>
            <value>
                <fullName>Appel, Pam</fullName>
            </value>
            <value>
                <fullName>Appetiti, Valentina</fullName>
            </value>
            <value>
                <fullName>Arghir, Andrei</fullName>
            </value>
            <value>
                <fullName>Bagchi, Madhavi</fullName>
            </value>
            <value>
                <fullName>Bakken, Dan</fullName>
            </value>
            <value>
                <fullName>Ilana Barishman</fullName>
                <label>Barishman, Ilana</label>
            </value>
            <value>
                <fullName>Bean, Erika</fullName>
            </value>
            <value>
                <fullName>Beck, Elizabeth</fullName>
            </value>
            <value>
                <fullName>Belenkiy, Ilya</fullName>
            </value>
            <value>
                <fullName>Bhalla, Atul</fullName>
            </value>
            <value>
                <fullName>Boesch, Jerry</fullName>
            </value>
            <value>
                <fullName>Bradatan, Bogdan</fullName>
            </value>
            <value>
                <fullName>Brand, Lyndsey</fullName>
            </value>
            <value>
                <fullName>Bugbee, Todd</fullName>
            </value>
            <value>
                <fullName>Burnett, Beth</fullName>
            </value>
            <value>
                <fullName>Carmen, Maria</fullName>
            </value>
            <value>
                <fullName>Carver, Jeff</fullName>
            </value>
            <value>
                <fullName>Cassidy Crook</fullName>
            </value>
            <value>
                <fullName>Catela, Maria</fullName>
            </value>
            <value>
                <fullName>Cerati, Elisa</fullName>
            </value>
            <value>
                <fullName>Chadwick, Ben</fullName>
            </value>
            <value>
                <fullName>Chaturvedi, Tanya</fullName>
            </value>
            <value>
                <fullName>Chen, Jerry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Budget_Owner__c.field-meta.xml
<CustomField>
    <fullName>Budget_Owner__c</fullName>
    <label>Budget Owner</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>IM</fullName>
            </value>
            <value>
                <fullName>PIH</fullName>
            </value>
            <value>
                <fullName>CBO</fullName>
            </value>
            <value>
                <fullName>PBG</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <isActive>false</isActive>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>PEH</fullName>
                <isActive>false</isActive>
                <label>PEH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/COE_Supported__c.field-meta.xml
<CustomField>
    <fullName>COE_Supported__c</fullName>
    <defaultValue>true</defaultValue>
    <label>COE Supported</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Congress_Lead__c.field-meta.xml
<CustomField>
    <fullName>Congress_Lead__c</fullName>
    <label>Congress Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Virginia Hayward</fullName>
            </value>
            <value>
                <fullName>Lee Kim</fullName>
            </value>
            <value>
                <fullName>Sandra Kusek</fullName>
            </value>
            <value>
                <fullName>Laine Mann</fullName>
            </value>
            <value>
                <fullName>Don Schmid</fullName>
            </value>
            <value>
                <fullName>Suthee Suvansri</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Finance_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Finance_Coordinator__c</fullName>
    <label>Finance Coordinator</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Funding_Owner__c.field-meta.xml
<CustomField>
    <fullName>Funding_Owner__c</fullName>
    <label>Funding Provider Owner</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Funding_Provider_Department__c.field-meta.xml
<CustomField>
    <fullName>Funding_Provider_Department__c</fullName>
    <label>Funding Provider Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/GES_Congress_Manager__c.field-meta.xml
<CustomField>
    <fullName>GES_Congress_Manager__c</fullName>
    <label>GES Congress Manager</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Debbie Hummel</fullName>
            </value>
            <value>
                <fullName>Elena Fezzardi</fullName>
            </value>
            <value>
                <fullName>Eva McCartney</fullName>
            </value>
            <value>
                <fullName>Gail Griffith</fullName>
            </value>
            <value>
                <fullName>Ilysa Link</fullName>
            </value>
            <value>
                <fullName>Julia Noonan</fullName>
            </value>
            <value>
                <fullName>Linnell Navarro</fullName>
            </value>
            <value>
                <fullName>Michelle Pflug</fullName>
            </value>
            <value>
                <fullName>Stephanie Houck</fullName>
            </value>
            <value>
                <fullName>Tricia Purcell</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/GES_Connect_Corporate_Accounts__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Corporate_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect - Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Brand</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Product_Theater_Costs_Actual__c.field-meta.xml
<CustomField>
    <fullName>Product_Theater_Costs_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Product Theater Costs Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Product_Theater_Costs_Estimated__c.field-meta.xml
<CustomField>
    <fullName>Product_Theater_Costs_Estimated__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Product Theater Costs Estimated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Sponsorship_Costs_Estimated__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Costs_Estimated__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sponsorship Costs Estimated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/GES_Connect_Corporate_Accounts__c.object-meta.xml
<CustomObject>
    <description>Details for GES Connect - Corporate Accounts  for the Data Requirements purpose</description>
    <label>GES Connect - Corporate Accounts</label>
    <nameField>
        <displayFormat>GCA-{0000}</displayFormat>
        <label>GES Connect - Corporate Accounts</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect - Corporate Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Funding_Owner__c.field-meta.xml
<CustomField>
    <fullName>Funding_Owner__c</fullName>
    <label>Funding Owner</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ProductTheaterbrandDetail.cls
public class ProductTheaterbrandDetail 
{
     Brand__c br=new Brand__c();
     Public Brand__c getbr(){
      return br;
    }
    public string ptrbrid{get;set;}
    public string ptrbrName{get;set;}
    public string ProductTheaterid{get;set;}
    public string prtName{get;set;}
    public string congid{get;set;}
    public string congName{get;set;}
    public ProductTheaterbrandDetail()
    {
        ptrbrid=System.currentPageReference().getParameters().get('ptrbrandid'); 
        system.debug('ptrbrid id'+ ptrbrid);
        ptrbrName=System.currentPageReference().getParameters().get('ptrbrandName'); 
        system.debug('ptrbrName '+ ptrbrName);
        ProductTheaterid=System.currentPageReference().getParameters().get('ProductTheaterid'); 
        system.debug('ProductTheaterid '+ ProductTheaterid);
        prtName=System.currentPageReference().getParameters().get('prtName'); 
        system.debug('prtName'+ prtName);
        congid=System.currentPageReference().getParameters().get('congid'); 
        system.debug('congid'+ congid);
        congName=System.currentPageReference().getParameters().get('congName'); 
        system.debug('congName '+ congName);
        br=[select id,Name,Finance_Coordinator__c,CurrencyISOCode,GES_Connect_Corporate_Accounts__c,GES_Congress_Manager__c ,Brand_Name__c,Brand_Category__c,Business_Unit__c,Congress_Lead__c,Brand_Team_Contact__c,COE_Supported__c,Sponsorship_Costs_Estimated__c,Budget_Owner__c,Funding_Owner__c,Cost_Center__c,Product_Theater_Costs_Estimated__c,Product_Theater_Costs_Actual__c,Funding_Provider_Department__c,Funding_Provider_Region__c,Canceled__c, Cancelled_Date__c, Reason_for_Cancellation__c, Contact_Not_Listed__c, Funding_Provider_Brand__c, Company_Code__c  from Brand__c where id=:ptrbrid];
    }
     public PageReference BrandSave()
    {
        //ExhibitBrandEdit?exhibitid=a6Rc0000000D7nSEAS&brandId=a6Sc0000000Ct6PEAS&exhibitName=&congid=a6Qc00000007lxTEAQ&congName=GCA-0201
        //brandId=a6Sc0000000Ct6PEAS&congid=a6Qc00000007lxTEAQ&congName=GCA-0201&exhibitid=a6Rc0000000D7nSEAS&exhibitName=null
        return new PageReference(GC_PageUtil.CheckApexDomain() + '/ProductTheaterbrandEdit?ProductTheaterid='+ProductTheaterid+'&brandId='+br.Id+'&producttherName='+prtName+'&congid='+congid+'&congName='+congName);
    }

     public PageReference BrandCancel()
    {
        //ExhibitDetails?congressid=a6Qc00000007lxTEAQ&congressName=GCA-0201&exhibitid=a6Rc0000000D7nSEAS
        //return new PageReference(GC_PageUtil.CheckApexDomain() + '/SponsorshipBrandDetail?sponbrandid='sponid+'&congName='+congName+);
        //return null;
        return new PageReference(GC_PageUtil.CheckApexDomain() + '/ProductTheaterDetail?congid='+congid+'&prtName='+prtName+'&producttherid='+ProductTheaterid+'&congName='+congName);
    }
}