unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Brand Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brand__c/fields/Funding_Owner__c.field-meta.xml
<CustomField>
    <fullName>Funding_Owner__c</fullName>
    <label>Funding Provider Owner</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/GES_Connect_Corporate_Accounts__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Corporate_Accounts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect - Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Brand</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Brand__c/fields/Meeting_Room__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting Room</label>
    <referenceTo>Meeting_Room__c</referenceTo>
    <relationshipLabel>Brand</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/GES_Connect_Corporate_Accounts__c.object-meta.xml
<CustomObject>
    <description>Details for GES Connect - Corporate Accounts  for the Data Requirements purpose</description>
    <label>GES Connect - Corporate Accounts</label>
    <nameField>
        <displayFormat>GCA-{0000}</displayFormat>
        <label>GES Connect - Corporate Accounts</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect - Corporate Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Funding_Owner__c.field-meta.xml
<CustomField>
    <fullName>Funding_Owner__c</fullName>
    <label>Funding Owner</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Meeting_Room__c/Meeting_Room__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Meeting Room</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Meeting Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Room</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Meeting_Room__c/fields/Congress__c.field-meta.xml
<CustomField>
    <fullName>Congress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Congress</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Meeting Room</relationshipLabel>
    <relationshipName>Meeting_Room</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/MeetingRoomBrandEditTest.cls
@isTest
Public Class MeetingRoomBrandEditTest{
    
    Public Static Testmethod void BrandEdit() {
        GES_Connect_Corporate_Accounts__c parentCongress = GC_TestUtils.getTestCongress();
        Meeting_Room__c  MeetingRoom= GC_TestUtils.getTestMeetingRoom();
        Brand__c brand= GC_TestUtils.getTestBrand();
        brand.Funding_Owner__c='Test';
        brand.Meeting_Room__c =MeetingRoom.id;
        upsert brand;       
        Test.setCurrentPageReference(new PageReference('Page.MeetingRoomBrandEdit'));
        System.currentPageReference().getParameters().put('congid',MeetingRoom.Congress__c);    
        System.currentPageReference().getParameters().put('mrid',MeetingRoom.id);
        System.currentPageReference().getParameters().put('brandid',brand.Id);    
        System.currentPageReference().getParameters().put('mrName',MeetingRoom.Name);
        MeetingRoomBrandEdit eBrandCTRL= new MeetingRoomBrandEdit();
        eBrandCTRL.MeetingRoomBrandSave();
        eBrandCTRL.BrandCancel();
        eBrandCTRL.cancelOperation();
        eBrandCTRL.getbr();
        eBrandCTRL.changeBrandCatandBusUnit();
    }
}