unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/LC_ShowDetailsApexTest.cls
@isTest
public class LC_ShowDetailsApexTest {
     @testSetup static void setup() {
        GC_Connect2_Show__c testShws = new GC_Connect2_Show__c(Job_Number__c='Show');
        insert testShws;     
     }

    @isTest Static Void testfogetrecords(){
    GC_Connect2_Show__c testShowId= [select id,Job_Number__c from GC_Connect2_Show__c where Job_Number__c='Show' ];
    LC_ShowDetailsApex.showDetils(testShowId.id,testShowId.Job_Number__c);
        LC_ShowDetailsApex.fetchUser();
        LC_ShowDetailsApex.getShows(testShowId.Id);
    }
 @isTest Static Void testfogetrecords1(){
    GC_Connect2_Show__c testShowId= [select id,Job_Number__c from GC_Connect2_Show__c where Job_Number__c='Show' ];
    LC_ShowDetailsApex.showDetils(testShowId.id,'');
 }
    @isTest Static Void testfogetrecords2(){
    GC_Connect2_Show__c testShowId= [select id,Job_Number__c from GC_Connect2_Show__c where Job_Number__c='Show' ];
    LC_ShowDetailsApex.showDetils('',testShowId.Job_Number__c);
 }
    
}