unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</inlineHelpText>
    <label>Installation/Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>GES Connect Order Object.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <description>Order Number in which this line item belongs to from the external system.  Populated when the order has been submitted.</description>
    <inlineHelpText>Order Number in which this line item belongs to from the external system.</inlineHelpText>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</inlineHelpText>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Formula to Show Name</description>
    <formula>Order__r.Show_Name__c</formula>
    <inlineHelpText>Show Name</inlineHelpText>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that display&#39;s different status values</description>
    <inlineHelpText>Status of GES Order Task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Graphics Requested</fullName>
            </value>
            <value>
                <fullName>Graphics Submitted</fullName>
            </value>
            <value>
                <fullName>Graphics Rejected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Submitted to Graphics</fullName>
            </value>
            <value>
                <fullName>Submitted For AM Review</fullName>
            </value>
            <value>
                <fullName>Pending AM Review</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>Completion Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Completion Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>Delivery Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Delivery Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <description>Order Number used from the External System.  When this is filled out, the External CORE instance knows about the order and has a direct link of this order.  Field is read only on the page layouts and system but can be used for display purposes.</description>
    <inlineHelpText>Order Number used from the External System.</inlineHelpText>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <description>Removal Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Removal Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Formula to Connect2 Show&#39;s Show Name</description>
    <formula>Connect2_Show__r.Show_Name__c</formula>
    <inlineHelpText>Show Name for Connect2 Show</inlineHelpText>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Status of the Order.  Defaults to &#39;New&#39; and will clearly indicate the status of the order state and what its in.</description>
    <inlineHelpText>Status of the Order.</inlineHelpText>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Daily_Order_Summary_Emails__c.field-meta.xml
<CustomField>
    <fullName>Daily_Order_Summary_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if you want a daily summary email for orders.</inlineHelpText>
    <label>Daily Order Summary Emails</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/No_Notification_Emails__c.field-meta.xml
<CustomField>
    <fullName>No_Notification_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for SAL 519</description>
    <inlineHelpText>Check this box if you don&#39;t want any summary emails.</inlineHelpText>
    <label>No Notification Emails</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/ReceiveNotificationAllOrders__c.field-meta.xml
<CustomField>
    <fullName>ReceiveNotificationAllOrders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Receive Notification All Orders</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/ReceiveNotificationMyOrders__c.field-meta.xml
<CustomField>
    <fullName>ReceiveNotificationMyOrders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Receive Notification My Orders</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <formula>Connect2_Show__r.Show_Name__c</formula>
    <label>Show Name Formula</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Role__c.field-meta.xml
<CustomField>
    <fullName>Show_Role__c</fullName>
    <description>Determines the level of access to associated elements on a show.</description>
    <inlineHelpText>Determines the level of access to associated elements on a show.</inlineHelpText>
    <label>Show Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Convention_Planning</fullName>
                <label>Convention Planning</label>
            </value>
            <value>
                <fullName>Creative Director</fullName>
            </value>
            <value>
                <fullName>Designer/Detailer</fullName>
            </value>
            <value>
                <fullName>Director of Account Management</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager Direct</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Secondary Account Manager</fullName>
            </value>
            <value>
                <fullName>Show Organizer</fullName>
            </value>
            <value>
                <fullName>Show Organizer - Read Only</fullName>
            </value>
            <value>
                <fullName>Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/DailyOrderSummaryNotification.cls
global class DailyOrderSummaryNotification implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String newStatus = 'New';
        String submitted = 'Submitted';
        String approved = 'Approved';
        
        String queryToGetTasks = 'Select Id, OwnerId,Name, Delivery_Date_Time__c, Removal_Date_Time__c, Order__c, Order__r.Connect2_Show__c, Order__r.Show_Name__c, Completion_Date_Time__c, Order_Number__c,Status__c,CreatedBy.Name, Order__r.Connect2_Show__r.Name from GC_GES_Order_Task__c WHERE (LastModifiedDate = LAST_N_DAYS:1 AND Order__r.Connect2_Show__r.Show_End_Date__c>=TODAY)';
        system.debug('queryToGetTasks>>>>>>'+queryToGetTasks);
        return Database.getQueryLocator(queryToGetTasks);
    }
    
    global void execute(Database.BatchableContext bc, List<GC_GES_Order_Task__c> listOfTasks) {
        system.debug('listOfTasks>>>>'+listOfTasks.size());
        List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
        Map<Id,List<String>> showMemEmail = new Map<Id,List<String>>();
        Map<Id,List<String>> showMemEmaiMyOrders = new Map<Id,List<String>>();
        //Map<Id,List<GC_Order__c>> showOrders= new Map<Id,List<GC_Order__c>>();
        Map<Id,String> showmemEmailMyOrders = new Map<Id,String>();
        //Map<Id,List<GC_GES_Order_Task__c>> ordOrdTask = new Map<Id,List<GC_GES_Order_Task__c>>(); // map key= orders, value= order task
        Map<Id,List<GC_GES_Order_Task__c>> showAndTask = new Map<Id,List<GC_GES_Order_Task__c>>();
        String html1 = '';
        Set<Id> setOfShows= new Set<Id>();
        //Set<String> setOfTaskOwner =new Set<String>();
        //Map<Id,String> showOwnerEmail = new Map<Id,String>();
        Map<Id,String> showName = new Map<Id,String>();
        List<GC_Show_Team_Member__c> showTeamMemList = new List<GC_Show_Team_Member__c>();
        List<GC_Show_Team_Member__c> showTeamMemListMyOrders = new List<GC_Show_Team_Member__c>();
        
        for(GC_GES_Order_Task__c got: listOfTasks)
        {
                        
            if(!showAndTask.containsKey(got.Order__r.Connect2_Show__c)){
                showAndTask.put(got.Order__r.Connect2_Show__c,new List<GC_GES_Order_Task__c>());
            }
            showAndTask.get(got.Order__r.Connect2_Show__c).add(got);
            setOfShows.add(got.Order__r.Connect2_Show__c);
            
            if(!showName.containsKey(got.Order__r.Connect2_Show__c)){
                    showName.put(got.Order__r.Connect2_Show__c,got.Order__r.Show_Name__c); 
                }
            
        }
        
        if(showAndTask.keySet().size() > 0)
        {
            //get a list of Show Organisers who opted to recieve notifications on all order tasks
            showTeamMemList = [Select Id,Name,User__r.Email,Connect2_Show__c from GC_Show_Team_Member__c where  Connect2_Show__c in : showAndTask.keySet() and (ReceiveNotificationAllOrders__c = true AND Daily_Order_Summary_Emails__c = true AND No_Notification_Emails__c = false) AND Show_Role__c='Show Organizer'];
            //get a list of Show Organisers who opted to recieve notifications only on their order tasks
            showTeamMemListMyOrders = [Select Id,Name,User__r.Email,Connect2_Show__c from GC_Show_Team_Member__c where  Connect2_Show__c in : showAndTask.keySet() and (ReceiveNotificationMyOrders__c = true AND Daily_Order_Summary_Emails__c = true AND No_Notification_Emails__c = false) AND Show_Role__c='Show Organizer'];
        }
        
        for(GC_Show_Team_Member__c stm: showTeamMemList) 
            {
                 if(!showMemEmail.containsKey(stm.Connect2_Show__c)){
                    showMemEmail.put(stm.Connect2_Show__c,new List<String>());
                }
                showMemEmail.get(stm.Connect2_Show__c).add(stm.User__r.Email);
            }

            for(GC_Show_Team_Member__c stm: showTeamMemListMyOrders) 
            {
                 if(!showMemEmaiMyOrders.containsKey(stm.Connect2_Show__c)){
                    showMemEmaiMyOrders.put(stm.Connect2_Show__c,new List<String>());
                }
                showMemEmaiMyOrders.get(stm.Connect2_Show__c).add(stm.User__r.Email);

                if(!showmemEmailMyOrders.containsKey(stm.User__c)){
                    showmemEmailMyOrders.put(stm.User__c,stm.User__r.Email);
                }
            }

            system.debug('showAndTask>>>>'+showAndTask);
            system.debug('showMemEmail>>>>'+showMemEmail);
            system.debug('showmemEmailMyOrders>>>>'+showmemEmailMyOrders);
            
        for(Id showId: setOfShows)
            {
                //Summary email for all Order tasks to show organisers who opted for such options
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                Set<String> toEmailSet = new Set<String>();
                
                List<String> toEmailList;

                if(showMemEmail.containsKey(showId))
                {
                   for(String email: showMemEmail.get(showId))
                   {
                        toEmailSet.add(email);
                   }
                }
                
                toEmailList = new List<String>(toEmailSet);
                system.debug('toEmailList>>>>'+toEmailList);
                
                mail.setToAddresses(toEmailList);
                mail.setSaveAsActivity(false);
                if(showName.containsKey(showId))
                {
                    mail.setSubject('Order Tasks Summary for Connect2 Show Name: '+showName.get(showId));
                }
                html1 = '<style>table, th, td { border: 1px solid black;}</style><b>Listed below is your daily order task summary</b></ br></ br><table><tr><th> Order Name </th><th> Delivery Date/Time</th><th> Completion Date/Time</th><th>Removal Date/Time</th><th> Order Number</th><th> Order Status</th><th>CreatedBy</th></tr>';
                for(GC_GES_Order_Task__c con : showAndTask.get(showId))
                {
                    html1 += '<tr><td><a href="https://ges--c.vf.force.com/apex/GC_OrderView?id='+con.id+'&sfdc.override=1" target="_blank">'+ con.Name+'</a> </td> <td>'+ (con.Delivery_Date_Time__c != null ? con.Delivery_Date_Time__c.format() : '')+' </td><td>'+ (con.Completion_Date_Time__c != null ? con.Completion_Date_Time__c.format() : '')+' </td><td>'+ (con.Removal_Date_Time__c != null ? con.Removal_Date_Time__c.format() : '')+' </td><td>'+ (con.Order_Number__c != null ? con.Order_Number__c : '')+' </td><td>'+ con.Status__c+' </td><td>'+ con.CreatedBy.Name+' </td></tr>';
                }
                 mail.setHtmlBody(html1);
                if(toEmailList.size()>0) 
                {
                    mailList.add(mail);  
                }
                Set<String> toEmailSet1 = new Set<String>();
                List<String> toEmailList1;
                Map<Id,List<GC_GES_Order_Task__c>> ordOwnerMap = new Map<Id,List<GC_GES_Order_Task__c>>();
                
            for(GC_GES_Order_Task__c con : showAndTask.get(showId))
            {
                if(showmemEmailMyOrders.containsKey(con.OwnerId))
                {
                    if(!ordOwnerMap.containsKey(con.OwnerId)){
                        ordOwnerMap.put(con.OwnerId,new List<GC_GES_Order_Task__c>());
                    }
                    ordOwnerMap.get(con.OwnerId).add(con);
                }
                
            }
        for(Id ownerId: ordOwnerMap.keySet())
            {
                Messaging.SingleEmailMessage mail1 = new Messaging.SingleEmailMessage();
                mail1.setSaveAsActivity(false);
                if(showName.containsKey(showId))
                {
                    mail1.setSubject('Order Tasks Summary for Connect2 Show Name: '+showName.get(showId));
                }
                html1 = '<style>table, th, td { border: 1px solid black;}</style><b>Listed below is your daily order task summary</b></ br></ br><table><tr><th> Order Name </th><th> Delivery Date/Time</th><th> Completion Date/Time</th><th>Removal Date/Time</th><th> Order Number</th><th> Order Status</th><th>CreatedBy</th></tr>';
                if(ordOwnerMap.get(ownerId) != null) {
                  for(GC_GES_Order_Task__c con : ordOwnerMap.get(ownerId))
                  {
                      html1 += '<tr><td><a href="https://ges--c.vf.force.com/apex/GC_OrderView?id='+con.id+'&sfdc.override=1" target="_blank">'+ con.Name+'</a> </td> <td>'+ (con.Delivery_Date_Time__c != null ? con.Delivery_Date_Time__c.format() : '')+' </td><td>'+ (con.Completion_Date_Time__c != null ? con.Completion_Date_Time__c.format() : '')+' </td><td>'+ (con.Removal_Date_Time__c != null ? con.Removal_Date_Time__c.format() : '')+' </td><td>'+ (con.Order_Number__c != null ? con.Order_Number__c : '')+' </td><td>'+ con.Status__c+' </td><td>'+ con.CreatedBy.Name+' </td></tr>';
                  }
                }
                if(showmemEmailMyOrders.containsKey(ownerId))
                    {
                        toEmailSet1.add(showmemEmailMyOrders.get(ownerId));
                    }
                    toEmailList1 = new List<String>(toEmailSet1);
                    system.debug('toEmailList1>>>>'+toEmailList1);
                    mail1.setToAddresses(toEmailList1);
                    
                    system.debug('toEmailList1>>>>'+toEmailList1);
                    
                    mail1.setHtmlBody(html1);
                    if(toEmailList1.size()>0)
                    {
                        mailList.add(mail1); 
                    }
                
            }
        }
            
            
            
        Messaging.sendEmail(mailList);
    }
    global void finish(Database.BatchableContext bc) {
    }
}