unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Request_Form__c/GC_Design_Request_Form__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Request Form Custom Object.  Each Opportunity will have one and only one Active Design Request Form.  The Design Request Form object will be the central object to relate Design Element designated to a show.  The DRF contains details about budgets / graphics / show information.</description>
    <label>Design Request Form</label>
    <nameField>
        <displayFormat>DRF-{0000}</displayFormat>
        <label>Design Request Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Request Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Design Request Forms</relationshipLabel>
    <relationshipName>Design_Request_Forms</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of DRF.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form_Budget__c/GC_Design_Request_Form_Budget__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Request Form Budget Custom Object.</description>
    <label>Design Request Form Budget</label>
    <nameField>
        <displayFormat>DRFB-{0000000}</displayFormat>
        <label>Design Request Form Budget Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Request Form Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Request_Form_Budget__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal Lookup to Connect2 Show.  This is set via insert / update trigger when Design Request Form is set.  It is used internally when adding show team member assignments.</description>
    <inlineHelpText>Internal Lookup to Connect2 Show.  This is set via insert / update trigger when Design Request Form is set.  It is used internally when adding show team member assignments.</inlineHelpText>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Design Request Form Budgets</relationshipLabel>
    <relationshipName>Design_Request_Form_Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form_Budget__c/fields/Design_Request_Form__c.field-meta.xml
<CustomField>
    <fullName>Design_Request_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Design Request Form</label>
    <referenceTo>GC_Design_Request_Form__c</referenceTo>
    <relationshipName>Design_Request_Forms_Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form_Budget__c/fields/Next_ApproverSTM__c.field-meta.xml
<CustomField>
    <fullName>Next_ApproverSTM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Next Approver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GC_Show_Team_Member__c.Show_Role__c</field>
            <operation>contains</operation>
            <value>Director of Account Management</value>
        </filterItems>
        <filterItems>
            <field>$Source.Connect2_Show__c</field>
            <operation>equals</operation>
            <valueField>GC_Show_Team_Member__c.Connect2_Show__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GC_Show_Team_Member__c</referenceTo>
    <relationshipLabel>Design Request Form Budgets</relationshipLabel>
    <relationshipName>Design_Request_Form_Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form_Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submit</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Role__c.field-meta.xml
<CustomField>
    <fullName>Show_Role__c</fullName>
    <description>Determines the level of access to associated elements on a show.</description>
    <inlineHelpText>Determines the level of access to associated elements on a show.</inlineHelpText>
    <label>Show Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Convention_Planning</fullName>
                <label>Convention Planning</label>
            </value>
            <value>
                <fullName>Creative Director</fullName>
            </value>
            <value>
                <fullName>Designer/Detailer</fullName>
            </value>
            <value>
                <fullName>Director of Account Management</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager Direct</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Secondary Account Manager</fullName>
            </value>
            <value>
                <fullName>Show Organizer</fullName>
            </value>
            <value>
                <fullName>Show Organizer - Read Only</fullName>
            </value>
            <value>
                <fullName>Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GC_DRF_BudgetApprovalController_Test.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Test code for Design Request Form budget approval controller
* 2016-04-13 : Original Version
**/
@isTest
public class GC_DRF_BudgetApprovalController_Test {
    @isTest
    public static void GC_BudgetApprovalTests() {
        GC_Connect2_Show__c show =  GC_TestUtils.getTestConnect2Show();
        User director = GC_TestUtils.createUser('GC Director of Account Management', 'director', 'danny');
        GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c(
            User__c = director.Id,
            Connect2_Show__c = show.Id,
            Show_Role__c = 'Director of Account Management');
        insert stm;
        GC_Show_Team_Member__c stmInfo = [select Id, User__c from GC_Show_Team_Member__c where Id = :stm.Id];
        GC_Design_Request_Form__c drf = new GC_Design_Request_Form__c();
        drf.Connect2_Show__c = show.Id;
        insert drf;
        GC_Design_Request_Form_Budget__c newDRFB = new GC_Design_Request_Form_Budget__c();
        newDRFB.Design_Request_Form__c = drf.Id;
        newDRFB.Next_ApproverSTM__c = stmInfo.Id;
        insert newDRFB;

        Test.startTest();

        ApexPages.StandardController sc = new ApexPages.StandardController(newDRFB);
        GC_DRF_BudgetApprovalController cont = new GC_DRF_BudgetApprovalController(sc);

        cont.loadAction();

        System.assertEquals(cont.canSubmit, true);
        System.assertEquals(cont.getCanSubmitForApproval(), true);
        cont.getUserName();

        PageReference pg = cont.setApprover();
        System.assertNotEquals(null, pg);

        System.assertEquals(GC_ApprovalUtils.isUnderApproval(newDRFB.Id), true);

        pg.setRedirect(true);
        cont.cancel();
        cont.cancelSubmitForApproval();

        cont.approverChanged();
        System.assertEquals(cont.approverName != null, true);



        Test.stopTest();
    }

    @isTest
    public static void GC_BudgetApprovalErrorConditions() {
        GC_Connect2_Show__c show =  GC_TestUtils.getTestConnect2Show();
        User director = GC_TestUtils.createUser('GC Director of Account Management', 'director', 'danny');
        GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c(
            User__c = director.Id,
            Connect2_Show__c = show.Id,
            Show_Role__c = 'Director of Account Management');
        insert stm;
        GC_Show_Team_Member__c stmInfo = [select Id, User__c from GC_Show_Team_Member__c where Id = :stm.Id];
        GC_Design_Request_Form__c drf = new GC_Design_Request_Form__c();
        drf.Connect2_Show__c = show.Id;
        insert drf;
        GC_Design_Request_Form_Budget__c newDRFB = new GC_Design_Request_Form_Budget__c();
        newDRFB.Design_Request_Form__c = drf.Id;
        newDRFB.Next_ApproverSTM__c = stmInfo.Id;
        insert newDRFB;

        Test.startTest();

        ApexPages.StandardController sc = new ApexPages.StandardController(newDRFB);
        GC_DRF_BudgetApprovalController cont = new GC_DRF_BudgetApprovalController(sc);

        newDRFB.Status__c = 'Not New';
        update newDRFB;
        cont.drfB = [select Id, Name, Next_ApproverSTM__c, Status__c, Design_Request_Form__r.Connect2_Show__c, Design_Request_Form__c, OwnerId from GC_Design_Request_Form_Budget__c where Id = :newDRFB.id];

        cont.loadAction();
        System.assertEquals(cont.canSubmit, false);

        newDRFB.Status__c = 'New';
        update newDRFB;
        cont.drfB = [select Id, Name, Next_ApproverSTM__c, Status__c, Design_Request_Form__r.Connect2_Show__c, Design_Request_Form__c, OwnerId from GC_Design_Request_Form_Budget__c where Id = :newDRFB.id];

        delete stm;
        cont.loadAction();
        System.assertEquals(cont.canSubmit, false);

        // TODO need to test budget owner
        Test.stopTest();
    }
}