unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Analytics_Role__c.field-meta.xml
<CustomField>
    <fullName>Show_Analytics_Role__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created under SAL-436</description>
    <inlineHelpText>Check this box to allow team member to use the analytics portal.</inlineHelpText>
    <label>Show Analytics Access</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GC_Community_HeaderController.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Controller class for the Header component for community
* 2016-04-13 : Original Version
**/
public with sharing class GC_Community_HeaderController {
    public GC_Connect2_Show__c show {get; set;}
    public GC_Order__c order {get; set;}
    
    public GC_Community_HeaderController() {
        String showId = ApexPages.currentPage().getParameters().get('showId');
        if (String.isNotBlank(showId)) {
            show = GC_Connect2ShowDao.getInstance().getConnect2ShowById(showId);
        }
        String orderId = ApexPages.currentPage().getParameters().get('orderId');
        if (String.isNotBlank(orderId)) {
            order = GC_OrderDao.getInstance().getOrderById(orderId);
        }
    }
    
     public Boolean getDownTimeStart(){
        String customLabelValue = System.Label.GES_Connect_OracleDownTimeNotification;
        system.debug('customLabelValue==='+ customLabelValue);
        String labelStatus= customLabelValue.substringBefore(':');
        if(labelStatus.toLowerCase()=='alert'){
            return true;
        }else{
            return false;
        }
     }
    
    /**
* @description Retrieves show start and end dates
* @return String of start and end dates
**/
    public String getShowDates() {
        return show.Show_Start_Date__c.format() + ' - ' + show.Show_End_Date__c.format();
    }
    
    /**
* @description Determines if user has taskRay permission set assigned.
**/
    public Boolean hasTaskRayAccess {
        get {
            Boolean hasAccess = false;
            List<PermissionSet> taskRayPermSet = [select Id, Name from PermissionSet where Name = 'TaskRay_Standard_Access'];
            if (taskRayPermSet.size() > 0) {
                String permSetId = taskRayPermSet[0].Id;
                List<PermissionSetAssignment> permSetAssignments = [select Id, AssigneeId, PermissionSetId from PermissionSetAssignment where AssigneeId = :UserInfo.getUserId() AND PermissionSetId = :permSetId];
                if (permSetAssignments.size() > 0) {
                    hasAccess = true;
                }
            }
            System.debug('Has Access ' + hasAccess);
            return hasAccess;
        }
    }
    
    public Boolean hasCongressAccess {
        get {
            Boolean hasAccess = false;
            List<Profile> Profile = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];  
            String MyProflieName = Profile[0].Name;
            if(MyProflieName == 'GC Congress Client' || MyProflieName == 'GC Congress Internal' || MyProflieName == 'System Administrator' || MyProflieName == 'Digital Products/IT Admin') {
                hasAccess = true;           
            } else {
                hasAccess = false;
            }         
            System.debug('Has Congress Access ' + hasAccess);
            return hasAccess;
        }
    }
    
    public Boolean hasTradeshowAccess {
        get {
            Boolean hasAccess = false;
            List<Profile> Profile = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];  
            String MyProflieName = Profile[0].Name;
            if(MyProflieName == 'GC Community Client' || MyProflieName == 'GC Community Vendor' || MyProflieName == 'System Administrator' || MyProflieName == 'Digital Products/IT Admin') {
                hasAccess = true;           
            } else {
                hasAccess = false;
            }         
            System.debug('Has Tradeshow Access ' + hasAccess);
            return hasAccess;
        }
    }
    
    /* Start here- Added this to check access to use analytics page SAL-436 */
    public PageReference navigateAnalytics() {
        System.debug('profile id' + UserInfo.getProfileId());
        String c2ShowID = ApexPages.currentPage().getParameters().get('showId');
        if (String.isNotBlank(c2ShowID)) {
            show = GC_Connect2ShowDao.getInstance().getConnect2ShowById(c2ShowID);
        }
        String userID= UserInfo.getUserId();
        GC_Show_Team_Member__c teamMember = new GC_Show_Team_Member__c();
        try{
            teamMember = [Select id, Show_Analytics_Role__c from GC_Show_Team_Member__c where User__c= :userID AND Connect2_Show__r.Job_Number__c=:show.Job_Number__c Limit 1];
        }catch(Exception e){}       
        
        if(String.isNotBlank(c2ShowID)&& (teamMember.Show_Analytics_Role__c || System.Label.GC_Label_ProfilesForAnalytics.contains(UserInfo.getProfileId()))){
            
                pageReference pager = Page.GC_Community_ExpressoReportsList;
                pager.getParameters().put('showId',show.Id);
                pager.getParameters().put('projectNumber',show.Job_Number__c);
                pager.setRedirect(true);
                return pager;
        }else if(String.isBlank(c2ShowID)){
            pageReference pager = Page.GC_Community_ConnectAnaltyticsHome;          
            pager.setRedirect(true);
            return pager;            
        }
        
        else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please contact your GES Account Manager for Analytics access. Thank You!'));
        }
        return null;
    }
    
    /* Stop here- Added this to check access to use analytics page SAL-436 */
}