unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Carpet_Length__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Length__c</fullName>
    <description>Carpet Length Option (Required) when Submitting a Carpet Line Item Order.</description>
    <inlineHelpText>Carpet Length Option (Required) when Submitting a Carpet Line Item Order.</inlineHelpText>
    <label>Carpet Length</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Carpet_Width__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Width__c</fullName>
    <description>Carpet Width Option (Required) when Submitting a Carpet Line Item Order.</description>
    <inlineHelpText>Carpet Width Option (Required) when Submitting a Carpet Line Item Order.</inlineHelpText>
    <label>Carpet Width</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</inlineHelpText>
    <label>Installation/Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <description>Item Number defined by the product selection picklist.</description>
    <inlineHelpText>Item Number defined by the product selection picklist.</inlineHelpText>
    <label>Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Template__c.field-meta.xml
<CustomField>
    <fullName>Item_Template__c</fullName>
    <description>Determines the list of order options to select for an order task</description>
    <inlineHelpText>Basic, Carpet, Graphics, Custom Carpet, Custom Graphics as determined by selecting the item.</inlineHelpText>
    <label>Item Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Onsite_Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>No longer used as needs to lookup to contact.</description>
    <inlineHelpText>No longer used as needs to lookup to contact.</inlineHelpText>
    <label>(No Longer Used)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GES_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>GES Connect Order Object.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/QuantityNum__c.field-meta.xml
<CustomField>
    <fullName>QuantityNum__c</fullName>
    <description>Number of Units to Order</description>
    <inlineHelpText>Number of Units to Order</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</inlineHelpText>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Text field that displays current revision number</description>
    <inlineHelpText>Current revision number</inlineHelpText>
    <label>Revision</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Sign_Length__c.field-meta.xml
<CustomField>
    <fullName>Sign_Length__c</fullName>
    <description>Sign height in inches for a custom graphics order.</description>
    <inlineHelpText>Sign height in inches for a custom graphics order.</inlineHelpText>
    <label>Sign Height (in)</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Sign_Width__c.field-meta.xml
<CustomField>
    <fullName>Sign_Width__c</fullName>
    <description>Sign length in inches for a custom graphics order.</description>
    <inlineHelpText>Sign length in inches for a custom graphics order.</inlineHelpText>
    <label>Sign Width (in)</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that display&#39;s different status values</description>
    <inlineHelpText>Status of GES Order Task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Graphics Requested</fullName>
            </value>
            <value>
                <fullName>Graphics Submitted</fullName>
            </value>
            <value>
                <fullName>Graphics Rejected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Submitted to Graphics</fullName>
            </value>
            <value>
                <fullName>Submitted For AM Review</fullName>
            </value>
            <value>
                <fullName>Pending AM Review</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area_ID__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area_ID__c</fullName>
    <description>Booth Area ID known by the External System.  Used for mapping the Item Discounts associated with a booth area.</description>
    <inlineHelpText>Booth Area ID known by the External System.  Used for mapping the Item Discounts associated with a booth area.</inlineHelpText>
    <label>Booth Area ID (Hidden)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>Completion Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Completion Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>Delivery Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Delivery Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <description>Removal Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Removal Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Status of the Order.  Defaults to &#39;New&#39; and will clearly indicate the status of the order state and what its in.</description>
    <inlineHelpText>Status of the Order.</inlineHelpText>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GC_GESOrderTaskDaoTest.cls
@isTest
Public Class GC_GESOrderTaskDaoTest{
    @testSetup static void dataSetup() {
        //Opportunity opp = GC_TestUtils.getTestOpportunity();
        //GC_Connect2_Show__c show = GC_TestUtils.getTestConnect2Show1();
        GC_Order__c testOrder=GC_TestUtils.getTestOrder();
        GC_GES_Order_Task__c testGOT = new GC_GES_Order_Task__c();
        testGOT.Order__c = testOrder.Id;
        testGOT.Sign_Length__c = 10;
        testGOT.Sign_Width__c = 10;
        //testGOT.Onsite_Contact_Person__c = accountManagerId;
        testGOT.Delivery_Date_Time__c = DateTime.now();
        testGOT.Completion_Date_Time__c = DateTime.now() + 10;
        testGOT.Removal_Date_Time__c = DateTime.now() + 15;
        testGOT.QuantityNum__c = 5;
        testGOT.Carpet_Length__c = 15;
        testGOT.Carpet_Width__c = 15;
        testGOT.Revision__c = 1;
        testGOT.Status__c = 'New';
        testGOT.Item_Number__c = '12345';
        testGOT.Item_Template__c = 'Carpet';
        insert testGOT;
    }
    
    //Start testing all methods one by one
    @isTest static void testMethod0() {
        GC_Order__c testOrder1= [SELECT id, name, Connect2_Show__c, Connect2_Show__r.Id from  GC_Order__c where Booth_Area_ID__c='1390259'];
        GC_GESOrderTaskDao gotDAO= GC_GESOrderTaskDao.getInstance();
        List<GC_GES_Order_Task__c> gots = gotDAO.getByConnect2ShowId(testOrder1.Connect2_Show__c);
        Set<String> gotIds= new Set<String>();
        gotIds.add(testOrder1.Id);
        String gotId;
        for(GC_GES_Order_Task__c got: gots){
            gotIds.add(string.valueOf(got.Id));
            gotId=string.valueOf(got.Id);
        }
        gots = gotDAO.getByConnect2ShowId(testOrder1.Connect2_Show__c,'Name');
        gots = gotDAO.getByGesOrderId(testOrder1.Id);
        gots = gotDAO.getByGesOrderIdAndExcludeStatus(testOrder1.Id,'Submitted');
        gots = gotDAO.getByGesOrderIdDesc(testOrder1.Id);
        String whereClause = 'Order__c = \'' + testOrder1.Id + '\' AND OwnerId = \'' + UserInfo.getUserId() + '\'';
        gots = gotDAO.getByWhere(whereClause);
        Set<String> orderIds= new Set<String>();
        orderIds.add(string.valueOf(testOrder1.Id));
        gots = gotDAO.getGesOrderTaskByOrderSet(orderIds);
        gots = gotDAO.getGesOrderTaskOrderByOrderSet(orderIds);
        gots = gotDAO.getGESOrderTaskByIds(gotIds);
        GC_GES_Order_Task__c got = gotDAO.getGESOrderTaskById(gotId);
        
    }
}