unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/FormulaShowDates__c.field-meta.xml
<CustomField>
    <fullName>FormulaShowDates__c</fullName>
    <formula>TEXT(Show_Start_Date__c) + &#39; - &#39; + TEXT(Show_End_Date__c)</formula>
    <label>Show Dates</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Formula to Connect2 Show&#39;s Show Name</description>
    <formula>Connect2_Show__r.Show_Name__c</formula>
    <inlineHelpText>Show Name for Connect2 Show</inlineHelpText>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GC_OrderDao.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description DAO for GES Order
* 2016-04-13 : Original Version
**/
public with sharing class GC_OrderDao extends GC_BaseDao {
    
     //@TestVisible
    private static final GC_OrderDao Dao = new GC_OrderDao();
    // @TestVisible
    private static Set<String> relatedFields;

   //  @TestVisible
     private GC_OrderDao() {
        super('GC_Order__c');
        relatedFields = new Set<String> {
            'Connect2_Show__r.Name',
            'Connect2_Show__r.Job_Number__c',
            'Connect2_Show__r.Show_Name__c',
            'Connect2_Show__r.FormulaShowDates__c',
            'Owner.Name',
            '(Select Id, Name, BodyLength, Description from Attachments)' //added for SAL 517-518 @rksinha
        };
        addFields(relatedFields);
    }

    public static GC_OrderDao getInstance() {
        return Dao;
    }

    public GC_Order__c getOrderById(String orderId) {
        return (GC_Order__c)getSObjectById(orderId);
    }
    public List<GC_Order__c> getOrderByIds(Set<String> orderIds) {
        return (List<GC_Order__c>)getSObjectByIdSet('Id', orderIds);
    }
    public List<GC_Order__c> getByConnect2ShowId(String showId) {
        return Database.query(getSelect('Connect2_Show__c = :showId', 'Name', null));
    }
    public List<GC_Order__c> getByConnect2ShowId(String showId, String orderBy) {
        return Database.query(getSelect('Connect2_Show__c = :showId', orderBy, null));
    }
}