unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Are_hanging_signs_allowed__c.field-meta.xml
<CustomField>
    <fullName>Are_hanging_signs_allowed__c</fullName>
    <label>Are hanging signs allowed?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/If_approval_is_needed_please_provide_a__c.field-meta.xml
<CustomField>
    <fullName>If_approval_is_needed_please_provide_a__c</fullName>
    <inlineHelpText>If approval is needed, please provide a contact name and email.</inlineHelpText>
    <label>Provide a contact name and email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/If_so_how_would_you_like_Order_Entry_to__c.field-meta.xml
<CustomField>
    <fullName>If_so_how_would_you_like_Order_Entry_to__c</fullName>
    <inlineHelpText>Are there any special considerations on entering the booth packages? Anything Order Entry should know regarding the packages?</inlineHelpText>
    <label>How is order to be processed?</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Is_it_for_both_inbound_and_or_outbound__c.field-meta.xml
<CustomField>
    <fullName>Is_it_for_both_inbound_and_or_outbound__c</fullName>
    <label>Is it for both inbound and/or outbound?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Is_the_show_targeted__c.field-meta.xml
<CustomField>
    <fullName>Is_the_show_targeted__c</fullName>
    <label>Is the show targeted?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Is_there_Storage_Labor__c.field-meta.xml
<CustomField>
    <fullName>Is_there_Storage_Labor__c</fullName>
    <label>Is there Storage &amp; Labor?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Know_Your_Show_Complete__c.field-meta.xml
<CustomField>
    <fullName>Know_Your_Show_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this checkbox when the KYS is finished.</inlineHelpText>
    <label>Know Your Show Complete</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/KYS_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>KYS_Notification_Date__c</fullName>
    <label>KYS Notification Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/KYS_Overall_Comments__c.field-meta.xml
<CustomField>
    <fullName>KYS_Overall_Comments__c</fullName>
    <inlineHelpText>Enter additional comments and special details related to this show.</inlineHelpText>
    <label>KYS Overall Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Method_of_Entry_of_Booth_Statuses__c.field-meta.xml
<CustomField>
    <fullName>Method_of_Entry_of_Booth_Statuses__c</fullName>
    <label>Method of entry of Booth Packages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exhibitor Ordered on Expresso</fullName>
            </value>
            <value>
                <fullName>Show Organizer Ordered</fullName>
            </value>
            <value>
                <fullName>Other (please describe)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Provide_CSM_comments_for_Target_Change_p__c.field-meta.xml
<CustomField>
    <fullName>Provide_CSM_comments_for_Target_Change_p__c</fullName>
    <inlineHelpText>Provide CSM comments for Target Change process, if not in Expresso.</inlineHelpText>
    <label>Provide CSM comments for Target Change</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Team_Member_Ids__c.field-meta.xml
<CustomField>
    <fullName>Show_Team_Member_Ids__c</fullName>
    <description>Field populated via trigger with comma separated list of user Ids for all show team members on this show. Used in formula to check if current user is part of the show team</description>
    <label>Show Team Member Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Will_approval_be_needed_prior_to_entry__c.field-meta.xml
<CustomField>
    <fullName>Will_approval_be_needed_prior_to_entry__c</fullName>
    <label>Will approval be needed prior to entry?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Will_GES_provide_the_service__c.field-meta.xml
<CustomField>
    <fullName>Will_GES_provide_the_service__c</fullName>
    <label>Will GES provide the service?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Will_there_be_Booth_Statuses__c.field-meta.xml
<CustomField>
    <fullName>Will_there_be_Booth_Statuses__c</fullName>
    <label>Will there be Booth Statuses?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Role__c.field-meta.xml
<CustomField>
    <fullName>Show_Role__c</fullName>
    <description>Determines the level of access to associated elements on a show.</description>
    <inlineHelpText>Determines the level of access to associated elements on a show.</inlineHelpText>
    <label>Show Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Convention_Planning</fullName>
                <label>Convention Planning</label>
            </value>
            <value>
                <fullName>Creative Director</fullName>
            </value>
            <value>
                <fullName>Designer/Detailer</fullName>
            </value>
            <value>
                <fullName>Director of Account Management</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager Direct</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Secondary Account Manager</fullName>
            </value>
            <value>
                <fullName>Show Organizer</fullName>
            </value>
            <value>
                <fullName>Show Organizer - Read Only</fullName>
            </value>
            <value>
                <fullName>Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/GC_Vendor_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Vendor Order Task Custom Object. This Object is used to identify Vendor Order Task details to be performed in a GES Connect Show.</description>
    <label>Vendor Order Task</label>
    <nameField>
        <displayFormat>VOT-{0000}</displayFormat>
        <label>Vendor Order Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the GES Order associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order associated with this vendor order task.</inlineHelpText>
    <label>Delivery Location</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipLabel>Vendor Order Tasks</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GC_Show_Role__c.field-meta.xml
<CustomField>
    <fullName>GC_Show_Role__c</fullName>
    <label>GES Connect Show Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GC Account Manager</fullName>
            </value>
            <value>
                <fullName>GC Creative Director</fullName>
            </value>
            <value>
                <fullName>GC Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>GC Detailer</fullName>
            </value>
            <value>
                <fullName>GC Director of Account Management</fullName>
            </value>
            <value>
                <fullName>GC Sales Manager</fullName>
            </value>
            <value>
                <fullName>GC Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>GC Community Client</fullName>
            </value>
            <value>
                <fullName>GC Community Vendor</fullName>
            </value>
            <value>
                <fullName>GC Drafter</fullName>
            </value>
            <value>
                <fullName>GC Convention Planning Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/GC_Connect2ShowTriggerHandler.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Trigger logic for Connect2 Show
* 2016-04-13 : Original Version
**/
public without sharing class GC_Connect2ShowTriggerHandler {

    public static void CheckChangeOwner(Map<Id, GC_Connect2_Show__c> oldMap, Map<Id, GC_Connect2_Show__c> newMap) {
        List<GC_Connect2_Show__c> recalcRecords = new List<GC_Connect2_Show__c>();

        for (Id showId : Trigger.newMap.keySet()) {
            if (oldMap.get(showId).OwnerId != newMap.get(showId).OwnerId) {
                recalcRecords.add(newMap.get(showId));
            }
        }

        if (recalcRecords.size() > 0) {
            UpdateShowTeamAccess(recalcRecords);
            AddShowTeamMembers(recalcRecords);
            UpdateVendorTasks(recalcRecords);
        }
    }

    public static void UpdateShowTeamAccess(List<GC_Connect2_Show__c> shows) {
        Set<Id> showIds = new Set<Id>();

        for (GC_Connect2_Show__c show : shows) {
            showIds.add(show.Id);
        }

        List<GC_Show_Team_Member__c> entireShowTeam = [select Id, User__c, Connect2_Show__c, Show_Role__c from GC_Show_Team_Member__c where Connect2_Show__c in :showIds];
        GC_ShowTeamMemberTriggerHandler.UpdateRecordAccessShows(entireShowTeam, shows);
    }

    public static void UpdateVendorTasks(List<GC_Connect2_Show__c> shows) {
        Set<Id> showIds = new Set<Id>();

        for (GC_Connect2_Show__c show : shows) {
            showIds.add(show.Id);
        }

        List<GC_Vendor_Order_Task__c> vendorTasks = [select Id, Vendor__c from GC_Vendor_Order_Task__c where Order__r.Connect2_Show__c In :showIds AND Vendor__c != null];

        if (vendorTasks.size() > 0) {
            GC_VendorOrderTaskTriggerHandler.HandleVendorShares(vendorTasks);
        }
    }

    // need to do this after insert only.
    public static void AddShowTeamMembers(List<GC_Connect2_Show__c> shows) {
        // look at created by and owner, if they are not show team members for the opportunity then add them to the show.
        if (shows.size() == 0) {
            return;
        }

        Set<Id> usersOnConnect2Show = new Set<Id>();
        Set<Id> showIds = new Set<Id>();

        for (GC_Connect2_Show__c show : shows) {
            usersOnConnect2Show.add(show.CreatedById);
            usersOnConnect2Show.add(show.OwnerId);
            showIds.add(show.Id);
        }

        Map<Id, User> usersOnConnect2ShowMap = new Map<Id, User>([select Id, Name, GC_Show_Role__c, Profile.Name from User where Id in :usersOnConnect2Show]);
        List<GC_Show_Team_Member__c> stms = [select Id, Name, User__c, Connect2_Show__c, Show_Role__c from GC_Show_Team_Member__c where Connect2_Show__c in :showIds AND User__c in :usersOnConnect2Show];
        Map<String, GC_Show_Team_Member__c> existingShowTeamMembers = new Map<String, GC_Show_Team_Member__c>();

        List<GC_Show_Team_Member__c> tmpDelete = new List<GC_Show_Team_Member__c>();

        for (GC_Show_Team_Member__c stm : stms) {
            String key = (stm.User__c + '.' + stm.Connect2_Show__c).toLowerCase();

            if (!existingShowTeamMembers.containsKey(key)) {
                existingShowTeamMembers.put(key, stm);
            } else {
                tmpDelete.add(stm);
            }
        }

        //delete tmpDelete;
        List<GC_Show_Team_Member__c> showTeamMembersToAdd = new List<GC_Show_Team_Member__c>();

        for (GC_Connect2_Show__c show : shows) {
            if (usersOnConnect2ShowMap.containsKey(show.CreatedById)) {
                User createdByUser = usersOnConnect2ShowMap.get(show.CreatedById);

                if (GC_SecurityUtil.userHasRole(createdByUser, GC_SecurityUtil.R_SALES_MGR)) {
                    String key = (show.CreatedById + '.' + show.Id).toLowerCase();

                    if (existingShowTeamMembers.containsKey(key)) {
                        System.Debug('This user ' + show.CreatedById + ' is already on the show ' + show.Id);
                    } else {
                        GC_Show_Team_Member__c newStm = new GC_Show_Team_Member__c();
                        newStm.Connect2_Show__c = show.Id;
                        newStm.Show_Role__c = 'Sales Manager';
                        newStm.User__c = show.CreatedById;
                        showTeamMembersToAdd.add(newStm);
                    }
                }
            }

            if (usersOnConnect2ShowMap.containsKey(show.OwnerId)) {
                User ownerUser = usersOnConnect2ShowMap.get(show.OwnerId);

                if (GC_SecurityUtil.userHasRole(ownerUser, GC_SecurityUtil.R_ACCT_MANAGER)) {
                    String key = (show.OwnerId + '.' + show.Id).toLowerCase();

                    if (existingShowTeamMembers.containsKey(key)) {
                        System.Debug('This user ' + show.OwnerId + ' is already on the show ' + show.Id);
                    } else {
                        GC_Show_Team_Member__c newStm = new GC_Show_Team_Member__c();
                        newStm.Connect2_Show__c = show.Id;
                        newStm.Show_Role__c = 'Account Manager';
                        newStm.User__c = show.OwnerId;
                        showTeamMembersToAdd.add(newStm);
                    }
                }
            }
        }

        insert showTeamMembersToAdd;
    }

    // as of 1/1/2017 there were 2200 show team member records in the system, so this should be able to be run without batch processing
    public static void UpdateShowTeamMembersField(List<GC_Connect2_Show__c> shows) {
        Set<String> showIds = new Set<String>();

        for (GC_Connect2_Show__c show : shows) {
            showIds.add(show.Id);
        }

        List<GC_Show_Team_Member__c> stms = [select Id, Name, Connect2_Show__c, User__c from GC_Show_Team_Member__c where Connect2_Show__c in :showIds AND Show_Role__c != 'Vendor' AND Show_Role__c != 'Show Organizer - Read Only' AND Show_Role__c != 'Show Organizer' order by createdDate asc limit 10000];

        Map<String, Set<String>> showTeamIdsByShow = new Map<String, Set<String>>();

        for (GC_Show_Team_Member__c stm : stms) {
            if (!showTeamIdsByShow.containsKey(stm.Connect2_Show__c)) {
                showTeamIdsByShow.put(stm.Connect2_Show__c, new Set<String>());
            }

            showTeamIdsByShow.get(stm.Connect2_Show__c).add(stm.User__c);
        }

        List<GC_Connect2_Show__c> showsToUpdate = new List<GC_Connect2_Show__c>();
        List<GC_Connect2_Show__c> existingShows = GC_Connect2ShowDao.getInstance().getShowsByIds(showIds);

        for (GC_Connect2_Show__c show : existingShows) {
            if (showTeamIdsByShow.containsKey(show.Id)) {
                String showTeamCSV = String.join(new List<String>(showTeamIdsByShow.get(show.Id)), ',');
                System.debug(loggingLevel.Debug, '*** showTeamCSV: ' + showTeamCSV);
                show.Show_Team_Member_Ids__c = showTeamCSV;
                showsToUpdate.add(show);
            }
        }

        Database.update(showsToUpdate, false);
    }
    
    //SAL-1315 - KYS NoficationDate field updated on record insert - 12/14/23 - Sajid
    public static void updateKYSNoficationDate(List<GC_Connect2_Show__c> newRecords) {
        for(GC_Connect2_Show__c show : newRecords){
            if(show.Know_Your_Show_Complete__c){
                show.KYS_Notification_Date__c = System.now();
            } 
        }
    }
    
    //SAL-1315 - KYS NoficationDate and KYS Complete field updated on record update - 12/14/23 - Sajid
    public static void updateKYSFields(List<GC_Connect2_Show__c> newRecords, Map<Id, GC_Connect2_Show__c> oldMap) {
        for(GC_Connect2_Show__c show : newRecords){
            GC_Connect2_Show__c oldRecord = oldMap.get(show.Id);
            if(show.Know_Your_Show_Complete__c != oldRecord.Know_Your_Show_Complete__c && show.Know_Your_Show_Complete__c){
                show.KYS_Notification_Date__c = System.now();
            }
            else if(checkKYSFieldsChanged(show, oldRecord)){
                show.Know_Your_Show_Complete__c = false;
            }
            
        }
    }
    
    //SAL-1315 - checking if KYS fields updated to populate false value in 'KYS Complete' field - 12/14/23 - Sajid
    public static Boolean checkKYSFieldsChanged(GC_Connect2_Show__c newRecord, GC_Connect2_Show__c oldRecord){
        if(newRecord.Know_Your_Show_Complete__c && 
           (newRecord.KYS_Overall_Comments__c != oldRecord.KYS_Overall_Comments__c ||
           newRecord.Will_there_be_Booth_Statuses__c != oldRecord.Will_there_be_Booth_Statuses__c ||
           newRecord.If_so_how_would_you_like_Order_Entry_to__c != oldRecord.If_so_how_would_you_like_Order_Entry_to__c || 
           newRecord.Method_of_Entry_of_Booth_Statuses__c != oldRecord.Method_of_Entry_of_Booth_Statuses__c || 
           newRecord.Are_hanging_signs_allowed__c != oldRecord.Are_hanging_signs_allowed__c || 
           newRecord.Will_GES_provide_the_service__c != oldRecord.Will_GES_provide_the_service__c || 
           newRecord.Will_approval_be_needed_prior_to_entry__c != oldRecord.Will_approval_be_needed_prior_to_entry__c || 
           newRecord.If_approval_is_needed_please_provide_a__c != oldRecord.If_approval_is_needed_please_provide_a__c	 ||
           newRecord.Is_there_Storage_Labor__c != oldRecord.Is_there_Storage_Labor__c || 
           newRecord.Is_the_show_targeted__c != oldRecord.Is_the_show_targeted__c || 
           newRecord.Provide_CSM_comments_for_Target_Change_p__c != oldRecord.Provide_CSM_comments_for_Target_Change_p__c || 
           newRecord.Is_it_for_both_inbound_and_or_outbound__c != oldRecord.Is_it_for_both_inbound_and_or_outbound__c || 
           newRecord.Include_internal_and_external_links__c != oldRecord.Include_internal_and_external_links__c || 
           newRecord.Is_early_move_in_available__c != oldRecord.Is_early_move_in_available__c || 
           newRecord.If_yes_provide_CSM_comments__c != oldRecord.If_yes_provide_CSM_comments__c || 
           newRecord.Is_Access_Storage_available__c != oldRecord.Is_Access_Storage_available__c || 
           newRecord.If_no_provide_CSM_comments__c != oldRecord.If_no_provide_CSM_comments__c || 
           newRecord.Last_day_to_ship_to_the_warehouse__c != oldRecord.Last_day_to_ship_to_the_warehouse__c || 
           newRecord.Non_GES_advance_warehouse_is_being_used__c != oldRecord.Non_GES_advance_warehouse_is_being_used__c || 
           newRecord.Post_Show_Info__c != oldRecord.Post_Show_Info__c || 
           newRecord.Is_the_hall_carpeted__c != oldRecord.Is_the_hall_carpeted__c || 
           newRecord.Is_flooring_required_for_this_show__c != oldRecord.Is_flooring_required_for_this_show__c || 
           newRecord.Power_from_the_ceiling_or_floor__c != oldRecord.Power_from_the_ceiling_or_floor__c || 
           newRecord.Show_site__c != oldRecord.Show_site__c || 
           newRecord.Is_Lead_Retrieval_being_offered_on_this__c != oldRecord.Is_Lead_Retrieval_being_offered_on_this__c || 
           newRecord.Any_Column_S_inside_booth__c != oldRecord.Any_Column_S_inside_booth__c || 
           newRecord.Dimensions_of_columns_posted_in_Expresso__c != oldRecord.Dimensions_of_columns_posted_in_Expresso__c || 
           newRecord.Additional_Comments__c != oldRecord.Additional_Comments__c)){
               return true;
           }else{
               return false;
           }
    }
    
    //SAL-1315 - Notify to NSC team if KYS field marked as Complete - 12/14/23 - Sajid
    public static void sendEmailToNSC(List<GC_Connect2_Show__c> newRecords, Map<Id, GC_Connect2_Show__c> oldMap) {
        Id senderOrgId = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'noreply@ges.com' LIMIT 1].Id;
        Id templateId = [SELECT Id FROM EmailTemplate WHERE name = 'PC Know Your Show KYS Marked as Complete'].Id;
        
        List<String> toEmails = new List<String>();
        Project_Central_Setting__c pcSetting = Project_Central_Setting__c.getOrgDefaults();
        String toEmailAddress = pcSetting.Email_Address__c;
        if(toEmailAddress != null){
            toEmails = toEmailAddress.split(',');
        }
        
        List<Contact> conts = [SELECT id FROM Contact LIMIT 1];
        if (conts != null && conts.size() > 0) {
            List<Messaging.SingleEmailMessage> messageList = new List<Messaging.SingleEmailMessage>();
            
            for(GC_Connect2_Show__c show : newRecords){
                if((Trigger.isInsert || (Trigger.isUpdate && show.Know_Your_Show_Complete__c != oldMap.get(show.Id).Know_Your_Show_Complete__c)) && show.Know_Your_Show_Complete__c){
                    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                    message.setOrgWideEmailAddressId(senderOrgId);
                    message.setToAddresses(toEmails);
                    message.setTemplateId(templateId);
                    message.setSaveAsActivity(false);
                    message.setWhatId(show.Id);
                    message.setTreatTargetObjectAsRecipient(false);
                    message.setTargetObjectId(conts.get(0).Id);
                    messageList.add(message);
                }
            }
            if (messageList != null && messageList.size() > 0){
                Messaging.sendEmail(messageList); 
            }
        }
    }
}