unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Know_Your_Show_Complete__c.field-meta.xml
<CustomField>
    <fullName>Know_Your_Show_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this checkbox when the KYS is finished.</inlineHelpText>
    <label>Know Your Show Complete</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/KYS_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>KYS_Notification_Date__c</fullName>
    <label>KYS Notification Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <description>Displays the opportunity Id</description>
    <label>Opportunity Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <description>Displays the opportunity name</description>
    <label>Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Team_Member_Ids__c.field-meta.xml
<CustomField>
    <fullName>Show_Team_Member_Ids__c</fullName>
    <description>Field populated via trigger with comma separated list of user Ids for all show team members on this show. Used in formula to check if current user is part of the show team</description>
    <label>Show Team Member Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/GC_Design_Request_Form__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Request Form Custom Object.  Each Opportunity will have one and only one Active Design Request Form.  The Design Request Form object will be the central object to relate Design Element designated to a show.  The DRF contains details about budgets / graphics / show information.</description>
    <label>Design Request Form</label>
    <nameField>
        <displayFormat>DRF-{0000}</displayFormat>
        <label>Design Request Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Request Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Design Request Forms</relationshipLabel>
    <relationshipName>Design_Request_Forms</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <formula>Connect2_Show__r.Show_Name__c</formula>
    <label>Show Name Formula</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Role__c.field-meta.xml
<CustomField>
    <fullName>Show_Role__c</fullName>
    <description>Determines the level of access to associated elements on a show.</description>
    <inlineHelpText>Determines the level of access to associated elements on a show.</inlineHelpText>
    <label>Show Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Convention_Planning</fullName>
                <label>Convention Planning</label>
            </value>
            <value>
                <fullName>Creative Director</fullName>
            </value>
            <value>
                <fullName>Designer/Detailer</fullName>
            </value>
            <value>
                <fullName>Director of Account Management</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager Direct</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Secondary Account Manager</fullName>
            </value>
            <value>
                <fullName>Show Organizer</fullName>
            </value>
            <value>
                <fullName>Show Organizer - Read Only</fullName>
            </value>
            <value>
                <fullName>Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Show Job Number.</inlineHelpText>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Central_Setting__c/Project_Central_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Project Central Setting</label>
</CustomObject>

unpackaged/main/default/classes/GC_Connect2ShowTriggerHandlerTest.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Test code for Connect2 Show trigger handler class
* 2016-04-13 : Original Version
**/
@isTest
private class GC_Connect2ShowTriggerHandlerTest {
    
    @isTest
    public static void testTriggerInsert() {
        GC_Connect2_Show__c show =  GC_TestUtils.getTestConnect2Show();
        GC_Design_Request_Form__c newDRF = GC_TestUtils.getTestDRF(show.Id);
        Test.startTest();
        GC_Design_Request_Form__c drf = new GC_Design_Request_Form__c();
        drf.Connect2_Show__c = show.Id;
        try {
            insert drf;
            System.assert(false, 'Expected a Duplicate DRF error but did not receive one.');
        }
        catch (Exception e) {
            if (!e.getMessage().contains('This show already has a DRF attached to it')) {
                System.assert(false, 'Received an unknown exception.');
            }
        }
        Test.stopTest();
    }

    @isTest
    public static void testShowTeamIds() {

        User amUser = GC_TestUtils.createUser('GC Account Manager', 'test', 'am');
        User taUser = GC_TestUtils.createUser('GC Traffic Administrator', 'test', 'ta');

        System.runAs(amUser) {
            GC_Connect2_Show__c show =  GC_TestUtils.getTestConnect2Show();
            GC_Show_Team_Member__c stm1 = new GC_Show_Team_Member__c();
            stm1.Connect2_Show__c = show.Id;
            stm1.User__c = taUser.Id;
            stm1.Show_Role__c = 'Account Manager';
            GC_Show_Team_Member__c stm2 = new GC_Show_Team_Member__c();
            stm2.Connect2_Show__c = show.Id;
            stm2.User__c = taUser.Id;
            stm2.Show_Role__c = 'Traffic Administrator';
            insert stm1;
            //insert stm2;
            show = GC_Connect2ShowDao.getInstance().getConnect2ShowById(show.Id);

            // Shouldn't be blank due to insert triggers
            System.assertNotEquals(null, show.Show_Team_Member_Ids__c);

            // Blank it out to test a different method
            show.Show_Team_Member_Ids__c = null;
            update show;
            show = GC_Connect2ShowDao.getInstance().getConnect2ShowById(show.Id);
            // testing to make sure it was blanked out
            System.assertEquals(null, show.Show_Team_Member_Ids__c);

            List<GC_Connect2_Show__c> shows = new List<GC_Connect2_Show__c>();
            shows.add(show);
            GC_Connect2ShowTriggerHandler.UpdateShowTeamMembersField(shows);
            show = GC_Connect2ShowDao.getInstance().getConnect2ShowById(show.Id);
            // now this method can be used to backfill any old data and repopulate this field needed for the show view page.
            System.assertNotEquals(null, show.Show_Team_Member_Ids__c);
        }
    }
    
    @isTest
    public static void updateKYSNoficationDateTest(){
        
        Account acc = TestDataUtil.CreateTestFirm(); 
        Opportunity opp = new Opportunity(Name='MyTestShow # 1',Job_Number__c='020121231',StageName='SL1',CloseDate = Date.newInstance(2030,12,2),AccountId=acc.Id,RecordTypeId=TestDataUtil.OpportunitySalesRepRecordTypeId);
        Database.insert(opp);
        
        GC_Connect2_Show__c newShow = new GC_Connect2_Show__c();
        newShow.Opportunity_Name__c = '01453-201601-Test1';
        newShow.Opportunity_Id__c = opp.Id;
        newShow.Show_Name__c = 'test show';
        newShow.Job_Number__c = '12345';
        newShow.Show_Start_Date__c = Date.today();
        newShow.Show_End_Date__c = Date.today();
        newShow.Know_Your_Show_Complete__c = true;
        insert newShow; 
		GC_Connect2_Show__c showRec = [select id, KYS_Notification_Date__c from GC_Connect2_Show__c where id =: newShow.Id limit 1];
		System.assertEquals(true, showRec.KYS_Notification_Date__c != null, 'Notification date should not be null and it is set to current date and time');
    }
    
     @isTest
    public static void updateKYSFieldsTest1(){
        
        Account acc = TestDataUtil.CreateTestFirm(); 
        Opportunity opp = new Opportunity(Name='MyTestShow # 1',Job_Number__c='020121231',StageName='SL1',CloseDate = Date.newInstance(2030,12,2),AccountId=acc.Id,RecordTypeId=TestDataUtil.OpportunitySalesRepRecordTypeId);
        Database.insert(opp);
        
        GC_Connect2_Show__c newShow = new GC_Connect2_Show__c();
        newShow.Opportunity_Name__c = '01453-201601-Test1';
        newShow.Opportunity_Id__c = opp.Id;
        newShow.Show_Name__c = 'test show';
        newShow.Job_Number__c = '12345';
        newShow.Show_Start_Date__c = Date.today();
        newShow.Show_End_Date__c = Date.today();
        newShow.Know_Your_Show_Complete__c = false;
        insert newShow;
        newShow.Know_Your_Show_Complete__c = true;
        update newShow;
        GC_Connect2_Show__c showRec = [select id, KYS_Notification_Date__c from GC_Connect2_Show__c where id =: newShow.Id limit 1];
        System.assertEquals(true, showRec.KYS_Notification_Date__c != null, 'Notification date should not be null and it is set to current date and time');
    }
    
    @isTest
    public static void updateKYSFieldsTest2(){
        
        Account acc = TestDataUtil.CreateTestFirm(); 
        Opportunity opp = new Opportunity(Name='MyTestShow # 1',Job_Number__c='020121231',StageName='SL1',CloseDate = Date.newInstance(2030,12,2),AccountId=acc.Id,RecordTypeId=TestDataUtil.OpportunitySalesRepRecordTypeId);
        Database.insert(opp);
        
        GC_Connect2_Show__c newShow = new GC_Connect2_Show__c();
        newShow.Opportunity_Name__c = '01453-201601-Test1';
        newShow.Opportunity_Id__c = opp.Id;
        newShow.Show_Name__c = 'test show';
        newShow.Job_Number__c = '12345';
        newShow.Show_Start_Date__c = Date.today();
        newShow.Show_End_Date__c = Date.today();
        newShow.Additional_Comments__c = 'test';
		newShow.Know_Your_Show_Complete__c = true;
        insert newShow;
        newShow.Additional_Comments__c = 'test2';
        update newShow;
        GC_Connect2_Show__c showRec = [select id, Know_Your_Show_Complete__c from GC_Connect2_Show__c where id =: newShow.Id limit 1];
        System.assertEquals(false, showRec.Know_Your_Show_Complete__c, 'Notification date should not be null and it is set to current date and time');
    }
    
    @isTest
    public static void sendEmailToNSCTest(){
        
        Account acc = TestDataUtil.CreateTestFirm(); 
        Contact cont = new Contact(LastName='Test Contact',MobilePhone='+18606005240',Email='test@ges.com',AccountId=acc.Id);
        insert cont;
        
        Opportunity opp = new Opportunity(Name='MyTestShow # 1',Job_Number__c='020121231',StageName='SL1',CloseDate = Date.newInstance(2030,12,2),AccountId=acc.Id,RecordTypeId=TestDataUtil.OpportunitySalesRepRecordTypeId);
        Database.insert(opp);
        
        Project_Central_Setting__c pcSetting = new Project_Central_Setting__c(Email_Address__c='test@test.com.invalid');
        insert pcSetting;
        
        GC_Connect2_Show__c newShow = new GC_Connect2_Show__c();
        newShow.Opportunity_Name__c = '01453-201601-Test1';
        newShow.Opportunity_Id__c = opp.Id;
        newShow.Show_Name__c = 'test show';
        newShow.Job_Number__c = '12345';
        newShow.Show_Start_Date__c = Date.today();
        newShow.Show_End_Date__c = Date.today();
        newShow.Additional_Comments__c = 'test';
        newShow.Know_Your_Show_Complete__c = true;
        insert newShow;
    }

}