unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <description>Displays facility of show</description>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/GC_Community_ShowSearchControllerTest.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Test code for the Show Search controller
* 2016-04-12 : Original Version
**/
@isTest
public class GC_Community_ShowSearchControllerTest {

    public static testMethod void getShowsTest() {
        GC_Connect2_Show__c show = GC_TestUtils.getTestConnect2Show();
        show.Facility__c = 'facility 1';
        show.Job_Number__c = '1';
        show.Show_Start_Date__c = Date.today();
        update show;
        GC_Community_ShowSearchController cont = new GC_Community_ShowSearchController();
        cont.showDate = Date.today();
        cont.searchShows();
        List<GC_Connect2_Show__c> showQuery = cont.getPagedShows();
        cont.showId = show.Id;
        System.assertEquals(showQuery.size() , 1);
        System.assertEquals(showQuery.get(0).Facility__c , show.Facility__c);
        cont.resetSearch();
        showQuery = cont.getPagedShows();

        System.assertEquals(showQuery.size() , 1);
        System.assertEquals(showQuery.get(0).Facility__c , show.Facility__c);
        System.assertEquals(cont.getDateString(null), '');
        cont.sortColumn();
        cont.noAccess();
    }
}