unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Element__c/GC_Design_Element__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Element Task Custom Object.</description>
    <label>Design Element Task</label>
    <nameField>
        <displayFormat>DE-{0000000}</displayFormat>
        <label>Design Element Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Element Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>a person or organization using the services of another professional person or company.</description>
    <inlineHelpText>person or organization using the services of another professional person or company.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Design Element Tasks</relationshipLabel>
    <relationshipName>Design_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Design Element Tasks</relationshipLabel>
    <relationshipName>Design_Element_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Deliverable__c.field-meta.xml
<CustomField>
    <fullName>Deliverable__c</fullName>
    <description>Deliverable type</description>
    <inlineHelpText>Deliverable(product) type</inlineHelpText>
    <label>Deliverable</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Task_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Rendering</fullName>
                <label>Color Rendering</label>
            </value>
            <value>
                <fullName>White Model</fullName>
            </value>
            <value>
                <fullName>Line Drawing</fullName>
            </value>
            <value>
                <fullName>Graphic</fullName>
                <default>true</default>
                <label>Graphic</label>
            </value>
            <value>
                <fullName>Detailed Drawing</fullName>
            </value>
            <value>
                <fullName>Floor Plan</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Design_Element__c.field-meta.xml
<CustomField>
    <fullName>Design_Element__c</fullName>
    <description>Design Element Type</description>
    <inlineHelpText>Design Element Type</inlineHelpText>
    <label>Design Element</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Task_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Charging Station</fullName>
            </value>
            <value>
                <fullName>Column Wrap</fullName>
            </value>
            <value>
                <fullName>Design Style Guide</fullName>
            </value>
            <value>
                <fullName>Entrance</fullName>
            </value>
            <value>
                <fullName>Exhibitor Pods</fullName>
            </value>
            <value>
                <fullName>Fill-in</fullName>
            </value>
            <value>
                <fullName>Impact Unit</fullName>
            </value>
            <value>
                <fullName>Information Booth</fullName>
            </value>
            <value>
                <fullName>Kiosks</fullName>
            </value>
            <value>
                <fullName>Kit Booth Packages</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Management Booth</fullName>
            </value>
            <value>
                <fullName>Product Showcases</fullName>
            </value>
            <value>
                <fullName>Publication Bin</fullName>
            </value>
            <value>
                <fullName>Registration/Counters</fullName>
            </value>
            <value>
                <fullName>Resource Center</fullName>
            </value>
            <value>
                <fullName>Schedule at a Glance</fullName>
            </value>
            <value>
                <fullName>Service Desk</fullName>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Theater</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Design_Request_Form__c.field-meta.xml
<CustomField>
    <fullName>Design_Request_Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Design request form number associated with opportunity</description>
    <inlineHelpText>Design request form number associated with opportunity</inlineHelpText>
    <label>Design Request Form</label>
    <referenceTo>GC_Design_Request_Form__c</referenceTo>
    <relationshipLabel>Manifest</relationshipLabel>
    <relationshipName>Design_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name associated with Requestor user</description>
    <inlineHelpText>Name of Requestor</inlineHelpText>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Requester_Design_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of Revisions</description>
    <label>Revision</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of product or task</description>
    <inlineHelpText>Status of product or task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>CD Assign</fullName>
            </value>
            <value>
                <fullName>Task Accepted</fullName>
            </value>
            <value>
                <fullName>Task Rejected</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>On Hold/WFI</fullName>
            </value>
            <value>
                <fullName>GES Approved</fullName>
            </value>
            <value>
                <fullName>GES Disapproved</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Work Product Disapproved</fullName>
            </value>
            <value>
                <fullName>Work Product Approved</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Task_Description__c.field-meta.xml
<CustomField>
    <fullName>Task_Description__c</fullName>
    <description>Short name for Design Element above( Example: Entrance Hall A)</description>
    <inlineHelpText>Short name for Design Element above( Example: Entrance Hall A)</inlineHelpText>
    <label>Design Element Title</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <description>Type of Task</description>
    <inlineHelpText>Type of Task</inlineHelpText>
    <label>Task Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Detailing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/GC_Design_Request_Form__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Request Form Custom Object.  Each Opportunity will have one and only one Active Design Request Form.  The Design Request Form object will be the central object to relate Design Element designated to a show.  The DRF contains details about budgets / graphics / show information.</description>
    <label>Design Request Form</label>
    <nameField>
        <displayFormat>DRF-{0000}</displayFormat>
        <label>Design Request Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Request Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Design Request Forms</relationshipLabel>
    <relationshipName>Design_Request_Forms</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>GC_Show_Team_Member__c</referenceTo>
    <relationshipLabel>Design Request Forms</relationshipLabel>
    <relationshipName>Design_Request_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of DRF.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/GC_DESaveController_Test.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Test code for Design Element save controller
* 2016-04-13 : Original Version
**/
@isTest
public class GC_DESaveController_Test {
    @isTest
    public static void GC_DESaveController_Test() {
        GC_Connect2_Show__c show =  GC_TestUtils.getTestConnect2Show();
        GC_Design_Request_Form__c newDRF = GC_TestUtils.getTestDRF(show.Id);
        Account acc = new Account(
            Name = 'Specifier Summit',
            Phone = '415-900-5322',
            Fax = '115-900-5233',
            BillingStreet = '4108 W. 52nd Place',
            BillingCity = 'Chicago',
            BillingState = 'IL' ,
            BillingPostalCode = '60632',
            NumberOfEmployees = 200,
            AnnualRevenue = 20000000);
        insert acc;
        GC_Design_Element__c newDE = new GC_Design_Element__c();
        //newDE.Design_Request_Form__c = newDRF.Id;
        newDE.Client__c = acc.Id;
        newDE.Requester__c = UserInfo.getUserId();
        newDE.Task_Type__c = 'Design';
        newDE.Design_Element__c = 'Entrance';
        newDE.Task_Description__c = 'Test Design Element';
        newDE.Deliverable__c = 'Graphics';
        newDE.Status__c = 'New';
        newDE.Revision__c = 1;
        newDE.Connect2_Show__c = show.Id;
        insert newDE;
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(newDE);
        GC_DESaveController controller = new GC_DESaveController(sc);
    }
}