unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/GT_Brand__c.object-meta.xml
<CustomObject>
    <description>This will be the product object for all accounts in Generic Template</description>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Brand__c/fields/Canceled__c.field-meta.xml
<CustomField>
    <fullName>Canceled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up for GT_Event__c  (GES Connect Event)</description>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsorship</label>
    <referenceTo>GT_Sponsorship__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/GT_Event__c.object-meta.xml
<CustomObject>
    <description>Object will be used to create Generic Template Account for GES Community. Main Event object for 1st Lightning Community. CC, Merck, SS, GT, Pharma Template, NNI.</description>
    <label>GES Connect Event</label>
    <nameField>
        <displayFormat>GCE-{000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Event__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Sponsorship__c/GT_Sponsorship__c.object-meta.xml
<CustomObject>
    <description>This will be the Sponsorship object for all accounts in Generic Template</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Sponsorship__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up for GT_Event__c</description>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsorship__c/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Sponsorship</relationshipLabel>
    <relationshipName>Sponsorship_Instance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsorship__c/fields/Sponsorship_Name__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Name__c</fullName>
    <label>Sponsorship Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GT_sponsorshipCancellationTriggerTest.cls
@isTest
public class GT_sponsorshipCancellationTriggerTest {
      public static testMethod void testMethod1() {
     GC_Connect2_Show__c cgs=new GC_Connect2_Show__c();   
        cgs.Show_Start_Date__c=Date.parse('3/4/2015');
        cgs.Show_End_Date__c=Date.parse('3/4/2015');
        insert cgs; 
        
        GT_Event__c  evt=new GT_Event__c();  
        evt.Name_of_Event__c='Test';
        evt.Show_Name__c=cgs.id;
        insert evt;  
        
        List<GT_Sponsorship__c> listSponsor = new List<GT_Sponsorship__c>();
        GT_Sponsorship__c sp = new GT_Sponsorship__c();
       
        sp.Sponsorship_Name__c = 'Test';
        sp.GES_Connect_Event__c =  evt.Id;
        
        GT_Sponsorship__c sp1 = new GT_Sponsorship__c();
       
        sp1.Sponsorship_Name__c = 'Test';
        sp1.Canceled__c = true;
        sp1.Cancellation_Date__c=Date.today();
        sp1.GES_Connect_Event__c =  evt.Id;
        listSponsor.add(sp);
        listSponsor.add(sp1);
        insert listSponsor;
        
        GT_Brand__c bd = new GT_Brand__c();
        bd.Sponsorship__c = sp.Id;
        bd.GES_Connect_Event__c = evt.Id;
        insert bd;
        
        sp.Canceled__c = true;
         sp.Cancellation_Date__c=Date.today();
        update sp;
          delete sp;
      }

}