unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Facility_Address_City__c</fullName>
    <label>Facility Address City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility_Address_Country__c.field-meta.xml
<CustomField>
    <fullName>Facility_Address_Country__c</fullName>
    <label>Facility Address Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Facility_Address_State__c</fullName>
    <label>Facility Address State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/FacilityAddressPostalCode__c.field-meta.xml
<CustomField>
    <fullName>FacilityAddressPostalCode__c</fullName>
    <label>Facility Address PostalCode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/FacilityAddressStreet__c.field-meta.xml
<CustomField>
    <fullName>FacilityAddressStreet__c</fullName>
    <label>Facility Address Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/IsUpdated__c.field-meta.xml
<CustomField>
    <fullName>IsUpdated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsUpdated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CA_UpdateFacilityTest.cls
@isTest
public class CA_UpdateFacilityTest 
{
@isTest
    public static void executeMethod1()
    {
        List<GC_Connect2_Show__c> lstPCS = New List<GC_Connect2_Show__c>();
        GC_Connect2_Show__c pcs = new GC_Connect2_Show__c();
        pcs.FacilityAddressPostalCode__c= 'B40 1NT';
        pcs.FacilityAddressStreet__c='The Nec';
        pcs.Facility_Address_City__c='Birmingham';
        pcs.Facility_Address_Country__c='UK';
        pcs.Facility_Address_State__c='West Midlands';
        pcs.IsUpdated__c=FALSE;
        lstPCS.add(pcs);
       
        insert lstPCS;
        
        Test.startTest();
         CA_UpdateFacility updatefac = new CA_UpdateFacility();
         DataBase.executeBatch(updatefac); 
        Test.stopTest();
    }
}