unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Element__c/GC_Design_Element__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Element Task Custom Object.</description>
    <label>Design Element Task</label>
    <nameField>
        <displayFormat>DE-{0000000}</displayFormat>
        <label>Design Element Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Element Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Design Element Tasks</relationshipLabel>
    <relationshipName>Design_Element_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Contact_Designer_Detailer_Approver1__c.field-meta.xml
<CustomField>
    <fullName>Contact_Designer_Detailer_Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Designer/Detailer Approver1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Design Element Tasks</relationshipLabel>
    <relationshipName>Design_Element_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Creative_Director_Approvers__c.field-meta.xml
<CustomField>
    <fullName>Creative_Director_Approvers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of Creative Director is set to Approve the Design Element</description>
    <inlineHelpText>Name of Creative Director is set to Approve the Design Element.  This will automatically add this member to the Show Team.</inlineHelpText>
    <label>Creative Director Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Creative_Director_For</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Design_Request_Form__c.field-meta.xml
<CustomField>
    <fullName>Design_Request_Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Design request form number associated with opportunity</description>
    <inlineHelpText>Design request form number associated with opportunity</inlineHelpText>
    <label>Design Request Form</label>
    <referenceTo>GC_Design_Request_Form__c</referenceTo>
    <relationshipLabel>Manifest</relationshipLabel>
    <relationshipName>Design_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Detailer_Approver__c.field-meta.xml
<CustomField>
    <fullName>Detailer_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is a lookup to the Designer/Detailer User that is Assigned to this Task to be used in the approval process routing.  This field is set by assigning a designer/detailer to the task.</inlineHelpText>
    <label>Designer/Detailer Approver1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>GC Detailer,GC Creative Director</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Design_Element_Tasks_Approver1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of product or task</description>
    <inlineHelpText>Status of product or task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>CD Assign</fullName>
            </value>
            <value>
                <fullName>Task Accepted</fullName>
            </value>
            <value>
                <fullName>Task Rejected</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>On Hold/WFI</fullName>
            </value>
            <value>
                <fullName>GES Approved</fullName>
            </value>
            <value>
                <fullName>GES Disapproved</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Work Product Disapproved</fullName>
            </value>
            <value>
                <fullName>Work Product Approved</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Design_Element__c/fields/Traffic_Administrator_Approver__c.field-meta.xml
<CustomField>
    <fullName>Traffic_Administrator_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of Traffic Administrator set to Approve the Design Element</description>
    <inlineHelpText>Name of Traffic Administrator is set to Approve the Design Element.  This will automatically add this member to the Show Team.</inlineHelpText>
    <label>Traffic Administrator Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Design_Element_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/GC_Design_Request_Form__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Design Request Form Custom Object.  Each Opportunity will have one and only one Active Design Request Form.  The Design Request Form object will be the central object to relate Design Element designated to a show.  The DRF contains details about budgets / graphics / show information.</description>
    <label>Design Request Form</label>
    <nameField>
        <displayFormat>DRF-{0000}</displayFormat>
        <label>Design Request Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Request Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Design Request Forms</relationshipLabel>
    <relationshipName>Design_Request_Forms</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of DRF.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Design_Request_Form__c/recordTypes/RFP.recordType-meta.xml
<RecordType>
    <fullName>RFP</fullName>
    <active>true</active>
    <description>Request for Proposal for an Exhibition or Event.</description>
    <label>RFP (Exhibition or Event)</label>
</RecordType>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Role__c.field-meta.xml
<CustomField>
    <fullName>Show_Role__c</fullName>
    <description>Determines the level of access to associated elements on a show.</description>
    <inlineHelpText>Determines the level of access to associated elements on a show.</inlineHelpText>
    <label>Show Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Convention_Planning</fullName>
                <label>Convention Planning</label>
            </value>
            <value>
                <fullName>Creative Director</fullName>
            </value>
            <value>
                <fullName>Designer/Detailer</fullName>
            </value>
            <value>
                <fullName>Director of Account Management</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager Direct</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Secondary Account Manager</fullName>
            </value>
            <value>
                <fullName>Show Organizer</fullName>
            </value>
            <value>
                <fullName>Show Organizer - Read Only</fullName>
            </value>
            <value>
                <fullName>Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GC_DRF_RFP_ApprovalController_Test.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Test code for Design Request Form RFP approval controller
* 2016-04-13 : Original Version
**/
@isTest
public class GC_DRF_RFP_ApprovalController_Test {
    @isTest
    public static void approvalTaTest() {
        User trafficAdmin = GC_TestUtils.createUser('GC Traffic Administrator', 'trafAd', 'ministrator');
        User creativeDirector = GC_TestUtils.createUser('GC Creative Director', 'DandyD', 'Singleton');
        User detailer = GC_TestUtils.createUser('GC Detailer', 'detailing', 'tom');
        Account account = GC_TestUtils.getAccount();
        Contact contact = GC_TestUtils.getContact('firstname', 'lastname', account);
        System.runAs(trafficAdmin) {
            GC_Connect2_Show__c show =  GC_TestUtils.getTestConnect2Show();
            GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c(
                User__c = trafficAdmin.Id,
                Connect2_Show__c = show.Id,
                Show_Role__c = 'Traffic Administrator');
            insert stm;
            GC_Show_Team_Member__c stm2 = new GC_Show_Team_Member__c(
                User__c = creativeDirector.Id,
                Connect2_Show__c = show.Id,
                Show_Role__c = 'Creative Director');
            insert stm2;
            GC_Design_Request_Form__c drf = new GC_Design_Request_Form__c();
            drf.Connect2_Show__c = show.Id;
            insert drf;
            GC_Design_Element__c newDE = new GC_Design_Element__c();
            newDE.Design_Request_Form__c = drf.Id;
            newDE.Creative_Director_Approvers__c = creativeDirector.Id;
            newDE.Traffic_Administrator_Approver__c = trafficAdmin.Id;
            test.startTest();
            insert newDE;
            test.stopTest();
            //newDE.Detailer_Approver__c = detailer.Id;  //Amarab 04062021 SAL-1243 Replacing old Designer/Detailer Approver1 field with new field
            newDE.Contact_Designer_Detailer_Approver1__c = contact.Id;
            update newDE;
            ApexPages.StandardController sc = new ApexPages.StandardController(newDE);
            GC_DRF_RFP_ApprovalController cont = new GC_DRF_RFP_ApprovalController(sc);
            PageReference pg = cont.setApprover();
            //FIXME Update this Test
            //System.assertNotEquals(pg , null);
        }
    }
    
    @isTest
    public static void approvalAmTest() {
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        
        System.runAs ( thisUser ) {
            User trafficAdmin = GC_TestUtils.createUser('GC Traffic Administrator', 'trafAd', 'ministrator');
            User creativeDirector = GC_TestUtils.createUser('GC Creative Director', 'DandyD', 'Singleton');
            User detailer = GC_TestUtils.createUser('GC Detailer', 'detailing', 'tom');
            User accountManager = GC_TestUtils.createUser('GC Account Manager', 'accounting1', 'manager2');
            Account account1 = GC_TestUtils.getAccount();
            Contact contact = GC_TestUtils.getContact('firstname', 'lastname', account1);
            System.runAs(accountManager) {
                GC_Connect2_Show__c show =  GC_TestUtils.getTestConnect2Show();
                GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c(
                    User__c = trafficAdmin.Id,
                    Connect2_Show__c = show.Id,
                    Show_Role__c = 'Traffic Administrator');
                insert stm;
                GC_Show_Team_Member__c stm2 = new GC_Show_Team_Member__c(
                    User__c = creativeDirector.Id,
                    Connect2_Show__c = show.Id,
                    Show_Role__c = 'Creative Director');
                insert stm2;
                GC_Design_Request_Form__c drf = new GC_Design_Request_Form__c();
                drf.Connect2_Show__c = show.Id;
                insert drf;
                GC_Design_Element__c newDE = new GC_Design_Element__c();
                newDE.Design_Request_Form__c = drf.Id;
                newDE.Creative_Director_Approvers__c = creativeDirector.Id;
                newDE.Traffic_Administrator_Approver__c = trafficAdmin.Id;
                insert newDE;
                //newDE.Detailer_Approver__c = detailer.Id;  //Amarab 04062021 SAL-1243 Replacing old Designer/Detailer Approver1 field with new field
                newDE.Contact_Designer_Detailer_Approver1__c = contact.Id;
                update newDE;
                
                Test.startTest();
                
                ApexPages.StandardController sc = new ApexPages.StandardController(newDE);
                GC_DRF_RFP_ApprovalController cont = new GC_DRF_RFP_ApprovalController(sc);
                PageReference pg = cont.setApprover();
                
                Test.stopTest();
                
                //FIXME Update this Test
                //System.assertNotEquals(pg , null);
            }
        }
    }
    @isTest
    public static void deOnHoldTest() {
        GC_Connect2_Show__c show =  GC_TestUtils.getTestConnect2Show();
        GC_Design_Request_Form__c drf = new GC_Design_Request_Form__c();
        drf.Connect2_Show__c = show.Id;
        insert drf;
        GC_Design_Element__c newDE = new GC_Design_Element__c();
        newDE.Design_Request_Form__c = drf.Id;
        newDE.Status__c = 'On Hold/WFI';
        insert newDE;
        ApexPages.StandardController sc = new ApexPages.StandardController(newDE);
        GC_DRF_RFP_ApprovalController cont = new GC_DRF_RFP_ApprovalController(sc);
        PageReference pg = cont.setApprover();
        System.assertEquals(pg , null);
    }
    
    @isTest
    public static void noDETTest() {
        User trafficAdmin = GC_TestUtils.createUser('GC Traffic Administrator', 'trafAd1', 'ministrator1');
        User creativeDirector = GC_TestUtils.createUser('GC Creative Director', 'DandyD2', 'Singleton2');
        GC_Connect2_Show__c show =  GC_TestUtils.getTestConnect2Show();
        GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c(
            User__c = trafficAdmin.Id,
            Connect2_Show__c = show.Id,
            Show_Role__c = 'Traffic Administrator');
        insert stm;
        GC_Show_Team_Member__c stm2 = new GC_Show_Team_Member__c(
            User__c = creativeDirector.Id,
            Connect2_Show__c = show.Id,
            Show_Role__c = 'Creative Director');
        insert stm2;
        GC_Design_Request_Form__c drf = new GC_Design_Request_Form__c();
        drf.Connect2_Show__c = show.Id;
        insert drf;
        GC_Design_Element__c newDE = new GC_Design_Element__c();
        newDE.Design_Request_Form__c = drf.Id;
        newDE.Creative_Director_Approvers__c = creativeDirector.Id;
        newDE.Traffic_Administrator_Approver__c = trafficAdmin.Id;
        insert newDE;
        System.runAs(trafficAdmin) {
            ApexPages.StandardController sc = new ApexPages.StandardController(newDE);
            GC_DRF_RFP_ApprovalController cont = new GC_DRF_RFP_ApprovalController(sc);
            PageReference pg = cont.setApprover();
            //System.assertEquals(pg , null);
        }
    }
    
    @isTest
    public static void failedApprovalTest() {
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        
        System.runAs ( thisUser ) {
            User trafficAdmin = GC_TestUtils.createUser('GC Traffic Administrator', 'trafA3', 'ministrato3');
            User creativeDirector = GC_TestUtils.createUser('GC Creative Director', 'Dandy5', 'Singleto5');
            User detailer = GC_TestUtils.createUser('GC Detailer', 'detailin1', 'tommy1');
            Account account2 = GC_TestUtils.getAccount();
            Contact contact = GC_TestUtils.getContact('firstname', 'lastname', account2);
            GC_Connect2_Show__c show =  GC_TestUtils.getTestConnect2Show();
            GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c(
                User__c = trafficAdmin.Id,
                Connect2_Show__c = show.Id,
                Show_Role__c = 'Traffic Administrator');
            insert stm;
            GC_Show_Team_Member__c stm2 = new GC_Show_Team_Member__c(
                User__c = creativeDirector.Id,
                Connect2_Show__c = show.Id,
                Show_Role__c = 'Creative Director');
            insert stm2;
            GC_Design_Request_Form__c drf = new GC_Design_Request_Form__c();
            drf.Connect2_Show__c = show.Id;
            insert drf;
            GC_Design_Element__c newDE = new GC_Design_Element__c();
            newDE.Design_Request_Form__c = drf.Id;
            newDE.Creative_Director_Approvers__c = creativeDirector.Id;
            newDE.Traffic_Administrator_Approver__c = trafficAdmin.Id;
            //newDE.Detailer_Approver__c = detailer.Id;  //Amarab 04062021 SAL-1243 Replacing old Designer/Detailer Approver1 field with new field
            //newDE.Contact_Designer_Detailer_Approver1__c = contact.Id;
            insert newDE;
            System.runAs(trafficAdmin) {
                ApexPages.StandardController sc = new ApexPages.StandardController(newDE);
                GC_DRF_RFP_ApprovalController cont = new GC_DRF_RFP_ApprovalController(sc);
                PageReference pg = cont.setApprover();
                //System.assertEquals(pg , null);
                cont.cancel();
            }
        }
    }
    
    @isTest
    public static void noCDTest() {
        User trafficAdmin = GC_TestUtils.createUser('GC Traffic Administrator', 'trafA3', 'ministrato3');
        GC_Connect2_Show__c show =  GC_TestUtils.getTestConnect2Show();
        GC_Show_Team_Member__c stm = new GC_Show_Team_Member__c(
            User__c = trafficAdmin.Id,
            Connect2_Show__c = show.Id,
            Show_Role__c = 'Traffic Administrator');
        insert stm;
        GC_Design_Request_Form__c drf = new GC_Design_Request_Form__c();
        drf.Connect2_Show__c = show.Id;
        insert drf;
        GC_Design_Element__c newDE = new GC_Design_Element__c();
        newDE.Design_Request_Form__c = drf.Id;
        newDE.Traffic_Administrator_Approver__c = trafficAdmin.Id;
        insert newDE;
        ApexPages.StandardController sc = new ApexPages.StandardController(newDE);
        GC_DRF_RFP_ApprovalController cont = new GC_DRF_RFP_ApprovalController(sc);
        PageReference pg = cont.setApprover();
        System.assertEquals(pg , null);
    }
}