unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <description>Displays facility of show</description>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>Completion Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Completion Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>Delivery Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Delivery Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Tiles_Access__c.field-meta.xml
<CustomField>
    <fullName>Tiles_Access__c</fullName>
    <description>Select the tiles that you want to give access to this team member</description>
    <inlineHelpText>Select the tiles that you want to give access to this team member</inlineHelpText>
    <label>Tiles Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tasks</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Attendee Management</fullName>
            </value>
            <value>
                <fullName>Analytics</fullName>
            </value>
            <value>
                <fullName>Service Tickets</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>ProofBook</fullName>
            </value>
            <value>
                <fullName>Exhibitors</fullName>
            </value>
            <value>
                <fullName>Accomodation</fullName>
            </value>
            <value>
                <fullName>Graphic Proofing</fullName>
            </value>
            <value>
                <fullName>SharePoint</fullName>
            </value>
            <value>
                <fullName>Sponsorship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/LC_ProjectCentralHomePageTest.cls
@isTest
public class LC_ProjectCentralHomePageTest {
    @testSetup static void setup() {
        List<GC_Connect2_Show__c> testShws = new List<GC_Connect2_Show__c>();
        for(Integer i=0;i<2;i++) {
            testShws.add(new GC_Connect2_Show__c(Job_Number__c='Show'+i,Show_Start_Date__c=Date.today(),Facility__c='facility'+i,Show_End_Date__c=Date.today()+3));
        }
        insert testShws;     
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Digital Products/IT Admin'].Id,
            LastName = 'last',
            Email = 'test@test.com',
            Username = 'test@test.com'+ System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        insert u;
        GC_Show_Team_Member__c  shwTeamMemeber=new GC_Show_Team_Member__c(Tiles_Access__c='Tasks',User__c=u.Id,Connect2_Show__c=testShws[0].Id);
        insert shwTeamMemeber;
        List<GC_Order__c> orderList = new List<GC_Order__c>();
        for(Integer i=0;i<2;i++) {
            orderList.add(new GC_Order__c(Delivery_Date_Time__c=Date.today(),Completion_Date_Time__c=Date.today()+5,Connect2_Show__c=testShws[0].Id));
        }
        insert orderList;     
    }
    @isTest static void testgetShows(){
        Test.startTest();
        List<GC_Connect2_Show__c> shows=LC_ProjectCentralHomePage.getShowsApex();
        Test.stopTest();
    }
    @isTest Static Void testfogetrecords(){
        List<GC_Connect2_Show__c> showgetrecords=LC_ProjectCentralHomePage.getrecords('Show0',system.today(),false);
    }
     @isTest Static Void testfogetrecordssearch(){
        List<GC_Connect2_Show__c> showget1=LC_ProjectCentralHomePage.getrecords('Show0',null,false);
    }
     @isTest Static Void testfogetrecordsfacility(){
        List<GC_Connect2_Show__c> showgetrec=LC_ProjectCentralHomePage.getrecords('',system.today(),false);
    }
    @isTest Static Void testPastShows1(){
        List<GC_Connect2_Show__c> showgetrec=LC_ProjectCentralHomePage.getrecords(null,null,false);
    }
    @isTest Static Void testPastShows2(){
        List<GC_Connect2_Show__c> showgetrec=LC_ProjectCentralHomePage.getrecords(null,null,true);
    }
    @isTest static void testoverRidePermissions(){
        Boolean bl=LC_ProjectCentralHomePage.overRidePermissions();
    }
    @isTest static void testsaveNewSTM(){
        GC_Show_Team_Member__c STM=[select id,Tiles_Access__c from GC_Show_Team_Member__c where  Tiles_Access__c='Tasks'];
        STM.Tiles_Access__c='Orders';
        String result=LC_ProjectCentralHomePage.saveNewSTM(STM);
    }
    @isTest static void testreturnCurrentShow(){
        GC_Connect2_Show__c currentShow =LC_ProjectCentralHomePage.returnCurrentShow('Show1');
    }
    @isTest static void tescheckUsersPermission(){
        String result=LC_ProjectCentralHomePage.checkUsersPermission();
    }
    
  /*  @isTest static void testgetUserSessionID(){
        Test.startTest();
        List<String> results=LC_ProjectCentralHomePage.getUserSessionID();
        Test.stopTest();
    }*/
      @isTest static void fetchuserMethod(){
       user u=LC_ProjectCentralHomePage.fetchUser();
    }
}