unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of Item from the External System.</description>
    <inlineHelpText>Description of Item from the External System.</inlineHelpText>
    <label>Item Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/File_Reference_Link__c.field-meta.xml
<CustomField>
    <fullName>File_Reference_Link__c</fullName>
    <description>External link or reference to Graphics order files. (Graphics Remarks)</description>
    <inlineHelpText>External link or reference to Graphics order files. (Graphics Remarks)</inlineHelpText>
    <label>File Reference Link/Folder</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Item_Category_ID__c</fullName>
    <description>Item Category Id Used for Item Filters.  Needs to be hidden from page layouts.</description>
    <inlineHelpText>Item Category Id Used for Item Filters.  Needs to be hidden from page layouts.</inlineHelpText>
    <label>Item Category ID (Hidden)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <description>Item Number defined by the product selection picklist.</description>
    <inlineHelpText>Item Number defined by the product selection picklist.</inlineHelpText>
    <label>Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Template__c.field-meta.xml
<CustomField>
    <fullName>Item_Template__c</fullName>
    <description>Determines the list of order options to select for an order task</description>
    <inlineHelpText>Basic, Carpet, Graphics, Custom Carpet, Custom Graphics as determined by selecting the item.</inlineHelpText>
    <label>Item Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <formula>Order__r.Connect2_Show__r.Job_Number__c</formula>
    <label>Job Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>GES Connect Order Object.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/QuantityNum__c.field-meta.xml
<CustomField>
    <fullName>QuantityNum__c</fullName>
    <description>Number of Units to Order</description>
    <inlineHelpText>Number of Units to Order</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</inlineHelpText>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Show_Management_Field__c.field-meta.xml
<CustomField>
    <fullName>Show_Management_Field__c</fullName>
    <description>Special Notes for the Order Task.</description>
    <inlineHelpText>Special Notes.</inlineHelpText>
    <label>Special Instructions (Client Remarks)</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that display&#39;s different status values</description>
    <inlineHelpText>Status of GES Order Task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Graphics Requested</fullName>
            </value>
            <value>
                <fullName>Graphics Submitted</fullName>
            </value>
            <value>
                <fullName>Graphics Rejected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Submitted to Graphics</fullName>
            </value>
            <value>
                <fullName>Submitted For AM Review</fullName>
            </value>
            <value>
                <fullName>Pending AM Review</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <description>Units identified by the Order Item.</description>
    <inlineHelpText>Units identified by the Order Item.</inlineHelpText>
    <label>Units</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>Completion Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Completion Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Status of the Order.  Defaults to &#39;New&#39; and will clearly indicate the status of the order state and what its in.</description>
    <inlineHelpText>Status of the Order.</inlineHelpText>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Role__c.field-meta.xml
<CustomField>
    <fullName>Show_Role__c</fullName>
    <description>Determines the level of access to associated elements on a show.</description>
    <inlineHelpText>Determines the level of access to associated elements on a show.</inlineHelpText>
    <label>Show Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Convention_Planning</fullName>
                <label>Convention Planning</label>
            </value>
            <value>
                <fullName>Creative Director</fullName>
            </value>
            <value>
                <fullName>Designer/Detailer</fullName>
            </value>
            <value>
                <fullName>Director of Account Management</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager Direct</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Secondary Account Manager</fullName>
            </value>
            <value>
                <fullName>Show Organizer</fullName>
            </value>
            <value>
                <fullName>Show Organizer - Read Only</fullName>
            </value>
            <value>
                <fullName>Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/GC_Vendor_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Vendor Order Task Custom Object. This Object is used to identify Vendor Order Task details to be performed in a GES Connect Show.</description>
    <label>Vendor Order Task</label>
    <nameField>
        <displayFormat>VOT-{0000}</displayFormat>
        <label>Vendor Order Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the GES Order associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order associated with this vendor order task.</inlineHelpText>
    <label>Delivery Location</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipLabel>Vendor Order Tasks</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Vendor Order Task.</description>
    <inlineHelpText>Status of the Vendor Order Task.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LC_SubmitAllOrderTaskControllerTest.cls
@isTest
public class LC_SubmitAllOrderTaskControllerTest {
    
    @isTest
    public static void allTestMethod(){
        
        list<GC_GES_Order_Task__c> gotList = new list<GC_GES_Order_Task__c>();
        GC_Connect2_Show__c show = GC_TestUtils.getTestConnect2Show();
        show.Job_Number__c = '00100';
        update show;
        
        GC_Order__c order = GC_TestUtils.getTestOrder();
        order.Connect2_Show__c = show.Id;
        upsert order;
        
        Map<String, User> userMap = GC_TestUtils.getUsers();
        User user1 = userMap.get('AM');
        
        list<GC_Show_Team_Member__c> showTeamsList = new list<GC_Show_Team_Member__c>();
        
        
        GC_Show_Team_Member__c teamMember = new GC_Show_Team_Member__c(Connect2_Show__c = order.Connect2_Show__c, 
                                                                       Show_Role__c = 'Account Manager',
                                                                       User__c = user1.Id);
        showTeamsList.add(teamMember);
        insert teamMember;
        
        GC_GES_Order_Task__c got = new GC_GES_Order_Task__c();
        got.Order__c = order.Id;
        got.Item_Category_ID__c = '1896';
        got.Item_Number__c = '300004';
        got.Description__c = 'Test Item Description';
        got.Item_Template__c = 'Basic';
        got.QuantityNum__c = 1;
        got.UOM__c = 'EA';
        got.Status__c = 'Approved';
        got.Show_Management_Field__c = 'Yes';
        got.File_Reference_Link__c = 'link';
        got.Completion_Date_Time__c = DateTime.Now();
        got.Removal_Date_Time__c = DateTime.Now();
        got.Delivery_Date_Time__c = DateTime.Now();
        got.Price__c = '11.59';
        got.New_Price__c = 12;
        got.Description__c = 'test Desciption';
        got.Invoice_Remarks__c = 'test remarks';
        got.Production_Remarks__c = 'test remarks';
        got.Item_Type_Remarks__c = 'test remarks';
        got.Show_Site_Remarks__c = 'test show site remarks';
        got.Discount_Reason_Text__c ='test';
        got.Booth_Area_Discount_Override__c=12;
        got.Budget_Code__c ='test'; 
        insert got;
        gotList.add(got);
        
        Id votId;
        GC_Vendor_Order_Task__c vot = GC_TestUtils.getTestVendorTask(order.id,votId);
        vot.Vendor__c= UserInfo.getUserId();
        vot.Vendor2__c= UserInfo.getUserId();
        vot.Vendor3__c= UserInfo.getUserId();
        vot.Vendor4__c= UserInfo.getUserId();
        vot.Vendor5__c= UserInfo.getUserId();
        update vot;
        
        LC_SubmitAllOrderTaskController.getAllGot(order.id);
        LC_SubmitAllOrderTaskController.getAllVot(order.id);
        LC_SubmitAllOrderTaskController.getAllApprovers(order.id);
        LC_SubmitAllOrderTaskController.submitAllTasks(order.id, showTeamsList, LC_SubmitAllOrderTaskController.getAllGot(order.id), LC_SubmitAllOrderTaskController.getAllVot(order.id));
        LC_SubmitAllOrderTaskController.getShow(show.id);
        LC_SubmitAllOrderTaskController.submitForApproval(show.id,gotList);
       
        vot.Status__c='Sent';
        update vot;
        LC_SubmitAllOrderTaskController.submitAllTasks(order.id, showTeamsList, LC_SubmitAllOrderTaskController.getAllGot(order.id), LC_SubmitAllOrderTaskController.getAllVot(order.id));
        
    }
    
}