unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Attribute__c/GC_Show_Attribute__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Attribute object for use in storing dynamic lookup content for a Show such as Department / Sign Types / Hall Information / Area Information / Sign Sizes and other related content.  Each type of object is defined by RecordType.</description>
    <label>Show Attribute</label>
    <nameField>
        <label>Show Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Show Attributes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Attribute__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Attributes</relationshipLabel>
    <relationshipName>Show_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GC_Community_ExpressoReports_test.cls
@isTest
public class GC_Community_ExpressoReports_test {
    
   public static testMethod void searchResultsTest() {
        GC_Connect2_Show__c show = GC_TestUtils.getTestConnect2Show();
        User usr = [SELECT Id, Name FROM User WHERE Id = :userinfo.getUserId() LIMIT 1];
        string showId = show.Id;
        show.job_number__c='123456789';
       update show;
        GC_Show_Attribute__c GCshow=new GC_Show_Attribute__c();
        GCshow.Connect2_Show__c =show.Id;
        GCshow.name='test';
        insert GCshow;
        Test.setCurrentPageReference(new PageReference('Page.GC_Community_ExpressoReportsList'));
        ApexPages.currentPage().getParameters().put('Id' , showId);
        ApexPages.currentPage().getParameters().put('projectNumber' , show.job_number__c);  //pass this as if a parameter is made available in URL
        GC_Community_ExpressoReportsController cont = new GC_Community_ExpressoReportsController();
        //cont.showId =  show.Id;
      
        //test to check search result returned 
        PageReference pr = cont.ExhibitorOrderShowProgress();
        PageReference pr1 = cont.ExhibitorOrdersByCategory();
        PageReference pr2 = cont.SubmittedFormShowProgress();
        PageReference pr3 = cont.ExhibitorChecklistStatus();
        PageReference pr4 = cont.ShowInstanceChecklistItems();
        cont.checkValidations();
    }
    
     public static testMethod void searchResultsTestForExceptions() {
        GC_Connect2_Show__c show = GC_TestUtils.getTestConnect2Show();
        User usr = [SELECT Id, Name FROM User WHERE Id = :userinfo.getUserId() LIMIT 1];
        string showId = show.Id;
        
        GC_Show_Attribute__c GCshow=new GC_Show_Attribute__c();
        GCshow.Connect2_Show__c =show.Id;
        GCshow.name='test';
        insert GCshow;
        Test.setCurrentPageReference(new PageReference('Page.GC_Community_ExpressoReportsList'));
        ApexPages.currentPage().getParameters().put('Id' , showId);
        ApexPages.currentPage().getParameters().put('projectNumber' , '12345678');  //pass this as if a parameter is made available in URL
        GC_Community_ExpressoReportsController cont = new GC_Community_ExpressoReportsController();
        //cont.showId =  show.Id;
      
        //test to check search result returned 
        PageReference pr = cont.ExhibitorOrderShowProgress();
        PageReference pr1 = cont.ExhibitorOrdersByCategory();
        PageReference pr2 = cont.SubmittedFormShowProgress();
        PageReference pr3 = cont.ExhibitorChecklistStatus();
        PageReference pr4 = cont.ShowInstanceChecklistItems();
        cont.checkValidations();
    }
}