unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <description>Displays facility of show</description>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility_Address__c.field-meta.xml
<CustomField>
    <fullName>Facility_Address__c</fullName>
    <description>Displays location of the facility</description>
    <label>Facility Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <formula>Connect2_Show__r.Show_Name__c</formula>
    <label>Show Name Formula</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/LC_OrderCloneController.cls
public with sharing class LC_OrderCloneController {
    public string recordId{get; set;}
    public LC_OrderCloneController(ApexPages.StandardSetController controller){
        recordId=apexpages.currentpage().getparameters().get('id');
    }
    //Method to get the shows Created by loggedin user to Clone orders
    public class ShowWrapper{
        @AuraEnabled
        public Boolean isComm {get;set;}
        @AuraEnabled
        public Map<Id,String> showIdNameMap {get;set;}
        ShowWrapper(){}
    }
    @AuraEnabled
    public static ShowWrapper getopenShowOptions(){
        Map<Id,String> showsToAssociate=new Map<Id,String>();
        List<Id> showmem=new List<Id>();
        try{
            List<GC_Show_Team_Member__c> tempShowList;            
            tempShowList=[select id,connect2_show__c from GC_Show_Team_Member__c where User__c=:UserInfo.getUserId()];            
            for(GC_Show_Team_Member__c sm: tempShowList){
                showmem.add(sm.connect2_show__c);
            }
            List<GC_Connect2_Show__c> shows =[SELECT Id, Name,Show_Name__c,Facility__c,Facility_Address__c,Show_Start_Date__c,Show_End_Date__c 
                                                     FROM GC_Connect2_Show__c WHERE id IN :showmem];
            for(GC_Connect2_Show__c show : shows){
                string str='';
                str = show.Name+'|'+show.Show_Name__c+'|'+show.Facility__c+'|'+show.Show_Start_Date__c+'|'+show.Show_End_Date__c;
                showsToAssociate.put(show.Id,str);
            }            
            ShowWrapper sWrap = new ShowWrapper();
            sWrap.showIdNameMap = showsToAssociate;
            sWrap.isComm = LC_AppUtils.isCommunity();            
            return sWrap;
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
}