unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <description>Displays the opportunity name</description>
    <label>Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Production_Location__c.field-meta.xml
<CustomField>
    <fullName>Production_Location__c</fullName>
    <label>Production Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/StageName__c.field-meta.xml
<CustomField>
    <fullName>StageName__c</fullName>
    <description>Stage name of the opportunity</description>
    <inlineHelpText>Stage name of the opportunity</inlineHelpText>
    <label>Stage Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Show Job Number.</inlineHelpText>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Production_Location__c.field-meta.xml
<CustomField>
    <fullName>Production_Location__c</fullName>
    <description>As determined by Operations / Exhibitions account management. Any additions or edits also need to be made to the Locations object.</description>
    <inlineHelpText>Operational location producing exhibition</inlineHelpText>
    <label>Production Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120-OnPeak</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix</fullName>
            </value>
            <value>
                <fullName>180 - Registration</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles, CA</fullName>
            </value>
            <value>
                <fullName>230-Intl Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>270- Corporate Events (Marketing Dept only)</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460 - Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470 - Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480- Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Florida</fullName>
            </value>
            <value>
                <fullName>530- New Orleans</fullName>
            </value>
            <value>
                <fullName>610- Portland, Seattle</fullName>
            </value>
            <value>
                <fullName>710- Chicago, Cleveland, Milwaukee, St. Louis</fullName>
            </value>
            <value>
                <fullName>810- New York &amp; Boston</fullName>
            </value>
            <value>
                <fullName>830-DC, Philadelphia</fullName>
            </value>
            <value>
                <fullName>890- Toronto, Canada</fullName>
            </value>
            <value>
                <fullName>940 - Tradeshow Foreign</fullName>
            </value>
            <value>
                <fullName>944 - E&amp;E Foreign</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi, UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/GC_Connect2ShowCreateController.cls
public without sharing class GC_Connect2ShowCreateController {
    
    public GC_Connect2_Show__c connect2Show {get; set;}
    public List<SelectOption> productionLocations {get; set;}
    
    
    
    //public GC_Connect2ShowCreateController(ApexPages.StandardController sc) {
      //  connect2Show = new GC_Connect2_Show__c();
        
    //}
    
    public GC_Connect2ShowCreateController() { 
        connect2Show = new GC_Connect2_Show__c();
        connect2Show.StageName__c = 'CR';
        productionLocations = new List<SelectOption>();
        
        Schema.DescribeFieldResult fieldResult = Opportunity.Production_Location__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for( Schema.PicklistEntry f : ple)   {
            productionLocations.add(new SelectOption(f.getLabel(), f.getValue()));
        }
    }
    
    public PageReference saveAction(){
        List<GC_Connect2_Show__c> uniqueOpportunityc2s = [select Opportunity_Name__c from GC_Connect2_Show__c where Opportunity_Name__c=:connect2Show.Opportunity_Name__c];
        if(uniqueOpportunityc2s.size() > 0) {
            GC_PageUtil.AddErrorMessage('Opportunity Name should be unique');
            return null;
        }
        List<GC_Connect2_Show__c> uniuqeJobc2s = [select Job_Number__c from GC_Connect2_Show__c where Job_Number__c=:connect2Show.Job_Number__c];
        if(uniuqeJobc2s.size() > 0) {
            GC_PageUtil.AddErrorMessage('Job Number should be unique');
            return null;
        }
        try {
            upsert connect2Show;
        }
        catch (Exception e) {
            GC_PageUtil.AddErrorMessage('Error Saving the Record. ' + e.getMessage());
            return null;
        }
        PageReference viewPage = new PageReference('/' + connect2Show.Id);
        return viewPage;
    }
    
    public PageReference cancelAction(){
        try{
            String baseURL= URL.getSalesforceBaseUrl().toExternalForm()+'/a3r/o';
            PageReference pr = new PageReference(baseURL);
            return pr;
        }catch(exception e){
            system.debug('error=='+e.getMessage()+e.getStackTraceString());
            return null;
        }
    }
}