unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <description>Displays facility of show</description>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Facility_Address__c.field-meta.xml
<CustomField>
    <fullName>Facility_Address__c</fullName>
    <description>Displays location of the facility</description>
    <label>Facility Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/GES_Connect_Corporate_Accounts__c.object-meta.xml
<CustomObject>
    <description>Details for GES Connect - Corporate Accounts  for the Data Requirements purpose</description>
    <label>GES Connect - Corporate Accounts</label>
    <nameField>
        <displayFormat>GCA-{0000}</displayFormat>
        <label>GES Connect - Corporate Accounts</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect - Corporate Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Acronym_of_Congress__c.field-meta.xml
<CustomField>
    <fullName>Acronym_of_Congress__c</fullName>
    <label>Acronym of Congress</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Congress_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Congress_End_Date__c</fullName>
    <label>Congress End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Congress_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Congress_Start_Date__c</fullName>
    <label>Congress Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Congress_Type__c.field-meta.xml
<CustomField>
    <fullName>Congress_Type__c</fullName>
    <label>Congress Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AbC</fullName>
            </value>
            <value>
                <fullName>GBL</fullName>
            </value>
            <value>
                <fullName>INC</fullName>
            </value>
            <value>
                <fullName>LED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Congress_Website__c.field-meta.xml
<CustomField>
    <fullName>Congress_Website__c</fullName>
    <label>Congress Website</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Exhibit_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Close_Date__c</fullName>
    <label>Exhibit Close Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Exhibit_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Exhibit_Open_Date__c</fullName>
    <label>Exhibit Open Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Name_of_Congress__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Congress__c</fullName>
    <label>Name of Congress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Shipping_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State_Province__c</fullName>
    <label>Shipping State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GES_Connect_Corporate_Accounts__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>GES_Connet_Corporate_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CongressSummaryReportController.cls
public with sharing class CongressSummaryReportController {
    public String congressId {get; set;}
    public String congressName {get; set;}
    public Date congressDate {get; set;}
    public String acronymName {get; set;}
    //public String username{get;set;}
    public String congressQuery {get; set;}
    public String orderByQuery {get; set;}
    public String sortOrder {get; set;}
    public String nullsOrder {get; set;}
    public transient List<GES_Connect_Corporate_Accounts__c> theshows {get; set;}
    //--Pagination
    public Integer noOfCongressRecords { get; set; }
    public Integer size { get; set; }
    public Integer pageNumber = null;


    public ApexPages.StandardSetController setcongress { get; set; }

    public CongressSummaryReportController () {
        //theshows =  GC_Connect2ShowDao.getInstance().getShowsWithJobNumberPopulated();
        orderByQuery = 'Name_of_Congress__c';
        sortOrder = 'asc';
        nullsOrder = 'nulls last';
        searchShows();
    }

    public PageReference resetSearch() {
        congressDate = null;
        congressName = null;
        acronymName =null;
        return searchShows();
    }
    Public PageReference Congressedit(){
        congressDate = null;
        congressName = null;
    return Page.Congressedit;
    }
    
    public PageReference searchShows() {
        setcongress = null;
        if (theshows != null) {
            theshows.clear();
        }
        String congWhereClause = '';
        Date today = Date.today();

        congressQuery = 'SELECT Id,Show_Name__r.Name,Name,Acronym_of_Congress__c,Name_of_Congress__c,Congress_Type__c,Congress_Website__c,Congress_Start_Date__c,Congress_End_Date__c,Exhibit_Open_Date__c,Exhibit_Close_Date__c, Shipping_City__c,Shipping_State_Province__c  FROM GES_Connect_Corporate_Accounts__c WHERE Exhibit_Open_Date__c!= null';
        system.debug('List Data'+congressQuery );
        //congressQuery = 'SELECT Id, Name, Show_Name__c,Facility__c,Facility_Address__c,Show_Start_Date__c,Show_End_Date__c FROM GC_Connect2_Show__c WHERE Show_End_Date__c >= ' + getDateString(today) + ' AND Job_Number__c != null';
        congWhereClause += String.isNotBlank(congressName) ? ' AND Name_of_Congress__c like \'%' + congressName + '%\'' : '';
        system.debug('List congWhereClause '+congWhereClause );
        system.debug('Date congWhereClause '+congressDate );
        if (congressDate != null) {
            congWhereClause += ' AND Exhibit_Open_Date__c=' + getDateString(congressDate);
        }
        system.debug('acronymName  congWhereClause '+acronymName );
      congWhereClause += String.isNotBlank(acronymName) ? ' AND Acronym_of_Congress__c like \'%' + acronymName+ '%\'' : '';
        congressQuery = congressQuery +  congWhereClause +' order by ' + orderByQuery + ' ' + sortOrder + ' ' + nullsOrder + ' limit 10000';
        system.debug('List Data'+congressQuery );
        if (setcongress != null) {
            pageNumber = setcongress .getPageNumber();
        }
        system.debug('List Data'+congressQuery );
        setcongress = new ApexPages.StandardSetController(Database.Query(congressQuery));
        
        size = 100;
        system.debug('setcongress Data'+setcongress );
        setcongress.setPageSize(size);
        noOfCongressRecords = setcongress .getResultSize();
        if (pageNumber != null) {
            setcongress .setPageNumber(pageNumber);
            system.debug('setcongress Data'+setcongress );
        }  
         system.debug('setcongress Records'+noOfCongressRecords );    
        return null;
    }

    public String getDateString(Date date1) {
        if (date1 == null) {
            return '';
        }
        DateTime dt = DateTime.newInstance(date1.year(), date1.month(), date1.day());
        return dt.format('yyyy-MM-dd');
    }


    public void setDate() {
        try {
            congressDate = Date.parse(Apexpages.currentPage().getParameters().get('inputDate'));
        }
        catch (Exception e) {
            System.debug(e.getMessage());
        }
    }

    public PageReference sortColumn() {
        String previousColumn = orderByQuery;

        if (Apexpages.currentPage().getParameters().containsKey('orderByCol')) {
            orderByQuery = Apexpages.currentPage().getParameters().get('orderByCol');
        }

        if (previousColumn != orderByQuery) {
            sortOrder = 'asc';
            nullsOrder = 'nulls last';
        }
        else if (sortOrder.contains('asc')) {
            sortOrder = sortOrder.replace('asc', 'desc');

            if (nullsOrder.contains('nulls first')) {
                nullsOrder = nullsOrder.replace('nulls first', 'nulls last');
            }
            else if (nullsOrder.contains('nulls last')) {
                nullsOrder = nullsOrder.replace('nulls last', 'nulls first');
            }
        }
        else if (sortOrder.contains('desc')) {
            sortOrder = sortOrder.replace('desc', 'asc');

            if (nullsOrder.contains('nulls first')) {
                nullsOrder = nullsOrder.replace('nulls first', 'nulls last');
            }
            else if (nullsOrder.contains('nulls last')) {
                nullsOrder = nullsOrder.replace('nulls last', 'nulls first');
            }
        }

        return searchShows();
    }

    public List<GES_Connect_Corporate_Accounts__c> getPagedcongress() {
        Set<String> showIds = new Set<String>();
        for (GES_Connect_Corporate_Accounts__c show : (List<GES_Connect_Corporate_Accounts__c>)setcongress.getRecords()) {
            showIds.add(show.Id);
        }

        return getShowsByIds(showIds, orderByQuery + ' ' + sortOrder + ' ' + nullsOrder);
    }
    
    public List<sObject> getSObjectByIdSet(String field, Set<String> ids, String whereClause, String orderBy) {
        if (ids == null) {
            return null;
        }
        String query = 'select Show_Name__r.Name,Name, Acronym_of_Congress__c,Name_of_Congress__c,Congress_Type__c,Congress_Website__c,Exhibit_Open_Date__c,Exhibit_Close_Date__c ,Congress_Start_Date__c,Congress_End_Date__c,Shipping_City__c,Shipping_State_Province__c from GES_Connect_Corporate_Accounts__c where Id in: ids ';
        if (String.isNotBlank(whereClause)) {
            query += ' AND ' + whereClause;
        }
        if (String.isNotBlank(orderBy)) {
            query += ' order by ' + orderBy;
        }
        return Database.query(query);
    }
    
     public List<GES_Connect_Corporate_Accounts__c> getShowsByIds(Set<String> showIds, String orderBy) {
        return (List<GES_Connect_Corporate_Accounts__c>)getSObjectByIdSet('Id', showIds, null, orderBy);
    }
    public PageReference back() 
   {
        return page.ReportsList;
        
    }
    public PageReference gotoReports()
    {
        PageReference reports=new PageReference('/apex/ReportsList');
        reports.setRedirect(true);
        return reports;
    }
}