unpackaged/main/default/objects/Floor_Plan_Request__c/Floor_Plan_Request__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Floor Plan Request Custom Object</description>
    <label>Floor Plan Request</label>
    <nameField>
        <displayFormat>FPR-{000000}</displayFormat>
        <label>Floor Plan Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Floor Plan Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Floor_Plan_Request__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Floor Plan Requests</relationshipLabel>
    <relationshipName>Floor_Plan_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Floor_Plan_Request__c/fields/Fire_Marshaling__c.field-meta.xml
<CustomField>
    <fullName>Fire_Marshaling__c</fullName>
    <description>Does your show require Fire Marshaling at this time?</description>
    <inlineHelpText>Does your show require Fire Marshaling at this time?</inlineHelpText>
    <label>Fire Marshaling</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Floor_Plan_Request__c/fields/Halls__c.field-meta.xml
<CustomField>
    <fullName>Halls__c</fullName>
    <label>Hall(s)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Floor_Plan_Request__c/fields/Is_Approval_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Is_Approval_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approval Submitted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Floor_Plan_Request__c/fields/Request_Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Plan_Type__c</fullName>
    <label>Plan Type (Multi Select)</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Revision</fullName>
            </value>
            <value>
                <fullName>Fire Marshal</fullName>
            </value>
            <value>
                <fullName>Zone File Upload</fullName>
                <label>Zone Upload</label>
            </value>
            <value>
                <fullName>Management/Official Plan</fullName>
                <label>Management/Official</label>
            </value>
            <value>
                <fullName>Wall Build Plan</fullName>
            </value>
            <value>
                <fullName>Meeting/Skype with Drafter</fullName>
                <label>Meeting/Drafter Collaboration</label>
            </value>
            <value>
                <fullName>Building Maintenance</fullName>
            </value>
            <value>
                <fullName>Target Plan</fullName>
                <label>Ops - Target Plan</label>
            </value>
            <value>
                <fullName>Operations - Empty Plan</fullName>
                <label>Ops - Empty Plan</label>
            </value>
            <value>
                <fullName>Floor Marking</fullName>
                <label>Ops - Floor Marking</label>
            </value>
            <value>
                <fullName>Operations - Pipe &amp; Drape Plan</fullName>
                <label>Ops - Pipe &amp; Drape</label>
            </value>
            <value>
                <fullName>Operations - General Plan</fullName>
                <label>Ops - General Plan</label>
            </value>
            <value>
                <fullName>Exhibitor Service Plan</fullName>
            </value>
            <value>
                <fullName>Carpet Visual Delivery</fullName>
                <label>Visual Delivery - Carpet</label>
            </value>
            <value>
                <fullName>Deco Plan</fullName>
                <label>Visual Delivery - Deco</label>
            </value>
            <value>
                <fullName>NSC Heat Map</fullName>
            </value>
            <value>
                <fullName>TSE Electrical Download Plan</fullName>
                <label>TSE Electrical Download</label>
            </value>
            <value>
                <fullName>Prints</fullName>
            </value>
            <value>
                <fullName>Electronic File Request - Internal Use Only</fullName>
                <label>Electronic File Request - Internal Distribution</label>
            </value>
            <value>
                <fullName>Electronic File Request</fullName>
                <label>Electronic File Request - External Distribution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/FloorPlanRequestHandlerTest.cls
@isTest
public class FloorPlanRequestHandlerTest {
	@isTest
    static void testUpdateDueDate(){
        Opportunity opp=LC_TestUtils.insertOpportunity();
        GC_Connect2_Show__c show=LC_TestUtils.insertShow(opp.Id, opp.Name);
        
        Floor_Plan_Request__c fpr = new Floor_Plan_Request__c();
        fpr.Request_Plan_Type__c = 'Initial';
        fpr.Connect2_Show__c = show.Id;
        fpr.Halls__c = '1';
        fpr.Fire_Marshaling__c = 'Yes';
        insert fpr;
        fpr.Is_Approval_Submitted__c = true;
        update fpr;
    }
}