unpackaged/main/default/objects/GT_Brand__c/GT_Brand__c.object-meta.xml
<CustomObject>
    <description>This will be the product object for all accounts in Generic Template</description>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Brand__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup for Event Activity Type</description>
    <label>Event</label>
    <referenceTo>GT_Event_RL__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Exhibit__c.field-meta.xml
<CustomField>
    <fullName>Exhibit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibit</label>
    <referenceTo>GT_Exhibit__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up for GT_Event__c  (GES Connect Event)</description>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Meeting_Room__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting Room</label>
    <referenceTo>GT_Meeting_Room__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Speaking_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Speaking_Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Speaking Engagement</label>
    <referenceTo>GT_Speaking_Engagement__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsorship</label>
    <referenceTo>GT_Sponsorship__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/GT_Event__c.object-meta.xml
<CustomObject>
    <description>Object will be used to create Generic Template Account for GES Community. Main Event object for 1st Lightning Community. CC, Merck, SS, GT, Pharma Template, NNI.</description>
    <label>GES Connect Event</label>
    <nameField>
        <displayFormat>GCE-{000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Event__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/fields/Shipping_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State_Province__c</fullName>
    <label>Shipping State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GT_Event_RL__c/GT_Event_RL__c.object-meta.xml
<CustomObject>
    <description>This will be the Event (Related List to GES Connect Event) object for all Accounts under Generic Template</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Event_RL__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Event_RL__c/fields/Project_Manager_CrownCastle__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager_CrownCastle__c</fullName>
    <label>CC Project Manager</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Gina Carroll</fullName>
            </value>
            <value>
                <fullName>Juanita Timney</fullName>
            </value>
            <value>
                <fullName>Katie Lillie</fullName>
            </value>
            <value>
                <fullName>Lacey Hull</fullName>
            </value>
            <value>
                <fullName>Lisandra Fernandez</fullName>
            </value>
            <value>
                <fullName>Oswin Chackochan</fullName>
            </value>
            <value>
                <fullName>Stephanie Naida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GT_Exhibit__c/GT_Exhibit__c.object-meta.xml
<CustomObject>
    <description>This will be the Exhibit object for all Accounts under Generic Template</description>
    <label>Exhibit</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exhibit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Exhibit__c/fields/Contacts_Made__c.field-meta.xml
<CustomField>
    <fullName>Contacts_Made__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of contacts made</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GT_Exhibit__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Exhibits</relationshipLabel>
    <relationshipName>Exhibits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Meeting_Room__c/GT_Meeting_Room__c.object-meta.xml
<CustomObject>
    <description>This will be the Meeting Room object for all accounts in Generic Template</description>
    <label>Meeting Room</label>
    <nameField>
        <displayFormat>MR-{00000}</displayFormat>
        <label>Meeting Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Meeting_Room__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Meeting Rooms</relationshipLabel>
    <relationshipName>Meeting_Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Meeting_Room__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <label>CC Project Manager</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Gina Carroll</fullName>
            </value>
            <value>
                <fullName>Juanita Timney</fullName>
            </value>
            <value>
                <fullName>Katie Lillie</fullName>
            </value>
            <value>
                <fullName>Lacey Hull</fullName>
            </value>
            <value>
                <fullName>Lisandra Fernandez</fullName>
            </value>
            <value>
                <fullName>Oswin Chackochan</fullName>
            </value>
            <value>
                <fullName>Stephanie Naida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GT_Membership__c/GT_Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>MS-{0000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Membership__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Reg_Attend_Only__c/GT_Reg_Attend_Only__c.object-meta.xml
<CustomObject>
    <description>This will be the Registration/Attend Only object for all accounts in Generic Template</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Registration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Reg_Attend_Only__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipName>Registration_Attend_Only</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Reg_Attend_Only__c/fields/Project_Manager_CrownCastle__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager_CrownCastle__c</fullName>
    <label>CC Project Manager</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Gina Carroll</fullName>
            </value>
            <value>
                <fullName>Juanita Timney</fullName>
            </value>
            <value>
                <fullName>Katie Lillie</fullName>
            </value>
            <value>
                <fullName>Lacey Hull</fullName>
            </value>
            <value>
                <fullName>Lisandra Fernandez</fullName>
            </value>
            <value>
                <fullName>Oswin Chackochan</fullName>
            </value>
            <value>
                <fullName>Stephanie Naida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GT_Speaking_Engagement__c/GT_Speaking_Engagement__c.object-meta.xml
<CustomObject>
    <description>This will be the Speaking Engagement object for all accounts in Generic Template</description>
    <label>Speaking Engagement</label>
    <nameField>
        <displayFormat>SE-{00000}</displayFormat>
        <label>Speaking Engagement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speaking Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Speaking_Engagement__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Speaking Engagements</relationshipLabel>
    <relationshipName>Symposia</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Sponsorship__c/GT_Sponsorship__c.object-meta.xml
<CustomObject>
    <description>This will be the Sponsorship object for all accounts in Generic Template</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Sponsorship__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up for GT_Event__c</description>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Sporting_Event__c/GT_Sporting_Event__c.object-meta.xml
<CustomObject>
    <description>This will be the Sporting Event object for all accounts in Generic Template</description>
    <label>Sporting Event</label>
    <nameField>
        <displayFormat>SE - {0000}</displayFormat>
        <label>Sporting Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sporting Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Sporting_Event__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Sporting Events</relationshipLabel>
    <relationshipName>Sporting_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsorship__c/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Sponsorship</relationshipLabel>
    <relationshipName>Sponsorship_Instance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GT_Consolidated_EventTest.cls
@isTest
public class GT_Consolidated_EventTest {
   @testSetup static void setup() {
        GT_Event__c shw=new GT_Event__c(Shipping_City__c='Test',Shipping_State_Province__c='Test',Name_of_Event__c='Test Event',
                                        Event_Start_Date__c=Date.today(),Event_End_Date__c=Date.today()+3);
        insert shw; 
        GT_Event__c shw2=new GT_Event__c(Shipping_City__c='Test',Shipping_State_Province__c='Test',Name_of_Event__c='Test Event',
                                        Event_Start_Date__c=Date.today(),Event_End_Date__c=Date.today()+3);
        insert shw2; 
        GT_Exhibit__c ex=new GT_Exhibit__c(Project_Manager_CrownCastle__c='Juanita Timney', GES_Connect_Event__c = shw.Id, Contacts_Made__c=10);
        insert ex;
       	GT_Exhibit__c ex2=new GT_Exhibit__c(Project_Manager_CrownCastle__c='Juanita Timney', GES_Connect_Event__c = shw.Id, Contacts_Made__c=100);
        insert ex2;
        GT_Sponsorship__c sp=new GT_Sponsorship__c(Project_Manager_CrownCastle__c='Juanita Timney', GES_Connect_Event__c = shw.Id);
        insert sp;
        GT_Speaking_Engagement__c spk=new GT_Speaking_Engagement__c(Project_Manager_CrownCastle__c='Juanita Timney', GES_Connect_Event__c = shw.Id);
        insert spk;
        GT_Meeting_Room__c mtng=new GT_Meeting_Room__c(Project_Manager__c='Juanita Timney', GES_Connect_Event__c = shw.Id);
        insert mtng;
        GT_Event_RL__c evt=new GT_Event_RL__c(Project_Manager_CrownCastle__c='Juanita Timney', GES_Connect_Event__c = shw.Id,Event_Room_Name__c='Test');
        insert evt;
        GT_Reg_Attend_Only__c rg=new GT_Reg_Attend_Only__c(Project_Manager_CrownCastle__c='Juanita Timney', GES_Connect_Event__c = shw.Id,Names_of_Attendees__c='Test');
        insert rg;
        GT_Sporting_Event__c sprt=new GT_Sporting_Event__c(CC_Project_Manager__c='Juanita Timney', GES_Connect_Event__c = shw.Id,Sporting_Event_Type__c='Suite');
        insert sprt;
        GT_Membership__c member=new GT_Membership__c(CC_Project_Manager__c='Juanita Timney', GES_Connect_Event__c = shw.Id);
       insert member;
       GT_Brand__c brand=new GT_Brand__c(GES_Connect_Event__c=shw.Id,Exhibit__c=ex.Id,Booth_Space_Cost_Actual__c=20,
                                         Booth_Space_Cost_Estimated__c=40,GES_Costs_Estimated__c=30,GES_Costs_Actual__c=40,
                                        Sponsorship__c=sp.Id,Speaking_Engagement__c=spk.Id,Meeting_Room__c=mtng.Id,Event__c=evt.Id,
                                        Registration_Attend_Only__c=rg.id,Sporting_Event__c=sprt.Id,Membership__c=member.Id,Sales_Leaders__c='Fagan');
        insert brand;
    }
    Public Static Testmethod void test(){
        //GT_Consolidated_Event evt=new GT_Consolidated_Event();
         GT_Consolidated_Event.fetchReports(null,null,null,null,null);
         GT_Consolidated_Event.fetchReports(string.valueOfGmt(Date.today()),string.valueOfGmt(Date.today()+3),'Fagan', 'No', 'No');
    }
    
    @isTest
     static void testInit(){
         GT_Consolidated_Event.init();
    }
    
}