unpackaged/main/default/objects/GT_Brand__c/GT_Brand__c.object-meta.xml
<CustomObject>
    <description>This will be the product object for all accounts in Generic Template</description>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Brand__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup for Event Activity Type</description>
    <label>Event</label>
    <referenceTo>GT_Event_RL__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Exhibit__c.field-meta.xml
<CustomField>
    <fullName>Exhibit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibit</label>
    <referenceTo>GT_Exhibit__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/General_Event_Costs__c.field-meta.xml
<CustomField>
    <fullName>General_Event_Costs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Event Costs</label>
    <referenceTo>GT_General_Event_Costs__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up for GT_Event__c  (GES Connect Event)</description>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Meeting_Planning__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Planning__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting Planning</label>
    <referenceTo>GT_Meeting_Planning__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Meeting_Room__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meeting Room</label>
    <referenceTo>GT_Meeting_Room__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>GT_Membership__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Speaking_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Speaking_Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Speaking Engagement</label>
    <referenceTo>GT_Speaking_Engagement__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsorship</label>
    <referenceTo>GT_Sponsorship__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Brand__c/fields/Sporting_Event__c.field-meta.xml
<CustomField>
    <fullName>Sporting_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sporting Event</label>
    <referenceTo>GT_Sporting_Event__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Event_RL__c/GT_Event_RL__c.object-meta.xml
<CustomObject>
    <description>This will be the Event (Related List to GES Connect Event) object for all Accounts under Generic Template</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Event_RL__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Exhibit__c/GT_Exhibit__c.object-meta.xml
<CustomObject>
    <description>This will be the Exhibit object for all Accounts under Generic Template</description>
    <label>Exhibit</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exhibit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Exhibit__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Exhibits</relationshipLabel>
    <relationshipName>Exhibits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_General_Event_Costs__c/GT_General_Event_Costs__c.object-meta.xml
<CustomObject>
    <description>This is an Activity Type for Crown Castle Users in Generic Template (GT).</description>
    <label>General Event Costs</label>
    <nameField>
        <displayFormat>GEC-{00000}</displayFormat>
        <label>General Event Costs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Event Costs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_General_Event_Costs__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>General Event Costs</relationshipLabel>
    <relationshipName>General_Event_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Meeting_Planning__c/GT_Meeting_Planning__c.object-meta.xml
<CustomObject>
    <description>This object is for NNI Customers to track the details around having GES do their meeting planning</description>
    <label>Meeting Planning</label>
    <nameField>
        <displayFormat>MP-{00000}</displayFormat>
        <label>Meeting Planning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Meeting_Planning__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Meeting Planning</relationshipLabel>
    <relationshipName>Meeting_Plannings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Meeting_Room__c/GT_Meeting_Room__c.object-meta.xml
<CustomObject>
    <description>This will be the Meeting Room object for all accounts in Generic Template</description>
    <label>Meeting Room</label>
    <nameField>
        <displayFormat>MR-{00000}</displayFormat>
        <label>Meeting Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Meeting_Room__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Meeting Rooms</relationshipLabel>
    <relationshipName>Meeting_Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Membership__c/GT_Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>MS-{0000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Membership__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Reg_Attend_Only__c/GT_Reg_Attend_Only__c.object-meta.xml
<CustomObject>
    <description>This will be the Registration/Attend Only object for all accounts in Generic Template</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Registration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Reg_Attend_Only__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipName>Registration_Attend_Only</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Speaking_Engagement__c/GT_Speaking_Engagement__c.object-meta.xml
<CustomObject>
    <description>This will be the Speaking Engagement object for all accounts in Generic Template</description>
    <label>Speaking Engagement</label>
    <nameField>
        <displayFormat>SE-{00000}</displayFormat>
        <label>Speaking Engagement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speaking Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Speaking_Engagement__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Speaking Engagements</relationshipLabel>
    <relationshipName>Symposia</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Sponsorship__c/GT_Sponsorship__c.object-meta.xml
<CustomObject>
    <description>This will be the Sponsorship object for all accounts in Generic Template</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Sponsorship__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up for GT_Event__c</description>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Sporting_Event__c/GT_Sporting_Event__c.object-meta.xml
<CustomObject>
    <description>This will be the Sporting Event object for all accounts in Generic Template</description>
    <label>Sporting Event</label>
    <nameField>
        <displayFormat>SE - {0000}</displayFormat>
        <label>Sporting Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sporting Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Sporting_Event__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipLabel>Sporting Events</relationshipLabel>
    <relationshipName>Sporting_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <description>Used for Pfizer in GES Connect</description>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sponsorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sponsorship__c/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GES Connect Corporate Accounts</label>
    <referenceTo>GES_Connect_Corporate_Accounts__c</referenceTo>
    <relationshipLabel>Sponsorship</relationshipLabel>
    <relationshipName>Sponsorship_Instance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GT_ProductCreateController.cls
/**
* @Author   :		Namratha
* @Date		:		24-Oct-2018
* @Desc		:		Controller for GT_Product Create Component
* */
public class GT_ProductCreateController {
    
    @AuraEnabled
    public static String getObjectName(id ObjectId){
        String objectname;
        objectName = String.valueOf(ObjectId.getSObjectType());
        System.debug('objectname-----'+objectname);
        
        return objectName;
    }
    
    @AuraEnabled
    public Static String getProfileName(){
        id userId = userinfo.getProfileId();
        LIST<profile> ProfileName = new LIST<profile>();
		ProfileName = [select Name,Id from profile where id = :userId LIMIT 1];
        system.debug('profile id--->'+ProfileName[0].Id);
        Return ProfileName[0].Name;
    }
    
    @AuraEnabled
    public static Object getObject(id ObjectId){
        
        Object  ParentObject;
        String recordId;
        String objectname;
        
        objectName = String.valueOf(ObjectId.getSObjectType());
        System.debug('objectname-----'+objectname);
        
        if(objectName.contains('GT_Exhibit__c')){
            GT_Exhibit__c exhibit = [select name,Id,GES_Connect_Event__c,GES_Connect_Event__r.Name,GES_Connect_Event__r.CurrencyIsoCode from GT_Exhibit__c
                                     where id =: ObjectId ];
            System.debug('exhibit>>>'+exhibit);
            ParentObject = exhibit;
        }
        else if(objectName.contains('GT_Sponsorship__c')){
            GT_Sponsorship__c sponsorship = [select name,Id,GES_Connect_Event__c,GES_Connect_Event__r.Name from GT_Sponsorship__c
                                             where id =: ObjectId ];
            ParentObject = sponsorship;
        }
        else if(objectName.contains('GT_Meeting_Room__c')){
            GT_Meeting_Room__c meetingRoom = [select name,Id,GES_Connect_Event__c,GES_Connect_Event__r.Name from GT_Meeting_Room__c
                                              where id =: ObjectId ];
            ParentObject = meetingRoom;
        }
        else if(objectName.contains('GT_Speaking_Engagement__c')){
            GT_Speaking_Engagement__c speakingEngagement = [select name,Id,GES_Connect_Event__c,GES_Connect_Event__r.Name from GT_Speaking_Engagement__c
                                                            where id =: ObjectId ];
            ParentObject = speakingEngagement;
        }
        else if(objectName.contains('GT_Event_RL__c')){
            GT_Event_RL__c eventObj = [select name,Id,GES_Connect_Event__c,GES_Connect_Event__r.Name from GT_Event_RL__c
                                       where id =: ObjectId ];
            ParentObject = eventObj;
        }
        else if(objectName.contains('GT_Reg_Attend_Only__c')){
            GT_Reg_Attend_Only__c regAttendObj = [select name,Id,GES_Connect_Event__c,GES_Connect_Event__r.Name from GT_Reg_Attend_Only__c
                                                  where id =: ObjectId ];
            ParentObject = regAttendObj;
        }
         else if(objectName.contains('GT_General_Event_Costs__c')){
            GT_General_Event_Costs__c generalEventObj = [select name,Id,GES_Connect_Event__c,GES_Connect_Event__r.Name from GT_General_Event_Costs__c
                                                  where id =: ObjectId ];
            ParentObject = generalEventObj;
        }
        else if(objectName.contains('GT_Meeting_Planning__c')){
            GT_Meeting_Planning__c meetingPlanningObj = [select name,Id,GES_Connect_Event__c,GES_Connect_Event__r.Name from GT_Meeting_Planning__c
                                                  where id =: ObjectId ];
            ParentObject = meetingPlanningObj;
        }
        else if(objectName.contains('GT_Sporting_Event__c')){
            GT_Sporting_Event__c sportingEventObj = [select name,Id,GES_Connect_Event__c,GES_Connect_Event__r.Name from GT_Sporting_Event__c
                                                  where id =: ObjectId ];
            ParentObject = sportingEventObj;
        }
        else if(objectName.contains('GT_Membership__c')){
            GT_Membership__c membershipObj = [select name,Id,GES_Connect_Event__c,GES_Connect_Event__r.Name from GT_Membership__c
                                                  where id =: ObjectId ];
            ParentObject = membershipObj;
        }
        
        return ParentObject;
    }
    
    @AuraEnabled
    public static Object getProductObj(id ObjectId){
        
        GT_Brand__c brandObj = [SELECT id,name,GES_Connect_Event__c,Event__c,Exhibit__c,
                                Meeting_Room__c,Sponsorship__c,Speaking_Engagement__c,Registration_Attend_Only__c,Meeting_Planning__c,
                                General_Event_Costs__c,Sporting_Event__c,Membership__c,GES_Connect_Event__r.name,
                                Event__r.name,Exhibit__r.name,Sponsorship__r.name, Meeting_Room__r.name,Registration_Attend_Only__r.name,
                                General_Event_Costs__r.name,Speaking_Engagement__r.name,Meeting_Planning__r.name, Sporting_Event__r.name,Membership__r.name from GT_Brand__c where id =: ObjectId LIMIT 1];
        System.debug('brandObj-----'+brandObj);
        System.debug('name --->'+brandObj.Meeting_Room__r.name);
        
        return brandObj;
    }
}