unpackaged/main/default/objects/GT_Brand__c/GT_Brand__c.object-meta.xml
<CustomObject>
    <description>This will be the product object for all accounts in Generic Template</description>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GT_Brand__c/fields/GES_Connect_Event__c.field-meta.xml
<CustomField>
    <fullName>GES_Connect_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up for GT_Event__c  (GES Connect Event)</description>
    <label>GES Connect Event</label>
    <referenceTo>GT_Event__c</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GT_Event__c/GT_Event__c.object-meta.xml
<CustomObject>
    <description>Object will be used to create Generic Template Account for GES Community. Main Event object for 1st Lightning Community. CC, Merck, SS, GT, Pharma Template, NNI.</description>
    <label>GES Connect Event</label>
    <nameField>
        <displayFormat>GCE-{000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Connect Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/GT_BrandTriggerTest.cls
@isTest(SeeAllData=true)
public class GT_BrandTriggerTest {
    public static testMethod void testMethod1() {
        User u=[select id from user where id='0051W000004H9WM'];
        System.runAs(u){
            GT_Event__c evt=new GT_Event__c(currencyisocode='USD');
            insert evt;
            GT_Brand__c brand=new GT_Brand__c(GES_Connect_Event__c=evt.id);
            insert brand;
        }
    }

}