unpackaged/main/default/objects/Booth_Staging__c/Booth_Staging__c.object-meta.xml
<CustomObject>
    <description>A place where test Booths and Booth Contacts live until approved</description>
    <label>Booth Staging</label>
    <nameField>
        <displayFormat>BStage-{0000}</displayFormat>
        <label>Booth Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booth Staging</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Booth_Staging__c/fields/Agency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Agency_Contact__c</fullName>
    <label>Agency Contact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Booth_Staging__c/fields/Agency_Email__c.field-meta.xml
<CustomField>
    <fullName>Agency_Email__c</fullName>
    <label>Agency Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Booth_Staging__c/fields/Booth_Upload__c.field-meta.xml
<CustomField>
    <fullName>Booth_Upload__c</fullName>
    <label>Booth Upload</label>
    <referenceTo>Booth_Upload__c</referenceTo>
    <relationshipLabel>Booth Staging</relationshipLabel>
    <relationshipName>Booth_Staging</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Booth_Staging__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Staging_Booths</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Booth_Staging__c/fields/Post_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Post_Zip_Code__c</fullName>
    <label>Post/Zip Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Booth_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status will automatically be changed to Confirmed when the File Upload has been Confirmed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Booth_Upload__c/Booth_Upload__c.object-meta.xml
<CustomObject>
    <label>Booth Upload</label>
    <nameField>
        <displayFormat>BUP-{0000}</displayFormat>
        <label>Booth Upload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booth Upload</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Booth_Upload__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Opportunity needs to be an EMEA - Exhibition record</errorMessage>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>EMEA - Exhibition</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booth Upload</relationshipLabel>
    <relationshipName>Booth_Upload</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Booth_Upload__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MasterUploadControllerTest.cls
@isTest
private class MasterUploadControllerTest {
	@isTest static void test_method_one() {
		Profile profile1 = [SELECT Id FROM Profile WHERE Name='Standard User']; 
		User testUser = new User(
	   	ProfileId = profile1.Id,
	    Username ='DarkKnight@test.com',
	   	Alias = 'batman',
	   	Email='bruce.wayne@wayneenterprises.com',
	   	EmailEncodingKey='UTF-8',
	   	Firstname='Bruce',
	   	Lastname='Wayne',
	   	LanguageLocaleKey='en_US',
	   	LocaleSidKey='en_US',
	   	TimeZoneSidKey='America/Chicago'
	   	);
		insert(testUser);

		Opportunity op1 = new Opportunity();
		op1.Name = 'opp1';
		op1.stageName = 'oppStage';
		op1.closeDate = Date.today();
		insert op1;
		Booth_Upload__c bu = new Booth_Upload__c();
		bu.Opportunity__c = op1.id;
		insert bu;
		Booth_Staging__c b = new Booth_Staging__c();
		b.Booth_Upload__c = bu.id;
		b.Status__c = 'New';
		insert b;

		ApexPages.StandardController sc = new ApexPages.StandardController(bu);
		system.currentPageReference().getParameters().put('Id', bu.Id);
		MasterUploadController muc = new MasterUploadController(sc);
		muc.resetAlerts();
		muc.gotoImportBuddy();
		muc.isdeleting();
		muc.saveRecords();
		try {
			muc.CancelBatch();
		} catch (Exception e) {
			system.debug(e);
		}
		try {
			muc.CheckBatch();
		} catch(Exception e) {
			system.debug(e);
		}
		try {
			muc.confirmRecords();	
		} catch(Exception e){
			system.debug(e);
		}
		try	{
			muc.RedirectIfNotFound();
		} catch(Exception e) {
			system.debug(e);
		}
		Integer i = muc.noPages;
		muc.firstPage();
		muc.lastPage();
		muc.currentPage = 4;
		muc.previousPage();
		muc.currentPage = -4;
		muc.nextPage();
	}
    
    @isTest public static void test_for_Lightning() {
        List<Booth_Staging__c> bsList = new List<Booth_Staging__c>();
        Opportunity op1 = new Opportunity();
		op1.Name = 'opp1';
		op1.stageName = 'oppStage';
		op1.closeDate = Date.today();
		insert op1;
		Booth_Upload__c bu = new Booth_Upload__c();
		bu.Opportunity__c = op1.id;
		insert bu;
		Booth_Staging__c bs_good = new Booth_Staging__c();
		bs_good.Booth_Upload__c = bu.id;
		bs_good.Status__c = 'New';
        bsList.add(bs_good);
        Booth_Staging__c bs_bad = new Booth_Staging__c();
		bs_bad.Booth_Upload__c = bu.id;
		bs_bad.Status__c = 'NONE';
		bs_bad.Post_Zip_Code__c = '323423423412342134';
        bsList.add(bs_bad);
        MasterUploadController.createStageRecords(bsList,new List<String>{'Test'});
        Test.startTest();
		MasterUploadController.sendEmailAfterFileUpload('TestHeading1,TestHeading2 \n Test1,Test2',true,bu.id);
		Test.stopTest();
        MasterUploadController.getAllColumnsDetail('Booth_Staging__c');
        MasterUploadController.showStageData('["Status__c","Name","Company__c","Country__c","Agency_Email__c","Agency_Contact__c"]','Booth_Staging__c',bu.id);
        String batchId = MasterUploadController.runTheBatch(bu.id);
        MasterUploadController.checkRunningBatchStatus(bu.id,batchId);
        MasterUploadController.deleteBsRecords([SELECT Id from Booth_Staging__c where Booth_Upload__c =: bu.id]);
        MasterUploadController.checkRunningBatchStatus(bu.id,batchId);
    }
}