unpackaged/main/default/objects/ApexLog__c/ApexLog__c.object-meta.xml
<CustomObject>
    <label>ApexLog</label>
    <nameField>
        <label>APEX Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApexLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApexLog__c/fields/RecordId_Data__c.field-meta.xml
<CustomField>
    <fullName>RecordId_Data__c</fullName>
    <label>RecordId/Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/Core_Exhibitor__c.object-meta.xml
<CustomObject>
    <label>Core Exhibitor</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Exhibitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Counter__c.field-meta.xml
<CustomField>
    <fullName>Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Error Counter</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Melissa_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Integration_Status__c</fullName>
    <label>Melissa Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Melissa Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Melissa_Results__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Results__c</fullName>
    <label>Melissa Results</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MelissaSetting__c/MelissaSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is specify, melissa switch, Counter ,Melissa error etc. Don&#39;t change the Name field value.It is use in apex melissa classes.</description>
    <label>Melissa Setting</label>
</CustomObject>

unpackaged/main/default/classes/HttpCalloutController.cls
/*********************************************************************
    Date    : 18 April 2017 
    Note    : This class contains one method getCalloutResponseContents() that returns callout response.
              We can use this class to perform HTTP callout when request is in JSON.
    Change History
    =============
    Developer       Modified On     Change description
                  
**********************************************************************/
public class HttpCalloutController {

  Map<String,MelissaSetting__c> melissaSetting = MelissaSetting__c.getAll();

  decimal counterFromSetting=decimal.valueOf(melissaSetting.get('Melissa Counter').value__c);

  // Pass in the endpoint/Method(GET/POST/PUT etc.)/request body to be used using the string url
  public HttpResponse getCalloutResponseContents(String url, string HTTPMethod, map<string,string> mapOfHeader, string jsonBody, boolean isCompressed) {
    
    HttpResponse response ;
 
    // Instantiate a new http object
    Http h = new Http();
    system.debug('my request ++ ' + jsonBody );
    // Instantiate a new HTTP request, specify the method (GET) as well as the endpoint
    HttpRequest req = new HttpRequest();
    req.setEndpoint(url);
    req.setMethod(HTTPMethod);
    req.setBody(jsonBody);
    // to support multiple headers
    for(string headerkey : mapOfHeader.keyset()){
        req.setHeader(headerkey, mapOfHeader.get(headerkey));
    }
    req.setCompressed(isCompressed);
    req.setTImeout(120000);

    // Send the request, and return a response
    system.debug('**************req'+req);
    try{
       
        response = h.send(req);
        System.debug('responseBody: '+response.getBody()); 
        
    }catch(System.CalloutException ex){
        
        // Log the exception
        APEXLog__c log = new APEXLog__c(); 
        log.ClassName__c = 'HttpCalloutCOntroller';
        log.Message__c = ex.getMessage();
        log.StackTrace__c =  ex.getStackTraceString();
        log.Method__c = 'getCalloutResponseContents';      
        log.RecordId_Data__c = jsonBody;                       
        insert log;
    }
    return response;
  }
  
   // Pass in the endpoint/Method(GET/POST/PUT etc.)/request body to be used using the string url
  public HttpResponse getCalloutResponseContentsMelissa(Map<Id,CORE_EXHIBITOR__c> mapCoreExhibitor,String url, string HTTPMethod, map<string,string> mapOfHeader, string jsonBody, boolean isCompressed) {
    
    HttpResponse response ;
   
    // Instantiate a new http object
    Http h = new Http();
    system.debug('my request ++ ' + jsonBody );
    // Instantiate a new HTTP request, specify the method (GET) as well as the endpoint
    HttpRequest req = new HttpRequest();
    req.setEndpoint(url);
    req.setMethod(HTTPMethod);
    req.setBody(jsonBody);
    // to support multiple headers
    for(string headerkey : mapOfHeader.keyset()){
        req.setHeader(headerkey, mapOfHeader.get(headerkey));
    }
    req.setCompressed(isCompressed);
    req.setTImeout(120000);

    // Send the request, and return a response
    system.debug('**************req'+req);
    try{
       
        response = h.send(req);
        System.debug('responseBody: '+response.getBody()); 
        
    }catch(System.CalloutException ex){
        
        Set<ID> setCoreExhbID=new Set<ID>();
        List<CORE_EXHIBITOR__c> listCoreExhbt=new List<CORE_EXHIBITOR__c>();
        for(Id coreexhbtID: mapCoreExhibitor.keyset()){
            system.debug('============>jsonBody'+jsonBody+'------'+jsonBody.contains(coreexhbtID));
            //if(jsonBody!=null && jsonBody.contains(coreexhbtID)){
                setCoreExhbID.add(coreexhbtID);
            //}
        }
        for(CORE_EXHIBITOR__c objCoreExhbt:[select Counter__c,Melissa_Integration_Status__c,Melissa_Results__c from CORE_EXHIBITOR__c where id in :setCoreExhbID]){
            
            objCoreExhbt.Counter__c=objCoreExhbt.Counter__c!=null?objCoreExhbt.counter__c:0;
            objCoreExhbt.counter__C=objCoreExhbt.counter__C+1;
            if(objCoreExhbt.Counter__c>=counterFromSetting){
                    objCoreExhbt.Melissa_Integration_Status__c = 'Success';
                    objCoreExhbt.Counter__c=0;
            }else{
                    objCoreExhbt.Melissa_Integration_Status__c ='Failed';
                    objCoreExhbt.Melissa_Results__c=ex.getMessage();
            }
            listCoreExhbt.add(objCoreExhbt);
        }
        
        update listCoreExhbt;
        // Log the exception
        APEXLog__c log = new APEXLog__c(); 
        log.ClassName__c = 'HttpCalloutCOntroller';
        log.Message__c = ex.getMessage();
        log.StackTrace__c =  ex.getStackTraceString();
        log.Method__c = 'getCalloutResponseContents';      
        log.RecordId_Data__c = jsonBody;                       
        insert log;
    }
    return response;
  }
}