unpackaged/main/default/objects/Booth_Area__c/Booth_Area__c.object-meta.xml
<CustomObject>
    <label>Booth Area</label>
    <nameField>
        <label>Booth Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booth Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area__c</fullName>
    <description>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</description>
    <inlineHelpText>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</inlineHelpText>
    <label>Delivery Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Status of the Order.  Defaults to &#39;New&#39; and will clearly indicate the status of the order state and what its in.</description>
    <inlineHelpText>Status of the Order.</inlineHelpText>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Attribute__c/GC_Show_Attribute__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Attribute object for use in storing dynamic lookup content for a Show such as Department / Sign Types / Hall Information / Area Information / Sign Sizes and other related content.  Each type of object is defined by RecordType.</description>
    <label>Show Attribute</label>
    <nameField>
        <label>Show Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Show Attributes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/GC_Vendor_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Vendor Order Task Custom Object. This Object is used to identify Vendor Order Task details to be performed in a GES Connect Show.</description>
    <label>Vendor Order Task</label>
    <nameField>
        <displayFormat>VOT-{0000}</displayFormat>
        <label>Vendor Order Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Delivery_Location_Ven__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Location_Ven__c</fullName>
    <label>Delivery Area</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the GES Order associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order associated with this vendor order task.</inlineHelpText>
    <label>Delivery Location</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipLabel>Vendor Order Tasks</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Vendor Order Task.</description>
    <inlineHelpText>Status of the Vendor Order Task.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LC_VOTRelatedListControllerTest.cls
@isTest
public class LC_VOTRelatedListControllerTest {
    @testsetup
    public static void testSetup(){
        Opportunity opp=LC_TestUtils.insertOpportunity();
        GC_Connect2_Show__c show=LC_TestUtils.insertShow(opp.Id,opp.Name);
        GC_Order__c order=LC_TestUtils.insertOrder(show.Id);
        GC_Show_Attribute__c serviceAttribute=LC_TestUtils.insertServiceAttributes(show.Id);
        GC_Show_Attribute__c venueAttribute=LC_TestUtils.insertVenueAttributes(show.Id);
        GC_Show_Team_Member__c member=LC_TestUtils.insertShowTeamMember(serviceAttribute.Id,show.Id);
        GC_Vendor_Order_Task__c vot=LC_TestUtils.insertVOT(order.Id,serviceAttribute.Id);
    }
    @isTest
    public static void testMethod1() {
        GC_Show_Team_Member__c member=[select User__c from GC_Show_Team_Member__c limit 1];
        GC_Show_Team_Member__c mem=[select User__r.Name from GC_Show_Team_Member__c where User__c=:member.User__c];
        string vendorName=mem.User__r.Name;
        GC_Order__c order=[select id from GC_Order__c where Booth_Area__c='new Booth Area'];
        GC_Vendor_Order_Task__c vot=[select id, name,Status__c,Order__c,Delivery_Location_Ven__c from GC_Vendor_Order_Task__c where Delivery_Location_Ven__c='votForExistingMethod Location'];
        Test.startTest();    
        LC_VOTRelatedListController.getOrdersData(order.Id);
        LC_VOTRelatedListController.fetchVOTData(order.Id);
        LC_VOTRelatedListController.getPicklistValues(order.Id);
        LC_VOTRelatedListController.getVenueLocations(order.Id);
        LC_VOTRelatedListController.InsertVOT(null,false,order.Id,'Test Service attribut1','Test Service attribut1','Test Service attribut1','Test Service attribut1','Test Service attribut1',vendorName,vendorName,vendorName,vendorName,vendorName,'Test Vendor Instructions from Test Class','Test Venue attribut1','Delivery Area',system.today().addDays(10),system.today().addDays(5),system.today().addDays(11));
        LC_VOTRelatedListController.existingValues(vot.Id);  
        //LC_VOTRelatedListController.getOrderID(vot.Id);
        LC_VOTRelatedListController.vendorsAssigned(vot.Id);
        LC_VOTRelatedListController.getClonedVOT();
        LC_VOTRelatedListController.InsertVOT(vot.Id,true,order.Id,'Test Service attribut1','Test Service attribut1','Test Service attribut1','Test Service attribut1','Test Service attribut1',vendorName,vendorName,vendorName,vendorName,vendorName,'Test Vendor Instructions from Test Class','Test Venue attribut1','Delivery Area',system.today().addDays(10),system.today().addDays(5),system.today().addDays(11));
        LC_VOTRelatedListController.InsertVOT(vot.Id,false,order.Id,'Test Service attribut1','Test Service attribut1','Test Service attribut1','Test Service attribut1','Test Service attribut1',vendorName,vendorName,vendorName,vendorName,vendorName,'Test Vendor Instructions from Test Class','Test Venue attribut1','Delivery Area',system.today().addDays(10),system.today().addDays(5),system.today().addDays(11));
        LC_VOTRelatedListController.submitRecord(vot.Id);
        LC_VOTRelatedListController.deleteVOTRecords(vot.Id);
        LC_VOTRelatedListController.isCommunity();
        system.debug('vot---'+vot);
        LC_VOTRelatedListController.getVotBannerData(vot.Id);
        LC_VOTRelatedListController.getCurrentUserProfile();
        Test.stopTest();
    }
}