unpackaged/main/default/objects/Booth_Area__c/Booth_Area__c.object-meta.xml
<CustomObject>
    <label>Booth Area</label>
    <nameField>
        <label>Booth Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booth Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Booth_Area__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Booth Areas</relationshipLabel>
    <relationshipName>Booth_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>GES Connect Order Object.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area__c</fullName>
    <description>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</description>
    <inlineHelpText>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</inlineHelpText>
    <label>Delivery Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area_ID__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area_ID__c</fullName>
    <description>Booth Area ID known by the External System.  Used for mapping the Item Discounts associated with a booth area.</description>
    <inlineHelpText>Booth Area ID known by the External System.  Used for mapping the Item Discounts associated with a booth area.</inlineHelpText>
    <label>Booth Area ID (Hidden)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Show_Role__c.field-meta.xml
<CustomField>
    <fullName>Show_Role__c</fullName>
    <description>Determines the level of access to associated elements on a show.</description>
    <inlineHelpText>Determines the level of access to associated elements on a show.</inlineHelpText>
    <label>Show Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Convention_Planning</fullName>
                <label>Convention Planning</label>
            </value>
            <value>
                <fullName>Creative Director</fullName>
            </value>
            <value>
                <fullName>Designer/Detailer</fullName>
            </value>
            <value>
                <fullName>Director of Account Management</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>Graphics Project Manager Direct</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Secondary Account Manager</fullName>
            </value>
            <value>
                <fullName>Show Organizer</fullName>
            </value>
            <value>
                <fullName>Show Organizer - Read Only</fullName>
            </value>
            <value>
                <fullName>Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/GC_Vendor_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Vendor Order Task Custom Object. This Object is used to identify Vendor Order Task details to be performed in a GES Connect Show.</description>
    <label>Vendor Order Task</label>
    <nameField>
        <displayFormat>VOT-{0000}</displayFormat>
        <label>Vendor Order Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/GESOrderTask1__c.field-meta.xml
<CustomField>
    <fullName>GESOrderTask1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the GES Order Task associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order Task associated with this vendor order task.</inlineHelpText>
    <label>GES Order Task 1</label>
    <referenceTo>GC_GES_Order_Task__c</referenceTo>
    <relationshipLabel>GES Order Tasks</relationshipLabel>
    <relationshipName>GES_Order_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the GES Order associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order associated with this vendor order task.</inlineHelpText>
    <label>Delivery Location</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipLabel>Vendor Order Tasks</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor2__c.field-meta.xml
<CustomField>
    <fullName>Vendor2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor 2</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor3__c.field-meta.xml
<CustomField>
    <fullName>Vendor3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor 3</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor4__c.field-meta.xml
<CustomField>
    <fullName>Vendor4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor 4</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor5__c.field-meta.xml
<CustomField>
    <fullName>Vendor5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor 5</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Instructions__c</fullName>
    <description>Instructions to the Vendor.</description>
    <inlineHelpText>Instructions to the Vendor indicating services needed.</inlineHelpText>
    <label>Vendor Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/classes/GC_VendorOrderTaskTriggerHandlerTest.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Test code for Vendor Order Task trigger handler
* 2016-04-13 : Original Version
**/
@isTest
private class GC_VendorOrderTaskTriggerHandlerTest {

    @isTest static void TestInsertAndUpdate() {
        GC_Connect2_Show__c show = GC_TestUtils.getTestConnect2Show();
        GC_Order__c order = new GC_Order__c();
        order.Connect2_Show__c = show.Id;
        order.Booth_Area_ID__c = '1390259';
        order.Booth_Area__c = 'Area';
        insert order;
        GC_Vendor_Order_Task__c task = new GC_Vendor_Order_Task__c();
        task.Order__c = order.id;
        insert task;
        task.Vendor_Instructions__c = 'test instructions';
        update task;
    }

    @isTest
    private static void TriggerTest() {
        GC_Connect2_Show__c show = GC_TestUtils.getTestConnect2Show();
        GC_Order__c order = new GC_Order__c();
        order.Connect2_Show__c = show.Id;
        order.Booth_Area_ID__c = '1390259';
        order.Booth_Area__c = 'Area';
        insert order;
        GC_GES_Order_Task__c got = new GC_GES_Order_Task__c();
        got.Order__c = order.Id;
        insert got;

        Account acc = GC_TestUtils.getAccount();
        User vendor1 = GC_TestUtils.createPortalUser('GC Community Vendor', 'unit_test', 'vendor1', acc);
        User vendor2 = GC_TestUtils.createPortalUser('GC Community Vendor', 'unit_test', 'vendor2', acc);
        User vendor3 = GC_TestUtils.createPortalUser('GC Community Vendor', 'unit_test', 'vendor3', acc);
        User vendor4 = GC_TestUtils.createPortalUser('GC Community Vendor', 'unit_test', 'vendor4', acc);
        User vendor5 = GC_TestUtils.createPortalUser('GC Community Vendor', 'unit_test', 'vendor5', acc);

        Test.startTest();

        GC_Vendor_Order_Task__c vendorTask = new GC_Vendor_Order_Task__c();
        vendorTask.Order__c = order.Id;
        vendorTask.Vendor__c = vendor1.Id;
        vendorTask.Vendor2__c = vendor2.Id;
        vendorTask.Vendor3__c = vendor3.Id;
        vendorTask.Vendor4__c = vendor4.Id;
        vendorTask.Vendor5__c = vendor5.Id;
        insert vendorTask;
        
        GC_GES_Order_Task__c got2 = new GC_GES_Order_Task__c();
        got2.Order__c = order.Id;
        insert got2;
        
        List<GC_Show_Team_Member__c> stms = [select Id, User__r.Name from GC_Show_Team_Member__c where Connect2_Show__c = :show.Id AND Show_Role__c = 'Vendor'];
        //System.assertEquals(5, stms.size());

        vendorTask.Vendor_Instructions__c = 'test instructions';
        vendorTask.GESOrderTask1__c = got.Id;

        update vendorTask;

        // run as vendor user and verify access
        System.runAs(vendor5) {
            List<GC_GES_Order_Task__c> gots = [select Id, Name from GC_GES_Order_Task__c where Id = :got.id];
            System.assertEquals(1, gots.size());
            List<GC_Order__c> orders = [select Id, Name from GC_Order__c where Id = :order.id];
            System.assertEquals(1, orders.size());
            List<GC_Connect2_Show__c> shows = [select Id, Name from GC_Connect2_Show__c where Id = :show.Id];
            System.assertEquals(1, shows.size());
        }

        Test.stopTest();
    }

}