unpackaged/main/default/objects/Booth_Area__c/Booth_Area__c.object-meta.xml
<CustomObject>
    <label>Booth Area</label>
    <nameField>
        <label>Booth Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booth Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Formula to Show Name</description>
    <formula>Order__r.Show_Name__c</formula>
    <inlineHelpText>Show Name</inlineHelpText>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that display&#39;s different status values</description>
    <inlineHelpText>Status of GES Order Task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Graphics Requested</fullName>
            </value>
            <value>
                <fullName>Graphics Submitted</fullName>
            </value>
            <value>
                <fullName>Graphics Rejected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Submitted to Graphics</fullName>
            </value>
            <value>
                <fullName>Submitted For AM Review</fullName>
            </value>
            <value>
                <fullName>Pending AM Review</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area__c</fullName>
    <description>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</description>
    <inlineHelpText>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</inlineHelpText>
    <label>Delivery Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Formula to Connect2 Show&#39;s Show Name</description>
    <formula>Connect2_Show__r.Show_Name__c</formula>
    <inlineHelpText>Show Name for Connect2 Show</inlineHelpText>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Status of the Order.  Defaults to &#39;New&#39; and will clearly indicate the status of the order state and what its in.</description>
    <inlineHelpText>Status of the Order.</inlineHelpText>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Attribute__c/GC_Show_Attribute__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Attribute object for use in storing dynamic lookup content for a Show such as Department / Sign Types / Hall Information / Area Information / Sign Sizes and other related content.  Each type of object is defined by RecordType.</description>
    <label>Show Attribute</label>
    <nameField>
        <label>Show Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Show Attributes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/GC_Vendor_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Vendor Order Task Custom Object. This Object is used to identify Vendor Order Task details to be performed in a GES Connect Show.</description>
    <label>Vendor Order Task</label>
    <nameField>
        <displayFormat>VOT-{0000}</displayFormat>
        <label>Vendor Order Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Delivery_Location_Ven__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Location_Ven__c</fullName>
    <label>Delivery Area</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <formula>Order__r.Show_Name__c</formula>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Vendor Order Task.</description>
    <inlineHelpText>Status of the Vendor Order Task.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/GC_Show_Role__c.field-meta.xml
<CustomField>
    <fullName>GC_Show_Role__c</fullName>
    <label>GES Connect Show Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GC Account Manager</fullName>
            </value>
            <value>
                <fullName>GC Creative Director</fullName>
            </value>
            <value>
                <fullName>GC Traffic Administrator</fullName>
            </value>
            <value>
                <fullName>GC Detailer</fullName>
            </value>
            <value>
                <fullName>GC Director of Account Management</fullName>
            </value>
            <value>
                <fullName>GC Sales Manager</fullName>
            </value>
            <value>
                <fullName>GC Graphics Project Manager</fullName>
            </value>
            <value>
                <fullName>GC Community Client</fullName>
            </value>
            <value>
                <fullName>GC Community Vendor</fullName>
            </value>
            <value>
                <fullName>GC Drafter</fullName>
            </value>
            <value>
                <fullName>GC Convention Planning Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LC_OrderViewControllerTest.cls
@isTest
public class LC_OrderViewControllerTest {
    @TestSetup
    public static void testSetup(){
        Opportunity opp=LC_TestUtils.insertOpportunity();
        GC_Connect2_Show__c show=LC_TestUtils.insertShow(opp.Id,opp.Name);
        GC_Order__c order=LC_TestUtils.insertOrder(show.Id);
         GC_Show_Attribute__c venueAttribute=LC_TestUtils.insertVenueAttributes(show.Id);
        GC_Show_Attribute__c deptAttribute=LC_TestUtils.insertDeptAttributes(show.Id);
        GC_Show_Attribute__c serviceAttribute=LC_TestUtils.insertServiceAttributes(show.Id);
        GC_Vendor_Order_Task__c vot=LC_TestUtils.insertVOT(order.Id,serviceAttribute.Id);
        GC_GES_Order_Task__c got=LC_TestUtils.insertGOT(order.Id,venueAttribute.Id,deptAttribute.Id);
    }
    @isTest
    public static void testMethod1() {
        GC_Connect2_Show__c show=[select id from GC_Connect2_Show__c where Show_Name__c = 'test show'];
        GC_Order__c order = [select Id from GC_Order__c where Booth_Area__c='new Booth Area'];
        list<String> orderIds = new list<String>();
        List<string> selectedStatusToPrint=new List<String>();
        orderIds.add(order.Id);
        LC_OrderViewController.getShowNumber(order.Id);
        LC_OrderViewController.getDataToDownlaodAsCSV(orderIds,selectedStatusToPrint,show.Id);
        LC_OrderViewController.showOrHideDeleteButton(order.Id);
        LC_OrderViewController.isCommunity();
        order.Status__c='';
        update order;
        LC_OrderViewController.showOrHideDeleteButton(order.Id); 
        LC_OrderViewController.getVOTStatusOfOrder(order.Id);
        GC_Vendor_Order_Task__c vendorOrderTask=[select Id from GC_Vendor_Order_Task__c where Delivery_Location_Ven__c='votForExistingMethod Location'];
        vendorOrderTask.Status__c='sent';
        update vendorOrderTask;
        LC_OrderViewController.getVOTStatusOfOrder(order.Id);
        order.Status__c='New';
        update order;
        LC_OrderViewController.deleteOrderAction(order.Id);
        order.Status__c='Active';
        update order;
        delete vendorOrderTask;
        LC_OrderViewController.deleteOrderAction(order.Id);
        LC_OrderViewController.getVOTStatusOfOrder(order.Id);
        LC_OrderViewController.initializeDeliveryLocationDetails(order.Id);
        LC_OrderViewController.GetShowID(order.Id);
        
        User accountMgr = GC_TestUtils.createUser('GC Account Manager', 'Test','AC01');
        accountMgr.GC_Show_Role__c='GC Account Manager; GC Creative Director; GC Traffic Administrator; GC Detailer; GC Director of Account Management; GC Sales Manager; GC Graphics Project Manager; GC Community Client; GC Community Vendor';
        update accountMgr;
        
        system.runAs(accountMgr){
            LC_OrderViewController.getProfileName();
        }
    }
    public static void testMethod2() {
        GC_Order__c order = [select Id from GC_Order__c where Booth_Area__c='new Booth Area'];
        LC_OrderViewController.GetShowID(order.Id);
 		LC_OrderViewController.isCommunity();       
    }
}