unpackaged/main/default/objects/Booth_Area__c/Booth_Area__c.object-meta.xml
<CustomObject>
    <label>Booth Area</label>
    <nameField>
        <label>Booth Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booth Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Booth_Area__c/fields/Delivery_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_time__c</fullName>
    <label>Delivery Date/time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</inlineHelpText>
    <label>Installation/Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Formula to Show Name</description>
    <formula>Order__r.Show_Name__c</formula>
    <inlineHelpText>Show Name</inlineHelpText>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area__c</fullName>
    <description>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</description>
    <inlineHelpText>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</inlineHelpText>
    <label>Delivery Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>Delivery Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Delivery Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Order_Area_Description__c.field-meta.xml
<CustomField>
    <fullName>Order_Area_Description__c</fullName>
    <description>Additonal Description for the Order.</description>
    <inlineHelpText>Additonal Description for the Order.</inlineHelpText>
    <label>Area Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Formula to Connect2 Show&#39;s Show Name</description>
    <formula>Connect2_Show__r.Show_Name__c</formula>
    <inlineHelpText>Show Name for Connect2 Show</inlineHelpText>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Attribute__c/GC_Show_Attribute__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Attribute object for use in storing dynamic lookup content for a Show such as Department / Sign Types / Hall Information / Area Information / Sign Sizes and other related content.  Each type of object is defined by RecordType.</description>
    <label>Show Attribute</label>
    <nameField>
        <label>Show Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Show Attributes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Attribute__c/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <description>Department Lookup Value</description>
    <label>Department</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/LC_showOnTheGoTest.cls
@isTest
public class LC_showOnTheGoTest {
    @testsetup
    public static void testSetup(){
        Opportunity opp=LC_TestUtils.insertOpportunity();
        GC_Connect2_Show__c show=LC_TestUtils.insertShow(opp.Id,opp.Name);
        GC_Order__c order=LC_TestUtils.insertOrder(show.Id);
        GC_Show_Attribute__c venueAttribute=LC_TestUtils.insertVenueAttributes(show.Id);
        GC_Show_Attribute__c deptAttribute=LC_TestUtils.insertDeptAttributes(show.Id);
        GC_GES_Order_Task__c gesOt=LC_TestUtils.insertGOT(order.Id,venueAttribute.Id,deptAttribute.Id);
    }
    @isTest
    public static void testMethod1() {
        List<GC_Order__c> orders=[select Id,Name,Booth_Area__c,Order_Area_Description__c,Delivery_Date_Time__c from GC_Order__c where Booth_Area__c='new Booth Area'];
        GC_Connect2_Show__c show=[select id from GC_Connect2_Show__c where Show_Name__c = 'test show'];
        List<GC_Order__c> ordersList= new List<GC_Order__c>();
        List<string> orderIdsToExportAsCsv=new List<String>();
        List<string> selectedStatusToPrint=new List<String>();
        selectedStatusToPrint.add('New');
        selectedStatusToPrint.add('Active');
        selectedStatusToPrint.add('Approved');
        selectedStatusToPrint.add('Submitted');
        LC_showOnTheGo.generatePDFApex(ordersList,selectedStatusToPrint,true,true,false);
        for(GC_Order__c o:orders){
            ordersList.add(o);
            orderIdsToExportAsCsv.add(o.Id);
        }
        List<string> users=new List<string>();
        users.add('');
        List<string> onsitePerson=new List<string>();
        onsitePerson.add('');
        List<string> onsitePersonOther=new List<string>();
        onsitePersonOther.add('');
        selectedStatusToPrint.add('New');
        LC_showOnTheGo.generatePDFApex(ordersList,selectedStatusToPrint,true,true,false);
        LC_showOnTheGo.exportOrdersCSV(orderIdsToExportAsCsv,selectedStatusToPrint,show.Id);
        LC_showOnTheGo.generateOrdersCSV(ordersList,selectedStatusToPrint,show.Id);
        
        LC_showOnTheGo.generatePDFApex(ordersList,selectedStatusToPrint,true,true,true);
        LC_showOnTheGo.getPicklistValues(show.Id);
        LC_showOnTheGo.fetchTableData(show.Id);
        LC_showOnTheGo.getTableValue(show.Id,'new Booth Area','new order area',users,'new',system.today().addDays(10),system.today().addDays(5),system.today().addDays(15),system.today().addDays(3),system.today().addDays(6),system.today().addDays(3),system.today().addDays(3),'Shubhashree Joshi','Test Department attribut1','new Booth Area','Test Venue attribut1',onsitePerson,onsitePersonOther,selectedStatusToPrint);
        LC_showOnTheGo.isCommunity();
        LC_showOnTheGo.escapeSpecialCharacters('Test Department attribut1');
    }
       
    
}