unpackaged/main/default/objects/Booth_Area__c/Booth_Area__c.object-meta.xml
<CustomObject>
    <label>Booth Area</label>
    <nameField>
        <label>Booth Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booth Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <displayFormat>Discount-{0000}</displayFormat>
        <label>Discounts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Discount__c/fields/Booth_Area__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booth Area</label>
    <referenceTo>Booth_Area__c</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Discount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount %</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/RedirectToDiscountEditPage.cls
public class RedirectToDiscountEditPage {
    public PageReference result{set;get;}
    public  RedirectToDiscountEditPage(ApexPages.StandardController controller){
        result=new PageReference('/apex/NewDiscountFromBoothArea');
        String discountId=controller.getId();
        List<Discount__c> gc=[select Booth_Area__r.Id from Discount__c where id =: controller.getId() limit 1];
        result.getParameters().put('Id',gc.get(0).Booth_Area__c);
        result.getParameters().put('discountId', discountId);
        result.setRedirect(true);
    }
    public PageReference navigate(){
        return result;
    }
}