unpackaged/main/default/objects/Booth_Area__c/Booth_Area__c.object-meta.xml
<CustomObject>
    <label>Booth Area</label>
    <nameField>
        <label>Booth Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booth Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Booth_Area__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Booth Areas</relationshipLabel>
    <relationshipName>Booth_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Booth_Area__c/fields/Delivery_Location__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Location__c</fullName>
    <label>Delivery Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Core_Interface_Log__c/GC_Core_Interface_Log__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) A log item that is generated everytime a call is made into the COREInterface class</description>
    <label>GC Core Interface Log</label>
    <nameField>
        <displayFormat>CORELOG-{0000000000}</displayFormat>
        <label>GC Core Interface Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GC Core Interface Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Core_Interface_Log__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the order which this log belongs to.</description>
    <inlineHelpText>Lookup to the order which this log belongs to.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipLabel>GC Core Interface Logs</relationshipLabel>
    <relationshipName>GC_Core_Interface_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Delivery_Location__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Location__c</fullName>
    <description>Deliver To Location</description>
    <inlineHelpText>Deliver To Location</inlineHelpText>
    <label>Delivery Area</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Department for Order.</description>
    <inlineHelpText>Department for Order.</inlineHelpText>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GC_Show_Attribute__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GC_Show_Attribute__c</referenceTo>
    <relationshipName>GES_Orders28</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>GES Connect Order Object.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <description>Order Number in which this line item belongs to from the external system.  Populated when the order has been submitted.</description>
    <inlineHelpText>Order Number in which this line item belongs to from the external system.</inlineHelpText>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area__c</fullName>
    <description>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</description>
    <inlineHelpText>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</inlineHelpText>
    <label>Delivery Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Order_Area_Description__c.field-meta.xml
<CustomField>
    <fullName>Order_Area_Description__c</fullName>
    <description>Additonal Description for the Order.</description>
    <inlineHelpText>Additonal Description for the Order.</inlineHelpText>
    <label>Area Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <description>Order Number used from the External System.  When this is filled out, the External CORE instance knows about the order and has a direct link of this order.  Field is read only on the page layouts and system but can be used for display purposes.</description>
    <inlineHelpText>Order Number used from the External System.</inlineHelpText>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Attribute__c/GC_Show_Attribute__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Attribute object for use in storing dynamic lookup content for a Show such as Department / Sign Types / Hall Information / Area Information / Sign Sizes and other related content.  Each type of object is defined by RecordType.</description>
    <label>Show Attribute</label>
    <nameField>
        <label>Show Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Show Attributes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Attribute__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Attributes</relationshipLabel>
    <relationshipName>Show_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Attribute__c/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <description>Department Lookup Value</description>
    <label>Department</label>
</RecordType>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/GC_Vendor_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Vendor Order Task Custom Object. This Object is used to identify Vendor Order Task details to be performed in a GES Connect Show.</description>
    <label>Vendor Order Task</label>
    <nameField>
        <displayFormat>VOT-{0000}</displayFormat>
        <label>Vendor Order Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the GES Order associated with this vendor order task.</description>
    <inlineHelpText>Lookup to the GES Order associated with this vendor order task.</inlineHelpText>
    <label>Delivery Location</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipLabel>Vendor Order Tasks</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Vendor Community user.</description>
    <inlineHelpText>Lookup to the Vendor Community user to get notified of this task.</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendor_Order_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/GC_ShowOnTheGoHolderControllerTest.cls
/**
* @author Ethos Solutions - www.ethos.com
* @description Test code for the Show On The Go Holder controller
* 2016-04-13 : Original Version
**/
@isTest
public class GC_ShowOnTheGoHolderControllerTest {
    
    public static testMethod void selectTasks() {
        
        GC_Connect2_Show__c show = GC_TestUtils.getTestConnect2Show();
        
        //GC_Order__c order = new GC_Order__c();
        //order.Connect2_Show__c = show.Id;
        //insert order;
        
        User usr = [SELECT Id, Name FROM User WHERE Id = :userinfo.getUserId() LIMIT 1];
        
        GC_Order__c order = new GC_Order__c();
        order.Connect2_Show__c = show.Id;
        order.Order_Area_Description__c = 'testing';
        order.Booth_Area__c='Bangalore';
        insert order;
        
        GC_Show_Attribute__c GCshow=new GC_Show_Attribute__c();
        GCshow.Connect2_Show__c =show.Id;
        GCshow.name='test';
        insert GCshow;
        
        GC_GES_Order_Task__c got = new GC_GES_Order_Task__c();
        got.Order__c = order.Id;
        got.Delivery_Location__c = 'testing';
        got.Department__c=GCshow.id;
        insert got;
        
        GC_Vendor_Order_Task__c vot = new GC_Vendor_Order_Task__c();
        vot.Order__c = order.Id;
        vot.Vendor__c=usr.Id;
        insert vot ;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(show);
        ApexPages.currentPage().getParameters().put('initialOrderByQuery' , 'Order_Number__c');
        
        GC_OrderHolder orderHolder = new GC_OrderHolder(order);
        orderHolder.selected = true;
        List<GC_OrderHolder> holderList = new List<GC_OrderHolder>();
        holderList.add(orderHolder);
        
        GC_ShowOnTheGoHolderController cont = new GC_ShowOnTheGoHolderController(sc);
        cont.orderHolders = holderList;
        cont.signOrderOpt='false';
        cont.workOrderOpt='false';
        cont.pdfByLocation = true;
        PageReference pr;
        pr = cont.itemsSelected();
        GC_Core_Interface_Log__c ilog = [select Id, Name from GC_Core_Interface_Log__c];
        //System.assertEquals(pr.getUrl() , ('/apex/GC_ShowOnTheGoPDF?urlParamsId=' + ilog.Id+'&signOrderOpt='+cont.signOrderOpt+'&workOrderOpt='+cont.workOrderOpt));
        //System.assertEquals(pr.getUrl() , ('/apex/GC_ShowOnTheGoPDF?urlParamsId=' + ilog.Id));
        
        cont.Username=new List<String>();
        cont.searchString = 'test';
        
        cont.getDateString(Date.today());
        cont.modifiedDateFrom = (Date.today());
        cont.modifiedDateTo = (Date.today());
        cont.createdDateFrom = (Date.today());
        cont.createdDateTo = (Date.today());
        cont.showDateDelivery = (Date.today());
        cont.showDateRemoval = (Date.today());
        cont.showDateCompletion = (Date.today()); 
        cont.onsiteContactPerson = new List<String>();
        cont.onsiteContactPersonOther = new List<String>();
        cont.searchString = 'test';
        cont.deliveryLocation = 'US';
        cont.department ='Graphics';
        cont.searchResults();
        cont.Username.add('Rahul Sinha');
        cont.SavePDFFilter();
        cont.resetSearch();
        cont.itemsSelectedtoExportCSV();
        cont.performSort();
        List<String> st = new  List<String>();
        st.add('element');
        cont.filterString(st);
    }
}