unpackaged/main/default/objects/Booth_Area__c/Booth_Area__c.object-meta.xml
<CustomObject>
    <label>Booth Area</label>
    <nameField>
        <label>Booth Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booth Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Booth_Area__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Booth Areas</relationshipLabel>
    <relationshipName>Booth_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <displayFormat>Discount-{0000}</displayFormat>
        <label>Discounts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Discount__c/fields/Booth_Area__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booth Area</label>
    <referenceTo>Booth_Area__c</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Discount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount %</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/Redirect_Test.cls
@isTest
public class Redirect_Test {
    public static testMethod void testMethod1() {
        GC_Connect2_Show__c connect2 = GC_TestUtils.getTestConnect2Show();
         Discount__c disc = GC_TestUtils.getTestDiscount();
        insert disc;
        Booth_Area__c ba = [select Connect2_Show__c from Booth_Area__c where id=: disc.Booth_Area__c limit 1];
        ba.Connect2_Show__c = connect2.Id;
        update ba;
        ApexPages.StandardController dc = new ApexPages.StandardController(ba);
        Test.startTest(); 
        ApexPages.currentPage().getParameters().put('Id',disc.Booth_Area__c);
        Redirect discount = new Redirect(dc);
        Test.stopTest(); 
    }
}