unpackaged/main/default/objects/Booth_Area__c/Booth_Area__c.object-meta.xml
<CustomObject>
    <label>Booth Area</label>
    <nameField>
        <label>Booth Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booth Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Booth_Area__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Booth Areas</relationshipLabel>
    <relationshipName>Booth_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Booth_Area__c/fields/Delivery_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_time__c</fullName>
    <label>Delivery Date/time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</inlineHelpText>
    <label>Installation/Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of Item from the External System.</description>
    <inlineHelpText>Description of Item from the External System.</inlineHelpText>
    <label>Item Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <description>Item Number defined by the product selection picklist.</description>
    <inlineHelpText>Item Number defined by the product selection picklist.</inlineHelpText>
    <label>Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>GES Connect Order Object.</inlineHelpText>
    <label>Order</label>
    <referenceTo>GC_Order__c</referenceTo>
    <relationshipName>GES_Order_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Item Price / Unit from the External System.  Populated on item selection.</description>
    <inlineHelpText>Item Price / Unit from the External System.  Populated on item selection.</inlineHelpText>
    <label>Price</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/QuantityNum__c.field-meta.xml
<CustomField>
    <fullName>QuantityNum__c</fullName>
    <description>Number of Units to Order</description>
    <inlineHelpText>Number of Units to Order</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that display&#39;s different status values</description>
    <inlineHelpText>Status of GES Order Task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Graphics Requested</fullName>
            </value>
            <value>
                <fullName>Graphics Submitted</fullName>
            </value>
            <value>
                <fullName>Graphics Rejected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Submitted to Graphics</fullName>
            </value>
            <value>
                <fullName>Submitted For AM Review</fullName>
            </value>
            <value>
                <fullName>Pending AM Review</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <description>Total price (quantity * unit price)</description>
    <formula>VALUE(Price__c)  *  QuantityNum__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total price (quantity * unit price)</inlineHelpText>
    <label>Total $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <description>Units identified by the Order Item.</description>
    <inlineHelpText>Units identified by the Order Item.</inlineHelpText>
    <label>Units</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <formula>CreatedBy.FirstName +&#39; &#39;+ CreatedBy.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area__c</fullName>
    <description>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</description>
    <inlineHelpText>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</inlineHelpText>
    <label>Delivery Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>Delivery Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Delivery Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Status of the Order.  Defaults to &#39;New&#39; and will clearly indicate the status of the order state and what its in.</description>
    <inlineHelpText>Status of the Order.</inlineHelpText>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GC_OrderTaskMove_Controller.cls
public with sharing class GC_OrderTaskMove_Controller {
    
    public String sortOrder {get; set;}
    public String orderByQuery {get; set;}
    public string str {get;set;}
    public string str1 {get;set;}
    public Boolean isDisplayed {get; set;}
    public Boolean showContent {get; set;}
    public Boolean showContent1 {get; set;}
    public Boolean display {get; set;}
    public Boolean display1 {get; set;}
    public List<SelectOption> opt {get;set;}
    public List<wrapOrdTask> ordTaskList {get; set;}
    public List<GC_GES_Order_Task__c> selectedOrdTasks{get;set;}
    public List<GC_GES_Order_Task__c> gotMov{get;set;}
    public List<SelectOption> optns {get;set;}
    public set<Id> TaskId {get;set;}
    public String Connect2ShowId {get; set;}

     public GC_OrderTaskMove_Controller(ApexPages.StandardController sc)
     {
         str='';
         str1='';
         showContent = false;
         showContent1 = true;
         display = false;
         display1 = true;
         String orderId = ApexPages.currentPage().getParameters().get('OrderId');
         String showId = ApexPages.currentPage().getParameters().get('showId');
        if(ordTaskList == null) {
            ordTaskList = new List<wrapOrdTask>();
            for(GC_GES_Order_Task__c got : [select Id,Name,Description__c,Total__c,Item_Number__c,Price__c,QuantityNum__c,UOM__c,Order__r.Connect2_Show__c from GC_GES_Order_Task__c where order__c=:orderId and (Status__c='New' or Status__c='Submitted' or Status__c='Approved')]) 
            {
                ordTaskList.add(new wrapOrdTask(got));
                Connect2ShowId = got.Order__r.Connect2_Show__c;
            }
        }
        
        opt = new List<Selectoption>();
                List<GC_Order__C> existingOrder =[select Id,name,status__c,Delivery_Date_Time__c,Booth_Area__c,User_Name__c,
                                                  Connect2_Show__c  from GC_Order__C where Connect2_Show__c =:showId  order by Name ASC];
    
        for(GC_Order__C ordr : existingOrder){
            str1 = ordr.Name+'|'+ordr.Booth_Area__c+'|'+ordr.Delivery_Date_Time__c+'|'+ordr.status__c+'|'+ordr.User_Name__c;
            opt.add(new selectOption(ordr.Id, str1));
        }  
    }


         public class wrapOrdTask
         {
            public GC_GES_Order_Task__c ordtask {get; set;}
            public Boolean selected {get; set;}
 
            public wrapOrdTask(GC_GES_Order_Task__c g) {
                ordtask = g;
                selected = false;
            }
         }
        
         public String selectedshow{get;set;}  // This will hold the show name, the id in here
         public String selectedOrder{get;set;}// This will hold the order name, the id in here
         
          
        public PageReference cancelclone() 
        {
            //string showId = ApexPages.currentPage().getParameters().get('showId');
            string orderId = ApexPages.currentPage().getParameters().get('orderId');
            string isCommunity = ApexPages.currentPage().getParameters().get('isCommunity');
            if(isCommunity == 'true')
            {
              return new PageReference(GC_PageUtil.CheckApexDomain() + '/GC_Community_OrderView?orderId=' + orderId +'&showId='+Connect2ShowId);
            }
            else
            {
              return new PageReference(GC_PageUtil.CheckApexDomain() + '/GC_OrderView?id=' + orderId +'&sfdc.override=1');
            }
            
        }
    
        public PageReference moveOrdTasks()
        {
            selectedOrdTasks = New List<GC_GES_Order_Task__c>();
            TaskId = New set<Id>();
            List<GC_GES_Order_Task__c> ordTasksToBeMoved = New List<GC_GES_Order_Task__c>();
            for(wrapOrdTask Task : ordTaskList){
                if(Task.selected==True){
                    selectedOrdTasks.add(Task.ordtask);
                }
            }
            
            for(GC_GES_Order_Task__c ordtsk: selectedOrdTasks){
                TaskId.add(ordtsk.Id);
            }
            
            if(String.isBlank(selectedOrder))
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR , 'You must select an Order'));
                return null;
            }

            if (TaskId.size() == 0) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR , 'You must select at least one Order Task'));
                return null;
            }

            gotMov = [select id,order__c from GC_GES_Order_Task__c where Id in : TaskId];
            
            for(GC_GES_Order_Task__c movGot : gotMov)
            { 
                movGot.order__c = selectedOrder; 
                ordTasksToBeMoved.add(movGot);
            }
            
            update ordTasksToBeMoved;

            if (String.isNotBlank(selectedOrder)) 
            {
                return new PageReference(GC_PageUtil.CheckApexDomain() + '/GC_OrderView?id='+selectedOrder+'&sfdc.override=1');
            }
            else
            {
               return null;
            }
        }
}