unpackaged/main/default/objects/Booth_Area__c/Booth_Area__c.object-meta.xml
<CustomObject>
    <label>Booth Area</label>
    <nameField>
        <label>Booth Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booth Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Booth_Area__c/fields/Completion_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_time__c</fullName>
    <label>Completion Date/time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Booth_Area__c/fields/Delivery_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_time__c</fullName>
    <label>Delivery Date/time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Booth_Area__c/fields/Removal_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_time__c</fullName>
    <label>Removal Date/time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Core_Interface_Log__c/GC_Core_Interface_Log__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) A log item that is generated everytime a call is made into the COREInterface class</description>
    <label>GC Core Interface Log</label>
    <nameField>
        <displayFormat>CORELOG-{0000000000}</displayFormat>
        <label>GC Core Interface Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GC Core Interface Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Core_Interface_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
                <default>true</default>
                <label>Success</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Core_Session__c/GC_Core_Session__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Core Session Object.  This object maintains the session ID per user along with expiration values to determine when it needs to refresh it&#39;s session.</description>
    <label>Core Session</label>
    <nameField>
        <displayFormat>GCS-{0000}</displayFormat>
        <label>Core Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Sessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Core_Session__c/fields/Core_Application_Session_ID__c.field-meta.xml
<CustomField>
    <fullName>Core_Application_Session_ID__c</fullName>
    <label>Core Application Session ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Booth_Area_Discount__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area_Discount__c</fullName>
    <description>Booth Area discount percentage as determined by the Parent Orders booth area.</description>
    <inlineHelpText>Booth Area discount percentage 0-100</inlineHelpText>
    <label>Booth Area Discount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Child_Category__c.field-meta.xml
<CustomField>
    <fullName>Child_Category__c</fullName>
    <label>Child Category</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</inlineHelpText>
    <label>Installation/Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of Item from the External System.</description>
    <inlineHelpText>Description of Item from the External System.</inlineHelpText>
    <label>Item Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Item_Category_ID__c</fullName>
    <description>Item Category Id Used for Item Filters.  Needs to be hidden from page layouts.</description>
    <inlineHelpText>Item Category Id Used for Item Filters.  Needs to be hidden from page layouts.</inlineHelpText>
    <label>Item Category ID (Hidden)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <description>Item Number defined by the product selection picklist.</description>
    <inlineHelpText>Item Number defined by the product selection picklist.</inlineHelpText>
    <label>Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Item_Template__c.field-meta.xml
<CustomField>
    <fullName>Item_Template__c</fullName>
    <description>Determines the list of order options to select for an order task</description>
    <inlineHelpText>Basic, Carpet, Graphics, Custom Carpet, Custom Graphics as determined by selecting the item.</inlineHelpText>
    <label>Item Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Parent_Category__c.field-meta.xml
<CustomField>
    <fullName>Parent_Category__c</fullName>
    <label>Parent Category</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Item Price / Unit from the External System.  Populated on item selection.</description>
    <inlineHelpText>Item Price / Unit from the External System.  Populated on item selection.</inlineHelpText>
    <label>Price</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/QuantityNum__c.field-meta.xml
<CustomField>
    <fullName>QuantityNum__c</fullName>
    <description>Number of Units to Order</description>
    <inlineHelpText>Number of Units to Order</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</inlineHelpText>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that display&#39;s different status values</description>
    <inlineHelpText>Status of GES Order Task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Graphics Requested</fullName>
            </value>
            <value>
                <fullName>Graphics Submitted</fullName>
            </value>
            <value>
                <fullName>Graphics Rejected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Submitted to Graphics</fullName>
            </value>
            <value>
                <fullName>Submitted For AM Review</fullName>
            </value>
            <value>
                <fullName>Pending AM Review</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <description>Units identified by the Order Item.</description>
    <inlineHelpText>Units identified by the Order Item.</inlineHelpText>
    <label>Units</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area__c</fullName>
    <description>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</description>
    <inlineHelpText>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</inlineHelpText>
    <label>Delivery Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area_ID__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area_ID__c</fullName>
    <description>Booth Area ID known by the External System.  Used for mapping the Item Discounts associated with a booth area.</description>
    <inlineHelpText>Booth Area ID known by the External System.  Used for mapping the Item Discounts associated with a booth area.</inlineHelpText>
    <label>Booth Area ID (Hidden)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>Completion Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Completion Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>Delivery Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Delivery Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <description>Removal Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Removal Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Status of the Order.  Defaults to &#39;New&#39; and will clearly indicate the status of the order state and what its in.</description>
    <inlineHelpText>Status of the Order.</inlineHelpText>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GC_CoreQuery.cls
public with sharing class GC_CoreQuery {
    public GC_Order__c order {get; set;}
    public GC_GES_Order_Task__c got {get; set;}
    
    // These are consistent via multiline and booth area changes
    public String coreSessionId { get; set; }
    public String showProjectNumber { get; set; } // CORE uses two numbers for ordering items, showProjectNumber is the salesforce Job number.
    public String showOccrProjectId { get; set; } // This is determined by the salesforce job number above and needs to be queried for.
    public String selectedBooth { get; set; } // Selected Booth ID from Parent Order
    public String selectedBoothName { get; set; } // Selected Booth ID from Parent Order
    public List<SelectOption> boothOptions { get; private set; }
    public Map<String, CORE_V2.BoothArea> boothAreas { get; private set; }
    public List<SelectOption> productCategories { get; private set; }
    public List<SelectOption> childCategories { get; private set; }
    public LargeSelectList productList { get; set; }
    public Map<String, Map<String, List<string>>> products { get; private set; }
    public Map<String, GC_ItemHolder> itemsMap ;
    public Boolean isProjectValid { get; set; }
    public String searchItemClick { get; set; }
    
    // These vary per item, potentially can change based on which task is selected.
    public GC_ItemHolder selectedItem { get; set; } // Wrapper Item to hold the selected Item
    //public List<GC_ItemHolder> currentItems { get; set; } // Wrapper Item to hold the selected Item
    public List<String> currentItems { get; set; } 
    public String selectedCategory { get; set; } // Selected Category for Filters
    public String selectedParentCategory { get; set; } // Selected Category for Filters
    
    public String selectedChildCategory { get; set; } // Selected Category for Filters
    public String selectedItemNumber { get; set; } // Selected Item Number when Selected
    public String selectedItemNumberAndDescription { get; set; } // Selected Item Number when Selected
    public String itemOptionsTemplate { get; set; } // itemOptionsTemplate is used to rerender the options for the particular item, Basic / Graphics / Carpet are the simple options.
    public String selectedImagePath { get; set; } // itemOptionsTemplate is used to rerender the options for the particular item, Basic / Graphics / Carpet are the simple options.
    public Map<string,string> categoryMap { get; set; } 
    public set<string> setItemNumber;
    
    public GC_CoreQuery() {
        SelectOption noneSelectOption = new SelectOption('', '---None---');
        productCategories = new List<SelectOption>();
        productCategories.Add(noneSelectOption);
        
        childCategories = new List<SelectOption>();
        childCategories.Add(noneSelectOption);
        
        productList = new LargeSelectList();
        productList.Add(noneSelectOption);
        
        //selectedParentCategory = '';
        selectedChildCategory = '';
        
        //products = new Map<String, Map<String, List<GC_ItemHolder>>>();
        products = new Map<String, Map<String, List<string>>>();
        boothOptions = new List<SelectOption>();
        boothAreas = new Map<String, CORE_V2.BoothArea>();
        categoryMap  = new Map<String, String>();
    }
    
    public void setCurrentTask(GC_GES_Order_Task__c gesOrderTask) {
        
        system.debug('setCurrentTask=======' + gesOrderTask);
        system.debug('itemsMap=======' + itemsMap);
        
        got = gesOrderTask;
        selectedCategory = String.valueOf(got.Item_Category_ID__c);
        selectedParentCategory= got.Parent_Category__c;
        selectedChildCategory= got.Child_Category__c;
        selectedItemNumber = String.valueOf(got.Item_Number__c);
        selectedItemNumberAndDescription = selectedItemNumber + '_' + String.valueOf(got.Description__c);
        selectCategories();
        itemOptionsTemplate = String.valueOf(got.Item_Template__c);
    }
    
    public class GC_ItemHolder {
        public String Category { get; set; }
        public String CategoryId { get; set; }
        public String ChildCategory { get; set; }
        public String InventoryItemId { get; set; }
        public String ItemNumber { get; set; }
        public String ItemDescription { get; set; }
        public String ItemOptionTemplate { get; set; }
        public String ImageUrl { get; set; }
        public String ItemType { get; set; }
        public String LineOfBusiness { get; set; }
        public String ParentCategory { get; set; }
        public String Price { get; set; }
        public String Units { get; set; }
        public String TaxRate { get; set; }
        public String BoothAreaDiscount { get; set; }
        
        
        public GC_ItemHolder(CORE_V1.ShowOrgProduct orgProduct) {
            InventoryItemId = String.valueOf(orgProduct.InventoryItemId);
            ItemNumber = orgProduct.ItemNumber;
            ItemDescription = orgProduct.ItemDescription;
            ImageUrl = orgProduct.ImageUrl;
            ItemOptionTemplate = orgProduct.ItemOptionTemplate;
            Price = String.valueOf(orgProduct.Price);
            Units = orgProduct.UOM;
            TaxRate = String.valueOf(orgProduct.TaxRate);
            BoothAreaDiscount = String.valueOf(orgproduct.DiscountPercentage);
            
        }
    }
    
    public class GC_ProductMap{
        //public Map<String, Map<String, List<string>>> productMap {get; set;}
        public Map<String, GC_ItemHolder> itemsMap {get; set;}
        //public set<string> setItemNumber {get; set;}
        //public Map<string,string> categoryMap { get; set; }
        //public List<SelectOption> productCategories { get; set; }
        
        public GC_ProductMap(){
            
        }
    }
    
    public PageReference obtainBoothAreas() {
        if (isProjectValid) {
            //if (String.isBlank(coreSessionId)) {
            //    sessionLoad();
            //}
            if (String.isBlank(coreSessionId)) {
                GC_PageUtil.AddErrorMessage('Failed to Obtain the Session Id');
                return null;
            }
            CORE_V2.BasicHttpBinding_IShowService projectQuery = new CORE_V2.BasicHttpBinding_IShowService();
            try {
                CORE_V2.ShowProject showProject;
                if (Test.isRunningTest()) {
                   showProject = GC_TestUtils.getTestShowProject();
                }
                else {
                    showProject = projectQuery.GetShowProjectByProjectNumber(coreSessionId, showProjectNumber);
                }
                boothAreas = getBoothAreaByShowProject(showProject);
                showOccrProjectId = String.valueOf(showProject.showOccrProjectId);
            }
            catch (Exception e) {
                GC_Core_Interface_Log__c logMsg;
                if (order != null && String.isNotBlank(order.Id)) {
                    logMsg = GC_CoreUtils.createNewLog('Obtain Booth Areas', 'Failed to Obtain Booth Areas ' + e.getMessage(), 'Error', order);
                }
                else {
                    logMsg = GC_CoreUtils.createNewLog('Obtain Booth Areas', 'Failed to Obtain Booth Areas ' + e.getMessage(), 'Error');
                }
                insert logMsg;
                GC_PageUtil.AddErrorMessage('Failed to Obtain Booth Areas');
                GC_PageUtil.AddErrorMessage('Response from Web Service: ' + e.getMessage());
            }
            selectedBooth = String.valueof(order.Booth_Area_ID__c);
        }else {
            GC_PageUtil.AddErrorMessage('Job Number is blank, Cannot proceed with obtaining the Booth Areas.');
        }if (order.Status__c == 'Active') {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'The current order can not be changed because it has active tasks'));
        }
        return null;
    }
    
    public PageReference selectBoothArea() {
        if (String.isNotBlank(selectedBooth) && boothAreas != null) {
            CORE_V2.BoothArea boothArea = boothAreas.get(selectedBooth);
            order.Booth_Area__c = String.valueOf(boothArea.Area);
            order.Booth_Area_ID__c = String.valueOf(boothArea.BoothAreaId);
            order.Delivery_Date_Time__c = GC_CoreUtils.ConvertExternalDateTime(boothArea.DeliveryDateTime);
            order.Removal_Date_Time__c = GC_CoreUtils.ConvertExternalDateTime(boothArea.RemovalDateTime);
            order.Completion_Date_Time__c = GC_CoreUtils.ConvertExternalDateTime(boothArea.CompletionDateTime);
            return null;
        }
        return null;
    }
    
    public Map<String, CORE_V2.BoothArea> getBoothAreaByShowProject(CORE_V2.ShowProject showProject) {
        boothOptions.clear();
        Map<String, CORE_V2.BoothArea> boothAreaLookup = new Map<String, CORE_V2.BoothArea>(); // we'll use Area as the Key, this should be filled out
        SelectOption noneSelectOption = new SelectOption('', '---None---');
        boothOptions.Add(noneSelectOption);
        
        for (CORE_V2.BoothArea boothArea : showProject.BoothAreas.BoothArea) {
            boothAreaLookup.put(String.valueOf(boothArea.BoothAreaId), boothArea);
            SelectOption so = new SelectOption(String.valueof(boothArea.BoothAreaId), boothArea.Area);
            boothOptions.Add(so);
        }
        return boothAreaLookup;
    }
    
    public PageReference obtainProducts() {
        if (isProjectValid) {
            GC_Core_Session__c session;
            try {
                session = GC_CoreUtils.getSessionID();
                coreSessionId = session.Core_Application_Session_ID__c;
            }
            catch (Exception e) {
                GC_PageUtil.AddErrorMessage(e.getMessage());
                return null;
            }
            
            if (String.isBlank(selectedBooth)) {
                selectedBooth = String.valueof(order.Booth_Area_ID__c);
                if (String.isBlank(selectedBooth)) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Booth area is required to create the GES order task.'));
                    return null;
                }
            }
            CORE_V2.BasicHttpBinding_IShowService projectQuery = new CORE_V2.BasicHttpBinding_IShowService();
            try {
                CORE_V2.ShowProject showProject;
                if (Test.isRunningTest()) {
                    showProject = GC_TestUtils.getTestShowProject();
                }
                else {
                    showProject = projectQuery.GetShowProjectByProjectNumber(coreSessionId, showProjectNumber);
                }
                showOccrProjectId = String.valueOf(showProject.showOccrProjectId);
            }catch (Exception e) {
                //system.debug(LoggingLevel.ERROR, e.getMessage() + ' ' + e.getStackTraceString());
                GC_PageUtil.AddErrorMessage(e.getMessage());
                return null;
            }
            CORE_V1.BasicHttpBinding_IProductService productService = new CORE_V1.BasicHttpBinding_IProductService();
            try {
                //rk CORE_V1.ArrayOfShowOrgProduct showOrgProducts;
                CORE_V1.ArrayOfShowOrgParentCategory showOrgProducts;
                if (Test.isRunningTest()) {
                    showOrgProducts = GC_TestUtils.getTestShowParentProducts();
                }else {
                    showOrgProducts = productService.GetShowOrgProducts(coreSessionId, Integer.valueOf(showOccrProjectId), Integer.valueOf(selectedBooth));
                }
                    products = getProductMap(showOrgProducts);
                    GC_ProductMap newProductMap= new GC_ProductMap();
                    newProductMap.itemsMap= itemsMap;
            } catch (Exception e) {
                GC_PageUtil.AddErrorMessage(e.getMessage());
                system.debug('error at=='+e.getStackTraceString());
                system.debug('error at=='+e.getMessage());
                return null;
            }
        }
        else {
            GC_PageUtil.AddErrorMessage('Job Number is invalid, Cannot proceed with selecting order items.');
        } 
       
        if (got != null) {
            
            System.debug('inside got 1-----------------'+ got.Parent_Category__c);
            selectedCategory = String.isNotBlank(got.Item_Category_ID__c) ? String.valueOf(got.Item_Category_ID__c): null;
            selectedItemNumber = String.isNotBlank(got.Item_Number__c) ? String.valueOf(got.Item_Number__c) : null;
            selectedItemNumberAndDescription = String.isNotBlank(got.Item_Number__c) ? String.valueOf(got.Item_Number__c) + '_' + String.valueOf(got.Description__c) : null;
            selectedParentCategory=String.isNotBlank(got.Parent_Category__c) ? String.valueOf(got.Parent_Category__c): null;
            selectedChildCategory= String.isNotBlank(got.Child_Category__c) ? String.valueOf(got.Child_Category__c): null;
        }
        try {
            PageReference pr = selectCategories();
            return pr;
        } catch(Exception e) {
            GC_PageUtil.AddErrorMessage('Failed to select category: ' + e.getMessage());
            return null;
        }
    }
    
    public Map<String, Map<String, List<String>>> getProductMap(CORE_V1.ArrayOfShowOrgParentCategory products){
        productCategories.clear();
        categoryMap.clear();
        Map<String, Map<String, List<String>>> productsMap= new Map<String, Map<String, List<String>>>();
        itemsMap = new Map<String, GC_ItemHolder>();
        setItemNumber = new set<string>();
        SelectOption noneSelectOption = new SelectOption('', '---None---');
        productCategories.Add(noneSelectOption);    
        
        if (products.ShowOrgParentCategory != null) {
            for (CORE_V1.ShowOrgParentCategory parentCategory : products.ShowOrgParentCategory ) {
                if(!productsMap.containsKey(parentCategory.Name)){
                    //productsMap.put(parentCategory.Name, new Map<String, List<GC_ItemHolder>>());
                    productsMap.put(parentCategory.Name, new Map<String, List<string>>());
                    SelectOption so = new SelectOption(parentCategory.Name, parentCategory.Name);
                    productCategories.Add(so);
                    categoryMap.put(String.valueof(parentCategory.Name), parentCategory.Name);
                    if(parentCategory.ChildCategories !=null){
                        for(CORE_V1.ShowOrgChildCategory childCategory: parentCategory.ChildCategories.ShowOrgChildCategory){
                            if(!productsMap.get(parentCategory.Name).containsKey(childCategory.Name)){
                                //productsMap.get(parentCategory.Name).put(childCategory.Name, new List<GC_ItemHolder>());
                                productsMap.get(parentCategory.Name).put(childCategory.Name, new List<string>());
                            }
                            if(childCategory.Products!=null){
                                for(CORE_V1.ShowOrgProduct product:childCategory.Products.ShowOrgProduct){
                                    GC_ItemHolder productHolder = new GC_ItemHolder(product);
                                    productHolder.ParentCategory = parentCategory.Name;
                                    productHolder.ChildCategory = childCategory.Name;
                                    //productsMap.get(parentCategory.Name).get(childCategory.Name).add(productHolder);
                                    productsMap.get(parentCategory.Name).get(childCategory.Name).add(String.valueOf(productHolder.ItemNumber + '_' + productHolder.ItemDescription));
                                    itemsMap.put(String.valueOf(productHolder.ItemNumber + '_' + productHolder.ItemDescription), productHolder);
                                    setItemNumber.add(productHolder.ItemNumber); 
                                }
                                        
                            }
                            
                        }
                    }
                }
            }
            if (itemsMap.containsKey(selectedItemNumberAndDescription)) {
                selectedItem = itemsMap.get(selectedItemNumberAndDescription);
                                
                //ADDED BY KN 
                if(got != null){
                    got.Parent_Category__c = String.isBlank(got.Parent_Category__c) ? selectedItem.ParentCategory: String.valueOf(got.Parent_Category__c);
                    got.Child_Category__c = String.isBlank(got.Child_Category__c) ? selectedItem.ChildCategory: String.valueOf(got.Child_Category__c);
                }
            }
        }
        
        else{
            GC_PageUtil.AddErrorMessage('Failed to return any products for the booth area.  Can not proceed with Ordering items.');
        }
        return productsMap;
    }
    
      public List<String> getProductList() {
        if (String.isNotBlank(selectedParentCategory)) {
            return products.get(selectedParentCategory).get(selectedChildCategory);
        }
        return null;
    }
    
    public List<GC_ItemHolder> getProductSelected() {
        if (selectedItem != null) {
            List<GC_ItemHolder> retList = new List<GC_ItemHolder>();
            retList.add(selectedItem);
            return retList;
        }
        return null;
    }
    
    public PageReference selectCategories() {
        searchItemClick = '';
         productList.clear();
        if (String.isNotBlank(selectedParentCategory)) {
            childCategories.clear();
            SelectOption noneOption = new SelectOption('' , '--None--');
            childCategories.add(noneOption);
            
            if (products != null && products.containsKey(selectedParentCategory)) {
                //system.debug('key set-----------'+products.get(selectedParentCategory).keySet());
                for (String childCat : products.get(selectedParentCategory).keySet()) {
                    String displayValue = childCat;
                    String uniqueValue = childCat;
                    //system.debug('childCat=='+childCat);
                    SelectOption so = new SelectOption(childCat, childCat);
                    childCategories.add(so);
                }
            }
            itemOptionsTemplate = '';
        }
       selectChildCategories();
        return null;
    }
    
    public PageReference selectChildCategories() {
        searchItemClick = '';
        if (String.isNotBlank(selectedParentCategory) && String.isNotBlank(selectedChildCategory)) {
            productList.clear();
            SelectOption noneOption = new SelectOption('' , '--None--');
            productList.add(noneOption);
            
            if (products != null && products.containsKey(selectedParentCategory)) {
                if(products.get(selectedParentCategory).containsKey(selectedChildCategory)){
                selectedCategory = products.get(selectedParentCategory).get(selectedChildCategory)[0].substringBefore('_');
                    for (String item : products.get(selectedParentCategory).get(selectedChildCategory)) {
                        SelectOption so = new SelectOption(item, item);
                        productList.add(so);
                    }
                }
            }
            
            itemOptionsTemplate = '';
        }
        system.debug('selectedItem==='+selectedItem);
        return null;
    }
    
    public PageReference selectItem() {
        try {
            if(searchItemClick == 'searchItemHidden'){
                if (itemsMap.containsKey(selectedItemNumberAndDescription)) {
                    selectedItem = itemsMap.get(selectedItemNumberAndDescription);
                    got.Booth_Area_Discount__c =  Decimal.valueOf(selectedItem.BoothAreaDiscount);
                    if (got.Item_Template__c != selectedItem.ItemOptionTemplate) {
                        got.QuantityNum__c = null;
                    }
                    got.Item_Template__c = selectedItem.ItemOptionTemplate;
                    got.Item_Number__c = selectedItem.ItemNumber;
                    got.Price__c = selectedItem.Price;
                    got.UOM__c = selectedItem.Units;
                    //-----SY chang to SF
                    if((selectedParentCategory =='Carpet'||got.Item_Template__c == 'Carpet') && (got.UOM__c == 'SY')){
                            got.UOM__c ='SF';
                        }
                    got.Description__c = selectedItem.ItemDescription;
                    got.Item_Category_ID__c = selectedItem.CategoryId;
                    itemOptionsTemplate = got.Item_Template__c;
                    selectedImagePath = selectedItem.ImageUrl;
                    selectedCategory = selectedItem.CategoryId;
                    selectedParentCategory =  selectedItem.ParentCategory;
                    selectedChildCategory = selectedItem.ChildCategory;
                    got.Parent_Category__c= selectedItem.ParentCategory;
                    got.Child_Category__c= selectedItem.ChildCategory;
                } else {
                    selectedItem = null;
                    selectedImagePath = null;
                }
            }
            else
            {
            system.debug('inside second else searchItemClick==='+searchItemClick);

                if (products != null && products.containsKey(selectedParentCategory)) {
                    //Map<String, List<GC_ItemHolder>> productMap = products.get(selectedParentCategory);
                    Map<String, List<String>> productMap = products.get(selectedParentCategory);
                    if (productMap.containsKey(selectedChildCategory)) {
                        currentItems = productMap.get(selectedChildCategory);
                        for(String holder:products.get(selectedParentCategory).get(selectedChildCategory) ){
                            if(selectedItemNumberAndDescription == holder){
                                selectedItem= itemsMap.get(holder);
                            }
                            
                        }
                        got.Booth_Area_Discount__c =  Decimal.valueOf(selectedItem.BoothAreaDiscount);
                        if (got.Item_Template__c != selectedItem.ItemOptionTemplate) {
                            got.QuantityNum__c = null;
                        }
                        got.Item_Template__c = selectedItem.ItemOptionTemplate;
                        //system.debug('selectedItem==='+selectedItem);
                        got.Item_Number__c = selectedItem.ItemNumber;
                        got.Price__c = selectedItem.Price;
                        got.UOM__c = selectedItem.Units;
                        if((selectedParentCategory =='Carpet'||got.Item_Template__c == 'Carpet') && (got.UOM__c == 'SY')){
                            got.UOM__c ='SF';
                        }
                        got.Description__c = selectedItem.ItemDescription;
                        got.Item_Category_ID__c = selectedItem.CategoryId;
                        itemOptionsTemplate = got.Item_Template__c;
                        selectedImagePath = selectedItem.ImageUrl;
                        got.Parent_Category__c= selectedItem.ParentCategory;
                        got.Child_Category__c= selectedItem.ChildCategory;
                    } else {
                        selectedItem = null;
                        selectedImagePath = null;
                    }
                }
                else 
                {
                    selectedItem = null;
                    selectedImagePath = null;
                }
            }
        //system.debug('selectedChildCategory==='+selectedChildCategory );
        }
        catch (Exception e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, '' + got));
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, e.getMessage()));
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, e.getStackTraceString()));
        }
        selectCategories();
        return null;
    }
    public void populateProductList() {
        selectedCategory = '';
        productList.clear();
        
        SelectOption so1 = new SelectOption(' ', '--None--');
        productList.add(so1);
        for (GC_ItemHolder item : itemsMap.values()) {
            String displayValue = item.ItemNumber + ' ' + item.ItemDescription;
            String uniqueValue = item.ItemNumber + '_' + item.ItemDescription;
            
            SelectOption so = new SelectOption(uniqueValue, displayValue);
            productList.add(so);
            
        }
    }
   
    public void emptyProductList() {
        productList.clear();
        SelectOption so1 = new SelectOption(' ', '--None--');
        productList.add(so1);
    }
}