unpackaged/main/default/objects/Booth_Area__c/Booth_Area__c.object-meta.xml
<CustomObject>
    <label>Booth Area</label>
    <nameField>
        <label>Booth Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booth Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Booth_Area__c/fields/Completion_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_time__c</fullName>
    <label>Completion Date/time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Booth_Area__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Booth Areas</relationshipLabel>
    <relationshipName>Booth_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Booth_Area__c/fields/Delivery_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_time__c</fullName>
    <label>Delivery Date/time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Booth_Area__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Booth_Area__c/fields/Removal_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_time__c</fullName>
    <label>Removal Date/time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Displays show name</description>
    <label>Show Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Completion Date/Time</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Delivery Date/Time</inlineHelpText>
    <label>Installation/Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <formula>Order__r.Connect2_Show__r.Job_Number__c</formula>
    <label>Job Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <description>Order Number in which this line item belongs to from the external system.  Populated when the order has been submitted.</description>
    <inlineHelpText>Order Number in which this line item belongs to from the external system.</inlineHelpText>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <description>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</description>
    <inlineHelpText>If Set, will use this time instead of the Default Order&#39;s Removal Date/Time</inlineHelpText>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Formula to Show Name</description>
    <formula>Order__r.Show_Name__c</formula>
    <inlineHelpText>Show Name</inlineHelpText>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Sign_Title__c.field-meta.xml
<CustomField>
    <fullName>Sign_Title__c</fullName>
    <description>Graphics Order Sign Title</description>
    <inlineHelpText>Title to be displayed on the Sign</inlineHelpText>
    <label>Sign Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that display&#39;s different status values</description>
    <inlineHelpText>Status of GES Order Task</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Graphics Requested</fullName>
            </value>
            <value>
                <fullName>Graphics Submitted</fullName>
            </value>
            <value>
                <fullName>Graphics Rejected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Submitted to Graphics</fullName>
            </value>
            <value>
                <fullName>Submitted For AM Review</fullName>
            </value>
            <value>
                <fullName>Pending AM Review</fullName>
            </value>
            <value>
                <fullName>Proof Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Proof Changes Required</fullName>
            </value>
            <value>
                <fullName>Proof Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area__c</fullName>
    <description>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</description>
    <inlineHelpText>Booth Area for the Entire Order.   Booth area affects discounts of items within an order.</inlineHelpText>
    <label>Delivery Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Booth_Area_ID__c.field-meta.xml
<CustomField>
    <fullName>Booth_Area_ID__c</fullName>
    <description>Booth Area ID known by the External System.  Used for mapping the Item Discounts associated with a booth area.</description>
    <inlineHelpText>Booth Area ID known by the External System.  Used for mapping the Item Discounts associated with a booth area.</inlineHelpText>
    <label>Booth Area ID (Hidden)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Completion_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date_Time__c</fullName>
    <description>Completion Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Completion Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Completion Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Show Opportunity this Order is assigned to.</description>
    <inlineHelpText>Parent Show Opportunity this Order is assigned to.</inlineHelpText>
    <label>Project Central Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Time__c</fullName>
    <description>Delivery Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Delivery Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Order_Area_Description__c.field-meta.xml
<CustomField>
    <fullName>Order_Area_Description__c</fullName>
    <description>Additonal Description for the Order.</description>
    <inlineHelpText>Additonal Description for the Order.</inlineHelpText>
    <label>Area Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <description>Order Number used from the External System.  When this is filled out, the External CORE instance knows about the order and has a direct link of this order.  Field is read only on the page layouts and system but can be used for display purposes.</description>
    <inlineHelpText>Order Number used from the External System.</inlineHelpText>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Removal_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Removal_Date_Time__c</fullName>
    <description>Removal Date / Time as Determined by Booth Area.</description>
    <inlineHelpText>Removal Date / Time as Determined by Booth Area.</inlineHelpText>
    <label>Removal Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <description>Formula to Connect2 Show&#39;s Show Name</description>
    <formula>Connect2_Show__r.Show_Name__c</formula>
    <inlineHelpText>Show Name for Connect2 Show</inlineHelpText>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Status of the Order.  Defaults to &#39;New&#39; and will clearly indicate the status of the order state and what its in.</description>
    <inlineHelpText>Status of the Order.</inlineHelpText>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/GC_Vendor_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Vendor Order Task Custom Object. This Object is used to identify Vendor Order Task details to be performed in a GES Connect Show.</description>
    <label>Vendor Order Task</label>
    <nameField>
        <displayFormat>VOT-{0000}</displayFormat>
        <label>Vendor Order Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <formula>Order__r.Show_Name__c</formula>
    <label>Show Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Vendor Order Task.</description>
    <inlineHelpText>Status of the Vendor Order Task.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LC_OrderViewController.cls
/* LC_OrderviewController - Apex Controller for LC_OrderView Lightning Component
* Order object has been Renamed to Delivery Location
* Author(s) - Namratha.P Salesforce Developer - SLK Software
* Date - 31/Dec/2018
* Version(Rev) - 1.00(1)
*/

public with sharing class LC_OrderViewController {
    
    public class applicationException extends Exception {}
    static GC_Order__c currentOrder {get; set;}
    static GC_Core_Session__c sessionObject = new GC_Core_Session__c();
    
    @AuraEnabled 
    public static boolean isCommunity(){
        Id siteId = Site.getSiteId(); // take a look at the apex class Site, you may find more useful method concerning site/community
        if (siteId != null) {
            return true;
        }
        return false;
    }
    
    @AuraEnabled
    public Static String getProfileName(){
        List<Profile> PROFILE = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
        system.debug('profileName  ==='+PROFILE[0].Name);
        List<PermissionSetAssignment> currentUserPerSet =  [SELECT Id, PermissionSet.Name,AssigneeId
                                                            FROM PermissionSetAssignment
                                                            WHERE AssigneeId = :Userinfo.getUserId() 
                                                            AND PermissionSet.Name = 'GC_Director_Of_Account_Management_Connect'];
        
        if(currentUserPerSet != null && currentUserPerSet.size() == 1){
            system.debug('currentUserPerSet =='+currentUserPerSet[0]);
            system.debug('GES Connect - AM, DAM, SM');
            if(PROFILE[0].Name == 'System Administrator'){
                return PROFILE[0].Name;
            }else{
                return 'GES Connect - AM, DAM, SM';
            }
        }
        else{
            return PROFILE[0].Name;
        }
    }
    
    @AuraEnabled // Order object Label has been renamed to GES Delivery Loaction ----NP
    public static GC_Order__c initializeDeliveryLocationDetails(id orderId){
        GC_Order__c deliveryLocation = [SELECT ID,name,Connect2_Show__c ,Connect2_Show__r.Show_Name__c ,Connect2_Show__r.Job_Number__c
                                        ,Order_Number__c ,Status__c ,Order_Area_Description__c ,Booth_Area__c
                                        ,Booth_Area_ID__c ,Delivery_Date_Time__c ,Completion_Date_Time__c
                                        ,Removal_Date_Time__c ,OwnerId ,LastModifiedById ,LastModifiedDate FROM GC_Order__c WHERE ID =: orderId LIMIT 1];
        return deliveryLocation;
    }
    
    @AuraEnabled
    public static Boolean deleteOrderAction(string orderId) {
        GC_Order__c order= new GC_Order__c();
        order=[select Id,Status__c from GC_Order__c where Id=:orderId];
        system.debug('order is'+order);
        List<GC_GES_Order_Task__c> orderTaskToDelete = GC_GESOrderTaskDao.getInstance().getByGesOrderId(orderId);
        system.debug('orderTaskToDelete is'+orderTaskToDelete);
        List<GC_Vendor_Order_Task__c> vendorTaskToDelete = GC_VendorOrderTaskDao.getInstance().getByGesOrderId(orderId);
        system.debug('vendorTaskToDelete is'+vendorTaskToDelete);
        
        try{
             if(Test.isRunningTest())
			{
				throw new applicationException('Sorry! We don\'t do that here!!');
			}
            if (order.Status__c != 'Active') {
                if (vendorTaskToDelete.size() > 0) {
                    delete vendorTaskToDelete;
                }
                if (orderTaskToDelete.size() > 0) {
                    delete orderTaskToDelete;
                }
                delete order;
                return true;
            }
            else{
                system.debug('You have Active task orders, order cannot be deleted.');
                return false;
            }
        }
        catch (Exception e) {
            system.debug(' Failed to Delete the Order: ' + e.getMessage());
            return false;
        }
    }
    
    @AuraEnabled
    public static Boolean showOrHideDeleteButton(string orderId){
        Boolean canDelete;
        GC_Order__c orderDetails=[select Id,OwnerId,Status__c from GC_Order__c where Id=:orderId];
        if((orderDetails.OwnerId == UserInfo.getUserId()) && orderDetails.Status__c != null){
            canDelete=true;
        }
        else{
            canDelete=false;
        }
        return canDelete;
    }
    
    @AUraEnabled
    public static Boolean getVOTStatusOfOrder(string orderId){
        Boolean status=false;
        List<GC_Vendor_Order_Task__c> vendorTasks = GC_VendorOrderTaskDao.getInstance().getByGesOrderId(orderId);
        if(vendorTasks.size() >0){
            for(GC_Vendor_Order_Task__c vot:vendorTasks){
                if(vot.Status__c == 'Sent'){
                    status=true;
                }
                else{
                    status=false;
                }
            }
            return status;
        }
        else{
            return status;
        }
    }
    @AuraEnabled 
    public static Id getShowNumber(string recordId){
        GC_Order__c orderDetails= new GC_Order__c();
        orderDetails=[select Id,Connect2_Show__c from GC_Order__c where Id=:recordId];
        return orderDetails.Connect2_Show__c;
    }
    @AuraEnabled (cacheable=true)
    public static List<string> getDataToDownlaodAsCSV(List<string> orderId,List<String> selectedStatusValues,string showId){
        String signTitel = 'Sign_Title__c';
        String signCopy ='Sign_Copy__c';
        String showManagement = 'Show_Management_Field__c';
        try {
            Set<String> orderSet = new Set<String>(orderId);
            orderSet.addAll(orderId);
            string whereClause='';
            if(selectedStatusValues!=null && selectedStatusValues.size()>0){
                List<String> selectedStatusWithInvertedCommas = new List<String>();
                for(Integer i=0;i<selectedStatusValues.size();i++){
                    string statusValues='\''+selectedStatusValues[i]+'\'';
                    selectedStatusWithInvertedCommas.add(statusValues);
                }
                whereClause += ' Status__c in'+selectedStatusWithInvertedCommas+'';
                  }
            List<GC_GES_Order_Task__c> gots = GC_GESOrderTaskDao.getInstance().getGesOrderTaskOrderByStatus(orderSet,whereClause);
            List<GC_Vendor_Order_Task__c> vots = GC_VendorOrderTaskDao.getInstance().getVendorOrderTaskByStatus(orderSet,whereClause);
            List<String> generatedCSVFile = new List<String>();
            List<GC_OrderCSV__mdt> orderCSVList = new List<GC_OrderCSV__mdt>();
            List<String> allLabels = new List<String>();
                orderCSVList = [Select Field_Label__c, Field_Name__c, Order_No__c, Is_Rich_Text__c from GC_OrderCSV__mdt where Hide_Community__c = false Order By Order_No__c];
            for (GC_OrderCSV__mdt orderCSV : orderCSVList) {
                allLabels.add(orderCSV.Field_Label__c);
            }
            generatedCSVFile.add(String.join(allLabels, ',') + '\n');
                Map<String, String> taskDataMap = new Map<String, String>();
                for (GC_GES_Order_Task__c task : gots) {
                    List<String> taskData = new List<String>();
                    for (GC_OrderCSV__mdt orderCSV : orderCSVList) {
                        String parseStrVal = getFieldData(orderCSV.Field_Name__c, task, orderCSV.Is_Rich_Text__c).replaceAll('<[/a-zAZ0-9]*>', ' ');
                        parseStrVal = parseStrVal.stripHtmlTags();
                        taskData.add(parseStrVal);
                    }
                    taskDataMap.put(task.Name, String.join(taskData, ',') + '\n');
                }
                for (GC_Vendor_Order_Task__c task : vots) {
                    List<String> taskData = new List<String>();
                    for (GC_OrderCSV__mdt orderCSV : orderCSVList) {
                        if (orderCSV.Field_Name__c == 'Revision__c') {
                            task.Revision__c = null;
                        }
                        String parseStrVal = getFieldData(orderCSV.Field_Name__c, task, orderCSV.Is_Rich_Text__c).replaceAll('<[/a-zAZ0-9]*>', ' ');
                        taskData.add(parseStrVal);
                    }
                    taskDataMap.put(task.Name, String.join(taskData, ',') + '\n');
                }
                for (String taskName : taskDataMap.keySet()) {     
                    generatedCSVFile.add(taskDataMap.get(taskName));   
                }
             if(Test.isRunningTest())
			{
				throw new applicationException('Sorry! We don\'t do that here!!');
			}
            return generatedCSVFile;
        } catch (Exception e) {
            system.debug('error'+e.getMessage());
            system.debug('error'+e.getStackTraceString());
            return null;
        }
    }

    public static String getFieldData(String fieldName, sObject task, boolean isRichText) {
        try {
            String[] fnSplit = fieldName.split('\\.');
            if(fieldName == 'Owner.Name')
            {
                String stringValue;
                stringValue = (String) task.getSobject('Owner').get('Name');
                return stringValue;
            }
            if (!fieldName.contains('__r.') && task.get(fieldName) == null) {
                
                return '';
                
            } else if (fieldName.contains('__r.') && fnSplit.size() == 2 && (task.getsObject(fnSplit[0]) == null || task.getsObject(fnSplit[0]).get(fnSplit[1]) == null)) {
                return '';
            } 
            else {
                String stringValue;
                if (fieldName.contains('__r.')) {
                    stringValue = String.valueOf(task.getsObject(fieldName.split('\\.')[0]).get(fieldName.split('\\.')[1]));
                } else {
                    stringValue = String.valueOf(task.get(fieldName));
                }
                if (String.isNotBlank(stringValue) && isRichText) {
                    stringValue = stringValue.stripHtmlTags();
                }
                if (String.isNotBlank(stringValue) && stringValue.contains(',')) {
                    stringValue = stringValue.escapeCsv();
                }
                stringValue = stringValue.stripHtmlTags();
                return stringValue;
            }
        } catch (Exception e) {
            return '';
        }
        
    }
    
    @AuraEnabled // Order object Label has been renamed to GES Delivery Loaction ----NP
    public static ID GetShowID(string recordId){
        GC_Order__c deliveryLocations = [SELECT ID,name,Connect2_Show__c, Order_Number__c FROM GC_Order__c where id =:recordId limit 1]; 
        return deliveryLocations.Connect2_Show__c;
    }
}