unpackaged/main/default/objects/CampaignMember/fields/Booth__c.field-meta.xml
<CustomField>
    <fullName>Booth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booth</label>
    <referenceTo>Oracle_Show_Booth__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Sync_with_Marketo__c.field-meta.xml
<CustomField>
    <fullName>Sync_with_Marketo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be checked if this record is to be synced with Marketo. We have custom workflow that sets this flag automatically upon creation if criteria are met. Historical records will be bulk updated</description>
    <inlineHelpText>Sync with Marketo?</inlineHelpText>
    <label>Sync with Marketo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/Oracle_Show_Booth__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booths from Oracle</description>
    <label>Booth</label>
    <nameField>
        <label>Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booths</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/Sync_with_Marketo__c.field-meta.xml
<CustomField>
    <fullName>Sync_with_Marketo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Added to track whether a booth should be flagged or not</description>
    <label>Sync with Marketo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/Oracle_Show_Booth_Contact__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booth Contacts from Oracle</description>
    <label>Booth Contact</label>
    <nameField>
        <displayFormat>BC-{000000000}</displayFormat>
        <label>Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booth Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship field to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Booth_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/Oracle_Show_Booth__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Show_Booth__c</fullName>
    <description>Master Detail relationship to parent Booth</description>
    <label>Booth</label>
    <referenceTo>Oracle_Show_Booth__c</referenceTo>
    <relationshipLabel>Booth Contacts</relationshipLabel>
    <relationshipName>Booth_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/Sync_with_Marketo__c.field-meta.xml
<CustomField>
    <fullName>Sync_with_Marketo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify booth contacts for marketo</description>
    <label>Sync with Marketo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/updcontactfrombooth.cls
public class updcontactfrombooth{

public updcontactfrombooth(){
}

 @future
    public static void updsyncmarketo(set<id> cmliststr){
      
    
     if(cmliststr.size()>0 ){
     list<CampaignMember>  cmlist2 = new list<CampaignMember>(); 
     cmlist2 = [select Booth__c from CampaignMember where id=:cmliststr];
            set<id> boothlist = new set<id>();
            list<Oracle_Show_Booth_Contact__c> boothcontlist = new list<Oracle_Show_Booth_Contact__c>();
            list<Contact> contactlist = new list<contact>();
            
            for(CampaignMember  cm: cmlist2){
                boothlist.add(cm.Booth__c);
            }
            boothcontlist  = [select id,Contact__c,Contact__r.Sync_with_Marketo__c,Sync_with_Marketo__c from Oracle_Show_Booth_Contact__c where Oracle_Show_Booth__c =: boothlist  ];
            system.debug('boothlist---------------'+boothlist);
            
            list<Oracle_Show_Booth_Contact__c> updboothcontlist = new list<Oracle_Show_Booth_Contact__c>();
           set<id> contactlistsyncids = new set<id>();

            
            for(Oracle_Show_Booth_Contact__c obc: boothcontlist){
                obc.Sync_with_Marketo__c  = true;
                contactlistsyncids.add(obc.Contact__c);
                updboothcontlist.add(obc);
            }
            
            if(updboothcontlist.size()>0){
                update updboothcontlist;
            }
            try{
          if(contactlistsyncids.size() > 0){
     list<contact> contactlistsync  = new list<contact>();
           //contactlistsync = [select Sync_with_Marketo__c from Contact where id=:contactlistsyncids]; 
           contactlistsync = [select Sync_with_Marketo__c, LeadSource from Contact where id=:contactlistsyncids]; 
            
            list<contact> updcontact = new list<contact>();
            for(contact obc: contactlistsync){
                obc.Sync_with_Marketo__c = true; 
                obc.LeadSource = 'Exhibitor List'; // Amarab 04/12/2021 SFDC-163 Default Lead Source Field to Exhibitor List on Contact Object            
                updcontact.add(obc);
            }
            
            if(updcontact.size()>0){
            update updcontact;
            }
         }   
          } catch(exception e){}
        }
    }
 }