unpackaged/main/default/objects/AS_Tile__c/AS_Tile__c.object-meta.xml
<CustomObject>
    <description>This object is to display the tiles on the Start page of lightning At Show</description>
    <label>AS Tile</label>
    <nameField>
        <label>AS Tile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AS Tiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AS_Tile__c/fields/Order_of_Display__c.field-meta.xml
<CustomField>
    <fullName>Order_of_Display__c</fullName>
    <description>the matrix is 3*3 
1 2 3
4 5 6
7 8 9</description>
    <inlineHelpText>the matrix is 3*3 
1 2 3
4 5 6
7 8 9</inlineHelpText>
    <label>Order of Display</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/AS_Tile__c/fields/UniqueId_Number__c.field-meta.xml
<CustomField>
    <fullName>UniqueId_Number__c</fullName>
    <label>UniqueId Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/GC_Connect2_Show__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) object that displays show related information</description>
    <label>Project Central Show</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Connect2 Show Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Central Shows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <description>Displays the job number</description>
    <label>Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/SharePoint_Link__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Link__c</fullName>
    <inlineHelpText>Please enter a valid link to the SharePoint folder for file collaboration</inlineHelpText>
    <label>SharePoint Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_End_Date__c</fullName>
    <label>Show End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Start_Date__c</fullName>
    <label>Show Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/GC_Connect2_Show__c/fields/Sponsorship_Link__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Link__c</fullName>
    <inlineHelpText>Please enter a valid URL for sponsorship</inlineHelpText>
    <label>Sponsorship Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/GC_Show_Team_Member__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Show Team Member Custom Object.  This Object is used to represent a show team to give record level access to GES Connect objects.  This object is a junction object between Opportunity and User and specifies a role within a Show.  Primary maintenance of the show team members are performed by the account manager.</description>
    <label>Show Team Member</label>
    <nameField>
        <displayFormat>STM-{0000}</displayFormat>
        <label>Show Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Show Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Connect2_Show__c.field-meta.xml
<CustomField>
    <fullName>Connect2_Show__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connect2 Show</label>
    <referenceTo>GC_Connect2_Show__c</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Pre_show_Tile_Access__c.field-meta.xml
<CustomField>
    <fullName>Pre_show_Tile_Access__c</fullName>
    <label>Pre-show Tile Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OrdersPreshow</fullName>
            </value>
            <value>
                <fullName>GraphicProofingPreshow</fullName>
            </value>
            <value>
                <fullName>AnalyticsPreshow</fullName>
            </value>
            <value>
                <fullName>FileCollaborationPreshow</fullName>
            </value>
            <value>
                <fullName>SharePoint</fullName>
            </value>
            <value>
                <fullName>Sponsorship</fullName>
            </value>
            <value>
                <fullName>ProofBookPreshow</fullName>
                <isActive>false</isActive>
                <label>ProofBookPreshow</label>
            </value>
            <value>
                <fullName>TasksPreshow</fullName>
                <isActive>false</isActive>
                <label>TasksPreshow</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/Tiles_Access__c.field-meta.xml
<CustomField>
    <fullName>Tiles_Access__c</fullName>
    <description>Select the tiles that you want to give access to this team member</description>
    <inlineHelpText>Select the tiles that you want to give access to this team member</inlineHelpText>
    <label>Tiles Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tasks</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Attendee Management</fullName>
            </value>
            <value>
                <fullName>Analytics</fullName>
            </value>
            <value>
                <fullName>Service Tickets</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>ProofBook</fullName>
            </value>
            <value>
                <fullName>Exhibitors</fullName>
            </value>
            <value>
                <fullName>Accomodation</fullName>
            </value>
            <value>
                <fullName>Graphic Proofing</fullName>
            </value>
            <value>
                <fullName>SharePoint</fullName>
            </value>
            <value>
                <fullName>Sponsorship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GC_Show_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to the salesforce user serving the role on the show team.</description>
    <inlineHelpText>Looks up to the salesforce user serving the role on the show team.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Show Team Members</relationshipLabel>
    <relationshipName>Show_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/LC_PreShowTileControllerTest.cls
@isTest
public class LC_PreShowTileControllerTest {
    @testSetup static void setup(){
        
List<GC_Connect2_Show__c> testShws = new List<GC_Connect2_Show__c>();
        for(Integer i=0;i<2;i++) {
            testShws.add(new GC_Connect2_Show__c(Job_Number__c='Show'+i,Show_Start_Date__c=Date.today(),Show_End_Date__c=Date.today()+3,SharePoint_Link__c='https://www.example.com',Sponsorship_Link__c='https://www.test.com'));
        }
        insert testShws;  
        
        AS_Tile__c tile=new AS_Tile__c(Name='Tasks',Order_of_Display__c=1,UniqueId_Number__c=2);
        insert tile;
        
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Digital Products/IT Admin'].Id,
            LastName = 'last',
            Email = 'test@test.com',
            Username = 'test@test.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        insert u;
        GC_Show_Team_Member__c STM= new GC_Show_Team_Member__c(Tiles_Access__c='Tasks',User__c=u.Id,Connect2_Show__c=testShws[0].Id,Pre_show_Tile_Access__c='OrdersPreshow');
        insert STM;
    }
    @isTest static void testmethod1(){
         test.startTest();
        List<AS_Tile__c> allowedTiles=  LC_PreShowTileController.getTilesForShowTeamMember('Show0');
         test.stopTest();
        
    }
    @isTest static void testmethod2(){
        User u=[select id from user where LastName = 'last' Limit 1];
        System.runAs(u) {
            test.startTest();
            List<AS_Tile__c> allowedTiles=  LC_PreShowTileController.getTilesForShowTeamMember('Show0');
            test.stopTest();
        }
    }

}