unpackaged/main/default/objects/GC_Core_Interface_Log__c/GC_Core_Interface_Log__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) A log item that is generated everytime a call is made into the COREInterface class</description>
    <label>GC Core Interface Log</label>
    <nameField>
        <displayFormat>CORELOG-{0000000000}</displayFormat>
        <label>GC Core Interface Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GC Core Interface Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Core_Interface_Log__c/fields/Message_Content__c.field-meta.xml
<CustomField>
    <fullName>Message_Content__c</fullName>
    <description>The content of the call that is made into the COREInterface class (JSON Serialized)</description>
    <label>Message Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/GC_Core_Interface_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>The method in the COREInterface class that was accessed</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GC_GES_Order_Task__c/GC_GES_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) GES Order Task Custom Object. This Object is used to identify GES Order Task details to be performed in a GES Connect Show for ultimately ordering items in Core.</description>
    <label>GES Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Order__c/GC_Order__c.object-meta.xml
<CustomObject>
    <description>Contains the Custom Object Class that comprises of GES Order Tasks and Vendor Orders.</description>
    <label>GES Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GES Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GC_Vendor_Order_Task__c/GC_Vendor_Order_Task__c.object-meta.xml
<CustomObject>
    <description>GES Connect (GC) Vendor Order Task Custom Object. This Object is used to identify Vendor Order Task details to be performed in a GES Connect Show.</description>
    <label>Vendor Order Task</label>
    <nameField>
        <displayFormat>VOT-{0000}</displayFormat>
        <label>Vendor Order Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/GC_ExportToCSVController.cls
public with sharing class GC_ExportToCSVController {
    public String csvContent {get; set;}
    public List<GC_Vendor_Order_Task__c> vots {get; set;}
    public List<GC_GES_Order_Task__c> gots {get; set;}
    public List<GC_Order__c> orders {get; set;}

    public List<GC_OrderHolder> OrderWrappers {get; set;}
    public GC_ExportToCSVController() {

        try {
            String isCommunity = ApexPages.currentPage().getParameters().get('isCommunity');

            String urlParams = ApexPages.currentPage().getParameters().get('urlParamsId');

            if (String.isNotBlank(urlParams)) {
                GC_Core_Interface_Log__c urlParamsObject = [select Id, Name, Method_Name__c, Message_Content__c from GC_Core_Interface_Log__c where Id = :urlParams];
                System.debug(loggingLevel.Error, '*** urlParamsObject.Method_Name__c: ' + urlParamsObject.Method_Name__c);
                GC_OrderUtils.URLParameters orderParams = (GC_OrderUtils.URLParameters)JSON.deserialize(urlParamsObject.Message_Content__c, GC_OrderUtils.URLParameters.Class);
                String orderIds = String.join(new List<String>(orderParams.orderIds), ',');

                if (String.isNotBlank(orderIds)) {
                    csvContent = GC_PageUtil.exportToCSV(orderIds, isCommunity == 'true');
                }
            } else {
                String orderIds = ApexPages.currentPage().getParameters().get('orderIds');

                if (String.isNotBlank(orderIds)) {
                    csvContent = GC_PageUtil.exportToCSV(orderIds, isCommunity == 'true');
                }
            }


        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, e.getMessage()));
        }
    }
}