unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to contact, filter on the account so we only show related contacts in the search</description>
    <inlineHelpText>Please search for the relevant contact</inlineHelpText>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <infoMessage>Please select the correct contact</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact)</relationshipLabel>
    <relationshipName>OpportunitiesContact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/Oracle_Show_Booth__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booths from Oracle</description>
    <label>Booth</label>
    <nameField>
        <label>Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booths</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/BOOTH_ID__c.field-meta.xml
<CustomField>
    <fullName>BOOTH_ID__c</fullName>
    <description>Unique ID of Oracle Booth record</description>
    <label>BOOTH_ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/CUST_CONT_ID__c.field-meta.xml
<CustomField>
    <fullName>CUST_CONT_ID__c</fullName>
    <label>CUST_CONT_ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/SHOW_OCCR_CUST_ID__c.field-meta.xml
<CustomField>
    <fullName>SHOW_OCCR_CUST_ID__c</fullName>
    <label>Show Occurrence Customer ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/Oracle_Show_Booth_Contact__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booth Contacts from Oracle</description>
    <label>Booth Contact</label>
    <nameField>
        <displayFormat>BC-{000000000}</displayFormat>
        <label>Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booth Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship field to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Booth_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/COUNTRY_CODE__c.field-meta.xml
<CustomField>
    <fullName>COUNTRY_CODE__c</fullName>
    <description>Oracle Booth Contact Phone Country Code</description>
    <label>Country Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/CUST_BOOTH_ID__c.field-meta.xml
<CustomField>
    <fullName>CUST_BOOTH_ID__c</fullName>
    <description>Oracle Customer Booth Id</description>
    <label>CUST_BOOTH_ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/CUST_CONT_ID__c.field-meta.xml
<CustomField>
    <fullName>CUST_CONT_ID__c</fullName>
    <description>Oracle Customer Contact Id</description>
    <label>CUST_CONT_ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/EMAIL__c.field-meta.xml
<CustomField>
    <fullName>EMAIL__c</fullName>
    <description>Oracle Booth Contact Email</description>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/EXTENSION__c.field-meta.xml
<CustomField>
    <fullName>EXTENSION__c</fullName>
    <description>Oracle Booth Contact Phone Extension</description>
    <label>Extension</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/FAX__c.field-meta.xml
<CustomField>
    <fullName>FAX__c</fullName>
    <description>Oracle Booth Contact Fax</description>
    <label>Fax</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/FIRST_NAME__c.field-meta.xml
<CustomField>
    <fullName>FIRST_NAME__c</fullName>
    <description>Oracle Booth Contact First Name</description>
    <label>First Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/LAST_NAME__c.field-meta.xml
<CustomField>
    <fullName>LAST_NAME__c</fullName>
    <description>Oracle Booth Contact Last Name</description>
    <label>Last Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/Oracle_Show_Booth__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Show_Booth__c</fullName>
    <description>Master Detail relationship to parent Booth</description>
    <label>Booth</label>
    <referenceTo>Oracle_Show_Booth__c</referenceTo>
    <relationshipLabel>Booth Contacts</relationshipLabel>
    <relationshipName>Booth_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/PHONE__c.field-meta.xml
<CustomField>
    <fullName>PHONE__c</fullName>
    <description>Oracle Booth Contact Phone</description>
    <label>Phone</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/PRIMARY_FLAG__c.field-meta.xml
<CustomField>
    <fullName>PRIMARY_FLAG__c</fullName>
    <description>Oracle Booth Contact Primary</description>
    <label>Primary Flag</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth_Contact__c/fields/SHOW_OCCR_CUST_ID__c.field-meta.xml
<CustomField>
    <fullName>SHOW_OCCR_CUST_ID__c</fullName>
    <description>Oracle Show Occurrence Customer Id</description>
    <label>SHOW_OCCR_CUST_ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ShowsiteContactSetting__c/ShowsiteContactSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Showsite Contact Setting</label>
</CustomObject>

unpackaged/main/default/objects/ShowsiteContactSetting__c/fields/ApplicationID__c.field-meta.xml
<CustomField>
    <fullName>ApplicationID__c</fullName>
    <label>ApplicationID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ShowsiteContactSetting__c/fields/ApplicationKey__c.field-meta.xml
<CustomField>
    <fullName>ApplicationKey__c</fullName>
    <label>ApplicationKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ShowsiteContactSetting__c/fields/Authentication_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>Authentication_EndPoint__c</fullName>
    <label>Authentication EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ShowsiteContactSetting__c/fields/Client_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>Client_EndPoint__c</fullName>
    <label>Client EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ExhibitorServiceClientTest.cls
/**************************************
Author          : Mohd Sajid
Release         : April 18, 2023
Created         : April 10, 2023
Functionality   : this class covers to ExhibitorServiceClient
Itrack#   		: sfdc-202

Modification History:
Itrack#        Date                Author                         Change  
****************************************************************************

***********************************************************************************/
@isTest
public class ExhibitorServiceClientTest {
    
    @testSetup static void setupTestData() {
        
        ShowsiteContactSetting__c ct = new ShowsiteContactSetting__c();
        ct.Name = 'ContactToCore Webservice Auth';
        ct.ApplicationID__c = 'SalesForce';
        ct.ApplicationKey__c =  '76v.H-_7};9^+4(]J.;3';
        ct.Authentication_EndPoint__c =  'https://qaapi.viad.com/Security/v2/AuthenticationService.svc';
        ct.Client_EndPoint__c =  '';
        ct.EndPoint__c =  'http://qaapi.viad.com/ges/v1/ExhibitorService.svc';
        ct.Password__c =  'coresqr';
        ct.Username__c =  'welcome#123';
        insert ct;
        
    }
	
    public static testMethod void AddShowSiteContactTest() {
		//Contact co = [Select id from Contact limit 1];
        //Oracle_Show_Booth__c bo = [Select id from Oracle_Show_Booth__c limit 1];
        
        Account acc = TestDataUtil.CreateTestFacility(); 
        Account acc1 = TestDataUtil.CreateTestFirm(); 
        Contact co = TestDataUtil.CreateTestContact(acc1.Id);
        Show__c show = TestDataUtil.CreateTestShow(acc1.id);
        Opportunity opp = TestDataUtil.CreateTestSalesRepOpp(acc.Id, acc1.Id, show.Id);
        Test.startTest();
        Oracle_Show_Booth__c bo = TestDataUtil.CreateTestBooth(acc1.Id, opp.id, '1111', show.Id);
        bo.SHOW_OCCR_CUST_ID__c = '232333';
        bo.BOOTH_ID__c = '112221';
        update bo;
        
        Test.setMock(WebServiceMock.class, new ExhibitorServiceClientMockImpl());
        
        Oracle_Show_Booth_Contact__c bc = new Oracle_Show_Booth_Contact__c();
        bc.Contact__c = co.Id;
        bc.Oracle_Show_Booth__c = bo.Id;
        bc.FIRST_NAME__c = 'Abc';
        bc.LAST_NAME__c = 'Test';
        //bc.CUST_CONT_ID__c = '123456';
        bc.SHOW_OCCR_CUST_ID__c = '123456';
        bc.CUST_BOOTH_ID__c = '123456';
        bc.PRIMARY_FLAG__c = 'Y';
        bc.COUNTRY_CODE__c = '1';
        bc.PHONE__c = '5123233333';
        bc.EXTENSION__c = 23444;
        bc.FAX__c = '234323333';
        bc.EMAIL__c = 'tset@test.test';
        insert bc;
        
        ExhibitorServiceClient.submitContactToCore(bc.Id);
        Test.stopTest();
    }
    
    public static testMethod void UpdateShowSiteContactTest() {
		Account acc = TestDataUtil.CreateTestFacility(); 
        Account acc1 = TestDataUtil.CreateTestFirm(); 
        Contact co = TestDataUtil.CreateTestContact(acc1.Id);
        Show__c show = TestDataUtil.CreateTestShow(acc1.id);
        Opportunity opp = TestDataUtil.CreateTestSalesRepOpp(acc.Id, acc1.Id, show.Id);
        Test.startTest();
        Oracle_Show_Booth__c bo = TestDataUtil.CreateTestBooth(acc1.Id, opp.id, '1111', show.Id);
        bo.SHOW_OCCR_CUST_ID__c = '232333';
        bo.BOOTH_ID__c = '112221';
        update bo;
        
        
        Test.setMock(WebServiceMock.class, new ExhibitorServiceClientMockImpl());
        
        Oracle_Show_Booth_Contact__c bc = new Oracle_Show_Booth_Contact__c();
        bc.Contact__c = co.Id;
        bc.Oracle_Show_Booth__c = bo.Id;
        bc.FIRST_NAME__c = 'Abc';
        bc.LAST_NAME__c = 'Test';
        bc.CUST_CONT_ID__c = '123456';
        bc.SHOW_OCCR_CUST_ID__c = '123456';
        bc.CUST_BOOTH_ID__c = '123456';
        bc.PRIMARY_FLAG__c = 'Y';
        bc.COUNTRY_CODE__c = '1';
        bc.PHONE__c = '5123233333';
        bc.EXTENSION__c = 23444;
        bc.FAX__c = '234323333';
        bc.EMAIL__c = 'tset@test.test';
        insert bc;
        
        ExhibitorServiceClient.submitContactToCore(bc.Id);
        Test.stopTest();
        
    }
    
}