unpackaged/main/default/objects/Opportunity/fields/Event_Manager__c.field-meta.xml
<CustomField>
    <fullName>Event_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Event manager responsible for the show</description>
    <inlineHelpText>Please select the Event Manager</inlineHelpText>
    <label>Event Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Please select the Event Manager from the list. They must have an active account in Salesforce.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>UsertoOpportunitiesEventManager</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Venue in which exhibition takes place</inlineHelpText>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Facility type account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Show Occurrences (Private)</relationshipLabel>
    <relationshipName>R00N40000001pjqSEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/GES_Move_In__c.field-meta.xml
<CustomField>
    <fullName>GES_Move_In__c</fullName>
    <inlineHelpText>GES Move in Day 1.</inlineHelpText>
    <label>GES Move-In Date 1</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/GES_Move_Out_Date_1__c.field-meta.xml
<CustomField>
    <fullName>GES_Move_Out_Date_1__c</fullName>
    <inlineHelpText>GES Move-Out Day 1.</inlineHelpText>
    <label>GES Move-Out Date 1</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/RecordType_Name__c.field-meta.xml
<CustomField>
    <fullName>RecordType_Name__c</fullName>
    <formula>$RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RecordType Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary sales person (regardless of user type)</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N40000001qZlCEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Close_Date__c</fullName>
    <inlineHelpText>Date exhibition floor closes; if show close date unknown, select last day of appropriate month</inlineHelpText>
    <label>Exhibition Close Date.</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Exhibition Name (not date/location specific)</inlineHelpText>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Show Occurrences</relationshipLabel>
    <relationshipName>R00N40000001pkbZEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Open_Date__c</fullName>
    <inlineHelpText>Date exhibition floor opens; if show open date unknown, select first day of appropriate month</inlineHelpText>
    <label>Exhibition Open Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SOP_Event_ID__c.field-meta.xml
<CustomField>
    <fullName>SOP_Event_ID__c</fullName>
    <description>Holds EMEA SOP Event ID, only Exhibition</description>
    <inlineHelpText>Please enter the SOP Event ID, this should be a six digit number</inlineHelpText>
    <label>SOP Event ID</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <formula>PricebookEntry.Product2.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProductCode</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/EMEAShowCalendar.cls
public with sharing class EMEAShowCalendar {

    public List<OpportunityWrapper> show {get;set;}
    public string searchQuery{get;set;}
    public string monthValue{get;set;} 

    public Map<String, String> periodsMap = new Map<String, String> {
        'THIS_MONTH' => 'This Month',
        'LAST_MONTH' => 'Last Month',
        'NEXT_MONTH' => 'Next Month',
        'THIS_QUARTER' => 'This Quarter',
        'NEXT_QUARTER' => 'Next Quarter',
        'LAST_QUARTER' => 'Last Quarter',
        'THIS_YEAR' => 'This Year',
        'LAST_YEAR' => 'Last Year',
        'NEXT_YEAR' => 'Next Year'
    };

    public EMEAShowCalendar(ApexPages.StandardSetController controller){
        monthValue = 'THIS_MONTH';
    }

    public void search(){
        string searchQuery=  'SELECT Event_Manager__c, Sop_Event_ID__c, Show_Name__c, Name, Id, Facility__c, AccountId, Show_Open_Date__c, Show_Close_Date__c, Sales_Person__c, GES_Move_In__c, GES_Move_Out_Date_1__c, (SELECT ProductCode__c, Product2.Name FROM OpportunityLineItems) FROM Opportunity';
        searchQuery += ' WHERE RecordType_Name__c = \'EMEA - Exhibition\'' ;
        searchQuery += ' AND Show_Open_Date__c = ' + monthValue;
        searchQuery += ' AND (StageName = \'CR\' OR StageName = \'CV\') ';
        searchQuery += ' ORDER BY Show_Open_Date__c Limit 1000';
        string.escapeSingleQuotes(searchQuery);
        List<Opportunity> showTemp = Database.query(searchQuery);
        
        system.debug('Search Results: ' + showTemp);
        
        show = new List<OpportunityWrapper>();
        for (Opportunity o : showTemp) {
            show.add(new OpportunityWrapper(o));
        }
    }

    public void clear() {
        show.clear();
    }

    public PageReference print() {
        return new PageReference('/apex/EMEA_Show_Calendar_Print?v=' + monthValue + '&l=' + periodsMap.get(monthValue));
    }

    public PageReference excel() {
        return new PageReference('/apex/EMEA_Show_Calendar_Excel?v=' + monthValue + '&l=' + periodsMap.get(monthValue));
    }
    
    public class OpportunityWrapper {
        
        public Opportunity opp { get; set; }
        
        public string products {
            get {
                string prods = '';
                for (OpportunityLineItem oli : opp.OpportunityLineItems) {
                    if (prods != '')
                        prods += ', ';
                    prods += oli.Product2.Name;
                }
                return prods;
            }
        }
        
        public OpportunityWrapper(Opportunity o) {
            opp = o;
        }
        
    }
}