unpackaged/main/default/objects/Opportunity/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Show Job Number.</inlineHelpText>
    <label>Job Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prime_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Prime_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contractor producing the exhibition</inlineHelpText>
    <label>Exhibition Prime Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm, Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Prime Contractor)</relationshipLabel>
    <relationshipName>R00N40000001pjqyEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Production_Location__c.field-meta.xml
<CustomField>
    <fullName>Production_Location__c</fullName>
    <description>As determined by Operations / Exhibitions account management. Any additions or edits also need to be made to the Locations object.</description>
    <inlineHelpText>Operational location producing exhibition</inlineHelpText>
    <label>Production Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120-OnPeak</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix</fullName>
            </value>
            <value>
                <fullName>180 - Registration</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles, CA</fullName>
            </value>
            <value>
                <fullName>230-Intl Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>270- Corporate Events (Marketing Dept only)</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460 - Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470 - Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480- Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Florida</fullName>
            </value>
            <value>
                <fullName>530- New Orleans</fullName>
            </value>
            <value>
                <fullName>610- Portland, Seattle</fullName>
            </value>
            <value>
                <fullName>710- Chicago, Cleveland, Milwaukee, St. Louis</fullName>
            </value>
            <value>
                <fullName>810- New York &amp; Boston</fullName>
            </value>
            <value>
                <fullName>830-DC, Philadelphia</fullName>
            </value>
            <value>
                <fullName>890- Toronto, Canada</fullName>
            </value>
            <value>
                <fullName>940 - Tradeshow Foreign</fullName>
            </value>
            <value>
                <fullName>944 - E&amp;E Foreign</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi, UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Location__c.field-meta.xml
<CustomField>
    <fullName>Sales_Location__c</fullName>
    <inlineHelpText>Primary exhibition sales person&#39;s office/team</inlineHelpText>
    <label>Sales Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>110- Las Vegas</fullName>
            </value>
            <value>
                <fullName>120- Housing</fullName>
                <label>120- OnPeak</label>
            </value>
            <value>
                <fullName>140- Salt Lake City</fullName>
            </value>
            <value>
                <fullName>150- Reno</fullName>
            </value>
            <value>
                <fullName>160- Denver</fullName>
            </value>
            <value>
                <fullName>170- Phoenix, Tucson, Albquerque</fullName>
            </value>
            <value>
                <fullName>220- Los Angeles</fullName>
            </value>
            <value>
                <fullName>230- Corp Events</fullName>
            </value>
            <value>
                <fullName>240- San Francisco, San Jose</fullName>
            </value>
            <value>
                <fullName>250- San Diego</fullName>
            </value>
            <value>
                <fullName>290 - Audio Visual</fullName>
            </value>
            <value>
                <fullName>310 - Lead Gen</fullName>
            </value>
            <value>
                <fullName>320 - Program</fullName>
            </value>
            <value>
                <fullName>330 - GES INT, DPM</fullName>
            </value>
            <value>
                <fullName>340 - GES UK, BD</fullName>
            </value>
            <value>
                <fullName>350 - GES Europe, BD</fullName>
            </value>
            <value>
                <fullName>360 - GES Middle East, BD</fullName>
            </value>
            <value>
                <fullName>370 - Retail INT, BD</fullName>
            </value>
            <value>
                <fullName>380 - Show Team</fullName>
            </value>
            <value>
                <fullName>390 - Branded Entertainment</fullName>
            </value>
            <value>
                <fullName>420- Austin, Dallas, Houston, San Antonio</fullName>
            </value>
            <value>
                <fullName>460- Calgary, Canada</fullName>
            </value>
            <value>
                <fullName>470- Edmonton, Canada</fullName>
            </value>
            <value>
                <fullName>471 - Vancouver, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada</fullName>
            </value>
            <value>
                <fullName>480 - Montreal, Canada - ESS</fullName>
            </value>
            <value>
                <fullName>481 - Quebec City, Canada</fullName>
            </value>
            <value>
                <fullName>483 - Montreal, Canada - CCI</fullName>
            </value>
            <value>
                <fullName>510- Atlanta</fullName>
            </value>
            <value>
                <fullName>520- Miami, Orlando, Tampa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary sales person (regardless of user type)</inlineHelpText>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N40000001qZlCEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Show_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Show_Occurrence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Corporate Accounts &amp; AV Projects</relationshipLabel>
    <relationshipName>Show_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Supplemental_Revenue_Stream_Type__c.field-meta.xml
<CustomField>
    <fullName>Supplemental_Revenue_Stream_Type__c</fullName>
    <label>Supplemental Revenue Stream Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Accomodations</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Dollar Rebate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TestbatchOppUpdateTrg.cls
@isTest
public class TestbatchOppUpdateTrg {
	@testsetup 
    static void setupData(){
            List<Opportunity> lsopps=new List<Opportunity>();
            Set<id> OppListIds=new Set<id>();
            RecordType oRectype1 = [Select Id From RecordType Where SObjectType = 'Opportunity' And Name = 'US - Registration'];
            Id Rectype1 = oRectype1.Id; 
            RecordType oRectype2 = [Select Id From RecordType Where SObjectType = 'Opportunity' And Name = 'Sales Rep Show Occurrence'];
            Id RecType2 = oRectype2.Id;  
            for(integer i=0;i<10;i++){
                Opportunity opp = new Opportunity();
                opp.Job_Number__c = 'TEST_JOB_'+i;        
                opp.OwnerId = UserInfo.getUserId();   
                opp.Sales_Person__c = UserInfo.getUserId();        
                opp.Sales_Location__c = 'TEST_LOCATION_'+i;        
                opp.Name = 'TestShowOpp-'+i;        
                opp.Prime_Contractor__c = null;        
                opp.Production_Location__c = 'TEST_LOCATION_'+i; 
                if(i==0){
                  opp.RecordTypeId = RecType1; 
                }
                else if(i==1){
                  opp.RecordTypeId = RecType2;    
                }
                  opp.StageName = 'SL1';  
                  opp.CloseDate = Date.newInstance(DateTime.now().yearGmt()-1,12,2); 
                  lsopps.add(opp);
                }
            Database.insert(lsopps);
     
    }
    
    @isTest
    static void runTest(){
        Map<Id,Opportunity> mOpps=new Map<Id,Opportunity>([Select Id, Name,Show_Occurrence__r.Name, RecordType.Name, Supplemental_Revenue_Stream_Type__c FROM Opportunity]);
        Test.startTest();
        	batchOppUpdatetrg oppBatch=new batchOppUpdatetrg(mOpps.keySet());
        	Database.executeBatch(oppBatch);
        Test.stopTest();
    }
}