unpackaged/main/default/objects/Opportunity/fields/PRF_Sent_to_CORE__c.field-meta.xml
<CustomField>
    <fullName>PRF_Sent_to_CORE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PRF Sent to CORE</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Processed_in_CORE__c.field-meta.xml
<CustomField>
    <fullName>Processed_in_CORE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processed in CORE</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/UpdateOpportunity.cls
public  class UpdateOpportunity {
     @AuraEnabled
    public static void upadateOpportunity(String RecordId) {
            opportunity opp  =  [select  id  , PRF_Sent_to_CORE__c , Processed_in_CORE__c , Type from opportunity where id  =: RecordId ];
            opp.PRF_Sent_to_CORE__c = True;
            opp.Processed_in_CORE__c = false;
            opp.Type    =  'Competitor CORE Show'; 
        try{
          update opp;
          if(Test.isRunningTest())
            {
                throw new applicationException ('Invalid myValue');

            }
        }
        catch(Exception e){
          
        }    

    }
    
    public class applicationException extends Exception {}

       
}