unpackaged/main/default/objects/Auth_Token__c/Auth_Token__c.object-meta.xml
<CustomObject>
    <label>Auth Token</label>
    <nameField>
        <label>Auth_Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auth Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Auth_Token__c/fields/Auth_Token_Expires__c.field-meta.xml
<CustomField>
    <fullName>Auth_Token_Expires__c</fullName>
    <label>Auth Token Expires</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/Core_Exhibitor__c.object-meta.xml
<CustomObject>
    <label>Core Exhibitor</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Exhibitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Address1__c.field-meta.xml
<CustomField>
    <fullName>Address1__c</fullName>
    <label>Address1</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Counter__c.field-meta.xml
<CustomField>
    <fullName>Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Error Counter</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Data_Com_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Data_Com_Error_Message__c</fullName>
    <label>Data.Com Error Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Data_Com_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Data_Com_Integration_Status__c</fullName>
    <label>Data.Com Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/IsManualIntervention__c.field-meta.xml
<CustomField>
    <fullName>IsManualIntervention__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It is used to identify the record which goes for manual Intervention</description>
    <label>IsManualIntervention</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Melissa_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Integration_Status__c</fullName>
    <label>Melissa Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Melissa Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Melissa_Results__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Results__c</fullName>
    <label>Melissa Results</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Oracle_Interface_Status__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Interface_Status__c</fullName>
    <label>Oracle Interface Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Oracle_Key_Index__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Key_Index__c</fullName>
    <externalId>true</externalId>
    <label>Oracle Key Index</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MelissaSetting__c/MelissaSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is specify, melissa switch, Counter ,Melissa error etc. Don&#39;t change the Name field value.It is use in apex melissa classes.</description>
    <label>Melissa Setting</label>
</CustomObject>

unpackaged/main/default/objects/oAuth__c/oAuth__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>oAuth Settings</label>
</CustomObject>

unpackaged/main/default/objects/oAuth__c/fields/Auth_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Auth_Endpoint__c</fullName>
    <label>Auth Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/oAuth__c/fields/DataComURL__c.field-meta.xml
<CustomField>
    <fullName>DataComURL__c</fullName>
    <label>DataComURL</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/oAuth__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/oAuth__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Test_EnrichmentOfCoreExhibitor.cls
/* Class Name: EnrichmentOfCoreExhibitor

    Author: Nehal Jain
    Created Date: 5/11/2017*/

@isTest(SeeAllData=false)

Public class Test_EnrichmentOfCoreExhibitor{



 private static void createCustomSetting(){
    
    List<MelissaSetting__c> listSetting = new List<MelissaSetting__c>();
    
    MelissaSetting__c instMsetting=new MelissaSetting__c(Name= 'MelisaPersonatorCountry',Value__c = 'US');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa GlobalAddress URL',Value__c = 'https://address.melissadata.net/V3/WEB/GlobalAddress/doGlobalAddress');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Personator URL',Value__c = 'https://personator.melissadata.net/v3/WEB/ContactVerify/doContactVerify');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Error Codes',Value__c = 'AE01');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa ClientId',Value__c = 'FWhH1f9hr-7NpBDjRxOu-R**');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Options',Value__c = 'DELIVERYLINES:ON');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Min Address Length',Value__c = '1');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Counter',Value__c = '3');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'datacom Counter',Value__c = '3');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Switch',Value__c = 'On');
    listSetting.add(instMsetting);
    
    insert listSetting;
    
    
    oAuth__c myoAuth = new oAuth__c();
    myoAuth.Auth_Endpoint__c = 'https://test123.salesforce.com';
    myoAuth.Client_ID__c = '3MVG9Pb';
    myoAuth.Client_Secret__c = '6888';
    myoAuth.Username__c='test@ges.com';
    myoAuth.Password__c='123456'; 
    myoAuth.name = 'DataComMatch';
    myoAuth.datacomUrl__C='https://test.com/services/data/v32.0/match/DunsRightMatchEngine/DatacloudCompany/DunsRightMatchRule';
    insert myoAuth;
    
}

private static void createCustomSettingSwtichOff(){
    
    List<MelissaSetting__c> listSetting = new List<MelissaSetting__c>();
    
    MelissaSetting__c instMsetting=new MelissaSetting__c(Name= 'MelisaPersonatorCountry',Value__c = 'US');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa GlobalAddress URL',Value__c = 'https://address.melissadata.net/V3/WEB/GlobalAddress/doGlobalAddress');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Personator URL',Value__c = 'https://personator.melissadata.net/v3/WEB/ContactVerify/doContactVerify');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Error Codes',Value__c = 'AE01');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa ClientId',Value__c = 'FWhH1f9hr-7NpBDjRxOu-R**');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Options',Value__c = 'DELIVERYLINES:ON');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Min Address Length',Value__c = '1');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Counter',Value__c = '3');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'datacom Counter',Value__c = '3');
    listSetting.add(instMsetting);
    instMsetting=new MelissaSetting__c(Name= 'Melissa Switch',Value__c = 'OFF');
    listSetting.add(instMsetting);
    
    insert listSetting;
    
    
    oAuth__c myoAuth = new oAuth__c();
    myoAuth.Auth_Endpoint__c = 'https://test123.salesforce.com';
    myoAuth.Client_ID__c = '3MVG9Pb';
    myoAuth.Client_Secret__c = '6888';
    myoAuth.Username__c='test@ges.com';
    myoAuth.Password__c='123456'; 
    myoAuth.name = 'DataComMatch';
    myoAuth.datacomUrl__C='https://test.com/services/data/v32.0/match/DunsRightMatchEngine/DatacloudCompany/DunsRightMatchRule';
    insert myoAuth;
    
}




static  testMethod void testmethod1() {



    createCustomSetting();
    Test.startTest();
Auth_Token__c auth= new Auth_Token__c();
    auth.Name='DataCom';
    auth.Auth_Token__c='606256c8-6122-464f-a9dc-cb90f32a0b20';
    auth.Auth_Token_Expires__c=Datetime.now().addminutes(60);
    insert auth;



 List<CORE_EXHIBITOR__c> CoreList = new List<CORE_EXHIBITOR__c>();
    CORE_EXHIBITOR__c Core = new CORE_EXHIBITOR__c();
    Core.Company_Name__c = 'Test';
    Core.Address1__c = 'Test1';
    Core.City__c = 'Delhi';
    Core.State__c = 'New Delhi';
    Core.Postal_Code__c = '201014';
    Core.Country__c  = 'India';
    Core.Melissa_Integration_Status__c  = 'Success';
    Core.Oracle_Interface_Status__c = '';
    Core.Oracle_Interface_Status__c='P';
    Core.Data_Com_Integration_Status__c='';
    Core.Data_Com_Integration_Status__c = 'Failed';
    Core.counter__C=3;
    Core.Data_Com_Error_Message__c='Unknown Exception or Read TimeOut Exception';
    Core.isManualIntervention__c=true;
    Core.Melissa_Results__c ='AE01,AE02';
    Core.Oracle_Key_Index__c = '123456';
    CoreList.add(Core);
    insert CoreList;
    
    BatchableMelissaCoreExhibitorCallOutMock instBatch= new BatchableMelissaCoreExhibitorCallOutMock();
    instBatch.coreExihibitorId=CoreList[0].id;
    Test.setMock(HttpCalloutMock.class, instBatch);
  //  Test.startTest();
 
   


EnrichmentOfCoreExhibitor ecc = new EnrichmentOfCoreExhibitor();

ecc.getSwitchStatus();
ecc.melissaRequestBodyInJson(CoreList);
ecc.enrichCoreExhibitorAddress(CoreList);
ecc.setStatusForRecord(Core,true ,3.0);
 Test.stopTest();
}

static  testMethod void testmethod2() {

 
    createCustomSetting();

Auth_Token__c auth= new Auth_Token__c();
    auth.Name='DataCom';
    auth.Auth_Token__c='606256c8-6122-464f-a9dc-cb90f32a0b20';
    auth.Auth_Token_Expires__c=Datetime.now().addminutes(60);
    insert auth;




 List<CORE_EXHIBITOR__c> CoreList = new List<CORE_EXHIBITOR__c>();
    CORE_EXHIBITOR__c Core = new CORE_EXHIBITOR__c();
    Core.Company_Name__c = 'Test09';
    Core.Address1__c = 'Test123';
    Core.City__c = 'New York';
    Core.State__c = 'NY';
    Core.Postal_Code__c = '10018-3249';
    Core.Country__c  = 'US';
    Core.Melissa_Integration_Status__c  = 'Success';
    Core.Oracle_Interface_Status__c = '';
    Core.Oracle_Interface_Status__c='P';
    Core.Data_Com_Integration_Status__c='';
    Core.Data_Com_Integration_Status__c = 'Failed';
    Core.counter__C=3;
    Core.Data_Com_Error_Message__c='Unknown Exception or Read TimeOut Exception';
    Core.Oracle_Key_Index__c = '023456';
    CoreList.add(Core);
    insert CoreList;
    Test.startTest(); 
 set<id> CoreIDs= new set<id>();
    CoreIDs.add(Core.id);
   Test.setMock(HttpCalloutMock.class, new BatchableDataComWebServiceCallOutMock());
 
EnrichmentOfCoreExhibitor ecc = new EnrichmentOfCoreExhibitor();

ecc.getSwitchStatus();
ecc.melissaRequestBodyInJson(CoreList);
//ecc.enrichCoreExhibitorAddress(CoreList);
ecc.enrichCoreExhibitorDUNS(CoreList);
 Test.stopTest();
}

static  testMethod void testmethod3() {


createCustomSetting();

Auth_Token__c auth= new Auth_Token__c();
    auth.Name='DataCom';
    auth.Auth_Token__c='606256c8-6122-464f-a9dc-cb90f32a0b20';
    auth.Auth_Token_Expires__c=Datetime.now().addminutes(60);
    insert auth;



 List<CORE_EXHIBITOR__c> CoreList = new List<CORE_EXHIBITOR__c>();
    CORE_EXHIBITOR__c Core = new CORE_EXHIBITOR__c();
    Core.Company_Name__c = 'Test';
    Core.Address1__c = 'Test1';
    Core.City__c = 'Delhi';
    Core.State__c = 'New Delhi';
    Core.Postal_Code__c = '201014';
    Core.Country__c  = 'India';
    Core.isManualIntervention__c=true;
    Core.counter__C=0;
    Core.Melissa_Integration_Status__c  = 'Melissa Error';
    Core.Data_Com_Error_Message__c='Unknown Exception or Read TimeOut Exception';
    Core.Melissa_Results__c ='AE01,AE02';
    Core.Oracle_Key_Index__c = '123456';
    CoreList.add(Core);
    insert CoreList;
    
 
    Test.startTest();
   BatchableMelissaCoreExhibitorCallOutMock instBatch= new BatchableMelissaCoreExhibitorCallOutMock();
    instBatch.coreExihibitorId=CoreList[0].id;
    Test.setMock(HttpCalloutMock.class, instBatch);
   


EnrichmentOfCoreExhibitor ecc = new EnrichmentOfCoreExhibitor();

ecc.getSwitchStatus();
ecc.melissaRequestBodyInJson(CoreList);
ecc.enrichCoreExhibitorAddress(CoreList);
ecc.setStatusForRecord(Core,true ,3.0);
 Test.stopTest();
}

static  testMethod void testmethod4() {


createCustomSetting();

Auth_Token__c auth= new Auth_Token__c();
    auth.Name='DataCom';
    auth.Auth_Token__c='606256c8-6122-464f-a9dc-cb90f32a0b20';
    auth.Auth_Token_Expires__c=Datetime.now().addminutes(60);
    insert auth;



 List<CORE_EXHIBITOR__c> CoreList = new List<CORE_EXHIBITOR__c>();
    CORE_EXHIBITOR__c Core = new CORE_EXHIBITOR__c();
    Core.Company_Name__c = 'Test';
    Core.Address1__c = 'Test1';
    Core.City__c = 'Delhi';
    Core.State__c = 'New Delhi';
    Core.Postal_Code__c = '201014';
    Core.Country__c  = 'US';
    Core.isManualIntervention__c=true;
    Core.counter__C=0;
    Core.Melissa_Integration_Status__c  = 'Failed';
    Core.Data_Com_Error_Message__c='Unknown Exception or Read TimeOut Exception';
    Core.Melissa_Results__c ='AE01,AE02';
    Core.Oracle_Key_Index__c = '123456';
    CoreList.add(Core);
    insert CoreList;
    
 
    Test.startTest();
    BatchableMelissaCoreExhibitorCallOutMock instBatch= new BatchableMelissaCoreExhibitorCallOutMock();
    instBatch.coreExihibitorId=CoreList[0].id;
    Test.setMock(HttpCalloutMock.class, instBatch);
   


EnrichmentOfCoreExhibitor ecc = new EnrichmentOfCoreExhibitor();

ecc.getSwitchStatus();
ecc.melissaRequestBodyInJson(CoreList);
ecc.enrichCoreExhibitorAddress(CoreList);
ecc.setStatusForRecord(Core,true ,3.0);
 Test.stopTest();
}

static  testMethod void testmethod5() {

createCustomSettingSwtichOff();


Auth_Token__c auth= new Auth_Token__c();
    auth.Name='DataCom';
    auth.Auth_Token__c='606256c8-6122-464f-a9dc-cb90f32a0b20';
    auth.Auth_Token_Expires__c=Datetime.now().addminutes(60);
    insert auth;



 List<CORE_EXHIBITOR__c> CoreList = new List<CORE_EXHIBITOR__c>();
    CORE_EXHIBITOR__c Core = new CORE_EXHIBITOR__c();
    Core.Company_Name__c = 'Test';
    Core.Address1__c = 'Test1';
    Core.City__c = 'Delhi';
    Core.State__c = 'New Delhi';
    Core.Postal_Code__c = '201014';
    Core.Country__c  = 'US';
    //Core.isManualIntervention__c=true;
    Core.counter__C=0;
    Core.Melissa_Integration_Status__c  = 'Success';
    //Core.counter__C=0;
    Core.Data_Com_Error_Message__c='Unknown Exception or Read TimeOut Exception';
    Core.Melissa_Results__c ='AE01,AE02';
    Core.Oracle_Key_Index__c = '123456';
    CoreList.add(Core);
    insert CoreList;
   // Core.counter__C=1;
   // update CoreList;
    
    map<Id, List<CORE_EXHIBITOR__c>> map1 = new map<Id, List<CORE_EXHIBITOR__c>>(); 
    for(CORE_EXHIBITOR__c t : CoreList)
    {
        map1.put(t.Id, new List<CORE_EXHIBITOR__c>{t});
    }
    
    
 
    Test.startTest();
       BatchableMelissaCoreExhibitorCallOutMock instBatch= new BatchableMelissaCoreExhibitorCallOutMock();
    instBatch.coreExihibitorId=CoreList[0].id;
    Test.setMock(HttpCalloutMock.class, instBatch);
       


    EnrichmentOfCoreExhibitor ecc = new EnrichmentOfCoreExhibitor();

ecc.getSwitchStatus();
ecc.melissaRequestBodyInJson(CoreList);
    ecc.enrichCoreExhibitorAddress(CoreList);
ecc.setStatusForRecord(Core,true ,3.0);
 Test.stopTest();
 
    
}


}