unpackaged/main/default/objects/Credit_Memo_ICS__c/Credit_Memo_ICS__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM - {00000}</displayFormat>
        <label>Credit_Memo No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/AR1_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>Credit_Memo_ICS4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/AR2_Approver_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver_Email_ID__c</fullName>
    <label>AR2 Approver Email ID</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/AR2_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>Credit_Memo_ICS3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/CSO_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Credit Memo (CSO Approver Name)</relationshipLabel>
    <relationshipName>Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <description>Employees  object stored information about gesemployee email address</description>
    <label>Employees</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/ICS_Approver_Matrix__c.object-meta.xml
<CustomObject>
    <label>ICS Approver Matrix</label>
    <nameField>
        <displayFormat>ICS_AM-{00000}</displayFormat>
        <label>ICS Approver Matrix N0</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICS Approver Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/AR1_Approver__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (AR1 Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/AR2_Approver__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (AR2 Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/CSO_Approver__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (CSO Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Max_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Amount__c</fullName>
    <label>Max - Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Min_Amount__c.field-meta.xml
<CustomField>
    <fullName>Min_Amount__c</fullName>
    <label>Min - Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Transaction_Types__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Types__c</fullName>
    <label>Transaction Types</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AR Adjustments</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>Credit Memo</fullName>
            </value>
            <value>
                <fullName>Payment Transfer</fullName>
            </value>
            <value>
                <fullName>Receipt Reversals</fullName>
            </value>
            <value>
                <fullName>Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/Refunds_ICS__c.object-meta.xml
<CustomObject>
    <label>Refunds</label>
    <nameField>
        <displayFormat>Refunds-{00000}</displayFormat>
        <label>Refunds ICS No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Refunds_ICS__c/fields/AR1_Approver_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Email_ID__c</fullName>
    <label>AR1 Approver Email ID</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/fields/AR1_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>Refunds_ICS1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/fields/AR2_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>Refunds_ICS2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/fields/CSO_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Refunds (CSO Approver Name)</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ICS_Refunds_Approver_Update.cls
public class ICS_Refunds_Approver_Update {
    //public static Void CMapproverdetails(List<Credit_Memo_ICS__c> CrList){
    
    public static List<Refunds_ICS__c> Refunds_Approverdetails(List<Refunds_ICS__c> CrList){
    List<Refunds_ICS__c> RefundsList = CrList;
        
        List<ICS_Approver_Matrix__c> CRMList = [select  Transaction_Types__c,Max_Amount__c, Min_Amount__c,    
                                                AR1_Approver__c,AR2_Approver__c, CSO_Approver__c
                                                    from ICS_Approver_Matrix__c where Transaction_Types__c = 'Refunds'];
        
        Set<Id> approverIds = new Set<Id>();
        for(ICS_Approver_Matrix__c cr : CRMList){
            approverIds.add(cr.AR1_Approver__c);
            approverIds.add(cr.AR2_Approver__c);
        }
        List<Employees__c> EmployeeList = [select id, Email_Address__c from Employees__c where id in :approverIds ];
        
        Map<Id, String> EmployeeIdEmailMap = new Map<Id, String>();
        for(Employees__c u : EmployeeList){
            EmployeeIdEmailMap.put(u.id, u.Email_Address__c);
        }  
           for(Refunds_ICS__c cm : RefundsList){
           for(ICS_Approver_Matrix__c cr : CRMList){
                   system.debug('cr==='+cr);
                  if (cr.Min_Amount__c != null && cr.Max_Amount__c != null){
                      if (cm.Amount__c >= cr.Min_Amount__c && cm.Amount__c <= cr.Max_Amount__c){
                            system.debug('cm==='+cm);
                            system.debug('cr1==='+cr);
                            cm.AR1_Approver_Name__c = cr.AR1_Approver__c;
                            cm.AR1_Approver_Email_ID__c = EmployeeIdEmailMap.get(cr.AR1_Approver__c);
                            cm.CSO_Approver_Name__c = cr.CSO_Approver__c;
                            //cm.CSO_Approver_EmailID__c = EmployeeIdEmailMap.get(cr.CSO_Approver__c);
                            cm.AR2_Approver_Name__c = cr.AR2_Approver__c;
                            cm.AR2_Approver_Email_ID__c = EmployeeIdEmailMap.get(cr.AR2_Approver__c);
                          system.debug('cm==='+cm);
                          break;
                         }
                   }
                else if(cr.Max_Amount__c == null){
                      if (cm.Amount__c >= cr.Min_Amount__c){
                        cm.AR1_Approver_Name__c = cr.AR1_Approver__c;
                        cm.AR1_Approver_Email_ID__c = EmployeeIdEmailMap.get(cr.AR1_Approver__c);
                        cm.CSO_Approver_Name__c = cr.CSO_Approver__c;
                        //cm.CSO_Approver_EmailID__c = EmployeeIdEmailMap.get(cr.CSO_Approver__c);  
                        cm.AR2_Approver_Name__c = cr.AR2_Approver__c;
                        cm.AR2_Approver_Email_ID__c = EmployeeIdEmailMap.get(cr.AR2_Approver__c);
                          break;
                   }
               }                 
             
           }   
               system.debug('c2=='+cm); 
        }
        return RefundsList;
    }    
}