unpackaged/main/default/objects/SOPAuthentication__c/SOPAuthentication__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SOP_Authentication</label>
</CustomObject>

unpackaged/main/default/objects/SOPService__c/SOPService__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A custom setting for the SOP Service</description>
    <label>SOPService</label>
</CustomObject>

unpackaged/main/default/objects/SOPService__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The URL for the SOP Service</description>
    <inlineHelpText>The URL for the SOP Service</inlineHelpText>
    <label>URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/VatNumberValidatorTest.cls
@isTest
private class VatNumberValidatorTest {
    

    @isTest static void test_method_one() {

      insert new SOPService__c(Name = 'VatServiceEndpoint', URL__c = 'https://uatapi.viad.com/GES/v1/VatService.svc');
          
      SOPAuthentication__c auth = new SOPAuthentication__c();
                 
      VatNumberValidator sapII = new VatNumberValidator();
        
      insert new SOPService__c(Name = 'Default', URL__c = 'https://uatapi.viad.com/GES/v2/SOPService.svc');
            
      auth.Name = 'Login Credentials';
      auth.Password__c = 'sf4GFK@)GJSv674hS/gfht4K{L';
      auth.Username__c = 'Vertiba';
      insert auth;
             
      VatNumberValidator.ValidateVatNumber('test');
      VatNumberValidator.ValidateVatNumber('');
      VatNumberValidator.ValidateVatNumber('GB830914636');
  
    }
}