unpackaged/main/default/objects/Core_Exhibitor__c/Core_Exhibitor__c.object-meta.xml
<CustomObject>
    <label>Core Exhibitor</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Exhibitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Counter__c.field-meta.xml
<CustomField>
    <fullName>Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Error Counter</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Data_Com_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Data_Com_Integration_Status__c</fullName>
    <label>Data.Com Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/IsManualIntervention__c.field-meta.xml
<CustomField>
    <fullName>IsManualIntervention__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It is used to identify the record which goes for manual Intervention</description>
    <label>IsManualIntervention</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Melissa_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Integration_Status__c</fullName>
    <label>Melissa Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Melissa Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Melissa_Results__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Results__c</fullName>
    <label>Melissa Results</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Occurrence_Id__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Id__c</fullName>
    <label>Occurrence Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Oracle_Interface_Status__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Interface_Status__c</fullName>
    <label>Oracle Interface Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Oracle_Key_Index__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Key_Index__c</fullName>
    <externalId>true</externalId>
    <label>Oracle Key Index</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/MelissaSetting__c/MelissaSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It is specify, melissa switch, Counter ,Melissa error etc. Don&#39;t change the Name field value.It is use in apex melissa classes.</description>
    <label>Melissa Setting</label>
</CustomObject>

unpackaged/main/default/classes/Test_ListViewCoreExhibitorController.cls
/* Class Name: ListViewCoreExhibitorController 

    Author: Nehal Jain
    Created Date: 5/11/2017*/

@isTest
Public class Test_ListViewCoreExhibitorController
{
    static  testMethod void controllertest1() 
    {
    
        MelissaSetting__c setting = new MelissaSetting__c();
        setting.Name = 'Melissa Manual Intervention';
        setting.Value__c = 'AE01';
        insert setting;                
        
        List<CORE_EXHIBITOR__c> coreexh= new List<CORE_EXHIBITOR__c>();
        CORE_EXHIBITOR__c core = new CORE_EXHIBITOR__c();
        core.Oracle_Key_Index__c='12345';
        core.Oracle_Interface_Status__c='P';
        core.Data_Com_Integration_Status__c='Success';
        core.Country__c='US';
        core.Melissa_Results__c='AE01';
        core.IsManualIntervention__c=false;
        core.Melissa_Integration_Status__c='Success';
        core.Occurrence_Id__c='341894';
        core.Counter__c=4;
        coreexh.add(core);
        insert coreexh;
        
        ListViewCoreExhibitorController.Exhibitorwrapper wrap = new ListViewCoreExhibitorController.Exhibitorwrapper();        
        ListViewCoreExhibitorController listview = new ListViewCoreExhibitorController(); 
        
        listview.cancel();
        listview.save();
        listview.getShowOccurences();
        listview.showOccurrence();
        listview.updateWrapperList();
        listview.createMainWrapper(coreexh);
        listview.getprev();
        listview.getnxt();
        listview.beginning();
        listview.previous();
        listview.next();
        //listview.end();    
    }
}