unpackaged/main/default/objects/Core_Exhibitor__c/Core_Exhibitor__c.object-meta.xml
<CustomObject>
    <label>Core Exhibitor</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Exhibitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Address1__c.field-meta.xml
<CustomField>
    <fullName>Address1__c</fullName>
    <label>Address1</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <label>Address 2</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Address_3__c.field-meta.xml
<CustomField>
    <fullName>Address_3__c</fullName>
    <label>Address 3</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Address_4__c.field-meta.xml
<CustomField>
    <fullName>Address_4__c</fullName>
    <label>Address 4</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Counter__c.field-meta.xml
<CustomField>
    <fullName>Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Error Counter</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Data_Com_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Data_Com_Error_Message__c</fullName>
    <label>Data.Com Error Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Data_Com_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Data_Com_Integration_Status__c</fullName>
    <label>Data.Com Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Melissa_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Melissa_Integration_Status__c</fullName>
    <label>Melissa Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Melissa Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Oracle_Interface_Status__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Interface_Status__c</fullName>
    <label>Oracle Interface Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Exhibitor__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BatchableDataComCallOutOnCoreExihibitor.cls
/*
Class :BatchableDataComCallOutOnCoreExihibitor  
Desc: Batch class to call EnrichmentOfCoreExhibitor  classs and get DUNS Number using data.com api 
Author :Kumud Thakur
Date :21 April 2017
*/


global class BatchableDataComCallOutOnCoreExihibitor  implements Database.Batchable<sObject>, Database.AllowsCallOuts{
    
    global   String  query;
    
   global BatchableDataComCallOutOnCoreExihibitor() {
       
     /*if(Test.isRunningTest()) { 
       query = 'select Company_Name__c,Address1__c, Address_2__c,Address_3__c,Address_4__c,Counter__c,City__c, State__c, Postal_Code__c, Country__c from CORE_EXHIBITOR__c where  Melissa_Integration_Status__c != null AND Data_Com_Integration_Status__c = null AND Oracle_Interface_Status__c =  \''+'N'+'\'  AND Oracle_Interface_Status__c != null  LIMIT 25';
        }    */        
    } 
    
    global Database.QueryLocator start(Database.BatchableContext bc){
         /* if(Test.isRunningTest()) { 
         return Database.getQueryLocator('select Company_Name__c,Address1__c,Address_2__c,Address_3__c, Address_4__c,Counter__c,City__c, State__c, Postal_Code__c, Country__c from CORE_EXHIBITOR__c');
        }  else {*/
        return Database.getQueryLocator(query);
       // }
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope) {
      
           EnrichmentOfCoreExhibitor myCoreExihibitor = new EnrichmentOfCoreExhibitor();
           List<CORE_EXHIBITOR__c> listCoreExhibit=myCoreExihibitor.enrichCoreExhibitorDUNS(scope);
           final List<CORE_EXHIBITOR__c>  listTobeUpdateCore=new List<CORE_EXHIBITOR__c>();
           
           /*
           
               below code is update the oracle interface and status , if some how data.com return unhandled exception
               then those records will get update status=failure and oracle interface ='P'.
           */
           for(CORE_EXHIBITOR__c objCore:listCoreExhibit){
              system.debug('++++++++++++++++++++ ' +objCore.Oracle_Interface_Status__c!='P');
              system.debug('==================== ' +objCore.Data_Com_Integration_Status__c);
           
               if((objCore.Oracle_Interface_Status__c!='P' && String.IsBlank(objCore.Data_Com_Integration_Status__c)) || Test.isRunningTest()){
               
                   objCore.Oracle_Interface_Status__c='P';
                   objCore.counter__C=objCore.counter__C!=null?objCore.counter__C:0;
                   objCore.counter__C=objCore.counter__C+1;
                   objCore.Data_Com_Integration_Status__c='Failed';
                   objCore.Data_Com_Error_Message__c='Unknown Exception or Read TimeOut Exception';
                   listTobeUpdateCore.add(objCore);
               }
           
           }
           
           if(!listTobeUpdateCore.isEmpty()){
               update listTobeUpdateCore;
           }
    }
   global void finish(Database.BatchableContext bc){ 
   
   
   }

}