unpackaged/main/default/objects/AR_Adjustments__c/AR_Adjustments__c.object-meta.xml
<CustomObject>
    <label>AR Adjustments</label>
    <nameField>
        <displayFormat>ARA-{0000}</displayFormat>
        <label>AR_Adjustments_No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR_Adj_CSI_ID__c.field-meta.xml
<CustomField>
    <fullName>AR_Adj_CSI_ID__c</fullName>
    <description>AR_Adj_CSI_ID</description>
    <label>CSI ICS</label>
    <referenceTo>Customer_Service_Inquiries_ICS__c</referenceTo>
    <relationshipName>AR_Adjustments_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/Case_location__c.field-meta.xml
<CustomField>
    <fullName>Case_location__c</fullName>
    <formula>AR_Adj_CSI_ID__r.Location__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/Case_Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Case_Sales_Channel__c</fullName>
    <formula>Text(AR_Adj_CSI_ID__r.Sales_Channel__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Sales Channel</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/Credit_Memo_ICS__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM - {00000}</displayFormat>
        <label>Credit_Memo No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/Case_Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Case_Sales_Channel__c</fullName>
    <formula>Text(CSI_ICS__r.Sales_Channel__c)</formula>
    <label>Case Sales Channel</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/Credit_Memo_Reason__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Reason__c</fullName>
    <label>Credit Memo Reason</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accounts Receivables Billing Error: CM ERROR</fullName>
            </value>
            <value>
                <fullName>Bad Debt: CM</fullName>
            </value>
            <value>
                <fullName>Billed Wrong Customer/Show: CM ERROR</fullName>
            </value>
            <value>
                <fullName>Cancel Refund Check: CM ERROR</fullName>
            </value>
            <value>
                <fullName>Cancelled/Didn&#39;t Attend Show: CM</fullName>
            </value>
            <value>
                <fullName>Didn&#39;t Order:CM</fullName>
            </value>
            <value>
                <fullName>Discount Given to Customer: CM</fullName>
            </value>
            <value>
                <fullName>Duplicate Billing: CM ERROR</fullName>
            </value>
            <value>
                <fullName>Good Faith/Settlement/In Short Pd/PO Honored: CM</fullName>
            </value>
            <value>
                <fullName>Insufficient/Incomplete Documentation: CM</fullName>
            </value>
            <value>
                <fullName>Legal Settlement: CM</fullName>
            </value>
            <value>
                <fullName>Logistics Good Faith/Settlement: CM</fullName>
            </value>
            <value>
                <fullName>Operations Error: CM</fullName>
            </value>
            <value>
                <fullName>Order Entry Error: CM</fullName>
            </value>
            <value>
                <fullName>Outbound Quote Didn&#39;t Match IB: CM</fullName>
            </value>
            <value>
                <fullName>Sales Tax Error: CM ERROR</fullName>
            </value>
            <value>
                <fullName>Service Failure/Item(s) not Received: CM</fullName>
            </value>
            <value>
                <fullName>Should be Billed to Assn: CM</fullName>
            </value>
            <value>
                <fullName>Supervision Charged in Error: CM</fullName>
            </value>
            <value>
                <fullName>Surcharge/Off Target Doesn&#39;t Apply: CM</fullName>
            </value>
            <value>
                <fullName>Tax Exempt: CM ERROR</fullName>
            </value>
            <value>
                <fullName>Trans/Discount not Applied: CM</fullName>
            </value>
            <value>
                <fullName>Wrong Price/Quote/Rate: CM</fullName>
            </value>
            <value>
                <fullName>Wrong Product: CM</fullName>
            </value>
            <value>
                <fullName>Wrong Qty/Weight/Hours: CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/Reason_Code_Category__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code_Category__c</fullName>
    <label>Reason Code Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cat - A</fullName>
            </value>
            <value>
                <fullName>Cat - B</fullName>
            </value>
            <value>
                <fullName>Cat - C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E&amp;E (Trade Show)</fullName>
            </value>
            <value>
                <fullName>E&amp;E Logistics (Trade Show)</fullName>
            </value>
            <value>
                <fullName>E&amp;E(GBMS)</fullName>
            </value>
            <value>
                <fullName>Revenue Exhibitor</fullName>
            </value>
            <value>
                <fullName>Revenue Logistics</fullName>
            </value>
            <value>
                <fullName>Revenue Show Org</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Revenue Trade Show &amp; Logistics</fullName>
                <isActive>false</isActive>
                <label>Revenue Trade Show &amp; Logistics</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Amount_w_psp__c  +  Tax_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/Customer_Service_Inquiries_ICS__c.object-meta.xml
<CustomObject>
    <label>ICS Cases</label>
    <nameField>
        <displayFormat>ICS {000000}</displayFormat>
        <label>CSI ICS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICS Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Service_Inquiries_ICS</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Case_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Approval_Status__c</fullName>
    <label>Case Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Case Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Case Open</fullName>
                <default>true</default>
                <label>Case Open</label>
            </value>
            <value>
                <fullName>Requestor Submitted</fullName>
            </value>
            <value>
                <fullName>Requestor Approved</fullName>
            </value>
            <value>
                <fullName>Requestor Rejected</fullName>
            </value>
            <value>
                <fullName>LOB Open</fullName>
            </value>
            <value>
                <fullName>LOB Submitted</fullName>
            </value>
            <value>
                <fullName>LOB Approved</fullName>
            </value>
            <value>
                <fullName>LOB Rejected</fullName>
            </value>
            <value>
                <fullName>F&amp;R Open</fullName>
            </value>
            <value>
                <fullName>F&amp;R Submitted</fullName>
            </value>
            <value>
                <fullName>F&amp;R Approved</fullName>
            </value>
            <value>
                <fullName>F&amp;R Rejected</fullName>
            </value>
            <value>
                <fullName>AR1 Open</fullName>
            </value>
            <value>
                <fullName>AR1 Submitted</fullName>
            </value>
            <value>
                <fullName>AR1 Approved</fullName>
            </value>
            <value>
                <fullName>AR1 Rejected</fullName>
            </value>
            <value>
                <fullName>CSO Open</fullName>
            </value>
            <value>
                <fullName>CSO Submitted</fullName>
            </value>
            <value>
                <fullName>CSO Approved</fullName>
            </value>
            <value>
                <fullName>CSO Rejected</fullName>
            </value>
            <value>
                <fullName>AR2 Open</fullName>
            </value>
            <value>
                <fullName>AR2 Submitted</fullName>
            </value>
            <value>
                <fullName>AR2 Approved</fullName>
            </value>
            <value>
                <fullName>AR2 Rejected</fullName>
            </value>
            <value>
                <fullName>Additional Open</fullName>
            </value>
            <value>
                <fullName>Additional Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Show Occurrence</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Customer_Service_Inquiries_ICS</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E&amp;E (Trade Show)</fullName>
                <default>true</default>
                <label>E&amp;E (Trade Show)</label>
            </value>
            <value>
                <fullName>E&amp;E Logistics (Trade Show)</fullName>
            </value>
            <value>
                <fullName>E&amp;E(GBMS)</fullName>
            </value>
            <value>
                <fullName>Revenue Exhibitor</fullName>
            </value>
            <value>
                <fullName>Revenue Logistics</fullName>
            </value>
            <value>
                <fullName>Revenue Show Org</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Revenue Trade Show &amp; Logistics</fullName>
                <isActive>false</isActive>
                <label>Revenue Trade Show &amp; Logistics</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/Refunds_ICS__c.object-meta.xml
<CustomObject>
    <label>Refunds</label>
    <nameField>
        <displayFormat>Refunds-{00000}</displayFormat>
        <label>Refunds ICS No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Refunds_ICS__c/fields/Case_Location__c.field-meta.xml
<CustomField>
    <fullName>Case_Location__c</fullName>
    <formula>CSI_ICS__r.Location__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ICS_UpdatetransactionOnCase.cls
public with sharing class ICS_UpdatetransactionOnCase {
    public static Set<Id>updatedCaseIDs;
        
    public static void handleApprovers(List<Customer_Service_Inquiries_ICS__c> updatedCases){
        updatedCaseIDs= new Set<Id>();
        List<Customer_Service_Inquiries_ICS__c> allCaseList =updatedCases;
        try{
            for(Customer_Service_Inquiries_ICS__c varCase : allCaseList ){
                updatedCaseIDs.add(varCase.Id);
            }
        }catch(exception e){
            system.debug('error==='+e.getMessage());
            system.debug('error==='+e.getStackTraceString());
        }
        List<Credit_Memo_ICS__c> allCreditMemo= new List<Credit_Memo_ICS__c>();
        try{
            
            List<Credit_Memo_ICS__c> updatedcreditMemo= new List<Credit_Memo_ICS__c>();
            List<AR_Adjustments__c> allARAdjustments= new List<AR_Adjustments__c>();
            List<AR_Adjustments__c> updatedARAdjustments= new List<AR_Adjustments__c>();
            List<Refunds_ICS__c> allRefunds= new List<Refunds_ICS__c>();
            List<Refunds_ICS__c> updatedRefunds= new List<Refunds_ICS__c>();
            
            List<Customer_Service_Inquiries_ICS__c>casesToBeUpdated= [SELECT Id,Case_Approval_Status__c,Account_Name__c, Opportunity_Name__c, Sales_Channel__c,(SELECT Id,Case_location__c,Case_Sales_Channel__c,Amount__c FROM AR_Adjustments_Approvals__r),(SELECT Id,Reason_Code_Category__c,Credit_Memo_Reason__c, Case_Sales_Channel__c, Case_Location__c, Total_Amount__c, Credit_LOB__c FROM ICS_Credit_Memo__r),(SELECT Id,Amount__c  FROM Refunds_ICS__r) FROM Customer_Service_Inquiries_ICS__c WHERE Case_Approval_Status__c ='Case Open' AND Id IN :updatedCaseIDs];
            for(Customer_Service_Inquiries_ICS__c tempCase:casesToBeUpdated){
                allCreditMemo.addAll(tempCase.ICS_Credit_Memo__r);
                allARAdjustments.addAll(tempCase.AR_Adjustments_Approvals__r);
                allRefunds.addAll(tempCase.Refunds_ICS__r);

            }
            if(allCreditMemo.size()>0){
                ICS_CreditMemo_Handler.updateReasonCategoryCode(allCreditMemo);
                updatedcreditMemo=ICS_CreditMemo_Handler.CMapproverdetails(allCreditMemo);
                update updatedcreditMemo;   
            }   
            if(allARAdjustments.size()>0){
                updatedARAdjustments=ICS_AR_Adjustments_Approver_Update.AR_Adjustments_Approverdetails(allARAdjustments);
                update updatedARAdjustments;
            }
            if(allRefunds.size()>0){
                updatedRefunds=ICS_Refunds_Approver_Update.Refunds_Approverdetails(allRefunds);
                update updatedRefunds;  
            }
            
        }catch(exception e){
            system.debug('allCreditMemo ==='+allCreditMemo );
            system.debug('allCreditMemo size ==='+allCreditMemo.size() );
            system.debug('error==='+e.getMessage());
            system.debug('error==='+e.getStackTraceString());
        }
    }
}