unpackaged/main/default/objects/AR_Adjustments__c/AR_Adjustments__c.object-meta.xml
<CustomObject>
    <label>AR Adjustments</label>
    <nameField>
        <displayFormat>ARA-{0000}</displayFormat>
        <label>AR_Adjustments_No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR1_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Email__c</fullName>
    <label>AR1 Approver Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR1_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments7</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR2_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments8</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/Case_location__c.field-meta.xml
<CustomField>
    <fullName>Case_location__c</fullName>
    <formula>AR_Adj_CSI_ID__r.Location__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/Case_Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Case_Sales_Channel__c</fullName>
    <formula>Text(AR_Adj_CSI_ID__r.Sales_Channel__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Sales Channel</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/CSO_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>AR Adjustments (CSO Approver Name)</relationshipLabel>
    <relationshipName>AR_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/DAM_Approver_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>DAM_Approver_Email_ID__c</fullName>
    <label>DAM Approver Email ID</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/DAM_LOB_Approver__c.field-meta.xml
<CustomField>
    <fullName>DAM_LOB_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DAM/LOB Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/F_A_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>F_A_Approver_Email__c</fullName>
    <label>F&amp;A Approver Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/F_R_Approver__c.field-meta.xml
<CustomField>
    <fullName>F_R_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>F&amp;R Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments6</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>AUDIO VISUAL</fullName>
            </value>
            <value>
                <fullName>DECO</fullName>
            </value>
            <value>
                <fullName>ELECTRICAL</fullName>
            </value>
            <value>
                <fullName>FREIGHT</fullName>
            </value>
            <value>
                <fullName>GRAPHICS</fullName>
            </value>
            <value>
                <fullName>HANGING SIGN/ RIGGING</fullName>
            </value>
            <value>
                <fullName>I&amp;D LABOR</fullName>
            </value>
            <value>
                <fullName>JANITORIAL</fullName>
            </value>
            <value>
                <fullName>LOGISTICS</fullName>
            </value>
            <value>
                <fullName>PLUMBING</fullName>
            </value>
            <value>
                <fullName>Corporate Accounts (program/priority)</fullName>
            </value>
            <value>
                <fullName>Furniture/Accessories (aka: Deco)</fullName>
                <isActive>false</isActive>
                <label>Furniture/Accessories (aka: Deco)</label>
            </value>
            <value>
                <fullName>Hanging Sign</fullName>
                <isActive>false</isActive>
                <label>Hanging Sign</label>
            </value>
            <value>
                <fullName>I&amp;D</fullName>
                <isActive>false</isActive>
                <label>I&amp;D</label>
            </value>
            <value>
                <fullName>Labor</fullName>
                <isActive>false</isActive>
                <label>Labor</label>
            </value>
            <value>
                <fullName>RIGGING</fullName>
                <isActive>false</isActive>
                <label>RIGGING</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ICS_Location_City</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/ICS_Approver_Matrix__c.object-meta.xml
<CustomObject>
    <label>ICS Approver Matrix</label>
    <nameField>
        <displayFormat>ICS_AM-{00000}</displayFormat>
        <label>ICS Approver Matrix N0</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICS Approver Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Additional_Approver__c.field-meta.xml
<CustomField>
    <fullName>Additional_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (Additional Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/AR1_Approver__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (AR1 Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/AR2_Approver__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (AR2 Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/CSO_Approver__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (CSO Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/F_R_Approver__c.field-meta.xml
<CustomField>
    <fullName>F_R_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>F&amp;R Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (F&amp;R Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUDIO VISUAL</fullName>
            </value>
            <value>
                <fullName>DECO</fullName>
            </value>
            <value>
                <fullName>ELECTRICAL</fullName>
            </value>
            <value>
                <fullName>FREIGHT</fullName>
            </value>
            <value>
                <fullName>GRAPHICS</fullName>
            </value>
            <value>
                <fullName>HANGING SIGN/ RIGGING</fullName>
            </value>
            <value>
                <fullName>I&amp;D LABOR</fullName>
            </value>
            <value>
                <fullName>JANITORIAL</fullName>
            </value>
            <value>
                <fullName>LOGISTICS</fullName>
            </value>
            <value>
                <fullName>PLUMBING</fullName>
            </value>
            <value>
                <fullName>Corporate Accounts (program/priority)</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Furniture/Accessories (aka: Deco)</fullName>
                <isActive>false</isActive>
                <label>Furniture/Accessories (aka: Deco)</label>
            </value>
            <value>
                <fullName>Hanging Sign</fullName>
                <isActive>false</isActive>
                <label>Hanging Sign</label>
            </value>
            <value>
                <fullName>I&amp;D</fullName>
                <isActive>false</isActive>
                <label>I&amp;D</label>
            </value>
            <value>
                <fullName>Labor</fullName>
                <isActive>false</isActive>
                <label>Labor</label>
            </value>
            <value>
                <fullName>RIGGING</fullName>
                <isActive>false</isActive>
                <label>RIGGING</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/LOB_Approver__c.field-meta.xml
<CustomField>
    <fullName>LOB_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LOB Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ICS_Location_City</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Max_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Amount__c</fullName>
    <label>Max - Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Min_Amount__c.field-meta.xml
<CustomField>
    <fullName>Min_Amount__c</fullName>
    <label>Min - Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E&amp;E (Trade Show)</fullName>
            </value>
            <value>
                <fullName>E&amp;E Logistics (Trade Show)</fullName>
            </value>
            <value>
                <fullName>E&amp;E(GBMS)</fullName>
            </value>
            <value>
                <fullName>Revenue Exhibitor</fullName>
            </value>
            <value>
                <fullName>Revenue Logistics</fullName>
            </value>
            <value>
                <fullName>Revenue Show Org</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Revenue Trade Show &amp; Logistics</fullName>
                <isActive>false</isActive>
                <label>Revenue Trade Show &amp; Logistics</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/Transaction_Types__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Types__c</fullName>
    <label>Transaction Types</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AR Adjustments</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>Credit Memo</fullName>
            </value>
            <value>
                <fullName>Payment Transfer</fullName>
            </value>
            <value>
                <fullName>Receipt Reversals</fullName>
            </value>
            <value>
                <fullName>Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ICS_AR_Adjustments_Approver_Update.cls
public class ICS_AR_Adjustments_Approver_Update {

    public static List<AR_Adjustments__c> AR_Adjustments_Approverdetails(List<AR_Adjustments__c> ARList){
        List<AR_Adjustments__c> AdjustmentList = ARList;
        
        system.debug('AdjustmentList==='+AdjustmentList.size());
        
         List<ICS_Approver_Matrix__c> CRMList = [select  Transaction_Types__c,Max_Amount__c, Min_Amount__c,location__c,
                                                LOB_Approver__c, F_R_Approver__c,    CSO_Approver__c,  LOB__c,
                                                AR1_Approver__c,AR2_Approver__c,Additional_Approver__c,Sales_Channel__c
                                                 from ICS_Approver_Matrix__c];
        
        Set<Id> approverIds = new Set<Id>();
        for(ICS_Approver_Matrix__c cr : CRMList){
            approverIds.add(cr.LOB_Approver__c);
            approverIds.add(cr.F_R_Approver__c); 
            approverIds.add(cr.AR1_Approver__c);
            approverIds.add(cr.CSO_Approver__c);
            approverIds.add(cr.AR2_Approver__c);
            
        }
        
        //system.debug('CRMList==='+CRMList);
        
        List<Employees__c> EmployeeList = [select id, Email_Address__c from Employees__c where id in :approverIds ];
        
       // system.debug('EmployeeList==='+EmployeeList);
        
        Map<Id, String> EmployeeIdEmailMap = new Map<Id, String>();
        for(Employees__c u : EmployeeList){
            EmployeeIdEmailMap.put(u.id, u.Email_Address__c);
            //system.debug(u.id+'==>'+u.Email_Address__c);
        }
        
        
            
        for(AR_Adjustments__c ar : AdjustmentList){
            system.debug('1st for loop');
            for(ICS_Approver_Matrix__c cr : CRMList){
                system.debug('2nd for loop');               
                if(cr.Transaction_Types__c == 'AR Adjustments'){
                    system.debug('1st if loop');    
                    if (ar.Case_location__c == cr.Location__c ){
                        system.debug('2nd if loop');
                        if(ar.Case_Sales_Channel__c == cr.Sales_Channel__c ){
                            system.debug('3rd if loop');
                           // if(ar.LOB__c == cr.LOB__c){
                                if(cr.Min_Amount__c == null){
                                    system.debug('4th if loop');
                                    if (ar.Amount__c <= cr.Max_Amount__c){
                                        system.debug('5th if loop');
                                        ar.DAM_LOB_Approver__c = cr.LOB_Approver__c;
                                        ar.DAM_Approver_Email_ID__c = EmployeeIdEmailMap.get(cr.LOB_Approver__c);
                                        ar.F_R_Approver__c = cr.F_R_Approver__c;
                                        ar.F_A_Approver_Email__c = EmployeeIdEmailMap.get(cr.F_R_Approver__c);
                                        ar.AR1_Approver_Name__c = cr.AR1_Approver__c;
                                        ar.AR1_Approver_Email__c = EmployeeIdEmailMap.get(cr.AR1_Approver__c);
                                        ar.CSO_Approver_Name__c = cr.CSO_Approver__c;
                                        ar.CSO_Approver_Email__c = EmployeeIdEmailMap.get(cr.CSO_Approver__c);  
                                        ar.AR2_Approver_Name__c = cr.AR2_Approver__c;
                                        ar.AR2_Approver_Email__c = EmployeeIdEmailMap.get(cr.AR2_Approver__c);
                                    }
                                }
                   
                                if(cr.Max_Amount__c == null){
                                    if (ar.Amount__c >= cr.Min_Amount__c){
                                        ar.DAM_LOB_Approver__c = cr.LOB_Approver__c;
                                        ar.DAM_Approver_Email_ID__c = EmployeeIdEmailMap.get(cr.LOB_Approver__c);
                                        ar.F_R_Approver__c = cr.F_R_Approver__c;
                                        ar.F_A_Approver_Email__c = EmployeeIdEmailMap.get(cr.F_R_Approver__c);
                                        ar.AR1_Approver_Name__c = cr.AR1_Approver__c;
                                        ar.AR1_Approver_Email__c = EmployeeIdEmailMap.get(cr.AR1_Approver__c);
                                        ar.CSO_Approver_Name__c = cr.CSO_Approver__c;
                                        ar.CSO_Approver_Email__c = EmployeeIdEmailMap.get(cr.CSO_Approver__c);
                                        ar.AR2_Approver_Name__c = cr.AR2_Approver__c;
                                        ar.AR2_Approver_Email__c = EmployeeIdEmailMap.get(cr.AR2_Approver__c);
                                    }
                                }
                            //}   
                        }                
                    }   
                             
                }
            }
        }
        system.debug('AdjustmentList==='+AdjustmentList);
        return AdjustmentList;
    } 
}