unpackaged/main/default/objects/AR_Adjustments__c/AR_Adjustments__c.object-meta.xml
<CustomObject>
    <label>AR Adjustments</label>
    <nameField>
        <displayFormat>ARA-{0000}</displayFormat>
        <label>AR_Adjustments_No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR1_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Email__c</fullName>
    <label>AR1 Approver Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR1_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments7</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR2_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver_Email__c</fullName>
    <label>AR2 Approver Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/AR2_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments8</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/CSO_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>AR Adjustments (CSO Approver Name)</relationshipLabel>
    <relationshipName>AR_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/DAM_Approver_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>DAM_Approver_Email_ID__c</fullName>
    <label>DAM Approver Email ID</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/DAM_Approver_Status__c.field-meta.xml
<CustomField>
    <fullName>DAM_Approver_Status__c</fullName>
    <label>DAM Approver Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/DAM_LOB_Approver__c.field-meta.xml
<CustomField>
    <fullName>DAM_LOB_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DAM/LOB Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/Del_DAM_LOB_Approver__c.field-meta.xml
<CustomField>
    <fullName>Del_DAM_LOB_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Del_DAM/LOB Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments9</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/F_A_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>F_A_Approver_Email__c</fullName>
    <label>F&amp;A Approver Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/AR_Adjustments__c/fields/F_R_Approver__c.field-meta.xml
<CustomField>
    <fullName>F_R_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>F&amp;R Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>AR_Adjustments6</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/Credit_Memo_ICS__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM - {00000}</displayFormat>
        <label>Credit_Memo No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/AR1_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>Credit_Memo_ICS4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/AR2_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>Credit_Memo_ICS3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/CSO_Approver_Email__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver_Email__c</fullName>
    <label>CSO Approver Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Credit_Memo_ICS__c/fields/CSO_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Credit Memo (CSO Approver Name)</relationshipLabel>
    <relationshipName>Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/Customer_Service_Inquiries_ICS__c.object-meta.xml
<CustomObject>
    <label>ICS Cases</label>
    <nameField>
        <displayFormat>ICS {000000}</displayFormat>
        <label>CSI ICS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICS Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Case_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Approval_Status__c</fullName>
    <label>Case Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Case Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Case Open</fullName>
                <default>true</default>
                <label>Case Open</label>
            </value>
            <value>
                <fullName>Requestor Submitted</fullName>
            </value>
            <value>
                <fullName>Requestor Approved</fullName>
            </value>
            <value>
                <fullName>Requestor Rejected</fullName>
            </value>
            <value>
                <fullName>LOB Open</fullName>
            </value>
            <value>
                <fullName>LOB Submitted</fullName>
            </value>
            <value>
                <fullName>LOB Approved</fullName>
            </value>
            <value>
                <fullName>LOB Rejected</fullName>
            </value>
            <value>
                <fullName>F&amp;R Open</fullName>
            </value>
            <value>
                <fullName>F&amp;R Submitted</fullName>
            </value>
            <value>
                <fullName>F&amp;R Approved</fullName>
            </value>
            <value>
                <fullName>F&amp;R Rejected</fullName>
            </value>
            <value>
                <fullName>AR1 Open</fullName>
            </value>
            <value>
                <fullName>AR1 Submitted</fullName>
            </value>
            <value>
                <fullName>AR1 Approved</fullName>
            </value>
            <value>
                <fullName>AR1 Rejected</fullName>
            </value>
            <value>
                <fullName>CSO Open</fullName>
            </value>
            <value>
                <fullName>CSO Submitted</fullName>
            </value>
            <value>
                <fullName>CSO Approved</fullName>
            </value>
            <value>
                <fullName>CSO Rejected</fullName>
            </value>
            <value>
                <fullName>AR2 Open</fullName>
            </value>
            <value>
                <fullName>AR2 Submitted</fullName>
            </value>
            <value>
                <fullName>AR2 Approved</fullName>
            </value>
            <value>
                <fullName>AR2 Rejected</fullName>
            </value>
            <value>
                <fullName>Additional Open</fullName>
            </value>
            <value>
                <fullName>Additional Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Case_Requestor__c.field-meta.xml
<CustomField>
    <fullName>Case_Requestor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case Requestor</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>CSI_ICS</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Show Occurrence</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Customer_Service_Inquiries_ICS</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Service_Inquiries_ICS__c/fields/Requestor_Apporval_Required__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Apporval_Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Case Requestor Apporval Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/ICS_Approver_Matrix__c.object-meta.xml
<CustomObject>
    <label>ICS Approver Matrix</label>
    <nameField>
        <displayFormat>ICS_AM-{00000}</displayFormat>
        <label>ICS Approver Matrix N0</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICS Approver Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ICS_Approver_Matrix__c/fields/F_R_Approver__c.field-meta.xml
<CustomField>
    <fullName>F_R_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>F&amp;R Approver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>ICS Approver Matrix (F&amp;R Approver)</relationshipLabel>
    <relationshipName>ICS_Approver_Matrix1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/Refunds_ICS__c.object-meta.xml
<CustomObject>
    <label>Refunds</label>
    <nameField>
        <displayFormat>Refunds-{00000}</displayFormat>
        <label>Refunds ICS No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Refunds_ICS__c/fields/AR1_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR1_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR1 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>Refunds_ICS1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/fields/AR2_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>AR2_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AR2 Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>Refunds_ICS2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Refunds_ICS__c/fields/CSO_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>CSO_Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO Approver Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Refunds (CSO Approver Name)</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CaseSubmitForApprovalTest.cls
@isTest(SeeAllData=false)
public class CaseSubmitForApprovalTest {
    
    //setting up test data
    @testSetup
    static void setup(){
        //Test.startTest();
        //Account facility=TestDataUtil.CreateTestFacility();
        //Account firm=TestDataUtil.CreateTestFirm();
        //Show__c show=TestDataUtil.CreateTestShow(firm.id);
        
        List<Employees__c> listEmp = new List<Employees__c>();
        Employees__c emp = TestDataUtil.createTestEmployee();
        Employees__c emp1 = TestDataUtil.createTestEmployee();
        emp.Email_Address__c='test1@test1.com';
        emp1.Email_Address__c='test1@test1.com';
        listEmp.add(emp);
        listEmp.add(emp1);
        insert listEmp;
        
        
        ICS_Approver_Matrix__c approverMatrix = TestDataUtil.createTestApproverMatrix(listEmp[0].id);
        insert approverMatrix;
        
        List<Customer_Service_Inquiries_ICS__c> listICS = new List<Customer_Service_Inquiries_ICS__c>();
        Customer_Service_Inquiries_ICS__c ICS = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS.Case_Requestor__c = listEmp[0].Id;
        ICS.Case_Approval_Status__c = 'Case Open' ;
        ICS.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS);
        //insert ICS;
        
        Customer_Service_Inquiries_ICS__c ICS1 = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS1.Case_Requestor__c = listEmp[0].Id;
        ICS1.Case_Approval_Status__c = 'Case Open' ;
        ICS1.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS1);
        
        Customer_Service_Inquiries_ICS__c ICS2 = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS2.Case_Requestor__c = listEmp[0].Id;
        ICS2.Case_Approval_Status__c = 'F&R Open' ;
        //ICS1.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS2);
        
        Customer_Service_Inquiries_ICS__c ICS3 = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS3.Case_Requestor__c = listEmp[0].Id;
        ICS3.Case_Approval_Status__c = 'F&R Open' ;
        //ICS1.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS3);
        
        Customer_Service_Inquiries_ICS__c ICS4 = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS4.Case_Requestor__c = listEmp[0].Id;
        ICS4.Case_Approval_Status__c = 'AR1 Open' ;
        //ICS1.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS4);
        
        Customer_Service_Inquiries_ICS__c ICS5 = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS5.Case_Requestor__c = listEmp[0].Id;
        ICS5.Case_Approval_Status__c = 'AR1 Open' ;
        //ICS1.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS5);
        
        Customer_Service_Inquiries_ICS__c ICS6 = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS6.Case_Requestor__c = listEmp[0].Id;
        ICS6.Case_Approval_Status__c = 'CSO Open' ;
        //ICS1.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS6);
        
        Customer_Service_Inquiries_ICS__c ICS7 = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS7.Case_Requestor__c = listEmp[0].Id;
        ICS7.Case_Approval_Status__c = 'CSO Open' ;
        //ICS1.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS7);
        
        Customer_Service_Inquiries_ICS__c ICS8 = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS8.Case_Requestor__c = listEmp[0].Id;
        ICS8.Case_Approval_Status__c = 'AR2 Open' ;
        //ICS1.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS8);
        
        Customer_Service_Inquiries_ICS__c ICS9 = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS9.Case_Requestor__c = listEmp[0].Id;
        ICS9.Case_Approval_Status__c = 'AR2 Open' ;
        //ICS1.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS9);
        
        Customer_Service_Inquiries_ICS__c ICS10 = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS10.Case_Requestor__c = listEmp[0].Id;
        ICS10.Case_Approval_Status__c = 'Additional Open' ;
        //ICS1.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS10);
        
        Customer_Service_Inquiries_ICS__c ICS11 = TestDataUtil.createTestCustomerServiceInquries();
        //ics.Opportunity_Name__c = 'ASDLVA-201708-LVCC';
        ICS11.Case_Requestor__c = listEmp[0].Id;
        ICS11.Case_Approval_Status__c = 'Additional Open' ;
        //ICS1.Requestor_Apporval_Required__c = true; 
        listICS.add(ICS11);
        
        insert listICS;
        
        //for commented code -- goto ==>Commented Line - Part 1       
    }
    
    
    @isTest
    public static void  testMethod1() { 
        List<Customer_Service_Inquiries_ICS__c> testRecordICS= [select Id, Case_Approval_Status__c, Name, Requestor_Apporval_Required__c from Customer_Service_Inquiries_ICS__c]; 
        List<Employees__c> listEmp = [select Email_Address__c from Employees__c];
        List<AR_Adjustments__c> arAdjList = new List<AR_Adjustments__c>();
        AR_Adjustments__c arAdj = TestDataUtil.createTestARAdjustment(testRecordICS[0].Id);
        arAdj.DAM_LOB_Approver__c = listEmp[0].Id;
        arAdj.DAM_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        arAdj.F_R_Approver__c = listEmp[0].Id;
        arAdj.F_A_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.AR1_Approver_Name__c = listEmp[0].Id;
        arAdj.AR1_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.CSO_Approver_Name__c = listEmp[0].Id;
        arAdj.CSO_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.AR2_Approver_Name__c = listEmp[0].Id;
        arAdj.AR2_Approver_Email__c = listEmp[0].Email_Address__c; 
        //arAdj.DAM_Approver_Status__c = 'Approved';
         
        
        AR_Adjustments__c arAdj1 = TestDataUtil.createTestARAdjustment(testRecordICS[1].Id);
        arAdj1.DAM_LOB_Approver__c = listEmp[0].Id;
        arAdj1.DAM_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        arAdj1.F_R_Approver__c = listEmp[0].Id;
        arAdj1.F_A_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.AR1_Approver_Name__c = listEmp[0].Id;
        arAdj1.AR1_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.CSO_Approver_Name__c = listEmp[0].Id;
        arAdj1.CSO_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.AR2_Approver_Name__c = listEmp[0].Id;
        arAdj1.AR2_Approver_Email__c = listEmp[0].Email_Address__c; 
        arAdj1.Del_DAM_LOB_Approver__c = listEmp[0].Id;
        arAdjList.add(arAdj);
        arAdjList.add(arAdj1);
        insert arAdjList;
          
        ICS_Approver_Matrix__c approverMatrix = TestDataUtil.createTestApproverMatrix(listEmp[0].id);
        insert approverMatrix;
        List<Credit_Memo_ICS__c> creditMemoList = new List<Credit_Memo_ICS__c>();
        Credit_Memo_ICS__c creditMemo = TestDataUtil.createTestCreditMemo(testRecordICS[0].Id); 
        creditMemo.Sales_Channel__c='E&E (Trade Show)';
        creditMemo.Amount_w_psp__c = 0;
        creditMemo.Tax_Amount__c = 0;
        creditMemoList.add(creditMemo);
        
        Credit_Memo_ICS__c creditMemo1 = TestDataUtil.createTestCreditMemo(testRecordICS[1].Id); 
        creditMemo1.Del_LOB_Approver__c = listEmp[0].Id;
        creditMemo1.Sales_Channel__c='E&E (Trade Show)';
        creditMemoList.add(creditMemo1);
        INSERT creditMemoList;  
        
        //Charges__c  Charges = TestDataUtil.createTestCharges(testRecordICS[0].Id);
        //insert Charges; 
        system.debug('creditMemoList==='+creditMemoList[0].LOB_Approver_Email_ID__c);
        
        system.debug('Test Record Is --> '+testRecordICS);
        
        CaseSubmitForApproval.generateEmail(testRecordICS[0].Id);
        
        testRecordICS[0].Requestor_Apporval_Required__c = false;
        testRecordICS[1].Requestor_Apporval_Required__c = false;
        update testRecordICS;
        test.startTest();
        system.debug('Credit_Memo_ICS__c==='+[select LOB_Approver_Email_ID__c from Credit_Memo_ICS__c where id=: creditMemoList[0].Id]);
        CaseSubmitForApproval.generateEmail(testRecordICS[0].Id);
        
        CaseSubmitForApproval.generateEmail(testRecordICS[1].Id);
        test.stopTest();
        
        //for commented code -- goto ==>Commented Line - Part 2
    }
    
    @isTest
    public static void testMethod2() { 
        List<Customer_Service_Inquiries_ICS__c> testRecordICS= [select Id, Case_Approval_Status__c, Name, Requestor_Apporval_Required__c from Customer_Service_Inquiries_ICS__c where Case_Approval_Status__c=:'F&R Open']; 
        List<Employees__c> listEmp = [select Email_Address__c from Employees__c];
        List<AR_Adjustments__c> arAdjList = new List<AR_Adjustments__c>();
        AR_Adjustments__c arAdj = TestDataUtil.createTestARAdjustment(testRecordICS[0].Id);
        arAdj.DAM_LOB_Approver__c = listEmp[0].Id;
        arAdj.DAM_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        arAdj.F_R_Approver__c = listEmp[0].Id;
        arAdj.F_A_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.AR1_Approver_Name__c = listEmp[0].Id;
        arAdj.AR1_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.CSO_Approver_Name__c = listEmp[0].Id;
        arAdj.CSO_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.AR2_Approver_Name__c = listEmp[0].Id;
        arAdj.AR2_Approver_Email__c = listEmp[0].Email_Address__c; 
        //arAdj.DAM_Approver_Status__c = 'Approved';
         
        
        AR_Adjustments__c arAdj1 = TestDataUtil.createTestARAdjustment(testRecordICS[1].Id);
        arAdj1.DAM_LOB_Approver__c = listEmp[0].Id;
        arAdj1.DAM_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        arAdj1.F_R_Approver__c = listEmp[0].Id;
        arAdj1.F_A_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.AR1_Approver_Name__c = listEmp[0].Id;
        arAdj1.AR1_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.CSO_Approver_Name__c = listEmp[0].Id;
        arAdj1.CSO_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.AR2_Approver_Name__c = listEmp[0].Id;
        arAdj1.AR2_Approver_Email__c = listEmp[0].Email_Address__c; 
        arAdj1.Del_F_R_Approver__c = listEmp[0].Id;
        arAdjList.add(arAdj);
        arAdjList.add(arAdj1);
        insert arAdjList;
        
        ICS_Approver_Matrix__c approverMatrix = TestDataUtil.createTestApproverMatrix(listEmp[0].id);
        insert approverMatrix;
        List<Credit_Memo_ICS__c> creditMemoList = new List<Credit_Memo_ICS__c>();
        Credit_Memo_ICS__c creditMemo = TestDataUtil.createTestCreditMemo(testRecordICS[0].Id); 
        creditMemo.Sales_Channel__c='E&E (Trade Show)';
        creditMemo.Amount_w_psp__c = 0;
        creditMemo.Tax_Amount__c = 0;
        creditMemoList.add(creditMemo);
        
        Credit_Memo_ICS__c creditMemo1 = TestDataUtil.createTestCreditMemo(testRecordICS[1].Id); 
        creditMemo1.Del_F_R_Approver__c = listEmp[0].Id;
        creditMemo1.Sales_Channel__c='E&E (Trade Show)';
        creditMemoList.add(creditMemo1);
        INSERT creditMemoList;  
        
        system.debug('Test Record Is --> '+testRecordICS);
        
        CaseSubmitForApproval.generateEmail(testRecordICS[0].Id);
        test.startTest();
        CaseSubmitForApproval.generateEmail(testRecordICS[1].Id);
        test.stopTest();
        
        //for commented code -- goto ==>Commented Line - Part 2
    }
    
    @isTest
    public static void testMethod3() { 
        List<Customer_Service_Inquiries_ICS__c> testRecordICS= [select Id, Case_Approval_Status__c, Name, Requestor_Apporval_Required__c from Customer_Service_Inquiries_ICS__c where Case_Approval_Status__c=:'AR1 Open']; 
        List<Employees__c> listEmp = [select Email_Address__c from Employees__c];
        List<AR_Adjustments__c> arAdjList = new List<AR_Adjustments__c>();
        AR_Adjustments__c arAdj = TestDataUtil.createTestARAdjustment(testRecordICS[0].Id);
        arAdj.DAM_LOB_Approver__c = listEmp[0].Id;
        arAdj.DAM_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        arAdj.F_R_Approver__c = listEmp[0].Id;
        arAdj.F_A_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.AR1_Approver_Name__c = listEmp[0].Id;
        arAdj.AR1_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.CSO_Approver_Name__c = listEmp[0].Id;
        arAdj.CSO_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.AR2_Approver_Name__c = listEmp[0].Id;
        arAdj.AR2_Approver_Email__c = listEmp[0].Email_Address__c; 
        //arAdj.DAM_Approver_Status__c = 'Approved';
         
        
        AR_Adjustments__c arAdj1 = TestDataUtil.createTestARAdjustment(testRecordICS[1].Id);
        arAdj1.DAM_LOB_Approver__c = listEmp[0].Id;
        arAdj1.DAM_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        arAdj1.F_R_Approver__c = listEmp[0].Id;
        arAdj1.F_A_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.AR1_Approver_Name__c = listEmp[0].Id;
        arAdj1.AR1_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.CSO_Approver_Name__c = listEmp[0].Id;
        arAdj1.CSO_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.AR2_Approver_Name__c = listEmp[0].Id;
        arAdj1.AR2_Approver_Email__c = listEmp[0].Email_Address__c; 
        arAdj1.Del_AR1_Approver__c = listEmp[0].Id;
        arAdjList.add(arAdj);
        arAdjList.add(arAdj1);
        insert arAdjList;
        
        ICS_Approver_Matrix__c approverMatrix = TestDataUtil.createTestApproverMatrix(listEmp[0].id);
        insert approverMatrix;
        List<Credit_Memo_ICS__c> creditMemoList = new List<Credit_Memo_ICS__c>();
        Credit_Memo_ICS__c creditMemo = TestDataUtil.createTestCreditMemo(testRecordICS[0].Id); 
        creditMemo.Sales_Channel__c='E&E (Trade Show)';
        creditMemo.Amount_w_psp__c = 0;
        creditMemo.Tax_Amount__c = 0;
        creditMemoList.add(creditMemo);
        
        Credit_Memo_ICS__c creditMemo1 = TestDataUtil.createTestCreditMemo(testRecordICS[1].Id); 
        creditMemo1.Del_AR1_Approver__c = listEmp[0].Id;
        creditMemo1.Sales_Channel__c='E&E (Trade Show)';
        creditMemoList.add(creditMemo1);
        INSERT creditMemoList;
        
        system.debug('Test Record Is --> '+testRecordICS);
        
        List<Refunds_ICS__c> refundList = new  List<Refunds_ICS__c>();
        Refunds_ICS__c refund = TestDataUtil.createTestRefund(testRecordICS[0].Id);
        refund.AR1_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        refundList.add(refund);
        
        Refunds_ICS__c refund1 = TestDataUtil.createTestRefund(testRecordICS[1].Id);
        refund1.Del_AR1_Approver__c = listEmp[0].Id;
        refund1.Del_CSO_Approver__c = listEmp[0].Id;
        refund1.Del_AR2_Approver__c = listEmp[0].Id;
        refundList.add(refund1);
        insert refundList;
        
        test.startTest();
        CaseSubmitForApproval.generateEmail(testRecordICS[0].Id);
        CaseSubmitForApproval.generateEmail(testRecordICS[1].Id);
        test.stopTest();
        
        //for commented code -- goto ==>Commented Line - Part 2
    }
    
    @isTest
    public static void testMethod4() { 
        List<Customer_Service_Inquiries_ICS__c> testRecordICS= [select Id, Case_Approval_Status__c, Name, Requestor_Apporval_Required__c from Customer_Service_Inquiries_ICS__c where Case_Approval_Status__c=:'CSO Open']; 
        List<Employees__c> listEmp = [select Email_Address__c from Employees__c];
        List<AR_Adjustments__c> arAdjList = new List<AR_Adjustments__c>();
        AR_Adjustments__c arAdj = TestDataUtil.createTestARAdjustment(testRecordICS[0].Id);
        arAdj.DAM_LOB_Approver__c = listEmp[0].Id;
        arAdj.DAM_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        arAdj.F_R_Approver__c = listEmp[0].Id;
        arAdj.F_A_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.AR1_Approver_Name__c = listEmp[0].Id;
        arAdj.AR1_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.CSO_Approver_Name__c = listEmp[0].Id;
        arAdj.CSO_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.AR2_Approver_Name__c = listEmp[0].Id;
        arAdj.AR2_Approver_Email__c = listEmp[0].Email_Address__c; 
        //arAdj.DAM_Approver_Status__c = 'Approved';
         
        
        AR_Adjustments__c arAdj1 = TestDataUtil.createTestARAdjustment(testRecordICS[1].Id);
        arAdj1.DAM_LOB_Approver__c = listEmp[0].Id;
        arAdj1.DAM_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        arAdj1.F_R_Approver__c = listEmp[0].Id;
        arAdj1.F_A_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.AR1_Approver_Name__c = listEmp[0].Id;
        arAdj1.AR1_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.CSO_Approver_Name__c = listEmp[0].Id;
        arAdj1.CSO_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.AR2_Approver_Name__c = listEmp[0].Id;
        arAdj1.AR2_Approver_Email__c = listEmp[0].Email_Address__c; 
        arAdj1.Del_CSO_Approver__c = listEmp[0].Id;
        arAdjList.add(arAdj);
        arAdjList.add(arAdj1);
        insert arAdjList;
        
        ICS_Approver_Matrix__c approverMatrix = TestDataUtil.createTestApproverMatrix(listEmp[0].id);
        insert approverMatrix;
        List<Credit_Memo_ICS__c> creditMemoList = new List<Credit_Memo_ICS__c>();
        Credit_Memo_ICS__c creditMemo = TestDataUtil.createTestCreditMemo(testRecordICS[0].Id); 
        creditMemo.Sales_Channel__c='E&E (Trade Show)';
        creditMemo.Amount_w_psp__c = 0;
        creditMemo.Tax_Amount__c = 0;
        creditMemoList.add(creditMemo);
        
        Credit_Memo_ICS__c creditMemo1 = TestDataUtil.createTestCreditMemo(testRecordICS[1].Id); 
        creditMemo1.Del_CSO_Approver__c = listEmp[0].Id;
        creditMemo1.Sales_Channel__c='E&E (Trade Show)';
        creditMemoList.add(creditMemo1);
        INSERT creditMemoList;
        
        List<Refunds_ICS__c> refundList = new  List<Refunds_ICS__c>();
        Refunds_ICS__c refund = TestDataUtil.createTestRefund(testRecordICS[0].Id);
       // refund.CSO_Approver_Email__c = listEmp[0].Email_Address__c;
        refundList.add(refund);
        
        Refunds_ICS__c refund1 = TestDataUtil.createTestRefund(testRecordICS[1].Id);
        refund1.Del_AR1_Approver__c = listEmp[0].Id;
        refund1.Del_CSO_Approver__c = listEmp[0].Id;
        refund1.Del_AR2_Approver__c = listEmp[0].Id;
        refundList.add(refund1);
        insert refundList;
        
        system.debug('Test Record Is --> '+testRecordICS);
        
        
        test.startTest();
        CaseSubmitForApproval.generateEmail(testRecordICS[0].Id);
        CaseSubmitForApproval.generateEmail(testRecordICS[1].Id);
        test.stopTest();
        
        //for commented code -- goto ==>Commented Line - Part 2
    }
    
    @isTest
    public static void testMethod5() { 
        List<Customer_Service_Inquiries_ICS__c> testRecordICS= [select Id, Case_Approval_Status__c, Name, Requestor_Apporval_Required__c from Customer_Service_Inquiries_ICS__c where Case_Approval_Status__c=:'AR2 Open']; 
        List<Employees__c> listEmp = [select Email_Address__c from Employees__c];
        List<AR_Adjustments__c> arAdjList = new List<AR_Adjustments__c>();
        AR_Adjustments__c arAdj = TestDataUtil.createTestARAdjustment(testRecordICS[0].Id);
        arAdj.DAM_LOB_Approver__c = listEmp[0].Id;
        arAdj.DAM_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        arAdj.F_R_Approver__c = listEmp[0].Id;
        arAdj.F_A_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.AR1_Approver_Name__c = listEmp[0].Id;
        arAdj.AR1_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.CSO_Approver_Name__c = listEmp[0].Id;
        arAdj.CSO_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj.AR2_Approver_Name__c = listEmp[0].Id;
        arAdj.AR2_Approver_Email__c = listEmp[0].Email_Address__c; 
        //arAdj.DAM_Approver_Status__c = 'Approved';
         
        
        AR_Adjustments__c arAdj1 = TestDataUtil.createTestARAdjustment(testRecordICS[1].Id);
        arAdj1.DAM_LOB_Approver__c = listEmp[0].Id;
        arAdj1.DAM_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        arAdj1.F_R_Approver__c = listEmp[0].Id;
        arAdj1.F_A_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.AR1_Approver_Name__c = listEmp[0].Id;
        arAdj1.AR1_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.CSO_Approver_Name__c = listEmp[0].Id;
        arAdj1.CSO_Approver_Email__c = listEmp[0].Email_Address__c;
        arAdj1.AR2_Approver_Name__c = listEmp[0].Id;
        arAdj1.AR2_Approver_Email__c = listEmp[0].Email_Address__c; 
        arAdj1.Del_AR2_Approver__c = listEmp[0].Id;
        arAdjList.add(arAdj);
        arAdjList.add(arAdj1);
        insert arAdjList;
        
        ICS_Approver_Matrix__c approverMatrix = TestDataUtil.createTestApproverMatrix(listEmp[0].id);
        insert approverMatrix;
        List<Credit_Memo_ICS__c> creditMemoList = new List<Credit_Memo_ICS__c>();
        Credit_Memo_ICS__c creditMemo = TestDataUtil.createTestCreditMemo(testRecordICS[0].Id); 
        creditMemo.Sales_Channel__c='E&E (Trade Show)';
        creditMemo.Amount_w_psp__c = 0;
        creditMemo.Tax_Amount__c = 0;
        creditMemoList.add(creditMemo);
        
        Credit_Memo_ICS__c creditMemo1 = TestDataUtil.createTestCreditMemo(testRecordICS[1].Id); 
        creditMemo1.Del_AR2_Approver__c = listEmp[0].Id;
        creditMemo1.Sales_Channel__c='E&E (Trade Show)';
        creditMemoList.add(creditMemo1);
        INSERT creditMemoList;
        
        List<Refunds_ICS__c> refundList = new  List<Refunds_ICS__c>();
        Refunds_ICS__c refund = TestDataUtil.createTestRefund(testRecordICS[0].Id);
        refund.AR2_Approver_Email_ID__c = listEmp[0].Email_Address__c;
        refundList.add(refund);
        
        Refunds_ICS__c refund1 = TestDataUtil.createTestRefund(testRecordICS[1].Id);
        refund1.Del_AR2_Approver__c = listEmp[0].Id;
        refundList.add(refund1);
        insert refundList;
        
        system.debug('Test Record Is --> '+testRecordICS);
        
        test.startTest();
        CaseSubmitForApproval.generateEmail(testRecordICS[0].Id);
        CaseSubmitForApproval.generateEmail(testRecordICS[1].Id);
        test.stopTest();
        
        //for commented code -- goto ==>Commented Line - Part 2
    }
    
    @isTest
    public static void testMethod6() { 
        List<Customer_Service_Inquiries_ICS__c> testRecordICS= [select Id, Case_Approval_Status__c, Name, Requestor_Apporval_Required__c from Customer_Service_Inquiries_ICS__c where Case_Approval_Status__c = 'Case Open']; 
        List<Employees__c> listEmp = [select Email_Address__c from Employees__c];
        
        Charges__c  Charges = TestDataUtil.createTestCharges(testRecordICS[0].Id);
        insert Charges; 
        
        Payment_Transfer_ICS__c Payment = TestDataUtil.createTestPaymentTransfer(testRecordICS[0].Id);
         insert Payment; 
         
        
        List<Receipt_Reversals__c> receiptReversalList = new List<Receipt_Reversals__c>();
        Receipt_Reversals__c receiptReversal = TestDataUtil.createTestReceiptReversal(testRecordICS[0].Id);
        receiptReversal.Additional_Approver_Name__c = listEmp[0].Id;
        receiptReversal.Del_Additional_Approver__c = listEmp[0].Id;
       // receiptReversal.Del_Additional_Approver_Email__c = 'as@slkgroup.com';
        receiptReversalList.add(receiptReversal);       
        insert receiptReversalList; 
        
        List<Refunds_ICS__c> refundList = new  List<Refunds_ICS__c>();
        Refunds_ICS__c refund = TestDataUtil.createTestRefund(testRecordICS[0].Id);
         refund.Del_AR1_Approver__c = listEmp[0].Id;
        refund.Del_CSO_Approver__c = listEmp[0].Id;
        refund.Del_AR2_Approver__c = listEmp[0].Id;
        refundList.add(refund);
        insert refundList;
        
        Attachment attach=new Attachment();     
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=refundList[0].id;
        insert attach;
        
        test.startTest();

        CaseSubmitForApproval.generateEmail(testRecordICS[0].Id);
        test.stopTest();
        
        //for commented code -- goto ==>Commented Line - Part 2
    }
    
    @isTest
    public static void testMethod7() { 
        List<Customer_Service_Inquiries_ICS__c> testRecordICS= [select Id, Case_Approval_Status__c, Name, Requestor_Apporval_Required__c from Customer_Service_Inquiries_ICS__c where Case_Approval_Status__c = 'Additional Open']; 
        List<Employees__c> listEmp = [select Email_Address__c from Employees__c];
        List<Receipt_Reversals__c> receiptReversalList = new List<Receipt_Reversals__c>();
        
        ICS_Approver_Matrix__c approverMatrix = TestDataUtil.createTestApproverMatrix(listEmp[0].id);
        insert approverMatrix;
        List<Credit_Memo_ICS__c> creditMemoList = new List<Credit_Memo_ICS__c>();
        Credit_Memo_ICS__c creditMemo = TestDataUtil.createTestCreditMemo(testRecordICS[0].Id); 
        creditMemo.Sales_Channel__c='E&E (Trade Show)';
        creditMemo.Amount_w_psp__c = 0;
        creditMemo.Tax_Amount__c = 0;
        creditMemoList.add(creditMemo);
        
        Credit_Memo_ICS__c creditMemo1 = TestDataUtil.createTestCreditMemo(testRecordICS[1].Id); 
        creditMemo1.Del_Additional_Approver__c = listEmp[0].Id;
        creditMemo1.Sales_Channel__c='E&E (Trade Show)';
        creditMemoList.add(creditMemo1);
        INSERT creditMemoList;
        
        Receipt_Reversals__c receiptReversal1 = TestDataUtil.createTestReceiptReversal(testRecordICS[0].Id);
        //receiptReversal1.Additional_Approver_Name__c = listEmp[0].Id;
        receiptReversal1.Del_Additional_Approver__c = listEmp[0].Id;
       // receiptReversal.Del_Additional_Approver_Email__c = 'as@slkgroup.com';
        receiptReversalList.add(receiptReversal1);
        
        Receipt_Reversals__c receiptReversal2 = TestDataUtil.createTestReceiptReversal(testRecordICS[1].Id);
        receiptReversal2.Additional_Approver_Name__c = listEmp[0].Id;
        receiptReversalList.add(receiptReversal2);
        
        insert receiptReversalList; 
        test.startTest();
        
        Attachment attach=new Attachment();     
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=creditMemoList[0].id;
        insert attach;
        
        CaseSubmitForApproval.generateEmail(testRecordICS[0].Id);
        CaseSubmitForApproval.generateEmail(testRecordICS[1].Id);
        test.stopTest();
        
        //for commented code -- goto ==>Commented Line - Part 2
    }
}