unpackaged/main/default/objects/Activity_Log_ACCC__c/Activity_Log_ACCC__c.object-meta.xml
<CustomObject>
    <label>Activity Log ACCC</label>
    <nameField>
        <displayFormat>ACCC-{0000}</displayFormat>
        <label>Activity Log ACCC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Logs ACCC</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Activity_Log_ACCC__c/fields/Booth_ID__c.field-meta.xml
<CustomField>
    <fullName>Booth_ID__c</fullName>
    <label>Booth ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Activity_Log_ACCC__c/fields/Customer_Service_Inquiry_Case__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Inquiry_Case__c</fullName>
    <label>Customer Service Inquiry (Case)</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activity Logs ACCC</relationshipLabel>
    <relationshipName>Activity_Logs_ACCC</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Log_ACCC__c/fields/Mail_has_been_Sent_on_Requesting_CC__c.field-meta.xml
<CustomField>
    <fullName>Mail_has_been_Sent_on_Requesting_CC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mail has been Sent on Requesting CC</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Activity_Log_ACCC__c/fields/Payment_ID_Info__c.field-meta.xml
<CustomField>
    <fullName>Payment_ID_Info__c</fullName>
    <label>Payment ID Info</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Activity_Log_ACCC__c/fields/Session_ID_info__c.field-meta.xml
<CustomField>
    <fullName>Session_ID_info__c</fullName>
    <label>Session ID info</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Booth__c.field-meta.xml
<CustomField>
    <fullName>Booth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booth on which user requested service</description>
    <label>Booth (Lookup)</label>
    <referenceTo>Oracle_Show_Booth__c</referenceTo>
    <relationshipLabel>Customer Service Inquiries (Cases)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Show_Name__c.field-meta.xml
<CustomField>
    <fullName>Show_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Show Name</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Oracle_Show_Booth__c/Oracle_Show_Booth__c.object-meta.xml
<CustomObject>
    <description>Show Occurrence Booths from Oracle</description>
    <label>Booth</label>
    <nameField>
        <label>Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booths</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Oracle_Show_Booth__c/fields/BOOTH_ID__c.field-meta.xml
<CustomField>
    <fullName>BOOTH_ID__c</fullName>
    <description>Unique ID of Oracle Booth record</description>
    <label>BOOTH_ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <description>A custom object that defines the details about a trade show.</description>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ACCC_SendEmail.cls
global class ACCC_SendEmail{
    webservice static string sendMinimalPaymentMail(Id caseId) {
        Case caseRec = [select Booth__r.BOOTH_ID__c, ContactEmail,Contact.Name,Show_Name__r.Name, Account.Name from Case where Id =: caseId];
        //Contact C = [select Contact.Name from Contact where ID =: caseId];
        String ApplicationID = System.Label.GC_Label_AppID;//'SalesForce';    //change to custom label
        String ApplicationKey = System.Label.GC_Label_AppKey;//'76v.H-_7};9^+4(]J.;3';    //change to custom label
        String companyId= '';
        String languageId= '';
        String boothId = caseRec.Booth__r.BOOTH_ID__c;
        string resultFlag;
        try{
            //Added isRunningTest to skip session code for test class by Sajid 06/02/2023 SFDC-229 SFDC+Twilio ACCC Button on Lightning Page for text reps (ME# 331277)
            ACCC_wwwViadComSecurityV2.AppSessionInfo responseAppSessionInfo = new ACCC_wwwViadComSecurityV2.AppSessionInfo();
            String response_x;
            if(!Test.isRunningTest()){
                ACCC_wwwViadComSecurityV2.BasicHttpBinding_IAuthenticationService appSecurity = new ACCC_wwwViadComSecurityV2.BasicHttpBinding_IAuthenticationService();
                responseAppSessionInfo = appSecurity.StartAppSession(ApplicationID,  ApplicationKey, companyId, languageId);
                system.debug('SessionID==='+responseAppSessionInfo.SessionID);
                system.debug('boothId==='+boothId);
                system.debug('caseRec.Contact.Name==='+caseRec.Contact.Name);
                system.debug('caseRec.Account.Name==='+caseRec.Account.Name);
                system.debug('caseRec.ContactEmail==='+caseRec.ContactEmail);
                system.debug('caseRec.Show_Name__r.name==='+caseRec.Show_Name__r.name);
                ACCC1_wwwViadComV1.BasicHttpBinding_IPaymentCollectionService v1accp = new ACCC1_wwwViadComV1.BasicHttpBinding_IPaymentCollectionService();
                response_x = v1accp.RequestPaymentCollection(responseAppSessionInfo.SessionID,boothId, caseRec.Contact.Name,caseRec.Account.Name,String.valueOf(caseRec.ContactEmail),0.00,caseRec.Show_Name__r.name,'','','');
            }
            system.debug('response_x==='+response_x);
            Activity_Log_ACCC__c varACCC= new Activity_Log_ACCC__c();
            varACCC.Customer_Service_Inquiry_Case__c = caseRec.Id;
            varACCC.Payment_ID_Info__c = +response_x;
            varACCC.Session_ID_info__c= +responseAppSessionInfo.SessionID;
            insert varACCC;
            varACCC.Mail_has_been_Sent_on_Requesting_CC__c = true;
            varACCC.Subject__c = 'Your GES Payment Information - '+caseRec.ContactEmail;
            varACCC.Booth_ID__c= '01000';               
            Update varACCC; 
            resultFlag= 'true';
        }catch(exception e){
            system.debug('error at==='+e.getStackTraceString());
            system.debug('error msg==='+e.getMessage());
            resultFlag= 'false';
        } 
        return resultFlag;
    }  
    //Sajid 06/02/2023 SFDC-229 SFDC+Twilio ACCC Button on Lightning Page for text reps (ME# 331277)
    @AuraEnabled
    public static String sendAnEmail(id recordId)
    {
        System.debug('recordId:: '+recordId);
        
        Case c = [select id, Booth__c from Case where id =: recordId];
        if(c.Booth__c != null)
        {
            Oracle_Show_Booth__c showBooth = [select id, BOOTH_ID__c from Oracle_Show_Booth__c where id =: c.Booth__c];
            
            if(showBooth != null && showBooth.BOOTH_ID__c != null)
            {
                String result = sendMinimalPaymentMail(c.Id);
                return result;
            }
            else
            {
                return 'Please enter the Valid Booth ID';
            }
        }
        return 'Please enter the Valid Booth ID';
    }      
}