unpackaged/main/default/objects/CA_Personalized_Object_Setting__c/CA_Personalized_Object_Setting__c.object-meta.xml
<CustomObject>
    <label>CA Personalized Object Setting</label>
    <nameField>
        <displayFormat>CA_POS-{0000}</displayFormat>
        <label>POS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Personalized Object Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pharma_Template__mdt/Pharma_Template__mdt.object-meta.xml
<CustomObject>
    <label>Merck - Product Hierarchy</label>
    <pluralLabel>Merck - Product Hierarchies</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Pharma_Template__mdt/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pharma_Template__mdt/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pharma_Template__mdt/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <label>Therapeutic Area</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CA_ExhibitApexController.cls
public class CA_ExhibitApexController {
    
    @AuraEnabled
    public static CA_Personalized_Object_Setting__c getSettingObjectList(string objectName){
        User currentUser = [select id,Name,profile.name,IsPortalEnabled FROM User Where id =: userInfo.getUserId()];
        String profileName=currentUser.profile.name;
        CA_Personalized_Object_Setting__c sDebug = CA_ApexUtils.getHomeTableSettings(profileName, objectName, true);
        system.debug('-------' + sDebug);
        return sDebug;
    }
    
    @AuraEnabled
    public static string getParntObjName(string recordId){
        return CA_RecordBannerApexController.getParntObjName(recordId);
    }
    
    @AuraEnabled
    public static Pharma_Template__mdt getPickListValues(String productName){
        Pharma_Template__mdt therapeuticAndBusinessUnit;
        User currentUser = [select id,Name,profile.name,IsPortalEnabled FROM User Where id =: userInfo.getUserId()];
        String profileName=currentUser.profile.name;
        If (Test.isRunningTest()){profileName='GC Merck';}
        if (profileName=='GC Merck'){
            therapeuticAndBusinessUnit = [SELECT Business_Unit__c,Therapeutic_Area__c FROM Pharma_Template__mdt WHERE Product_Name__c =: productName AND DeveloperName like 'Merck%' LIMIT 1]; 
        }
        else{
        	therapeuticAndBusinessUnit = [SELECT Business_Unit__c,Therapeutic_Area__c FROM Pharma_Template__mdt WHERE Product_Name__c =: productName AND (NOT DeveloperName like 'Merck%') LIMIT 1]; 
        }
            return therapeuticAndBusinessUnit;
    }
}